### DISCUSSION TITLE
Generate non-interactive user kubeconfig for a remote Kubernetes cluster

### DISCUSSION THREAD

**Discussion by andrea-armstrong** [gravitational/teleport#10404] [Q&A]
I've set up a Teleport cluster using the TLS routing method that has a Kubernetes cluster connected remotely via the kube-teleport-agent deployment. I can connect successfully as an SSO user to this cluster.

However, I am also trying to create a kubeconfig for a non-interactive user to be able to connect to the remote cluster as well, but have been unable to successfully accomplish this following the [CI/CD](https://goteleport.com/docs/kubernetes-access/guides/cicd/) documentation. Even when I provide the kube-cluster-name & proxy flags, the generated kubeconfig does not seem to point to the correct cluster. I'm looking for some guidance on what I may be missing, or if this isn't possible with this setup.

Teleport cluster config:
```
version: v2
teleport:
  data_dir: /var/lib/teleport
  pid_file: /run/teleport.pid
  diag_addr: 0.0.0.0:3000
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  storage:
    type: firestore
    collection_name: teleport-cluster-data
    credentials_path: /var/lib/teleport/gcp_credentials.json
    project_id: <redacted>
    audit_events_uri: 'firestore://<redacted>?projectID=<redacted>&credentialsPath=/var/lib/teleport/gcp_credentials.json'
    audit_sessions_uri: 'gs://<redacted>?projectID=<redacted>&credentialsPath=/var/lib/teleport/gcp_credentials.json'
auth_service:
  enabled: yes
  public_addr: ["teleport.redacted.ai:443"]
  proxy_listener_mode: multiplex
ssh_service:
  enabled: true
  public_addr: ["teleport.redacted.ai:443"]
proxy_service:
  enabled: true
  public_addr: ["teleport.redacted.ai:443"]
  web_listen_addr: "0.0.0.0:443"
  acme:
    enabled: true
    email: test@redacted.ai
```

Teleport-agent config in Kubernetes cluster:
```
teleport:
  auth_token: "/etc/teleport-secrets/auth-token"
  auth_servers: ["teleport.<redacted>.ai:443"]
  log:
    severity: INFO
    output: stderr
    format:
      output: text
      extra_fields: ["timestamp","level","component","caller"]

kubernetes_service:
  enabled: true
  kube_cluster_name: staging
  labels:
    env: staging

app_service:
  enabled: false

db_service:
  enabled: false

auth_service:
  enabled: false
ssh_service:
  enabled: false
proxy_service:
  enabled: false
```

Command I am trying to run to generate the kubeconfig on the teleport server:
`tctl auth sign -o kubeconfig --format kubernetes --kube-cluster-name staging --user github-actions --proxy teleport.<redacted>.ai:443`

Then the generated kubeconfig is as follows:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: teleport.redacted.ai:443
  name: teleport-server-group-32q7
contexts:
- context:
    cluster: teleport-server-group-32q7
    user: teleport-server-group-32q7
  name: teleport-server-group-32q7
current-context: teleport-server-group-32q7
kind: Config
preferences: {}
users:
- name: teleport-server-group-32q7
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
```

When I try to use that kubeconfig through kubectl on my local machine, I eventually get this error:
```
kubectl --kubeconfig github_actions_kubeconfig get deployments
Unable to connect to the server: EOF
```

I don't see any logs at the server or kube-agent levels related to this.

User and role config:
```
kind: role
metadata:
  id: 1645028518678542031
  name: kube-github-actions
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_groups:
    - github-actions
    kubernetes_labels:
      env:
      - staging
      - prod
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
---
kind: user
metadata:
  id: 1645028721016262072
  name: github-actions
spec:
  created_by:
    time: "2022-02-16T16:25:20.955578204Z"
    user:
      name: 5d8ed733-df8d-43e8-a4e7-bdccdfa472e5.teleport-server-group-32q7
  expires: "0001-01-01T00:00:00Z"
  roles:
  - kube-github-actions
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
    recovery_attempt_lock_expires: "0001-01-01T00:00:00Z"
  traits:
    kubernetes_groups:
    - ""
    kubernetes_users:
    - ""
    logins: null
    windows_logins: null
version: v2

```
