### DISCUSSION TITLE
Connecting to AWS RDS on secure connection gave error

### DISCUSSION THREAD

**Discussion by lkwjohn** [gravitational/teleport#10692] [Q&A] [answered]
I've been trying to connect to me RDS database which have it's connectivity secure by rds-ca-2019, but was facing error when I tried to connect from the client side `tsh db connect xxx`, the teleport was able to pickup the RDS database via the teleport.yaml config.

```
ERROR 1105 (HY000): x509: certificate relies on legacy Common Name field, use SANs instead
```

teleport.yaml
```
db_service:
  enabled: "yes"
  databases:
  - name: "xxx"
    description: "xxx description"
    protocol: "mysql"
    uri: "xxxx:3306"
    aws:
     region: "xxxx"
```

Guessing it's could be that the rds-ca-2019 is kinda of a old structure, I also tried to include the tls field in the teleport.yaml, however, after added tls as a insecure mode, I encountered the following error when I run `teleport start`, how can I resolve this?

```
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 55: field tls not found in type config.Database
```

```
db_service:
  enabled: "yes"
  databases:
  - name: "xxx"
    description: "xxx description"
    protocol: "mysql"
    uri: "xxxx:3306"
    tls:
     mode: insecure
    aws:
     region: "xxxx"
```
