### DISCUSSION TITLE
Add Server Manually Shows Wrong(?) Port

### DISCUSSION THREAD

**Discussion by Ducky6944** [gravitational/teleport#11173] [Q&A] [answered]
I've pretty much just take the example config It shows the auth service listening on port 3025.

```YAML
version: v2
teleport:
  nodename: my_node
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
```

When I got to `Add Server` I get the command below, which dosen't work. Changing the port to 3025, does however. 

`teleport start --roles=node --token=SOME_TOKEN --auth-server=myserver.lan:3080 `

Any help would be greatly appreciated.
