### DISCUSSION TITLE
Azure Tag Syncing

### DISCUSSION THREAD

**Discussion by scottpgallagher** [gravitational/teleport#11250] [Show and tell]
Syncing tags with Azure is possible with Teleport. There are a few ways to achieve this so I'll cover them in this show and tell. 

Option 1: Using Curl 
Prerequisites: `curl` & `jq`

First you'll need to setup a script that can be used in the teleport.yaml file:
```sh
#!/usr/bin/sh
curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq -r ".compute.tagsList[].value"
```
Save this script; for example 'tag-sync.sh'

Then in the teleport.yaml file you can call it on the node:
```yaml
ssh_service:
  enabled: yes
  commands:
    - name: owner
      command: ["/usr/bin/sh", "-c", "/home/azureuser/tag-sync.sh"]
      period: 1h
```

In this case the tag were going to sync is the owner tag so we give it that name and the curl command will pull the value for that into the teleport system. 

Option 2 & 3: Using Azure CLI

It's also possible to use the Azure CLI to achieve this result as well; using this method you can do it by setting up what Azure calls a service principal. Service principals can be a username/password or a certificate (see more here: https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli). 

This method is a little more complex due to the nature that you first need to get credentials using your local system, then get them onto the system running in Azure. 

For example the steps I used to achieve this (I did the username/password method) to test this does work. 

Step 1:
Install azure cli (on mac you can do `brew install az`)

Step 2: 
```bash
$ az login
```

Step 3:
Now we create that service principal (note: these steps are for a username/password; if you want a PEM file then use the URL above to follow those directions)
$ az ad sp create-for-rbac --role reader --scopes /subscriptions/<subscription id> 
The subscription ID can be found in the Azure web portal

This command will create some output we will need to use on the Azure VM (appID, password, tenantID)

Step 4: 
On the Azure VM we can now login; note since Teleport runs as root this needs to be done as the root user so when the script is run to get the tag it can.
```code
$ az login --service-principal --username appID --password PASSWORD --tenant tenantID
```
You can confirm this works then by doing a `az tag list` which will list tags for all resources in Azure. 

Step 5:
Create the script
```sh
#!/usr/bin/sh
az tag list --resource-id /subscriptions/resourcegroups/{rg}/providers/Microsoft.Compute/virtualMachines/{vmName} | grep <tag name> | cut -d '"' -f 4
```

Step 6:
Reference that script in the teleport.yaml file
```yaml
ssh_service:
  enabled: yes
  commands:
      - name: owner
      command: ["/usr/bin/sh", "-c", "/home/azureuser/synctags.sh"]
      period: 1h
```
