### DISCUSSION TITLE
Struggling to get docker deployment working.

### DISCUSSION THREAD

**Discussion by JeremiahSecrist** [gravitational/teleport#11276] [Q&A] [answered]
# system overview information.
Currently running inside a docker container on an ubuntu server.

## Configuration
teleport yaml
```yaml
version: v2
teleport:
  nodename: localhost
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name:  [redacted domain]
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: [redacted domain]:443
  acme:
    enabled: "yes"
    email: [redacted email]
   ```
Docker config:
```yaml
- name: Deploy teleport.
  community.docker.docker_container:
    name: teleport
    image: quay.io/gravitational/teleport:9
    volumes:
      - "~/teleport/config:/etc/teleport"
      - "~/teleport/data:/var/lib/teleport"
    ports:
      - 3022:3022
      - 3023:3023
      - 3025:3025
      - 3080:3080
      - 443:443
 ```
## Logs:
```
2022-03-20T15:37:27Z WARN [ALPN:PROX] Failed to handle client connection: acme can't get a cert for domain 6c6f63616c686f7374.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: [redacted domain] alpnproxy/proxy.go:288
```
```
2022-03-20T11:37:27-04:00 INFO [PROC:1]    Connecting to the cluster localhost with TLS client certificate. service/connect.go:160
2022-03-20T11:37:28-04:00 ERRO [PROC:1]    Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.. service/connect.go:81
```

## Issue
I am unable to add clients to teleport. I am not sure where I went wrong in the config and I am open to suggestions.
the web server is working but adding new connections is non fucntional.
