### DISCUSSION TITLE
How do I set logins for existing users ?

### DISCUSSION THREAD

**Discussion by PavelNiedoba** [gravitational/teleport#11820] [Q&A] [answered]
I have existing user "John" which I created using gui. "John" has no logins (there's no gui field for it). How do I set login "john" for user "John" then?

I found this issue: https://github.com/gravitational/teleport/issues/9790 which clearly states that it's not possible and it's not even priority so tried to do it via command line using tctl. I'm stuck here too. Tried different variation of

```
root@vm-teleport:~# tctl users update pavel
ERROR: missing name
```

but have no idea what `name` the ERROR is referring to

**Comment by scottpgallagher** [comment]
Sounds like you are referring to the users login to ssh systems?

If that is the case you need to specify the logins "John" can login to those systems as. In the role attached to the user "John" you will need something like this (replacing ubuntu/root with the logins "John" can login with)

spec:
  allow:
    logins:
    - ubuntu
    - root

**Reply by simplecoin-eu** [reply]
I assume I don't need to create new role for each user because I can create users with logins from command line. It should be possible to change logins later. Did you read whole question? Including the link?

**Comment by webvictim** [comment, marked as answer]
- `tctl get user/pavel > pavel.yaml`
- Edit the `pavel.yaml` file and change the `logins` section to include the logins you want
- `tctl create -f pavel.yaml`

**Reply by KasperSkytte** [reply]
Maybe this should be included in the docs?

**Reply by simplecoin-eu** [reply]
maybe there can be gui for this, there is yaml editor already used in some places

**Reply by webvictim** [reply]
Please do feel free to raise a feature request, or a PR to add it to to the docs.

**Reply by codevalve** [reply]
Thank you! This worked for me.

**Comment by zmb3** [comment]
Note that `tctl users update --set-logins` also works.

**Comment by myosotisgit** [comment]
> Note that `tctl users update --set-logins` also works.

If you look at the included help from tctl the `--set-logins` options says:

 _--set-logins             List of allowed SSH logins for the user, replaces
                               current logins_

So be SURE to INCLUDE all the logins that were assigned originally PLUS the new ones. Otherwise it will instantly overwrite existing ones!

>edit 
And, in my case, i needed to re-login to the webportal to view the changes made by --set-logins. Reloading the browser did not work for me!

**Comment by webvictim** [comment]
Related issue: https://github.com/gravitational/teleport/issues/9790

**Comment by behnambm** [comment]
## With Full example

When the user is created from web UI it does not include `traits` section when you get the info. If there is no `traits` section, then just add it.


```
tctl get user/joe > joe.yaml
```

```
kind: user
metadata:
  id: 1705123
  name: joe
spec:
  created_by:
    time: "2024-01-06T13:22:01"
    user:
      name: a6c354-ab97-4d8b-8a7b-bf271c
  expires: "0001-01-01T00:00:00Z"
  roles:
  - access
  - editor
  traits:
     .........
    db_users: null
    logins:
    - root        <-------- EDIT
    - ubuntu      <-------- EDIT
    windows_logins: null
version: v2

```


```
tctl create -f joe.yaml
```
