### DISCUSSION TITLE
How to allow any login for a user

### DISCUSSION THREAD

**Discussion by sgohl** [gravitational/teleport#11893] [Q&A] [answered]
The specific use-case is: I want to define a role for a helpdesk team to support Developers on their virtual machines, who of course have their personal name as login, hence the allowed logins can not be defined explicitely.
allowing `root` for the supporters is not intended.

the role I came up with so far:
```
kind: role
metadata:
  name: helper
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    node_labels:
      type: dev
  deny:
    logins:
    - root
version: v5
```

what I certainly want is:
```
allow:
    logins:
    - '{{internal.logins}}'
    - '*'
```

which understandably leads to the error message

> wildcard matcher is not allowed in logins

what I hope for is that there is some other kind of variable like this `'{{internal.logins}}'` (which I don't find any explanation for) , but for "any login that is available on the target machine"

As a matter of fact, it would be absolutely sufficient if we'd be able to provide a `uid` instead of a username, because every user has the same `uid` of `1000`, but that doesn't work either:

```
allow:
    logins:
    - '{{internal.logins}}'
    - '1000'
```

**Comment by webvictim** [comment, marked as answer]
Unfortunately, Teleport's RBAC checks require that you enumerate all individual logins that you might want to use. This is essentially a security feature to avoid inadvertently granting more access than intended.

**Reply by ethan-gallant** [reply]
What if your company has too many usernames to fit into the multiplexer header, it crashes Teleport auth requests and subsequently locks everyone out?

Asking for a friend 😉

**Reply by webvictim** [reply]
There are a few ways to solve this problem!

1) Set each user's username as a claim (OIDC) or attribute (SAML) in your SSO provider instead, then pass that username through to the role using the `{{external.username}}` nomenclature instead:

```yaml
spec:
  allow:
    logins:
    - "{{external.username}}"
```

2) If you use individual users, set each user's logins as a trait on each the user themselves:

```
tctl users update gus --set-logins gus,ubuntu,ec2-user
```

...then reference that in the role instead:

```yaml
spec:
  allow:
    logins:
    - "{{internal.logins}}"
```

This will cause the role to be individually evaluated for each user rather than having a large list which causes problems :)

Docs reference here: https://goteleport.com/docs/reference/access-controls/roles/#traits
