### DISCUSSION TITLE
Hiding sections from Teleport's web UI

### DISCUSSION THREAD

**Discussion by webvictim** [gravitational/teleport#11920] [Show and tell]
Normally, a Teleport cluster's web UI will show all 5 protocols in its left-hand navigation bar:

![image](https://user-images.githubusercontent.com/897821/163243845-658ef583-d9f1-4104-b645-399f2d534e37.png)

It may be desirable in some circumstances to hide certain sections - for example, a user may only have Application access and no other protocols available, and showing other blank tabs may confuse them.

You can hide one or more protocols from the left-hand navigation bar by adding a `deny` section like this to any Teleport role:

```yaml
kind: role
metadata:
  name: only-show-apps
spec:
  allow: {}
  deny:
    rules:
    - resources:
      - node
      - kube_server
      - db_server
      - windows_desktop
      verbs:
      - list
```

Granting this role to a user will remove these sections. When they next log into Teleport, they will only see the Applications section. It will also be the default view shown when they log in:

![image](https://user-images.githubusercontent.com/897821/163245561-c4f1d334-56ad-4b8b-ae50-55d160e52448.png)

Here's the full list of protocol -> resource name mappings:

Servers: `node` (only supported in Teleport 9.1.0+)
Applications: `app_server`
Kubernetes: `kube_server` (or `kube_service` prior to Teleport 10)
Databases: `db_server`
Desktops: `windows_desktop`

It's not currently possible to completely hide the "Activity" or "Clusters" sections. We are looking at adding this support to the UI in future.
