### DISCUSSION TITLE
Struggling to properly deploy this behind a reverse Proxy

### DISCUSSION THREAD

**Discussion by Ducky6944** [gravitational/teleport#12028] [Q&A]
This app seems like it would solve a lot of problems for me but I am struggling to set it up properly. 

Following the Getting Started Guide. I generate the default config and build a compose file.

<details>
<summary>teleport.yaml</summary>

```YAML
version: v2
teleport:
  nodename: localhost
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
```
</details>

<details>
<summary>docker-compose.yml</summary>

```YAML
services:
  teleport:
    container_name: teleport
    image: quay.io/gravitational/teleport:9
    volumes:
      - /docker_storage/teleport/config:/etc/teleport
      - /docker_storage/teleport/data:/var/lib/teleport
    ports:
      - 10022:3023
      - 10023:3025
      - 10024:3080
```
</details>

I then create a default user with 
`sudo docker exec teleport tctl users add teleport_admin --roles=editor,access --logins=root,ubuntu,ec2-user`.

I create an entry in traefiks file provider to proxy to `localhost:3080`.

<details>
<summary>traefik: config.yml</summary>

```YAML
http:
  routers:
    teleport:
      entryPoints:
        - "web"
        - "websecure"
      rule: "Host(`teleport.local.my.domain`)"
      middlewares:
        - default-headers
      tls: {}
      service: teleport

  services:
    teleport:
      loadBalancer:
        servers:
          - url: "https://10.10.10.3:10024"
        passHostHeader: true

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
```
</details>

I go to `teleport.local.my.domain/path/to/invite` which has a valid wild card cert. Everything looks good I sign up. I then add a server `user@ip:port`. It returns a automatic script. `sudo bash -c "$(curl -fsSL https://teleport.local.my.domain/scripts/A_TOKEN/install-node.sh)"` If I go to that URL I see.

```BASH
#!/bin/sh
echo -e "An error has occurred. \nThe token may be expired or invalid. \nPlease check log for further details."
exit 1
```
I try to use the internal IP instead of the domain and it returns the same thing. 

I'm assume this has something to do with my proxying but I'm not sure how to resolve it.

Any help would be appreciated. I tried looking through the teleport.yaml reference, but I don't even know what I'm looking for networking isn't a strong suit of mine. 

All the best.
