### DISCUSSION TITLE
Example JumpCloud SSO into your Teleport Cluster

### DISCUSSION THREAD

**Discussion by campanamarco** [gravitational/teleport#12047] [Show and tell]
Here is an example for adding a JumpCloud SSO integration that can be used to authorize you into your Teleport Cluster with assigned roles (Teleport RBAC) to define access for users accessing various protocols. 

This example shows a JumpCloud Auth Connector with Teleport Enterprise, connecting to your Teleport Cluster via ACS Callback URI in a yaml format.

### **Prerequisites:** 
- Teleport Enterprise Cluster with Editor Privileges 
- JumpCloud Console Account
- JumpCloud User Group with Assigned Test User

### **Recommendations:** 
- Since this is a SAML Connector, review our [Okta SAML Connector Docs](https://goteleport.com/docs/enterprise/sso/okta/) to prepare

### **Step 1: Enable default SAML authentication in your config file teleport.yaml**
```
auth_service:
  authentication:
    type: saml
```
### **Step 2: Create new JumpCloud SSO Application**
_Choose 'Custom SAML Application'_

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/93137855/163870279-455ea57e-9272-4e0e-91b2-299a3a224e45.png">

_Add your Teleport ACS URI to both Entity IDs and ACS URL_

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/93137855/163870169-64fe13aa-7f01-4868-b149-9684279975a2.png">

_Copy your IDP URL and Set User Attribute Mapping to 'username' and 'email'_

<img width="615" alt="image" src="https://user-images.githubusercontent.com/93137855/163870456-8f8d776f-5703-4d2d-9d75-edb74e988e77.png">

### **Step 3: Create Auth Connector in Teleport Web UI**

```
`kind: saml
metadata:
  name: JumpCloud
spec:
  acs: https://example.teleport.com:443/v1/webapi/saml/acs
  attributes_to_roles:
  - name: groups
    roles:
    - editor
    - access
    value: TeleportDev
  audience: https://example.teleport.com:443/v1/webapi/saml/acs
  cert: ""
  display: JumpCloud SSO
  entity_descriptor: |
  entity_descriptor_url: ""
  issuer: https://example.teleport.com:443/v1/webapi/saml/acs
  # you can also use 'provider: jumpcloud' in Teleport 9.1.1 and above
  provider: adfs
  service_provider_issuer: JumpCloud
  signing_key_pair:
    cert: xxxx
  sso: IDP URL 
version: v2`
```
NOTE: Paste your IDP URL in 'sso:' and ensure 'Value' matches your User Group name in JumpCloud

### **Step 4: Export Metadata and paste XML File into Teleport JumpCloud Auth Connector under 'entity_descriptor'**

<img width="636" alt="image" src="https://user-images.githubusercontent.com/93137855/163871413-543fa6ea-411f-425b-bae8-7204ea11f3e5.png">

### **Step 5: Refresh Teleport Cluster and Test new JumpCloud SSO Integration!**

<img width="662" alt="image" src="https://user-images.githubusercontent.com/93137855/163871533-a213888c-df72-49b8-b3fb-db9382042a4a.png">
