### DISCUSSION TITLE
Providing Teleport Desktop access to multiple Windows domains with multiple agents

### DISCUSSION THREAD

**Discussion by webvictim** [gravitational/teleport#12180] [Show and tell]
Edit 2026-03-13: Updated to use `teleport-update enable --install-suffix ...` instead of the previous manual unit file method.

---

For Windows desktops, Teleport currently has a one agent -> one domain model. If you have multiple Windows domains that you'd like to use with Teleport Desktop access, you will need to run multiple Teleport agents to provide access to each of these domains.

To avoid excess cost, it's possible to run multiple Teleport agents on one VM or physical server. In this example, we'll be provisioning access to two domains:
- `example.com` (`EXAMPLE` in NetBIOS terms)
- `test.com` (`TEST` in NetBIOS terms)

## Teleport config files

Each agent needs its own config file. When you run `teleport-update enable` with `--install-suffix`, it automatically uses a config file named after the suffix — so you don't need to manually manage separate data directories or write your own systemd unit files.

### `example.com`

Config file: `/etc/teleport_example.yaml` (note: this must match the format `/etc/teleport_<suffix>.yaml`)
```yaml
version: v3
teleport:
  # this must match the format /var/lib/teleport_<suffix>
  data_dir: /var/lib/teleport_example
  log:
    output: stderr
    severity: INFO
  # use your Teleport proxy hostname here to establish a reverse tunnel
  proxy_server: example.teleportdemo.com:443
  # you'll need a join token for this cluster, created with `tctl tokens add --type=windows_desktop` or similar
  join_params:
    method: token
    token_name: 9bb4b5ebb0785d1c26e0e7e271d408b1
auth_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: false
windows_desktop_service:
  enabled: true
  ldap:
    # Address of the Domain Controller for LDAP connections. Usually, this
    # address will use port 636, like: domain-controller.example.com:636.
    addr: "WIN-QD644VEFMV7.example.com:636"
    # Active Directory domain name you are connecting to, like: domain-controller.example.com.
    domain: "example.com"
    # LDAP username for authentication. This will be the user logon name you chose for the service
    # account User in step 1 (svc-teleport). This username must include the domain NetBIOS name.
    #
    # For example, if your domain is "example.com", the NetBIOS name for it is
    # likely "EXAMPLE". When connecting as the "svc-teleport" user, you should
    # use the format: "EXAMPLE\svc-teleport".
    #
    # If you are unsure of your NetBIOS name, you can find it by opening a PowerShell command prompt
    # and running:
    # ```
    # (Get-ADDomain).NetBIOSName
    # ```
    username: 'EXAMPLE\svc-teleport'
    insecure_skip_verify: false
    # DER encoded certificate.
    # This should be the path to the certificate exported in step 4 of the Windows setup docs.
    der_ca_file: /etc/teleport/teleport-cluster-ca.cer
  discovery:
    # The wildcard '*' character tells Teleport to discover all the hosts in
    # the Active Directory Domain. To refine the search, specify a custom DN.
    base_dn: '*'
```

### `test.com`

Config file: `/etc/teleport_test.yaml` (note: this must match the format `/etc/teleport_<suffix>.yaml`)
```yaml
version: v3
teleport:
  # this must match the format /var/lib/teleport_<suffix>
  data_dir: /var/lib/teleport_test
  log:
    output: stderr
    severity: INFO
  proxy_server: example.teleportdemo.com:443
  join_params:
    method: token
    token_name: 9bb4b5ebb0785d1c26e0e7e271d408b1
auth_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: false
windows_desktop_service:
  enabled: true
  ldap:
    addr: "WIN-OE649VFEMA4.test.com:636"
    domain: "test.com"
    username: 'TEST\svc-teleport'
    insecure_skip_verify: false
    der_ca_file: /etc/teleport/teleport-cluster-ca.cer
  discovery:
    base_dn: '*'
```

## Installing and enabling the agents

Use `teleport-update` with `--install-suffix` to set up each agent as an isolated installation. Each suffix gets its own binaries, data directory (`/var/lib/teleport_<suffix>`), and systemd service — no manual unit file authoring required.

### `example.com`

```console
sudo teleport-update --install-suffix example enable
sudo systemctl enable teleport_example --now
```

### `test.com`

```console
sudo teleport-update --install-suffix test enable
sudo systemctl enable teleport_test --now
```

## Managing the agents

Check the status of each agent:
```console
sudo systemctl status teleport_example
sudo systemctl status teleport_test
```

Check logs:
```console
sudo journalctl -u teleport_example
sudo journalctl -u teleport_test
```

Check the updater status for a specific installation:
```console
teleport-update --install-suffix example status
teleport-update --install-suffix test status
```

Each installation is fully independent — updating or restarting one agent has no effect on the other. Managed updates will keep each agent on the cluster-advertised version automatically.

You can run as many agents as needed by following this model — adding a config file and running `teleport-update enable` with a new suffix for each domain.
