### DISCUSSION TITLE
Edit / Add labels

### DISCUSSION THREAD

**Discussion by r-kjha** [gravitational/teleport#12198] [Q&A] [answered]
How do I edit labels?
![image](https://user-images.githubusercontent.com/87710356/164956865-1f4ef789-963d-4ffc-9b0e-557fcc0cdebd.png)

How do I add lables?
![image](https://user-images.githubusercontent.com/87710356/164956892-fb965df6-0ceb-4f25-95b9-cb59e6e54230.png)

All the new servers are added using the automatic installer script.

**Comment by webvictim** [comment, marked as answer]
Edit the `ssh_service` section of `/etc/teleport.yaml`, then restart Teleport (usually `sudo systemctl restart teleport`)

```yaml
ssh_service:
  enabled: true
  labels:
    env: example
    hostname: teleport
```
