### DISCUSSION TITLE
Keep users logged in to the web application

### DISCUSSION THREAD

**Discussion by maximelebastard** [gravitational/teleport#12203] [Q&A] [answered]
Hi,

When users log in to the teleport webapp - they're getting signed out in the next few hours.
It is annoying as they have to always keep entering their MFA code.

Is there any way to make the session on the webapp last a few days ?

**Comment by webvictim** [comment, marked as answer]
What's the `max_session_ttl` for the user's roles set to? Teleport will use the lowest value.

By default, web sessions will stay signed in for as long as they can. Things like clock drift or keeping the tabs in the background can sometimes prevent the token refresh from happening, however.

**Comment by maximelebastard** [comment]
Thank you, I had a role with a 30h ttl which matches the behavior of Teleport

```
kind: role
metadata:
  name: myrole
spec:
  allow:
    app_labels:
     myapps: '*'
  deny: {}
  options:
    cert_format: standard
    desktop_clipboard: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v5
```
