### DISCUSSION TITLE
Connecting to RDS in another AWS account?

### DISCUSSION THREAD

**Discussion by wtphilbrook** [gravitational/teleport#12248] [Q&A] [answered]
Hey ya'll - 

I've got a Teleport cluster setup and running smooth in AWS. I'm hoping to get it linked up with a handful of RDS and Aurora instances setup in a handful of different AWS accounts. I've tried bridging permissions using an IAM role as well as setting up an IAM user on a test account with permissions to access the database, but it doesn't seem to click.

So far, my most successful setup has been: 
- IAM user on `test AWS account`
- Access Key + Secret Key AWS credentials setup on every Teleport main node (proxy + auth)
- Run a `teleport db start ...` on one node, which kicks off auto-discovery (??)
- Databases in `test AWS account` are now visible on Teleport and using `tctl db ls`

Once all that is done, I'm able to see databases in Teleport but unable to connect to them (`ERROR 1105 (HY000): access denied`). I've confirmed my database user has the right permissions, I've attempted to kickstart the database auto-discovery with the RDS certificate, and I've tried connecting via mysql using the output of `tsh db config --format=cmd`.

I'm pretty sure I'm just missing a step or forgetting something silly.

Here's my main node config for reference:
```
teleport:
  storage:
    type: dynamodb
    region: us-east-2
    table_name: teleport
    audit_events_uri:  ['dynamodb://teleport_events', 'file:///var/lib/teleport/audit/events', 'stdout://']
    audit_sessions_uri: s3://[redacted]/records
    audit_retention_period: 1y
  nodename: [redacted]
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: [redacted]
  public_addr: [redacted]
ssh_service:
  enabled: "yes"
  labels:
    teleport_main: true
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  public_addr: [redacted]:443
  mysql_listen_addr: "0.0.0.0:3036"
  https_keypairs:
    - key_file: [redacted].key
      cert_file: [redacted].crt
  acme:
    enabled: "no"
    email: [redacted]
db_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
  aws:
  - types: ["rds"]
    regions: ["us-east-1", "us-east-2"]
    tags:
      "*": "*"
```

**Comment by webvictim** [comment, marked as answer]
EDIT: Since this comment was written, Teleport has added native support for AWS IAM role assumption which makes this sort of use case much easier.

The documentation for this feature is here: https://goteleport.com/docs/database-access/guides/aws-cross-account/

Here's an example config:

```yaml
db_service:
  enabled: "yes"
  aws:
    - types: ["rds"]
      regions: ["us-west-1"]
      assume_role_arn: "arn:aws:iam::222222222222:role/example-role"
      external_id: "example-external-id"
    - types: ["rds"]
      regions: ["us-east-2"]
      assume_role_arn: "arn:aws:iam::111111111111:role/example-role-two"
      external_id: "example-external-id"
```

Note that the same role used to discover the databases will automatically be used for access.

~~To add databases from multiple different AWS accounts, you'll likely need to run a separate Teleport agent instance inside each individual account with an appropriate IAM role list/add the databases to Teleport. This also often helps to circumvent restrictions on cross-VPC/subnet traffic too.~~

~~Essentially you run an agent in each account with a config a bit like this:~~

```
# no longer needed, see examples above
teleport:
  auth_token: token # replace with token from "tctl tokens add --type=db"
  auth_servers: ['teleport.example.com:443'] # replace with your proxy hostname/port
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
db_service:
  enabled: "yes"
  aws:
  - types: ["rds"]
    regions: ["us-east-1", "us-east-2"]
    tags:
      "*": "*"
```

~~With regard to your `access denied` issue, it seems like maybe you don't have appropriate database users/names configured inside any of the roles that your logged-in Teleport user has. Check output of `tsh status` and then see what's set for `spec.allow.db_names` and `spec.allow.db_users` inside each of those roles. The logs on the Teleport auth/proxy server may also help.~~
