### DISCUSSION TITLE
Help with setting up teleport aws console access

### DISCUSSION THREAD

**Discussion by AritraWork97** [gravitational/teleport#12290] [Q&A]
Hi everyone, 

We are using the latest teleport version. We are trying to setup aws console access in teleport. We have created the necessary roles and attached required security permissions to our ec2 instance. When I try to login to a role, the drop down menu on the right hand side is showing as no roles found. 

Any help will be appreciated.

**Comment by philip-teleport** [comment]
Have you created a Teleport role with the 'aws_role_arns' field listing all IAM role ARNs that can be assumed by a user?

See documentation [here](https://goteleport.com/docs/application-access/guides/aws-console/).

```
kind: role
version: v5
metadata:
  name: aws-console-access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - arn:aws:iam::1234567890:role/ExamplePowerUser
    - arn:aws:iam::1234567890:role/ExampleReadOnlyAccess
```
