### DISCUSSION TITLE
Teleport Applications behind nginx causes infinite redirection loops

### DISCUSSION THREAD

**Discussion by ColaIan** [gravitational/teleport#12349] [Q&A]
## Current setup
Teleport proxy `web_listen_addr` on `0.0.0.0:3080`, Nginx redirects `tele.<>:443` and `*.tele.<>:443` to `0.0.0.0:3080`

## Scenarios
If I set proxy_service.public_addr to `tele.<>` the application urls will become `something.tele.<>:3080`, which I do not want the :3080 to show up

If I set proxy_service.public_addr to `tele.<>:443`, when I try to access `something.tele.<>:443`, it loops between `tele.<>:443/web/launch...` and `something.tele.<>:443/x-teleport-auth...`, which doesn't seem to be intended

**Comment by webvictim** [comment]
The latter use case should be supported - I use this exact setup myself with Teleport listening on :3080, Caddy listening on :443 with a redirect/reverse proxy and `proxy.service.public_addr: teleport.example.com:443`. It works fine.

Can you share your `/etc/teleport.yaml` and your nginx config?

**Reply by ColaIan** [reply]
Teleport config:
```yml
version: v2
teleport:
  nodename: vmi743413
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
  #auth_servers:
  #- tele.pydrox.com:3025
app_service:
    enabled: yes
    # Teleport provides a small debug app that can be used to make sure application
    # access is working correctly. It'll output JWTs so it can be useful
    # when extending your application.
    debug_app: true
    # This section contains definitions of all applications proxied by this
    # service. It can contain multiple items.
    apps:
      # Name of the application. Used for identification purposes.
    - name: "mm"
      # URI and port the application is available at.
      uri: "http://127.0.0.1:85"
      # Optional application public address to override.
      # public_addr: "mail.tele.pydrox.com"
      # Optional static labels to assign to the app. Used in RBAC.
      labels:
        env: "prod"
      # Optional dynamic labels to assign to the app. Used in RBAC.
      commands:
      - name: "os"
        command: ["/usr/bin/uname"]
        period: "5s"
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: tele.pydrox.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: prod
    provider: contabo
    region: us
    group: pydrox
  commands:
    - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  public_addr: tele.pydrox.com:443
  https_keypairs:
  - key_file: /etc/letsencrypt/live/tele.pydrox.com/privkey.pem
    cert_file: /etc/letsencrypt/live/tele.pydrox.com/fullchain.pem
  acme: {}
```

Nginx config:
```nginx
server {

        # Add root for non-proxy connections
        root /home/www/html/tele.pydrox.com/public;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm;

        server_name tele.pydrox.com *.tele.pydrox.com;

        include /home/www/html/tele.pydrox.com/*.conf;
        client_max_body_size 1024M;

        location / {
                proxy_set_header Host $http_host;
                proxy_pass https://127.0.0.1:3080;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }


    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/tele.pydrox.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/tele.pydrox.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = tele.pydrox.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name tele.pydrox.com *.tele.pydrox.com;

    listen [::]:80;
    listen 80;
    return 404; # managed by Certbot

}
```

With `tele.pydrox.com:443`

https://user-images.githubusercontent.com/43201383/166175221-a02c9dde-af59-4ea3-bd8d-02245c88ea91.mp4


With `tele.pydrox.com`

https://user-images.githubusercontent.com/43201383/166175211-266ebf88-1135-4a15-9fe6-6256b4ae9b68.mp4

**Comment by webvictim** [comment]
I'm far from an nginx expert, but try setting `proxy_redirect off;` inside the ` location / {` block of your top `server` config. My guess would be that nginx is intercepting the redirects from Teleport and incorrectly rewriting them.

**Reply by ColaIan** [reply]
I have just tried and restarted nginx, however nothing have changed, the loop is still there :(

**Reply by ColaIan** [reply]
Another thing is that when I put :443, this shows up in my teleport logs
```
[APP:WEB]   Failed to get session: failed to match applications. app/handler.go:180
 [APP:SERVI] Failed to create remote tunnel: failed to dial: all auth methods failed, conn: <nil>. leaseID:20 target:tele.pydrox.com:443 reversetunnel/agent.go:393
 ```

**Reply by webvictim** [reply]
@ColaIan Do you have any Teleport servers/agents running other than your main one? It seems weird that you're getting an issue with remote tunnels when it looks like you have everything running inside the same process.

What appears in `sudo tctl apps ls` on your auth server?

**Reply by ColaIan** [reply]
> 

I have 2 other ssh only teleport servers, however I have only set up 1 application on my main one (I don't know what the dumper means though, I didn't set it up)
```
root@vmi743413:~# tctl apps ls
Host      Name   Public Address         URI                    Labels            Version 
--------- ------ ---------------------- ---------------------- ----------------- ------- 
vmi743413 dumper dumper.tele.pydrox.com http://127.0.0.1:35197                   9.1.2   
vmi743413 mm     mm.tele.pydrox.com     http://127.0.0.1:85    env=prod,os=Linux 9.1.2
```

**Comment by webvictim** [comment]
Does loading the app through Teleport work on port 443 if you remove nginx from the picture entirely? It seems like getting that functioning as expected before adding the extra layer of nginx would be smart.

Also, what's the reason to use nginx at all here? You have a keypair from Let's Encrypt that Teleport can use to serve TLS itself, so If you just want nginx to rewrite 80 -> 443 you can have it listen on port 80 and then redirect to Teleport listening on 443, rather than having this extra layer of indirection?

**Reply by ColaIan** [reply]
well it might not be obvious but obviously I wouldn't use nginx without a reason xD it is not possible for me to use teleport on 443 as I have over 10 other public web services running on it :( also if I don't set :443, it is back to :3080 which does not have nginx in between anymore, :3080 works, it's an issue only when using with nginx

**Comment by webvictim** [comment]
You might find some useful info here: https://github.com/gravitational/teleport/issues/9799

**Reply by ColaIan** [reply]
Thanks for the info, seems like what I'm trying to do is similar to [abjoseph](https://github.com/abjoseph) but looks like there isn't a solution with using nginx with teleport without having teleport inside a docker container either, but I guess I might as well move my discussion there as well, thanks!

**Comment by sbourdette** [comment]
Same for me

**Reply by sbourdette** [reply]
Any News on this ?

**Reply by webvictim** [reply]
I'm unsure why exactly this is happening here, but it doesn't seem to happen when using Caddy or other reverse proxies. Something about the config being used with nginx seems to be causing the redirect loops.

**Comment by sbourdette** [comment]
My setup is 

CLOUDFLARE <--> NGINX <--> TELEPORT <--> NODE

**teleport.yml :** 

```
teleport:
  nodename: bastion
  data_dir: /var/lib/teleport
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: /var/log/teleport.log
    severity: INFO
  storage:
    type: sqlite
    sync: '0'

# configures the 'auth' server
auth_service:
  enabled: yes
  cluster_name: bastion.example.int
  listen_addr: 0.0.0.0:3025
  public_addr: bastion.example.int:3025
  proxy_listener_mode: multiplex
  keep_alive_interval: 1m
  keep_alive_count_max: 3

# configures the 'proxy' server
proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  web_listen_addr: bastion.example.int:8443
  tunnel_listen_addr: bastion.example.int:8443
  public_addr: bastion.example.int:8443
  https_keypairs:
    - key_file: /etc/pki/tls/private/wildcard_bastion.example.int.key
      cert_file: /etc/pki/tls/certs/wildcard_bastion.example.int.crt

# configures the 'node' server
ssh_service:
  enabled: True
  listen_addr: 0.0.0.0:3022
  labels:
    network : dmz
    service : webservers
  commands:
    - name: distrib
      command:
        - /bin/sh
        - -c
        - cat /etc/os-release | grep '^ID=' | cut -f2 -d'='
      period: 24h0m0s
    - name: chassis
      command:
        - /bin/sh
        - -c
        - hostnamectl status | grep 'Chassis' | cut -f2 -d':' | cut -f2 -d' '
      period: 24h0m0s
    - name: hostname
      command:
        - hostname
      period: 1m0s

app_service:
  enabled: yes
  # Teleport provides a small debug app that can be used to make sure applic$
  # access is working correctly. It'll output JWTs so it can be useful
  # when extending your application.
  debug_app: True
  # This section contains definitions of all applications proxied by this
  # service. It can contain multiple items.
  apps:
    - name: "centreon"
      # URI and Port of Application.
      uri: "https://centreon.example.int"
      # Optionally skip TLS verification. default false
      #insecure_skip_verify: true
      # Optional Public Addr
      public_addr: "centreon.example.com"
```

**nginx Conf :** 

```
server {
    
    listen 443 ssl http2;

    server_name centreon.example.com;

    root /var/www/example.com;

    index index.php index.html index.htm;

    access_log /var/log/nginx/centreon.example.com.access combined;
    error_log /var/log/nginx/centreon.example.com.error error;
   
    
    location / {
        proxy_pass https://bastion.example.int:8443/;
        proxy_http_version                 1.1;
        proxy_cache_bypass                 $http_upgrade;
        include proxy_params;
        # Proxy timeouts
        proxy_connect_timeout              60s;
        proxy_send_timeout                 60s;
        proxy_read_timeout                 60s;
    }
    include snippets/ssl_params.conf;
    include snippets/ssl_cloudflare_wildcard_example.com.conf;
}
```

When I click launch in the webui on my application, I'm redirected to

`https://centreon.example.com/web/launch/bastion.example.int/bastion.example.int/centreon.example.com?state=272155f9b71dbdedbb3ba9baddcfad16`

with a 404 Not found

**Reply by webvictim** [reply]
I think your problem is that you're using a subdomain that isn't served by Teleport - i.e. your app should be available on a subdomain of `bastion.example.int` like `centreon.bastion.example.int` rather than `centreon.example.com`

nginx is receiving that request and forwarding it to Teleport, but Teleport doesn't know how to handle it. Does it work without nginx?

**Reply by sbourdette** [reply]
@webvictim thanks for your reply but in apps configuration I use in apps section  :
      `public_addr: "centreon.example.com"`

So Teleport should be able to resolve.

Am I wrong ?

**Reply by sbourdette** [reply]
I'm unable to use sub sub domain because cloudflare certificate don't allow it in free mode.

**Reply by webvictim** [reply]
You should make sure that nginx is preserving the `Host` header when forwarding to Teleport too. Teleport's app redirection behaviour normally expects that all the redirections and cookies will be handled by Teleport itself, but the nginx layer here seems to be causing confusion.

What's the need to use nginx?

**Reply by sbourdette** [reply]
I have tried without nginx and it's working.
I just had to add a rewrite the location :

```
  apps:
    - name: "centreon"
      # URI and Port of Application.
      uri: "https://centreon.example.int"
      # Optionally skip TLS verification. default false
#      insecure_skip_verify: true
      # Optional Public Addr
      public_addr: "centreon.bastion.example.int"
      rewrite:
        # Rewrite the "Location" header on redirect responses replacing the
        # host with the public address of this application.
        redirect:
          - "centreon.example.int"
```
When I tried with NGINX, I got this error message in Teleport log : 

```
2022-10-24T19:04:19+02:00 [WEB]       WARN http: named cookie not present request:GET /web/login web/apiserver.go:2875
2022-10-24T19:04:19+02:00 [WEB]       DEBU Could not authenticate. error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError missing session cookie
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:2877 github.com/gravitational/teleport/lib/web.(*Handler).AuthenticateRequest
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:409 github.com/gravitational/teleport/lib/web.(*Handler).authenticateWebSession
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:352 github.com/gravitational/teleport/lib/web.NewHandler.func1
	/opt/go/src/net/http/server.go:2084 net/http.HandlerFunc.ServeHTTP
	/tmp/gomodcache/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:222 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	/opt/go/src/net/http/server.go:2916 net/http.serverHandler.ServeHTTP
	/opt/go/src/net/http/server.go:1966 net/http.(*conn).serve
	/opt/go/src/runtime/asm_arm64.s:1263 runtime.goexit
User Message: missing session cookie] web/apiserver.go:354

```

So I have tried to add nginx directive :

```
        proxy_pass_request_headers      on;
        proxy_set_header Cookie $http_cookie;
```

But it's not working.

Any help would be appreciated.
