### DISCUSSION TITLE
Configuring teleport-kube-agent to access CloudSQL MySQL

### DISCUSSION THREAD

**Discussion by stevenGravy** [gravitational/teleport#12381] [Show and tell]
This shows how to configure a Teleport helm deployment into a Kubernetes cluster to connect to a GCP MySQL CloudSQL.

### Prerequisites:
  - Teleport Cluster >=9.1.2
  - Available MySQL CloudSQL instance with allocated users
 
Follow the steps at https://goteleport.com/docs/database-access/guides/mysql-cloudsql/ to collect
  - Private key for Teleport Service account
  - Certificate file for Cloud SQL instance (typically server-ca.pem)
  - GCP Project ID
  - Cloud SQL instance ID
  - Teleport token of `db` type

### Create namespace for agent
```bash
kubectl create ns teleport-agent
```

### Upload the certificate for the instance into secret
```bash
kubectl create secret generic server-ca --from-file=./server-ca.pem -n teleport-agent
```

### Upload JSON private key for service account to access DB.
```bash
# Rename JSON file to service-account.json
kubectl create secret generic google-app-creds --from-file=./service-account.json -n teleport-agent
```

### Create k8sCloudSQL.yaml file 
Update `authToken`, `proxyAddr`, `uri`, `project_id`, and `instance_id`

```yaml
#Token that has at least db type
authToken: <token>
# Proxy address, teleport.example.com:443
proxyAddr: <proxy:port>
roles: db
databases:
- name: gcpmysql
  uri: "<ip of mysql isntance>:3306"
  protocol: "mysql"
  static_labels:
    database: staging
  ca_cert_file: /cloudsql/sam-instance/server-ca.pem
    # GCP-specific configuration when connecting a Cloud SQL instance.
  gcp:
    # GCP project ID.
    project_id: "<project-id>"
    # Cloud SQL instance ID.
    instance_id: "<instance-id>"
extraVolumes:
- name: server-ca
  secret:
    secretName: server-ca
- name: google-app-creds
  secret:
    secretName: google-app-creds
extraVolumeMounts:
- name: server-ca
  mountPath: /cloudsql/cloudsql-instance
- name: google-app-creds
  mountPath: /gcp
extraEnv:
- name: "GOOGLE_APPLICATION_CREDENTIALS"
  value: "/gcp/service-account.json"
```

### Install kube agent

```bash
 helm install teleport-agent teleport/teleport-kube-agent --namespace=teleport-agent -f ./k8sCloudSQL.yaml
```

### Test
Confirm pod started
```bash
kubectl get po -n teleport-agent
NAME                              READY   STATUS    RESTARTS   AGE
teleport-agent-74b74f5c88-k6w8w   1/1     Running   0          70s
```
Check logs
```bash
kubectl logs -n teleport-agent <pod-name>
```

Follow steps from guide to connect via `tsh db connect`.

**Comment by doyelese** [comment]
Suggestions @stevenGravy 

Need to fix mismatched syntax for the `extraVolumeMounts` and the `ca_cert_file` to both be /cloudsql-instance/ instead of `sam-instance`

also replacing ca_cert_file with `tls.ca_cert_file` per this notice 

`ca_cert_file is deprecated, please use tls.ca_cert_file instead for gcpmysql. config/configuration.go:1229`

Final edit looks like:
```yaml
#Token that has at least db type
authToken: <token>
# Proxy address, teleport.example.com:443
proxyAddr: <proxy:port>
roles: db
databases:
- name: gcpmysql
  uri: "<ip of mysql instance>:3306"
  protocol: "mysql"
  static_labels:
    database: staging
  tls:
    ca_cert_file: /cloudsql/cloudsql-instance/server-ca.pem
    # GCP-specific configuration when connecting a Cloud SQL instance.
  gcp:
    # GCP project ID.
    project_id: "<project-id>"
    # Cloud SQL instance ID.
    instance_id: "<instance-id>"
extraVolumes:
- name: server-ca
  secret:
    secretName: server-ca
- name: google-app-creds
  secret:
    secretName: google-app-creds
extraVolumeMounts:
- name: server-ca
  mountPath: /cloudsql/cloudsql-instance
- name: google-app-creds
  mountPath: /gcp
extraEnv:
- name: "GOOGLE_APPLICATION_CREDENTIALS"
  value: "/gcp/service-account.json"
```
