### DISCUSSION TITLE
v5 RBAC for joining sessions in OSS teleport

### DISCUSSION THREAD

**Discussion by stereobutter** [gravitational/teleport#12383] [Q&A] [answered]
The other day I had the same issue as https://github.com/gravitational/teleport/issues/12022 i.e. users could not join sessions on teleport 9 (OSS). After adding appropriate settings under `join_sessions` for that role joining sessions works again.

```yaml 
allow:
    join_sessions:
      - name: Session access
        roles : ['developer]
        kinds: ['k8s', 'ssh']
        modes: ['peer']
```

The [docs](https://goteleport.com/docs/access-controls/guides/moderated-sessions/) state that moderated sessions are a teleport enterprise feature however. From what I see in some of the PRs like https://github.com/gravitational/teleport/pull/11223 this appears to be only partly true? From experimenting with this it appears that only using the modes `moderator` and `observer` as well as using `require_session_join` are restricted to enterprise teleport and won't work in OSS teleport? What is the correct way to (re)-enable session access in OSS teleport using v5 RBAC?
