### DISCUSSION TITLE
Access remote application through a tunnel

### DISCUSSION THREAD

**Discussion by muyen** [gravitational/teleport#12508] [Q&A]
Hi,

Teleport can add a remote node to an existing Teleport Cluster through a tunnel. Can we also add a web application through a tunnel? I tried to add the node first and then add the application but it didn't work. What do I need to do? Do I need to set up a trusted cluster first?

Best regards,

Arsene Lee

**Comment by duhast** [comment]
Same problem for me:
Host A runs with auth, proxy, node, app services enabled
Host B joined the cluster with a token of type "node,app"

But apps specified in host B config are not accessible through the proxy.
Any suggestions?

**Reply by webvictim** [reply]
What's in your `/etc/teleport.yaml` on host B?

Apps need to join via the proxy server, so if you have `auth_servers: ['teleport.example.com:3025']` it won't work - you should use `auth_servers: ['teleport.example.com:443']` instead.

**Reply by duhast** [reply]
Thanks! Entering proper auth server has resolved my issue!
I was under impression that it's better to set auth server LAN address to minimize internet dependency.

My host B entry was `auth_servers: ['10.20.0.3:3025']`

**Comment by muyen** [comment]
I tried to use the trusted cluster. However, the leaf cluster needs a domain name and a proxy that is on a public network. I don't want to do that so back to the original question. Can teleport support adding a web application by reverse tunnel?

**Reply by webvictim** [reply]
Yes, this is supported. You just need to install an agent that can access the app in the remote network. A config file like this should work:

```yaml
teleport:
  auth_servers: ['teleport.example.com:443'] # replace with the public hostname/port of your Teleport web UI
  auth_token: token-goes-here # replace this with a token generated with `sudo tctl tokens add --type=app` on your main Teleport server
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: no
app_service:
  enabled: yes
  apps:
  - name: myapp # replace with the name of your app
    uri: http://localhost:3000 # replace with the hostname/IP and port of the app as seen from the agent machine
```

Your app should then be available on `myapp.teleport.example.com`. You'll need to configure a wildcard DNS record for `*.teleport.example.com` to point to the IP of your Teleport proxy server.
