### DISCUSSION TITLE
Is it possible to run a teleport proxy in a docker container with the main teleport host outside docker on bare metal?

### DISCUSSION THREAD

**Discussion by BLucky-gh** [gravitational/teleport#12672] [Q&A] [answered]
Basically I want to access a database that has no ports exposed (the intention is to let applications just use docker's internal dns to connect to the db with `container_name:port` allowing us to set per-app permissions with docker networks), so my idea was to have a teleport proxy container which can access the database and point teleport at that. I looked int he docs but the closest thing I could find was running teleport itself in docker which I don't want

**Comment by webvictim** [comment, marked as answer]
The terminology is a little bit different to what you're describing. I think this is what you're suggesting:

`Teleport auth/proxy <- Teleport agent in Docker <-> Database in another Docker container`

You can do this, although you'll probably need to do it in insecure mode to work around the SAN on the TLS cert. Basically write a config file for Teleport a bit like this and save it to `teleport.yaml`:

```yaml
teleport:
  auth_servers: ['172.17.0.1:3080'] # replace 3080 with the port of your Teleport proxy on the bare metal host
  auth_token: abc123 # get the token from 'tctl tokens add --type=db' on the host
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: no
db_service:
  enabled: yes
  databases:
  - name: postgres-db
    description: Postgres Database in Docker
    uri: "postgres-container:5432" # replace with the Docker DNS hostname for your DB container
    protocol: postgres
```

Then start up your container with something like `docker run -v ./teleport.yaml:/etc/teleport/teleport.yaml quay.io/gravitational/teleport:9 -- --insecure`

This'd probably be a little easier with `docker-compose`.
