### DISCUSSION TITLE
Role to access session recordings from other users

### DISCUSSION THREAD

**Discussion by jamshidyerzakov** [gravitational/teleport#12901] [Q&A] [answered]
Hello

I would like to ask is it possible to create a role to access session recordings from other users. Now it's impossible to view other users' recordings with default teleport-admin roles (access, editor). Can you help me with some documentation or reference? 

Teleport version: v9.2.4

**Comment by webvictim** [comment, marked as answer]
This is the default role that allows a user to view their own session recordings:

```yaml
kind: role
metadata:
  name: view-own-recordings
spec:
  allow:
    rules:
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
  deny: {}
version: v5
```

You can modify this role by removing the `where` clause to allow _ALL_ session recordings to be viewed:

```yaml
kind: role
metadata:
  name: view-all-recordings
spec:
  allow:
    rules:
    - resources:
      - session
      verbs:
      - read
      - list
  deny: {}
version: v5
```
