### DISCUSSION TITLE
teleport with minio S3 in replicated HA mode

### DISCUSSION THREAD

**Discussion by hydridity** [gravitational/teleport#13375] [Q&A]
Greetings

I'm trying to deploy replicated teleport cluster (at least 3 replicas of auth and proxy nodes) as proof of concept for evaluating decision of buying enterprise license for our company, with the tech stack of: teleport hosted in kubernetes, etcd for teleport cluster state and S3 provided by Minio for session recording.
I've encountered problem where teleport is connecting to etcd fine, but completely ignoring the audit_session_uri config, that is not even trying to connect to minio s3, no connection error logs in teleport just straight up writing session recording to teleport data dir.

While documentation says teleport support any S3 compatible product, it's not exactly clear as to how to set up anything else than Amazon S3 regarding credentials.

Configuration I'm using for auth service right now is:
```
teleport:
  storage:
    type: etcd
    peers: ["http://[in cluster url]:2379"]
    prefix: "/teleport/"
    username: root
    password_file: /etc/teleport-pass/teleport-pass
    insecure: true

    region: [region as set in minio]
    audit_session_uri: "s3://teleport/logs?endpoint=http://[in.cluster.url]:9000&insecure=true&region=[region as set in minio]"

  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  #ca_pin: []
  diag_addr: ""

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: [public url]:3025
  proxy_listener_mode: multiplex
  cluster_name: [name]
  authentication:
    second_factor: off
```

With S3 credentials in mounted in: /root/.aws/credentials in format that should be supported by aws cli

```
[default]

aws_access_key_id=REDACTED

aws_secret_access_key=REDACTED
```

The only two things I can think of why teleport is ignoring the S3 config is that once etcd is used it wont allow to use another set of storage config. 
Which would not be exactly wise from development standpoint, and it's mentioned for example [here](https://github.com/gravitational/teleport/discussions/10990#discussioncomment-2374578) that it supports separate config foll all 3 components
The second thing is that I'm missing something in the url parameter in which case I would like to ask whether somebody could help me out with setting it up.

Also as by security and reliability policy we need the entire stack to be self hosted that's why Firestore and DynamoDB is out of question as long as there exists possibility of not using them.
I'm aware teleport can't store audit logs anywhere else except those two and local filesystem, would it work if every replica pod had it's own separate volume with sidecar container for filebeat for collecting the logs manually and uploading them to graylog or similar ?
