### DISCUSSION TITLE
Not sure how to configure ACM for sub domain apps

### DISCUSSION THREAD

**Discussion by ahsan-n** [gravitational/teleport#13539] [Q&A] [answered]
Hi, amazing tool a game changer. 

We are using AWS ACM with `tempo-cluster` helm chart on aws eks. 

Created public certificate for `*.example.com` 

Upon accessing `teleport.example.com` everything works fine. But when we launch an app 
`grafana.teleport.example.com` we get insecure certificate error. 

We later tried to reverse it by associating the certificate for `*.teleport.example.com`. After that login page gets the insecure error where the application launches without SSL warning. 

Now we are not sure of what we are missing. Will really appreciate any support in this. 

app config:
```yaml
    app_service:
      enabled: yes
      # Teleport provides a small debug app that can be used to make sure application
      # access is working correctly. It'll output JWTs so it can be useful
      # when extending your application.
      debug_app: true
      # This section contains definitions of all applications proxied by this
      # service. It can contain multiple items.
      apps:
        # Name of the application. Used for identification purposes.
      - name: "grafana"
        # URI and port the application is available at.
        uri: "http://grafana.example.private"
        # Optional application public address to override.
        labels:
          app: "watchman"
```

helm-chart values.yaml:

```yaml
annotations:
  service:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:REGION:ACCOUNT:certificate/1293893n1e1uwidh823he31"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

chartMode: aws
clusterName: teleport.example.com
aws:
  region: ap-southeast-1
  backendTable: teleport-backend
  auditLogTable: teleport-events
  auditLogMirrorOnStdout: false
  sessionRecordingBucket: example-teleport-sessions
  backups: true
highAvailability:
  replicaCount: 2
serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: teleport
```

**Comment by ahsan-n** [comment, marked as answer]
```yaml
        public_addr: "grafana.examplecom"
        rewrite:
          redirect:
          - "grafana.example.private"
```

this fix the issue
