### DISCUSSION TITLE
Teleport and multiple VPCs.  Possible?  Easy?

### DISCUSSION THREAD

**Discussion by randy-johnson** [gravitational/teleport#13656] [Q&A] [answered]
Hello,

We use Digital Ocean to host all our servers and our clients' servers.  Each client is in their own VPC with their own servers and managed DB.

Can we configure teleport so all our developers can access all the servers regardless of VPC?

It looks like perhaps [trusted clusters](https://goteleport.com/docs/setup/admin/trustedclusters/) would be what I want, but I am not sure because I do not want to establish trust be between clusters other than allowing developers to use teleport to connect to any server.

Thank You for pointing me in the right direction.

**Comment by webvictim** [comment, marked as answer]
Check out https://goteleport.com/docs/setup/admin/adding-nodes/#alternative-connect-to-the-proxy-service-via-teleport-node-tunneling

If you use the address of your Teleport proxy (e.g. `teleport.example.com:443`) in your `/etc/teleport.yaml` file on each server you're trying to join, this will establish a reverse tunnel between the server and the Teleport cluster which is used for all traffic. In this way you can bridge across multiple VPCs/networks without needing trusted clusters.

```yaml
teleport:
  auth_servers: ['teleport.example.com:443']
  auth_token: <token from tctl tokens add --type=node>
auth_service:
  enabled: no
proxy_service:
  enabled: no
# enable SSH
ssh_service:
  enabled: yes
# enable databases
db_service:
  enabled: yes
  # list databases here
  databases:
  - name: postgres
  ...
```
