### DISCUSSION TITLE
How to create a user that has access to a limited number or nodes.

### DISCUSSION THREAD

**Discussion by suykerbuyk** [gravitational/teleport#13669] [Q&A]
I'm having a hard time sorting through the methods to create/add a new user that only has access to specific nodes that I assume are marked with specific labels.

There doesn't seem to be a top-level "map" of what `tctl get` can actually get that I am hoping can lend some hints. 

I'm using the community/open-source v9.3.6.

What I would love to see is some example YAML files that:
A) Add a guest-like tag to select nodes.
B) Adds that tag to selected users.

The intent here is to limit access to a few development nodes for a subset of users while still allowing "access" users to be able to access everything.

**Comment by webvictim** [comment]
Here's a rough example.

`ssh_service` section of `/etc/teleport.yaml` on node belonging to `gus`:
```yaml
ssh_service:
  enabled: yes
  labels:
    owner: gus
```

`ssh_service` section of `/etc/teleport.yaml` on node for open access:
```yaml
ssh_service:
  enabled: yes
  labels:
    access: open
```

`traits` for user `gus` (`tctl get user/gus > gus.yaml`, edit `gus.yaml`, `tctl create -f gus.yaml` to update)
```yaml
spec:
  traits:
    logins:
    - gus
    node_labels:
      owner: gus
```

`access` role (can edit via the web UI, or `sudo tctl get role/access > access.yaml` etc)
```yaml
spec:
  allow:
    logins:
    - ec2-user
    - ubuntu
   node_labels:
     access: open
```

- Any user with the `access` role will get access to any server with the `access: open` label as `ec2-user` or `ubuntu`
- `gus` will get access to any servers with the `owner: gus` label as `gus`
- If you also grant `gus` the `access` role, he'll get access to both nodes.
