### DISCUSSION TITLE
Deploy a Teleport cluster on AWS EKS with eksctl and Helm

### DISCUSSION THREAD

**Discussion by WilliamLoy** [gravitational/teleport#13850] [Show and tell]
# Deploy a Teleport cluster on AWS EKS with eksctl and Helm

This post provides instructions for creating your own AWS EKS cluster to host Teleport
using [`eksctl`](https://eksctl.io/) and Helm.

The Teleport Helm chart deploys a highly available single-region Teleport cluster.

## Prerequisites

- [Programmatic access to your AWS account](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html)
-  [`eksctl`](https://eksctl.io/) CLI tool
- Latest version of Helm
- A registered domain name
- A downloaded Teleport enterprise license

## EKS deployment parameters

The configuration example in this section creates a highly available EKS cluster with the necessary IAM permissions to manage the necessary nodegroup as well as facilitate the DNS challenge required by [cert-manager](https://cert-manager.io/docs/). This example uses the `eksctl` config-based option to create the EKS cluster.

Create a `cluster.yaml` file using the following parameters:
```
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1c
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      certManager: true
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: true
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: t2.small
  labels:
    alpha.eksctl.io/cluster-name: example-name
    alpha.eksctl.io/nodegroup-name: example-name
  maxSize: 2
  minSize: 2
  name: example-name
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
    publicKeyPath: ""
  tags:
    alpha.eksctl.io/nodegroup-name: example-name
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: example-eks-cluster
  region: us-east-1
  version: "1.21"
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
```

Use the following command to create your EKS cluster using the `cluster.yaml` config:

    `eksctl create cluster -f cluster.yaml`

  You can monitor the progress of the cluster creation in AWS CloudFormation.

## SSL certificate management

This example uses Helm to deploy [cert-manager](https://cert-manager.io/docs/) for certificate creation and Kubernetes Issuer management.

Complete cert-manager's instructions for [deploying cert-manager using Helm](https://cert-manager.io/docs/installation/helm/#1-add-the-jetstack-helm-repository).

## Deploy a Teleport Cluster

The following example utilizes the following Helm chart configuration options:
- Deployment: High Availability
- Hosting provider: AWS
- Kubernetes service: EKS
- Region: us-east-1
- Backend and audit log storage: DynamoDB
- Session recording storage: S3
- TLS certificate management: Cert Manager
- Port management type: TLS Routing

1. Create a `aws-values.yaml` file using the following parameters:
```
clusterName: "example.teleport.com"
kubeClusterName: "exampleClusterName"
authenticationType: "local"
proxyListenerMode: "multiplex"

# Set enterprise to true to use enterprise image
# You will need to download your Enterprise license from the Teleport dashboard and create a secret to use this:
# kubectl -n ${TELEPORT_NAMESPACE?} create secret generic license --from-file=/path/to/downloaded/license.pem
enterprise: true
chartMode: aws

##################################################
# AWS-specific settings (only used in "aws" mode)
##################################################
aws:
  region: "us-east-1"
  backendTable: "bep-teleport-backend"
  auditLogTable: "bep-teleport-audit"
  auditLogMirrorOnStdout: false
  sessionRecordingBucket: "bep-teleport-session-example"
  backups: true
highAvailability:
  replicaCount: 2
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  # Settings for cert-manager (can be used for provisioning TLS certs in HA mode)
  certManager:
    addCommonName: true
    enabled: true
    issuerName: "letsencrypt-production"
    issuerKind: Issuer
    issuerGroup: cert-manager.io
```

2. Configure the necessary AWS IAM policies to allow the DynamoDB and S3 resources to be created by the Teleport service.

  - DynamoDB IAM policy:

```
     {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "ClusterStateStorage",
                  "Effect": "Allow",
                  "Action": [
                      "dynamodb:BatchWriteItem",
                      "dynamodb:UpdateTimeToLive",
                      "dynamodb:PutItem",
                      "dynamodb:DeleteItem",
                      "dynamodb:Scan",
                      "dynamodb:Query",
                      "dynamodb:DescribeStream",
                      "dynamodb:UpdateItem",
                      "dynamodb:DescribeTimeToLive",
                      "dynamodb:CreateTable",
                      "dynamodb:DescribeTable",
                      "dynamodb:GetShardIterator",
                      "dynamodb:GetItem",
                      "dynamodb:UpdateTable",
                      "dynamodb:GetRecords",
                      "dynamodb:UpdateContinuousBackups"
                  ],
                  "Resource": [
                      "arn:aws:dynamodb:us-east-1:1234567890:table/teleport-helm-backend",
                      "arn:aws:dynamodb:us-east-1:1234567890:table/teleport-helm-backend/stream/*"
                  ]
              },
              {
                  "Sid": "ClusterEventsStorage",
                  "Effect": "Allow",
                  "Action": [
                      "dynamodb:CreateTable",
                      "dynamodb:BatchWriteItem",
                      "dynamodb:UpdateTimeToLive",
                      "dynamodb:PutItem",
                      "dynamodb:DescribeTable",
                      "dynamodb:DeleteItem",
                      "dynamodb:GetItem",
                      "dynamodb:Scan",
                      "dynamodb:Query",
                      "dynamodb:UpdateItem",
                      "dynamodb:DescribeTimeToLive",
                      "dynamodb:UpdateTable",
                      "dynamodb:UpdateContinuousBackups"
                  ],
                  "Resource": [
                      "arn:aws:dynamodb:us-east-1:1234567890:table/teleport-helm-events",
                      "arn:aws:dynamodb:us-east-1:1234567890:table/teleport-helm-events/index/*"
                  ]
              }
          ]
      }
```
   - S3 IAM policy:

```
     {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "ClusterSessionsStorage",
                "Effect": "Allow",
                "Action": [
                    "s3:PutEncryptionConfiguration",
                    "s3:PutObject",
                    "s3:GetObject",
                    "s3:GetEncryptionConfiguration",
                    "s3:GetObjectRetention",
                    "s3:ListBucketVersions",
                    "s3:ListBucketMultipartUploads",
                    "s3:AbortMultipartUpload",
                    "s3:CreateBucket",
                    "s3:ListBucket",
                    "s3:GetBucketVersioning",
                    "s3:PutBucketVersioning",
                    "s3:GetObjectVersion"
                ],
                "Resource": [
                    "arn:aws:s3:::teleport-helm-sessions/*",
                    "arn:aws:s3:::teleport-helm-sessions"
                ]
            }
         ]
      }
```
3. Add the Teleport Helm repository chart repository.

   `helm repo add teleport https://charts.releases.teleport.dev`
   `helm repo update`

4. Deploy the Teleport cluster:

    `helm --create-namespace example-namespace`
    `helm -n example-namespace install deployment-name teleport/teleport-cluster -f aws-values.yaml`

5. Confirm the chart is deployed:

    `kubectl --namespace example-namespace get all`

6. Configure DNS

    Teleport uses TLS to provide secure access to its Proxy Service and Auth Service, and this requires a domain name that clients can use to verify Teleport's certificate.

    Set up two CNAME DNS records: example.teleport.com for all traffic and *.example.teleport.com that point to the load balancer handing public traffic for your EKS cluster.

7. Deploy the Issuer using the following command:

    `kubectl -n example-namespace apply -f issuer.yaml`

8. Verify the Teleport cluster is deployed.

See [creating a user](#https://goteleport.com/docs/kubernetes-access/getting-started/local/#step-24-create-a-user) to create your first local Teleport user.

Once you have created this user you have successfully gone from zero to Teleporting on EKS!
