### DISCUSSION TITLE
X forwarding with `tsh` on Windows

### DISCUSSION THREAD

**Discussion by webvictim** [gravitational/teleport#13869] [Show and tell]
1. You must have X11 forwarding enabled for the `ssh_service` on your machine running Teleport:

```yaml
ssh_service:
  enabled: true
  x11:
    enabled: true
```

2. Your role must allow X11 forwarding to be requested:

```yaml
spec:
  options:
    permit_x11_forwarding: true
```

(you can check whether you have the permission by looking for `permit-X11-forwarding` in the `Extensions` output from `tsh status`):

```console
  Extensions:         permit-X11-forwarding, permit-agent-forwarding, permit-port-forwarding, permit-pty
```

3. You'll need to set your `DISPLAY` variable manually. For me (running [Xming](http://www.straightrunning.com/XmingNotes/)) I used:

```console
set DISPLAY=localhost:0.0
```

4. Once this is done, you can run `tsh ssh -Y` to request trusted X11 forwarding (i.e. no Xauth) to your target machine:

```console
tsh ssh -Y user@host
```

At this point, you should be able to run a command requiring an X display on the remote machine and have it display locally on your Windows machine, all forwarded via Teleport.
