### DISCUSSION TITLE
what is exact the procedure to configure 2 auth servers?

### DISCUSSION THREAD

**Discussion by conung-vic** [gravitational/teleport#13971] [Q&A]
Hi.
I want to have 2 auth+proxy servers in my infrastructure without load balancer before.

like p1.auth... and p2.auth

https://goteleport.com/docs/setup/reference/backends/#auth-server-state - here is written that servers must have the same config.

I assume, that almost all configuration have to be the same, except of things related to proxy_service domain names and certificates, right?

I tried this, and got the common user and nodes base (when I add something on one auth-server, I see it on another).

but when I try to connect to some node using WebUI from the second auth server, I got the following:
```
disconnected
connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
```

```
2022-06-29T13:08:54Z INFO [WEB]       Getting terminal to &web.TerminalRequest{Server:"d5c9558c-a305-4b62-8759-d6b02571c559", Login:"ubuntu", Term:session.TerminalParams{W:157, H:26}, SessionID:"c44513ea-ca90-4872-ba86-41b6f234f3bd", Namespace:"default", ProxyHostPort:"localhost:443,3023", Cluster:"company-main", InteractiveCommand:[]string(nil), KeepAliveInterval:300000000000}. web/apiserver.go:2006
2022-06-29T13:08:54Z INFO [CLIENT]    Connecting to proxy=localhost:3023 login="ubuntu" client/api.go:2559
2022-06-29T13:08:54Z INFO [CLIENT]    Successful auth with proxy localhost:3023. client/api.go:2564
2022-06-29T13:09:24Z INFO [SUBSYSTEM] Connected to auth server: 172.31.26.136:3025 trace.fields:map[dst:127.0.0.1:3023 src:127.0.0.1:33740] regular/proxy.go:291
2022-06-29T13:09:24Z INFO [WEBSOCKET] Failed creating a client for session c44513ea-ca90-4872-ba86-41b6f234f3bd. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: authentication handshake failed: context deadline exceeded&#34;
Stack Trace:
        /work/projects/teleport/teleport-9.2.4/api/client/client.go:1411 github.com/gravitational/teleport/api/client.(*Client).IsMFARequired
        /work/projects/teleport/teleport-9.2.4/lib/client/client.go:348 github.com/gravitational/teleport/lib/client.(*ProxyClient).IssueUserCertsWithMFA
        /work/projects/teleport/teleport-9.2.4/lib/web/terminal.go:357 github.com/gravitational/teleport/lib/web.(*TerminalHandler).issueSessionMFACerts
        /work/projects/teleport/teleport-9.2.4/lib/web/terminal.go:338 github.com/gravitational/teleport/lib/web.(*TerminalHandler).makeClient
        /work/projects/teleport/teleport-9.2.4/lib/web/terminal.go:263 github.com/gravitational/teleport/lib/web.(*TerminalHandler).handler
        /work/projects/teleport/teleport-9.2.4/lib/web/terminal.go:207 github.com/gravitational/teleport/lib/web.(*TerminalHandler).Serve
        /work/projects/teleport/teleport-9.2.4/lib/web/apiserver.go:2007 github.com/gravitational/teleport/lib/web.(*Handler).siteNodeConnect
        /work/projects/teleport/teleport-9.2.4/lib/web/apiserver.go:2590 github.com/gravitational/teleport/lib/web.(*Handler).WithClusterAuth.func1
        /work/projects/teleport/teleport-9.2.4/lib/httplib/httplib.go:79 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
        /work/projects/teleport/teleport-9.2.4/lib/httplib/httplib.go:65 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1.1
        /usr/lib/go-1.18/src/net/http/server.go:2084 net/http.HandlerFunc.ServeHTTP
        /home/igor/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.31.0/handler.go:191 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
        /work/projects/teleport/teleport-9.2.4/lib/httplib/httplib.go:68 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1
        /home/igor/go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        /usr/lib/go-1.18/src/net/http/server.go:2127 net/http.StripPrefix.func1
        /usr/lib/go-1.18/src/net/http/server.go:2084 net/http.HandlerFunc.ServeHTTP
        /work/projects/teleport/teleport-9.2.4/lib/web/apiserver.go:464 github.com/gravitational/teleport/lib/web.NewHandler.func1
        /usr/lib/go-1.18/src/net/http/server.go:2084 net/http.HandlerFunc.ServeHTTP
        /home/igor/go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        /work/projects/teleport/teleport-9.2.4/lib/web/apiserver.go:216 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
        /home/igor/go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
        /home/igor/go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
        /usr/lib/go-1.18/src/net/http/server.go:2916 net/http.serverHandler.ServeHTTP
        /usr/lib/go-1.18/src/net/http/server.go:1966 net/http.(*conn).serve
        /usr/lib/go-1.18/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: connection error: desc = &#34;transport: authentication handshake failed: context deadline exceeded&#34;] web/terminal.go:265
```

how I should connect the second auth server to the first one? just copy config or generate token and something else?

**Comment by webvictim** [comment]
As per the docs: "To run multiple instances of Teleport Auth Server, you must switch to a High Availability secrets back-end first."

Supported HA storage backends are:
- AWS DynamoDB
- GCP Firestore
- `etcd`
- PostgreSQL/CockroachDB (preview)

See the backend docs here: https://goteleport.com/docs/setup/reference/backends/

**Reply by conung-vic** [reply]
I have already referenced to this doc. Now, both my auth servers are using DynamoDB with the same settings.

this step is only one which is described in documentation.
the question is: what are the **_next_** steps?

**Comment by webvictim** [comment]
If you’re not using a load balancer, you’ll want to use a round robin DNS record which points to the IP/hostnames of both servers, then configure your services to connect to that:

```
teleport.example.com has address 172.20.1.1
teleport.example.com has address 172.20.1.2
```

```yaml
teleport:
  auth_servers: ['teleport.example.com:443']
```

If you’re running proxies in HA then you’ll also want them to be serving the same domain name too - so they should both be using the TLS key pair for `teleport.example.com`.

**Reply by conung-vic** [reply]
thank you for answer.

So, there is no way to configure 2 auth servers with different DNS in one cluster, right?

I must use either loadbalancer before, or round robin DNS record?

**Reply by webvictim** [reply]
Correct.

**Comment by conung-vic** [comment]
I reconfigured my servers to one round-robin domain name using MultipleAnswer DNS from AWS Route53 with health checks with TTL=10.

Now, if at least one auth+proxy server is working, I have an access to WebUI  on my domain (like auth.company.com).

after that, I have added a node using tctl.

If the first auth server is working only - I am able to connect to target node from WebUI.
If the second auth server is working only - I got the same error as in the first post in this discussion.

here is a auth config:
```
version: v2
teleport:
  nodename: p2.auth.company.com # the difference is here only. Is it important?
  storage:
    type: dynamodb
    region: eu-west-2
    table_name: teleport-auth
    access_key: XXXXXXXXXX
    secret_key: XXXXXXXXXXXXXXXXXX

  data_dir: /var/lib/teleport
  log:
    output: /var/log/teleport/teleport.log
    severity: INFO
    format:
      output: text
      extra_fields: [level, timestamp, component, caller]

auth_service:
  enabled: yes
  cluster_name: auth.company.com
  proxy_protocol: on
  listen_addr: 0.0.0.0:3025
  public_addr: auth.company.com:3025

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:443
  https_cert_file: /etc/letsencrypt/live/auth.company.com/fullchain.pem
  https_key_file: /etc/letsencrypt/live/auth.company.com/privkey.pem
  public_addr: auth.company.com:443

ssh_service:
  enabled: no

app_service:
  enabled: no

kubernetes_service:
  enabled: no

db_service:
  enabled: no

windows_desktop_service:
  enabled: no
```

used certificates are the same (generated on one server and copied to the second).


UPD:
access to target node using `tsh ssh` is working as well if at least one auth node is active (doesn't matter which exactly).

so the problem is in WebUI only =(
