### DISCUSSION TITLE
X11 example with xeyes

### DISCUSSION THREAD

**Discussion by stevenGravy** [gravitational/teleport#14482] [Show and tell]
# End to End X11 forwarding example

This is an end to end example of using X11 Forwarding to access a graphical desktop application through ssh and Teleport `tsh`.

## Prerequisites:
- Teleport Cluster V10
- `tsh` client version 10
- Deployment of Ubuntu server

This example used a AWS ubuntu instance with this setting:
Canonical, Ubuntu, 22.04 LTS, amd64 jammy image build on 2022-06-09

The `tsh` is V10.0.0 and the `ssh` used is `OpenSSH_8.6p1, LibreSSL 3.3.6` on a MacOS M1.

## Configure Ubuntu Server with X11 Apps
```bash
ssh -i identityfile.pem ubuntu@<publicIP>
sudo apt update
sudo apt install x11-apps -y
```

## X11 App Example with SSH on Desktop

```
ssh -Y -i identityfile.pem ubuntu@<publicIP> xeyes
```
<img width="818" alt="image" src="https://user-images.githubusercontent.com/60704961/179048112-4086a17e-b578-4869-b301-23046cce48d0.png">

## Teleport Example

Add a role with the `permit_x11_forwarding: true` and create a user with that role.

```yaml
kind: role
metadata:
  name: x11-role-example
spec:
  allow:
    logins: ['{{internal.logins}}', ubuntu, debian]
    node_labels:
      '*': '*'
  options:
      max_session_ttl: 8h0m0s
      permit_x11_forwarding: true
      create_host_user: true
version: v5
```

Now to add this server into Teleport.  You can use the Add Server button.

![image](https://user-images.githubusercontent.com/60704961/179049350-fd8df3f1-2a09-43a0-ab9a-52eddb054547.png)

After running the script add the `x11` into `/etc/teleport.yaml` in the `ssh_service`

```yaml
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  x11:
    enabled: yes
    display_offset: 10
    max_display: 1010
```

Restart the the service

```bash
sudo service teleport restart
```

## X11 with Teleport
Have a user that has the `x11-role-example` 

Login to the Teleport cluster and run `xeyes` with `tsh ssh`.

```bash
tsh login --proxy=teleport.example.com
tsh ls
tsh ssh -X ubuntu@nodename xeyes
```

<img width="876" alt="image" src="https://user-images.githubusercontent.com/60704961/179049130-f8092dfd-3ef0-44ff-8d8c-c6da97d7b0bd.png">
