### DISCUSSION TITLE
Can't connect to Aurora MySQL using Database Access

### DISCUSSION THREAD

**Discussion by dhaninugraha** [gravitational/teleport#14629] [Q&A]
Hi folks,

Been trying to figure out for the life of me, why I kept getting `ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 3` everytime I try to connect via `tsh db connect`.

I can login just fine:
```
❱❱❱ tsh login --proxy=sandbox-teleport.mydomain.com:443 --auth=local --user=admin
Welcome to Teleport cluster sandbox-teleport. Logging in implies that you are an authorized user, and that you both acknowledge and agree that your activities will be recorded.
Press [ENTER] to continue.
Enter password for Teleport user admin:
Tap any security key or enter a code from a OTP device
> Profile URL:        https://sandbox-teleport.mydomain.com:443
  Logged in as:       admin
  Cluster:            sandbox-teleport
  Roles:              access, db, editor
  Logins:             -teleport-nologin-7f3f520e-cfca-4416-b3d3-594f241c30fe, -teleport-internal-join
  Kubernetes:         enabled
  Valid until:        2022-07-20 03:25:39 +0700 WIB [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

`tsh db login` seems to return no error:
```
❱❱❱ tsh db login sandbox-mysql-5-7-cluster

Connection information for database "sandbox-mysql-5-7-cluster" has been saved.

You can now connect to it using the following command:

  tsh db connect --db-user=<user> --db-name=<name> sandbox-mysql-5-7-cluster

Or view the connect command for the native database CLI client:

  tsh db config --format=cmd sandbox-mysql-5-7-cluster
```

`tsh db ls` also lists my autoregistered Aurora cluster:
```
Name                             Description                                         Allowed Users Labels               Connect
-------------------------------- --------------------------------------------------- ------------- -------------------- ---------------------------------------------------
> sandbox-mysql-5-7-cluster      Aurora cluster in ap-southeast-3                    [*]           account-id=12345,... tsh db connect --db-user=<user> --db-name=<name>...
sandbox-mysql-5-7-cluster-reader Aurora cluster in ap-southeast-3 (reader endpoin... [*]           account-id=12345,...
```

But I can never connect to the cluster:
```
❱❱❱ tsh db connect --db-user=admin --db-name=information_schema sandbox-mysql-5-7-cluster
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 3
ERROR: exit status 1
```

`tsh db proxy` is also no bueno.

---

My cluster is setup in such a way in AWS:
- EC2
  - an instance for auth
  - an instance for proxy
  - an instance for DB service
- load balancers
  - an ALB that proxies HTTP/HTTPS to TCP 3080 on proxy instance
  - an NLB that proxies TCP 3023 and 3036 to proxy instance
- Route53 entries
  - sandbox-teleport-auth.mydomain.com -> points to auth instance
  - sandbox-teleport-mysql.mydomain.com -> points to NLB
  - sandbox-teleport-ssh.mydomain.com -> points to NLB
  - sandbox-teleport-tunnel.mydomain.com -> points to proxy instance
  - sandbox-teleport.mydomain.com -> points to ALB
- Aurora MySQL cluster -> DB service instance can connect here (no network issues & IAM authentication direct from the DB service instance works fine)

My Teleport user:
```
kind: user
metadata:
  id: 1658219081276075875
  name: admin
spec:
  created_by:
    time: "2022-07-11T16:42:01.405906259Z"
    user:
      name: 666adf6f-1355-4d96-9b2a-25d00e484fa9.sandbox-teleport
  expires: "0001-01-01T00:00:00Z"
  roles:
  - editor
  - access
  - db
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
    recovery_attempt_lock_expires: "0001-01-01T00:00:00Z"
  traits:
    aws_role_arns: null
    db_names: null
    db_users: null
    kubernetes_groups: null
    kubernetes_users: null
    logins: null
    windows_logins: null
version: v2
```

`db` role:
```
kind: role
metadata:
  id: 1658219064626333243
  name: db
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '*'
    db_users:
    - '*'
    kubernetes_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
version: v3
```

---

I'm attaching the proxy and auth logs during the `tsh db connect --verbose` attempt.

[teleport-auth.log](https://github.com/gravitational/teleport/files/9140113/teleport-auth.log)
[teleport-proxy.log](https://github.com/gravitational/teleport/files/9140114/teleport-proxy.log)
[tsh-db-connect-verbose.log](https://github.com/gravitational/teleport/files/9140115/tsh-db-connect-verbose.log)

I can provide proxy, auth and/or database service Teleport configs, as well as details for the security group for each EC2 instance, if required.

Thankyou for any and all help and insights!
