### DISCUSSION TITLE
Can't get passwordless to work with Apple TouchID

### DISCUSSION THREAD

**Discussion by apiening** [gravitational/teleport#14964] [Q&A] [answered]
I have updated my teleport server and all connected clients to version `10.0.2`.
I have updated the `auth_service` section of my teleport server config like this:
```yaml
auth_service:
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: tp.mydomain.com
    connector_name: passwordless # passwordless by default
```

When I log in to the `teleport web interfacec` with `Google Chrome 103.0.5060.114` on `Mac OS 12.4 Monterey` and go to `Account Settings` / `Two Factor Devices` and click on `ADD TWO-FACTOR DEVICE` I only get the option to choose between `Hardware Key` and `Authenticator App`.

With `tsh mfa add` on the terminal, I get the options `TOTP` and `WEBAUTHN`, but not `TOUCHID` as shown in the docs.

I do have `libfido2` installed. However, `tsh touchid diag` reports this:
```
Has compile support? true
Has signature? true
Has entitlements? false
Passed LAPolicy test? true
Passed Secure Enclave test? true
Touch ID enabled? false
```

Does anyone have `passwordless` authentication working with `TouchID`?
Any idea why `TouchID` ist not available on the Web browser (I also checked with `Safari`) as a 2F-Device?
What does `Has entitlements` mean and how can I resolve this to satisfy `tsh touchid diag`?
