### DISCUSSION TITLE
Active Sessions and Session Recordings are not showing up in my teleport UI. Only Audit logs is showing

### DISCUSSION THREAD

**Discussion by kotegit2022** [gravitational/teleport#15029] [Q&A]
Hi Team,

I've launched a kubernetes cluster and installed teleport cluster and SSO with my GITHUB by following the below URL https://goteleport.com/docs/getting-started/kubernetes-cluster/.

But even after performing the kubectl we are seeing only Audit Logs under Activity. Active Sessions and Session Recording are having no data even though the session is active.

Note: I'm trying all this by signing into the teleport through GitHub(koti2022 username) option, and performing the actions in kubernetes cluster as koti(user of teleport).

Thanks in Advance.
![ActiveSession_GitHub](https://user-images.githubusercontent.com/110150376/181742887-4032b8cb-320a-4cf6-877c-8c0ef2327a65.JPG)
![AuditLog_Github](https://user-images.githubusercontent.com/110150376/181742898-15d1b018-6d51-4199-9566-3f364b6c6ec8.JPG)
![SessionRecordings_GitHub](https://user-images.githubusercontent.com/110150376/181742906-0652752f-2945-4b53-9628-32994c3f4e46.JPG)
![teleport_Yaml](https://user-images.githubusercontent.com/110150376/181743188-c833c5cd-aab3-43f8-a07a-088bc29a25c4.JPG)

**Comment by scottpgallagher** [comment]
Are there any errors in the teleport log? If you do a journalctl -fu teleport.service you will see the logs to see if there are any errors. Also can you share the roles this user gets assigned?

**Comment by plutino** [comment]
This is an old thread, but I'm having the same problem with teleport 13.0.3.  

I'm able to see the `Session Uploaded` entries in the Audit Log, and the uploaded files in GCS bucket.  My user has all preset roles: `access`, `auditor`, and `editor`.

Cluster is deployed to a GKE cluster using the official helm chart.

**Reply by webvictim** [reply]
Where are you storing your Teleport audit logs? If you're using the Helm chart with `chartMode: gcp`, they should be in Firestore?

Can you share your Helm values here? (redact sensitive values if desired)

**Reply by plutino** [reply]
Thanks @webvictim.  Sorry for the late response, I have been traveling.

 Yes, we use the `gcp` chart mode and the audit logs are in Firestore.  We use teleport 13.0.3 and here are the Helm values:

```yaml
clusterName: teleport.example.com
kubeClusterName: platform
labels:
  id: platform

validateConfigOnDeploy: false
separatePostgresListener: true

chartMode: gcp
gcp:
  credentialSecretName: ""
  projectId: *****-platform
  auditLogMirrorOnStdout: false
  auditLogTable: teleport-events
  backendTable: teleport-backend
  sessionRecordingBucket: *****-platform-teleport-sessions

highAvailability:
  replicaCount: 2
  certManager:
    enabled: true
    issuerName: letsencrypt-prod

annotations:
  serviceAccount:
    iam.gke.io/gcp-service-account: teleport@*****-platform.iam.gserviceaccount.com

authentication:
  type: github
  connectorName: github
  localAuth: true
  secondFactor: otp

auth:
  teleportConfig:
    teleport:
      log:
        severity: INFO
        output: stdout
        format:
          output: json
          extra_fields: ["timestamp","level","component","caller"]
    auth_service:
      tokens:
      - db,kube:/etc/teleport-secrets/auth-token

proxy:
  teleportConfig:
    teleport:
      log:
        severity: INFO
        output: stdout
        format:
          output: json
          extra_fields: ["timestamp","level","component","caller"]
    proxy_service:
      kube_public_addr: teleport.example.com:3026
      postgres_public_addr: teleport.example.com:5432
      public_addr: teleport.example.com:443
```

The only further modification from this values file is to mount the `auth-token` secret as a file in the container.
