### DISCUSSION TITLE
Set users by hosts

### DISCUSSION THREAD

**Discussion by dgiorgio** [gravitational/teleport#15146] [Q&A]
I have hundreds of hosts, but not all of them have the same users.
If I enable all possible users, I need to create a list of approximately 20 users.
I saw in the discussion (https://github.com/gravitational/teleport/discussions/11893#discussioncomment-2552273) that it is not possible to allow for all users, is there any way to limit users by hosts and not just by teleport users?

**Comment by Valien** [comment]
Yes, you can leverage labels (key value pairs) to define access. So for instance you can have a label: `env=dev` and assign that to X number of hosts (via it's `teleport.yaml` file) and then in your RBAC you can allow/deny certain labels.

Example of a GCP role that only allows access to GCP labeled resources:

````
kind: role
metadata:
  name: gcp
spec:
  allow:
    app_labels:
      x: x
    db_labels:
      x: x
    kubernetes_groups:
    - admin
    kubernetes_labels:
      x: x
    logins:
    - ubuntu
    node_labels:
      cloud: gcp
  deny:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_groups:
    - admin
    kubernetes_labels:
      '*': '*'
  options:
    cert_format: standard
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v4
````

**Comment by dgiorgio** [comment]
I was trying, but it didn't work very well.
As I understand it, Teleport works with hosts, users and roles.
I created a role, to allow ssh user "test1", and added the teleport user in that role.
Now the test1 user will appear on all hosts of that user.

example:
```
configuration in teleport
user: teleportuser
role: testrole

host1:
name: machine1
user: user1

host2:
name: machine2
user: user2

host3:
name: machine3
user: user3
```

When I want to connect to server machine1, I want only user1 to appear.
on machine2, only user user2.
currently appears user1, user2 and user3 on the three servers.

**Reply by webvictim** [reply]
You can do this with three roles and some server labels.

Set labels on your servers like this:

host1:
```yaml
ssh_service:
  labels:
    user: user1
```

host2:
```yaml
ssh_service:
  labels:
    user: user2
```

host3:
```yaml
ssh_service:
  labels:
    user: user3
```

Then create 3 roles:

allow-user1:
```yaml
kind: role
metadata:
  name: allow-user1
spec:
  allow:
    logins:
    - user1
    node_labels:
      user: user1
```

allow-user2:
```yaml
kind: role
metadata:
  name: allow-user2
spec:
  allow:
    logins:
    - user2
    node_labels:
      user: user2
```

allow-user3:
```yaml
kind: role
metadata:
  name: allow-user3
spec:
  allow:
    logins:
    - user3
    node_labels:
      user: user3
```

Assign all 3 roles to your user.

**Reply by StownCraft** [reply]
Сan I hide this label for security purposes so that it does not appear in the server list in the web interface and in the console, but at the same time it can be used in the role settings?

**Reply by webvictim** [reply]
Not today, but we are working on similar functionality: https://github.com/gravitational/teleport/issues/17041

**Reply by StownCraft** [reply]
I just thought that if I have 200 servers with different usernames, it's not very convenient to create 200 roles and assign them to teleport users. You should probably consider not displaying non-existent server users in the web interface when connecting, or making it possible to use node labels in the role settings, for example:
```
kind: role
metadata:
  name: infrastructure-view-access
spec:
  allow:
    logins: '{{node.labels.view_users}}'
    node_labels:
      group: infrastrucrure
```
accordingly, the servers themselves would simply have a label like: `view_users: ['ubuntu', 'nginx', 'php']`

**Reply by dgiorgio** [reply]
> You can do this with three roles and some server labels.
> 
> Set labels on your servers like this:
> 
> host1:
> 
> ```yaml
> ssh_service:
>   labels:
>     user: user1
> ```
> 
> host2:
> 
> ```yaml
> ssh_service:
>   labels:
>     user: user2
> ```
> 
> host3:
> 
> ```yaml
> ssh_service:
>   labels:
>     user: user3
> ```
> 
> Then create 3 roles:
> 
> allow-user1:
> 
> ```yaml
> kind: role
> metadata:
>   name: allow-user1
> spec:
>   allow:
>     logins:
>     - user1
>     node_labels:
>       user: user1
> ```
> 
> allow-user2:
> 
> ```yaml
> kind: role
> metadata:
>   name: allow-user2
> spec:
>   allow:
>     logins:
>     - user2
>     node_labels:
>       user: user2
> ```
> 
> allow-user3:
> 
> ```yaml
> kind: role
> metadata:
>   name: allow-user3
> spec:
>   allow:
>     logins:
>     - user3
>     node_labels:
>       user: user3
> ```
> 
> Assign all 3 roles to your user.

It worked, but it is confusing to manage on host, which users can access, this permission should be on "teleport server" not the "teleport agent". 

How I do allow the teleport user to login with **server_user** user on host, but deny to login with user **root**, in a server with CA added?
https://goteleport.com/docs/server-access/guides/openssh/
Now, anyone teleport user, can to login on host with anyone user, including the **root** user.

Ok, I can do not allow the **root** user on specific teleport user.
But if I need to allow the login with **root** user on **server1**, this teleport user can to login with **root** in all servers.

edit: this answers my question.
https://goteleport.com/docs/access-controls/faq/?scope=enterprise#can-i-use-node-level-rbac-with-openssh-servers

**Comment by EvgeniaPatsoni** [comment]
I agree, it would be super useful if the users could be linked only with the server that they belong to. 

Let's say that server-1 has two users: e.g. `root` and `dev`.
And server-2 also has two users: e.g. `root` and `test`.

When trying to login to server-1 I should be able to choose only between `root` and `dev`.
Not  `root`, `dev` and `test`, since selecting the `test` user would result in a `Failed to launch: user: unknown user` error.

Trying to manage this issue with tinkering on the teleport-agents configuration and then creating multiple separate roles to assign to users, seems like an overkill and increases the chance of mistakes when having to maintain multiple servers.

**Reply by webvictim** [reply]
How would you like to be able to define this? Please provide a specific YAML example of what the configuration could look like.

**Reply by EvgeniaPatsoni** [reply]
**How would you like to be able to define this?**

Upon enrolling a new server resource to the Teleport cluster, it would be great if we were also able to enter some user accounts that exist on this server _but this input would then be tied to this particular server only_.

Currently, there is an option to enter account names when enrolling a new server to the cluster, but these accounts are then applied to all the other servers that were previously enrolled. This introduces the problem I mentioned in my previous comment.
In addition, if I delete one of these accounts, it would be deleted for all the servers too, not the one being enrolled at that time.

Both of these behaviors are misleading.

P.S. I am talking about vm/ssh user accounts NOT teleport user accounts. So I am not sure if it is possible to provide a YAML example for this configuration.

**Reply by webvictim** [reply]
As noted it's possible to do this today, see the comment above: https://github.com/gravitational/teleport/discussions/15146#discussioncomment-3362648

**Reply by EvgeniaPatsoni** [reply]
So if I have, let's say 300 servers, I would have to access them one by one, edit their `teleport.yaml` files in order to add these labels, then go to Teleport in order to create 300 different roles, and assign them accordingly to each user?

I apologize in advance in case I understood something wrong.

**Reply by StownCraft** [reply]
@webvictim  It is inconvenient to add a role for each server. If there are a lot of servers, then you can easily get confused in the rules and make a serious mistake. I have already given an example of a function that I would like to have in teleport. [example](https://github.com/gravitational/teleport/discussions/15146#discussioncomment-4691038)

**Reply by webvictim** [reply]
Unfortunately this is just a fundamental difference in the way that Teleport treats user access. Teleport ostensibly believes that servers are cattle, not pets - they should all look pretty similar and use a non-unique login for access. Having individual per-server users is always going to create a large management overhead no matter how you slice it.

**Comment by dgiorgio** [comment]
The problems still persists:
1 - edit the teleport.yaml every time and restart them.
2 - it's not possible to control access on server without the teleport (agent) installed, ex: router.

The problem 1, I'm trying to solve it.
I created a role in ansible, to manage all hosts, but I'm testing it.

**Comment by snags141** [comment]
This would be a huge improvement for us - across hundreds of servers, many are managed by third parties where we cannot control the unix usernames its very confusing when someone needs to connect to a server and there are 20+ users showing in the list to choose from. Would be much more helpful if the list only showed the users that are relevant for that particular host.

I could group my roles and thereby servers based on shared usernames and only assign one role at a time to each user, but I don't have time to be constantly assigning and removing roles from everyone. 

The only workaround I've found, which isn't really even a workaround is to set a label called "primary_user" on each host, so when someone is trying to connect they know which user to choose.
It would be handy if you could set the logins in the role yaml to include something like {{labels.primary_user}} but that doesn't solve the issue of that username then showing on all the other servers that other roles have granted a user access to. 

IMO the users that you specify in a role, should **only** apply to the nodes/servers that are granted by that particular role. They should not be applied to all the other servers you have access to from other roles as well. 
I'm not sure why a username for server B granted from role B should also show up on server A granted from role A, but appreciate that may go against the current model/other use cases fulfilled by the way things work currently.

**Reply by webvictim** [reply]
> IMO the users that you specify in a role, should only apply to the nodes/servers that are granted by that particular role. They should not be applied to all the other servers you have access to from other roles as well.

This is actually the way it works today. If you have two roles:

```yaml
kind: role
metadata:
  name: role-one
spec:
  allow:
    logins:
    - login-one
    node_labels:
      service: service-one
```

```yaml
kind: role
metadata:
  name: role-two
spec:
  allow:
    logins:
    - login-two
    node_labels:
      service: service-two
```

If you assign both roles to a user, then they'll only see `login-one` available for use on hosts with `service: service-one`, and only see `login-two` available for use on hosts with `service: service-two` - at least via the Teleport web UI or when using Teleport Connect.

It's a little messier when using `tsh login` and `tsh ssh` via the command line as there isn't currently a way to show the list of available users on each host - but the RBAC checks are performed at the backend and people will only be able to log on as hosts they can actually use.
