### DISCUSSION TITLE
How can I set 2 environment node labels

### DISCUSSION THREAD

**Discussion by mdrasheek** [gravitational/teleport#15246] [Q&A]
We have role that can be associated with multiple environment. But there are nodes which could belong to 2 environments (Like a common node). I was able to set only 1 node label as the environment. 

I have given access based on environment label only.

How can I label a common node so that the node should be visible under both the environment labels?

**Comment by webvictim** [comment]
You can set multiple labels in the `/etc/teleport.yaml` file on the node itself:

```yaml
ssh_service:
  labels:
    label-one: "a value"
    label-two: "another value:
```

**Reply by mdrasheek** [reply]
> You can set multiple labels in the `/etc/teleport.yaml` file on the node itself:
> 
> ```yaml
> ssh_service:
>   labels:
>     label-one: "a value"
>     label-two: "another value:
> ```

In my case, label-one itself has 2 values. Is it possible?

**Reply by webvictim** [reply]
You could try setting a list, but I don't believe this works:

```yaml
ssh_service:
  labels:
    label-one: ["value1", "value2"]
```

**Reply by PavelNiedoba** [reply]
what is the purpose of having values for labels then?

**Reply by PavelNiedoba** [reply]
> You could try setting a list, but I don't believe this works:
> 
> ```yaml
> ssh_service:
>   labels:
>     label-one: ["value1", "value2"]

just tried this with 11.1.1.0 version and it prevents teleport from starting

**Reply by mdrasheek** [reply]
Yes, I have also tried, it didn't work. Alternatively, I had to make a common environment and associate it with the roles.

**Reply by webvictim** [reply]
You might be better off inverting your logic to have the key contain the information rather than the value:

```yaml
ssh_service:
  labels:
    value1: true
    value2: true
```

> what is the purpose of having values for labels then?

Labels are key:value pairs. Having a single value is still a value...
