### DISCUSSION TITLE
How to run teleport behind a reverse proxy

### DISCUSSION THREAD

**Discussion by smperera** [gravitational/teleport#15293] [Q&A] [answered]
I am trying to run the teleport behind a reverse proxy. When I try to access teleport using **mydomain/teleport** url, I get below error.

> WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError multiplexer failed to detect connection protocol, first few bytes were: []byte{0x47, 0x45, 0x54, 0x20, 0x2f, 0x74, 0x65, 0x6c}\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:423 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:259 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:221 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit\nUser Message: multiplexer failed to detect connection protocol, first few bytes were: []byte{0x47, 0x45, 0x54, 0x20, 0x2f, 0x74, 0x65, 0x6c}" multiplexer/multiplexer.go:224

Here's are the configuration files

### Nginx configuration
/etc/nginx/sites-enabled/reverse-proxy.conf

```
server {
        listen 443;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /teleport {
                proxy_pass http://192.168.100.2:443;
        }
}
```

### Teleport configuration file
/etc/teleport.yaml

```
version: v2
teleport:
  nodename: control-center
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: paragon-infra
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: 0.0.0.0:443
  https_keypairs: []
```
