### DISCUSSION TITLE
Connection server to client, and not client to server

### DISCUSSION THREAD

**Discussion by dgiorgio** [gravitational/teleport#15584] [Q&A] [answered]
Is it possible to configure the teleport, to access a machine that does not have access to the teleport server?
For example, a server, which all outbound connection is blocked, and allows only incoming connections.
From what I understand using Teleport, it is that you need to install the teleport agent, and the agent needs to connect to the teleport server.

**Comment by webvictim** [comment, marked as answer]
It's possible to achieve this by not running the Teleport agent and instead using Teleport's integration with `sshd`.

You can configure `sshd` on the target machine to accept Teleport-issued user certificates for authentication and to present a host certificate which Teleport can trust. See our guide here: https://goteleport.com/docs/server-access/guides/openssh/

The only connectivity requirement then is that Teleport's proxy service can make an outbound connection to that machine's configured hostname/IP on port 22.

It isn't currently possible to run the Teleport agent's `ssh_service` process without an outbound connection to either Teleport's auth or proxy service.

**Reply by dgiorgio** [reply]
I managed to log in, but it always asks for a password.
And the Teleport server does not record the session.

**Comment by webvictim** [comment]
In general, having to enter a password to connect via SSH would mean that Teleport's certificates are not being used correctly. You can share your `/etc/ssh/sshd_config` if you like for some more assistance.

You would need to configure proxy recording mode to record sessions over SSH - put this in `/etc/teleport.yaml` and restart:
```yaml
auth_service:
  session_recording: proxy
```

**Comment by dgiorgio** [comment]
when activating the config, 
```
auth_service:
  session_recording: proxy
```
I have this problem in accessing the server.
```
2022-08-24T19:28:24Z ERRO             agent forwarding required in proxy recording mode regular/sshserver.go:2015
```


`/etc/teleport.yaml`
```
#
# A Sample Teleport configuration file.
# Creates a single proxy, auth and node server.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v2
teleport:
  nodename: teleport.xxx.com.br
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: "teleport.xxx.com.br:3025"
  proxy_listener_mode: multiplex
  proxy_checks_host_keys: no
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  public_addr: teleport.xxx.com.br:3022
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  listen_addr: "0.0.0.0:3023"
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: teleport.xxx.com.br:3080
  ssh_public_addr: teleport.xxx.com.br:3023
  tunnel_public_addr: teleport.xxx.com.br:3024
  enabled: "yes"
  https_keypairs: []
  acme: {}
```

`sshd_config` from the server I want to access.
```
#       $OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/local/bin:/usr/bin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

# If you want to change the port on a SELinux system, you have to tell
# SELinux about this change.
# semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
#
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/valid2
HostCertificate /etc/ssh/valid2-cert.pub

# Ciphers and keying
#RekeyLimit default none
Ciphers aes128-ctr,aes128-gcm@openssh.com,aes192-ctr,aes256-ctr,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com

# Logging
#SyslogFacility AUTH
SyslogFacility AUTHPRIV
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin yes
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile      .ssh/authorized_keys

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no
PasswordAuthentication yes

# Change to no to disable s/key passwords
#ChallengeResponseAuthentication yes
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no
#KerberosUseKuserok yes

# GSSAPI options
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no
#GSSAPIEnablek5users no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
# WARNING: 'UsePAM no' is not supported in Red Hat Enterprise Linux and may cause several
# problems.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#UsePrivilegeSeparation sandbox
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#ShowPatchLevel no
#UseDNS yes
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Accept locale-related environment variables
#AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
#AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
#AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
#AcceptEnv XMODIFIERS

# override default of no subsystems
Subsystem       sftp    /usr/libexec/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server

TrustedUserCAKeys /etc/ssh/teleport_user_ca.pub

```

**Comment by dgiorgio** [comment]
when activating `session_recording: proxy`, even servers with agent stopped working.

```
2022-08-24T20:20:43Z ERRO             agent forwarding required in proxy recording mode regular/sshserver.go:2015
2022-08-24T20:20:43Z WARN [WEBSOCKET] "Unable to stream terminal: failed connecting to node valid1. agent forwarding required in proxy recording mode\n." web/terminal.go:470
```

**Reply by webvictim** [reply]
- You'll need to make sure that `forward_agent: true` is set in all your assigned roles. If any of them have `forward_agent: false`, it won't work.

```yaml
kind: role
spec:
  options:
    forward_agent: true
```

- If you're using `tsh ssh`, use `tsh ssh -A` instead.
- If you're using `ssh`, use `ssh -A` instead. You can also set `ForwardAgent yes` in `~/.ssh/config`
