### DISCUSSION TITLE
Can't access Web app with Teleport when HTTP(S)_PROXY is set

### DISCUSSION THREAD

**Discussion by gensi0** [gravitational/teleport#15646] [Q&A]
Hello :wave: 

My question is about setting up teleport to go through my corporate proxy for any outgoing connection. I followed [this](https://goteleport.com/docs/setup/reference/networking/) and when I restart teleport service with `HTTP(S)_PROXY` env vars I can still access my nodes in SSH  but not the apps hosted on the same nodes.

When I try to access an App I get an `Internal Server Error`.

In teleport logs when accessing an app url I see :

```bash
[APP:WEB]   Error forwarding to /, err: unexpected EOF forward/fwd.go:181
```

I have no issue accessing the  Apps when I  comment the proxy variables.

So here is my setup : 

Teleport version is `Teleport v10.1.4`

- One vm with a corporate proxy configured --> `proxy.example.net` (DNS of private address)

- One vm with teleport server on it running with `sytemd` --> `tp.example.net` (public)

This vm also has an private IP capable of reaching the corporate proxy.

Teleport config is : 
```yml
version: v2
teleport:
  nodename: tp.example.net
  data_dir: /var/lib/teleport
  log:
    output: /var/log/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: "192.168.x.x:3000"
auth_service:
  enabled: "yes"
  listen_addr: tp.example.net:3025
  cluster_name: tp.example.net
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: :443
  public_addr: tp.example.net:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: name@example.com
```

In `/lib/systemd/system/teleport.service` I added : 

```bash
Environment="HTTP_PROXY=http://proxy.example.net:XXXX/"
Environment="HTTPS_PROXY=http://proxy.example.net:XXXX/"
```

- Some vms with teleport configured for ssh and/or app access 

Teleport config on those nodes look like this : 

```yml
teleport:
  nodename: someinstance
  auth_token: xxxxxxx 
  ca_pin:
  - sha256:xxxxxxx
  auth_servers:
  - tp.example.net:443
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: yes
  pam:
    enabled: yes
    service_name: "teleport"
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
app_service:
  enabled: yes
  debug_app: false
  apps:
  - name: "appname"
    uri: "http://192.168.X.X:XXXX/"
    public_addr: "appname.tp.example.net"
```

If anyone ever had the same issue or see anything in my configuration that looks suspicious I'll take anything :) Thanks in advance for your time :pray:
