### DISCUSSION TITLE
A role that can only create certain token types

### DISCUSSION THREAD

**Discussion by 0xVox** [gravitational/teleport#15676] [Q&A] [answered]
I've been trying to create a role that is limited to creating certain token types, is it possible to use the `where` field on these, this doesn't work:

```yaml
    - resources:
      - token
      verbs:
      - create
      - update
      - delete
      - read
      - list
      where: contains(resource.spec.roles, "Trusted_cluster")
```

`could not parse 'where' rule: "contains(resource.spec.roles, \"Trusted_cluster\")", error: field name spec.roles is not found`

From the api, this field does exist

```
➜  ~ tctl tokens ls --format yaml
- kind: token
  metadata:
    expires: "2022-08-19T10:53:54.119658874Z"
    name: ***
  spec:
    join_method: token
    roles:
    - Trusted_cluster
  version: v2
```
