### DISCUSSION TITLE
Login issue

### DISCUSSION THREAD

**Discussion by adriangabura** [gravitational/teleport#16196] [Q&A] [answered]
Hi, I get a weird error when I attempt to login

```
ERROR REPORT:
Original Error: *trace.RawTrace
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:167 github.com/gravitational/teleport/lib/httplib.ConvertResponse
        /go/src/github.com/gravitational/teleport/lib/auth/clt.go:269 github.com/gravitational/teleport/lib/auth.(*Client).Get
        /go/src/github.com/gravitational/teleport/lib/auth/clt.go:419 github.com/gravitational/teleport/lib/auth.(*Client).GetCertAuthorities
        /go/src/github.com/gravitational/teleport/lib/client/api.go:3687 github.com/gravitational/teleport/lib/client.(*TeleportClient).GetTrustedCA
        /go/src/github.com/gravitational/teleport/lib/client/api.go:3705 github.com/gravitational/teleport/lib/client.(*TeleportClient).UpdateTrustedCA
        /go/src/github.com/gravitational/teleport/lib/client/api.go:3525 github.com/gravitational/teleport/lib/client.(*TeleportClient).ActivateKey
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1477 main.onLogin
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:984 main.Run
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:434 main.main
        /opt/go/src/runtime/proc.go:250 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message:
```

```
#
# A Sample Teleport configuration file.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v2
teleport:
  nodename: mydomain
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
  web_listen_addr: 0.0.0.0:443
  public_addr: mydomain:443
  https_cert_file: /etc/letsencrypt/live/mydomain/fullchain.pem
  https_key_file: /etc/letsencrypt/live/mydomain/privkey.pem
```

My setup is the following:
```
version: "3.0"

services:
  teleport:
    image: quay.io/gravitational/teleport:10.1.9
    hostname: localhost
    container_name: teleport
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:443"
```

I run this behind a HAProxy with SSL pass-through.

The login command
```
tsh login --proxy=mydomain:443,443 --user=gamma1138
```

I am using LetsEncrypt for the webui

--debug says:
```
DEBU [KEYAGENT]  Validated host mydomain:443. client/keyagent.go:405
INFO [CLIENT]    Successful auth with proxy mydomain:443. client/api.go:3042
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/alpha1138/.tsh/keys/mydomain/gamma1138-x509.pem" valid until "2022-09-08 01:05:22 +0000 UTC". client/keystore.go:323

```
