### DISCUSSION TITLE
How to add OIDC config from helm chart of teleport cluster

### DISCUSSION THREAD

**Discussion by ahsan-n** [gravitational/teleport#16539] [Q&A]
Hi, we are using teleport-cluster chart 9.3.3 .  We have managing web apps from helm chart's configmap sucessfully. Now we have to integrate oidc config in teleport-cluster, trying to achive same with helm chart but struggling to understand where to put the configurations exactly? 

This is the yaml file we generated but it has to be converted w.r.t to configmap format:

```yaml
kind: oidc
version: v2
metadata:
  name: teleport_oidc_connector
spec:
  redirect_url: "https://prefix.suffix.com/"
  client_id: <clientID>
  # connector display name that will be appended to the title of "Login with"
  # button on the cluster login screen so it will say "Login with Google".
  # Teleport will provide custom CSS for 'Google'.
  display: ORG SSO
  client_secret: sdfihwfi3427hdjkanfiu32h
  issuer_url: https://identity-relm.suffix.com/realms/identity-realm
  scope: ["openid", "profile", "email", "groups"]
  claims_to_roles:
    - claim: "groups"
      value: "infra"
      roles: ["editor"]
```
