### DISCUSSION TITLE
app_service first record does not look like a TLS handshake

### DISCUSSION THREAD

**Discussion by heywoodlh** [gravitational/teleport#16707] [Q&A]
Hey all,

I am running into an issue with app_service where it complains about TLS issues when I am trying to proxy a plain HTTP service I have running. After going to my defined app URL, it just ends with HTTP status code 500 (Internal Service Error).

Here's my app_service config:

```
app_service:
    enabled: yes
    # Teleport provides a small de
bug app that can be used to make s
ure application
    # access is working correctly.
 It'll output JWTs so it can be us
eful
    # when extending your applicat
ion.
    debug_app: true
    # This section contains definitions of all applications proxied by this
    # service. It can contain multiple items.
    apps:
      # Name of the application. Used for identification purposes.
    - name: "cloudtube"
      # URI and port the application is available at.
      uri: "http://10.50.50.1:8081"
      # Optional application public address to override.
      public_addr: "cloudtube.heywoodlh.tech"
```

Here's the error:

```
eleport/lib/srv/app.(*Server).HandleConnection
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/transport.go:282 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:580 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: TLS handshake failed
        tls: first record does not look like a TLS handshake] app/server.go:585
```

Why is it failing with a TLS handshake error when the application Teleport is attempting to connect to is a plain HTTP endpoint?

P.S. I just set up Teleport today and I love it so much. What a great product 😁

**Comment by webvictim** [comment]
This is an issue with the `app_service` itself attempting to connect back to the Teleport proxy, rather than connecting to the HTTP application. Can you share the rest of your `/etc/teleport.yaml` file? Redact any tokens.

**Comment by heywoodlh** [comment]
```
version: v2
teleport:
  nodename: localhost
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 127.0.0.1:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: "0.0.0.0:443"
  public_addr: "teleport.domain.com:443"
  https_keypairs: 
  - key_file: "/etc/letsencrypt/live/domain.com/privkey.pem"
    cert_file: "/etc/letsencrypt/live/domain.com/fullchain.pem"
  - key_file: "/etc/letsencrypt/live/teleport.domain.com/privkey.pem"
    cert_file: "/etc/letsencrypt/live/teleport.domain.com/fullchain.pem"
  acme: {}
app_service:
    enabled: yes
    # Teleport provides a small debug app that can be used to make sure application
    # access is working correctly. It'll output JWTs so it can be useful
    # when extending your application.
    debug_app: true
    # This section contains definitions of all applications proxied by this
    # service. It can contain multiple items.
    apps:
      # Name of the application. Used for identification purposes.
    - name: "cloudtube"
      # URI and port the application is available at.
      uri: "http://127.0.0.1:8081"
      # Optional application public address to override.
      public_addr: "cloudtube.domain.com"
      # Name of the application. Used for identification purposes.
    - name: "cockpit"
      uri: "https://10.50.50.22"
      public_addr: "cockpit.domain.com"
      insecure_skip_verify: true
```
