### DISCUSSION TITLE
Minimum Viable Node Config

### DISCUSSION THREAD

**Discussion by corkrean** [gravitational/teleport#17011] [Show and tell]
The following is a bare-bones configuration to join a node to a Teleport cluster. This file should be stored at /etc/teleport.yaml

```
teleport:
  auth_token: <generated by the following command    tctl tokens add --type=node   >
  auth_servers:
  - <proxy url of the auth server> 
  ca_pin: <this is optional, but recomended. Generated with the following command: export CA_PIN=$(tctl status | awk '/CA pin/{print $3}')    >
auth_service:
  enabled: no
ssh_service:
  enabled: yes
proxy_service:
  enabled: no
```
