### DISCUSSION TITLE
Lost data

### DISCUSSION THREAD

**Discussion by soufianeelbeggar** [gravitational/teleport#17562] [Q&A]
Hello,
I installed teleport as a docker container, and I pull the new container and removed the previous one, I was thinking that keeping volumes will protect the data but I lost all the servers and users.
Any help to restore it? or replacing the ca_pin in the docker container?
Thank you!

**Comment by zmb3** [comment]
The location of the data depends on the backend you're using.

If you're using the sqlite backend, then the cluster data is stored in the `data_dir` that you've configured. Using a volume to persist that directory is the recommended approach.

**Reply by soufianeelbeggar** [reply]
I used volume but I don't know what happened I lost all users and servers.
NB: I upgraded from version 10.0.2 to 10.3.2.
Is there a way to get all the already installed servers?

**Reply by soufianeelbeggar** [reply]
Here is the docker-compose file I'm using  (I just changed the image as you can see it's commented, and that's how I lost my added servers):

```
version: '2'
services:
  configure:
    image: quay.io/gravitational/teleport:10.0.2
    #image: public.ecr.aws/gravitational/teleport:10.3.2
    container_name: teleport-configure
    entrypoint: /bin/sh
    hostname: myhost.com
    command: -c "if [ ! -f /etc/teleport/teleport.yaml ]; then teleport configure > /etc/teleport/teleport.yaml; fi"
    volumes:
      - ./teleport/config:/etc/teleport

  teleport:
    image: quay.io/gravitational/teleport:10.0.2
    #image: public.ecr.aws/gravitational/teleport:10.3.2
    command: "--insecure-no-tls"
    container_name: teleport
    entrypoint: /bin/sh
    hostname: myhost.com
    command: -c "sleep 1 && /bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
      - "443:3080"
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/
    depends_on:
      - configure
```

One of the servers that I have access to shows, after running ```sudo systemctl status teleport```:

```
Connecting to the cluster myhost.com with TLS client certificate. pid:156109.1 service/connect.go:>
"Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no ...
```

**Reply by webvictim** [reply]
What's in `./teleport/data` on disk? Your config looks OK - your data should have been persisted across the upgrade.

Also, what's in `./teleport/config`? Specifically `./teleport/config/teleport.yaml`?

**Reply by soufianeelbeggar** [reply]
In ```./teleport/data``` exists ``` backend  host_uuid  log  proc  webproxy_cert.pem  webproxy_key.pem```

In ```./teleport/config ``` exists ```teleport.yaml```

```teleport.yaml``` file contains:
```
version: v2
teleport:
  nodename: myhost.com
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
  https_cert_file: /etc/letsencrypt/live/myhost.com/fullchain.pem
  https_key_file: /etc/letsencrypt/live/myhost.com/privkey.pem
```
