### DISCUSSION TITLE
tsh login fails

### DISCUSSION THREAD

**Discussion by jegesm** [gravitational/teleport#17790] [Q&A] [answered]
Hi Everyone,
we encountered a problem, namely that when we try to login from a terminal with 
`tsh login --proxy=domain.teleport:443 --debug --user=wfct0p
`
we get the following error:

```
wfct0p@work:~ $ tsh login --proxy=domain.teleport:443 --debug --user=wfct0p 
DEBU [CLIENT]    open /home/wfct0p/.tsh/domain.teleportyaml: no such file or directory client/api.go:1055
INFO [CLIENT]    no host login given. defaulting to wfct0p client/api.go:1417
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:3915
DEBU [CLIENT]    not using loopback pool for remote proxy addr: domain.teleport443 client/api.go:3874
DEBU             Attempting GET domain.teleport443/webapi/ping webclient/webclient.go:115
Enter password for Teleport user wfct0p:
Enter your OTP token:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: domain.teleport443 client/api.go:3874
DEBU [CLIENT]    HTTPS client init(proxyAddr=domain.teleport:443, insecure=false) client/weblogin.go:252
DEBU [KEYAGENT]  Adding CA key for domain.teleport client/keyagent.go:324
DEBU [KEYSTORE]  Adding known host domain.teleport with proxy domain.teleport and key: SHA256:O0WHH0e51/XKdKgOtKlesLs4i79CrD7BUWFULASf4R0 client/keystore.go:595
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/wfct0p/.tsh/keys/domain.teleport/wfct0p-x509.pem" valid until "2022-10-26 02:18:22 +0000 UTC". client/keystore.go:319
DEBU [KEYAGENT]  Deleting obsolete stored key with index {ProxyHost:domain.teleport Username:wfct0p ClusterName:domain.teleport}. client/keyagent.go:525
INFO [KEYAGENT]  Loading SSH key for user "wfct0p" and cluster "domain.teleport". client/keyagent.go:202
INFO [CLIENT]    Connecting to proxy=domain.teleport:443 login="wfct0p" using TLS Routing client/api.go:2962
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/wfct0p/.tsh/keys/domain.teleport/wfct0p-x509.pem" valid until "2022-10-26 02:42:20 +0000 UTC". client/keystore.go:319
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:297
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/wfct0p/.tsh/keys/domain.teleport/wfct0p-x509.pem" valid until "2022-10-26 02:42:20 +0000 UTC". client/keystore.go:319
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg6K5enAdgooRmA2B9u4cnoqZZzF4QJnsKC+YA0oCWL8gAAAADAQABAAABAQCke+OQcK5jPoEzB1VA3eL8FuQsTd07UGkhez9Zw27OV4EM3Aon1uyxOrSChNeANgzkvojjJt5u0t/Y6KuRXceRJRgG7z4zk8j172Yx2h/sw/p8hBhuJxe3giadZomom6zMDnWrrscChznF4kWRWXRF+oxKeZVBFRRo6PKEH2BGLp4o9JyU4X0xBZBI0jMEwlf5QKfGaBHoDCPWiX+PVvxphBxCO0oSNytukPu7gByAEYzlS5to0iyG128RgDZqbJBB3b7wEgxWCMDP8MSpQvaPOsQLjSi0SyRKZJKFVFdPoKfDg6rz7i6yPdikfMCi3rw1+FYzHuP23F9aflDnGPq3AAAAAAAAAAAAAAACAAAAAAAAAPMAAAA4MzlmOTQ2NTYtNTE0OS00OTJhLWE3MTYtNWIxN2Y2MTE2ZTM0LnRlbGVwb3J0LnZvLmVsdGUuaHUAAAAkMzlmOTQ2NTYtNTE0OS00OTJhLWE3MTYtNWIxN2Y2MTE2ZTM0AAAAJ3RlbGVwb3J0LnZvLmVsdGUuaHUudGVsZXBvcnQudm8uZWx0ZS5odQAAABN0ZWxlcG9ydC52by5lbHRlLmh1AAAACWxvY2FsaG9zdAAAAAkxMjcuMC4wLjEAAAADOjoxAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAY1fdzP//////////AAAAAAAAAFMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAXAAAAE3RlbGVwb3J0LnZvLmVsdGUuaHUAAAAPeC10ZWxlcG9ydC1yb2xlAAAACQAAAAVQcm94eQAAAAAAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQD2NdQA8of+M0AhEXATVGjjvwRi6Fj2Pyg/OXkCcNvFiu5UkpOExfdB1Clw1P0kth8FIU94eQ85uC2P6JlFC9yZrttFXojCzQMN9GBW9L2JUVRPYlrguhU+oE8RPTrDbIOokJUwOE7ESSo39r8fgowTGmyZ3JnBra67eW31Z/8YakEoMuO47TnfYNmsBhZwrE9fec/+xTzzQ5S/CPXdwkU9d+J2oP+49MlippLirvmmGYS7ENqg/Oanrz0Fsix8zK7IhOqbxqiwY9Vf917Mze2B+uvPfi/0Yf3u9QUa9z1EPIgCS0fGzTgua7dU07XlS/n4NvNbSOhktzvqg263RDm9AAABFAAAAAxyc2Etc2hhMi01MTIAAAEAHCBtf6vd2uoF4W4LJM58l9iOVVHBhgGaylAKsOHEQJSEV/9RmyQ/mFWUO2tPnQo+Ye5S1F3shkbSbaJZPs1VL0thrhEMQOR7S9pgZnv/VAJ1cvF1mwBFm6yJaIMS7x8941gKd7n2dgUA/0J5cN/RCe0JvjnD6NYe5u0YR0jS/59Iq7nQdniVdvKqxVkZFajdK2s68rqT8MstBuzq7QtVOjzR7qJvVsidXR1KrZ2Q189akniZjVtCJP7TVF4Q785sz4H7kveoj9V1MJQKG10hVCN44efmFJO0/UOBJ+iUu7KeqR77L7GmejUtoJNXEnE7nmdnV3iNDMa0H5hLirdSIw==\n." client/keyagent.go:376
DEBU [KEYAGENT]  Validated host domain.teleport:443. client/keyagent.go:382
INFO [CLIENT]    Successful auth with proxy domain.teleportu:443. client/api.go:2967
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/wfct0p/.tsh/keys/domain.teleport/wfct0p-x509.pem" valid until "2022-10-26 02:42:20 +0000 UTC". client/keystore.go:319

ERROR REPORT:
Original Error: *trace.ConnectionProblemError Get &#34;https://teleport.cluster.local/v2/authorities/host?load_keys=false&#34;: x509: certificate is valid for ingress.local, not 74656c65706f72742e766f2e656c74652e6875.teleport.cluster.local
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:158 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:265 github.com/gravitational/teleport/lib/auth.(*Client).Get
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:415 github.com/gravitational/teleport/lib/auth.(*Client).GetCertAuthorities
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3620 github.com/gravitational/teleport/lib/client.(*TeleportClient).GetTrustedCA
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3638 github.com/gravitational/teleport/lib/client.(*TeleportClient).UpdateTrustedCA
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3458 github.com/gravitational/teleport/lib/client.(*TeleportClient).ActivateKey
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1400 main.onLogin
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:907 main.Run
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:412 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: Get &#34;https://teleport.cluster.local/v2/authorities/host?load_keys=false&#34;: x509: certificate is valid for ingress.local, not 74656c65706f72742e766f2e656c74652e6875.teleport.cluster.local
```

Environment:

    Teleport version (use teleport version):  Teleport v10.1.4 git:v10.1.4-0-gf095c6f go1.18.3
    Tsh version (use tsh version): Teleport v10.1.4 git:v10.1.4-0-gf095c6f go1.18.3
    OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS (Bionic Beaver)

teleport.yaml config file:
```
version: v2
teleport:
  nodename: domain.teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  auth_servers:
    - 127.0.0.1:3025
auth_service:
  enabled: "yes"
  cluster_name: "domain.teleport"
  listen_addr: 0.0.0.0:3025
  public_addr: domain.teleport:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs:
    - key_file: /certs/tls.key
      cert_file: /certs/tls.crt
  acme: {}
  web_listen_addr: 0.0.0.0:443
  public_addr: domain.teleport:443
  tunnel_listen_addr: 0.0.0.0:3024
  ssh_public_addr: domain.teleport:3023
```

We use the docker images from hub.docker.com and run it on a kubernetes cluster. I can share the yaml files for the ingress-nginx, statefulset and service if needed.

The web ui is accessible at "domain.teleport" from the browser, we can login to it and if a node is added to the cluster it is possible to login into it via ssh.

Can someone help out here? What do we miss here?

If I use --insecure flag then I get:
```
...
DEBU [KEYAGENT]  Validated host domain.teleport:443. client/keyagent.go:382
INFO [CLIENT]    Successful auth with proxy domain.teleport:443. client/api.go:2967
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/wfct0p/.tsh/keys/domain.teleport/wfct0p-x509.pem" valid until "2022-10-26 03:10:24 +0000 UTC". client/keystore.go:319

ERROR REPORT:
Original Error: *trace.NotFoundError object not found
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:167 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:265 github.com/gravitational/teleport/lib/auth.(*Client).Get
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:415 github.com/gravitational/teleport/lib/auth.(*Client).GetCertAuthorities
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3620 github.com/gravitational/teleport/lib/client.(*TeleportClient).GetTrustedCA
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3638 github.com/gravitational/teleport/lib/client.(*TeleportClient).UpdateTrustedCA
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3458 github.com/gravitational/teleport/lib/client.(*TeleportClient).ActivateKey
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1400 main.onLogin
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:907 main.Run
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:412 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: object not found

```

Thanks in advance for any replies! :)

**Comment by webvictim** [comment, marked as answer]
This is happening because Teleport is behind an ingress, which is not supported when using multiplexing mode.

See the docs here for some instructions on how it works: https://goteleport.com/docs/architecture/tls-routing/

You can disable multiplexing, but you will need some plain TCP ports opening (i.e. by using a LoadBalancer)

If you install using our `teleport-cluster` Helm chart it automatically configures a LoadBalancer service for you.

**Reply by jegesm** [reply]
Thanks for the quick answer!

I didn't get how the LoadBalancer alone would solve the problem, but seemed reasonable, that it is needed
(I checked the teleport-cluster Helm chart install in dry-run but unfortunately it didn't bring me any closer to the solution)

1. Following this line of thought I've disabled mulitplexing: `proxy_listener_mode: separate` and restarted the teleport service. Now it is supposed to be listening on the `ssh_public_addr: domain.teleport:3023`
So I've set the LoadBalancer as you suggested:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: teleport-ssh
  namespace: teleport
spec:
  type: LoadBalancer
  selector:
    app: teleport
  ports:
    - name: ssh
      protocol: TCP
      port: 3023
      targetPort: 3023
    - name: tunnel
      protocol: TCP
      port: 3024
      targetPort: 3024
    - name: auth
      protocol: TCP
      port: 3025
      targetPort: 3025
  externalIPs: 
  - ip1
  - ip2
  - ip3
```

2. I've searched for the method to expose mulitple ports on kubernetes ingress-nginx and found these
* https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
* https://www.ibm.com/docs/en/netcoolomnibus/8?topic=private-exposing-probe-service

Modify ingress to accept ssh conection on the same path:
Add --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services (and --udp-services-configmap) to ingress-nginx deployment to support forwarding of traffic on different ports and add ports to the deployment (or daemonset?)
`> kubectl edit -n ingress-nginx deployment ingress-nginx-controller`
```
        - containerPort: 3023
          name: ssh-teleport
          protocol: TCP
        - containerPort: 3024
          name: tunnel-teleport
          protocol: TCP
        - containerPort: 3025
          name: auth-teleport
          protocol: TCP
```

At this point connections were refused, but at least they got up to the teleport's pod.

After some googling I realized that there was still one thing missing:
```
proxy_service:
  ...
  listen_addr: 0.0.0.0:3023
  ....
````

After a restart everything was working fine! :)

Just for the sake of completeness I post my configuration file as well:
```
version: v2
teleport:
  nodename: domain.teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  auth_servers:
    - 127.0.0.1:3025
auth_service:
  enabled: "yes"
  cluster_name: "domain.teleport"
  listen_addr: 0.0.0.0:3025
  public_addr: domain.teleport:3025
  proxy_listener_mode: separate
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs:
    - key_file: /certs/tls.key
      cert_file: /certs/tls.crt
  acme: {}
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  public_addr: domain.teleport:443
  ssh_public_addr: domain.teleport:3023
  tunnel_listen_addr: 0.0.0.0:3024

```
