### DISCUSSION TITLE
Enabling Persistent Volume with Default Teleport Cluster Deployment in EKS

### DISCUSSION THREAD

**Discussion by stevenGravy** [gravitational/teleport#17997] [Show and tell]
With the version of EKS 1.23 you will no longer get automatic persistent volumes enabled.  The default Teleport-Cluster helm chart setting uses a persistent volume.  The HA version does not require persistent volumes.  To enable the `gp2` persistent volumes the ebs csi driver add on enablement will allow the persistent volume usage.

Here is an example of apply a add-on to a existing cluster:
https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html

To create a cluster with EBS enabled in `eksctl` here is an example.  To get the driver versions that are supported you can run this command to get the supported `aws-ebs-csi-driver` that matches to the k8s version.
`aws eks describe-addon-versions --addon-name aws-ebs-csi-driver --kubernetes-version 1.23`

cluster.yaml:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ent-cluster
  region: us-east-1
  version: "1.23"
 
iam:
  withOIDC: true

addons:
- name: aws-ebs-csi-driver
  version: v1.11.4-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
 
managedNodeGroups:
  - name: managed-ng-2
    instanceType: t3.medium
    minSize: 2
    maxSize: 3
```

Create cluster with configuration: 
`eksctl create cluster -f cluster.yaml`
