### DISCUSSION TITLE
How to properly setup AKS discovery and kubernetes service?

### DISCUSSION THREAD

**Discussion by PJHRobles** [gravitational/teleport#18507] [Q&A]
I have been trying to follow the guide here https://goteleport.com/docs/kubernetes-access/discovery/azure/. Trying to setup teleport AKS auto-discovery but `kubernetes_service` is failing to start. Discovery is able to return the clusters as checked by `tctl get kube_clusters`.

#### `tctl get kube_clusters`
```yaml
kind: kube_cluster
metadata:
  description: Azure AKS cluster "<cluster name>" in southeastasia
  id: <id>
  labels:
    env: dev
    region: southeastasia
    resource-group: <rg>
    subscription-id: <sub>
    teleport.dev/origin: cloud
  name: <cluster name>
spec:
  aws: {}
  azure:
    resource_group: <rg>
    resource_name: <cluster name>
    subscription_id: <sub>
    tenant_id: <tenant>
version: v3
```

I am encountering the error below.
#### Error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x237fb29]
goroutine 1160 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0xc00151a960?)
        k8s.io/client-go@v0.25.2/kubernetes/clientset.go:422 +0x29
github.com/gravitational/teleport/lib/kube/proxy.extractKubeCreds({0x7373a30, 0xc001d4b740}, {0xc00151a960, 0x1c}, 0x0, {0x73ac930, 0xc000189ce0}, 0x6a834e0)
        github.com/gravitational/teleport/lib/kube/proxy/auth.go:144 +0xf4
github.com/gravitational/teleport/lib/kube/proxy.(*dynamicKubeCreds).renewClientset(0xc001296480, {0x73b2228, 0xc0015a4fc0})
        github.com/gravitational/teleport/lib/kube/proxy/kube_creds.go:173 +0xe7
github.com/gravitational/teleport/lib/kube/proxy.newDynamicKubeCreds({0x7373a30?, 0xc001d4b740}, {0x73b2228?, 0xc0015a4fc0}, {0x73ac930?, 0xc000189ce0}, 0xc001ae1890, 0x6a834e0)
        github.com/gravitational/teleport/lib/kube/proxy/kube_creds.go:117 +0x17c
github.com/gravitational/teleport/lib/kube/proxy.getAzureCredentials({0x7373a30, 0xc001d4b740}, {0x73a6290?, 0xc001a345a0?}, {0x73b2228, 0xc0015a4fc0}, 0x8cc5da?, 0xc0001b63f0?)
        github.com/gravitational/teleport/lib/kube/proxy/cluster_details.go:104 +0x8a
github.com/gravitational/teleport/lib/kube/proxy.getKubeClusterCredentials({0x7373a30, 0xc001d4b740}, {0x73a6290, 0xc001a345a0}, {0x73b2228?, 0xc0015a4fc0?}, 0xc001478600?, 0x734a3c0?)
        github.com/gravitational/teleport/lib/kube/proxy/cluster_details.go:91 +0x1ab
github.com/gravitational/teleport/lib/kube/proxy.newClusterDetails({0x7373a30, 0xc001d4b740}, {0x73a6290?, 0xc001a345a0?}, {0x73b2228?, 0xc0015a4fc0?}, 0xc000189ce0, 0x5f7a8c0?)
        github.com/gravitational/teleport/lib/kube/proxy/cluster_details.go:51 +0x5f
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).registerKubeCluster(0xc00152b080, {0x7373a30, 0xc001d4b740}, {0x73b2228?, 0xc0015a4fc0?})
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:180 +0x74
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).onCreate(0x61b929d?, {0x7373a30, 0xc001d4b740}, {0x739b630?, 0xc0015a4fc0})
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:130 +0xde
github.com/gravitational/teleport/lib/services.(*Reconciler).processNewResource(0xc001d82be0, {0x7373a30, 0xc001d4b740}, 0xc0010f7cc0?, {0x739b630, 0xc0015a4fc0})
        github.com/gravitational/teleport/lib/services/reconciler.go:149 +0xab7
github.com/gravitational/teleport/lib/services.(*Reconciler).Reconcile(0xc001d82be0, {0x7373a30, 0xc001d4b740})
        github.com/gravitational/teleport/lib/services/reconciler.go:116 +0x397
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startReconciler.func1()
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:69 +0x176
created by github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startReconciler
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:49 +0x36a
teleport.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
teleport.service: Failed with result 'exit-code'.
```

#### Teleport Version
```
Teleport v11.0.3 git:v11.0.3-0-g6f0eeef go1.19.2
```

#### `/etc/teleport.yaml`
```yaml
version: v3                                                
teleport:                                                  
  nodename: node-x                                                                            
  data_dir: /var/lib/teleport              
  log:
    output: stderr
    severity: INFO
    format:
      output: json
  ca_pin: ""
  diag_addr: ""
  join_params:
    token_name: "/tmp/token-kube"
    method: token
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: <cluster-name>
  proxy_listener_mode: multiplex
db_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
  azure:
  - types: ["redis"]
    regions: ["southeastasia"]
    subscriptions: ["<sub>"] 
    resource_groups: ["r<rg>"]
    tags:
      "*": "*"
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  kube_listen_addr: 0.0.0.0:3027
  public_addr: <internal address>:443
  https_keypairs:
  - key_file: /var/lib/teleport/privkey.pem
    cert_file: /var/lib/teleport/fullchain.pem
  acme: {}
discovery_service:
  enabled: "yes"
  azure:
  - types: ["aks"]
    regions: ["southeastasia", "eastasia"]
    subscriptions: ["<sub>"] 
    resource_groups: ["<rg>"]
kubernetes_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3026
  resources:
  - labels:
      "*": "*"
```
^Separate issue but the 11.x version doesn't allow skipping `kubernetes_service.listen_addr` even though we're using the proxy.

#### Permissions
Assigned to both user and system-assigned identity attached to the VM with scope the subscription where the AKS cluster lives
```json
[
            {
                "actions": [
                    "Microsoft.Cache/redis/read",
                    "Microsoft.Cache/redis/listKeys/action",
                    "Microsoft.Cache/redisEnterprise/read",
                    "Microsoft.Cache/redisEnterprise/databases/read",
                    "Microsoft.Cache/redisEnterprise/databases/listKeys/action",
                    "Microsoft.ContainerService/managedClusters/read",
                    "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action",
                    "Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action"
                ],
                "notActions": [],
                "dataActions": [
                    "Microsoft.ContainerService/managedClusters/users/impersonate/action",
                    "Microsoft.ContainerService/managedClusters/authorization.k8s.io/selfsubjectaccessreviews/write",
                    "Microsoft.ContainerService/managedClusters/serviceaccounts/impersonate/action",
                    "Microsoft.ContainerService/managedClusters/pods/read",
                    "Microsoft.ContainerService/managedClusters/authorization.k8s.io/selfsubjectrulesreviews/write",
                    "Microsoft.ContainerService/managedClusters/groups/impersonate/action"
                ],
                "notDataActions": []
            }
        ]
```

#### Kubernetes RBAC
Test cluster uses Azure AD + Kubernetes RBAC so I have manually created the `ClusterRole` and binding as well
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    argocd.argoproj.io/instance: teleport-iam
  name: teleport
rules:
  - apiGroups:
      - ''
    resources:
      - users
      - groups
      - serviceaccounts
    verbs:
      - impersonate
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    argocd.argoproj.io/instance: teleport-iam
  name: teleport
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teleport
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: <Azure AD group ID where teleport VM user/system-assigned identities belong to> # also tried the group name
```

Is there anything I'm missing?

**Comment by scottpgallagher** [comment]
Can you make sure there aren't multiple teleport services trying to run at the same time? Doing some googling that error sometimes comes up when the port is being used already.

**Reply by PJHRobles** [reply]
I have tried leaving just discovery and kube service on but seems this isn't possible with the v3 config?
```
User Message: initialization failed
        configuration error
                config: auth_server or proxy_server is required
teleport.service: Main process exited, code=exited, status=1/FAILURE
teleport.service: Failed with result 'exit-code'.
teleport.service: Scheduled restart job, restart counter is at 5.
Stopped Teleport Service.
teleport.service: Start request repeated too quickly.
teleport.service: Failed with result 'exit-code'.
Failed to start Teleport Service.
```
 Leaving the bare minimum with auth, proxy, discovery, and kube still gets me the same error

**Reply by PJHRobles** [reply]
Have tried running a separate process with the v2 config on the example - still getting the below error
```
2022-11-17T00:50:58Z DEBU [DISCOVERY] Reconciling 1 current resources with 1 new resources. pid:1117936.1 services/reconciler.go:102
2022-11-17T00:50:58Z DEBU [DISCOVERY] kube_cluster <cluster-name> is already registered. pid:1117936.1 services/reconciler.go:182
2022-11-17T00:50:59Z DEBU [KUBERNETE] Checking Kubernetes impersonation permissions. cluster:<cluster-name> pid:1117936.1 proxy/auth.go:143
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x237fb29]

goroutine 343 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0xc0014ad740?)
        k8s.io/client-go@v0.25.2/kubernetes/clientset.go:422 +0x29
github.com/gravitational/teleport/lib/kube/proxy.extractKubeCreds({0x7373a30, 0xc0014cb180}, {0xc0014ad740, 0x1c}, 0x0, {0x73ac930, 0xc000734770}, 0x6a834e0)
        github.com/gravitational/teleport/lib/kube/proxy/auth.go:144 +0xf4
github.com/gravitational/teleport/lib/kube/proxy.(*dynamicKubeCreds).renewClientset(0xc00158ed80, {0x73b2228, 0xc001409880})
        github.com/gravitational/teleport/lib/kube/proxy/kube_creds.go:173 +0xe7
github.com/gravitational/teleport/lib/kube/proxy.newDynamicKubeCreds({0x7373a30?, 0xc0014cb180}, {0x73b2228?, 0xc001409880}, {0x73ac930?, 0xc000734770}, 0xc0015a6150, 0x6a834e0)
        github.com/gravitational/teleport/lib/kube/proxy/kube_creds.go:117 +0x17c
github.com/gravitational/teleport/lib/kube/proxy.getAzureCredentials({0x7373a30, 0xc0014cb180}, {0x73a6290?, 0xc000ce05a0?}, {0x73b2228, 0xc001409880}, 0x8cc5da?, 0xc0008662a0?)
        github.com/gravitational/teleport/lib/kube/proxy/cluster_details.go:104 +0x8a
github.com/gravitational/teleport/lib/kube/proxy.getKubeClusterCredentials({0x7373a30, 0xc0014cb180}, {0x73a6290, 0xc000ce05a0}, {0x73b2228?, 0xc001409880?}, 0xc000581cb0?, 0x734a3c0?)
        github.com/gravitational/teleport/lib/kube/proxy/cluster_details.go:91 +0x1ab
github.com/gravitational/teleport/lib/kube/proxy.newClusterDetails({0x7373a30, 0xc0014cb180}, {0x73a6290?, 0xc000ce05a0?}, {0x73b2228?, 0xc001409880?}, 0xc000734770, 0x5f7a8c0?)
        github.com/gravitational/teleport/lib/kube/proxy/cluster_details.go:51 +0x5f
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).registerKubeCluster(0xc000478000, {0x7373a30, 0xc0014cb180}, {0x73b2228?, 0xc001409880?})
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:180 +0x74
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).onCreate(0x61b929d?, {0x7373a30, 0xc0014cb180}, {0x739b630?, 0xc001409880})
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:130 +0xde
github.com/gravitational/teleport/lib/services.(*Reconciler).processNewResource(0xc001582230, {0x7373a30, 0xc0014cb180}, 0xc0015a8160?, {0x739b630, 0xc001409880})
        github.com/gravitational/teleport/lib/services/reconciler.go:149 +0xab7
github.com/gravitational/teleport/lib/services.(*Reconciler).Reconcile(0xc001582230, {0x7373a30, 0xc0014cb180})
        github.com/gravitational/teleport/lib/services/reconciler.go:116 +0x397
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startReconciler.func1()
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:69 +0x176
created by github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startReconciler
        github.com/gravitational/teleport/lib/kube/proxy/watcher.go:49 +0x36a
```

Config used below
```yaml
version: v2
teleport:
  log:
    severity: DEBUG
  pid_file: /var/run/teleport-kube.pid
  join_params:
    token_name: "/tmp/token-kube"
    method: token
  auth_servers:
  - "<address>:443"
auth_service:
  enabled: off
proxy_service:
  enabled: off
ssh_service:
  enabled: off
discovery_service:
  enabled: "yes"
  azure:
  - types: ["aks"]
    regions: ["southeastasia", "eastasia"]
    subscriptions: ["<sub>"]
    resource_groups: ["<rg>"]
kubernetes_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
```
