### DISCUSSION TITLE
Example Teleport HA deployment on Azure AKS

### DISCUSSION THREAD

**Discussion by nivasomu** [gravitational/teleport#18547] [Show and tell]
Here is the example deployment runbook for deploying  Teleport on Azure AKS deployment along with etcd and cert-manager,

**Important:**  _This is just an example to show how to deploy teleport on Azure AKS clusters. etcd is a backend dependency of the teleport cluster so it's your responsibility to manage them and the run-book is just an example. Please make sure you change the values for the deployment according to your deployment needs._ 

**Prerequisite**
1. AKS cluster
2. helm
3. Domain name

Here is the documentation for the etcd - https://etcd.io/docs/

**1. Create a new namespace for teleport**

`kubectl create namespace teleport`

**2. Deploy cert-manager**

This following command creates a namespace for cert-manager and deploys the Custom Resource Definition

`kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.yaml`

**3. Deploy the issuer in teleport namespace**
`kubectl apply -f issuer.yaml`

  Here is the example `issuer.yaml` file
  ```
  apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: selfsigned-issuer
    namespace: teleport
  spec:
    selfSigned: {} 
  ```
**4. Create the certificate for etcd**

`kubectl apply -f etcd-client.yaml`

here is the example etcd-client.yaml file
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
  namespace: teleport
spec:
  commonName: etcd-client
  dnsNames:
  - etcd-client
  - etcd-0.etcd-headless.teleport.svc.cluster.local
  - etcd-0.etcd-headless.teleport.svc
  - etcd-0
  - etcd-1.etcd-headless.teleport.svc.cluster.local
  - etcd-1.etcd-headless.teleport.svc
  - etcd-1
  - etcd-2.etcd-headless.teleport.svc.cluster.local
  - etcd-2.etcd-headless.teleport.svc
  - etcd-2
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: etcd-client
  subject:
    organizations:
    - azure
  usages:
  - server auth
  - client auth
  ```
  ensure that the secret etcd-client gets created by running the command  `kubectl get secret -n teleport`
  
**5. Deploy the etcd**

`helm repo add bitnami https://charts.bitnami.com/bitnami`

`helm install etcd bitnami/etcd -n teleport -f etcd-values.yaml`

here is the values.yaml file for the etcd
```
clusterDomain: cluster.local
replicaCount: 3
auth:
  rbac:
    create: false
  client:
    secureTransport: true
    existingSecret: etcd-client
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    caFilename: "ca.crt"
resources:
  requests:
    cpu: 0.2
    memory: 0.5Gi
 ```
**6. Create the license secret (Optional)**
 
`kubectl --namespace teleport create secret generic license --from-file=<license file path>`

**7. Create the teleport configmap**

_Note: make sure the file name is `teleport.yaml` because the teleport will look for that specific file name_ 

`kubectl create configmap dev-teleport --from-file=teleport.yaml -n teleport`

here is an example teleport.yaml file,
```
version: v2
teleport:
  log:
    severity: DEBUG
    output: stderr
    format:
      output: text
      extra_fields: ["timestamp","level","component","caller"]
  storage:
    type: etcd
    peers: ["https://etcd-0.etcd-headless.teleport.svc.cluster.local:2379", "https://etcd-1.etcd-headless.teleport.svc.cluster.local:2379", "https://etcd-2.etcd-headless.teleport.svc.cluster.local:2379"]
    prefix: /teleport/
    tls_key_file: /var/lib/etcd_client/tls.key
    tls_cert_file: /var/lib/etcd_client/tls.crt
    tls_ca_file: /var/lib/etcd_client/ca.crt
auth_service:
  enabled: true
  cluster_name: example.teleport-onboarding.com
  license_file: '/var/lib/license/license.pem' # this is optional
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: "off"
kubernetes_service:
  enabled: true
  listen_addr: 0.0.0.0:3027
  kube_cluster_name: teleport # this has to be changed
proxy_service:
  public_addr: 'example.teleport-onboarding.com:443' # this has to be changed
  # %{ if proxy_mode == "" }
  # kube_listen_addr: 0.0.0.0:3026
  # mysql_listen_addr: 0.0.0.0:3036
  # %{ endif }
  enabled: true
  acme:
    enabled: yes
    email: <email>
  https_keypairs:
    - key_file: /etc/teleport-tls/tls.key
      cert_file: /etc/teleport-tls/tls.crt
ssh_service:
  enabled: false
app_service:
  enabled: true
  debug_app: true
  ```
**8.  Install teleport helm chart**
  
`helm install dev-teleport teleport/teleport-cluster -f teleport-values.yaml -n teleport`

here is the teleport-values.yaml file
```
clusterName: "example.teleport-onboarding.com" # this has to be changed
kubeClusterName: "teleport" # this has to be changed
authenticationType: local
teleportVersionOverride: "10.1.4"
authenticationSecondFactor:
  secondFactor: "otp"
proxyListenerMode: "multiplex"
enterprise: true # change this if you are not using enterprise
chartMode: custom
highAvailability:
  replicaCount: 3
  certManager:
    enabled: true
    issuerName: selfsigned-issuer
    issuerKind: Issuer 
annotations:
  service:
    "external-dns.alpha.kubernetes.io/hostname": "example.teleport-onboarding.com,*.example.teleport-onboarding.com" # this has to be changed
    "external-dns.alpha.kubernetes.io/ttl": "60"
    "service.beta.kubernetes.io/aws-load-balancer-attributes": "idle_timeout.timeout_seconds=650"
    "service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout": "650"
extraVolumes:
- name: etcd-client
  secret:
    secretName: etcd-client
- name: dev-teleport
  configMap:
    name: dev-teleport
extraVolumeMounts:
- name: etcd-client
  mountPath: /var/lib/etcd_client/
- name: dev-teleport
  mountPath: /etc/teleport/
resources:
  requests:
    cpu: "0.2"
    memory: "1Gi"
   ```
   
**9. Configure DNS** 
Helm chart deploys a load balancer service with the public IP address. Set up two A records with the public IP of the load balancer: example.teleport.com and *.example.teleport.com.
