### DISCUSSION TITLE
Azure AD SSO connector

### DISCUSSION THREAD

**Discussion by AerodyneT** [gravitational/teleport#18939] [Q&A] [answered]
I am working on setting up Azure AD SSO and keep getting the same error when trying to import the metadata xml file from the azure download.  
User Message: failed to parse entity_descriptor
        XML syntax error on line 1: attribute name without = in element

It's not very descriptive as to which attribute is missing.  Is there a xml template I can confirm that my xml file is setup correctly?

**Comment by bearrito** [comment]
The template in the docs is correct. I have followed it to get up and running with Azure AD SSO.

I'm assuming you exported the federation XML. You can check the XML using a tool like : https://xmllint.com/

Is your connector file valid yaml without the XML? You can check that with https://www.yamllint.com/

If both are valid, then it's probably the way you are passing the multi-line string to the YAML

**Comment by webvictim** [comment, marked as answer]
The formatting for the `entity_descriptor` can be pretty tough to get right. YAML is very fussy about spaces.

Here's a rough example of how you need to do it:

```
kind: saml
metadata:
  name: azure-ad
spec:
  entity_descriptor: |
    <?xml version="1.0" encoding="utf-8"?><EntityDescriptor ID="_426282f4-5f7e-49ae-97a2-84c5d88201b3" entityID="https://sts.windows.net/ff882432-09b0-437b-bd22-ca13c0037ded/" xmlns="urn:oasis:names:tc:SAML:2.0:metadata"><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" /><Reference URI="#_426282f4-5f7e-49ae-97a2-84c5d88201b3"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></Transforms>...
```

Important things:
- `spec` is a top-level field, so is indented by 0 spaces
- `entity_descriptor` is one level down, so is indented by 2 spaces
- `entity_descriptor: |` must have the pipe character on the end followed by a newline (FYI this is known as a YAML block scalar: see https://yaml-multiline.info/)
- the XML section itself is two levels down, so is indented by 4 spaces (then you paste the `<?xml...` value)
- if the XML value is spread across multiple lines, you must indent the start of every line of the XML section to match its first line i.e. with 4 spaces
