### DISCUSSION TITLE
sample teleport.yaml for Application on Teleport Cloud

### DISCUSSION THREAD

**Discussion by gord-lyr** [gravitational/teleport#19012] [Q&A] [answered]
I managed to get my server connection to work for initial connection using this command line:
teleport app start --name=webdev --token=/etc/token.file --uri=https://www-dev.mydmain.com:8000 --auth-server=mydomain.teleport.sh:443 --skip-version-check

Note: needed the --skip-version-check because teleport 11.1.1 is installed on my Ubuntu server, but mydomain.teleport.sh appears to be v10

On subsequent iterations, I just drop the --token value and this continues to work (even after reboot).

But now, I'm trying to run this is a service so created /etc/teleport.yaml (and have tried MANY variations), but can't get it to work. Based on https://goteleport.com/docs/reference/config/, I thought this would work, but not having any luck

```
version: v3
teleport:
  auth_server: mydomain.teleport.sh:443
  nodename: wwwdev
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: no
proxy_service:
  enabled: no
app_service:
  enabled: yes
  apps:
  - name: "wwwdev"
    uri: "https://www-dev.mydomain.com:8000"

```
I see other examples for dedicated teleport servers, but nothing for teleport cloud service.
