### DISCUSSION TITLE
Machine ID - Github Actions Login to Application (Jenkins)

### DISCUSSION THREAD

**Discussion by juniyadi-pintar** [gravitational/teleport#20069] [Q&A] [answered]
Hi, we are trying to trigger our Jenkins build behind the teleport application proxy.

I'm already following this tutorial: https://goteleport.com/docs/machine-id/guides/github-actions/

We already assign bots with "access" roles. this is works in with my local account, but not working in github bot :

### Command

```
tsh -i ${{ steps.auth.outputs.identity-file }} app login jenkins-master
```

### Errors

```
ERROR: access denied: identity is not allowed to reissue certificates
```

our GitHub actions YAML (domain has been changed)

```
on:
  push:
    branches:
      - dev
  
jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 11.2.0
      - name: Fetch credentials using Machine ID
        id: auth
        uses: teleport-actions/auth@v1
        with:
          proxy: tel.ourdomain.test:443
          token: github-token
          certificate-ttl: 1h
      - name: Print identity file
        run: cat ${{ steps.auth.outputs.identity-file }}
      - name: List all nodes
        run: tsh -i ${{ steps.auth.outputs.identity-file }} ls
      - name: List all applications
        run: tsh -i ${{ steps.auth.outputs.identity-file }} app ls
      - name: Login to Jenkins Master
        run: tsh -i ${{ steps.auth.outputs.identity-file }} app login jenkins-master
```

any body can help me about this?

Thanks,
Best Regards,
Yadi

**Comment by webvictim** [comment, marked as answer]
I believe this question was answered on our Teleport Community Slack: https://goteleport.slack.com/archives/CEZH6UL64/p1673426586504289?thread_ts=1673420457.938379&cid=CEZH6UL64

Copy/pasted here:

---

For this, you'd need to use a custom config for tbot rather than one of the off the shelf actions:

```yaml
auth_server: "teleport.example.com:443"
oneshot: true
onboarding:
  join_method: "github"
  token: "name-of-github-token"
storage:
  directory: /var/lib/teleport/bot
destinations:
  - directory: /opt/machine-id
    app: jenkins-master
```

In `/opt/machine-id` you'd then find the certificates to use when making requests to `jenkins-master`.

**Reply by juniyadi-pintar** [reply]
yes, it's working now using custom config

**Reply by cwegener** [reply]
This should really be in the official Teleport documentation on goteleport.com instead of being hidden in a Github discussion.

**Reply by juniyadi-pintar** [reply]
hi @cwegener , with the current version, you can use https://github.com/teleport-actions/auth-application
this is simple setup for GitHub Actions

**Reply by webvictim** [reply]
cc @strideynet

**Reply by cwegener** [reply]
I forgot to mention that I couldn't care less about Github actions. :joy:

I'm actually using `tsh proxy app` with a tbot generated identity and the missing part in the documentation is the `destinations` list ...

**Reply by strideynet** [reply]
Is this not shown in the Machine ID application access documentation (https://goteleport.com/docs/machine-id/guides/applications/#step-23-configure-and-start-machine-id) ? I can see the config in the docs shows the destinations list.

**Reply by hungran** [reply]
how if I go with teleport 14.x
```
      - name: Fetch credentials using Machine ID
        id: auth
        uses: teleport-actions/auth@v2
        with:
          # Use the address of the auth/proxy server for your own cluster.
          proxy: teleport.xxx:443
          # Use the name of the join token resource you created in step 1.
          token: xxx
          # Specify the length of time that the generated credentials should be
          # valid for. This is optional and defaults to "1h"
          certificate-ttl: 1h
          # Enable the submission of anonymous usage telemetry. This
          # helps us shape the future development of `tbot`. You can disable this
          # by omitting this.
          anonymous-telemetry: 1
      - name: List Apps
        run: tsh apps ls
      # - name: tbot login
      #   run: tbot login --proxy teleport.xxx:443 --token xxx --insecure
      - name: tbot login app
        run:  tbot -d -c ./tbot.yaml proxy --proxy teleport.xxx:443 app nexus
```
```tbot.yaml
version: v1
auth_server: teleport.xxx:443
onboarding:
  join_method: github
  token: teleport-kube-agent-join-token
oneshot: true
storage:
  directory: /var/lib/teleport/bot
destinations:
  - directory: /opt/machine-id
    app: nexus
```
it's saying `ERROR REPORT:
Original Error: *fs.PathError open /opt/machine-id/identity: no such file or directory`
