### DISCUSSION TITLE
ACCESS DENIED failed to fetch

### DISCUSSION THREAD

**Discussion by SolarisEclipse** [gravitational/teleport#20502] [Q&A] [answered]
Fresh install of teleport. I have never seen this before.

![Screenshot 2023-01-20 at 14 58 26](https://user-images.githubusercontent.com/30984488/213794408-2f7001f1-7e6a-4905-8472-7e6876cf2452.png)

Teleport Version: 11.2.2

```
version: v3
teleport:
   nodename: 
   data_dir: /var/lib/teleport
auth_service:
   enabled: yes
   cluster_name: REDACTED
   proxy_listener_mode: multiplex
   authentication:
     second_factor: off
   listen_addr: 192.168.50.175:3025
ssh_service:
   enabled: yes
   commands:
     - name: hostname
       command: [hostname]
       period: 1m0s
proxy_service:
   enabled: yes
   web_listen_addr: 192.168.50.175:443
   public_addr: REDACTED
   https_keypairs: []
   acme:
     enabled: "yes"
     email: REDACTED
app_service:
    enabled: "yes"
    apps:
     - name: cockpit
       uri: https://192.168.50.175:9090
       insecure_skip_verify: true
     - name: portainer
       uri: https://192.168.50.49:9443
       insecure_skip_verify: true
```
