### DISCUSSION TITLE
Docker: cluster ID required

### DISCUSSION THREAD

**Discussion by azzopardim** [gravitational/teleport#20536] [Q&A]
I am trying to configure teleport the first time but all attempts I am stuck with this initialization error.

Here is the teleport.yaml config file

```
#
# A Sample Teleport configuration file.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v3
teleport:
  nodename: roma.xyz
  cluster_name: roma.xyz
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  public_addr: roma.xyz:3025
  cluster_name: roma.xyz
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}


```
