### DISCUSSION TITLE
App running in the same host as Teleport

### DISCUSSION THREAD

**Discussion by freestylo73** [gravitational/teleport#20602] [Q&A] [answered]
Hi. During tests accessing an app inside a container through Teleport, running on a guest VM using qemu/kvm, got a CORS error. My question is simple (and hopefully not too dumb):  for the purpose of testing configurations and not ignoring/disabling any security settings, is it possible a setup like mine? Thank you for any input.

Pete

**Comment by webvictim** [comment, marked as answer]
Yes, your sort of setup will work fine.

CORS errors are usually caused by the fact that your app sees the traffic coming to it originating from a different host/origin to its own URL and blocks it. To work around these errors, you can try injecting `Host` and `Origin` headers which match the subdomain that Teleport uses. 

For example, if you're using Teleport Application Access to proxy access to Grafana on `http://localhost:3000` (but you now access it using `https://grafana.teleport.example.com` via Teleport), the config would look something like this:

```yaml
app_service:
  enabled: true
  apps:
  - name: grafana
    uri: http://localhost:3000
    public_addr: grafana.teleport.example.com
    rewrite:
      headers:
      - "Host: grafana.teleport.example.com"
      - "Origin: https://grafana.teleport.example.com"
```
