### DISCUSSION TITLE
'no authorities for hostname' error when container connects to the teleport server

### DISCUSSION THREAD

**Discussion by AzyCrw4282** [gravitational/teleport#21683] [Q&A] [answered]
I am trying to enable a teleport-client in my docker environment. The yaml configuration is set as required.
My yaml setup (sensitive values as <>)
```
teleport:
  data_dir: /var/lib/teleport
  auth_token: "<>"
  auth_servers:
      - "<>"
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    env: lab
    service: dca
  commands:
    - command:
      - /bin/uname
      - -p
      name: arch
      period: 1h0m0s
  ```
  Every time the container starts, i get this error

  > 2023-02-10T19:54:47Z ERRO [PROC:1]    - connecting to auth server through tunnel: connection error: desc = "transport: Error while dialing failed to dial: ssh: handshake failed: ssh: no authorities for hostname: <>" pid:6.1 service/connect.go:1111
2023-02-10T19:54:47Z ERRO [PROC:1]    "Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tconnection error: desc = \"transport: authentication handshake failed: EOF\", connection error: desc = \"transport: Error while dialing failed to dial: **ssh: handshake failed: ssh: no authorities for hostname: <hostname here>\"**." pid:6.1 service/connect.go:119
2023-02-10T19:54:48Z INFO [PROC:1]    Connecting to the cluster <> with TLS client certificate. pid:6.1 service/connect.go:258
2023-02-10T19:54:49Z ERRO [PROC:1]    Node failed to establish connection to Teleport Proxy. We have tried the following endpoints: pid:6.1 service/connect.go:1106

looks like it cant verify the authority of my hostname that i am passing. Am i missing some `.crt` here? I havent had this issue on other setup.
