### DISCUSSION TITLE
Teleport Login User Name

### DISCUSSION THREAD

**Discussion by gmrajmohan** [gravitational/teleport#22062] [Q&A]
How to get login name of teleport, which can be used in YAML Scripts

**Comment by stevenGravy** [comment]
Please provide more information on your question.  Not clear to me the context of a login name with YAML scripts.

**Comment by gmrajmohan** [comment]
Want to login SSH server based on the teleport username. ie. Teleport username = SSH user name. 

shouldn't list / show all other existing SSH server's users.

How do I implement it in new role.

**Reply by stevenGravy** [reply]
For a local user (not GitHub or other SSO) you can set the `logins` trait.  Do `tctl edit users/myusername`.  You can add the desired login including their username as below.

```yaml
#...
  traits:
    logins:
    - myusername
#... 
```

When you create the user via the command line you can include that with `--logins=myusername`

`tctl users add --roles=access myusername --logins=myusername`

**Comment by gmrajmohan** [comment]
Thanks for the quick reply.

We had more than 100 users in Linux server. Shall I create 100 roles in teleport to access that Linux server? 

If the users listed in logins:, then users can connect other users home directory.

How to avoid this?

**Reply by stevenGravy** [reply]
By default your `access` role includes in the `internal.logins` variable. So any role that you assign in Teleport that has the `internal.logins` variable will include that local user trait.  So you shouldn't need 100 roles for 100 users.  Just the roles that apply for those users for which servers you want to give them access.


```yaml
  allow:
    # The logins array defines the OS/UNIX logins a user is allowed to use.
    # both strings and template variables are supported in this field
    logins: ['{{internal.logins}}']
```

See https://goteleport.com/docs/access-controls/guides/role-templates/#local-users

**Comment by gmrajmohan** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4477240/221883584-e02ab605-89f2-4150-b57d-8d3b7e68e515.png">
I have testuser in my Linux server and teleport 

server1 is my role

```yaml
kind: role
metadata:
  id: 1677594418255655436
  name: servers1
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
```
