### DISCUSSION TITLE
Why teleport binds 443 port to auth_server?

### DISCUSSION THREAD

**Discussion by computerphilosopher** [gravitational/teleport#22175] [Q&A] [answered]
log says

```sh
Feb 20 06:40:18 ip-10-21-1-229 teleport[14877]: 2023-02-20T06:40:18Z WARN             config: auth_server is pointing to port 443, is this the proxy server address? service/validateconfig.go:120
```

but my teleport.yaml file binds 3025 port to auth server

```yaml
version: v3
teleport:
  nodename: aurora-teleport-test
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: tele.example.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: tele.example.com:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: erlk0nig@naver.com
```

Why my teleport.yaml file does not work?
