### DISCUSSION TITLE
Server connect disconnect after exactly 1 minute

### DISCUSSION THREAD

**Discussion by sanggkaitoo** [gravitational/teleport#22303] [Q&A] [answered]
I have a weird issue that session connects to server of teleport disconnect after 1 minute if I do nothing although I had config in teleport.yaml that:
`client_idle_timeout: never`.
I also set up sshd_config like this:
```
ClientAliveInterval  1200
ClientAliveCountMax 3
```
If I set up client_idle_timeout_message: "" It doesn't show message when disconnected:
`sang.phung@ip-10-0-203-108:~$ disconnected`
I don't know why, so could anyone help me with this issue?

**Comment by webvictim** [comment]
The fact that it's exactly 1 minute suggests it's a 60 second timeout being enforced somewhere. How is your Teleport cluster configured? Do you have a load balancer or stateful firewall in front of Teleport, or on the connection that you're using to connect to Teleport?

**Reply by sanggkaitoo** [reply]
This is my Teleport configured, pls help me solve this issue:

```
version: v3
teleport:
  nodename: ***
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  session_recording: "node"
  listen_addr: 0.0.0.0:3025
  client_idle_timeout: never
  session_control_timeout: 15m
  cluster_name: ***
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
  pam:
    enabled: true
    service_name: "teleport"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: ***
  https_keypairs_reload_interval: 0s
  acme: {}
```
