### DISCUSSION TITLE
Confused over understanding teleport roles w.r.t access to kubernetes

### DISCUSSION THREAD

**Discussion by cotigao** [gravitational/teleport#22650] [Q&A]
I am following [this documentation](https://goteleport.com/docs/kubernetes-access/getting-started/) for creating a teleport role and having a hard time understanding how the teleport kubernetes service authenticates with the cluster and authorizes the teleport users.

In the following kube-access example. 

```yaml
kind: role
metadata:
  name: kube-access
version: v6
spec:
  allow:
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: pod
        namespace: "*"
        name: "*"
    kubernetes_groups:
    - viewers
    kubernetes_users:
    - USER
  deny: {}
```
Is `kubernetes_resources` section supposed to be a subset of the privileges of `viewers` and `USER` ? 
As I understand it `kube-access` role  uses `kubernetes_groups` and `USER` to authenticate with the kubernetes cluster and `kubernetes_resources` defines permissions for the teleport users
