### DISCUSSION TITLE
Kube failed to establish connection to cluster

### DISCUSSION THREAD

**Discussion by AlexFromMoscow6** [gravitational/teleport#22747] [Q&A] [answered]
I have problem with adding Kubernetes cluster to teleport. I used this manual
https://goteleport.com/docs/kubernetes-access/getting-started/
After I deployed agent (third step) pod is not running with this error:

`Readiness probe failed: HTTP probe failed with statuscode: 400`

Full log:

```
Kube failed to establish connection to cluster: Post "https://it-storage-test.ru:443/v1/webapi/host/credentials": dial tcp: lookup it-storage-test.ru on 10.96.0.10:53: read udp 10.244.1.4:37141->10.96.0.10:53: i/o timeout. pid:6.1 service/connect.go:119

Instance failed to establish connection to cluster: Post "https://it-storage-test.ru:443/v1/webapi/host/credentials": dial tcp: lookup it-storage-test.ru on 10.96.0.10:53: read udp 10.244.1.4:54074->10.96.0.10:53: i/o timeout. pid:6.1 service/connect.go:119
```

Here is my teleport.yaml config:

```
version: v3
teleport:
  nodename: k8s-master
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: it-storage-test.ru
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: it-storage-test.ru:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: test_world@gmail.com
```

I'm using self hosted kubernetes cluster 1.26.2 on Ubuntu 20.04.3.
Teleport v12.1.0 git:api/v12.1.0-0-g49a6de7 go1.19.6
Proxy version: 12.1.0
