### DISCUSSION TITLE
How to specify an NLB that already exists when deploying to EKS with helm?

### DISCUSSION THREAD

**Discussion by 4dollar4** [gravitational/teleport#23167] [Q&A]
I am testing a deployment of the open source Teleport to EKS with helm.

As a result, the deployment with helm went smoothly, but what I want to do is not to provision a new NLB for Teleport, but to use the NLB for istio that already exists.  

I'll make my helm chart public, where in the helm chart should I put the NLB I'm already using and with what key values?

```
chartMode: aws
clusterName: k8s-teleport.test.co                 # Name of your cluster. Use the FQDN you intend to configure in DNS below.
aws:
  region: ap-northeast-2                               # AWS region
  backendTable: teleport-helm-backend             # DynamoDB table to use for the Teleport backend
  auditLogTable: teleport-helm-events             # DynamoDB table to use for the Teleport audit log (must be different to the backend table)
  auditLogMirrorOnStdout: true                   # Whether to mirror audit log entries to stdout in JSON format (useful for external log collectors)
  sessionRecordingBucket: teleport-audit-test  # S3 bucket to use for Teleport session recordings
  backups: true                                   # Whether or not to turn on DynamoDB backups
  dynamoAutoScaling: false                        # Whether Teleport should configure DynamoDB's autoscaling.
highAvailability:
  replicaCount: 2                                 # Number of replicas to configure(only Auth service. Not provide Proxy service)
annotations:
  service:
    # Replace with your AWS certificate ARN
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:123456789:certificate/1234e23a-c321-4723-123e-48f12c0a3801"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  serviceAccount:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/teleport-sa-role

# If you are running Kubernetes 1.23 or above, disable PodSecurityPolicies
podSecurityPolicy:
  enabled: false
separatePostgresListener: true
mysqlPublicAddr: ["k8s-teleport.test.co:3036"]
postgresPublicAddr: ["k8s-teleport.test.co:4532"]
```
