### DISCUSSION TITLE
Access Requests questions

### DISCUSSION THREAD

**Discussion by mcantinqc** [gravitational/teleport#23212] [Q&A] [answered]
Hi,

We have two use case and I want to know if that it's possible with Teleport enterprise. These are related to the Access Requests.

First, is it possible to request a reason for accessing a resource or a role, but give the access automatically. So the reason will be recorded, but the access will be give automatically.

Second, is it possible to configure a workflow that ask another member to approve? For example, in a small team of 4-6, someone ask for access to role ABC, a team member must approve the request, but they cannot approve themselves.

Thanks

**Comment by zmb3** [comment, marked as answer]
> First, is it possible to request a reason for accessing a resource or a role, but give the access automatically. So the reason will be recorded, but the access will be give automatically.

You can do this with a plugin. For example, our [PagerDuty plugin](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-pagerduty/?scope=enterprise) can be configured to automatically approve access requests for members of the on call team.

> Second, is it possible to configure a workflow that ask another member to approve? For example, in a small team of 4-6, someone ask for access to role ABC, a team member must approve the request, but they cannot approve themselves.

Yes. We don't currently support approving your own access request, so you could do something like this.

```
kind: role
version: v5
metadata:
  name: team-member
spec:
  allow:
    # all 4-6 members of the team can request access to role 'abc'
    request:
      roles: ['abc']

    # all 4-6 members of the team can review other team members' 
    # requests for role 'abc'
    review_requests:
      roles: ['abc']
```
