### DISCUSSION TITLE
Web application access is failing

### DISCUSSION THREAD

**Discussion by RobertBrown3** [gravitational/teleport#23481] [Q&A]
I am running teleport in a docker container. I am also trying to add a web application to my list of apps that Teleport can launch.

My teleport.yml file is below:

    version: v3
    teleport:
      nodename: teleport.factor3.net
      data_dir: /var/lib/teleport
      log:
        output: stderr
        severity: INFO
        format:
          output: text
      ca_pin: ""
      diag_addr: ""
    auth_service:
      enabled: "yes"
      listen_addr: 0.0.0.0:3025
      proxy_listener_mode: multiplex
      cluster_name: teleport.factor3.net
      authentication:
        type: local
        second_factor: on
    ssh_service:
      enabled: "yes"
      commands:
      - name: hostname
        command: [hostname]
        period: 1m0s
    proxy_service:
      enabled: "yes"
      web_listen_addr: 0.0.0.0:443
      public_addr: teleport.factor3.net
      https_keypairs: []
      acme: 
         enabled: no
         email: <REDACTED>
    
When starting my server, I attempt to add a locally- running Jenkins server to my applications using the following procedure, as suggested on the Applications page:

1. I download and install the Teleport package. I use the tarball since I am installing it on Almalinux.
2. I run the following:

  ` teleport configure --output=$HOME/.config/app_config.yaml --app-name=jenkins --app-uri=http://localhost:8080/ --roles=app --token=<REDACTED> --auth-server=eleport.factor3.net:443 --data-dir=$HOME/.config`

 The resulting app_config file is below:
    
```
     version: v2
    teleport:
      nodename: DKServer.main1.net
      data_dir: /home/rbrown3/.config
      join_params:
        token_name: <REDACTED>
        method: token
      auth_servers:
      - teleport.factor3.net:443
      log:
        output: stderr
        severity: INFO
        format:
          output: text
      ca_pin: ""
      diag_addr: ""
    auth_service:
      enabled: "no"
    ssh_service:
      enabled: "no"
    proxy_service:
      enabled: "no"
      https_keypairs: []
      acme: {}
    app_service:
      enabled: "yes"
      debug_app: false
      apps:
      - name: portainer
        uri: https://localhost:8080/
        public_addr: ""
        insecure_skip_verify: false

```        
3. I start the teleport application:

    ` teleport start --config=$HOME/.config/app_config.yaml`
     
 The application starts, but every few seconds I get the following log entries:
 
     2023-03-22T01:19:45-04:00 INFO [PROC:1]    Joining the cluster with a secure token. pid:320502.1 service/connect.go:583
     2023-03-22T01:19:46-04:00 INFO [AUTH]      Attempting registration via proxy server. auth/register.go:185
     2023-03-22T01:19:46-04:00 INFO [AUTH]      Successfully registered via proxy server. auth/register.go:192
     2023-03-22T01:19:46-04:00 INFO [PROC:1]    Instance has obtained credentials to connect to the cluster. pid:320502.1 service/connect.go:618
     2023-03-22T01:19:46-04:00 ERRO [PROC:1]    "Instance failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tconnection error: desc = \"transport: authentication handshake failed: remote error: tls: unrecognized name\", connection error: desc = \"transport: Error while dialing failed to dial: remote error: tls: no application protocol\"." pid:320502.1 service/connect.go:113

Apparently, the agent is failing to connect to the "cluster". Needless to say, Jenkins is not added to my list of applications.

Can someone give some idea why this is happening and (more importantly) how to make the teleport agent actually connect?
