### DISCUSSION TITLE
Application Access Denied Failed to fetch

### DISCUSSION THREAD

**Discussion by yousif-faiq** [gravitational/teleport#23754] [Q&A]
I have installed teleport on my server,
I am facing this error: 

![Screenshot from 2023-03-26 12-39-59](https://user-images.githubusercontent.com/66562637/228479411-e40b2b39-ca3b-42bd-b8b1-10046b1ccc28.png)

I want to access the dumper app or even any app I have tried, it shows the same error "Access Denied Failed to fetch"

My Teleport version: Teleport v12.1.1

The config file:
```
version: v3
teleport:
  nodename: master
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: master
  proxy_listener_mode: multiplex

app_service:
  enabled: "yes"
  debug_app: true

ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: master.ex:443
  https_keypairs:
  - key_file: path/to/master/key/file
    cert_file: path/to/master/cert/file
  https_keypairs_reload_interval: 0s
  acme: {}
```
