### DISCUSSION TITLE
Unable to configure simple app on an ssh node

### DISCUSSION THREAD

**Discussion by elacour** [gravitational/teleport#24122] [Q&A] [answered]
Dear teleport users, I have a teleport cluster, running fine for tsh/ssh access. On one host I have also an http app (apache). I created a token for node,app, used it to register, but it fails with:

`BadParameterError failed to find reverse tunnel address, if running in single process mode, make sure &#34;auth_service&#34;, &#34;proxy_service&#34;, and &#34;app_service&#34; are all enabled`

any idea to solve this?

Here is the cluster node configuration:

```
teleport:
  nodename: bastion
  data_dir: /var/lib/teleport
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: "127.0.0.1:3000"

auth_service:
  enabled: "yes"
  cluster_name: teleport.foo
  session_recording: node-sync
  client_idle_timeout: "1h"
  client_idle_timeout_message: "Disconnected due to client inactivity"
  disconnect_expired_cert: no

ssh_service:
  enabled: "yes"
  labels:
    env: teleport_server
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s

proxy_service:
  enabled: "yes"
  listen_addr: 10.23.1.251:3023
  web_listen_addr: 10.23.1.251:3080
  public_addr: teleport.foo:3080

kubernetes_service:
  enabled: no

app_service:
  enabled: no
```

Here is the node/app configuration:

```
teleport:
  data_dir: /var/lib/teleport
  join_params:
    token_name: xxxx
    method: token
  ca_pin: xxxx
  auth_servers:
   - "10.23.1.251:3025"
#  log:
#    output: /var/lib/teleport/teleport.log
#    severity: INFO
#    format:
#      output: text

ssh_service:
  enabled: yes
  commands:
  - name: hostname
    command: [hostname]
    period: 60m0s
  listen_addr: 10.23.1.248:3022

auth_service:
  enabled: no

proxy_service:
  enabled: no

app_service:
  enabled: yes
  debug_app: false
  apps:
    - name: "backup-a"
      uri: "http://10.23.1.248:80/"
      public_addr: "backup-a.teleport.foo"
      insecure_skip_verify: true

kubernetes_service:
  enabled: no

db_service:
  enabled: no


```
