### DISCUSSION TITLE
'failed to find reverse tunnel address' error

### DISCUSSION THREAD

**Discussion by plutino** [gravitational/teleport#24221] [Q&A] [answered]
Hi, we run into this error recently when attempting to use private connections between a database node and the cluster.  Hope that anyone can shine some light on it.

We use `teleport` for database access only, and here is a summary of our deployment:

Cluster: auth and proxy are deployed to a GKE cluster in VPC A.  We have multiple pods for both services running behind 2 load balancers:  one with public IP address for client access, one with private IP address for connections between the proxy and the database nodes.

DB node: db service is deployed to a GKE cluster in VPC B, where the Cloud SQL database resides.  VPC A and B are connected with peering connections.  

Originally we have the DB node connected to the public LB and everything works fine, except that the latency is large compared to direct connection to the DB.  So we start to try to use GCP private connections with the hope that it would reduce the latency.  

This is when we run into the problem.  The internal load balancer on the cluster has these ports exposed: 3025 (auth), 3023/3024 (ssh), and 3080 (proxy).  The db node is able to successfully register with the cluster, but the pod then dies with this error:

```
Critical service db.init has exited with error failed to find reverse tunnel address, if running in single process mode, make sure "auth_service", "proxy_service", and "app_service" are all enabled, aborting.
```

I'm not familiar with the internals of `teleport`.  What else is required to establish the revers tunnel besides the SSH ports on the cluster end?

Many thanks.

**Comment by webvictim** [comment]
You may need to simply override the tunnel public address in your `teleport-cluster` values and do a `helm upgrade`: 

```yaml
tunnelPublicAddr: ['private-lb-address:3024']
```
(as per https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L195-L197)

If this doesn't work, can you share the Teleport config files from each of your Teleport pods? This is basically running `cat /etc/teleport/teleport.yaml` inside each pod, or something like `for TYPE in auth proxy; do kubectl -n ${NAMESPACE?} get configmap ${RELEASE?}-${TYPE} -o jsonpath="{.data['teleport\.yaml']}"; done`

The output of `curl -s https://teleport.example.com:443/webapi/ping` (where `teleport.example.com:443` is the public address of your proxy) would also be helpful.

**Reply by plutino** [reply]
Thanks @webvictim .  Setting `tunnel_public_addr` doesn't seem to help.  We are on teleport 10.3.13 and here are teleport configurations:

Cluster:
```yaml
    teleport:
      log:
        severity: INFO
        output: stderr
        format:
          output: json
          extra_fields: ["timestamp","level","component","caller"]
      storage:
        type: firestore
        project_id: my_project
        collection_name: teleport-backend
        audit_events_uri: ['firestore://teleport-events?projectID=my_project']
        audit_sessions_uri: "gs://mp-teleport-sessions?projectID=my_project"
    auth_service:
      enabled: true
      tokens:
      - "node,db:/etc/teleport-secrets/auth-token"
      cluster_name: teleport.myproject.cloud
      authentication:
        type: github
        second_factor: otp
    proxy_service:
      enabled: true
      public_addr: 'teleport.myproject.cloud:443'
      tunnel_public_addr: 10.10.15.216:3024
      postgres_listen_addr: 0.0.0.0:5432
      postgres_public_addr: teleport.myproject.cloud:5432
      https_keypairs:
      - key_file: /etc/teleport-tls/tls.key
        cert_file: /etc/teleport-tls/tls.crt
    ssh_service:
      enabled: false
    kubernetes_service:
      enabled: false
```

DB node:
```yaml
    teleport:
      auth_token: "/etc/teleport-secrets/auth-token"
      auth_servers: ["10.10.15.216:3025"]
      ca_pin:
        - sha256:******
      log:
        severity: INFO
        output: stderr
        format:
          output: json
          extra_fields: ["timestamp","level","component","caller"]
    kubernetes_service:
      enabled: false
    app_service:
      enabled: false
    db_service:
      enabled: true
      databases:
      - description: QA PostgreSQL database
        gcp:
          instance_id: qa-postgres-6f8bf4a0
          project_id: my_project
        name: qa-postgres
        protocol: postgres
        static_labels:
          env: qa
        uri: 10.241.1.3:5432
        ca_cert_file: /etc/teleport/qa-postgres-root-ca.pem
    auth_service:
      enabled: false
    ssh_service:
      enabled: false
    proxy_service:
      enabled: false
```

And here is the output of `curl -s https://teleport.example.com:443/webapi/ping` :
```json
{
  "auth": {
    "type": "github",
    "second_factor": "otp",
    "preferred_local_mfa": "otp",
    "github": {
      "name": "github",
      "display": "GitHub"
    },
    "has_motd": false
  },
  "proxy": {
    "kube": {},
    "ssh": {
      "listen_addr": "[::]:3023",
      "tunnel_listen_addr": "0.0.0.0:3024",
      "web_listen_addr": "0.0.0.0:3080",
      "public_addr": "teleport.myproject.cloud:443",
      "ssh_tunnel_public_addr": "10.10.15.216:3024"
    },
    "db": {
      "postgres_listen_addr": "0.0.0.0:5432",
      "postgres_public_addr": "teleport.myproject.cloud:5432"
    },
    "tls_routing_enabled": false
  },
  "server_version": "10.3.13",
  "min_client_version": "9.0.0",
  "cluster_name": "teleport.myproject.cloud"
}
```
