### DISCUSSION TITLE
Does Kubernetes access control in Teleport only support 'Pods'?

### DISCUSSION THREAD

**Discussion by computerphilosopher** [gravitational/teleport#24428] [Q&A] [answered]
I'm trying to create a role using the following YAML file:

```yaml
kind: role
metadata:
  name: pod-reader
version: v6
spec:
  allow:
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: pod
        namespace: "*"
        name: "*"
      - kind: namespace
        name: "*"
    kubernetes_groups:
      - my-group
    kubernetes_users:
      - my-name
```

However, I receive an error message from tctl: "ERROR: KubernetesResource kind 'namespace' is invalid or unsupported; Supported: [pod]".

Initially, I thought the issue was with the teleport-agent's clusterrole permissions. But upon examining the source code, I discovered this comment:

```go
// api/types/types.pb.go:6472
// KubernetesResource is the Kubernetes resource identifier.
type KubernetesResource struct {
	// Kind specifies the Kubernetes Resource type.
	// At the moment only "pod" is supported.
```

According to the comment, only access control for pods is supported in Kubernetes. Therefore, it seems that it's not possible to control actions like listing namespaces, creating ingresses, and so on. Am I understanding this correctly?

**Comment by webvictim** [comment, marked as answer]
Edit: It is now possible to control access to all Kubernetes built-in resource types through Teleport RBAC - see https://goteleport.com/docs/enroll-resources/kubernetes-access/controls/#kubernetes_resources

Also, in Teleport version 18 with role v8, it is also now possible to manage access to CRDs with Teleport: https://goteleport.com/docs/ver/18.x/changelog/#kubernetes-crd

~That's correct, it's only currently possible to control access to pods directly via a Teleport role.~

~You can limit access to other Kubernetes resources in the traditional method - by setting a Kubenetes user or group in Teleport RBAC, then adding a `RoleBinding` or `ClusterRoleBinding` directly to Kubernetes which references that user/group.~

~These docs may help: https://goteleport.com/docs/kubernetes-access/manage-access/rbac/#install-kubernetes-rbac-resources~

~There is also a discussion post here with some more details: https://github.com/gravitational/teleport/discussions/8581~

**Reply by mtp1376** [reply]
Is this behavior currently changed? I mean can we now use teleport to filter access to ingresses?

**Reply by webvictim** [reply]
Yes, you can manage access to other Kubernetes resource types now as per docs (https://goteleport.com/docs/enroll-resources/kubernetes-access/controls/#kubernetes_resources):

```yaml
kind: role
metadata:
  name: allow-ingresses-in-one-namespace
spec:
  allow:
    kubernetes_resources:
    - api_group: '*'
      kind: ingresses
      name: '*'
      namespace: ingress-namespace
      verbs:
      - '*'
version: v7
```
