### DISCUSSION TITLE
local authentication and ldap authentication for teleport access

### DISCUSSION THREAD

**Discussion by Bloody3556** [gravitational/teleport#24531] [Q&A]
Hello everyone, I apologize in advance but I have a problem with the configuration of my teleport.yaml file, I am working on a poc to integrate teleport into our services via ldap authentication with an active directory, local authentication is ok, but as soon as I want to add the ldap additionally but I can't find any documentation or example with these 2 authentications.

```yaml
app_service:
    enabled: yes
      #apps:
      #- name: "demo"
      #uri: "http://localhost:9000"
      #public_addr: "demo.teleport.example.com"

#LOCAL auth without OTP
auth_service:
   authentication:
        type: local
        second_factor: off
```
thanks for the help
