### DISCUSSION TITLE
Teleport Create Host Users

### DISCUSSION THREAD

**Discussion by alifiroozi80** [gravitational/teleport#25088] [Q&A]
Hello team,
First, Thank you so much for this amazing tool and your generous Open-Source License.
I have a problem and I want your help:

---

I want to [Configure Teleport to Create Host Users](https://goteleport.com/docs/server-access/guides/host-user-creation). 

I went through the docs step by step. Here is the role:

```yaml
kind: role
version: v5
metadata:
  name: auto-users
spec:
  options:
    create_host_user: true
  allow:
    logins: [ "guest" ]
    # List of host groups the created user will be added to. Any that don't already exist are created.
    host_groups: [docker, guest]
    # List of entries to include in a temporary sudoers file created in /etc/sudoers.d
    host_sudoers: [
       # This line will allow the `nginxrestarter` user to run
       # `systemctl restart nginx. service` as
       # root without requiring a password.
       # The sudoers entries will be prefixed with `nginxrestarter` in this case.
       # sudoers file reference documentation: https://www.sudo.ws/docs/man/1.8.17/sudoers.man/
       "ALL = (root) NOPASSWD: /usr/bin/systemctl status ssh.service"
    ]
```

---

If I execute `tsh status`, it shows me that it is enabled:

```shell
> Profile URL:        https://mydomain.com:443
  Logged in as:       teleport-admin
  Cluster:            digify
  Roles:              access, auditor, auto-users, editor, kube-digify-admin
  Logins:             ubuntu, root, guest, -teleport-internal-join
  Kubernetes:         enabled
  Kubernetes groups:  digify-admin
  Valid until:        2023-04-25 07:05:38 +0330 +0330 [valid for 11h51m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy
```

---

But, if I try to ssh with this `guest` user, It shows the error:

```shell
$ tsh ssh guest@agent1

ERROR: access denied to guest connecting to agent1:0@default@digify
```

---

I even add labels to the role like this:

```yaml
kind: role
version: v5
metadata:
  name: auto-users
spec:
  options:
    create_host_user: true
  allow:
    logins: [ "guest" ]
    # List of host groups the created user will be added to. Any that don't already exist are created.
    host_groups: [docker, guest]
    # List of entries to include in a temporary sudoers file created in /etc/sudoers.d
    host_sudoers: [
       # This line will allow the `nginxrestarter` user to run
       # `systemctl restart nginx.service` as
       # root without requiring a password.
       # The sudoers entries will be prefixed with `nginxrestarter` in this case.
       # sudoers file reference documentation: https://www.sudo.ws/docs/man/1.8.17/sudoers.man/
       "ALL = (root) NOPASSWD: /usr/bin/systemctl status ssh.service"
    ]
  node_labels:
      '*': '*'
```

and logout and login again with `tsh`.

but after I tried to ssh with user `guest`, it shows the same error.

---

Teleport version: 

```shell
Teleport v12.1.1 git:api/v12.1.1-0-gb9ee4832ec go1.19.7
Proxy version: 12.2.3
```

**Comment by ashokrajar** [comment]
Was facing the same. Restarting the teleport agent on the nodes fixed the issue.

**Comment by webvictim** [comment]
In newer versions of Teleport you can also configure:

Delete created host users after logout:
```yaml
spec:
  options:
    create_host_user_mode: drop
```

Keep created host users after logout:
```yaml
spec:
  options:
    create_host_user_mode: keep
```

Don't create host users (the default):
```yaml
spec:
  options:
    create_host_user_mode: off
```

The other thing to make sure is that _all_ Teleport roles you have assigned have `create_host_user_mode` set to the desired value.

If any of your roles has `create_host_user_mode` set to `off` (the default) then host users won't be created.
