### DISCUSSION TITLE
Help with teleport configuration on kubernetes running on azure (giant swarm cluster)

### DISCUSSION THREAD

**Discussion by Berveglieri** [gravitational/teleport#25313] [Q&A] [answered]
Hello everyone,

I would like to ask for some help in how to setup teleport properly on kubernetes (running on azure).
I am facing issues to be able to make the proxy server to connect to the auth server.

If I set the auth_server connection in the proxy section using the service name I get tls handshake issues if I set the auth_server with the public address it seems there is no connection at all.

Could someone please point me what I am doing wrong?

values.yaml

```
chartMode: scratch

auth:
  teleportConfig:
    version: v3
    teleport:
      log:
        output: stderr
        severity: INFO
    auth_service:
      enabled: true
      cluster_name: "teleport-test.fake.cloud"
      listen_addr: 0.0.0.0:3025
      public_addr: "teleport-test.fake.cloud:3025"
      proxy_listener_mode: multiplex
      authentication:
        type: local
        second_factor: otp
        webauthn:
          rp_id: "teleport-test.fake.cloud"

proxy:
  teleportConfig:
    version: v3
    teleport:
      join_params:
        method: kubernetes
        token_name: "teleport-proxy"
      auth_server: "teleport-test.fake.cloud:3025"
      advertise_ip: "teleport-test.fake.cloud"
      log:
        output: stderr
        severity: INFO
    proxy_service:
      enabled: true
      https_keypairs:
        - key_file: /etc/proxy-certs/df-key.pem
          cert_file: /etc/proxy-certs/df-chain-cert.pem
      web_listen_addr: 0.0.0.0:3080
      listen_addr: 0.0.0.0:3023
      public_addr: "teleport-test.fake.cloud:443"
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: teleport


podSecurityPolicy:
  enabled: false

tls:
  existingSecretName: "teleport-tls-certs"

extraVolumes:
 - name: proxy-certs
   secret:
     secretName: proxy-certs

extraVolumeMounts:
 - name: proxy-certs
   mountPath: /etc/proxy-certs/
   ```
   
   Thank you in advance

**Comment by webvictim** [comment]
Firstly, you probably don't need to use `chartMode: scratch` - that'll make things harder as it'll disable a lot of the "nice" config automation that the Helm chart does. Using `chartMode: scratch` here means that:
- your auth pod actually has `auth_service`, `proxy_service` and `ssh_service` all enabled (because Teleport enables them automatically, and you haven't disabled them in your passed config)
- your proxy pod actually has `auth_service`, `proxy_service` and `ssh_service` all enabled too

This will cause a lot of confusion and weird things to happen. I would look to use `chartMode: standalone` instead, which will write most of your config for you.

See these config templates for examples of what it will do automatically:
- auth: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/auth/_config.common.tpl
- proxy: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/proxy/_config.common.tpl

Also, it looks like you're using `tls.existingSecretName` (https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L417-L421) already to mount your proxy's TLS certificates - so theoretically you should be able to remove the `extraVolumes` and `extraVolumeMounts` sections, plus your `https_keypairs` config overrides.

Once this is done, your proxy pods should automatically join to the auth pod via Kubernetes join token and the exposed auth service. If not, post back here with the exact errors you're getting and we'll figure it out.

**Comment by Berveglieri** [comment]
@webvictim Thank your the help on that.
I have changed it to standalone on Friday and it worked fine, was able to access the web UI and even created a user.
But this morning, everything was broken and I have the following errors

2023/05/02 10:30:15 http: TLS handshake error from 10.1.219.28:57960: EOF
2023/05/02 10:30:15 http: TLS handshake error from 10.1.219.28:57980: remote error: tls: bad certificate
2023-05-02T10:30:31Z WARN [KUBERNETE] Denying proxy access to unauthenticated user of type authz.BuiltinRole - this can sometimes be caused by inadvertently using an HTTP load balancer instead of a TCP load balancer on the Kubernetes port. pid:7.2 proxy/forwarder.go:466

nothing have changed, any idea what is wrong?


```
chartMode: standalone

clusterName: "teleport-test.fake.cloud"
kubeClusterName: "teleport-test.fake.cloud"
proxyListenerMode: "multiplex"
authentication:
  type: local
  secondFactor: "on"
publicAddr:
  - "teleport-test.fake.cloud:443"
auth:
  teleportConfig:
    auth_service:
      authentication:
        webauthn:
          rp_id: "teleport-test.fake.cloud"

proxy:
  teleportConfig:
    teleport:
      auth_server: "teleport-test.fake.cloud.svc.cluster.local:3026"
      log:
        output: stderr
        severity: DEBUG


podSecurityPolicy:
  enabled: false



tls:
  existingSecretName: "fake-teleport"
```
