### DISCUSSION TITLE
Problem using certificate from own CA

### DISCUSSION THREAD

**Discussion by furrnace** [gravitational/teleport#25581] [Q&A] [answered]
In my home lab I am using my own root CA. This works so far fine with all sorts of services.

I am having a hard time to get teleport to accept the certificate I created for itself.
If I understand it correctly, `https_keypairs` is used to declare which certificate/key pair to use for the communication with the proxy service (mainly its web ui), correct? `https_keypairs` is not used by teleport to generate the short lived certificates that are used to authenticate users and services, correct?

I am using the following simple configuration:

```
version: v3
teleport:
  nodename: teleport.mgt.net
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: teleport.mgt.net:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.mgt.net:3080
  ssh_public_addr: teleport.mgt.net:3023
  https_keypairs:
  - key_file: /etc/teleport/key.pem
    cert_file: /etc/teleport/fullchain.pem
  https_keypairs_reload_interval: 1h
  acme: {}
```

the `key.pem` file contains the private key used with the host certificate I created for the teleport machine.
the `fullchain.pem` file is created by concatenating the host certificate, the intermediate certificate of the server CA, and the root CA certificate (all PEM format). I have tried all orders of these files, but I always get:

```
ERROR: "unable to verify HTTPS certificate chain in : \x1b[31mERROR: \x1b[0mWARNING:"

  The proxy you are connecting to has presented a certificate signed by a
  unknown authority. This is most likely due to either being presented
  with a self-signed certificate or the certificate was truly signed by an
  authority not known to the client.

  If you know the certificate is self-signed and would like to ignore this
  error use the --insecure flag.

  If you have your own certificate authority that you would like to use to
  validate the certificate chain presented by the proxy, set the
  SSL_CERT_FILE and SSL_CERT_DIR environment variables respectively and try
  again.

  If you think something malicious may be occurring, contact your Teleport
  system administrator to resolve this issue.

```
