### DISCUSSION TITLE
running auth, proxy AND app services in the same instance?

### DISCUSSION THREAD

**Discussion by furrnace** [gravitational/teleport#25608] [Q&A]
In my simplistic setup I do not need to (and oftentimes also cannot) run the app service on the application machine.
Running the app service on a different machine near to the application doesn't really make sense, the easiest would be to run the app service in the same instance as the proxy service and the auth service. the teleport.mgt.net machine here is basically a jump or bastion host to be able to access applications in mgt.net from other networks, where the firewall allows the other networks only to access the teleport machine.

Basically what I am trying to achieve is using teleport in agentless mode for applications. The FAQ claims that this is possible (https://goteleport.com/docs/faq/) but the documentation does not describe how to do it.

So I tried this confg:

```
version: v3
teleport:
  nodename: teleport.mgt.net
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  advertise_ip: <redacted>
auth_service:
  enabled: "yes"
  cluster_name: mgt
  listen_addr: 0.0.0.0:3025
  public_addr: teleport.mgt.net:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.mgt.net:3080
  ssh_public_addr: teleport.mgt.net:3023
  https_keypairs:
  - key_file: /etc/teleport/key.pem
    cert_file: /etc/teleport/fullchain.pem
  https_keypairs_reload_interval: 1h
  acme: {}
app_service:
  enabled: "yes"
  apps:
  - name: "something"
    uri: "https://other.mgt.net:7443"
    public_addr: "something.teleport.mgt.net"
    insecure_skip_verify: true
```

Does the app service actually need a token to be able to talk to the auth and proxy services when it is running in the same instance? How do I configure this in this case?

The current config gives me an application item where clicking the uri leads to no success:
```
Access Denied
NetworkError when attempting to fetch resource.
```

However, running `curl --insecure https://other.mgt.net:7443` on the teleport machine works.
