### DISCUSSION TITLE
How to configure Teleport App service for VMware vCenter web UI?

### DISCUSSION THREAD

**Discussion by furrnace** [gravitational/teleport#25746] [Q&A] [answered]
I would like to access the web UI of vCenter through Teleport. I always get `[400] An error occurred while sending an authentication request to the vCenter Single Sign-On server - An error occurred when processing metadata during vCenter Single Sign-On setup: the service provider validation failed. Verify that the server URL is correct and is in FQDN format, or that the hostname is a trusted service provider alias.` when trying to access.

In theory one can edit the domain name hat vCenter is using, but that is a risky thing to do, as you might lose access to your vCenter and need to rebuild from ground, not a fun exercise.

I have already tried to get this to work with support from Teleport staff on the Teleport Slack. I did not get a solution from there.

If someone got that to work I would be happy to see the configuration for Teleport. This is what I have now:

```
- name: "vcenter"
    insecure_skip_verify: true
    uri: "https://vcenter.ex.com"
    rewrite:
      redirect:
      - vcenter.ex.com
      headers:
      - "Origin: https://vcenter.teleport.ex.com"
      - "Host: vcenter.teleport.ex.com"
```
