### DISCUSSION TITLE
How to configure Teleport App service for Xen Orchestra web UI?

### DISCUSSION THREAD

**Discussion by furrnace** [gravitational/teleport#25744] [Q&A]
I would like to access the web UI of Xen Orchestra (https://xen-orchestra.com/docs/) through Teleport. On the login page after entering the credentials and clicking Sign-In the Login page just refreshs and clears the input fields and nothing else happens.

I checked the documentation regarding reverse proxy settings. Teleport allows me to put the header settings as you can see in the attached config, nothing else.

I have already tried to get this to work with support from Teleport staff on the Teleport Slack. I did not get a solution from there.

If someone got that to work I would be happy to see the configuration for Teleport. This is what I have now:

```
- name: "xo"
    insecure_skip_verify: true
    uri: "https://xo.ex.com"
    rewrite:
      redirect:
      - xo.ex.com
      headers:
      - "Origin: https://xo.teleport.ex.com"
      - "Host: xo.teleport.ex.com"
```
