### DISCUSSION TITLE
How to configure Teleport App service for APC UPS Network Management Card (NMC) web UI?

### DISCUSSION THREAD

**Discussion by furrnace** [gravitational/teleport#25745] [Q&A]
I would like to access the web UIs of my APC UPS NMCs through Teleport. I always get Internal Server Error (from Teleport) when trying to access. This indicates some behavior on the end of the NMC web UI which Teleport cannot handle. Teleport is OK with TLS 1.2 (which the NMCs use), so that is not the problem here.

I have already tried to get this to work with support from Teleport staff on the Teleport Slack. I did not get a solution from there.

If someone got that to work I would be happy to see the configuration for Teleport. This is what I have now (and should be fine according to Teleport staff):

```
- name: "nmc1"
    insecure_skip_verify: true
    uri: "https://nmc1.ex.com"
    rewrite:
      redirect:
      - nmc1.ex.com
      headers:
      - "Origin: https://nmc1.teleport.ex.com"
      - "Host: nmc1.teleport.ex.com"
```
