### DISCUSSION TITLE
How to configure Teleport App service for Supermicro IPMI web UI iKVM/HTML5 console

### DISCUSSION THREAD

**Discussion by furrnace** [gravitational/teleport#25747] [Q&A] [answered]
The SuperMicro IPMI (redfish) web UI can be used through teleport, but the iKVM/HTML5 console does not work. That’s of course the major value of IPMI, to be able to access the console/BIOS remotely. Would be great to get this to work.

When clicking the button to open the iKVM a new window opens for the console, but shortly after there is an error pop-up window: `Server disconnected (code: 1006)`

To be more specific the problem impacts server boards with the Firmware Revision 3.95 (2021-12-23) or lower, Redfish 1.0.1 or lower. That is the last BMC firmware version for these boards, they cannot be updated to the new BMC version that comes with newer boards, and which supposedly works out of the box with Teleport. However, hardware from 2021 or earlier is and will be in the field for a number of years. These boards are actually still being sold by SuperMicro today.

If someone got that to work I would be happy to see the configuration for Teleport. This is what I have now:

```
- name: "ipmi"
    insecure_skip_verify: true
    uri: "https://ipmi.ex.com"
    rewrite:
      redirect:
      - ipmi.ex.com
      headers:
      - "Origin: https://ipmi.teleport.ex.com"
      - "Host: ipmi.teleport.ex.com"
```
