### DISCUSSION TITLE
TLS Error when connecting to self hosted postgresql teleport node

### DISCUSSION THREAD

**Discussion by cdestouni-fmp** [gravitational/teleport#26217] [Q&A] [answered]
I can connect to a node managed by teleport using SSH without issues, however when it comes to configuring a teleport self-hosted postgres database service I am unable to get the connection to establish. This is all being ran locally for testing purposes.

## Setup

Teleport version: 13

docker-compose.yaml

```yaml
volumes:
  data: ~
  tokens: ~
  certs: ~

services:
  teleport-server:
    image: public.ecr.aws/gravitational/teleport:13
    hostname: teleport-proxy
    entrypoint:
      [
        '/usr/bin/dumb-init',
        'teleport',
        'start',
        '--insecure',
        '-c',
        '/etc/teleport/teleport.yaml',
      ]
    ports:
      - '3023:3023'
      - '3024:3024'
      - '3025:3025'
      - '3080:3080'
    volumes:
      - ./teleport.yaml:/etc/teleport/teleport.yaml
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
      - tokens:/mnt/shared/tokens
    healthcheck:
      test: tctl status
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 5s

  node-postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    hostname: node-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    depends_on:
      teleport-server:
        condition: service_healthy
    volumes:
      - certs:/mnt/shared/certs
      - tokens:/mnt/shared/tokens
```

Dockerfile.postgres

```dockerfile
FROM postgres
RUN apt update -y
RUN apt install --no-install-recommends -y sudo curl procps nano
RUN curl https://goteleport.com/static/install.sh | /bin/bash -s 13.0.0
```

teleport.yaml

```yaml
version: v3
teleport:
  nodename: teleport-proxy
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
    - "db,node:testtoken"  
  authentication: 
    second_factor: off
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  tunnel_public_addr: teleport-proxy:3024
```

postgresql.conf

```conf
ssl = on
ssl_cert_file = '/mnt/shared/certs/server.crt'
ssl_key_file = '/mnt/shared/certs/server.key'
ssl_ca_file = '/mnt/shared/certs/server.cas'
```

pg_hba.conf

```conf
hostssl all             all             ::/0                    cert
hostssl all             all             0.0.0.0/0               cert
```

## Problem

We followed the Database Access with Self-Hosted PostgreSQL [guide](https://goteleport.com/docs/database-access/guides/postgres-self-hosted/) using the above docker environment for local testing.

Generate token file to shared mount

```shell
docker exec teleport-ssh-access-teleport-server-1 /bin/bash -c 'tctl tokens add --type=node,db --format=text > /mnt/shared/tokens/token.file'
```

Create teleport client db configuration file

```shell
teleport db configure create \
    -o file \
   --token=/mnt/shared/token/token.file \
   --proxy=teleport-proxy:3080 \
   --name=node-postgres \
   --protocol=postgres \
   --uri=node-postgres:5432 \
   --labels=env=dev
```

Start the teleport db service

```shell
teleport db start \
    --token=/mnt/shared/tokens/token.file \
    --name=node-postgres \
    --protocol=postgres \
    --uri=node-postgres:5432 \
    --labels=env=dev \
    --insecure
```

At this point we should see the node-postgres host listed in the UI under the databases page. Then I click connect and it suggest the below commands for me to run.

```shell
tsh login --proxy=localhost:3080 --auth=local --user=testuser teleport-proxy
tsh db login [--db-user=<user>] [--db-name=<name>] node-postgres
tsh db connect [--db-user=<user>] [--db-name=<name>] node-postgres
```

I ran the follow commands:

```shell
tsh login --proxy=localhost:3080 --auth=local --user=testuser teleport-proxy --insecure
tsh db login --db-user=postgres --db-name=postgres node-postgres
tsh db connect --db-user=postgres --db-name=postgres node-postgres
```

And I hit the following error:

```shell
psql: error: server refused TLS connection
ERROR: exit status 2
```

The docker logs on the node-postgres service are below:

```log
2023-05-15T09:56:02Z ERRO [DB:SERVIC] Failed to handle connection. addr:172.30.0.1:38330 error:[
ERROR REPORT:
Original Error: *errors.errorString server refused TLS connection
Stack Trace:
        github.com/gravitational/teleport/lib/srv/db/common/errors.go:147 github.com/gravitational/teleport/lib/srv/db/common.ConvertConnectError
        github.com/gravitational/teleport/lib/srv/db/postgres/engine.go:237 github.com/gravitational/teleport/lib/srv/db/postgres.(*Engine).connect
        github.com/gravitational/teleport/lib/srv/db/postgres/engine.go:124 github.com/gravitational/teleport/lib/srv/db/postgres.(*Engine).HandleConnection
        github.com/gravitational/teleport/lib/srv/db/server.go:933 github.com/gravitational/teleport/lib/srv/db.(*Server).handleConnection
        github.com/gravitational/teleport/lib/srv/db/server.go:856 github.com/gravitational/teleport/lib/srv/db.(*Server).HandleConnection
        github.com/gravitational/teleport/lib/reversetunnel/transport.go:308 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
        github.com/gravitational/teleport/lib/reversetunnel/agent.go:587 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
        runtime/asm_amd64.s:1598 runtime.goexit
User Message: server refused TLS connection] db/server.go:858
```
