### DISCUSSION TITLE
Configuring Teleport 13+ behind nginx as an HTTPS reverse proxy

### DISCUSSION THREAD

**Discussion by webvictim** [gravitational/teleport#26445] [Show and tell]
Here's how to configure Teleport 13+ behind `nginx` as an HTTPS reverse proxy.

Notes:
- In all examples, replace `teleport.example.com` with your own public domain.
- Teleport listens on port 3080. nginx listens on port 443 and forwards traffic to port 3080.
  - It also optionally listens on port 80 to forward requests for http://teleport.example.com to https://teleport.example.com
- Port 443 must be open to the outside via firewall/security groups etc.
  - Also open port 80 for HTTP redirection if you want that
- Add an A record for `teleport.example.com`, pointing to the external IP address of your nginx server
  - Also add an A record for `*.teleport.example.com` pointing to the external IP address of your nginx server if you want to use Teleport application access
  - ~~If you're using Cloudflare, your DNS records must be set to "DNS only" rather than "proxied"~~ EDIT: Since version 15.1, Teleport uses regular websocket upgrades which work fine with Cloudflare proxying. However, Application Access subdomains should remain unproxied ("DNS only") unless you're using Advanced Certificate Manager.
- You will need to get a valid TLS certificate for your domain using something like `certbot` which you can supply to nginx:
  - Example: `sudo certbot certonly -d teleport.example.com`
- If you want to use Teleport application access, you should also add a wildcard SAN to the certificate request. Bear in mind that you will need a DNS-01 challenge to request wildcard certificates, which may require a certbot plugin and additional configuation.
  - Example: `sudo certbot certonly -d teleport.example.com,*.teleport.example.com --dns-route53`
- Don't forget to configure a cron job or some kind of process to automatically run `certbot renew` at least every 90 days
  - Add a hook to automatically reload `nginx` to read the updated certificates when this is done.
- Teleport itself will use a self-signed certificate and does not need to be configured to use `certbot`.
- Make sure you're using Teleport version 13+, and that you have `tsh` version 13+ installed locally.
  - If you're using an older version of `tsh`, commands like `tsh login` will not work as expected. Check your version with `tsh version` and upgrade if necessary.

`/etc/teleport.yaml`:
```yaml
version: v3
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: true
  cluster_name: "teleport.example.com" # update to your own public domain
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  authentication:
    second_factor: on
    webauthn:
      rp_id: teleport.example.com # update to your own public domain
ssh_service:
  enabled: true
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.example.com:443 # update to your own public domain
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
  trust_x_forwarded_for: true
# optional: enable the app service
app_service:
  enabled: true
  debug_app: true
  apps:
  - name: test
    uri: http://localhost:8000
```

`/etc/nginx/conf.d/teleport.conf`:
```
server {
    server_name teleport.example.com *.teleport.example.com; # update to your own public domain
    client_max_body_size 1024M;

    location / {
        proxy_set_header Host $http_host;
        proxy_pass https://127.0.0.1:3080;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen [::]:443 ssl;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/teleport.example.com/fullchain.pem; # change this to your actual domain/path
    ssl_certificate_key /etc/letsencrypt/live/teleport.example.com/privkey.pem; # change this to your actual domain/path
}

# optional section - listen for HTTP requests on port 80 and redirect them to HTTPS on 443
server {
    server_name teleport.example.com *.teleport.example.com; # update to your own public domain

    # update to your own public domain
    if ($host = teleport.example.com) {
        return 301 https://$host$request_uri;
    }

    listen [::]:80;
    listen 80;
    return 404;
}
```

Once these files are in place, start Teleport with `sudo systemctl start teleport` or similar, then start nginx with `sudo systemctl start nginx`.

- You can check Teleport logs with `sudo journalctl -u teleport -f`.
- You can check nginx's default access log using `sudo tail -F /var/log/nginx/access.log`

If you have any issues, post comments here for assistance. We'd also love to hear if you just get it working!

**Comment by sbourdette** [comment]
Hi, thank you for your tutorial.
I have tried to adapt to my configuration but I'm block.

The difference is that I use cloudflare and cloudflare universal SSL doesnt support sub sub domain
So I had to configure a `public_addr` for my application : app1.example.com

Now I have a CORS preflight issue in browser's console :

`app1.example.com:1 Access to fetch at 'https://app1.example.com/x-teleport-auth' from origin 'https://tele.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

I tried to add in teleport config app : 

```
    rewrite:
      headers:
        - "Origin: https://tele.bourdette.com"
        - "Access-Control-Allow-Origin: *"
```

I have put in nginx 

`        proxy_set_header Access-Control-Allow-Origin *;
`

**Reply by webvictim** [reply]
I'm afraid I can't recreate this either. I set up an app with a config like this:

```yaml
app_service:
  enabled: true
  debug_app: true
  apps:
  - name: test
    uri: http://localhost:8000
    public_addr: gus-nginx-app-test.teleportdemo.com
```

The public address of my cluster is a different subdomain of the same root domain (`teleportdemo.com`):

```yaml
proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:3080
  public_addr: gus-nginx.teleportdemo.com:443
```

I pointed the DNS records for both to my server's IP.

I ran `sudo certbot -d *.teleportdemo.com --plugin route53` to get a wildcard cert for everything under `teleportdemo.com`:

```
[ec2-user@ip-172-31-28-4 ~]$ sudo openssl x509 -in /etc/letsencrypt/live/teleportdemo.com/fullchain.pem -text | grep -A1 "Subject Alternative"
            X509v3 Subject Alternative Name:
                DNS:*.teleportdemo.com
```

I provided that to `nginx`:
```
    ssl_certificate /etc/letsencrypt/live/teleportdemo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/teleportdemo.com/privkey.pem;
```

Restarted both `nginx` and `teleport`, logged in and saw the application:

![image](https://github.com/gravitational/teleport/assets/897821/623ff7b8-6d8b-4d3a-8f72-1229c028c1f0)

When I click "Launch", the application loads fine:

![image](https://github.com/gravitational/teleport/assets/897821/c667924d-af0e-4639-bfba-6d3039b86b43)

(the 500 error is because there's actually nothing listening on `http://localhost:8000`)
```
May 26 16:23:20 ip-172-31-28-4.us-east-2.compute.internal teleport[466948]: 2023-05-26T16:23:20Z ERRO             Error forwarding to /, err: dial tcp 127.0.0.1:8000: connect: connection refused forward/fwd.go:176
```

I'm not sure exactly what the issue is here :(

I'm not using Cloudflare so I have to conclude that's probably where the root of the issue lies.

**Comment by mighty-services** [comment]
Hey Guys,

thanks a ton for all your questions and answers. I'm also fighting with a reverse proxy setup. I'm using the nginx proxy manager, since I'm not that skilled to use pure config-files. I got it working though... I read somewhere (I'm sorry I forgot the Website), to create the certificates within nginx proxy manager, copy them over to teleport and add the path within the teleport.yaml file - so it looks like this:
```yaml
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  listen_addr: 0.0.0.0:3023
  public_addr: teleport.example.com:443
  tunnel_public_addr: teleport.example.com:3024
  tunnel_listen_addr: 0.0.0.0:3024
  peer_listen_addr: 0.0.0.0:3022
  ssh_public_addr: teleport.example.com:3023
  kube_listen_addr: 0.0.0.0:3026
  kube_public_addr: teleport.example.com:3026
  https_keypairs:
  - key_file: /var/lib/teleport/privkey.pem
    cert_file: /var/lib/teleport/fullchain.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```

so what I (also) did was:
- as in [this issue](https://github.com/gravitational/teleport/discussions/15293) described, I removed "proxy_listener_mode: multiplex" from the preconfigured YAML-File
- added this lines to teleport.yaml file
   - tunnel_listen_addr: 0.0.0.0:3024
   - public_addr: teleport.example.com:443
   - tunnel_public_addr: teleport.example.com:3024
   - tunnel_listen_addr: 0.0.0.0:3024
   - peer_listen_addr: 0.0.0.0:3022
   - ssh_public_addr: teleport.example.com:3023
   - kube_listen_addr: 0.0.0.0:3026
   - kube_public_addr: teleport.example.com:3026

I created one entry in nginx proxy manager just for teleport.example.com:
```conf
server {
  set $forward_scheme https;
  set $server         "10.0.9.199";
  set $port           443;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;

  server_name teleport.example.com;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-79/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-79/privkey.pem;

  # added manually
  client_max_body_size 1024M;

  # Block Exploits
  include conf.d/include/block-exploits.conf;

  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;

  # Force SSL
  include conf.d/include/force-ssl.conf;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;

  access_log /data/logs/proxy-host-38_access.log proxy;
  error_log /data/logs/proxy-host-38_error.log warn;

  location / {
  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```
Please note that this file is created by nginx proxy manager itself - I just cut out empty lines.

Then I added another one for the wildcard with no certificate yet:
``` conf
server {
  set $forward_scheme https;
  set $server         "10.0.9.199";
  set $port           443;

  listen 80;
listen [::]:80;

  server_name *.teleport.example.com;

  # Asset Caching
  include conf.d/include/assets.conf;

  # Block Exploits
  include conf.d/include/block-exploits.conf;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;

  access_log /data/logs/proxy-host-39_access.log proxy;
  error_log /data/logs/proxy-host-39_error.log warn;

  location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

Caveats:
- I´m not able to use web-access, since I don´t have my domain registered on any service able to server wildcard-certificates, but I ordered one on [Kzuhlma IT](https://panel.kuhlma-it.de/store/ssl-zertifikate?language=english) to a reasonable price (I think at least)
- I need to copy the certificates manually over to my teleport cluster-host






Feel free to add your two cents to this since my solution is far from perfect :)

**Reply by webvictim** [reply]
You don't need a wildcard certificate unless you're planning to use Teleport application access, and even then it's only a recommendation to save time. I believe Nginx proxy manager has native support for the use of Let's Encrypt to get SSL certificates as well, so you shouldn't need to pay anything at all (unless you mean that you don't have any DNS records for your domain?)

**Reply by mighty-services** [reply]
Thanks for your advise. Yes I want to use the Web access Feature. 

Nginx reverse proxy manager doesn't support the Hoster, where my domain is registered. If you are on cloud flare for instance, you can use the DNS challenge to get a wildcard certificate through let's Encrypt.
the other option would be to move one of the supported Hoster, which is not an option for me... Or to use the generic api method and try to get the api of the Hoster working for me. Since I'm not good at that and there's not enough documentation from my Hoster, this isn't an option either.

**Comment by mighty-services** [comment]
But if a wildcard certificate is only optional, please share with me, how I can get access to websites. Right now the teleport cluster  access (with the webUI and the tsh command) works fine. ALSO the implementation of new nodes runs flawless, but when I add a local website it's giving me a self-signed certificate warning.:
![grafik](https://github.com/gravitational/teleport/assets/71066192/0ba0fa8e-b32b-474b-a1e4-efa18208388d)

**Reply by webvictim** [reply]
So say your cluster is `teleport.example.com` and your application is `app.teleport.example.com`. You have two options:

- Get a wildcard certificate which has `teleport.example.com` and `*.teleport.example.com` as SANs (Subject Alternative Names)
  - The benefit of this method is that if you then add `app2.teleport.example.com`, the wildcard certificate will cover that app too.
  - The downside is that ACME services like Let's Encrypt or ZeroSSL will require a DNS challenge to issue a wildcard certificate, which may not be possible with all providers as you've mentioned above.

- If you can't use wildcards, you can get one or more certificates which cover `teleport.example.com` and `app.teleport.example.com` as SANs.
  - The downside of this is that every time you add a new application, you'll need a new certificate for it.

**Comment by mighty-services** [comment]
Thanks Webvictim,

so in my case, where I want to utilize the App-Section for many Services, wildcard is the only real option.

This didn't change with teleport 13.0 upward, right?

The change from that version on is, that a reverse proxy-szenario is supported by default, like you said [here](https://github.com/gravitational/teleport/discussions/15293#discussioncomment-6318990)

**Reply by webvictim** [reply]
Yes, correct, nothing has changed with regard to certificate requirements in Teleport 13 - but we added the ability to deploy Teleport behind a layer 7 load balancer/HTTP proxy.

**Comment by Borega** [comment]
After some work I got this to work for applications. The Problem I am facing now is the following: it works only for applications that run on http. Some of my applications run on https with a self signed cert. These do not work. Any Idea how to get them to work?

**Reply by webvictim** [reply]
This config on the Teleport side should work:

```yaml
app_service:
  enabled: true
  debug_app: true
  apps:
  - name: test
    uri: https://localhost:8888
    insecure_skip_verify: true
```
