### DISCUSSION TITLE
'{{internal.logins}}' means what?

### DISCUSSION THREAD

**Discussion by abolast** [gravitational/teleport#27355] [Q&A] [answered]
I want to allow the teleport user “abc” can login to the ssh node using abc(the node itself has an abc user).
I see the '{{internal.logins}}'  parameter, I can't find any more descriptions of the parameter, I guess '{{internal.logins}}'  refers to the current teleport username, is that right?
I didn't assign any --logins when I created the abc user, just `sudo tctl users add abc --roles=ssh`, and I failed to log in to ssh as the abc user in the webUI using the abc user.  `disconnected , access denied to abc connecting to `
I want to know '{{internal.logins}}' means what?
```
kind: role
metadata:
  id: 1685947318792800089
  name: ssh
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    node_labels:
      hostname: webdevop
  deny: {}
  options:
    cert_format: standard
    create_desktop_user: false
    create_host_user: true
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
```

**Comment by dgkirkwood** [comment, marked as answer]
Hi @abolast,

You are correct in that `{{internal.logins}}` refers to a specific `logins` trait which can be set against users. 

This can be set using the tctl admin tool, for example `tctl users add abc --roles=ssh --logins=abc`.

This can also be set in a YAML configuration per user, for example
```
kind: user
version: v2
metadata:
  name: abc
spec:
  roles: ['ssh']
  traits:
    logins: ['abc']
```

You could also hard code usernames into the role definition if they are common to anyone with the role. For example:
```
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    - abc
```

Hopefully this explains things!
Dan.

**Reply by abolast** [reply]
Thank you so much for your help. I have now understood the meaning of '{{internal.logins}}'.It should be used to set traits. 
"Trait" is a keyword, and due to my limited proficiency in English, I overlooked it while reading the document.

**Comment by abolast** [comment]
```
kind: user
version: v2
metadata:
  name: abc
spec:
  roles: ['ssh']
  traits:
    logins: ['abc','bbb','ddd']
```

'{{internal.logins}}'  means one of 'abc','bbb','ddd'
♪（＾∀＾○）♪
