### DISCUSSION TITLE
Command only recording on SSH

### DISCUSSION THREAD

**Discussion by fireballsp** [gravitational/teleport#27932] [Ideas]
Hi,

It is possible to have recording only of commands without a fully session record? 

Thanks

**Comment by webvictim** [comment]
This is the default if you run single non-interactive commands i.e. `tsh ssh user@host ls -lR /` 

To get exactly what you want for interactive sessions, you could _try_:
- enabling [enhanced session recordings](https://goteleport.com/docs/server-access/guides/bpf-session-recording/) (requires a 5.7+ kernel with BPF support compiled in) at the node level
- disabling regular session recordings at the cluster level.

I'm actually not sure if this works - but it might.

Auth/proxy server:

```yaml
auth_service:
  enabled: true
  session_recording: off
```

Nodes:
```yaml
ssh_service:
  enabled: true
  enhanced_recording:
    enabled: true
```
