### DISCUSSION TITLE
Using Machine ID with the Teleport Terraform provider

### DISCUSSION THREAD

**Discussion by webvictim** [gravitational/teleport#28491] [Show and tell]
Here's a guide on how to use [Machine ID](https://goteleport.com/docs/machine-id/introduction/) in conjunction with the [Teleport Terraform provider](https://goteleport.com/docs/reference/terraform-provider/) to programmatically apply roles and other resources to your Teleport cluster.

1) On your Teleport cluster, create a `terraform` role with these permissions:
```yaml
kind: role
metadata:
  name: terraform
spec:
  allow:
    db_labels:
      '*': '*'
    app_labels:
      '*': '*'
    rules:
      - resources:
        - app
        - cluster_auth_preference
        - cluster_networking_config
        - db
        - device
        - github
        - login_rule
        - oidc
        - okta_import_rule
        - role
        - saml
        - session_recording_config
        - token
        - trusted_cluster
        - user
        verbs: ['list','create','read','update','delete']
version: v6
```

2. Log into your cluster with `tsh login --proxy=teleport.example.com`, then add a bot with the `terraform` role:

```
gus@ip-172-31-30-140:~# tctl bots add terraform-bot --roles terraform
The bot token: 853e531ed4765eb25a827bf3d91d7c5d
This token will expire in 59 minutes.
...
```

3. Write a config file for the bot (you can get the CA pin from `tctl status`):

```yaml
onboarding:
  # change this to match your token
  token: 853e531ed4765eb25a827bf3d91d7c5d
  ca_path: ""
  ca_pins:
  # set your own CA pin here (from tctl status)
  - sha256:015c54b353210befba6e36480f0db89541b7a94d088c0cea21ffc2ea27848799
  join_method: token
# tbot will keep its own data in this path
storage:
  directory:
    path: ./tbot-data
# set this to the path you want your short-lived certificates outputted to
destinations:
  - directory:
      path: ./tbot-output
debug: false
# although this says "auth server", you should put your Teleport PROXY server URL here, usually with port 443 or 3080
auth_server: teleport.example.com:443
# the short-lived certificates outputted will be valid for 1 hour
certificate_ttl: 1h0m0s
# certificates will be renewed this often when oneshot: false
renewal_interval: 20m0s
oneshot: true
```

4. Run the bot with `tbot start -c ./tbot.yaml`:
```
gus@apollo:~/se/terraform-provider-new/tbot % tbot start -c tbot.yaml
INFO [TBOT]      Anonymous telemetry is not enabled. Find out more about Machine ID's anonymous telemetry at https://goteleport.com/docs/machine-id/reference/telemetry/ tbot/anonymous_telemetry.go:83
INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:479
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:277
INFO [AUTH]      Successfully registered via proxy server. auth/register.go:284
INFO [TBOT]      Successfully generated new bot identity, valid: after=2023-06-29T20:32:05Z, before=2023-06-29T21:33:05Z, duration=1h1m0s | kind=tls, renewable=true, disallow-reissue=false, roles=[bot-terraform-bot-2], principals=[-teleport-internal-join], generation=1 tbot/tbot.go:422
INFO [TBOT]      Beginning renewal loop: ttl=1h0m0s interval=20m0s tbot/renew.go:693
INFO [TBOT]      Started watching for CA rotations tbot/ca_rotation.go:173
INFO [TBOT]      Successfully renewed bot certificates, valid: after=2023-06-29T20:32:06Z, before=2023-06-29T21:33:06Z, duration=1h1m0s | kind=tls, renewable=true, disallow-reissue=false, roles=[bot-terraform-bot-2], principals=[-teleport-internal-join], generation=2 tbot/renew.go:601tes successfully. One-shot mode enabled so exiting. tbot/renew.go:747
```

(this bot has `oneshot: true` in its config file, so it will only get certificates once and then exit. If you want it to stay running and refresh certificates regularly, set `oneshot: false` instead)

5. You can find the outputted certificates in the `tbot-output` directory:
```
gus@apollo:~/se/terraform-provider-new/tbot % ls -l tbot-output
total 96
-rw-------  1 gus  staff  8562 29 Jun 17:19 identity
-rw-------  1 gus  staff  1679 29 Jun 17:19 key
-rw-------  1 gus  staff  1826 29 Jun 17:19 key-cert.pub
-rw-------  1 gus  staff   381 29 Jun 17:19 key.pub
-rw-------  1 gus  staff   910 29 Jun 17:19 known_hosts
-rw-------  1 gus  staff  1572 29 Jun 17:19 ssh_config
-rw-------  1 gus  staff  1257 29 Jun 17:19 teleport-database-ca.crt
-rw-------  1 gus  staff  2575 29 Jun 17:19 teleport-host-ca.crt
-rw-------  1 gus  staff  1257 29 Jun 17:19 teleport-user-ca.crt
-rw-------  1 gus  staff  1614 29 Jun 17:19 tlscert
```

6. Write a `provider.tf` file for Terraform, telling it to use the tbot `identity` file:

```hcl
terraform {
  required_providers {
    teleport = {
      # match this to the version of your Teleport cluster
      version = "13.1.0"
      source  = "terraform.releases.teleport.dev/gravitational/teleport"
    }
  }
}

provider "teleport" {
  # put your Teleport proxy server address here
  addr               = "teleport.example.com:443"
  # Put the path to the tbot-output/identity file here
  identity_file_path = "/Users/gus/se/terraform-provider-new/tbot/tbot-output/identity"
}
```

Once you've configured a backend for Terraform and created some resource files, you should be able to run `terraform init`, `terraform plan`, `terraform apply` etc.

You'll see entries appear in the audit log:
![image](https://github.com/gravitational/teleport/assets/897821/70756bc3-7404-4311-bdd6-8fd992d6a03f)

```json
{
  "cluster_name": "gus.teleportdemo.com",
  "code": "T9000I",
  "ei": 0,
  "event": "role.created",
  "expires": "0001-01-01T00:00:00Z",
  "impersonator": "bot-terraform-bot",
  "name": "terraform-test",
  "time": "2023-06-29T20:25:18.91Z",
  "uid": "45e3ce3c-6930-4869-9e7a-100c3b928a6c",
  "user": "bot-terraform-bot"
}
```

Let us know how you get on!
