### DISCUSSION TITLE
Traefik configuration

### DISCUSSION THREAD

**Discussion by ilbarone87** [gravitational/teleport#28565] [Show and tell]
Since I couldn't find any example for traefik dynamic config and if someone is struggling to set this up (like i did for the last 5hrs... funny times), here it is a working yaml config (the middlewares should be optional haven't tested without them):

```
http:
  routers:
    teleport-ssl:
      rule: "Host(`teleport.domain.com`)"
      service: teleport
      middlewares:
        - https-redirect
        - secure-headers
      entryPoints:
        - websecure
      tls: true

  services:
    teleport:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://xx.xx.xx.xx:3080"

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
   secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          X-Forwarded-Proto: "https"
```
teleport.yaml

```
version: v3
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: true
  cluster_name: teleport.domain.com
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  authentication:
    second_factor: on
    webauthn:
      rp_id: teleport.domain.com
ssh_service:
  enabled: true
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.domain.com:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```
