### DISCUSSION TITLE
unexpected cluster name "teleport.tld" for signing ca (expected "teleport")

### DISCUSSION THREAD

**Discussion by eleaner** [gravitational/teleport#28647] [Q&A] [answered]
I am trying to move my cluster from CT behind traefik to own VPS with own IP and getting the error like in the subject

i did the
`tctl get all --with-secrets > state.yaml`
scp the file to new host and followed the instructions further
```
mkdir fresh && cat > fresh.yaml << EOF
teleport:
  data_dir: fresh
EOF
```

`sudo teleport start --config fresh.yaml --bootstrap state.yaml`

ports are open
the old DNS A was working with wildcard managed by  traefik so *.tld
I created new DNS A entry where the teleport.tld points directly to the IP of the new VPS

I did not temper with the file nor did I try to change the cluster name

how do I fix it?

**Comment by webvictim** [comment, marked as answer]
The cluster name is also embedded into the CAs (which are being exported as part of your `tctl get all --with-secrets` command) so you'd also need to keep the same cluster name as you were using before when you re-import:

```yaml
teleport:
  data_dir: fresh
auth_service:
  enabled: true
  cluster_name: teleport.tld
proxy_service:
  enabled: true
  public_addr: teleport.tld:443
```
