### DISCUSSION TITLE
Keep existing CockroachDB node certs when integrating with Teleport

### DISCUSSION THREAD

**Discussion by philip-teleport** [gravitational/teleport#28818] [Show and tell]
When setting up Teleport Database Access with Self-Hosted CockroachDB, the default approach is to replace the existing node certificates with Teleport certificates, as described [here](https://goteleport.com/docs/database-access/guides/cockroachdb-self-hosted/#set-up-mutual-tls).

However, you can keep the existing CockroachDB node certs using the "[Split CA certificates](https://www.cockroachlabs.com/docs/stable/create-security-certificates-custom-ca.html#split-ca-certificates)" option in CockroachDB:

1. Generate the Teleport secrets by running the following `tctl` command against your Teleport cluster; this will produce 3 files, `ca.crt`, `node.crt` and `node.key`:  
```
 tctl auth sign \
      --format=cockroachdb \
      --host=roach.example.com \
      --out=/path/to/cockroach/certs/dir/ \
      --ttl=2190h
 ```
2. Rename `ca.crt` to `ca-client.crt`, `node.crt` to `client-node.crt` and `node.key` to `client-node.key` to match the file names in the CockroachDB documentation.
3. Copy/transfer these files to the CockroachDB certs directory (i.e. the location of the `--certs-dir` flag) and restart your CockroachDB nodes.
4. Copy the existing `node.crt` file from the CockroachDB certs directory to the where you will run the Teleport Database Service.
5. Configure the Teleport `db_service` in the `/etc/teleport.yaml` as shown below, pointing the TLS `ca_cert_file` attribute to the location of `node.crt` file:
```
db_service:
  enabled: true
  databases:
  - name: "roach"
    protocol: "cockroachdb"
    uri: "localhost:26257"
    static_labels:
      "env": "test"
    tls:
      mode: "verify-full"
      # content of node.crt
      ca_cert_file: /etc/cockroachdb/certs/node.crt
```

In this scenario, the `node.crt` is the server certificate used when a node receives incoming connections from clients (e.g. Teleport) and other nodes. But the cert used for client connection verification (`ca-client.crt`) is not the same as cert presented by CockroachDB to a client, this is `node.crt`. So the Teleport Database Service is configured to trust the the self-signed `node.crt` presented by CockroachDB during handling incoming client connection.
