### DISCUSSION TITLE
Teleport DB Access

### DISCUSSION THREAD

**Discussion by CiscoNCS** [gravitational/teleport#29191] [Q&A] [answered]
Hi,

Configured DB service on teleport i got 1 MS SQL access working through SSMS question is am i able to add multiple MS SQL servers using the same node but additional URI and other relevent config.

Thanks

**Comment by webvictim** [comment, marked as answer]
Yes, the `databases` part of the config is a YAML list so you can add multiple databases if desired.

```yaml
db_service:
  enabled: yes
  databases:
- name: sqlserver
  protocol: sqlserver
  uri: sqlserver.example.com:1433
  ad:
    keytab_file: /path/to/teleport.keytab
    domain: EXAMPLE.COM
    spn: MSSQLSvc/sqlserver.example.com:1433
  static_labels:
    "env": "staging"
- name: sqlserver-dev
  protocol: sqlserver
  uri: sqlserver-dev.example.com:1433
  ad:
    keytab_file: /path/to/teleport.keytab
    domain: EXAMPLE.COM
    spn: MSSQLSvc/sqlserver-dev.example.com:1433
  static_labels:
    "env": "dev"
```

You will need to manage the keytab and SPN configuration correctly on the node to make sure it's able to authenticate to both databases.
