### DISCUSSION TITLE
join token with terraform

### DISCUSSION THREAD

**Discussion by redpimpernel** [gravitational/teleport#29662] [Q&A]
Hi, I am trying to join a vps to teleport using a token that was generated in terraform.
I have been following the guide: [deploy agents with terraform](https://goteleport.com/docs/agents/deploy-agents-terraform/).
However, what is copied to the vps in the guide, is the token ID which is different to the actual token. When I try to join an agent using the generated ID, I get the error, "Can not join the cluster as node, the token expired or not found...". 

Even though the guide shows the necessary steps using the ID of the `teleport_provision_token` terraform resource, I feel this must be wrong, or I am really misunderstanding something:

Below are snippets of my Infrastructure as code.
**Token generation:**
```
resource "teleport_provision_token" "node_test" {
  metadata = {
    #expires = timeadd(timestamp(), "1h")
  }
  spec = {
    roles = ["Node"]
    name = random_string.token.result
  }
}
```
I then take the token that was created and set it as an output in my teleport terraform module.

**Token output variable from module:**
```
output "test_token" {
    value = teleport_provision_token.node_test.id
}
```
After the above resource is created, it is passed to a terraform resource that creates a Linode VPS and runs an ansible playbook.

**Ansible task:**
```
- name: generate teleport config
  shell: "teleport configure \
  --roles=node \
  --token={{tele_token}} \
  --proxy=teleport.<domain>:443
  -o file
  "
```
That ansible task creates the teleport config that I am then using to try and connect the new linode vps to my running teleport instance.
**Teleport config:**
```
version: v3
teleport:
  nodename: test1
  data_dir: /var/lib/teleport
  join_params:
    token_name: "1690419665248792804"
    method: token
  proxy_server: teleport.<domain>:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```

If I manually edit the generated teleport config and replace it with the actual token (not the ID) it works.

I am very, very stuck and would greatly appreciate any help and advice.
