### DISCUSSION TITLE
Web application access denied

### DISCUSSION THREAD

**Discussion by Soldier2003** [gravitational/teleport#29728] [Q&A] [answered]
Expected behavior:
Successful connection to the web application.

Current behavior:
Access Denied
Unable to access "teleporttest1.seclab.local". This may happen if your Teleport Proxy is using untrusted or self-signed certificate. Please ensure Teleport Proxy service uses valid certificate or access the application domain directly (https://teleporttest1.seclab.local) and accept the certificate exception from your browser.

Bug details:
- Teleport version: 13.2.0

- Recreation steps:

Was installed separately:
1) Domain controller Windows Server 2019 (seclab.local) with DNS role for Windows machines
2) Certification Authority Windows Server 2019 for issuing certificates
3) teleport (ubuntu 22.04 with updates) - teleport
4) test machine with webmine (ubuntu 22.04 with updates) - teleporttest1

DNS records were created:
A record teleport 10.16.20.30
CNAME *.teleport teleport.seclab.local
A record teleporttest1 10.20.43.162

On the test machine, as well as on the teleport, the root certificate from the certification authority was added to the trusted root ones: 
```
sudo mkdir /usr/local/share/ca-certificates/extra
sudo cp root-ca.crt /usr/local/share/ca-certificates/extra/root-ca.crt
sudo update-ca-certificates 
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

Accordingly, certificates were issued and installed, while SAN were specified in them:
1) for teleport specifying SAN: teleport, teleport.seclub.local, *.teleport.seclub.local
2) for the test specifying SAN: teleporttest1, teleporttest1.seclab.local

At the same time, there is a notification in the browser that the connection is secure, that is, there are no security warnings when opening the teleport page or the webmine page.

teleport.yaml from teleport:
```
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
      #output: json
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.seclab.local
  proxy_listener_mode: multiplex
  session_recording: "node"

ssh_service:
  enabled: "yes"
  
  # Enhanced Session Recording
  # see https://goteleport.com/docs/features/enhanced-session-recording/
  enhanced_recording:
  
   # Enable or disable enhanced auditing for this node. Default value: false.
   enabled: true

   # Optional: command_buffer_size is optional with a default value of 8 pages.
   command_buffer_size: 8

   # Optional: disk_buffer_size is optional with default value of 128 pages.
   disk_buffer_size: 128

   # Optional: network_buffer_size is optional with default value of 8 pages.
   network_buffer_size: 8

   # Optional: Controls where cgroupv2 hierarchy is mounted. Default value:
   # /cgroup2.
   cgroup_path: /cgroup2
  
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
    
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.seclab.local:443
  https_keypairs:
  - key_file: /var/lib/teleport/teleport.key
    cert_file: /var/lib/teleport/teleport.pem
  https_keypairs_reload_interval: 0s
  acme: {}

```

I added the test server for SSH connection using the instructions from WebUI:
sudo bash -c "$(curl -fsSL https://teleport.seclab.local/scripts/ef8a9886bc17b39148243ec787a8d2f8/install-node.sh)"
SSH connection is successful.

After that, I decided to add webmin (test server) as an application for the test, below is an example of a command based on instructions from WebUI (Asterisks replaced the token data):

`teleport configure --output=$HOME/.config/app_config.yaml --app-name=webmine --app-uri=https://localhost:10000/ --roles=app --token=****************************** --proxy=teleport.seclab.local:443 --data-dir=$HOME/.config`

Then I checked the configuration and made edits, as a result, the following file (/home/user/.config/app_config.yaml) turned out (Asterisks replaced the token data):

```
version: v3
teleport:
  nodename: teleporttest1
  data_dir: /home/user/.config
  join_params:
    token_name: ******************************
    method: token
  proxy_server: teleport.seclab.local:443
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: true
  apps:
  - name: 'webmine'
    uri: https://localhost:10000/
    public_addr: "teleporttest1.seclab.local"
    insecure_skip_verify: true
```

Then I executed the command to run:
`teleport start --config=$HOME/.config/app_config.yaml`

The application was displayed in WebUI, but when I try to connect, I get an error message:
Access Denied
Unable to access "teleporttest1.seclab.local". This may happen if your Teleport Proxy is using untrusted or self-signed certificate. Please ensure Teleport Proxy service uses valid certificate or access the application domain directly (https://teleporttest1.seclab.local) and accept the certificate exception from your browser.

- Comments

The certificate authority is not public, and after receiving the error, I tried using the --insecure parameter both on the teleport itself and to run on the test server, but this did not affect the error.

In the attachment, the log from the terminal session of the test server and the teleport logs, unfortunately I could not find any useful information there.

I found the discussion thread #28564 and tried to replace the CNAME record with A record, then the result is the same, besides I checked that the proxy configurations match mine.

I also tried with another test server that responds on standard port 443 (displays a web resource application), but the error was exactly the same.

- Debug logs

[2023-07-14.00%3A00%3A00.log](https://github.com/gravitational/teleport/files/12052877/2023-07-14.00.3A00.3A00.log)
[events.log](https://github.com/gravitational/teleport/files/12052878/events.log)
[terminla-log-teleporttest1.txt](https://github.com/gravitational/teleport/files/12052879/terminla-log-teleporttest1.txt)

**Comment by webvictim** [comment]
I notice that you only have one certificate keypair specified under `proxy_service.https_keypairs` in the Teleport config file that's running your auth and proxy services, but in your comments I think you said that you have two different certificates with two different sets of SANs? Is that the case, or are all those SANs present on one certificate?

Essentially if the Teleport proxy does not think that it can make a secure connection to the `teleporttest1.seclab.local` domain itself, it will show this error. i would expect that in your case you would be specifying both certificates/keys under` https_keypairs` so that Teleport can pick the correct one for the domain it's serving.

**Comment by Soldier2003** [comment]
> I notice that you only have one certificate keypair specified under `proxy_service.https_keypairs` in the Teleport config file that's running your auth and proxy services, but in your comments I think you said that you have two different certificates with two different sets of SANs? Is that the case, or are all those SANs present on one certificate?
> 
> Essentially if the Teleport proxy does not think that it can make a secure connection to the `teleporttest1.seclab.local` domain itself, it will show this error. i would expect that in your case you would be specifying both certificates/keys under` https_keypairs` so that Teleport can pick the correct one for the domain it's serving.

Teleport and webmin are two different servers with two different certificates, but they are issued by the same certification authority.
I specified another certificate, restarted the teleport service on the teleport server, but the error persisted, below is the contents of the configuration file.

teleport.yaml
```
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.seclab.local
  proxy_listener_mode: multiplex
  session_recording: "node"

ssh_service:
  enabled: "yes"
  
  # Enhanced Session Recording
  # see https://goteleport.com/docs/features/enhanced-session-recording/
  enhanced_recording:
  
   # Enable or disable enhanced auditing for this node. Default value: false.
   enabled: true

   # Optional: command_buffer_size is optional with a default value of 8 pages.
   command_buffer_size: 8

   # Optional: disk_buffer_size is optional with default value of 128 pages.
   disk_buffer_size: 128

   # Optional: network_buffer_size is optional with default value of 8 pages.
   network_buffer_size: 8

   # Optional: Controls where cgroupv2 hierarchy is mounted. Default value:
   # /cgroup2.
   cgroup_path: /cgroup2
  
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
    
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.seclab.local:443
  https_keypairs:
  - key_file: /var/lib/teleport/teleport.key
    cert_file: /var/lib/teleport/teleport.pem
  - key_file: /var/lib/teleport/teleporttest1-key.key
    cert_file: /var/lib/teleport/teleporttest1.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```

**Comment by Soldier2003** [comment]
I tried to install the GUI on the teleport server and open the webmin page through the browser, then clicked take a risk and open the page, but the error when trying to use the application via WebUI teleport persisted.

**Comment by Soldier2003** [comment]
I deployed 1 more teleport and a test machine, but now use lets encrypt and the error persists.
It looks like the problem is in the configuration, but based on the documentation I can't figure out exactly where, please help.

**Comment by webvictim** [comment]
Can you share your new configuration files with the changes to use Let's Encrypt?

**Comment by Soldier2003** [comment]
> Can you share your new configuration files with the changes to use Let's Encrypt?

Below are the configuration files from a completely new installation of two servers with webmin and teleport server installed, but let's encrypt is running on the teleport server and 2 certificates are generated: for webmine and teleport

teleport.yaml (from the teleport server):

```
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    #output: stderr
    output: /var/lib/teleport/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: "127.0.0.1:3000"
  # Teleport throttles all connections to avoid abuse. These settings allow
  # you to adjust the default limits
  connection_limits:
      max_connections: 1000
      max_users: 250
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.fortest.tech
  proxy_listener_mode: multiplex
  session_recording: "node"

ssh_service:
  enabled: "yes"
  
  # Enhanced Session Recording
  # see https://goteleport.com/docs/features/enhanced-session-recording/
  enhanced_recording:
  
   # Enable or disable enhanced auditing for this node. Default value: false.
   enabled: true

   # Optional: command_buffer_size is optional with a default value of 8 pages.
   command_buffer_size: 8

   # Optional: disk_buffer_size is optional with default value of 128 pages.
   disk_buffer_size: 128

   # Optional: network_buffer_size is optional with default value of 8 pages.
   network_buffer_size: 8

   # Optional: Controls where cgroupv2 hierarchy is mounted. Default value:
   # /cgroup2.
   cgroup_path: /cgroup2
  
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
    
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.fortest.tech:443
  https_keypairs:
  - key_file: /etc/letsencrypt/live/teleport.fortest.tech/privkey.pem
    cert_file: /etc/letsencrypt/live/teleport.fortest.tech/fullchain.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```

app_config.yaml (from the webmine server):

```
version: v3
teleport:
  nodename: teleport1
  data_dir: /home/user/.config
  join_params:
    token_name: c4da923eadbfde33b44fcb872e5ea0ed
    method: token
  proxy_server: teleport.fortest.tech:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: webmine
    uri: http://localhost/
    public_addr: ""
    insecure_skip_verify: false
```
As you can see, the port for webmin has been changed from the standard 10000 to 443.

**Comment by webvictim** [comment]
1) You should either remove the `public_addr` completely from the app service (setting it to `""` will confuse things) or set it to `webmine.teleport.fortest.tech`.

2) It looks like you're connecting to webmin using http (`uri: http://localhost`) but you said it's listening on port 443? It should be configured as `uri: https://localhost` in that case.

```yaml
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: webmin
    uri: https://localhost/
```

If webmin itself isn't presenting a trusted HTTPS cert with `localhost` as a SAN, you'll also want to set `insecure_skip_verify: true`.

**Comment by Soldier2003** [comment]
> 1. You should either remove the `public_addr` completely from the app service (setting it to `""` will confuse things) or set it to `webmine.teleport.fortest.tech`.
> 2. It looks like you're connecting to webmin using http (`uri: http://localhost`) but you said it's listening on port 443? It should be configured as `uri: https://localhost` in that case.
> 
> ```yaml
> app_service:
>   enabled: "yes"
>   debug_app: false
>   apps:
>   - name: webmin
>     uri: https://localhost/
> ```
> 
> If webmin itself isn't presenting a trusted HTTPS cert with `localhost` as a SAN, you'll also want to set `insecure_skip_verify: true`.

I did not make any changes to the configuration file on the teleport server, I made them only on the webmine server:

app_config.yaml (from the webmine server):

```
version: v3
teleport:
  nodename: teleport1
  data_dir: /home/user/.config
  join_params:
    token_name: c4da923eadbfde33b44fcb872e5ea0ed
    method: token
  proxy_server: teleport.fortest.tech:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: webmine
    uri: https://localhost/
    public_addr: "webmine.teleport.fortest.tech"
    insecure_skip_verify: false
```

Now I'm getting an error: 
Access denied
504 - https://teleport.fortest.tech/v1/webapi/sessions/app

At this time, in the webmin server console, I observe:

```
2023-07-26T12:12:23+03:00 INFO             Starting Teleport v13.2.2 with a config file located at "/home/user/.config/app_config.yaml" common/teleport.go:556
2023-07-26T12:12:24+03:00 INFO [PROC:1]    Connecting to the cluster teleport.fortest.tech with TLS client certificate. pid:60600.1 service/connect.go:262
2023-07-26T12:12:24+03:00 INFO [PROC:1]    Connecting to the cluster teleport.fortest.tech with TLS client certificate. pid:60600.1 service/connect.go:262
2023-07-26T12:12:27+03:00 INFO [PROC:1]    App: features loaded from auth server: Kubernetes:true App:true DB:true Desktop:true Assist:true DeviceTrust:<>  pid:60600.1 service/connect.go:96
2023-07-26T12:12:27+03:00 INFO [PROC:1]    Instance: features loaded from auth server: Kubernetes:true App:true DB:true Desktop:true Assist:true DeviceTru
[teleport_26.07.log](https://github.com/gravitational/teleport/files/12170403/teleport_26.07.log)
st:<>  pid:60600.1 service/connect.go:96
2023-07-26T12:12:27+03:00 INFO [INSTANCE:] Successfully registered instance client. pid:60600.1 service/service.go:2325
2023-07-26T12:12:34+03:00 INFO [APP:SERVI] Cache "apps" first init succeeded. cache/cache.go:863
2023-07-26T12:12:35+03:00 INFO [APP:SERVI] All applications successfully started. pid:60600.1 service/service.go:5105
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  starting upload completer service pid:60600.1 service/service.go:2689
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log/upload. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log/upload owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log/upload/streaming. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log/upload/streaming owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log/upload/streaming/default. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log/upload/streaming/default owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log/upload. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log/upload owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log/upload/corrupted. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log/upload/corrupted owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Creating directory /home/user/.config/log/upload/corrupted/default. pid:60600.1 service/service.go:2705
2023-07-26T12:12:35+03:00 INFO [UPLOAD:1]  Setting directory /home/user/.config/log/upload/corrupted/default owner to 1000:4. pid:60600.1 service/service.go:2712
2023-07-26T12:12:35+03:00 INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status with period 10m0s. pid:60600.1 service/connect.go:811
2023-07-26T12:12:35+03:00 INFO [PROC:COMP] upload completer will run every 5m0s events/complete.go:143
2023-07-26T12:14:07+03:00 INFO [PROXY:AGE] Connection closed, returning leaseID:1 target:teleport.fortest.tech:443 localCluster: targetCluster:teleport.fortest.tech reversetunnel/agent.go:638
2023-07-26T12:14:07+03:00 WARN [PROXY:AGE] Failed to close discovery channel: EOF leaseID:1 target:teleport.fortest.tech:443 localCluster: targetCluster:teleport.fortest.tech reversetunnel/agent.go:627
```

log file from the teleport server
[teleport_26.07.log](https://github.com/gravitational/teleport/files/12170415/teleport_26.07.log)

**Comment by Soldier2003** [comment]
On the following attempts, an error occurred connecting through the tunnel, after which I created a new token and the error is the same again:

Access Denied
Unable to access "webmine.teleport.fortest.tech". This may happen if your Teleport Proxy is using untrusted or self-signed certificate. Please ensure Teleport Proxy service uses valid certificate or access the application domain directly (https://webmine.teleport.fortest.tech) and accept the certificate exception from your browser.

even despite the use of the parameter: insecure_skip_verify: true

**Comment by Soldier2003** [comment, marked as answer]
> 1. You should either remove the `public_addr` completely from the app service (setting it to `""` will confuse things) or set it to `webmine.teleport.fortest.tech`.
> 2. It looks like you're connecting to webmin using http (`uri: http://localhost`) but you said it's listening on port 443? It should be configured as `uri: https://localhost` in that case.
> 
> ```yaml
> app_service:
>   enabled: "yes"
>   debug_app: false
>   apps:
>   - name: webmin
>     uri: https://localhost/
> ```
> 
> If webmin itself isn't presenting a trusted HTTPS cert with `localhost` as a SAN, you'll also want to set `insecure_skip_verify: true`.

I deleted the CNAME *.teleport record and created a *.teleport record, then changed the public_address in the configuration file on the webmin server.

app_config.yaml (from the webmine server):
```
version: v3
teleport:
  nodename: teleport1
  data_dir: /home/user/.config
  join_params:
    #token_name: c4da923eadbfde33b44fcb872e5ea0ed
    token_name: f7372792ffeaf8e1b3c7da3fc5e5df1f
    method: token
  proxy_server: teleport.fortest.tech:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: webmine
    uri: https://localhost/
    #public_addr: "webmine.teleport.fortest.tech"
    public_addr: "teleport1.fortest.tech"
    insecure_skip_verify: true

```

I do not know what kind of magic, but now the webmine page has opened successfully, I did the same thing earlier, but unsuccessfully.
But after entering the login and password, the page is updated and becomes empty, if you open the application again, it is no longer visible that the authorization has passed and the webmine menu opens.

Unfortunately, webmin does not work as expected, when you try to open the edit menu, the system issues an alert about possible interference in the system from the outside, and what is most important, there is no video recording of this session in the teleport.

**Reply by webvictim** [reply]
Teleport doesn't record videos of application sessions, as this is technically impossible without client-side software. It does however log the requests sent to the application by the user's browser.

I'd imagine that webmin is seeing CORS errors because the URL you're using to access it is different to `localhost`. You can try adding `Origin` and `Host` headers in your `app` configuration like this:

```yaml
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: webmin
    uri: https://localhost/
    public_addr: "webmin.teleport.fortest.tech"
    insecure_skip_verify: true
    rewrite:
      headers:
      - "Host: webmin.teleport.fortest.tech"
      - "Origin: https://webmin.teleport.fortest.tech"
```
