### DISCUSSION TITLE
teleport-traefik-letsencrypt-docker-swarm

### DISCUSSION THREAD

**Discussion by mrkhachaturov** [gravitational/teleport#29743] [General]
Hey all!
Can anyone provide a stack to deploy teleport in docker swarm behind traefik?
I would be very grateful.

I found only this compose file in discussions.

```yaml
teleport:
    image: public.ecr.aws/gravitational/teleport:11.2.3
    container_name: teleport
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=net.external"
      - "traefik.tcp.services.teleport-svc.loadBalancer.server.port=3080"
      - "traefik.tcp.routers.teleport.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.teleport.entrypoints=websecure"
      - "traefik.tcp.routers.teleport.tls.passthrough=true"
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
    ports:
      - 3025:3025
      - 3080:3080
      - 3023:3023
    networks:
      - net.external
    restart: unless-stopped
```
