### DISCUSSION TITLE
Pass real client IP to application

### DISCUSSION THREAD

**Discussion by roko99** [gravitational/teleport#29767] [Q&A]
Hello.

I'm trying to setup Teleport in GKE cluster.
Using helm charts for both - agent and cluster.
Values file for cluster:
```
clusterName: "<cluster_domain>"
highAvailability:
  replicaCount: 1
  requireAntiAffinity: false
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  certManager:
    addCommonName: false
    enabled: true
    issuerName: "letsencrypt"
    issuerKind: "ClusterIssuer"
    issuerGroup: "cert-manager.io"
  minReadySeconds: 15
operator:
  enabled: true
authentication:
  type: "local"
  connectorName: "local"
  second_factor: "on"
proxy:
  teleportConfig:
    proxy_service:
      proxy_protocol: "on"
tunnelPublicAddr: [<cluster_domain>]
image: public.ecr.aws/gravitational/teleport
service:
  spec:
    externalTrafficPolicy: Local
```

In this case I have such service with type `LoadBalancer`:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: teleport-cluster
    meta.helm.sh/release-namespace: teleport
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: teleport-cluster
    app.kubernetes.io/version: 13.2.3
    argocd.argoproj.io/instance: infra-teleport-cluster
    helm.sh/chart: teleport-cluster-13.2.3
    teleport.dev/majorVersion: "13"
  name: teleport-cluster
  namespace: teleport
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: <ip>
  clusterIPs:
  - <ip>
  externalTrafficPolicy: Local
  healthCheckNodePort: 30452
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - <ports>
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/name: teleport-cluster
  sessionAffinity: None
  type: LoadBalancer
```

Agent values:
```
proxyAddr: "<cluster_domain>:443"
roles: apps
joinParams:
  method: "kubernetes"
  tokenName: "kubernetes-provision-token"
apps:
- <some_apps>
joinTokenSecret:
  create: true
  name: teleport-app-agent-join-token
image: public.ecr.aws/gravitational/teleport
```

Everything works fine except, that destination app doesn't receive real client IP, instead it got IP address of the agent pod in `x-real-ip` and `x-forwarded-for` headers.

From what I understood `externalTrafficPolicy: Local` setting is crucial to make work proxy protocol on cloud balancers. At least with it I can see as source IP client one:
```
09:57:58.757689 IP (tos 0x0, ttl 50, id 707, offset 0, flags [none], proto TCP (6), length 40)
    <client_real_ip>.37031 >  <proxy_pod_ip>.3080: Flags [.], cksum 0x802c (correct), ack 2147434268, win 2048, length 0
09:57:58.757706 IP (tos 0x0, ttl 64, id 34493, offset 0, flags [DF], proto TCP (6), length 52)
    <proxy_pod_ip>.3080 > <client_real_ip>.37031: Flags [.], cksum 0xac3a (incorrect -> 0x4a40), ack 1, win 331, options [nop,nop,TS val 2654003873 ecr 2277571317], length 0
```
With `externalTrafficPolicy: Cluster` (by default) its internal IP LB address.

Am I doing something wrong?

**Comment by webvictim** [comment]
With a layer 4 LB, setting `externalTrafficPolicy: Local` _should_ be enough assuming you have a Kubernetes `LoadBalancer`, but you might also need to set `internalTrafficPolicy: Local` depending on implementation. You might also need to explicitly enable PROXY protocol at the load balancer level - there's some docs on TCP LBs with Google here: https://cloud.google.com/sdk/gcloud/reference/compute/target-tcp-proxies/create

If you're running Teleport 13.2.0 or higher and using a layer 7 LB, try setting this in your config and redeploying:

```yaml
proxy:
  teleportConfig:
    proxy_service:
      trust_x_forwarded_for: true
```

In either case, you can test if this is working on the Teleport side by checking the audit log - when you log into the Teleport web UI, do you see the correct client IP in that log under `addr.remote`?

![image](https://github.com/gravitational/teleport/assets/897821/2d0db314-e10c-4de1-8af3-38e0bec0e04d)

```json
{
  "addr.remote": "1.2.3.4:30268", # here
  "cluster_name": "test.teleportdemo.com",
  "code": "T1000I",
  "ei": 0,
  "event": "user.login",
  "method": "local",
  "mfa_device": {
    "mfa_device_name": "apollo",
    "mfa_device_type": "WebAuthn",
    "mfa_device_uuid": "0f8b031f-55c1-44f4-a60f-425fdef8d54e"
  },
  "success": true,
  "time": "2023-07-31T18:32:02.165Z",
  "uid": "698b787e-a4ee-453d-bc77-5b3d42dd8a78",
  "user": "gus",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}
```

Once you're seeing the correct client IP there, try logging into your application and the correct client IP should be forwarded. If not, let us know as it's likely a bug.

**Reply by roko99** [reply]
Hello @webvictim 
Thanks for response.
Yes, I can confirm, that I can see my real IP in audit log for event `App Session Started`:
```yaml
{
  "addr.remote": "<my-real-ip>:4608",
  "app_name": "http-https-echo",
  "app_public_addr": "http-https-echo.<domain>",
  "app_uri": "https://http-https-echo.<domain>",
  "cluster_name": "<domain>",
  "code": "T2007I",
  "ei": 0,
  "event": "app.session.start",
  "namespace": "default",
  "public_addr": "http-https-echo.<domain>",
  "server_id": "11f6b45b-3871-4662-bcef-2d75aa1b8b2a",
  "sid": "9ad5139f-77dc-4921-bad6-e2a0955daa26",
  "time": "2023-08-05T10:22:10.633Z",
  "uid": "5e1ef210-c7a8-4bf2-9894-f101fefb3263",
  "user": "admin"
}
```
I'm running teleport behind L4 balancer (btw without `externalTrafficPolicy: Local` in log I can see balancer IP). From this we can assume, that LB is configured properly.
Teleport app is targeting to simple [app](https://hub.docker.com/r/mendhak/http-https-echo) which displays all headers for incoming requests. Response is:
```json
{
  "path": "/",
  "headers": {
    "host": "http-https-echo.<domain>",
    "x-request-id": "55ac1542708127d89834291bdce7169d",
    "x-real-ip": "10.148.2.185",
    "x-forwarded-for": "10.148.2.185",
    "x-forwarded-host": "http-https-echo.<domain>",
    "x-forwarded-port": "443",
    "x-forwarded-proto": "https",
    "x-forwarded-scheme": "https",
    "x-scheme": "https",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0",
    "accept-language": "uk,en-US;q=0.7,en;q=0.3",
    "sec-fetch-mode": "navigate",
    "teleport-jwt-assertion": "<token>",
    "accept-encoding": "gzip, deflate, br",
    "x-forwarded-server": "teleport-app-agent-0",
    "sec-fetch-dest": "document",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "sec-fetch-site": "same-site",
    "x-forwarded-ssl": "on",
    "cf-access-token": "<token>"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "http-https-echo.<domain>",
  "ip": "10.148.2.185",
  "ips": [
    "10.148.2.185"
  ],
  "protocol": "https",
  "query": {},
  "subdomains": [
    "<subdomains>",
    "http-https-echo"
  ],
  "xhr": false,
  "os": {
    "hostname": "http-https-echo-757f47bc8f-nwtct"
  },
  "connection": {}
}
```
Agent IP:
```bash
> kubectl get pods -n teleport teleport-app-agent-0 -o jsonpath='{.status.podIP}'                                                                                                                                                                                 kube cnode2-k8s-dev
10.148.2.185
```
