### DISCUSSION TITLE
New Teleport Install With Grafana Not Working (Websocket Issue?)

### DISCUSSION THREAD

**Discussion by JosTheDude** [gravitational/teleport#29769] [Q&A] [answered]
Hey! We're running Teleport to protect our internal applications from external access, however, Grafana and Pterodactyl don't appear to work despite being setup.

You can go to the sites and access them via Teleport, but it appears anything involving a websocket doesn't function at all. For Grafana, we get an "Origin Not Found" error for all of logs and Pterodactyl seems to fail to connect to any server (you can login, however)

Tried to find answers online but couldn't find anything, how would I go about fixing this?

**Comment by webvictim** [comment, marked as answer]
Generally adding the `Host` and `Origin` headers and pointing them to the Teleport version of the app URL is enough for applications which are fussy about CORS. Try this:

```yaml
apps:
- name: grafana
  uri: http://localhost:3000
  rewrite:
    headers:
    - "Host: grafana.teleport.example.com"
    - "Origin: https://grafana.teleport.example.com"
```
