### DISCUSSION TITLE
How do I enable session recording for a web application?

### DISCUSSION THREAD

**Discussion by Soldier2003** [gravitational/teleport#29890] [Q&A] [answered]
I have a teleport server (13.1) installed and a webmin server separately.
With the configurations listed below, the connection is successful, but the question arises:
How do I enable session recording (playback) and configure the storage limit or auto-deletion of old records?
Is the setup identical to SSH or different? from the documentation, it is not even clear to me whether this functionality is supported.

teleport.yaml (from the teleport server):
```
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    #output: stderr
    output: /var/lib/teleport/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: "127.0.0.1:3000"
  # Teleport throttles all connections to avoid abuse. These settings allow
  # you to adjust the default limits
  connection_limits:
      max_connections: 1000
      max_users: 250
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.fortest.tech
  proxy_listener_mode: multiplex
  session_recording: "node"

ssh_service:
  enabled: "yes"
  
  # Enhanced Session Recording
  # see https://goteleport.com/docs/features/enhanced-session-recording/
  enhanced_recording:
  
   # Enable or disable enhanced auditing for this node. Default value: false.
   enabled: true

   # Optional: command_buffer_size is optional with a default value of 8 pages.
   command_buffer_size: 8

   # Optional: disk_buffer_size is optional with default value of 128 pages.
   disk_buffer_size: 128

   # Optional: network_buffer_size is optional with default value of 8 pages.
   network_buffer_size: 8

   # Optional: Controls where cgroupv2 hierarchy is mounted. Default value:
   # /cgroup2.
   cgroup_path: /cgroup2
  
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
    
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:5443
  public_addr: teleport.fortest.tech:5443
  https_keypairs:
  - key_file: /etc/letsencrypt/live/teleport.fortest.tech/privkey.pem
    cert_file: /etc/letsencrypt/live/teleport.fortest.tech/fullchain.pem
  #https_cert_file: /etc/letsencrypt/live/teleport.fortest.tech/fullchain.pem
  #https_key_file: /etc/letsencrypt/live/teleport.fortest.tech/privkey.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```

app_config.yaml (from the webmine server/webapp):
```
version: v3
teleport:
  nodename: teleport1
  data_dir: /home/user/.config
  join_params:
    #token_name: c4da923eadbfde33b44fcb872e5ea0ed
    token_name: f7372792ffeaf8e1b3c7da3fc5e5df1f
    method: token
  proxy_server: teleport.fortest.tech:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: webmine
    uri: https://localhost/
    #public_addr: "webmine.teleport.fortest.tech"
    public_addr: "teleport1.fortest.tech"
    insecure_skip_verify: true
```
