### DISCUSSION TITLE
How to run teleport behind a cloudflared tunnel

### DISCUSSION THREAD

**Discussion by ngaxavi** [gravitational/teleport#30001] [Q&A] [answered]
I have a teleport server (13.3) installed. With the configuration listed below, the connection is successful. I can access to the teleport site and login, through the domain that I have configured in cloudflared tunnel.  The problem is I cannot add a new server, add Kubernetes cluster or login through  `tsh` .  What is missing in my configuration to fix this problem?

teleport.yaml

```yaml
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: "sha256:545cc6a92373xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  advertise_ip: 192.168.0.10
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
  public_addr: teleport.example.com:3025
ssh_service:
  enabled: "yes"
  labels:
    cloud: homelab
    role: bastion
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  peer_listen_addr: 0.0.0.0:3021
  kube_listen_addr: 0.0.0.0:3026
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.example.com:443
  ssh_public_addr: teleport.example.com:3023
  https_keypairs: []
  https_keypairs_reload_interval: 0s

```

Cloudflared Tunnel Config
```
 https://192.168.0.10:3080 -> teleport.example.com (tls disable)
```
