### DISCUSSION TITLE
Teleport session recording for k8s

### DISCUSSION THREAD

**Discussion by murtuza-kolasavala** [gravitational/teleport#30031] [Q&A] [answered]
Hello Community,

I am recently onboard to teleport teams. I have setup few servers and k8s clusters. When i am logged into SSH server i am getting recordings under Management -> Session recording section but when i am accessing K8s cluster via tsh commands it is not recording anything. Although i am getting all the audit logs under "Audit Log" section. Same happens on DB access as well.

Is video recording session only applicable to SSH session? I tried digging more into this and found that in role -> options -> record_session you can add `kubernetes: true` but once i am saving the role it is resetting back to original.

Currently my access role looks like this. Let me know what i am missing.

```
options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      **desktop: true** 
```
