### DISCUSSION TITLE
User application service to proxy Openshift console

### DISCUSSION THREAD

**Discussion by Rolandcr** [gravitational/teleport#30320] [Q&A] [answered]
Is it possible to use Teleport Application service to access Openshift web console deployed in a private network. Any example? Thank you.

**Comment by webvictim** [comment, marked as answer]
Yes, this should work the same as any other application config.

```yaml
teleport:
  proxy_server: teleport.example.com:443 # replace with the host/port of your Teleport proxy
  join_params:
    method: token
    token_name: <token>  # replace with the output of `tctl tokens add --type=app --ttl=30m`
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: false
app_service:
  enabled: true
  debug_app: true
  apps:
  - name: openshift
    description: Openshift console
    uri: https://localhost:8080 # replace with local host/port of Openshift console
    insecure_skip_verify: false # set to true if Openshift itself does not have a valid HTTPS cert for the hostname Teleport is connecting to, "localhost" in this example
    labels:
      app: openshift
    rewrite:
      redirect:
        - localhost
      headers:
      - "Host: openshift.teleport.example.com" # replace teleport.example.com with the hostname of your Teleport proxy
      - "Origin: https://openshift.teleport.example.com" # replace teleport.example.com with the hostname of your Teleport proxy
```

You'll also need to:
- add a DNS A record for `openshift.teleport.example.com` pointing to the IP of your Teleport proxy
- get a valid TLS certificate with a SAN (subject alternative name) of `openshift.teleport.example.com`, either using:
  - Teleport's built-ACME (`proxy_service.acme.enabled: true` on your cluster)
  - providing the key/cert to the Teleport cluster (using the `proxy_service.https_keypairs` config value)
  - having a reverse proxy/load balancer in front of your Teleport cluster which has the valid certificate
- You can also use a wildcard certificate for `*.teleport.example.com` if you desire.
