### DISCUSSION TITLE
Running *.tele.example.com Behind Cloudflare Proxy

### DISCUSSION THREAD

**Discussion by JosTheDude** [gravitational/teleport#30441] [Q&A] [answered]
Hey! My project uses Cloudflare as our DNS and CDN management platform. I was wondering how we would go about making it such that *.tele.example.com could be proxied, as when we have it proxied, we receive this error when attempting to access one of our applications:

![image](https://github.com/gravitational/teleport/assets/43651265/9eb85d90-6971-409e-bf8a-7ac47ff0452b)

**Comment by webvictim** [comment]
~Try removing the `2` from your application name - change its name (and public address) to contain `grafana-two` instead.~

~There's currently a bug with application access which makes it behave oddly when there's a number in the name of the application. I think this could be the same problem.~

https://github.com/gravitational/teleport/issues/30160

**Comment by JosTheDude** [comment]
> Try removing the `2` from your application name - change its name (and public address) to contain `grafana-two` instead.
> 
> There's currently a bug with application access which makes it behave oddly when there's a number in the name of the application. I think this could be the same problem.
> 
> #30160

Same issue as before, for additional debug information, here's what happens when I visit the domain directly as it says
![image](https://github.com/gravitational/teleport/assets/43651265/fea1ed10-bbc5-4a2a-939a-09d31260a591)

(happened before when I had -2 as well)

**Reply by webvictim** [reply]
I suspect this is something speaking HTTP to an HTTPS backend or vice versa. Presumably it works if you disable Cloudflare proxying for the domain?

**Reply by JosTheDude** [reply]
Yup, it works fine if I do.

**Reply by JosTheDude** [reply]
I just tried to modify my Teleport config to use https, just got 504 errors; figured considering it's localhost. Here's my current config:

```
  - name: 'grafana-dev-two'
    uri: "http://localhost:3000/"
    public_addr: "grafana-dev-two.tele.(redacted)"
    insecure_skip_verify: true
    rewrite:
      headers:
        - "Host: grafana-dev-two.tele.(redacted)"
        - "Connection: Upgrade"
        - "Upgrade: websocket"
    labels:
      environment: dev
```

Had this as a page rule as well:

![image](https://github.com/gravitational/teleport/assets/43651265/f2fb3af8-cbd4-4351-b0fd-002663744eb5)

**Reply by webvictim** [reply]
I think the extra layer of proxying added by Cloudflare is just going to interfere too much here. I'll try and test things out a bit myself and see if I can get it working but I'm not super hopeful.

**Reply by webvictim** [reply, marked as answer]
So when I configure a subdomain of `teleport.<cloudflare-domain>` to be proxied (in this case the wildcard `*.teleport.<domain>`), I get this little warning triangle with an error:

![image](https://github.com/gravitational/teleport/assets/897821/974f510d-2b8b-4a55-b702-6b245413cba8)

Going into the details reveals this information:

![image](https://github.com/gravitational/teleport/assets/897821/6395e8ec-3601-4fac-b272-6b59d89ff1b8)

Essentially, Cloudlfare's free plan is only giving me a cert which covers `<domain>` and `*.<domain>` i.e. one level deep, so `teleport.<domain>` is fine but `app.teleport.<domain>` is not. The only way around this is to either use non-proxied DNS (so the traffic goes direct to the Origin, which can serve its own TLS certs), or pay Cloudflare $10/month for them to handle it for you.

In a browser, this manifests as the error you showed above. At the command line, it looks like this because `curl` is not being presented with a certificate for the domain:

```
gus@apollo:~ % curl -v https://grafana.teleport.<domain>
*   Trying 104.21.20.148:443...
* Connected to grafana.teleport.<domain> (104.21.20.148) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL/3.3.6: error:1404B410:SSL routines:ST_CONNECT:sslv3 alert handshake failure
* Closing connection 0
curl: (35) LibreSSL/3.3.6: error:1404B410:SSL routines:ST_CONNECT:sslv3 alert handshake failure
```

**Reply by webvictim** [reply]
To follow on from this, I also confirmed that if I change my app domain to something that _is_ covered by Cloudflare's free cert (i.e. `grafana.<domain>`, which is covered by the top-level wildcard `*.<domain>` which they give out for free), add a new proxied DNS record for that domain and then change my Teleport config to use that `public_addr`, it works fine with Cloudflare proxying.

```yaml
  apps:
  - name: grafana
    uri: http://localhost:3000
    public_addr: grafana.<domain>
    rewrite:
      redirect:
        - localhost
      headers:
        - "Origin: https://grafana.<domain>"
        - "Host: grafana.<domain>"
```

I did also get a certificate from Let's Encrypt for that domain (`certbot certonly -d grafana.<domain>`) and add it to Teleport's `proxy_service` config so that the backend connection from Cloudflare -> Teleport could also be properly secured. I don't know if this is 100% necessary.

```yaml
proxy_service:
  https_keypairs:
    - key_file: /etc/letsencrypt/live/teleport.<domain>/privkey.pem
      cert_file: /etc/letsencrypt/live/teleport.<domain>/fullchain.pem
    - key_file: /etc/letsencrypt/live/grafana.<domain>/privkey.pem
      cert_file: /etc/letsencrypt/live/grafana.<domain>/fullchain.pem
```
