### DISCUSSION TITLE
Issue with teleport access role for teams plan

### DISCUSSION THREAD

**Discussion by murtuza-kolasavala** [gravitational/teleport#30541] [Q&A] [answered]
I have been editing access role to provide user permission. This role was working for some time but all of sudden we started getting issue while logging into console.

<img width="565" alt="Screenshot 2023-08-16 at 1 09 21 PM" src="https://github.com/gravitational/teleport/assets/91605149/a60f6c85-8bf3-471e-8570-938f1f8efc18">

Not sure why access role required billing permission to see resources on console. 

Role assign to user is below.

```
kind: role
metadata:
  description: Access cluster resources
  id: 1692168815097902647
  labels:
    teleport.internal/resource-type: preset
  name: access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - '{{internal.aws_role_arns}}'
    azure_identities:
    - '{{internal.azure_identities}}'
    db_labels:
      '*': '*'
    db_names:
    - '*'
    db_roles:
    - '{{internal.db_roles}}'
    db_service_labels:
      '*': '*'
    db_users:
    - '*'
    gcp_service_accounts:
    - '{{internal.gcp_service_accounts}}'
    kubernetes_groups:
    - system:masters
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    kubernetes_users:
    - admin
    logins:
    - user1
    - user2
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - assistant
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - user1
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: true
    ssh_file_copy: true
version: v6

```

**Comment by webvictim** [comment, marked as answer]
I agree that it's odd that `billing` permission would be required for all users using the web UI. i will raise an issue for the Cloud team to look into this.

In the meantime, you can work around this error by adding this to your role:

```yaml
spec:
  allow:
    rules:
    - resources:
      - billing
      verbs:
      - list
      - read
```
