### DISCUSSION TITLE
Getting teleport and traefik to work on docker swarm

### DISCUSSION THREAD

**Discussion by Reventlow** [gravitational/teleport#30914] [Q&A]
I am having trouble getting my setup to work.

In this example I have replaces my.url.dk with my actual url. 

My certificates I am useing are valid and working in other web-apps I use in my swarm.

I am running traefik and teleport on my docker swarm. Without labels I can reach it internally through my ip and port 3080. But when adding traefik labels. I get an internal server error when  trying to access it through a browser.

The only error I can see in my teleport.log is the following:
```
Failed to delete auto-upgrade-enroll alert: cluster alert "auto-upgrade-enroll" not found auth/auth.go:1101
```

Searched the web to see what it means but found no reference.

# Traefik Setup
My traefik setup looks like this:

docker-compose.yml
```yml
version: '3.7'
services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.10.3
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    deploy:
      placement:
        constraints:
          - node.role==manager
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    networks:
      - public
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/robo/docker-volumes/traefik/traefik-yaml/traefik.yml:/etc/traefik/traefik.yml
      - /home/robo/docker-volumes/traefik/traefik-yaml/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
      - /home/robo/docker-volumes/cert:/etc/certs/
      - /home/robo/docker-volumes/traefik/logs:/var/log
networks:
  public:
    external: true

```

traefik.yml
```yml
################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true  
################################################################
# Docker configuration backend
################################################################
providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true
  docker:
    watch: true
    exposedByDefault: false
    swarmMode: true

################################################################
# Traefik Logging
################################################################
log:
  level: ERROR
  filePath: "/var/log/traefik.log"
  format: common

accessLog:
  filePath: "/var/log/access.log"
  bufferingSize: 100 
  filters:
    statusCodes:
      - "200-499"
  fields:
    defaultMode: keep
    names:
      ClientAddr: keep
      ClientHost: keep
      ClientPort: keep
      ClientUsername: keep
      DownstreamContentSize: keep
      DownstreamStatus: keep
      DownstreamStatusLine: keep
      Duration: keep
      OriginContentSize: keep
      OriginDuration: keep
      OriginStatus: keep
      OriginStatusLine: keep
      Overhead: keep
      RequestAddr: keep
      RequestMethod: keep
      RequestPath: keep
      RequestPort: keep
      RequestProtocol: keep
      RequestScheme: keep
      RetryAttempts: keep
      RouterName: keep
      ServiceAddr: keep
      ServiceName: keep
      ServiceURL: keep
      StartLocal: keep
      StartUTC: keep

################################################################
# Entrypoints
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"  
  websecure:
    address: ":443"
    http:
      tls: true
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"  

################################################################
# Middlewares
################################################################
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

################################################################
# TLS configuration
################################################################
tls:
  options:
    default:
      minVersion: VersionTLS12
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/privatekey.pem
        keyFile: /etc/certs/all_certificates.pem 

```

dynamic_conf.yml
```yml
################################################################
# certificates
################################################################
tls:
  options:
    default:
      minVersion: VersionTLS12
  certificates:
      - certFile: /etc/certs/all_certificates.pem
        keyFile: /etc/certs/privatekey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/all_certificates.pem
        keyFile: /etc/certs/privatekey.pem
```

# Teleport Setup

My teleport setup:

docker-compose.yml
```yml
version: '3.8'
services:      
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:13.3.5
    container_name: teleport
    volumes:
      - /home/robo/docker-volumes/teleport/config:/etc/teleport
      - /home/robo/docker-local/teleport/data:/var/lib/teleport
      - /home/robo/docker-volumes/cert/privatekey.pem:/etc/ssl/certs/privatekey.pem
      - /home/robo/docker-volumes/cert/all_certificates.pem:/etc/ssl/certs/all_certificates.pem
#    ports:
#      - '3080:3080'
#      - '3023:3023'
#      - '3024:3024'
#      - '3025:3025'
    deploy:
      placement:
        constraints:
          - node.hostname == my-vms-rpa-09
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.teleport.rule=HostRegexp(`my.url.dk`, `{subhost:[a-z]+}.my.url.dk`)"
        - "traefik.http.routers.teleport.entrypoints=websecure"
        - "traefik.http.routers.teleport.tls=true"
        - "traefik.http.services.teleport.loadbalancer.server.port=3080"
        - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
        - "traefik.http.services.teleport.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.teleport.tls.domains[0].main=my.url.dk"
        - "traefik.http.routers.teleport.tls.domains[0].sans=*.my.url.dk"
    networks:
      - public

networks:
  public:
    external: true
```

teleport.yaml
```yml
version: v3
teleport:
  nodename: teleport_swarm
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: my.url.dk
ssh_service:
  enabled: "no"
proxy_service:
  web_listen_addr: 0.0.0.0:3080
  public_addr: ['my.url.dk:443']
  enabled: "yes"
  https_keypairs: 
  - key_file: /etc/ssl/certs/privatekey.pem
    cert_file: /etc/ssl/certs/all_certificates.pem 
```
