### DISCUSSION TITLE
All nodes disappeared

### DISCUSSION THREAD

**Discussion by bpowerie** [gravitational/teleport#31072] [Q&A]
Hi All, 

I got a notification on my WebUI that there was a security issue and I needed to update the cluster. Also at the same time, all of my server connections disappeared from the UI. I updated the auth server successfully and i have logged into one of the nodes, I am seeing the following error:

Node failed to establish connection to cluster: Failed to connect to Proxy Server through tunnel: connection error: desc = "transport: Error while dialing: failed to dial: tls: first record does not look like a TLS handshake". pid:238353.1 service/connect.go:123

Anyone have any ideas here? I would rather not have to regenerate tokens on all of my servers again (I have had to do it once before) I have about 80 servers listed generally.

Any info appreciated.

**Comment by zmb3** [comment]
Your nodes are having trouble connecting to the cluster. The first thing to look at it is probably the `teleport.yaml` configuration file. Mind sharing that here? (please redact any sensitive information like join tokens)

**Comment by bpowerie** [comment]
Hi guys,

Thanks, even if I remove the teleport on a node and reinstall it is not communicating - Here is the yaml file

version: v3
teleport:
  nodename: ip-172-31-**-***
  data_dir: /var/lib/teleport
  join_params:
    token_name: MASKED
    method: token
  proxy_server: teleport.***************.ie:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:MASKED
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: e****2aa-****-****-****-c7ba*****c7b

  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}

**Reply by webvictim** [reply]
I would be inclined to suggest that there's something external at play here. Is your Teleport cluster behind a load balancer? Could any changes have been made to it or its configuration recently by anyone else?

If you could share the `/etc/teleport.yaml` file from your Teleport cluster machine itself it would also be useful - the one you shared here is from an agent service.

**Comment by bpowerie** [comment]
```yaml
version: v3
teleport:
  nodename: tele-s-2vcpu-2gb-fra1-01
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.**********.ie
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  labels:
    environment: live
    client: Matrix Teleport Server
    web: teleport.************.ie
    ip: 161.35.***.**
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.**************.ie:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: it@************.ie
app_service:
    enabled: yes
    apps:
    - name: "demo"
      uri: "http://localhost:9000"
      public_addr: "teleport.************.ie"
```

Here it is.
