### DISCUSSION TITLE
Multiplexer error after upgrade attempt

### DISCUSSION THREAD

**Discussion by rodlord5000** [gravitational/teleport#31130] [Q&A]
I attempted an upgrade of Teleport Enterprise v12.4.15 to 13.3.4 to match our Team cloud hosted proxy version. I can no longer connect to Desktops, I get a EOF message in the web GUI and the following error in the log:

WARN 
ERROR REPORT:
Original Error: *net.OpError read pipe: i/o timeout
Stack Trace: github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:608 github.com/gravitational/teleport/lib/multiplexer.detectProto
github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:411 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detect
github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:267 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward
runtime/asm_amd64.s:1598 runtime.goexit
User Message: failed to peek connection
read pipe: i/o timeout" loglimit/loglimit.go:159

Before I attempted the upgrade I made a snapshot which I reverted to but the error persists on v12.4.15. Anyone have any ideas? I found this https://github.com/gravitational/teleport/pull/30882 but I'm not sure it's related.

**Comment by webvictim** [comment]
`i/o timeout` generally means something isn't responding when it should, or traffic is going out and never coming back.

How is your Teleport cluster deployed? Do you have a load balancer or similar in front of it? Firewalls, security groups etc?

Also, can your share your Teleport config file? Are you running the `windows_desktop_service` on the same machine as your Teleport auth/proxy, or is it separate?

**Comment by rodlord5000** [comment]
No load balancer, there is a firewall in front of our local teleport setup but this was previously working with v12.

We are running Teleport Team, so our auth/proxy is hosted at xxx.teleport.sh and we run the windows_desktop_service on a local machine here to provide access to domain joined machines.

Config:
```
version: v3
teleport:
  log:
    severity: DEBUG
  auth_token: <redacted>
  proxy_server: <redacted>.teleport.sh:443
windows_desktop_service:
  enabled: yes
  show_desktop_wallpaper: false
  ldap:
  <redacted>
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: no
```
