### DISCUSSION TITLE
Applications are not routed via the agent?

### DISCUSSION THREAD

**Discussion by jryberg** [gravitational/teleport#31404] [Q&A] [answered]
Hi,

I'm playing with a web application that was added to an agent

This is the agent config that are connecting to the server, the app was registered and are now in the list
```
teleport:
  nodename: some-name
  data_dir: /var/lib/teleport
  auth_token: some-token
  auth_servers:
    - some.server:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: no
  session_recording: "node"
ssh_service:
  enabled: yes
  commands:
  - name: hostname
    command: ["hostname"]
    period: 1h0m0s
proxy_service:
  enabled: no
app_service:
  enabled: yes
  apps:
  - name: "web1"
    uri: "https://web1.intranet.somedomain:2000"
    insecure_skip_verify: true
```

When I visit the Application tab and click on web1 the URL are redirecting to https://web1.intranet.somedomain:2000 in by browser. 

I was under the impression that all traffic was routed from the proxy server to the client. I cannot access https://web1.intranet.somedomain:2000 directly.

Am I missing something? 

Thanks, Johan
