### DISCUSSION TITLE
Can Machine ID onboard with GCP join method?

### DISCUSSION THREAD

**Discussion by james-ryans** [gravitational/teleport#31553] [Q&A] [answered]
I might have been confused with the current docs say that Machine ID currently only support onboard with ephemeral token & IAM join method. But I've found some issues saying (implicitly) that it's possible to onboard Machine ID using GCP join method.
Reference:
- https://github.com/gravitational/teleport/issues/28636#issuecomment-1620295997, said "This is a customer issue where they wanted to use GCP joining for tbot running as pod in GKE."
- https://github.com/gravitational/teleport/pull/29563, looks like it can be done in v13.
- https://github.com/gravitational/teleport/issues/30453, seems the issue was there is no clear documetation on this method instead of not supported.

If it's currently supported, can someone guide me to setup this?
I've tried to create token with `spec.roles: [Bot]` and `spec.join_method: gcp` following this guide https://goteleport.com/docs/agents/join-services-to-your-cluster/gcp/ but returns `ERROR: unknown join method "gcp"` instead.
And I wanted to use gcp `onboarding.join_method` on tbot config but I don't know what to fill in the token field.

**Comment by zmb3** [comment, marked as answer]
Yes, in v13 and up Machine ID can use GCP join. It was implemented in #28663

**Reply by james-ryans** [reply]
Oops, sorry. It is! I must've mixed the teleport version with my previous setup experiment.

**Comment by james-ryans** [comment]
Hi, sorry for reopen this discussion. I'm using Teleport Team Edition and I've been stuck on this error for a while. I'm trying to onboard Machine ID via GCP join method from GKE pod, I've setup the Workload Identity to GKE Node and fixed all the client-side errors (e.g. doesn't support default compute service account and I've changed the GKE Node SA to new service account, added required permissions to the service account, etc). I've checked this issue too https://github.com/gravitational/teleport/issues/28636 and ran `curl -s "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=teleport.cluster.local&format=full&licenses=FALSE" --header "Metadata-Flavor: Google"` inside the corresponding pod returned JWT with payloads below
```
{
  "aud": "teleport.cluster.local",
  "azp": "105899212996409768233",
  "email": "gke-node@[PROJECT_ID].iam.gserviceaccount.com",
  "email_verified": true,
  "exp": 1694515546,
  "iat": 1694511946,
  "iss": "https://accounts.google.com",
  "sub": "105899212996409768233"
}
```

I've created a token
```
# token.yaml
kind: token
version: v2
metadata:
  # the token name is not a secret because instances must prove that they are
  # running in your GCP project to use this token
  name: metabase
spec:
  # use the minimal set of roles required (e.g. Node, Proxy, App, Kube, DB, WindowsDesktop)
  roles: [Bot]
  bot_name: bot-metabase

  # set the join method allowed for this token
  join_method: gcp

  gcp:
    allow:
      # The GCP project ID(s) that VMs can join from.
      - project_ids: ["[PROJECT_ID]"]
        # (Optional) The locations that VMs can join from. Note: both regions and
        # zones are accepted.
        # locations: ["[LOCATION]"]
        # (Optional) The email addresses of service accounts that VMs can join
        # with.
        service_accounts: ["gke-node@[PROJECT_ID].iam.gserviceaccount.com"]
```
with config below
```
    auth_server: <trial-tenant>.teleport.sh:443
    onboarding:
      join_method: gcp
      token: metabase
      ca_pins:
      - sha256:xxxx
    storage:
      directory: /var/lib/teleport/bot
    destinations:
      - directory: /opt/machine-id
        database:
          service: cloudsql
          username: teleport@[PROJECT_ID].iam
          database: metabase
```

The error on proxy and auth server:
```
DEBU [TBOT]      Unable to load from current key "key-cert.pub", trying to migrate from old key "sshcert" identity/identity.go:456
DEBU [TBOT]      Identity directory /var/lib/teleport/bot is not found or empty and could not be loaded, will start from scratch: artifact "key-cert.pub" is unexpectedly empty in destination directory /var/lib/teleport/bot tbot/tbot.go:396
INFO [TBOT]      Anonymous telemetry is not enabled. Find out more about Machine ID's anonymous telemetry at https://goteleport.com/docs/machine-id/reference/telemetry/ tbot/anonymous_telemetry.go:83
INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:479
DEBU [AUTH]      Registering node to the cluster. auth-servers:[{<trial-tenant>.teleport.sh:443 tcp }] auth/register.go:264
DEBU [AUTH]      The first specified auth server appears to be a proxy. auth/register.go:270
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:277
DEBU [CLIENT]    HTTPS client init(proxyAddr=<trial-tenant>.teleport.sh:443, insecure=false, extraHeaders=map[]) client/weblogin.go:331
DEBU [CLIENT]    Attempting https://<trial-tenant>.teleport.sh:443/v1/webapi/host/credentials client/https_client.go:86
DEBU [AUTH]      Registration via proxy server failed. error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError access denied
Stack Trace:

Caught:
	github.com/gravitational/teleport/lib/httplib/httplib.go:206 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	github.com/gravitational/teleport/lib/client/https_client.go:91 github.com/gravitational/teleport/lib/client.(*WebClient).PostJSONWithFallback
	github.com/gravitational/teleport/lib/client/weblogin.go:650 github.com/gravitational/teleport/lib/client.HostCredentials
	github.com/gravitational/teleport/lib/auth/register.go:333 github.com/gravitational/teleport/lib/auth.registerThroughProxy
	github.com/gravitational/teleport/lib/auth/register.go:278 github.com/gravitational/teleport/lib/auth.Register
	github.com/gravitational/teleport/lib/tbot/renew.go:509 github.com/gravitational/teleport/lib/tbot.(*Bot).getIdentityFromToken
	github.com/gravitational/teleport/lib/tbot/tbot.go:409 github.com/gravitational/teleport/lib/tbot.(*Bot).initialize
	github.com/gravitational/teleport/lib/tbot/tbot.go:234 github.com/gravitational/teleport/lib/tbot.(*Bot).Run
	github.com/gravitational/teleport/tool/tbot/main.go:288 main.onStart
	github.com/gravitational/teleport/tool/tbot/main.go:171 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:50 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: access denied
] auth/register.go:281
INFO [AUTH]      Attempting registration with auth server. auth/register.go:277
DEBU [AUTH]      Registration with auth server failed. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: authentication handshake failed: read tcp x.x.x.x:38086-&gt;x.x.x.x:443: read: connection reset by peer&#34;
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/client.go:3486 github.com/gravitational/teleport/api/client.(*Client).GetClusterCACert
	github.com/gravitational/teleport/lib/auth/register.go:562 github.com/gravitational/teleport/lib/auth.pinRegisterClient
	github.com/gravitational/teleport/lib/auth/register.go:374 github.com/gravitational/teleport/lib/auth.registerThroughAuth
	github.com/gravitational/teleport/lib/auth/register.go:278 github.com/gravitational/teleport/lib/auth.Register
	github.com/gravitational/teleport/lib/tbot/renew.go:509 github.com/gravitational/teleport/lib/tbot.(*Bot).getIdentityFromToken
	github.com/gravitational/teleport/lib/tbot/tbot.go:409 github.com/gravitational/teleport/lib/tbot.(*Bot).initialize
	github.com/gravitational/teleport/lib/tbot/tbot.go:234 github.com/gravitational/teleport/lib/tbot.(*Bot).Run
	github.com/gravitational/teleport/tool/tbot/main.go:288 main.onStart
	github.com/gravitational/teleport/tool/tbot/main.go:171 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:50 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: connection error: desc = &#34;transport: authentication handshake failed: read tcp x.x.x.x:38086-&gt;x.x.x.x:443: read: connection reset by peer&#34;] auth/register.go:281

ERROR REPORT:
Original Error: trace.aggregate access denied, connection error: desc = &#34;transport: authentication handshake failed: read tcp x.x.x.x:38086-&gt;x.x.x.x:443: read: connection reset by peer&#34;
Stack Trace:
	github.com/gravitational/teleport/lib/auth/register.go:287 github.com/gravitational/teleport/lib/auth.Register
	github.com/gravitational/teleport/lib/tbot/renew.go:509 github.com/gravitational/teleport/lib/tbot.(*Bot).getIdentityFromToken
	github.com/gravitational/teleport/lib/tbot/tbot.go:409 github.com/gravitational/teleport/lib/tbot.(*Bot).initialize
	github.com/gravitational/teleport/lib/tbot/tbot.go:234 github.com/gravitational/teleport/lib/tbot.(*Bot).Run
	github.com/gravitational/teleport/tool/tbot/main.go:288 main.onStart
	github.com/gravitational/teleport/tool/tbot/main.go:171 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:50 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: access denied, connection error: desc = &#34;transport: authentication handshake failed: read tcp x.x.x.x:38086-&gt;x.x.x.x:443: read: connection reset by peer&#34;
```
