### DISCUSSION TITLE
Teleport SSO integration with Oracle IDCS

### DISCUSSION THREAD

**Discussion by philip-teleport** [gravitational/teleport#31628] [Show and tell]
In the IDCS Admin Console, from either the "Dashboard" or the "Applications" section, select the option to add an application:

![image](https://github.com/gravitational/teleport/assets/95687564/db3b5d90-d08b-48ce-a14a-d2e302449b18)

Select the "SAML Application" option:

![image](https://github.com/gravitational/teleport/assets/95687564/e5a59b8a-e0ed-4267-a18f-b33db1f45695)

Add the name "Teleport", upload the Teleport icon and then click the "Next' button:

![image](https://github.com/gravitational/teleport/assets/95687564/d5ece29a-9e2c-405f-ae9e-aa0e10dcd2c9)

Set the "Entity ID" and "Assertion Consumer URL" fields to point to Teleport, e.g. `https://example.teleportdemo.com:443/v1/webapi/saml/acs/idcs`:

![image](https://github.com/gravitational/teleport/assets/95687564/9ca6908a-c030-4695-be22-4f49eeff58c5)

Note that the integration is configured as an IdP-initiated login with the connector name at the end of the ACS URL, e.g. /idcs

Click the "Download Identity Provider Metadata" button to save the SAML Metadata XML file provided.

In the "Attribute Configuration" section, add user attributes to send group membership details as part of the assertion.

Click the "Finish" button.

Log into Teleport and create a new SAML connector as shown and insert the SAML Metadata XML contents from IDCS as the `entity_descriptor`:

```
kind: saml
metadata:
  name: idcs
spec:
  acs: https://example.teleportdemo.com:443/v1/webapi/saml/acs/idcs
  allow_idp_initiated: true
  attributes_to_roles:
  - name: groups
    roles:
    - access
    value: teleport
  audience: https://example.teleportdemo.com:443/v1/webapi/saml/acs/idcs
  cert: ""
  display: Oracle IDCS
  entity_descriptor: |
    <md:EntityDescriptor xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" 
```

Note that the IDCS integration is configured as an IdP-initiated login with the connector name at the end of the `acs` and `audience` URLs, e.g. /idcs.

The `allow_idp_initiated` attribute must also be set to "true".

From the CLI, use `tctl` to export the signing key to a file: `tctl saml export idcs > idcs.pem`

Return to the IDCS Admin Console and upload the Signing Certificate file that you have just created:

![image](https://github.com/gravitational/teleport/assets/95687564/15268d95-5c10-4d64-aca0-018857b4d86d)

The same Auth Connector can be used to log into Teleport from the IDCS console and from the Teleport log in page.

![image](https://github.com/gravitational/teleport/assets/95687564/e47e6458-3191-49b8-8572-d9f5e2aa8693)
