### DISCUSSION TITLE
Database service cannot validate database's certificate

### DISCUSSION THREAD

**Discussion by scott-jameson-eval** [gravitational/teleport#31806] [Q&A]
Hi,

I am running Teleport 13.3.7
I setup the db service on an EC2 which has access to the DB.
Teleport is able to discover the database just fine but I cannot connect to it. Tried using Teleport Connect app and local terminal.

What certificates does it need?

`ERROR 1105 (HY000): Database service cannot validate database's certificate: tls: failed to verify certificate: x509: certificate signed by unknown authority. Please verify if the correct CA bundle is used in the database config.`

**Comment by webvictim** [comment]
Teleport needs to be provided with the public key for the CA that generated the certificate which the database itself is presenting so it can validate it. If you're using an RDS database this is handled automatically, but it looks like you're using a self-hosted MySQL database here?

Take a look at your `[mysqld]` config in your config file (`/etc/my.cnf` by default) - it should look something like this:

```ini
[mysqld]
ssl_ca=/var/lib/mysql/ca.pem
ssl_cert=/var/lib/mysql/server-cert.pem
ssl_key= /var/lib/mysql/server-key.pem
```

`/var/lib/mysql/ca.pem` is the file you want to use. You need to provide it to Teleport like this:

```yaml
db_service:
  databases:
  - name: mysql
    uri: "mysql-server.hostname.com:3306"
    tls:
      mode: verify-full
      # if your certificate is valid for a hostname other than
      # mysql-server.hostname.com, you can set that hostname here
      server_name: mysql-production.hostname.com
      # put the full path to the ca.pem file here
      ca_cert_file: /var/lib/mysql/ca.pem
```

Restart the Teleport `db_service` and it should work.
