### DISCUSSION TITLE
Access the Kubernetes Dashboard using Teleport Application Access

### DISCUSSION THREAD

**Discussion by philip-teleport** [gravitational/teleport#31811] [Show and tell]
How to deploy the Kubernetes Dashboard and Teleport Kube Agent using Helm, exposing the dashboard using Teleport Application Access.

Reference:

- [https://github.com/kubernetes/dashboard](https://github.com/kubernetes/dashboard)
- [https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard)
- [https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/)
- [https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md)

## Steps

- Deploy Kubernetes Dashboard using Helm:

```
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
helm upgrade --install kubernetes-dashboard \
  kubernetes-dashboard/kubernetes-dashboard --create-namespace \
  --namespace kubernetes-dashboard
```

- Retrieve the "ClusterIP" for the deployed dashboard:

```
export CLUSTER_IP=$(kubectl -n kubernetes-dashboard get svc kubernetes-dashboard \
  -o jsonpath="{.spec.clusterIP}"); echo CLUSTER_IP=$CLUSTER_IP
```

- Create a Kubernetes Service Account that has permission to access the dashboard and a secret containing a long-lived Bearer Token for the ServiceAccount:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-admin-account
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-admin-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dashboard-admin-account
  namespace: kubernetes-dashboard
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-token
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: "dashboard-admin-account"   
type: kubernetes.io/service-account-token  
EOF
```

- Deploy the Teleport agent: 

```
echo CLUSTER_IP=$CLUSTER_IP

export TELEPORT_JOIN_TOKEN=$(tctl tokens add --type=kube,app \
  | grep "invite token:" | grep -Eo "[0-9a-z]{32}")
export TELEPORT_NAMESPACE=teleport-agent
export PROXY_ENDPOINT=example.teleport.com:443
export KUBERNETES_CLUSTER_NAME=example-k8s-dev

echo "
authToken: ${TELEPORT_JOIN_TOKEN?}
joinParams:
  method: token
  tokenName: ${TELEPORT_JOIN_TOKEN?}
proxyAddr: ${PROXY_ENDPOINT?} 
kubeClusterName: ${KUBERNETES_CLUSTER_NAME?}
labels:
  env: dev
  provider: eks
roles: "kube,app"
apps:
- name: kube-dashboard
  uri: https://${CLUSTER_IP?}
  insecure_skip_verify: true 
  labels:
    env: dev
" > values.yaml

helm install teleport-kube-agent teleport/teleport-kube-agent \
  --create-namespace --namespace ${TELEPORT_NAMESPACE?} \
  -f values.yaml
```

- Retrieve the dashboard token from the Secret that was created:

```
kubectl get secret dashboard-token -n kubernetes-dashboard \
  -o jsonpath={".data.token"} | base64 -d
```

- Log into the Teleport web user interface, go to Applications, click on the Kubernetes Dashboard. When the Dashboard opens, paste the token from step above into the "Enter token" field and click "Sign in":

![image](https://github.com/gravitational/teleport/assets/95687564/1da15ce3-739d-4b3e-aed9-bce35747a7ab)
