### DISCUSSION TITLE
Enable DB service to connect to GCP CloudSQL via private IPs.

### DISCUSSION THREAD

**Discussion by kmmanto** [gravitational/teleport#31867] [Q&A]
Scenario:

- Teleport deployed in GKE in Project A
- NLB is infront to workaround this issue: https://github.com/gravitational/teleport/issues/31202
- CloudNAT for Internet access
- CloudSQL is in Project B
- Project A and B vpcs have peering between them

How do we connect to the CloudSQL instance in Project B via the private IP instead of the public one.

I would only like to grant the VPC IP of Project A in the allow list of the CloudSQL instance instead of the NAT IP.

**Comment by webvictim** [comment]
You can tell Teleport to connect to a CloudSQL database using whatever address you like:

```yaml
db_service:
  enabled: true
  databases:
  - name: "cloudsql"
    # description
    description: "GCP Cloud SQL MySQL"
    # database protocol
    protocol: "mysql"
    # private IP goes here
    # test connectivity from the Teleport instance with nc -vz 10.1.2.3 3306
    uri: "10.1.2.3:3306"
    # Path to Cloud SQL instance root certificate you downloaded above.
    ca_cert_file: /path/to/cloudsql/instance/root.pem
    # GCP-specific configuration when connecting a Cloud SQL instance.
    gcp:
      # GCP project ID.
      project_id: "<project-id>"
      # Cloud SQL instance ID.
      instance_id: "test"
    # Labels to assign to the database, used in RBAC.
    static_labels:
      env: gcp
```
