### DISCUSSION TITLE
Role Mapping on Trusted Cluster

### DISCUSSION THREAD

**Discussion by sanchezzjf** [gravitational/teleport#33026] [Q&A] [answered]
Can I map more than one remote role to map a local role?

For example: 
I have one role that permit access to IT resources and other that permit access to HR resources, can I map them to different local roles?

Like
```yaml
role_map:
  - remote: "it-access"
    local: "it-access"
  - remote: "hr-access"
    local: "hr-access"
```

**Comment by webvictim** [comment]
Yes, you can have as many role mappings as you like.

**Reply by sanchezzjf** [reply]
How the yaml would look like? I tried the example that I gave but not worked

**Reply by webvictim** [reply, marked as answer]
```yaml
role_map:
- local:
  - it-access
  remote: it-access
- local:
  - hr-access
  remote: hr-access
```
