### DISCUSSION TITLE
Filtering accesible tokens for a role

### DISCUSSION THREAD

**Discussion by schferbe** [gravitational/teleport#33139] [Q&A] [answered]
I am on 13.4 Open Source Version and would like to create a role that can manage tokens for Gitlab CI. I tried the following role:

```yaml
kind: role
metadata:
  name: gitlab_ci_editor
spec:
  allow:
    rules:
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
      where: token.spec.join_method == "gitlab"
version: v5

```

When I log in as a user with the `gitlab_ci_editor` role I get the following output:
```
$ tctl get tokens
ERROR: token.spec.join_method is not defined, token.spec.join_method is not defined
```

Now I found out that this message means that already `token` is not defined. I was able to guess that `resource.metadata` exists but have not found a way to access the `spec`. 

I have looked at https://goteleport.com/docs/access-controls/reference/#teleport-resources and https://goteleport.com/docs/reference/predicate-language/ but cannot find the information I need. Can you give me some pointers?
