### DISCUSSION TITLE
Internal server error when trying to access application

### DISCUSSION THREAD

**Discussion by sanchezzjf** [gravitational/teleport#33155] [Q&A]
Hello, I'm getting a black screen saying "Internal Server Error" when I try to access our Dell EMC Storage web interface.

This are the errors generated in the logs:

```bash
out 09 17:18:17 teleport-app teleport[38601]: 2023-10-09T17:18:17Z ERRO [APP:SERVI] Error forwarding to https://storage.comp.com/, err: EOF reverseproxy/reverse_proxy.go:231
out 09 17:18:17 teleport-app teleport[38601]: 2023-10-09T17:18:17Z INFO [APP:WEB]   Round trip: GET /, code: 500, duration: 2.458275928s tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:storage.tele.com reverseproxy/reverse_proxy.go:236
out 09 17:18:19 teleport-app teleport[38601]: 2023-10-09T17:18:19Z ERRO [APP:SERVI] Error forwarding to https://storage.comp.com/favicon.ico, err: EOF reverseproxy/reverse_proxy.go:231
out 09 17:18:19 teleport-app teleport[38601]: 2023-10-09T17:18:19Z INFO [APP:WEB]   Round trip: GET /favicon.ico, code: 500, duration: 2.210199645s tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:storage.tele.com reverseproxy/reverse_proxy.go:236
```

It is https access with no certificate configured(the insecure_skip_verify is enabled)

Have no idea what to do.

Tried the rewrite redirect and setting some headers, but none worked out.

**Comment by webvictim** [comment]
Can you share a little more information about how your Teleport `auth_service`, `proxy_service` and `app_service` are configured? What does the machine/network layout look like?

**Comment by sanchezzjf** [comment]
Here are the configurations:

**Auth Service:**
```yaml
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: tp.ex.com
  proxy_listener_mode: multiplex
```

**Proxy Service:""
```yaml
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: tp.ex.com:443
  https_keypairs:
    - key_file: /var/lib/teleport/tp.ex.com.key
      cert_file: /var/lib/teleport/tp.ex.com.crt
    - key_file: /var/lib/teleport/STAR.tp.ex.com_key.pem
      cert_file: /var/lib/teleport/STAR.tp.ex.com.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```
**App Service:**
```yaml
app_service:
  enabled: "yes"
  apps:
    - name: storage-a
      uri: "https://a.storage.ex.com"
      insecure_skip_verify: true
```

They are comunicating on L3

**Reply by webvictim** [reply]
~~Your issue is that your app's public address is `a.storage.ex.com` but your Teleport server only has certs for `tp.ex.com` and `*.tp.ex.com`~~

~~You would need to give your proxy service an additional key pair for `a.storage.ex.com` or `*.storage.ex.com`~~

Apologies, misread the config.

**Reply by sanchezzjf** [reply]
But we hame some esxi and dell iDRACs configured that way and we had no problem to access them.
```yaml
app_service:
  enabled: "yes"
  apps:
    - name: idrac-host01
      uri: "https://idrac.host01.ex.com"
      insecure_skip_verify: true
    - name: esxi-01-01
      uri: "https://host01.01.ex.com"
      insecure_skip_verify: true
```
