### DISCUSSION TITLE
Is an enterprise license required for github SSO if I want to use it with Kubernetes?

### DISCUSSION THREAD

**Discussion by computerphilosopher** [gravitational/teleport#33627] [Q&A] [answered]
When I run `kubectl exec -i deployment/teleport-cluster-auth -- tctl create -f < github.yaml` command. it says `ERROR: this feature requires Teleport Enterprise`

Following is my github.yaml 

```yaml
kind: github
metadata:
  name: github
spec:
  api_endpoint_url: https://api.github.com
  client_id: xxxxxxxxxxxxx
  client_secret: xxxxxxxxx
  display: ""
  endpoint_url: https://github.com
  redirect_url: https://my-teleport.com:443/v1/webapi/github/callback
  teams_to_logins: null
  teams_to_roles:
  - organization: my-org
    roles:
    - access
    - editor
    team: my-team
version: v3
```

I understand that GitHub SSO is included in the open-source edition. Is an enterprise license required if I want to use it with Kubernetes?

**Comment by xom4ek** [comment, marked as answer]
No EE license is required for using GitHub SSO; it is not needed for Kubernetes access via Teleport.

```
kind: github
metadata:
  name: AmazeIt
spec:
  api_endpoint_url: ""
  client_id: ******
  client_secret: ""
  display: Github
  endpoint_url: ""
  redirect_url: https://teleport.exmaple.com/v1/webapi/github/callback
  teams_to_logins: null
  teams_to_roles:
  - organization: MYORG
    roles:
    - admins
    team: admins
version: v3
```

As i see u try set `endpoint_url` and this one usage for `github EE` - that paid feature for teleport
