### DISCUSSION TITLE
Teleport behind HAProxy - HAProxy IP on each connected node

### DISCUSSION THREAD

**Discussion by sammah0** [gravitational/teleport#33785] [Q&A] [answered]
I'm slowly trying to get my environment into a more highly available model. I have our backend migrated to postgresql which went well and now I'm trying to duplicate our current 1 server setup to a 2 server setup to insert and HAProxy inbetween. So far the only issue I'm seeing in our test environment is with HAProxy config for the Auth and Proxy (each on both servers) shows the Server IPs as the load balancer's IP and thus unable to connect. I was wondering if anyone has come across that before. I'll include the HAProxy config and a sample of the running config for both teleport.yaml files. I replaced the IPs of the running test machines.

```
frontend tpauth
  bind 3.3.3.3:3025
  mode tcp
  default_backend tp-servers-auth

frontend tpproxy
  bind 3.3.3.3:443
  mode tcp
  default_backend tp-servers-proxy

backend tp-servers-auth
  mode tcp
  server auth-1 1.1.1.1
  server auth-2 2.2.2.2

backend tp-servers-proxy
  balance roundrobin
  mode tcp
  server auth-1 1.1.1.1
  server auth-2 2.2.2.2
``` 

teleport.yaml sample for auth/proxy
```
teleport:
  nodename: tptest1.company.com
  advertise_ip: 108.61.157.87
  diag_addr: 0.0.0.0:3000
  auth_servers: [ "tptest1.company.com:3025" ]

proxy_service:
  # enable the proxy service
  enabled: true
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  public_addr: tptest1.company.com:443
  ssh_public_addr: tptest1.company.com
  tunnel_listen_addr: 0.0.0.0:3024
  https_keypairs:
    - key_file: "/var/lib/teleport/privkey.pem"
      cert_file: "/var/lib/teleport/fullchain.pem"
  acme:
    enabled: "no"

auth_service:
  # enable the auth service:
  license_file: "/var/lib/teleport/license.pem"
  enabled: true
  cluster_name: "tptest1.company.com"
```

Thank you!

edit: clarified some information

**Comment by webvictim** [comment]
There's a couple of things that stand out to me:
- You should add the port to this in your proxy config: `ssh_public_addr: tptest1.company.com:3023`
- If `advertise_ip` isn't working for setting the address of the SSH service, you could try overriding the SSH public address directly on each server:
```yaml
ssh_service:
  enabled: true
  public_addr: 108.61.157.87:3022 # change to the server's public IP
```

The other thing you might want to look into with HAProxy (not sure if this is relevant or you've investigated it yet) is the use of a [VIP](https://en.wikipedia.org/wiki/Virtual_IP_address) which is configured on both servers: https://serverfault.com/a/1110566
