### DISCUSSION TITLE
I get selfsigned certificate from webapi instead of the purchased one

### DISCUSSION THREAD

**Discussion by KOTOXJle6** [gravitational/teleport#34110] [Q&A] [answered]
Hello everyone!
Im trying to install  teleport community edition, stuck on adding hosts.
First of all, here is my teleport.yaml:
```
version: v3
teleport:
  nodename: dpc-teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport_cluster
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.mydomain.com:443
  https_keypairs:
  - key_file: /etc/teleport/ssl/ca.key
    cert_file: /etc/teleport/ssl/ca.pem
  https_keypairs_reload_interval: 0s
```
ca.pem - my purchased Globalsing wildcard certificate with name *.mydomain.com. I got all chain in file.

Everything starting fine and i can access teleport via web and see that it using cert from config file, but when im trying to donwload certificate with
`curl -o teleport.cer --insecure https://teleport.mydomain.com/webapi/auth/export?type=windows
`
i got selfsigned certificate with issuer name teleport.mydomain.com, issued for teleport.mydomain.com.

Is that normal behavior and i should install selfsinged cert to trusted certificates on each machine i want to add? Or i missed something and curl should return my purchased one?
