### DISCUSSION TITLE
Need Help Getting Started

### DISCUSSION THREAD

**Discussion by rubydotexe** [gravitational/teleport#34224] [Q&A]
I've got noobish questions but I've been trying to get Teleport to run on my personal server for a long time! 

Here's my current config on Debian 12:

```
version: v3
teleport:
  nodename: node
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.com:443
```

Typing the IP address of my sever, 192.168.40.40 gives me the web UI. However, the domain teleport.example.com does not. My actual domain is hosted on Cloudflare, so typing the domain takes me to Cloudflare with a host not found error. 

I have Pi-Hole and I have the domain set to my server as well. I want ssl and naturally I want to be able to use my domain, it doesn't seem right that I would have to type my local IP. 

The getting started page on teleport documentation says I should be able to see the Web UI via the domain I selected as well, so I'm not sure what I'm doing wrong. Does it have something to do with multiplex? I don't even know anymore man. Am I supposed to be using a reverse proxy like Caddy, then?

**Comment by rubydotexe** [comment]
UPDATE: Okay, so port forwarding 443 allowed me to connect to teleport.example.com. However, now the problem is SSL. When I update my config as such:

```
version: v3
teleport:
  nodename: node
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.com:443
  https_keypairs:
    - key_file: /var/lib/teleport/webproxy_key.pem
      cert_file: /var/lib/teleport/webproxy_cert.pem
    - key_file: /etc/letsencrypt/live/*.teleport.example.com/privkey.pem
      cert_file: /etc/letsencrypt/live/*.teleport.example.com/fullchain.pem
```

It no longer works and I'm back to seeing the Cloudflare page.
