### DISCUSSION TITLE
pass github team / or mapped role / or mapped kubernetes_groups as header into teleport app

### DISCUSSION THREAD

**Discussion by dmitry-mightydevops** [gravitational/teleport#34345] [General]
I have github sso connector.
would like to pass the list of teams the user is a member of into the app using header.
- or list of granted teleport roles
- or list of mapped kubernetes groups based on roles.

I tried the options below and see no header `X-Auth-Groups*` in the wireshark. I see however `X-Auth-User` in the headers dump.

```yaml
 apps:
   - name: karma
     description: 'Internal alertmanager karma GUI'
     uri: http://karma.prometheus.svc.cluster.local
     rewrite:
       headers:
         - 'Host: karma.teleport.domain.net'
         - 'Origin: https://karma.teleport.domain.net'
         - 'X-Auth-User: {{external.logins}}'
         - 'X-Auth-Groups5: {{internal.kubernetes_groups}}'
         - 'X-Auth-Groups: Groups: {{external.teams}}'
         - 'X-Auth-Groups1: Groups: {{internal.groups}}'
         - 'X-Auth-Groups2: Groups: {{internal.roles}}'
         - 'X-Auth-Groups3: Groups: {{external.roles}}'
         - 'X-Auth-Groups4: Groups: {{external.organization}}'
     labels:
       environment: prod
       devops: 'true'
```

is there a way to do it?
