### DISCUSSION TITLE
Internal server error when Launch a specific web application

### DISCUSSION THREAD

**Discussion by bediverus** [gravitational/teleport#34587] [Q&A] [answered]
Hello,
When I try to connect to the web application I get a black screen with "Internal server error"
Unfortunately, I did not follow up after which configuration changes the problem occurred. But after setting up the services, I set up roles, logging, cache and something else.
Teleport logs provide very little information.
The problem is similar to #33155 , but I don't have gzip, and the service worked before.
Please share your thoughts.

Teleport cluster (auth- and proxy- services) version: `Teleport v14.1.1 git:api/v14.1.1-0-gfb6429e go1.21.3`
Teleport agent version: `Teleport v13.3.8 git:api/v13.3.8-0-gc95e235e88 go1.20.7`

Logs:
```
2023-11-14T17:45:10Z ERRO             Error forwarding to /, err: EOF forward/fwd.go:176
2023-11-14T17:45:11Z ERRO             Error forwarding to /favicon.ico, err: EOF forward/fwd.go:176
```
Why is it redirected to the root `forwarding to /`, shouldn't it be `forwarding to APPS_URI`?

Teleport cluster config:
```yaml
auth_service:
  enabled: "yes"
  listen_addr: 127.0.0.1:3025
  cluster_name: "mycluster.domain.co"
  proxy_listener_mode: multiplex
  authentication:
    type: github
    second_factor: otp
    webauthn:
      rp_id: mycluster.domain.co

proxy_service:
  enabled: "yes"
  web_listen_addr: 127.0.0.1:3080
  public_addr: mycluster.domain.co:443
  https_cert_file: /etc/letsencrypt/live/mycluster.domain.co/fullchain.pem
  https_key_file: /etc/letsencrypt/live/mycluster.domain.co/privkey.pem
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```
Teleport agent config:
```yaml
app_service:
  enabled: "yes"
  debug_app: true
  apps:
  - name: no-cameras
    uri: http://192.168.10.10
    insecure_skip_verify: false
```
curl from the teleport agent server
```
# curl -kv http://192.168.10.10
* Expire in 0 ms for 6 (transfer 0xf398b0)
*   Trying 192.168.10.10...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0xf398b0)
* Connected to 192.168.10.10 (192.168.10.10) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.10.10
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 15 Nov 2023 00:05:11 GMT
< Server: DNVRS-Webs
< ETag: "0-a72-1e0"
< Content-Length: 480
< Content-Type: text/html
< Connection: keep-alive
< Keep-Alive: timeout=60, max=99
< Last-Modified: Fri, 18 Aug 2017 09:50:21 GMT
< 
<!doctype html>
<html>
<head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" >
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Cache-Control" content="no-cache, must-revalidate" />
        <meta http-equiv="Expires" content="0" />
</head>
<body>
</body>
<script>
        window.location.href = "/doc/page/login.asp?_" + (new Date()).getTime();
</script>
* Connection #0 to host 192.168.10.10 left intact
```
I tried enabling `insecure_skip_verify: true` and adding rewrite headers.

Additional Information
- If it matters - teleport cluster runs behind nginx
- teleport cluster and teleport agent are installed locally (without docker/k8s/etc)
- there are other applications on the agent, and there are no problems with them:
```yaml
  - name: no-grafana
    uri: http://localhost:3000
    public_addr: ""
    insecure_skip_verify: false
    rewrite:
      headers:
      - "Host: no-grafana.mycluster.domain.co"
      - "Origin: https://no-grafana.mycluster.domain.co"
  - name: no-unifi
    uri: https://192.168.10.20:8443
    insecure_skip_verify: true
```

**Comment by webvictim** [comment]
You won't need `insecure_skip_verify` when connecting to an HTTP application.

Try using this app config instead (with the port added to the URI, and no `insecure_skip_verify`):

```yaml
apps:
- name: no-cameras
  uri: http://192.168.10.10:80
```

Restart the Teleport `app_service` afterwards.
