### DISCUSSION TITLE
Assign multiple IP's to web_listen_addr

### DISCUSSION THREAD

**Discussion by marcel-st** [gravitational/teleport#34745] [Q&A] [answered]
Hi all,

i'm trying to assign one IPv4 and one IPv6 IP to the web_listen_addr parameter so that i can use the other IP's for my other web applications that are also using port 443. I've tried the following:

```
proxy_service:
  enabled: "yes"
  web_listen_addr:
    - <my_pub_IPv4>:443
    - [<my_pub_IPv6>]:443
```

but this fails with error:

_teleport ERROR: failed parsing the config file: yaml: line 27 did not find expected '-' indicator_

and i've tried:

```
proxy_service:
  enabled: "yes"
  web_listen_addr:
      <my_pub_IPv4>:443
      [<my_pub_IPv6>]:443
```

This fails with error:

_teleport ERROR: failed to parse "tcp://<IPv4>:443 [<IPv6>]:443": parse "tcp://<IPv4>:443 [<IPv6>]:443": invalid character " " in host name_

I've also googled the options, but i can't find any solution. What is the proper way to set this up?
