### DISCUSSION TITLE
Internal Server Error when trying to launch a application on k8s

### DISCUSSION THREAD

**Discussion by rasouza** [gravitational/teleport#34743] [Q&A]
I've deployed both `teleport-cluster` and `teleport-kube-agent` using Helm charts (v14.1.15) in my local k8s cluster. It's using TLS Routing with L7 Load balancer behind a NGINX Ingress Controller. 

WebUI works fine, also implemented Github login which works fine too, so it seems I have a basic setup working properly. I followed [Get Started with Kubernetes Application Discovery](https://goteleport.com/docs/application-access/enroll-kubernetes-applications/get-started/) guide in order to enable auto discovery and I get the following apps in my dashboard:

![image](https://github.com/gravitational/teleport/assets/337906/ef12b94c-1580-4f8a-aada-9a36868a257f)

When I try to launch _any_ of the apps, I get `Internal Server Error` as response. This is the log I found in `teleport-proxy`
```
2023-11-18T13:10:37Z INFO [APP:WEB]   Round trip: GET /, code: 500, duration: 53.852051ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server: reverseproxy/reverse_proxy.go:236
2023-11-18T13:10:37Z INFO [APP:WEB]   Round trip: GET /favicon.ico, code: 500, duration: 7.12415ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server: reverseproxy/reverse_proxy.go:236
```

This is the log in `teleport-agent`
```
2023-11-18T12:56:58Z ERRO [APP:SERVI] Error forwarding to https://argocd-server.argocd.svc.cluster.local:443/, err: dial tcp: lookup argocd-server.argocd.svc.cluster.local: no such host reverseproxy/reverse_proxy.go:231
2023-11-18T12:56:58Z ERRO [APP:SERVI] Error forwarding to https://argocd-server.argocd.svc.cluster.local:443/favicon.ico, err: dial tcp: lookup argocd-server.argocd.svc.cluster.local: no such host reverseproxy/reverse_proxy.go:231
```

It seems `teleport-agent` is not getting the default DNS config from k8s. I also had to hardcode the `hostAliases` in order for the agent to connect to the cluster (as you can see below)

This is the Helm values I deployed `teleport-cluster` with
```
        clusterName: bastion.rasouza.dev
        acme: false
        acmeEmail: ''

        proxy:
          highAvailability:
            replicaCount: 1

        highAvailability:
          replicaCount: 1                                 # Number of replicas to configure
          certManager:
            enabled: true                                 # Enable cert-manager support to get TLS certificates
            issuerName: letsencrypt-prod            # Name of the cert-manager Issuer to use (as configured above)
            issuerKind: ClusterIssuer

        proxyListenerMode: multiplex 
        proxyProtocol: off                    # Number of replicas to configure
        service:
          type: ClusterIP
        ingress:
          enabled: true

        annotations:
          ingress:
            external-dns.alpha.kubernetes.io/hostname: ''
            external-dns.alpha.kubernetes.io/ttl: '120'
            nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
            nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
            nginx.ingress.kubernetes.io/ssl-redirect: 'true'

        podSecurityPolicy:
          enabled: false

        authentication:
          type: github
          connectorName: github_connector
          localAuth: false
          secondFactor: webauthn

        log:
          level: DEBUG
```

This is the Helm values I deployed `teleport-agent` with
```
        kubeClusterName: k8s-staging
        roles: "kube,app,discovery"
        proxyAddr: bastion.rasouza.dev:443
        authToken: 7d3f5cb5a668dce6d10dc74e06d38317 # Retrieve from Terraform first
        podSecurityPolicy:
          enabled: false
        log:
          level: DEBUG
        hostAliases:
          - ip: "10.96.39.114"
            hostnames:
              - "bastion.rasouza.dev"
        dnsPolicy: Default
        dnsConfig:
          nameservers:
            - 10.96.0.10
          searches:
            - teleport-agent.svc.cluster.local 
            - svc.cluster.local 
            - cluster.local
          options:
            - name: ndots
              value: "2"
```
I've already tried deploying `teleport-agent` with different combinations of `dnsPolicy`, `dnsConfig` and `hostAliases` (also without them all)

Can you spot the misconfiguration?
