### DISCUSSION TITLE
404 page not found - installing traefik behind teleport (docker)

### DISCUSSION THREAD

**Discussion by flayy73** [gravitational/teleport#36058] [Q&A] [answered]
Hello, I'm struggeling with this implemantation on my homeserver.

I have installed on a fresh docker proxmox linux container :
bind9
traefik
teleport

Now, the DNS server works. 
Traefik on local ip address:8080 (dasboard is active) , and works.
Problem:
webui of teleport on http or https respond with "404 page not found".

TLS certificaates is pulled and stored under ./config/certrs/acme.json - and is valid

## traefik setup:

docker-compose.yaml

```Dockerfile
networks:
  Esterna:
    external: true
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=MY-CLOUDFLARE-TOKEN
    # -- (Optional) When using a custom network
    networks:
      - Esterna
    restart: unless-stopped
```

traefik.yaml

```YAML
global:

  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change Log Level and Format here...
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
log:
  level: ERROR
#   format: common
#   filePath: /var/log/traefik/traefik.log
# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
# accesslog:
#   format: common
#   filePath: /var/log/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # -- (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  # -- (Optional) Add custom Entrypoint
  # custom:
  #   address: :8080

# -- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: my-email
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      #-- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  production:
    acme:
      email: my-email
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      #-- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# -- (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12
providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
```

## teleport setup:

docker-compose.yaml

```Dockerfile
networks:
  Esterna:
    external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:14.2.5-dev.marco.2
    container_name: teleport1
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    # -- (Optional) Traefik example configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
      - "traefik.http.routers.teleport-http.entrypoints=web"
      - "traefik.http.routers.teleport-http.rule=HostRegexp(`teleport1.dns.mydomain.com`, `{subhost:[a-z]+}.teleport1.dns.mydomain.com`)"
      - "traefik.http.routers.teleport-https.entrypoints=websecure"
      - "traefik.http.routers.teleport-https.rule=HostRegexp(`teleport1.dns.mydomain.com`, `{subhost:[a-z]+}.teleport1.dns.mydomain.com`)"
      - "traefik.http.routers.teleport-https.tls=true"
      - "traefik.http.routers.teleport-https.tls.certresolver=production"
      - "traefik.http.routers.teleport-https.tls.domains[0].main=teleport1.dns.mydomain.com"
      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.teleport1.dns.mydomain.com"
    networks:
      - Esterna
    restart: unless-stopped
```

teleport.yaml

```YAML
version: v2
teleport:
  nodename: teleport1
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: teleport1.dns.mydomain.com
  # -- (Optional) Passwordless Authentication
  # authentication:
  #   type: local
  #   second_factor: on
  #   webauthn:
  #     rp_id: your-server-url
  #   connector_name: passwordless
  # -- (Optional) Teleport Assist
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

ssh_service:
  enabled: "no"

proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  # -- (Optional) when using reverse proxy
  public_addr: ['teleport1.dns.mydomain.com:443']
  https_keypairs: []
  acme: {}
  # --(Optional) ACME
  # acme:
  #   enabled: "yes"
  #   email: your-email-address
  # -- (Optional) Teleport Assist
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

app_service:
  enabled: no
  # -- (Optional) App Service
  # enabled: yes
  # apps:
  #   - name: "yourapp"
  #     uri: "http://your-app-url"
  #     insecure_skip_verify: false
```

Thank you !.
and marry Christmas :)
