### DISCUSSION TITLE
Role to access multiple labels

### DISCUSSION THREAD

**Discussion by CyberPingU** [gravitational/teleport#36694] [Q&A] [answered]
Hello,
let's say I have an IaaS server with
```
labels:
  owner: group1
  servertype: dns
```
another IaaS server with:
```
labels:
  owner: group2
  servertype: logger
```
and last IaaS server:
```
labels:
  teleport.internal/resource-id: 113d9c4f-c030-4b82-89b3-4aad7be3d746
 ```

**Is there a way to create a myrole.yaml that puts me in a OR state? Something like "show me everything that satisfies AT LEAST ONE condition: belongs to group1, belongs to group2, is dns, is logger, is teleport.internal/serouce-id:xxxxxx) ?**

**Comment by webvictim** [comment, marked as answer]
The answer is yes, but not in one role. All conditions in a Teleport role are a boolean AND i.e. you must satisfy all of them for the role to be granted.

You can achieve what you want with two separate roles which will match on any of the entries in a list:

```yaml
kind: role
metadata:
  name: allowed-owners
spec:
  allow:
    logins:
    - allowed-user
    node_labels:
      owner:
      - group1
      - group2
```

```yaml
kind: role
metadata:
  name: allowed-servertypes
spec:
  allow:
    logins:
    - allowed-user
    node_labels:
      servertype:
      - dns
      - logger
```
