### DISCUSSION TITLE
Duplicate recordings

### DISCUSSION THREAD

**Discussion by dgiorgio** [gravitational/teleport#36809] [Q&A]
When I connect, two recordings appear.
![image](https://github.com/gravitational/teleport/assets/17960988/9a6e2919-6ff7-4a1c-86d7-04e2ceb63846)
Why does it appear duplicated?

```
---

auth_service:
    enabled: 'yes'
    listen_addr: 0.0.0.0:3025
    proxy_checks_host_keys: false
    proxy_listener_mode: multiplex
    public_addr: example.com:3025
    session_recording: proxy
proxy_service:
    acme: {}
    enabled: 'yes'
    https_keypairs:
    -   cert_file: /etc/certificates/fullchain.pem
        key_file: /etc/certificates/privkey.pem
    https_keypairs_reload_interval: 1h
    listen_addr: 0.0.0.0:3023
    public_addr: example.com:3080
    ssh_public_addr: example.com:3023
    tunnel_listen_addr: 0.0.0.0:3024
    tunnel_public_addr: example.com:3024
    web_listen_addr: 0.0.0.0:3080
ssh_service:
    commands:
    -   command:
        - hostname
        name: hostname
        period: 1m0s
    enabled: 'yes'
    listen_addr: 0.0.0.0:3022
    public_addr: example.com:3022
teleport:
    ca_pin: []
    data_dir: /var/lib/teleport
    diag_addr: ''
    log:
        format:
            output: text
        output: stderr
        severity: INFO
    nodename: example.com
version: v3

```
