### DISCUSSION TITLE
Multiplexing and reverse tunnel

### DISCUSSION THREAD

**Discussion by evrynet1** [gravitational/teleport#37286] [Q&A] [answered]
Teleport version: 14.3.3

I have just enabled multiplexing and when adding new SSH nodes (resources) reverse tunnels are being used which is much slower than the usual connection. How can I switch back to normal connections?

P.S.: still would like to use the advantages of multiplexing, the legacy listeners are just there for backward compatibility

<img width="401" alt="eu onecdn org â¢ New session 2024-01-25 at 9 20 37 PM" src="https://github.com/gravitational/teleport/assets/8157986/f0a7c215-64db-41d2-b485-3229c2d65d84">

<img width="511" alt="Screenshot 2024-01-25 at 21 40 19" src="https://github.com/gravitational/teleport/assets/8157986/646749e5-baf4-468b-98a2-7c648780809a">

teleport.yaml:

version: v3
teleport:
  nodename: 198-74-48-226.ip.linodeusercontent.com
  data_dir: /var/lib/teleport
  join_params:
    token_name: 
    method: token
  proxy_server: gw.domain.com:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: 
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: 
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
Thank you

Thank you

**Comment by evrynet1** [comment]
If I change this to auth_server with the following client teleport.yaml it shows the following after connecting:

Jan 25 21:16:50 localhost teleport: 2024-01-25T21:16:50Z INFO [NODE:1]    Connected to cluster over tunnel connection, ignoring public_addr setting. pid:1261.1 service/service.go:2555

teleport:
  nodename: 198-74-48-226.ip.linodeusercontent.com
  auth_token: 
  ca_pin:
  - 
  auth_servers:
  - gw.domain.com:443
ssh_service:
      enabled: yes
      public_addr: 127.0.0.1
      commands:
      - name: uptime
        command: [uptime]
        period: 30m0s
      labels:
        client: "Test"

**Comment by zmb3** [comment]
You are joining via the proxy server's reverse tunnel because you are specifying `proxy_server` in your agent config:

```
version: v3
teleport:
  proxy_server: proxy.example.com:443
```

If you want to dial agents directly instead of via reverse tunnel, you should configure your agents to connect to the auth server, not the proxy server.

```
version: v3
teleport:
  auth_server: auth.example.com:3025
```

As a side note, you included a join token in your message above, which is considered a secret and should not be shared. I'd recommend rotating it now that it's been exposed.

**Reply by evrynet1** [reply]
See my previous response please. I have also tried it with auth_server as well. I thought the idey behind multiplexing is that the connections are wrapped in TLS and multiplexed on one service port. The auth server is specified with 443 port in the agent config but it is still tunneling the connection.

[root@test ~]# curl https://gw.domain.com/webapi/ping | jq '.proxy'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   778  100   778    0     0   1208      0 --:--:-- --:--:-- --:--:--  1208
{
  "kube": {
    "enabled": true,
    "listen_addr": "0.0.0.0:443"
  },
  "ssh": {
    "listen_addr": "0.0.0.0:443",
    "tunnel_listen_addr": "0.0.0.0:443",
    "web_listen_addr": "0.0.0.0:443",
    "public_addr": "gw.domain.com:443"
  },
  "db": {
    "postgres_listen_addr": "0.0.0.0:443",
    "mysql_listen_addr": "0.0.0.0:443"
  },
  "tls_routing_enabled": true,
  "assist_enabled": false
}
[root@bq ~]#


Jan 25 21:16:50 localhost teleport: 2024-01-25T21:16:50Z INFO [NODE:1] Connected to cluster over tunnel connection, ignoring public_addr setting. pid:1261.1 service/service.go:2555

teleport:
nodename: 198-74-48-226.ip.linodeusercontent.com
auth_token:
ca_pin:

auth_servers:

gw.domain.com:443
ssh_service:
enabled: yes
public_addr: 127.0.0.1
commands:
name: uptime
command: [uptime]
period: 30m0s
labels:
client: "Test"

**Reply by zmb3** [reply]
Take a closer look at my answer. 

- You tried it with auth_servers,  not auth_server. 
- You still specified a proxy address on port 443, not an auth server address on port 3025. 

Multiplexing is a feature of the proxy. All traffic on the proxy server is multiplexed on a single port. If you want direct dial, agents must connect to auth, not proxy, and auth doesn't listen on port 443.

**Reply by evrynet1** [reply]
ah I see so it is still not possible to put both auth and proxy behind like CF right? which only supports 443/80 ports? is it possible to get auth listen on port 443 as well?

**Reply by zmb3** [reply, marked as answer]
It's possible, but you'd need a separate load balancer for auth. Both auth and proxy can't listen on the same port on the same host.

**Reply by evrynet1** [reply]
how about same host, different IPs?

**Reply by webvictim** [reply]
Give it a try!

**Reply by evrynet1** [reply]
Can you double check my configs please?

```
[root@eu ~]# netstat -ntpln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:1167            0.0.0.0:*               LISTEN      25000/cdp           
tcp        0      0 192.168.1.2:443       0.0.0.0:*               LISTEN      20271/teleport      
tcp        0      0 192.168.1.3:443      0.0.0.0:*               LISTEN      20271/teleport      
tcp6       0      0 :::3022                 :::*                    LISTEN      20271/teleport      
[root@eu ~]# 
```

```yaml
version: v2
teleport:
  nodename: eu.domain.com
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  proxy_listener_mode: multiplex
  listen_addr: 192.168.1.3:443
  cluster_name: eu.domain.com
  client_idle_timeout: 15m
  keep_alive_interval: 5s
  keep_alive_count_max: 3
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: gw.domain.com
ssh_service:
  enabled: "yes"
  labels:
    env: private
  commands:
  - name: uptime
    command: [uptime]
    period: 30m0s
proxy_service:
  enabled: "yes"
  tunnel_listen_addr: 192.168.1.2:443
  web_listen_addr: 192.168.1.2:443
  public_addr: ["gw.domain.com:443","domain.com:443","eu.domain.com:443"]
  https_keypairs:
    - key_file: /etc/letsencrypt/live/domain.com/privkey.pem
      cert_file: /etc/letsencrypt/live/domain.com/fullchain.pem
  acme:
    enabled: "no"
    email: test@test.com
```

Client side:

```yaml
version: v3
teleport:
  nodename: test.test.com
  auth_token: <redacted>
  ca_pin:
  - 
  auth_server: da.domain.com:443
ssh_service:
      enabled: yes
      public_addr: 127.0.0.1
      commands:
      - name: uptime
        command: [uptime]
        period: 30m0s
      labels:
        client: "name Name"
```

Is that supposed to be correct? da.domain.com is pointed to 192.168.1.3

**Reply by webvictim** [reply]
I fixed the formatting of your configs for you. In future you can use three backticks (```) to define code blocks so they're readable.

The configs look fine. Setting `tunnel_listen_addr` on the `proxy_service` is likely doing nothing and could be removed.

**Reply by evrynet1** [reply]
Thank you. Unfortunately no luck. This is how it looks now:

```
[root@eu ~]# netstat -ntpln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:1167            0.0.0.0:*               LISTEN      25000/cdp           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      28645/sshd          
tcp        0      0 192.168.1.2:443       0.0.0.0:*               LISTEN      29180/teleport      
tcp        0      0 192.168.1.3:443      0.0.0.0:*               LISTEN      29180/teleport      
tcp6       0      0 :::3022                 :::*                    LISTEN      29180/teleport      
tcp6       0      0 :::22                   :::*                    LISTEN      28645/sshd          
[root@eu ~]# 
```

Agent config:

```
version: v3
teleport:
  nodename: cp2.domain.com
  auth_token:
  ca_pin:
  - 
  auth_server: gw.domain.com:443
ssh_service:
```


Snippet from agent log:

```
Jan 31 06:27:42 cp2.nodecom teleport[21552]: 2024-01-31T06:27:42+11:00 INFO             Starting Teleport v14.1.3 with a config file located at "/etc/teleport.yaml" common/teleport.go:586
Jan 31 06:27:42 cp2.node.com teleport[21552]: 2024-01-31T06:27:42+11:00 WARN             config: auth_server is pointing to port 443, is this the proxy server address? service...onfig.go:688
Jan 31 06:27:42 cp2.node.com teleport[21552]: 2024-01-31T06:27:42+11:00 INFO [PROC:1]    Connecting to the cluster eu.domain.com with TLS client certificate. pid:21552.1 servi...nnect.go:209
Jan 31 06:27:42 cp2.node.com teleport[21552]: 2024-01-31T06:27:42+11:00 INFO [PROC:1]    Connecting to the cluster eu.domain.com with TLS client certificate. pid:21552.1 servi...nnect.go:209
Jan 31 06:27:43 cp2.node.com teleport[21552]: 2024-01-31T06:27:43+11:00 ERRO [PROC:1]    Instance failed to establish connection to cluster: connection error: desc = "transport: authentic...
Jan 31 06:27:43 cp2.node.com teleport[21552]: 2024-01-31T06:27:43+11:00 ERRO [PROC:1]    Check to see if the config has auth_server pointing to a Teleport Proxy. If it does, u...nnect.go:110
Hint: Some lines were ellipsized, use -l to show in full.

```

gw.domain.com is pointing to 192.168.1.2 but I also tried it with 192.168.1.3 with the same results:

snippet from teleport conf:

```
auth_service:
  enabled: "yes"
  proxy_listener_mode: multiplex
  listen_addr: 192.168.1.3:443

proxy_service:
  enabled: "yes"
  web_listen_addr: 192.168.1.2:443
```


Both are behind CF. Any idea?

**Reply by webvictim** [reply]
You'll need to share the full, non-truncated logs. `journalctl -u teleport --no-pager`

I wouldn't actually expect a connection to the auth server's port 3025 (which is a GRPC endpoint) to work behind any kind of proxy which does traffic filtering or inspection here like Cloudflare.

**Reply by evrynet1** [reply]
right so you don't believe that this would work out even if auth server is on 433 due to filtering? In that case probably we will skip it for now.

**Reply by webvictim** [reply]
Correct!

**Comment by evrynet1** [comment]
@greedy52 could you see this thread please? I found an older one here where websockets and ALPN routing were tested against well-known proxies like CloudFlare and as I understand this should be compatible now as per 36343? Could you advise here please?

https://github.com/gravitational/teleport/pull/36343

Both proxy and auth are on the same node behind CF (without tunnel).

**Reply by greedy52** [reply]
Hi @evrynet1. Thanks for tagging me.

I haven't tested myself but I think the regular CloudFlare proxy should work as long as WebSocket is enabled, once the above change (https://github.com/gravitational/teleport/pull/36343) is released. I did hear that CloudFlare wasn't working before this change though.

As for the auth servers, it will only be accessed by the proxy service through the local network. All other agents/clients should connect to the publicly advertised Proxy server address. So for `auth_service` on the same node, I believe you can just leave the` listen_addr: 0.0.0.0:3025`, or the same IP the `proxy_service` listens.

**Reply by evrynet1** [reply]
@greedy52 thank you for replying here so quickly. I have just keep testing this and with/without cloudflare tunnel I was also able to get the SSH nodes connected to the proxy service via reverse tunnel through Cloudflare just fine but due to latency I would get rid of reverse tunnels and get them connected directly...should that be possible as well?

<img width="401" alt="299797349-f0a7c215-64db-41d2-b485-3229c2d65d84" src="https://github.com/gravitational/teleport/assets/8157986/b48952c5-ebd4-402a-8a7e-53b5c8e7a1f1">

**Reply by greedy52** [reply]
https://goteleport.com/docs/architecture/nodes/#connecting-to-nodes

Are the SSH nodes in the same network as Proxy and Auth? If so, connect your SSH service to Auth instead of Proxy. E.g:
```yaml
version: v3
teleport:
  nodename: my-ssh-node
  auth_server: <auth-address>:3025
```

An alternative (again requires SSH nodes in the same network), is to use the env var `TELEPORT_TUNNEL_PUBLIC_ADDR` (on the SSH nodes) to specify a local Proxy domain/address for the SSH nodes to connect to:

https://github.com/gravitational/teleport/blob/26d657d51e42c984c689e20ff3203217a20ef5d8/api/client/webclient/webclient.go#L464-L473

This way avoids going through CloudFlare. Note that SSH nodes must connect reverse tunnels to all Proxy servers if you have multiple.

Let me know if that helps
