### DISCUSSION TITLE
Creating join tokens on the website (Team)

### DISCUSSION THREAD

**Discussion by maca134** [gravitational/teleport#37664] [Q&A] [answered]
How do I create join tokens on the website?
I have used the auto deploy script for an ssh service but want to add apps to the node.

This is the error I get when trying to add portainer to the config:
`App failed to establish connection to cluster: node "docker" [...] can not join the cluster, the token does not allow "App" role.`

Config:
```
app_service:
  enabled: yes
  apps:
    - name: "portainer"
      uri: "https://localhost:9443"
      insecure_skip_verify: false
```
