### DISCUSSION TITLE
Teleport with PostgreSQL

### DISCUSSION THREAD

**Discussion by evrynet1** [gravitational/teleport#37701] [Q&A] [answered]
Sorry guys for keep bugging you, you are utmost help so far.  I'm trying to configure PostgreSQL backend for Teleport  and later a cluster for HA here I'm using Steven guide:

https://github.com/gravitational/teleport/discussions/30247

except that for testing purposes I'm using user/pass auth and the db name is also set there ("postgre")

```
The PostgreSQL is an off-site managed database and I adjusted the teleport.yaml as follows:

version: v3
teleport:
  storage:
    type: postgresql

    # conn_string is a libpq-compatible connection string (see
    # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING);
    # pool_max_conns is an additional parameter that determines the maximum
    # number of connections in the connection pool used for the cluster state
    # database (the change feed uses an additional connection), defaulting to
    # a value that depends on the number of available CPUs.
    #
    # If your certificates are not stored at the default ~/.postgresql
    # location, you will need to specify them with the sslcert, sslkey, and
    # sslrootcert parameters.
    conn_string: postgresql://username:password@domain.com/db-name?teleport_backend?sslmode=verify-full&pool_max_conns=20
    audit_events_uri:
      - postgresql://username:password@domain.com/db-name?teleport_audit?sslmode=verify-full
    audit_sessions_uri: file://var/lib/teleport/log/records
  nodename: ny.domain.com
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: ny.domain.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: ny.domain.com:443
  https_keypairs:
    - key_file: /etc/letsencrypt/live/ny.domain.com/privkey.pem
      cert_file: /etc/letsencrypt/live/ny.domain.com/fullchain.pem
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "no"
    email: est@domain.com
```

Unfortunately Teleport is not listening on auth ports or any ports thereafter although it starts without error:

```
Feb  3 19:45:13 ny systemd[1]: teleport.service: Succeeded.
Feb  3 19:45:13 ny systemd[1]: Stopped Teleport Service.
Feb  3 19:45:13 ny systemd[1]: Started Teleport Service.
Feb  3 19:45:14 ny teleport[58478]: 2024-02-03T19:45:14Z INFO             Starting Teleport v15.0.0 with a config file located at "/etc/teleport.yaml" common/teleport.go:636
Feb  3 19:45:14 ny teleport[58478]: 2024-02-03T19:45:14Z INFO [PGBK]      Setting up backend. pgbk/pgbk.go:193
I have 2 further questions after following https://goteleport.com/docs/reference/backends/:

```

1. What do I do wrong here?
2. Is there any guide for setting up the second node of a self-hosted Postgre cluster?
3. How do I import the data from an existing cluster to PostgreSQL? Is PostgreSQL compatible with tctl get export?

Thank you so much,
Andrew
