### DISCUSSION TITLE
Proxy Version Endpoint configuration

### DISCUSSION THREAD

**Discussion by programmerq** [gravitational/teleport#38034] [Show and tell]
Instead of using the upstream `updates.releases.teleport.dev` endpoint or hosting your own, you can configure the Teleport Proxy to host version endpoint channels. This was added in https://github.com/gravitational/teleport/pull/36220. At the time of writing, Teleport 14.3.4 15.0.1 are the current versions of Teleport, and they support this feature.

To configure automatic upgrade channels, modifications must be made to the proxy_service section of the Teleport configuration file (teleport.yaml). The configuration allows specifying multiple channels, each with its own version and criticality settings.

This Discussion will follow the structure of https://goteleport.com/docs/upgrading/self-hosted-automatic-agent-updates/ but share specific information about any deviations.

### Step 1/5 - Configure Teleport Proxy to serve channels

This step replaces [Step 1/5. Create release channel files](https://goteleport.com/docs/upgrading/self-hosted-automatic-agent-updates/#step-15-create-release-channel-files) in the upstream document.

Edit your Teleport Proxy teleport.yaml file. In the `proxy_service` section, define your release channels. You can define more than one channel if desired.

```yaml
proxy_service:
  automatic_upgrades_channels:
    default:
      static_version: v14.3.4
      critical: true
```

Restart your proxies.

Test the channel by navigating to the `default` version endpoint for your channel:

```bash
% curl https://<proxy_url>/v1/webapi/automaticupgrades/channel/default/version
v14.3.4
% curl https://<proxy_url>/v1/webapi/automaticupgrades/channel/default/critical
no
```

You can define multiple channels. Defining a `default` channel will be required in the future, so it is shown here. The original guide shows a channel name called `current`. Other valid names include `stable/v14`, `stable/v15`, etc.

### Step 2/5.

Skip the upstream [Step 2/5. Create a Terraform configuration](https://goteleport.com/docs/upgrading/self-hosted-automatic-agent-updates/#step-25-create-a-terraform-configuration) step, as it is unnecessary when using an in-proxy version endpoint.

### Step 3/5. Configure the maintenance schedule

Follow the upstream guide [Step 3/5. Configure the maintenance schedule](https://goteleport.com/docs/upgrading/self-hosted-automatic-agent-updates/#step-35-configure-the-maintenance-schedule). No changes are needed!

### Step 4/5. Enroll Kubernetes agents in automatic upgrades

Follow the upstream [Step 4/5. Enroll Kubernetes agents in automatic upgrades](https://goteleport.com/docs/upgrading/self-hosted-automatic-agent-updates/#step-45-enroll-kubernetes-agents-in-automatic-upgrades)

* `versionServer:` value will be `https://<proxy_url>/v1/webapi/automaticupgrades/channel`
* `releaseChannel:` value will correspond to the channel name you picked in Step 1/5. `default` is the value in this example guide.

### Step 5/5. Enroll Linux agents in automatic upgrades

Follow the upstream [Step 5/5. Enroll Linux agents in automatic upgrades](https://goteleport.com/docs/upgrading/self-hosted-automatic-agent-updates/#step-55-enroll-linux-agents-in-automatic-upgrades)

In the "Configure the upgrader" section, 

* `version-server-url/path` value will be `<proxy_url>/v1/webapi/automaticupgrades/channel`. Do not include `https://`
* `release-channel:` value will correspond to the channel name you picked in Step 1/5. `default` is the value in this example guide.

### `teleport.yaml` Syntax Reference

The `automatic_upgrades_channels` configuration is a map where each entry
corresponds to a channel with specific versioning and criticality settings.
Below is the structure of the channel configuration:

```yaml
proxy_service:
  automatic_upgrades_channels:

    # you can have as many channels as you want. Each key is the channel name.
    channelname:
      # each channel should specify either `forward_url` or `static_version`. 

      # URL of an external version server providing version and criticality information.
      #forward_url: https://updates.releases.teleport.dev/v1/stable/cloud/v14

      # Specific version to serve for this channel. Version can be prefixed with v.
      static_version: v14.3.4

      # Indicates whether the `static_version` in current channel should be considered critical.
      # `false` by default if omitted. Cannot be set when using `forward_url`.
      critical: true
```

### Additional note

Unlike in Teleport Cloud, It is necessary to specifically configure your upgrades with a self-hosted proxy version endpoint.

In a Teleport Cloud environment, the auto upgrader will use `https://<teleport_proxy>/v1/webapi/automaticupgrades/channel/stable/cloud` when it detects that the `proxy_server` value as seen in `/etc/teleport.yaml` is a cloud endpoint.

edit: use `default` for the channel name throughout the guide. minor changes in YAML reference section.
