### DISCUSSION TITLE
2 Proxies, agents create reverse tunnel only on one of them

### DISCUSSION THREAD

**Discussion by buzzzo** [gravitational/teleport#38075] [Q&A] [answered]
**DETAILS** 

My high level config:
1) 2 proxy, teleport1.foo.bar and telepor2.foo.bar cluster name is: tport.foo.bar
2) on teleport1 there is also the auth server configured (is the first node created with the default config found on teleport's site)
3) i don't want to use tls routing so i setup on the auth server (teleport1): proxy_listener_mode: separate , tunnel_strategy: mesh

**So my goal would be:**
1) let teleport2 proxy be exposed on the internet 
2) let teleport1 proxy answers to internal agents

**What i'm expecting:**

As per documentation is supposed that each agent creates a reverse tunnel to each proxy, so in this case: one vs teleport1:3024 and one vs teleport2:3024 (as i does not use tls routing) 

**What's really happens:**

1) all works until i start the proxy on teleport2
2) as soon as teleport2 proxy is started i've start seeing weird log errors on teleport1
3) agents connects only on teleport1:3024 so started only one tunnel
4) i'm able to connect and login on teleport2:443 via  tsh login, but can't  connect to ant ssh resources
5) i'm able to connect to resources via teleport1 proxy, in other words it's just the teleport2 proxy that does not work

**Teleport1 config: (proxy1 + auth service):**

```
version: v3
teleport:
  nodename: teleport1.foo.bar
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  storage:
    type: sqlite
    sync: NORMAL
    journal: WAL

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: tport.foo.bar
  proxy_listener_mode: separate
  tunnel_strategy:
    type: agent_mesh

ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s

proxy_service:
  enabled: "yes"
  web_listen_addr: 172.18.4.90:443
  public_addr: tport.foo.bar:443
  tunnel_listen_addr: 0.0.0.0:3024
  #tunnel_public_addr: tport.foo.bar:3024
  listen_addr: 0.0.0.0:3023
  https_keypairs:
  - key_file: /etc/teleport/ssl/tport.key
  - cert_file: /etc/teleport/ssl/tport.crt
  https_keypairs_reload_interval: 0s
  acme: {}

```
Teleport2 config (proxy only):

```
version: v3
teleport:
  nodename: teleport2.foo.bar
   data_dir: /var/lib/teleport
  join_params:
    token_name: xya
    method: token
  auth_server: teleport1.foo.bar:3025
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: xyz
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
  labels:
    teleport.internal/resource-id: 0fd24cbb-38db-4fe4-b1b2-89cd3b6d50c1
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: teleport2.foo.bar:443
  public_addr: tport.foo.bar443
  tunnel_listen_addr: teleport2.foo.bar:3024
  tunnel_public_addr: teleport2.foo.bar:3024
  listen_addr: 0.0.0.0:3023
  https_keypairs:
  - key_file: /etc/teleport/ssl/tport.key
    cert_file: /etc/teleport/ssl/tport.crt
  https_keypairs_reload_interval: 0s
  acme: {}
```

**Config file of a test agent:**

```
version: v3
teleport:
  nodename: nbox1.foo.bar
  data_dir: /var/lib/teleport
  join_params:
    token_name: xyz
    method: token
 
  proxy_server: teleport1.foo.bar:3024
  log:
    output: stdout
    severity: DEBUG
    format:
      output: text
  ca_pin: xyz
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: a5ed3524-6c27-4a69-81ee-b3c804a221c5
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: a5ed3524-6c27-4a69-81ee-b3c804a221c5
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}

```
**tctl proxy ls output** 

```
kind: proxy
metadata:
  expires: "2024-02-11T12:24:50.499286517Z"
  id: 1707653690512023829
  name: 8bff5a63-4dae-491b-b3ca-d916bdd133d5
  revision: a4f5728f-eb48-4d03-b519-3c78fa184643
spec:
  addr: 172.16.1.99:443
  hostname: teleport2.foo.bar
  public_addrs:
  - tport.foo.bar:443
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 15.0.1
version: v2
---

kind: proxy
metadata:
  expires: "2024-02-11T12:25:57.662671311Z"
  id: 1707653757670119562
  name: e4fbfc25-20f1-4174-ae23-89839f0b6706
  revision: 1a4fff72-3414-4c88-8681-82b638cf154d
spec:
  addr: 172.18.4.90:443
  hostname: teleport1.foo.bar
  public_addrs:
  - tport.foo.bar:443
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 15.0.1
version: v2

```
**Log on nbox1 test client:**

Feb 11 13:21:40 nbox1 teleport[647682]: 2024-02-11T13:21:40+01:00 DEBU [PROXY:AGE] Received discovery request: [e4fbfc25-20f1-4174-ae23-89839f0b6706] leaseID:1 target:tport.foo.bar:3024 localCluster: targetCluster:tport.foo.bar reversetunnel/agent.go:652
Feb 11 13:21:41 nbox1 teleport[647682]: 2024-02-11T13:21:41+01:00 DEBU [PROXY:AGE] Received discovery request: [8bff5a63-4dae-491b-b3ca-d916bdd133d5, e4fbfc25-20f1-4174-ae23-89839f0b6706] leaseID:1 target:tport.foo.bar:3024 localCluster: targetCluster:tport.foo.bar reversetunnel/agent.go:652
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Runtime config: restrict_connection_count: false connection_count: 1 localCluster: targetCluster:tport.foo.bar reversetunnel/agentpool.go:340
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU             Attempting GET teleport1.foo.bar:3024/webapi/find webclient/webclient.go:129
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Starting agent {tport.foo.bar:3024 tcp } leaseID:506 target:tport.foo.bar:3024 localCluster: targetCluster:tport.foo.bar reversetunnel/agent.go:299
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:506 target:tport.foo.bar:3024 localCluster: targetCluster:tport.foo.bar reversetunnel/agent.go:287
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:197
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Aborting SSH handshake because the proxy "e4fbfc25-20f1-4174-ae23-89839f0b6706.tport.foo.bar" is already claimed by some other agent. localCluster: targetCluster:tport.foo.bar reversetunnel/agent_dialer.go:78
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Changing state connecting -> closed. leaseID:506 target:tport.foo.bar:3024 localCluster: targetCluster:tport.foo.bar reversetunnel/agent.go:287
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Failed to connect agent: ssh: handshake failed: proxy already claimed. localCluster: targetCluster:tport.foo.bar reversetunnel/agentpool.go:277
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Active agent count: 1 localCluster: targetCluster:tport.foo.bar reversetunnel/agentpool.go:423
Feb 11 13:21:46 nbox1 teleport[647682]: 2024-02-11T13:21:46+01:00 DEBU [PROXY:AGE] Active agent count: 1 localCluster: targetCluster:tport.foo.bar reversetunnel/agentpool.go:423

**CONCLUSIONS**

From nbox1 logs seems that although the node correctly discovered the two proxies it only connects only on teleport1, and starts continually try to recconect to it , resulting in handshaking errors.
It does not try to connect at all to proxy teleport2.
