### DISCUSSION TITLE
Unable to use Fortigate with teleport web application

### DISCUSSION THREAD

**Discussion by lucasmlrd** [gravitational/teleport#38329] [Q&A] [answered]
Hello,
I've added web applications to access my fortigate firewall (you'll find the conf of my teleport.yaml below). However, when I try to access it, I get the connection test pattern, but once I've connected, I get a blank page. If I reload the page, I can access my Fortigate's management, but the menus load randomly and sometimes I can't access anything.

Has this ever happened to anyone?

Thanks in advance,

```
app_service:
  enabled: "yes"
  apps:
    - name: "fortigate1"
      uri: "https://1.2.3.4:8443/"
      insecure_skip_verify: true
```

**Comment by stevenGravy** [comment, marked as answer]
I would take a look in the rewrite area here. If you look at the developer console you may see it's still attempting direct links. https://goteleport.com/docs/application-access/guides/connecting-apps/#rewrite-redirect

**Comment by lucasmlrd** [comment]
Thank you, the problem has been solved.

**Reply by FriedBoard** [reply]
Could you share how this was fixed?

**Reply by webvictim** [reply]
My guess would be adding a redirection to the Teleport app configuration:

```yaml
app_service:
  enabled: "yes"
  apps:
    - name: "fortigate1"
      uri: "https://1.2.3.4:8443/"
      insecure_skip_verify: true
      rewrite:
        redirect:
          - "1.2.3.4"
```
