### DISCUSSION TITLE
Configure access for local Windows users with running Windows Desktop Service on the teleport cluster itself

### DISCUSSION THREAD

**Discussion by longansv** [gravitational/teleport#39446] [Q&A]
i am looking to implement Configure access for local Windows users using the teleport cluster itself to run Windows Desktop Service, because I don't want to have to install another linux server to run Windows Desktop Service. Can anyone help me adjust the teleport.yaml configuration file on the teleport cluster to run Windows Desktop Service so that I can connect to Windows Desktop? Here is my current teleport.yaml file and how do I fix it

```
version: v3
teleport:
  nodename: jumpserver02
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  connection_limits:
    max_connections: 1000
    max_users: 250
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: longhd98.click
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: longhd98.click:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "no"
    email: longhd.vt1@gmail.com
```
