### DISCUSSION TITLE
Managing user access to kubernetes resource in teleport role or kubernetes RBAC ?

### DISCUSSION THREAD

**Discussion by mositafan10** [gravitational/teleport#40161] [Q&A] [answered]
Hi everyone. I am using teleport version 14 and define some roles for team members to use kubernetes through teleport.
In teleport tole i define this :

```
kind: role
metadata:
  name: kube-access
version: v6
spec:
  allow:
    kubernetes_groups:
    - editor
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: 'service'
        namespace: 'test''
        name: "*"
        verbs:
        - get
```

The editor group in kubernetes has bind with edit clusterrole. i want to restrict this role to get just service in namespace test but this role get servicec in all namespace and also get other resource because of editor group apparently. how should define such a role ?

in another role when i define nothing in kubernetes_groups, i get forbidden error when i run kubectl get services test. 
So apparently for each role i should define group in kubernetes. is that correct ?

please show a best practice for managing role access in teleport and kubernetes in order to the manage in one place (teleport or kubernetes)
