### DISCUSSION TITLE
power bi report server web application access shows internal server error 500

### DISCUSSION THREAD

**Discussion by masbirooo** [gravitational/teleport#40744] [Q&A]
Hi, 

iam proxying my power bi report server web UI through teleport, 
the UI is has a NLB and NFW on front,
iam accessing through the original url normally but through teleport  it prompts the report server's basic auth page
and after i log in it shows a black screen with internal server error 

Teleport/teleport agent Version:
14.3.14

Report server logs:

`received a request with an unmatched or no authentication scheme. 401
`

teleport agent logs:
`
{"caller":"reverseproxy/reverse_proxy.go:216","component":"app:service","level":"error","message":"Error forwarding to https://is-report.example.com/reports/browse, err: stream error: stream ID 3; HTTP_1_1_REQUIRED; received from peer","timestamp":"2024-04-18T08:57:54Z"}`

teleport agent config:

```
- name: is-report
    uri: "https://is-report.example.com/reports/browse"
    public_addr: is-report.teleport.exmple.com/reports/browse
  labels:
     xx: xx
```

iam not sure if this is related to teleport not supporting basic auth
or redirection issue or could be certificate issue!

any ideas ?

**Comment by masbirooo** [comment]
i can now login by switch the uri to http:10.x.x.x/reports/browse instead of https, but now i get 400 bad request

**Comment by webvictim** [comment]
On the face of it, this looks like the web server is expecting an HTTP/1.1 connection but Teleport is actually using HTTP/2 to connect to it. This shouldn't happen.

With that said, your app config also looks a bit off. Correct indentation and spacing are very important in YAML. Try this and restart:

```yaml
apps:
- name: is-report
  uri: https://is-report.example.com/reports/browse
  public_addr: is-report.teleport.exmple.com
  labels:
    xx: xx
```
