### DISCUSSION TITLE
Disabling local logins for Teleport authentication

### DISCUSSION THREAD

**Discussion by webvictim** [gravitational/teleport#40996] [Show and tell]
Related announcement: https://github.com/gravitational/teleport/discussions/41130

You may have noticed that following a Teleport proxy upgrade to v15.2.2 or higher, your login page now looks different to how it did before:

<img width="606" alt="Screenshot 2024-04-29 at 09 55 48" src="https://github.com/gravitational/teleport/assets/897821/f672da45-1e15-401b-9b39-429f21447efa">

## Disabling local logins

This is expected due to Teleport adding better support for passkey logins. If you only use SSO logins and don't like the increased size of the UI, however, you can disable local logins to make it smaller by adding this to your `/etc/teleport.yaml` config file on the machines running your Teleport `auth_service` and restarting:

```yaml
auth_service:
  authentication:
    local_auth: false
```

Cloud users can do this using `tctl edit cluster_auth_preference` and adding `local_auth: false` to the `spec` section:
```yaml
kind: cluster_auth_preference
metadata:
  name: cluster-auth-preference
spec:
  local_auth: false
version: v2
```

After this change is made, you should see a smaller login dialog which only shows SSO providers.

<img width="592" alt="Screenshot 2024-04-29 at 09 56 03" src="https://github.com/gravitational/teleport/assets/897821/ff5eaf92-7157-4da1-9f2d-0cd41b4fbc3b">

## Disabling passwordless logins

If you do use local users but don't use passwordless authentication, you can disable the passwordless functionality with the following configs.

`/etc/teleport.yaml`:

```yaml
auth_service:
  authentication:
    passwordless: false
```

`cluster_auth_preference`:
```yaml
kind: cluster_auth_preference
metadata:
  name: cluster-auth-preference
spec:
  passwordless: false
version: v2
```

This will result in the dialog looking more like this:

![image](https://github.com/gravitational/teleport/assets/897821/d8f69e3d-bb09-4e0a-8941-305e5c1d4294)
