### DISCUSSION TITLE
Connect external cluster to ArgoCD via teleport?

### DISCUSSION THREAD

**Discussion by gnur** [gravitational/teleport#41459] [Q&A]
Hi,

We're trying to use a central ArgoCD (hub) that manages multiple external clusters (distributed both locally and geographically) through teleport. However, we cannot seem to find any documentation on how to add an external cluster through teleport to ArgoCD.

Does anyone have a guide or example on how this can be achieved? Right now, it seems like it is almost impossible because the format that ArgoCD uses is different from what tbot outputs, which means we'd need some custom step inbetween (like kyverno) to translate the config.

Thanks!

**Comment by JeferCatarina** [comment]
@gnur I was playing with a similar scenario and I was able to configure this. 
Considering you already have all the clusters enrolled on Teleport, and your ArgoCD is installed using Helm as well, here is what I did:

- Create an ArgoCD bot on Teleport and assign it a role with access to the Kubernetes clusters
- Install a `tbot` Helm release in ArgoCD's namespace
  - Read [this docs](https://goteleport.com/docs/enroll-resources/machine-id/deployment/kubernetes/) to understand how to deploy your tbot 
  - I used the tbot helm chart - [ref1](https://github.com/gravitational/teleport/tree/master/examples/chart/tbot) and [ref2](https://goteleport.com/docs/reference/helm-reference/tbot/)
  - Here is quick values example:
```yaml
clusterName: "teleport.example.com"
teleportProxyAddress: "teleport.example.com:443"
token: "argocd-tbot" # This is your bot's name
defaultOutput:
  enabled: false
outputs:
  - type: kubernetes
    kubernetes_cluster: your-cluster-name
    disable_exec_plugin: true
    destination:
      type: kubernetes_secret
      name: your-cluster-secret
```
- Once your tbot is up and running, you should be able to see a secret with the Kubeconfig and the Teleport identity file in the namespace you deployed it. You can check that secret with the following Kubectl command: `kubectl get secrets -n argocd your-cluster-secret -o jsonpath='{.data}' | jq -r '. | map_values(@base64d)'`
- Now, you need to change your ArgoCD release (or manifests depending on how you deployed your ArgoCD) so Argocd have the new secret mounted into the pods and the `tsh` teleport command. This is how I changed my ArgoCD values:
```yaml
# yaml anchors to avoid repeating these definitions
x-teleport-config:
  volumes: &teleport-volumes
    - name: teleport-tsh
      emptyDir: {}
    - name: your-cluster-secret
      secret:
        secretName: your-cluster-secret
  initContainers: &teleport-init-container
    - name: install-teleport-tsh
      image: busybox:stable
      command: ["sh", "-c"]
      args:
        - |
          set -e
          TELEPORT_VERSION=16.x.x # your desired teleport version
          TELEPORT_PKG=teleport
          SYSTEM_ARCH=amd64
          wget https://cdn.teleport.dev/${TELEPORT_PKG}-v${TELEPORT_VERSION}-linux-${SYSTEM_ARCH}-bin.tar.gz
          tar -xvf ${TELEPORT_PKG}-v${TELEPORT_VERSION}-linux-${SYSTEM_ARCH}-bin.tar.gz
          mv teleport/tsh /opt/teleport/
      volumeMounts:
        - name: teleport-tsh
          mountPath: /opt/teleport
  volumeMounts: &teleport-volume-mounts
    - name: teleport-tsh
      mountPath: /opt/teleport
    - name: your-cluster-secret
      mountPath: /opt/your-cluster-secret
[...]
controller:
  volumes:
    *teleport-volumes
  volumeMounts:
    *teleport-volume-mounts
  initContainers:
    *teleport-init-container
[...]
server:
  volumes:
    *teleport-volumes
  volumeMounts:
    *teleport-volume-mounts
  initContainers:
    *teleport-init-container
```
- Now, you have the `tsh` binary in your ArgoCD pods. You might need to add it to your argocd appset controller pods as well depending on what you use in your argo environment
- If everything is in place, you can enroll your cluster in argocd:
```
# option 1: using argocd cli
argocd cluster add KUBECONFIG_CONTEXT_NAME --name your-cluster-secret \
    --exec-command-api-version "client.authentication.k8s.io/v1beta1"  \
    --exec-command "/opt/teleport/tsh" \
    --exec-command-args "kube" \
    --exec-command-args "credentials" \
    --exec-command-args "--kube-cluster=your-cluster-secret" \
    --exec-command-args "--teleport-cluster=teleport.example.com" \
    --exec-command-args "--proxy=teleport.example.com:443" \
    --exec-command-args "--identity=/opt/your-cluster-secret/identity"

# option 2: using declarative setup
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: your-cluster-name
  namespace: argocd
type: Opaque
stringData:
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "serverName": "kube-teleport-proxy-alpn.teleport.example.com",
        "caData": "YOUR TELEPORT CA DATA BASE64 ENCODED"
      },
      "execProviderConfig": {
        "command": "/opt/teleport/tsh",
        "args": [
          "kube",
          "credentials",
          "--kube-cluster=your-cluster-name",
          "--teleport-cluster=teleport.example.com",
          "--proxy=teleport.example.com:6332",
          "--identity=/opt/your-cluster-name/identity"
        ],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      }
    }
  name: your-cluster-name
  server: https://teleport.example.com:443
```

You can repeat this process for how many clusters you have.
Whenever the tbot updates the identity file, kubelet will update the content of the secret mounted on the Argocd pods, and the tsh will update the client cert and key.

Hopefully this helps you.

**Reply by eldarmus** [reply]
@JeferCatarina thank you for solution. just have a question. when I added only one cluster it works great but after adding the second cluster seems like argocd sees two clusters with the same server url but different names:
for the first cluster:
```
...
name: first-cluster
server: https://teleport.example.com:443
```
the second cluster
```
...
name: second-cluster
server: https://teleport.example.com:443
```
have you tried adding multiple clusters ? if yes can you help to handle this situation ?

**Reply by JeferCatarina** [reply]
That's expected, I think. 
The solution here is to set `destination` on Argo manifests using `name` instead of `server`:

```
  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    # or cluster name
    # name: in-cluster <<< HERE
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: guestbook
```
https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/

Let me know if that helps, @eldarmus

**Reply by eldarmus** [reply]
actually I use `name` of cluster in Application. 
when I checked from UI the list of cluster in settings the name changes between `first-cluster` and `second-cluster` like they are competing for the same url 
![Screenshot 2025-05-09 at 18 47 24](https://github.com/user-attachments/assets/4bf6d251-1819-44dd-86c3-5eabb3335527)

**Reply by JeferCatarina** [reply]
Got it. I think ArgoCD is caching the credentials based on the server address. If you configured `*.teleport.yourdomain.xyz`, you can hit any address you want in the server address, and it should work, as long as it does not conflict with enrolled applications in your Teleport cluster. 

Example:
```yaml
---
[...]
  name: your-cluster-name-a
  server: https://your-cluster-name-a.teleport.example.com:443
---
[...]
  name: your-cluster-name-b
  server: https://your-cluster-name-b.teleport.example.com:443
```
