### DISCUSSION TITLE
How to perform health check with Docker Compose for Teleport?

### DISCUSSION THREAD

**Discussion by MillhioreFiriannoBiscotti** [gravitational/teleport#41880] [Q&A]
I currently have Teleport deployed with Docker Compose.
According to the documentation [here](https://goteleport.com/docs/management/diagnostics/monitoring/), I can use `healthz` and `readyz` endpoint to monitor the status of teleport. However, there seems to be no curl binary in the distroless container image.

How to perform health check with Docker Compose in this case?

**Comment by gordianbahri** [comment]
Add this health check to your teleport-server service in your docker-compose.yml:
```
services:
  teleport-server:
    ...
    healthcheck:
      test: tctl status
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 5s
```

If you also have teleport nodes in your docker compose file, you can add a condition to these services to only start them if your teleport server is running:
```
services:
  teleport-node:
    ...
    depends_on:
      teleport-server:
        condition: service_healthy
```

**Reply by MillhioreFiriannoBiscotti** [reply]
Unfortunately using the healthcheck section from the snippet result in an unhealthy status

```
user@server:~/compose/teleport$ docker inspect --format "{{json .State.Health}}" teleport-main-1 
{"Status":"unhealthy","FailingStreak":71,"Log":[{"Start":"2024-05-22T17:27:36.075104618Z","End":"2024-05-22T17:27:36.174903711Z","ExitCode":-1,"Output":"OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown"},{"Start":"2024-05-22T17:27:38.175945458Z","End":"2024-05-22T17:27:38.287759557Z","ExitCode":-1,"Output":"OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown"},{"Start":"2024-05-22T17:27:40.288975887Z","End":"2024-05-22T17:27:40.412550549Z","ExitCode":-1,"Output":"OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown"},{"Start":"2024-05-22T17:27:42.414133417Z","End":"2024-05-22T17:27:42.548868142Z","ExitCode":-1,"Output":"OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown"},{"Start":"2024-05-22T17:27:44.550338091Z","End":"2024-05-22T17:27:44.671922275Z","ExitCode":-1,"Output":"OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown"}]}
```

**Reply by gordianbahri** [reply]
This is because in order to be able to use `tctl status` you need a shell. If you are using a distroless image and want to execute a command, you don't have a shell or package manager available within the image to run arbitrary commands or install additional software. That's why you're getting the error.
To solve this, you either need to run a teleport image with a distro, or you can pass a command to the distroless image on startup while running docker in the interactive mode:
```
docker run -i my-container tctl status
```
However, the latter will check the system health only once on startup instead of periodically in a 2s interval.

**Reply by MillhioreFiriannoBiscotti** [reply]
Is it not possible to do a normal healthcheck with a distroless container? I don't seems to see a non-distroless container available for Teleport and the latter suggestion only run the healthcheck once which completely defeats the purpose of the healthcheck.

**Reply by gordianbahri** [reply]
Just remove the disroless tag from the image to get a teleport image with a distro... This allows my previous health check snippet to work. Check their [ECR](https://gallery.ecr.aws/gravitational/teleport) page.
Running the `tctl status` command only on startup does not defeat the purpose of a health check, as some use cases only require checking for the initial availability of the teleport proxy service. This could be for example to start up all teleport nodes only if the proxy services started successfully. I pointed this out when posting the docker compose snippet, where the node checks for the proxy service and start conditionally if the proxy service is up and running.

**Reply by MillhioreFiriannoBiscotti** [reply]
According to the changelog of version 15.0.0, non-distroless images are no longer provided:

> 
> "Heavy" container images are discontinued
> 
> In order to increase default security in 15+, Teleport will **no longer publish [container images containing a shell and rich command line environment](https://github.com/gravitational/teleport/blob/branch/v14/build.assets/charts/Dockerfile)** to Elastic Container Registry's [gravitational/teleport](https://gallery.ecr.aws/gravitational/teleport) image repo. Instead, **all users should use the [distroless images](https://github.com/gravitational/teleport/blob/branch/v15/build.assets/charts/Dockerfile-distroless)** introduced in Teleport 12. These images can be found at:
>     <...>
> For users who need a shell in a Teleport container, a "debug" image is available which contains BusyBox, including a shell and many CLI tools. Find the debug images at:
> <...>
> **Do not run debug container images in production environments.**

The purpose of healthcheck is to constantly monitor the service status, and only running it once at startup does not do the continuous monitoring part.

**Reply by gordianbahri** [reply]
@MillhioreFiriannoBiscotti the purpose of a health check is to verify the health of the system. When and how often this action should be performed is different in each use case. However, in your case, you can just use their [diagnostics endpoint](https://goteleport.com/docs/management/diagnostics/monitoring/). Just start the docker container with a `--diag-addr` flag specifying where the diagnostics endpoint should listen. In your docker example, this would be 0.0.0.0:3000. Then create a second container and constantly monitor the service.

> However, there seems to be no curl binary in the distroless container image.

Whether curl is installed on the container that should be monitored is not relevant, as monitoring a system on the same system the service is running on, defeats the purpose of the monitoring in the first place. 

Obviously, this requires some more customization from you than my rough outline below (e.g. installing curl):

```
version: "3.8"

services:
  teleport-service:
    image: public.ecr.aws/gravitational/teleport-distroless:15.3.7
    ...
    ports:
      - "3000:3000"
    network:
      - teleport-network
    command: ["teleport", "start", "--config", "/etc/teleport.yaml", "--diag-addr=0.0.0.0:3000"]

  monitoring-service:
    image: alpine
    ...
    network:
      - teleport-network
    command: ["sh", "-c", "while true; do curl teleport-service:3000/readyz; sleep 2; done]

network:
  teleport-network:
    driver: bridge
```

**Reply by webvictim** [reply]
`http://<teleport-ip>:3000/readyz` is probably the best health check you can use.

`/healthz` reports whether the server is running, but `/readyz` reports whether it's in a good state (i.e. to accept connections)

https://goteleport.com/docs/management/diagnostics/monitoring/

**Reply by gordianbahri** [reply]
Thanks @webvictim, I updated my previous answer.

**Reply by rts-kotori** [reply]
Seems like the following can be used:
```
    healthcheck:
      test: ["CMD", "tctl", "status"]
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 5s
```
And it does return `healthy` status.
However I am not sure about the behavior of the `tctl status` command. Will it return non-zero exit code if the health is degraded?
