### DISCUSSION TITLE
Duplicated AWS Integration

### DISCUSSION THREAD

**Discussion by inthenightsky** [gravitational/teleport#42063] [Q&A] [answered]
Hi,

I appear to have two AWS logins on my instance, when I've only got one installed currently. I followed the guided experience in Community Edition to try setting up AWS, but had to restart the experience, so deleted the integration and started again. It seems somewhere along the line, this has resulted in two entries for AWS.

<img width="1322" alt="image" src="https://github.com/gravitational/teleport/assets/22177675/fa82ff0f-c413-459c-982f-5b13e265d260">

AWS-A is the incorrect configuration, AWS-B is the correct configuration. I've tried running **tctl rm app/aws-a** however that doesn't work, and outputs that the resource doesn't exist, despite it appearing successfully when **tctl apps ls** is used.

My /etc/teleport.yaml:

```                  
version: v3
teleport:
  nodename: <removed>
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: <removed>
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: <removed>
    passwordless: true
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: <removed>:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: <removed>
```

Under Access Management > Integrations, I only see one integration active for AWS-B and that's it so I'm stumped as to where it's pulling the configuration from.

All components of the cluster are running 15.3.7.

If you need additional files, please let me know.
