### DISCUSSION TITLE
Azure AKS with application gateway ingress on https not working

### DISCUSSION THREAD

**Discussion by shahidimran** [gravitational/teleport#42815] [Q&A]
### Description

**What happened:**
Can't make Teleport work inside Azure AKS with application gateway as ingress:

**Details:**
Following is the configuration I am using to deploy using the helm 

```yaml
clusterName: teleport.example.com
proxyListenerMode: multiplex

annotations:
  ingress:
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "ca-cert"
    
service:
  type: ClusterIP

ingress:
  enabled: true
  suppressAutomaticWildcards: false
  spec:
    ingressClassName: azure-application-gateway

tls:
  existingSecretName: "teleport-cert"
  existingCASecretName: "teleport-cert-ca"

proxy:
  tls:
    enabled: true
    usetlssecret: true
    secretName: teleport-cert

highAvailability:
  replicaCount: 2


podSecurityPolicy:
  enabled: false
```
  
everything gets deployed successfully and I do not see any errors in proxy pods, however, when i check the health probe on App GW they are not able to reach the health endpoint on HTTPS and because of this the ingress is not working

**Health Probe** 

![image](https://github.com/gravitational/teleport/assets/150918934/1255915d-792c-46ec-8371-5d8427aca16f)

![image](https://github.com/gravitational/teleport/assets/150918934/7c6e84bd-33b5-49d2-858a-f66e277a0aff)

If I change the health probe to HTTP, it works fine on the health probe test but for that, I have to change the backend settings to HTTP as well, which is not correct as the backend is always HTTPS and the ingress does not work either.

The only way I was able to get it working was to change the health probe to using FQDN and changing the port to 3080 and using webapi/ping endpoint but I am not sure if this is a valid health check endpoint for pods.

![image](https://github.com/gravitational/teleport/assets/150918934/0cd951e1-6510-40eb-97cd-58ad4d532ecd)
