### DISCUSSION TITLE
Teleport-acm service does not start after reboot of starter cluster

### DISCUSSION THREAD

**Discussion by varuna-aample** [gravitational/teleport#43172] [Q&A] [answered]
Hello,

The starter cluster teleport-acm service does not restart after reboot of ec2 instance. 
I tried to enable the service with `sudo systemctl enable teleport-acm`, but it returned 
```
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
```

Teleport version - `v16.0.1`
teleport.yaml
 ```yaml
version: v3
teleport:
  nodename: ap-south-1-compute-internal
  advertise_ip: <redacted>
  log:
    output: stderr
    severity: INFO
  data_dir: /var/lib/teleport
  storage:
    type: dynamodb
    region: ap-south-1
    table_name: teleport
    audit_events_uri: dynamodb://<redacted>
    audit_sessions_uri: s3://<redacted>/records

auth_service:
  enabled: yes
  keep_alive_interval: 1m
  keep_alive_count_max: 3
  listen_addr: 0.0.0.0:3025
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: <redacted>
  cluster_name: teleport
  proxy_listener_mode: multiplex

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:3022

proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:443
  public_addr: <redacted>:443
  trust_x_forwarded_for: true
```
Recreation steps
  - Setup an all-in-one(auth,node,proxy) starter cluster with ACM enabled (via terraform) on an AWS EC2 instance
  - Reboot the instance
 

How do I make the teleport-acm service restart at boot?
