### DISCUSSION TITLE
Completely disable Teleport-Jwt-Assertion header?

### DISCUSSION THREAD

**Discussion by uedvt359** [gravitational/teleport#43460] [Q&A] [answered]
I'm trying to proxy a WebApp that has very strict header length restrictions. Even when setting `jwt_claims: none`, the `Teleport-Jwt-Assertion` is still too long, and the webapp returns a http/500 error.

Is there a way to completely disable sending this header? I tried to create a header override rule, but it gets ignored:

```
spec:
  rewrite:
    headers:
    - name: Teleport-Jwt-Assertion
      value: ""  ## does not work, still sends the original header
    jwt_claims: none
```
