### DISCUSSION TITLE
403 While Accessing Jira Via Teleport

### DISCUSSION THREAD

**Discussion by rojinebrahimi** [gravitational/teleport#43672] [Q&A] [answered]
Hey! 
I am using teleport to access services including **Jira** and Confluence via **jira.teleport.example.com**, for instance. Jira has been deployed with the address (The one that Jira service was configured with - before setting up Teleport):
**jira.example.org**

Teleport **app** section's configuration looks like this:
```
app_service:
  apps:
  - insecure_skip_verify: true
    name: jira
    public_addr: jira.teleport.example.com
    rewrite:
      headers:
      - 'Origin: https://jira.example.org'
      - 'Host: jira.example.org'
      - 'Access-Control-Allow-Origin: *'
    uri: https://jira.example.org
...
```

Unfortunately, I get 403 or CORS status for some Jira resources. For example, uploaded images or avatars are not shown. What are necessary headers I need to set in Teleport app_services section for it? I have already tried using CORS headers. 
I have deployed Teleport on K8s taking advantage of Contour Ingress configurations in front of it.

I would be grateful if someone could help.
