### DISCUSSION TITLE
windows remote connection no audio

### DISCUSSION THREAD

**Discussion by hamedprog** [gravitational/teleport#43734] [Q&A] [answered]
I proceeded using the link below and the connection was established: 

https://goteleport.com/docs/desktop-access/getting-started/

However, there is no sound in the connection, while the Windows RDP does have sound.

![image](https://github.com/gravitational/teleport/assets/47194601/ee040c37-6f59-48e4-b8ad-612f50317bf1)

my config
```yaml
version: v3
teleport:
  nodename: ceph-mon-01
  proxy_server: mydomain.com:443
  auth_token: /root/token.txt
windows_desktop_service:
  enabled: yes
  static_hosts:
  - name: joe
    ad: false
    addr: 10.100.10.123

auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: no
```
