### DISCUSSION TITLE
path '/etc/teleport/teleport.yaml' does not exist

### DISCUSSION THREAD

**Discussion by JimmyJeann** [gravitational/teleport#43822] [Q&A]
Hello 
I'm trying to install teleport using this docker composer script 

```
---
# -- (Optional) When using Traefik, use this section
networks:
   frontend:
     external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:16
    container_name: teleport
    volumes:
      - ./config:/data/teleport
      - ./data:/var/lib/teleport
    # -- (Optional) Traefik example configuration
    labels:
       - "traefik.enable=true"
       - "traefik.http.services.teleport.loadbalancer.server.port=3080"
       - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
       - "traefik.http.routers.teleport-http.entrypoints=web"
       - "traefik.http.routers.teleport-http.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?lab.kignaczak.art(?::\\d+)?$`)"
       - "traefik.http.routers.teleport-https.entrypoints=websecure"
       - "traefik.http.routers.teleport-https.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?lab.kignaczak.art(?::\\d+)?$`)"
       - "traefik.http.routers.teleport-https.tls=true"
       - "traefik.http.routers.teleport-https.tls.certresolver=production"
       - "traefik.http.routers.teleport-https.tls.domains[0].main=lab.kignaczak.art"
       - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.lab.kignaczak.art"
    networks:
       - frontend
    restart: unless-stopped
```

with this config file.

```
version: v2
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: lab.kignaczak.art
  # -- (Optional) Passwordless Authentication
  # authentication:
  #   type: local
  #   second_factor: on
  #   webauthn:
  #     rp_id: your-server-url
  #   connector_name: passwordless
  # -- (Optional) Teleport Assist
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

ssh_service:
  enabled: "no"

proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  # -- (Optional) when using reverse proxy
  public_addr: ['lab.kignaczak.art:443']
  https_keypairs: []
  acme: {}
  # --(Optional) ACME
  # acme:
  #   enabled: "yes"
  #   email: your-email-address
  # -- (Optional) Teleport Assist
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

app_service:
  enabled: no
  # -- (Optional) App Service
  # enabled: yes
  # apps:
  #   - name: "yourapp"
  #     uri: "http://your-app-url"
  #     insecure_skip_verify: false
```
    
Everyting installs but I'm ending up with this error in logs

```
Starts a database server that proxies Aurora MySQL database running in AWS
region us-west-1 which only allows access to users with the role "env=aws".
ERROR: path '/etc/teleport/teleport.yaml' does not exist

```
I created this file, changed back path in docker-compose.yaml file to original etc/teleport, but it still dosen't work

Bug details:
- Teleport version: teleport-distroless:16
- Recreation steps: Install teleport with my docker-compose.yaml file
- Debug logsL As shown up top

**Comment by webvictim** [comment]
You're mounting the config file in the wrong place. You should:
- change the volume mount in the docker-compose spec to `./config:/etc/teleport`
- write the config file to `.config/teleport.yaml` outside the container
- run `docker-compose up`

**Reply by JimmyJeann** [reply]
Ok so this is my file structure 

```
root@laboratorium:/teleport# ls
config  data  docker-compose.yaml
root@laboratorium:/teleport# cd config/
root@laboratorium:/teleport/config# ls
teleport.yaml
root@laboratorium:/teleport/config#
```

I changed back volume mount to `./config:/etc/teleport` but i still get the same error 

![image](https://github.com/gravitational/teleport/assets/174643988/ee2e3d60-22b7-4cdb-b6e5-d0b75d6509a8)

**Reply by JimmyJeann** [reply]
OK i think i fixed it, moved it, to the home category and it worked, but now I'm stuck on this 

`teleport  | 2024-07-04T08:21:57Z INFO [PROXY:SER] Starting TLS ALPN SNI proxy server on. pid:7.1 listen_address:[::]:3080 service/service.go:4966`

**Reply by webvictim** [reply]
That's generally the last log line you see when everything is running correctly. Can you connect to the container?

If not, you can also try changing the log severity up to DEBUG to get more info, then restarting the container:
```yaml
teleport:
  log:
    output: stderr
    severity: DEBUG
```
