### DISCUSSION TITLE
tls: unrecognized name when trying to add a kubenetes cluster

### DISCUSSION THREAD

**Discussion by fenpaws** [gravitational/teleport#44585] [Q&A] [answered]
Hello everyone, after two days of trial and error, I decided to ask for some help.

I want to add a Teleport Agent to my RKE2 Cluster (Testing Purposes) via the Terraform UI and I'm failing constantly, 

Agent Version: `16.1.0`
Teleport Version: `Teleport v16.1.0 git:v16.1.0-0-gfd6032e go1.22.5`

---

I'm getting the following error:
```log
User Message: Post &#34;https://teleport.DOMAIN.art:443/v1/webapi/host/credentials&#34;: remote error: tls: unrecognized name] join/join.go:257
2024-07-24T07:33:06Z ERRO [PROC:1]    Failed to establish connection to cluster. pid:7.1 identity:Kube error:[
ERROR REPORT:
Original Error: trace.aggregate Post &#34;https://teleport.DOMAIN.art:443/v1/webapi/host/credentials&#34;: remote error: tls: unrecognized name
Stack Trace:
	github.com/gravitational/teleport/lib/auth/join/join.go:263 github.com/gravitational/teleport/lib/auth/join.Register
	github.com/gravitational/teleport/lib/service/connect.go:508 github.com/gravitational/teleport/lib/service.(*TeleportProcess).firstTimeConnect
	github.com/gravitational/teleport/lib/service/connect.go:215 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect
	github.com/gravitational/teleport/lib/service/connect.go:188 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService
	github.com/gravitational/teleport/lib/service/connect.go:81 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService
	github.com/gravitational/teleport/lib/service/service.go:2924 github.com/gravitational/teleport/lib/service.(*TeleportProcess).RegisterWithAuthServer.func1
	github.com/gravitational/teleport/lib/service/supervisor.go:588 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	github.com/gravitational/teleport/lib/service/supervisor.go:313 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	runtime/asm_amd64.s:1695 runtime.goexit
```

When I try to make a POST Request via Postman, I get a 400 error and not a TLS error.

My Teleport server is behind a [Nginx Proxy Manager](https://nginxproxymanager.com/), I also Tried Treafik, but I had the same result. I have a valid wildcard certificate and DNS also looks correct.

Even my semaphore that i "expose" via Teleport works fine. No issues there.

Here is my Teleport Config:

```yml
version: v3
teleport:
  nodename: vulpes.srv.DOMAIN.art
  data_dir: /var/lib/teleport
  # proxy_server: teleport.DOMAIN.art:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.DOMAIN.art
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  - name: teleport
    command: [teleport, version]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.DOMAIN.art:443
  ssh_public_addr: teleport.DOMAIN.art:3023
  tunnel_listen_addr: 0.0.0.0:3024
  tunnel_public_addr: teleport.DOMAIN.art:3024
  kube_listen_addr: 0.0.0.0:3026
  kube_public_addr: teleport.DOMAIN.art:3026
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: yes
  # debug_app: false
  apps:
    - name: semaphore
      uri: "http://127.0.0.1:3000"
      public_addr: "semaphore.teleport.DOMAIN.art"
```

Help would be greatly appreciated!
