### DISCUSSION TITLE
Since upgrade from 15.x to 16.x cannot access nodes via teleport web

### DISCUSSION THREAD

**Discussion by StillLoading** [gravitational/teleport#44617] [General]
Hi,

I've gone through all changelogs but could not find anything that points to changes requiring manual intervention for teleport-web.
After upgrading to 16.x I can no longer access any node via the Web-GUI. SSH Session instantly disconnect and web applications open with "access denied" and a CSP error "because it violates the following Content Security Policy directive: "connect-src 'self' wss:".
Access via tsh still works though.

My server config looks like this:

```
version: v2
teleport:
  nodename: teleport01
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: []
  diag_addr: ""
  storage:
    type: sqlite
    sync: NORMAL
    journal: WAL
auth_service:
  enabled: "yes"
  cluster_name: tele.example.com
  authentication:
    second_factor: on
    webauthn:
      rp_id: tele.example.com
  proxy_listener_mode: multiplex
  session_recording: "proxy"
ssh_service:
  enabled: "yes"
  labels:
    hardware: virtual
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  - name: arch
    command: [uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: tele.example.com:443
  https_keypairs: []
  trust_x_forwarded_for: true
  acme:
    enabled: "yes"
    email: js@example.com
```
