### DISCUSSION TITLE
Web SSH: File up/download buttons greyed out

### DISCUSSION THREAD

**Discussion by uedvt359** [gravitational/teleport#44864] [Q&A] [answered]
I don't know what I'm doing wrong, but these buttons are greyed out on all my hosts. My roles all have `ssh_file_copy` enabled, and `tsh scp` works. 
I enrolled them into teleport manually (creating a resource.yaml and role.yaml), and installed the openssh certificate authority in the sshd_config, so there is no agent running on my servers.

![image](https://github.com/user-attachments/assets/ba16cfda-c518-42fc-b8f9-6102263e02f2)

**Comment by webvictim** [comment]
Can you share the full YAML output of _every_ role that your user has? You can find the full list of roles in the "Users" section of the web UI:

<img width="1759" alt="Screenshot 2024-07-31 at 10 32 44" src="https://github.com/user-attachments/assets/ffc709f1-0a04-4dc3-bae1-91d70913be3c">

AFAIK there's nothing that would block you from using file upload/download other than an RBAC permission being denied somewhere.

**Reply by uedvt359** [reply]
sure. my user has the default `editor` and `auditor` roles, as well as my custom 'access-all-ssh-nodes'. (i used `tctl get roles/$rolename` to export them)

```yaml
kind: role
metadata:
  id: 7876710618521667430
  name: my-ssh-access
  revision: 6607882f-93b2-4fed-94fc-4b8a5fee02fc
spec:
  allow:
    logins:
    - ansible
    - root
    node_labels:
      sshname:
      - FQDN:22 for a whole bunch of nodes
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    permit_x11_forwarding: true
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    require_session_mfa: true
    ssh_file_copy: true
version: v7
```

<details><summary>auditor</summary>

```yaml
kind: role
metadata:
  description: Review cluster events and replay sessions
  id: 7945949270858023143
  labels:
    teleport.internal/resource-type: preset
  name: auditor
  revision: e740c42c-c3ae-456e-a263-83db2c816120
spec:
  allow:
    logins:
    - no-login-59b7be70-4421-4e85-8478-4c43c5f48363
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session_tracker
      verbs:
      - list
      - read
    - resources:
      - cluster_alert
      verbs:
      - list
      - read
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - security_report
      verbs:
      - list
      - read
      - use
    - resources:
      - audit_query
      verbs:
      - list
      - read
      - use
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: false
    ssh_file_copy: true
version: v7
```
</details>

<details><summary>editor</summary>

```yaml
kind: role
metadata:
  description: Edit cluster configuration
  id: 1966442169018747912
  labels:
    teleport.internal/resource-type: preset
  name: editor
  revision: 080cb6eb-bb34-4a1b-acca-4ed271dbd748
spec:
  allow:
    rules:
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - bot
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_audit_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_auth_preference
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_name
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_networking_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session_recording_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - external_audit_storage
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - ui_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - remote_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - connection_diagnostic
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - database_certificate
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - installer
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - device
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - create_enroll_token
      - enroll
    - resources:
      - db_service
      verbs:
      - list
      - read
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - login_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml_idp_service_provider
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - user_group
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - plugin
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - okta_import_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - okta_assignment
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - assistant
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - lock
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - integration
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - billing
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_alert
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - access_list
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - node
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - discovery_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - security_report
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - audit_query
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - access_graph
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - server_info
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db_object_import_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - app_server
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - access_monitoring_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - crown_jewel
      verbs:
      - list
      - create
      - read
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: false
    ssh_file_copy: true
version: v7

```
</details>

**Reply by uedvt359** [reply]
hey, @webvictim, I'm wondering what else I can do to debug this? I threw away my teleport.yaml and database and tried again with a minimal config, still doesn't work.

or is this feature incompatible with `sub_kind: openssh` nodes? (that's the only kind I got)

**Reply by webvictim** [reply]
It works fine for me on an OpenSSH node with the following config:

```yaml
kind: node
metadata:
  labels:
    type: openssh
  name: c70aeeed-84d3-4bd2-a739-88e70f0f344e
  revision: 00000000-0000-0000-0000-000000000000
spec:
  addr: 172.31.8.63:22
  hostname: ip-172-31-8-63
  rotation:
    current_id: ""
    last_rotated: "2021-12-03T19:43:59.014196449Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: ""
sub_kind: openssh
version: v2
```

**Reply by uedvt359** [reply]
that's exactly the same node config as I have (except for some different labels, and `metadata.id` is automatically populated). would you mind sharing a /etc/teleport.yaml please? i have attached mine

<details><summary>/etc/teleport.yaml</summary>

```
version: v3
teleport:
  nodename: myserver.com
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  diag_addr: 0.0.0.0:3000
  storage:
    type: postgresql
    conn_string: postgresql://teleport_dbuser@127.0.0.1:5432/teleport_backend?pool_max_conns=20
    audit_events_uri: postgresql://teleport_dbuser@/teleport_audit
    audit_sessions_uri: file:///var/lib/teleport/log
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: myteleport.org
  proxy_listener_mode: multiplex
  session_recording: "off"
  proxy_checks_host_keys: no
  authentication:
    type: local
    second_factor: webauthn
    webauthn:
      rp_id: myteleport.org
      attestation_allowed_cas:
      - "/var/lib/teleport/yubi_attestation.pem"
    connector_name: passwordless
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: myteleport.org:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
app_service:
    enabled: yes
    resources:
    - labels:
        "*": "*"
windows_desktop_service:
  enabled: "no"
db_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
kubernetes_service:
  enabled: "no"
```

</details>

**Reply by webvictim** [reply]
Mine is pretty standard and boring, there isn't much to it:

```yaml
teleport:
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  data_dir: /var/lib/teleport
  diag_addr: 0.0.0.0:3434

auth_service:
  enabled: yes
  authentication:
    type: github
    # require webauthn only (also enables MFA for tctl actions)
    second_factor: webauthn
    webauthn:
      rp_id: teleport.example.com
  cluster_name: purple

proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.com:443
  acme:
    enabled: true
    email: "example@example.com"

ssh_service:
  enabled: yes
  commands:
  - name: hostname
    command: [hostname]
    period: 1h0s
  - name: version
    command: ['/usr/local/bin/teleport', 'version']
    period: 30m0s
  - name: external_ip
    command: ['curl', 'icanhazip.com']
    period: 1h0ms
```
