### DISCUSSION TITLE
Teleport ArgoCD Configuration

### DISCUSSION THREAD

**Discussion by olawale-ib** [gravitational/teleport#44900] [Q&A] [answered]
i want to know if this ArgoCD Teleport configuration is alright.

```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: all-clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: teleport-cluster
    repoURL: https://charts.releases.teleport.dev
    targetRevision: "15.4.6"
    helm:
      values: |
        clusterName: teleport.example.com
        kubeClusterName: application-dev
        proxyListenerMode: multiplex
        proxyProtocol: "off"
        authentication:
          type: github
          connectorName: github
        auth:
          persistence:
            storageClassName: ebs-sc
          teleportConfig:
            auth_service:
              listen_addr: 0.0.0.0:3025
        storage:
          type: "dynamodb"
          region: "us-west-2"
          table_name: "teleport"
          audit_event_uri: "dynamodb://teleport-event"
          audit_session_uri: "s3://teleport-audit-log"
        sessionRecording: proxy-sync
        tls:
          existingSecretName: teleport-tls
        annotations:
          ingress:
            cert-manager.io/cluster-issuer: letsencrypt-internal-prod
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        log:
          format: json
          level: DEBUG
        service:
          type: ClusterIP
        proxy:
          teleportConfig:
            proxy_service:
              web_listen_addr: "0.0.0.0:3080"
              https_keypairs: []
              https_keypairs_reload_interval: 0s
              acme: {}
              trust_x_forwarded_for: true
          highAvailability:
            replicaCount: 1
        ingress:
          enabled: true
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
          limits:
            memory: 300Mi
  destination:
    name: application-dev
    namespace: teleport
```
Because it seems like there might be an issue with the storage block, there's no item showing in dynamo table.

**Comment by olawale-ib** [comment]
sessions are not getting uploaded to s3 too

**Comment by webvictim** [comment, marked as answer]
It looks OK, with a few issues:

1) `audit_session_uri` is a plural, it should be `audit_sessions_uri`

2) `audit_event_uri` is a plural, it should be `audit_events_uri`

3) Your `storage` section should be set as a config override:

```yaml
spec:
  source:
    helm:
      values:
        auth:
          teleportConfig:
            teleport:
              storage:
              ...
```

This is why your config isn't being applied.

For DynamoDB config examples, see https://goteleport.com/docs/reference/backends/#configuring-the-dynamodb-backend.

3) I don't know why you're manually setting the auth server's listen address to `0.0.0.0:3025`?

**Reply by olawale-ib** [reply]
Thank you very much.
For the auth listen address, that was the configuration I met before joining the team, and it works fine
For the storage section, that was actually the config I did but I got an error and changed to what I posted above
```
ERROR REPORT: 
Original Error: *awserr.requestError AccessDeniedException: User: arn:aws:sts::<acct id>:assumed-role/eks-node-group-***/i-*** is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-west-2:<acct id>.:table/teleport because no identity-based policy allows the dynamodb:DescribeTable action status code: 400
Stack Trace:
github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:750 github.com/gravitational/teleport/lib/backend/dynamo.(*Backend).getTableStatus
github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:301 github.com/gravitational/teleport/lib/backend/dynamo.New
github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:56 github.com/gravitational/teleport/lib/backend/dynamo.init.0.func1
github.com/gravitational/teleport/lib/backend/backend.go:125 github.com/gravitational/teleport/lib/backend.New
github.com/gravitational/teleport/lib/service/service.go:5918 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthStorage
github.com/gravitational/teleport/lib/service/service.go:1786 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
github.com/gravitational/teleport/lib/service/service.go:1247 github.com/gravitational/teleport/lib/service.NewTeleport
github.com/gravitational/teleport/lib/service/service.go:745 github.com/gravitational/teleport/lib/service.newTeleportProcess
github.com/gravitational/teleport/lib/service/service.go:761 github.com/gravitational/teleport/lib/service.Run
github.com/gravitational/teleport/tool/teleport/common/teleport.go:726
github.com/gravitational/teleport/tool/teleport/common.OnStart
github.com/gravitational/teleport/tool/teleport/common/teleport.go:613 github.com/gravitational/teleport/tool/teleport/common.Run
github.com/gravitational/teleport/tool/teleport/main.go:33 main.main   runtime/proc.go:271 runtime.main
runtime/asm_amd64.s:1695 runtime.goexit
User Message: initialization failed  AccessDeniedException: User: arn:aws:sts::<acct id>:assumed-role/eks-node-group-***/i-*** is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-west-2:<acct id>:table/teleport because no identity-based policy allows the dynamodb:DescribeTable action status code: 400
```

I can't attach s3 or dynamo policy to that role (eks-node-group-***) but there is a role (teleport-role) that has the necessary policy attached, if I add the role under `serviceAccount`, is that what teleport will assume when it tries to access the bucket or table

```
        auth:
          persistence:
            storageClassName: ebs-sc
          teleportConfig:
            auth_service:
              listen_addr: 0.0.0.0:3025
            storage:
              type: "dynamodb"
              region: "us-west-2"
              table_name: "teleport"
              audit_events_uri: "dynamodb://teleport-event"
              audit_sessions_uri: "s3://teleport-audit-log"
        sessionRecording: proxy-sync
        tls:
          existingSecretName: teleport-cluster-tls
        annotations:
          ingress:
            cert-manager.io/cluster-issuer: letsencrypt-internal-prod
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          serviceAccount:
            eks.amazonaws.com/role-arn: "arn:aws:iam::<acct-id>:role/teleport-role"
        log:
          format: json
          level: DEBUG
```

**Reply by webvictim** [reply]
> if I add the role under serviceAccount, is that what teleport will assume when it tries to access the bucket or table

Yes.

Bear in mind that there are separate Kubernetes `ServiceAccount`s for the auth and proxy - you need to add the IRSA annotation on the `ServiceAccount` used by the auth service.

```yaml
auth:
  annotations:
    serviceAccount:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<acct-id>:role/teleport-role"
```

You'll also need an appropriate trust policy for `AssumeRoleWithWebIdentity` set up on the IAM role.
