### DISCUSSION TITLE
Sessions Not Getting Recorded

### DISCUSSION THREAD

**Discussion by olawale-ib** [gravitational/teleport#45444] [Q&A] [answered]
Hello,
So I have a working teleport, that uses dynamodb and s3 for storage. in my testing I noticed that sessions are not getting recorded, audit logs works fine and are written to dynamo table
My configuration below
```
 auth:
          persistence:
            enabled: false
          teleportConfig:
            auth_service:
              listen_addr: 0.0.0.0:3025
            teleport:
              storage:
                type: "dynamodb"
                region: "us-west-2"
                table_name: "teleport"
                audit_events_uri: "dynamodb://teleport-events"
                audit_sessions_uri: "s3://teleport-audit-log"
        sessionRecording: proxy-sync
        tls:
          existingSecretName: teleport-tls
        annotations:
          ingress:
            cert-manager.io/cluster-issuer: letsencrypt-dev
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          serviceAccount:
            eks.amazonaws.com/role-arn: "arn:aws:iam::2****:role/teleport-role"
        log:
          format: json
          level: DEBUG
        service:
          type: ClusterIP
        proxy:
          teleportConfig:
            proxy_service:
              web_listen_addr: "0.0.0.0:3080"
              https_keypairs: []
              https_keypairs_reload_interval: 0s
              acme: {}
              trust_x_forwarded_for: true
          highAvailability:
            replicaCount: 1
```
This is log from my teleport-proxy 

```
{"caller":"services/watcher.go:534","component":"proxy:1","level":"debug","message":"List of known proxies updated: [\"52f71e3b-87d5-467a-a30d-1043a646eb99\"].","pid":"7.1","timestamp":"2024-08-13T17:25:31Z"}
{"caller":"web/sessions.go:733","component":"web","ctx":"WebSession(user=wale,id=9a61,expires=2024-08-14 00:44:48.962481282 +0000 UTC,bearer_expires=2024-08-13 17:17:18.037604247 +0000 UTC)","level":"debug","message":"Context expired.","timestamp":"2024-08-13T17:26:00Z"}
{"timestamp":"2024-08-13T17:26:20Z","level":"warning","caller":"web/conn_upgrade.go:193","message":"Failed to write ping message.","component":"web","error":"write tcp ip_address:3080->ip_address:56606: write: broken pipe"}
{"timestamp":"2024-08-13T17:28:34Z","level":"warning","caller":"web/conn_upgrade.go:193","message":"Failed to write ping message.","component":"web","error":"write tcp ip_address:3080->ip_address:55144: write: broken pipe"}
{"caller":"cache/cache.go:2499","component":"proxy:1:cache","level":"warning","message":"Cache was forced to load session web_session/15b26dd08a55bad402ed from upstream. Frequent occurrence may indicate sync/perf issues.","timestamp":"2024-08-13T17:29:19Z"}
```

Will changing to `node-sync` work, even though I  don't have ssh_service enabled in the config?
