### DISCUSSION TITLE
Static Tokens

### DISCUSSION THREAD

**Discussion by simaqsous** [gravitational/teleport#45723] [Q&A]
I am trying to generate static token ( teleport vs 16.1.4 ) and I am configuring it right here
```
auth_service:
  tokens:
    - 'proxy,node:teleport-token-test'
  enabled: "yes"
```
as shown in the document in here https://goteleport.com/docs/reference/join-methods/#static-tokens
but when I run 
```
tctl tokens ls
```
```
teleport-token-test    Proxy,Node        01 Jan 70 00:00 UTC (-479000h30m24s)
```
and when I try to use this token, it won't work, since it expired 
any help would be appreciated
