### DISCUSSION TITLE
How to deploy multi teleport cluster in K8s with teafik and use tsh login

### DISCUSSION THREAD

**Discussion by Rory-Z** [gravitational/teleport#46851] [Q&A]
Hi guys, I deployed two teleport cluster in my K8s cluster, and use teafik with tls route to export them, when I access them in browser, it all works great.

But when I use `tsh login` to access them, one of teleport cluster is work, but another one will return `transport: authentication handshake failed: context deadline exceeded`

I think the reason maybe is I set `hostnames: '*.teleport.cluster.local'` both of two teleport cluster TLS route, but if I delete this hostname, I event can't use `tsh login` to access anyone, and `teleport.cluster.local` looks is a golang constants in teleport's code, so I can't change it.

The follow is my TLSRoute, how can I access both teleport cluster by `tsh login` ?

One of the TLSRoute
```YAML
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: teleport
  namespace: teleport-dev
spec:
  hostnames:
    - '*.teleport.cluster.local'
    - teleport.dev.my.domain.name.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: teleport-gateway
      sectionName: https
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: teleport-cluster-dev
          port: 443
```

Another one of the TLSRoute
```YAML
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: teleport
  namespace: teleport-test
spec:
  hostnames:
    - '*.teleport.cluster.local'
    - teleport.test.my.domain.name.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: teleport-gateway
      sectionName: https
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: teleport-cluster-test
          port: 443
```
