### DISCUSSION TITLE
GOT "ERROR: ssh: cert has expired" when executing the command "sudo tsh play --format=json <session_chunk_id>"

### DISCUSSION THREAD

**Discussion by gramunno** [gravitational/teleport#47078] [Q&A]
In order to play the captured session of a web app I executed the command on the proxy machine

"sudo tsh play --format=json <session_chunk_id>"

and I got 

"ERROR: ssh: cert has expired"

I also executed the command

"tsh login --proxy=<proxy_FQDN> --user=teleport-admin"

and re-executed the play command with the same result.

Using strace didn't help understand which certificated is expired.

Teleport version: Teleport v16.4.2 git:v16.4.2-0-ge414b8f go1.22.7
on Ubuntu server 24.04

Any idea?

Any help would be appreciated.

**Comment by webvictim** [comment]
`tsh` requires an active user certificate. You can check your session status with `tsh status` as you saw.

Do note that `tsh` logins are specific to a user, so if you run `tsh login` as a non-root user and then `sudo tsh play` (as root) the error you're seeing is expected.

Try this:
- `tsh login --proxy=<proxy_FQDN> --user=teleport-admin`
- `tsh play --format=json <session_chunk_id>`

**Reply by gramunno** [reply]
Thanks for the reply.

If I execute the two commands above, I get:

[
]
ERROR: access denied to perform action "read" on "session"

**Reply by vanshika-agarwal88** [reply]
do you get the solution?

**Reply by santiago-mooser** [reply]
@gramunno this means your user doesn't have the permissions to read the recorded sessions. You'll have to update the role you have to include "session" in the "allow" section with the verbs "read" and "list": 

```yaml
spec:
[...] 
  allow:
    # rules allow a user holding this role to modify other resources
    # matching the expressions below
    # supported resources:
    # role               - role resource
    # user               - user resource
    #
    # auth_connector     - any auth connector resource
    # oidc               - OIDC connector resource
    # saml               - connector resource
    # github             - GitHub connector resource
    #
    # trusted_cluster    - Trusted cluster resource
    # remote_cluster     - remote cluster resource
    #
    # access_request     - Access Request resource
    # access_plugin_data - allows modifying Access Request plugin data
    #
    # session            - session playback records
    # session_tracker    - an active session
    # instance           - a Teleport instance
    # event              - structured audit logging event
    #
    # workload_identity     - config for Machine & Workload Identity SVIDS
    # bot                   - config for Machine & Workload Identity bots
    #
    # lock                  - lock resource.
    # network_restrictions  - restrictions for SSH sessions
    #
    # auth_server           - Auth Service resource
    # proxy                 - Proxy Service resource
    # node                  - SSH node resource
    # app                   - application resource
    # db                    - database  resource
    # kube_cluster          - Kubernetes cluster resource
    # token                 - provisioning token resource
    # cert_authority        - certificate authority resource
    # git_server            - Git server resource
    #
    # cluster_name              - resource that contains the cluster name.
    # cluster_config            - resource that holds cluster level config
    # cluster_auth_preference   - type of authentication for this cluster
    # session_recording_config  - resource for session recording config
    # cluster_audit_config      - resource that holds cluster audit config
    # cluster_networking_config - resource that holds cluster networking config

    rules:
      - resources: "session"
        verbs:
          - list
          - read
```
