### DISCUSSION TITLE
How to access database via Teleport in Github actions

### DISCUSSION THREAD

**Discussion by KrisF-Midnight** [gravitational/teleport#47188] [Q&A] [answered]
Hey, my goal is to have tests on github access our database in k8s

I've followed this guide hoping to set this up on github:
https://goteleport.com/docs/enroll-resources/machine-id/deployment/github-actions

I'm using this github workflow:

```
jobs:
  demo:
    permissions:
      id-token: write # permission is required or Machine ID will not be able to authenticate with the cluster.
      contents: read
    name: example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Fetch Teleport binaries
      uses: teleport-actions/setup@v1
      with:
        version: 16.4.2
    - name: Fetch credentials using Machine ID
      id: auth
      uses: teleport-actions/auth@v2
      with:
        proxy: teleport.XXXXXXXXXX:443
        token: qa-token
        certificate-ttl: 1h
    - name: login to the database
      run: tsh db login somedb-db --db-user someuser --db-name postgres
    - name: list files
      run: tsh proxy db --port 12345 --tunnel
```

On running the proxy I get this error message:
```
ERROR: please specify a database service by name, --labels, or --query
Error: Process completed with exit code 1.
```

Other db commands react similarly. 
The `tsh proxy` command has no --labels or --query parameter. The only command that has these flags are `tsh request search`.

Is there an example somewhere how to do a proxy tunnel from github?  

Edit: `tsh db login somedb-db --db-user someuser --db-name postgres` actually successfully executes and logs in fine.
