### DISCUSSION TITLE
Guided installation of an additional service on a node: how to avoid that the install script to (re)install teleport?

### DISCUSSION THREAD

**Discussion by gramunno** [gravitational/teleport#47620] [Q&A] [answered]
Hello,

I've a simple test setup with one VM running the proxy and the auth services and a VM as a teleport cluster node.

On this node I have installed a db service from scratch. When I want to install the ssh service on the same node (resource type named (Server) Ubuntu 14.04+), at a certain step I am requested to download and execute a script that tries to install teleport - and if it is already installed, it requests to completely remove it, disrupting the service(s) previously installed.

This problem also occurs if I first install ssh and then the db service.

I do not want to reinstall teleport at every service installation as I want to have multiple services (eg ssh, db, windows desktop,...) installed on the same VM.

How do I install the services on a node without reinstalling teleport every time?

Thanks in advance

**Comment by webvictim** [comment]
You'll want to manually edit the `/etc/teleport.yaml` configuration file to enable each service individually. Example for the SSH service:

```yaml
ssh_service:
  enabled: yes
  # replace with labels you would like set, if needed
  labels:
    env: dev
```

You'll also need to generate a new token valid for the `Node` and `Db` services - you can also edit an existing token in the web UI to add both services under the "Join Tokens" section, then copy the token and replace it in the config file:

```yaml
teleport:
  join_params:
    method: token
    token_name: <token-value-here>
```

After this, restart the Teleport service (`sudo systemctl restart teleport`) and both services should be active.
