### DISCUSSION TITLE
Noob Question .. Adding Cloudflare Root to Teleport Docker

### DISCUSSION THREAD

**Discussion by mOneThree** [gravitational/teleport#48173] [Q&A]
Hello, I am a noob with teleport and I am trying to deploy it in my homelab to access SSH sessions for testing using the latest debug docker image.
I am using an FQDN for access and I added the cert/key files successfully however it seems that the Cloudflare Root is not trusted and I am at a loss as to how to install it.

Any pointers would be really appreciated

**Comment by webvictim** [comment]
This page explains it pretty well: https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/

Do you already have the generated origin cert and private key from Cloudflare as described in Step 1 on that page?

Once you have those files, you will need to configure Docker to mount the files into the Teleport container, something like this:

```yaml
services:
  teleport:
...
    volumes:
      - ./local/path/to/cloudflare-certs:/etc/cloudflare
...
```


Then, configure Teleport to present the files by editing its configuration file (`/etc/teleport/teleport.yaml` by default in Docker):

```yaml
proxy_service:
  https_keypairs:
  - cert_file: /etc/cloudflare/cloudflare-supplied-cert.pem
    key_file: /etc/cloudflare/cloudflare-supplied-key.pem
```

Restart Teleport and you should be good.
