### DISCUSSION TITLE
Web application: how to have a different landing page from the default web server home?

### DISCUSSION THREAD

**Discussion by gramunno** [gravitational/teleport#48229] [Q&A] [answered]
Hello,

I have successfully enrolled a web application whose excerpt of the config file is the following:

```
app_service:
  enabled: yes
  debug_app: false
  apps:
  - name: "phpmyadmin"
    uri: "https://10.0.0.3"
    insecure_skip_verify: false
```

If I change the `uri` value to `uri: "https://10.0.0.3/phpmyadmin/"` and restart teleport on the web app box, nothing changes: the landing page results again the web server home page.

If I revert that change and work on the web server by adding the following global directive within the `<VirtualHost...>` tag in the Apache site config file

`RedirectMatch ^/$ /phpmyadmin/`

then when I launch the resource from teleport Web UI after a couple of slows redirections the browser landed to a timeout error web page with the following URL in the address bar:

`https://10.0.0.3/phpmyadmin/`

Note that the redirection on the web server works fine: I tested it on a machine with a browser running on the same network as the web server (i.e. 10.0.0.3).

Any clue on how to force the redirection to `\phpmyadmin` when launching the web application from the teleport Web UI?

Thanks in advance
