### DISCUSSION TITLE
"X-Forwarded-Host" cannot be overwritten, causing CSRF errors

### DISCUSSION THREAD

**Discussion by uedvt359** [gravitational/teleport#48434] [Q&A] [answered]
For HTTPS apps, Teleport automatically adds "X-Forwarded-Host" (among others) containing e.g "myapp.teleport.example.org". This causes a mismatch between "Host" (being e.g. "myapp.example.org") and XFH. If these don't match, Django 1.9 and above raise a CSRF error. (c.f this [stackoverflow answer](https://stackoverflow.com/a/48646798) or this [django ticket](https://code.djangoproject.com/ticket/26037))

I attempted to add a Header rewrite rule to my app's yaml config, but this seems to be ignored. I even found [a test case](https://github.com/gravitational/teleport/blob/deba1e861d5bd8ac1e4eb585848df15cff92e083/integration/appaccess/appaccess_test.go#L400-L407) specifically checking that this header cannot be modified.

```
spec:
  rewrite:
    headers:
    - name: Host     # can be overwritten just fine
      value: myapp.example.com
    - name: Origin     # can be overwritten just fine
      value: https://myapp.example.com
    - name: Referer     # can be overwritten just fine
      value: https://myapp.example.com
    - name: X-Forwarded-Host     # can NOT be overwritten!
      value: myapp.example.com
```

Other than placing another reverse proxy (eg. nginx) between teleport and myapp, can I somehow make Teleport not add this header to proxied requests?
