### DISCUSSION TITLE
How to connect to gaussdb - mysql service in OTC

### DISCUSSION THREAD

**Discussion by iammuho** [gravitational/teleport#49041] [Q&A]
Hey team,

We're using GaussDB Mysql which is a service of the OTC (open telecom cloud). There is no way to import the certificates to the gaussdb (for mutualtls) and if I make the tls mode as `inscure` , it throws:

```
ERROR 1105 (HY000): Database cannot validate client certificate generated by database service: io.ReadFull(header) failed. err remote error: tls: unknown certificate authority: connection was bad.
```

My kube agent:

```
  databases:
  - name: gaussdb-prod
    uri: 10.0.40.230:3306
    protocol: mysql
    tls:
      mode: insecure
    static_labels:
      env: prod
      engine: gaussdb
```

and I'm connecting as:

```
tsh db connect gaussdb-prod --insecure ## also without --insecure
```

Error:

```
ERROR 1105 (HY000): Database cannot validate client certificate generated by database service: io.ReadFull(header) failed. err remote error: tls: unknown certificate authority: connection was bad.
```

Is there any way to create a connection to the gaussdb from teleport? My kubernetes appications etc can connect .
