### DISCUSSION TITLE
Allow more "localhost" hostnames for client redirect URLs for SSO logins

### DISCUSSION THREAD

**Discussion by zzJinux** [gravitational/teleport#49112] [Q&A]
Since https://github.com/gravitational/teleport/pull/41833, `localhost`, `127.0.0.1`, and `::1` are the only `http:` scheme hostnames allowed for client redirect URLs. Please consider allowing more:
- All addresses in the 127/8 block, which are guaranteed to be loopback by the Internet Standard.
- `*.localhost` domains, which can't be registered in the Internet DNS.

I use IP addresses other than `127.0.0.1` in the `127/8` block and add `*.localhost` entries to `/etc/hosts` to easily manage many local addresses.

I believe there is no security concern to consider since these hostnames are as safe as `127.0.0.1` and `localhost`.

**Comment by webvictim** [comment]
I haven't tested this, but I _think_ you can actually override the allowed list of hostnames/IPs using these hidden settings in your connector:

```yaml
spec:
  ...
  client_redirect_settings:
    allowed_https_hostnames:
      - "*.localhost"
    insecure_allowed_cidr_ranges:
      - "127.0.0.1/8"
```

Docs: https://goteleport.com/docs/admin-guides/access-controls/sso/sso/#changing-callback-address
