### DISCUSSION TITLE
Unable to set custom Teleport node names for EC2 instances auto-enrolled via SSM in Teleport Cloud

### DISCUSSION THREAD

**Discussion by spiffaz** [gravitational/teleport#49416] [Q&A]
I am using Teleport Cloud with EC2 Auto Enrollment via SSM across multiple AWS accounts. I need to set custom node names using AWS tags instead of default EC2 hostnames. Currently, the only known method is manually changing each EC2 hostname, which is impractical at scale.

Environment:
Teleport Cloud (no direct access to teleport.yaml)
EC2 Auto Enrollment via SSM
50+ AWS Organization accounts

Request:
I need guidance on configuring Teleport to use a specific AWS tag as the node name for EC2 instances enrolled through SSM, or alternative solutions for custom node naming at scale.

**Comment by webvictim** [comment]
The `TeleportHostname` tag should override the displayed hostname: https://goteleport.com/docs/admin-guides/management/guides/ec2-tags/

**Reply by spiffaz** [reply]
Thank you @webvictim , I have added the tag and restarted the Teleport process and the tag shows up as a label, however, it does not update the hostname displayed on Teleport. Please see a screenshot below:

<img width="884" alt="Screenshot 2024-11-27 at 10 36 55" src="https://github.com/user-attachments/assets/99f5e269-8b15-41ec-b3bf-4651fbc2d397">

I went a step further to enable instance metadata as described in the guide and the experience is the same.

**Reply by webvictim** [reply]
Can you share the `/etc/teleport.yaml` config file from this specific node, please?

Redact any tokens which are shown.

**Reply by spiffaz** [reply]
Hi @webvictim , here's the file

```
version: v3
teleport:
  nodename: ip-xx-xx-xx-xx.region.compute.internal
  data_dir: /var/lib/teleport
  join_params:
    token_name: xxxxxxxxx
    method: iam
  proxy_server: xxxxxxxxx.teleport.sh:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.dev/account-id: "xxxxxxxxx"
    teleport.dev/instance-id: i-02e0960a83b61f71d
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```
