### DISCUSSION TITLE
Does the auto-provisioning users in Postgres grant permissions on sequences and materialized views?

### DISCUSSION THREAD

**Discussion by Ezzahhh** [gravitational/teleport#49581] [Q&A]
Hi,

Based on my reading of the code, I don't believe materialized views or sequences are available to grant to auto-provisioned users when using `db_permissions`. This means the only way to grant these kind of permissions is to use the `db_roles` and manage the roles in each database separately?

Thank you!

**Comment by stevenGravy** [comment]
Views should be possible. Have you taken a look at https://goteleport.com/docs/enroll-resources/database-access/rbac/ and given it a try?

**Reply by Ezzahhh** [reply]
Thanks for taking a look. This was my `db_permissions`
```
    db_permissions:
    - match:
        object_kind: table
        schema: public
      permissions:
      - SELECT
    - match:
        object_kind: view
        schema: public
      permissions:
      - SELECT
 ```
However, I was unable to select any view or materialized view: `ERROR:  permission denied for view {{view name}}`. The select on regular tables seemed to work fine though.
