### DISCUSSION TITLE
Is it possible to use AWS RDS auto-discovery and user auto-provisioning features together?

### DISCUSSION THREAD

**Discussion by computerphilosopher** [gravitational/teleport#50564] [Q&A]
Hello,

I’ve been using AWS RDS with the auto-discovery feature enabled. As the number of team members has increased, I now want to use the user auto-provisioning feature as well. My current configuration is as follows:

```yaml
db_service:
  enabled: true
  aws:
  - types: ["rds"]
    regions:
    - "{{my-region}}"
    tags:
      "*": "*"
```

I found out that the admin_user property is required for enabling the auto-provisioning feature. However, according to the reference documentation, this property only applies to databases configured with static settings.

https://goteleport.com/docs/reference/config/#database-service

Does this mean it’s impossible to use both RDS discovery and user auto-provisioning features simultaneously?
