### DISCUSSION TITLE
Proxied web services through Teleport suddenly stopped working.

### DISCUSSION THREAD

**Discussion by llek1000** [gravitational/teleport#50565] [Q&A] [answered]
Edit: As @stevenGravy said, this issue seems to be related to v17.1.0+ and was reported in #50556 

Hello, I have a problem where I can no longer access web services that are proxied as "Application" through Teleport. These services were working for the past year or more I've had this set up, and it stopped working kind of randomly, although I suspect this was after some kind of an update - I was not able to track down the specific update that caused this. Oh, and creating a proxy connection using the Teleport Connect App on windows works fine.
Accessing these apps now results in this error:
`Unable to access "de-fal1-pxm-gui.teleport.domain.com". This may happen if your Teleport Proxy is using untrusted or self-signed certificate. Please ensure Teleport Proxy service uses valid certificate or access the application domain directly (https://de-fal1-pxm-gui.teleport.domain.com) and accept the certificate exception from your browser.`

First of all I have a DNS SSL certificate for teleport.domain.com and *.teleport.domain.com in one and I am using this certificate both in a nginx reverse proxy and in Teleport itself (I am attaching the config).
I am running Teleport v17.1.1. on all nodes.

Now as this error suggests, I tried going directly to https://de-fal1-pxm-gui.teleport.domain.com - this just resulted in a redirect back to teleport, and then back to the error message. I also tried a different browser and private windows in both browsers. (This is through the nginx proxy)

I also tried to run it without the nginx proxy, just to rule out possible issues with the proxy - while trying in a chromium-based browser, I got the exact same error. However when I tried Firefox, I got this instead when directly trying to access https://de-fal1-pxm-gui.teleport.domain.com:
`MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING`

I tried regenerating the SSL certificates, I tried separate certificates for teleport.domain.com and *.teleport.domain.com. I tried running Teleport without the certificates specified in the config. I am kind of out of ideas at this point, so I am turning to the community. Please excuse me for any stupid mistakes I might've made, I've been trying to troubleshoot this for a while now.

Here's my Teleport config:
```
version: v3
teleport:
  nodename: de-fra3
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.domain.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.domain.com:443
  https_keypairs:
  - key_file: /opt/tls/certbot/live/teleport.domain.com/privkey.pem
    cert_file: /opt/tls/certbot/live/teleport.domain.com/fullchain.pem
  https_keypairs_reload_interval: 3600s
  acme: {}
```

This issue does not seem to generate errors in the log file.

Please, if you have any idea on what might be happening here let me know.
Thank you!
