### DISCUSSION TITLE
Invalid token while adding new resource

### DISCUSSION THREAD

**Discussion by gitmanesh** [gravitational/teleport#50590] [Q&A]
I have setup goteleport on my local server. when i add my first resource im getting error expired or invalid token.
![image](https://github.com/user-attachments/assets/5e7d9a20-f595-4061-a3af-6958203d71a2)

**Comment by zmb3** [comment]
I'd check the system clock on both this machine and your auth server.

**Reply by gitmanesh** [reply]
![image](https://github.com/user-attachments/assets/d458667c-8fa9-489b-8401-a28dda3be8fb)

Both the server and client machine dates are same.

**Reply by zmb3** [reply]
Likely an issue due to untrusted certificates.

The next step would be to `check log for further details` - they're likely at `/var/lib/teleport/`.

**Reply by stevenGravy** [reply]
This doesn't appear to have a public address assigned in the proxy service conig or is using an IP. As Zmb3 mentioned the certificate needs trusting. I would make sure that a curl call `curl https://<proxy public address>:3080` works cleanly.

**Reply by webvictim** [reply]
You can try this, but I'm not sure it'll work:

```yaml
proxy_service:
  enabled: true
  public_addr: 192.168.0.59:3080
```

You're still going to need certificates configuring at some point.

I would look at setting up a DNS record (like `teleport.example.com`) to point to the server's IP (`192.168.0.59`), then setting that as the public address instead:

```yaml
proxy_service:
  enabled: true
  public_addr: teleport.example.com:3080
```
