### DISCUSSION TITLE
Unable to access console in the UI using Teleport Community (Teleport v16.4.12)

### DISCUSSION THREAD

**Discussion by tmqjom** [gravitational/teleport#50706] [Q&A]
I deployed Teleport following the official high-availability guide: [Teleport High Availability Deployment](https://goteleport.com/docs/admin-guides/deploy-a-cluster/high-availability/). Note that I am only using ETCD.

The deployment went smoothly, except for an issue accessing the resource console.

Here are some relevant screenshots:

![image](https://github.com/user-attachments/assets/621c302f-6473-41b4-ab42-440717793095)
![image](https://github.com/user-attachments/assets/4e462755-03b4-497d-9962-02ae5817a1fa)

Issue:
Every time I try to access the web UI console, I encounter the following log error:
`Jan 02 18:33:23 teleport teleport[604338]: 2025-01-02T18:33:23Z INFO  http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:88)`

Here is my `/etc/teleport.yaml` configuration:
```
teleport configuration:
/etc/teleport.yaml
version: v3
teleport:
  nodename: "primary-teleport"
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
  storage:
    type: etcd
    peers: ["https://<etcd-ip-1>:2379", "https://<etcd-ip-2>:2379", "https://<etcd-ip-3>:2379"]
    tls_cert_file: /var/lib/teleport/etcd-client/teleport-etcd.crt
    tls_key_file: /var/lib/teleport/etcd-client/teleport-etcd.key
    tls_ca_file: /var/lib/teleport/etcd-client/ca.crt
    prefix: /teleport/
    insecure: false

auth_service:
  enabled: true
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: otp

ssh_service:
  enabled: true
  listen_addr: 0.0.0.0:3022

proxy_service:
  enabled: true
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: "<domain>:443"
```
