### DISCUSSION TITLE
Teleport Proxy and Auth Service Migration

### DISCUSSION THREAD

**Discussion by Arrizki16** [gravitational/teleport#51486] [Q&A] [answered]
Hi, I need help!

I am trying to move my proxy and auth service from an old server to a new server in the same region. I transferred the teleport data from my old server located at `var/lib/teleport` to the new server. This included roles, users, nodes, apps, database resources and session or events log. I also ensured that the configuration file `/etc/teleport.yaml` is set up exactly the same on the new server.

However, after the migration, all users are unable to log in, receiving the error message: "User Message: invalid username, password, or second factor." Additionally, the resources seem to be unregistered. What should I do? Thanks

I must create a new user and reset all users authentication to solve this issue temporary

**Comment by stevenGravy** [comment]
This sounds like the backend was not completely moved. Please share how you configured the auth service and any storage, was there any sep backend storage.

**Reply by Arrizki16** [reply]
Hi, heres my proxy and auth service yaml configuration, nothing special. the `/var/lib/teleport` was restored from old server.

```
version: v3
teleport:
  nodename: teleport-dev
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: xxx.tubestream.dev
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: xxx.tubestream.dev:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: deka.julian@inosoft.id
```


ssh and db node yaml configuration
```
version: v3
teleport:
  nodename: mititest
  data_dir: /var/lib/teleport
  join_params:
    token_name: c1e3xxx
    method: token
  proxy_server: xxx.tubestream.dev:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:4980xxx
  diag_addr: ""
db_service:
  enabled: true
  databases:
  - name: mititest-db
    description: mongo db database for mititest server.
    protocol: "mongodb"
    uri: "mongodb://localhost:27017/"
    static_labels:
      env: development
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: xxx
    dynamic/env: development
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```
