### DISCUSSION TITLE
Cant connect Linux Clients to Teleport

### DISCUSSION THREAD

**Discussion by Skyfay** [gravitational/teleport#52048] [Q&A] [answered]
I have installed Teleport and am now trying to connect a Debian machine. I have installed the client but the Teleport instance does not recognize the client.

<img width="804" alt="image" src="https://github.com/user-attachments/assets/3abaf3ba-5ca7-4a77-9047-417771b4dc83" />

Teleport is behind a reverse proxy. I have tried it both through Cloudflare Tunnels and through the Nginx reverse proxy, but it doesn't work with either.

Here my server config:
```yaml
---
version: v2
teleport:
  nodename: skyt81
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text

auth_service:
  enabled: true
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: your-server-url
  
ssh_service:
  enabled: true
  labels:
    ressource: vm

proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:3080
  # -- (Optional) when using reverse proxy
  public_addr: ['teleport.myserver.me:443']
  https_keypairs: []
  acme: {}

app_service:
  enabled: false
  # -- (Optional) App Service
  # enabled: true
```

Here is my Client Config (Auto generated):
```yaml
version: v3
teleport:
  nodename: skyv26
  data_dir: /var/lib/teleport
  join_params:
    token_name: 68cc5b7xxxxxxxxxxxx
    method: token
  proxy_server: teleport.myserver.me:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:41459b06460db9cxxxxxxxxx
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: 55122314-2f74-4143-ba11-e86bb2a3b445
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```

Here is the Client Status:
<img width="1823" alt="image" src="https://github.com/user-attachments/assets/44548814-3265-4f3c-8265-57aa9f3a4be5" />

And here are the server logs when trying to connect the agent:
```
2025-02-12T07:23:17.161Z INFO  emitting audit event event_type:cert.create fields:map[cert_type:user cluster_name:your-server-url code:TC000I ei:0 event:cert.create identity:map[client_ip:10.90.10.20 expires:2025-02-12T19:23:17.16066234Z logins:[-teleport-nologin-a64ff0f6-1ead-4acb-9d23-f1c7e249008e -teleport-internal-join] prev_identity_expires:0001-01-01T00:00:00Z private_key_policy:none roles:[editor] route_to_cluster:your-server-url teleport_cluster:your-server-url traits:map[aws_role_arns:<nil> azure_identities:<nil> db_names:<nil> db_roles:<nil> db_users:<nil> gcp_service_accounts:<nil> host_user_gid:[] host_user_uid:[] kubernetes_groups:<nil> kubernetes_users:<nil> logins:<nil> windows_logins:<nil>] user:Skyfay] time:2025-02-12T07:23:17.161Z trace.component:audit uid:eaec379a-0728-4951-9e70-994feb6f0aa1 user_agent:grpc-go/1.66.3] events/emitter.go:287
2025-02-12T07:23:35.838Z INFO  emitting audit event event_type:join_token.create fields:map[cluster_name:your-server-url code:TJT00I ei:0 event:join_token.create expires:2025-02-12T11:23:35.834921298Z join_method:token name:************************0eb4f843 roles:[App] time:2025-02-12T07:23:35.838Z trace.component:audit uid:197ad057-1d9b-49b9-bd87-03e45e15718d updated_by:Skyfay user:Skyfay user_kind:1] events/emitter.go:287
2025-02-12T07:23:54.364Z INFO  emitting audit event event_type:join_token.create fields:map[cluster_name:your-server-url code:TJT00I ei:0 event:join_token.create expires:2025-02-12T11:23:54.36111282Z join_method:token name:************************5523fad2 roles:[Node] time:2025-02-12T07:23:54.365Z trace.component:audit uid:03b8ddfd-2fe4-4497-8407-8de0c2f94eae updated_by:Skyfay user:Skyfay user_kind:1] events/emitter.go:287
2025-02-12T07:27:15.963Z INFO [AUTH]      Instance "skyv26" [2cfe8b6e-7766-4484-9346-b17f3c2adcc2] has joined the cluster. role=Instance, systemRoles=[Node] auth/join.go:510
2025-02-12T07:27:15.963Z INFO  emitting audit event event_type:instance.join fields:map[addr.remote:10.90.10.20 cluster_name:your-server-url code:TJ002I ei:0 event:instance.join host_id:2cfe8b6e-7766-4484-9346-b17f3c2adcc2 method:token node_name:skyv26 role:Instance success:true time:2025-02-12T07:27:15.963Z token_expires:2025-02-12T11:23:54.36111282Z token_name:************************5523fad2 trace.component:audit uid:11dc685f-695c-4d20-9a8d-7bd5a62dbb64] events/emitter.go:287
2025-02-12T07:27:15.978Z INFO [AUTH]      Instance "skyv26" [2cfe8b6e-7766-4484-9346-b17f3c2adcc2] has joined the cluster. role=Node auth/join.go:512
2025-02-12T07:27:15.978Z INFO  emitting audit event event_type:instance.join fields:map[addr.remote:10.90.10.20 cluster_name:your-server-url code:TJ002I ei:0 event:instance.join host_id:2cfe8b6e-7766-4484-9346-b17f3c2adcc2 method:token node_name:skyv26 role:Node success:true time:2025-02-12T07:27:15.979Z token_expires:2025-02-12T11:23:54.36111282Z token_name:************************5523fad2 trace.component:audit uid:6d1c4297-9c8e-49ea-9125-da8d4c0f202d] events/emitter.go:287
2025-02-12T07:28:12.244Z INFO [WEB]       Pinging auth server for features web/features.go:65
2025-02-12T07:28:12.245Z INFO [WEB]       Done updating proxy features features:Kubernetes:true App:true DB:true Desktop:true DeviceTrust:<> AccessRequests:<> AccessList:<> AccessMonitoring:<> Policy:<> SupportType:SUPPORT_TYPE_FREE JoinActiveSessions:true entitlements:<key:"AccessLists" value:<> > entitlements:<key:"AccessMonitoring" value:<> > entitlements:<key:"AccessRequests" value:<> > entitlements:<key:"App" value:<enabled:true > > entitlements:<key:"CloudAuditLogRetention" value:<> > entitlements:<key:"DB" value:<enabled:true > > entitlements:<key:"Desktop" value:<enabled:true > > entitlements:<key:"DeviceTrust" value:<> > entitlements:<key:"ExternalAuditStorage" value:<> > entitlements:<key:"FeatureHiding" value:<> > entitlements:<key:"HSM" value:<> > entitlements:<key:"Identity" value:<> > entitlements:<key:"JoinActiveSessions" value:<enabled:true > > entitlements:<key:"K8s" value:<enabled:true > > entitlements:<key:"LicenseAutoUpdate" value:<> > entitlements:<key:"MobileDeviceManagement" value:<> > entitlements:<key:"OIDC" value:<> > entitlements:<key:"OktaSCIM" value:<> > entitlements:<key:"OktaUserSync" value:<> > entitlements:<key:"Policy" value:<> > entitlements:<key:"SAML" value:<> > entitlements:<key:"SessionLocks" value:<> > entitlements:<key:"UpsellAlert" value:<> > entitlements:<key:"UsageReporting" value:<> >  web/features.go:73
```

I hope someone can help me with that :)

**Comment by stevenGravy** [comment]
typically the issue is that it's not allowing multiplex traffic to go through. This likely only allows https traffic.   Please see https://goteleport.com/docs/reference/architecture/tls-routing/ for a description of the traffic needed.

**Reply by stevenGravy** [reply]
There are some similar asks in discussion. Please take a search for nginx and similar setups.

**Reply by Skyfay** [reply]
Yeah i tried this for example: https://github.com/gravitational/teleport/discussions/26445
But no way to get it working. The agents can't connect no matter what I try. 
I don't quite understand what needs to be configured on the web server / reverse proxy for it to work with Multiplex. The documentation doesn't have any corresponding information either.

**Reply by webvictim** [reply]
Can you turn the logs on your Teleport SSH agent up to `DEBUG` level and restart Teleport with `systemctl restart teleport`?

```yaml
teleport:
  log:
    severity: DEBUG
```

Teleport does work behind Cloudflare, as discussed here: https://github.com/gravitational/teleport/discussions/50346

The docs on what is required for multiplexing to work behind a layer 7 LB/reverse proxy are here: https://goteleport.com/docs/reference/architecture/tls-routing/#working-with-layer-7-load-balancers-or-reverse-proxies

**Reply by Skyfay** [reply]
> Can you turn the logs on your Teleport SSH agent up to `DEBUG` level and restart Teleport with `systemctl restart teleport`?

Here are the logs from the agent with DEBUG on: https://skypaste.ch/?5db8b58ff3f3f2e8#BNio45tDQUJENocAELCs1qdRSaF5d8RyvdMsrc2Ux8dS

**Reply by webvictim** [reply]
Your logs look fine - it seems the server has connected without a problem.

If you run `tctl nodes ls` against the Teleport container, do you see the node listed?

If you open a new tab to look at the Teleport web UI, can you see the node listed there?

**Reply by Skyfay** [reply]
> If you run `tctl nodes ls` against the Teleport container, do you see the node listed?

Yeah this is the output:
```
Host   UUID                Public Address Labels       Version 
------ ------------------- -------------- ------------ ------- 
skyh80 23575f94-770e-49...                ressource=vm 17.2.1  
skyt81 29ed728c-daaf-4d... 127.0.0.1:3022 ressource=vm 17.2.1  
hetv26 abb8939d-52f6-44...                             17.2.1  
```



> If you open a new tab to look at the Teleport web UI, can you see the node listed there?

No i can't find any node there.

**Reply by webvictim** [reply]
OK, this looks like a Teleport RBAC/permissions problem rather than a connectivity problem.

Can you take a screenshot of your user entry in the web UI (under Access -> Users) which shows the roles that your user has assigned, and then share this along with the output of `tctl get roles`, please?

**Reply by Skyfay** [reply]
> OK, this looks like a Teleport RBAC/permissions problem rather than a connectivity problem.
> 
> Can you take a screenshot of your user entry in the web UI (under Access -> Users) which shows the roles that your user has assigned, and then share this along with the output of `tctl get roles`, please?

<img width="1814" alt="image" src="https://github.com/user-attachments/assets/e6f3da6c-76c0-432a-b8eb-9ed02da501b7" />

```
kind: role
metadata:
  description: Access cluster resources
  labels:
    teleport.internal/resource-type: preset
  name: access
  revision: fe2b71e6-d86c-4235-a2b4-e83ee5355005
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - '{{internal.aws_role_arns}}'
    azure_identities:
    - '{{internal.azure_identities}}'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_roles:
    - '{{internal.db_roles}}'
    db_service_labels:
      '*': '*'
    db_users:
    - '{{internal.db_users}}'
    gcp_service_accounts:
    - '{{internal.gcp_service_accounts}}'
    github_permissions:
    - orgs:
      - '{{internal.github_orgs}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: '*'
      verbs:
      - '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - cluster_maintenance_config
      verbs:
      - list
      - read
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      desktop: true
    ssh_file_copy: true
    ssh_port_forwarding:
      local:
        enabled: true
      remote:
        enabled: true
version: v7
---
kind: role
metadata:
  description: Review cluster events and replay sessions
  labels:
    teleport.internal/resource-type: preset
  name: auditor
  revision: 17f4fe0c-55b8-4fb1-929b-a0bcb4088c20
spec:
  allow:
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session_tracker
      verbs:
      - list
      - read
    - resources:
      - cluster_alert
      verbs:
      - list
      - read
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - security_report
      verbs:
      - list
      - read
      - use
    - resources:
      - audit_query
      verbs:
      - list
      - read
      - use
    - resources:
      - bot_instance
      verbs:
      - list
      - read
    - resources:
      - notification
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      desktop: false
    ssh_file_copy: true
version: v7
---
kind: role
metadata:
  description: Edit cluster configuration
  labels:
    teleport.internal/resource-type: preset
  name: editor
  revision: a6f85b01-6670-4589-b784-36302dbe04db
spec:
  allow:
    rules:
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - bot
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - crown_jewel
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db_object_import_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_audit_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_auth_preference
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_name
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_networking_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session_recording_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - external_audit_storage
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - ui_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - remote_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - connection_diagnostic
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - database_certificate
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - installer
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - device
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - create_enroll_token
      - enroll
    - resources:
      - db_service
      verbs:
      - list
      - read
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - login_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml_idp_service_provider
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - user_group
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - plugin
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - okta_import_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - okta_assignment
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - lock
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - integration
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - billing
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_alert
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - access_list
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - node
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - discovery_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - security_report
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - audit_query
      verbs:
      - list
      - create
      - read
      - update
      - delete
      - use
    - resources:
      - access_graph
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - server_info
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - access_monitoring_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - app_server
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - vnet_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - bot_instance
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - access_graph_settings
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - spiffe_federation
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - notification
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - static_host_user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - user_task
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - aws_identity_center
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - contact
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - workload_identity
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - autoupdate_version
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - autoupdate_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - git_server
      verbs:
      - list
      - create
      - read
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      desktop: false
    ssh_file_copy: true
    ssh_port_forwarding:
      local:
        enabled: true
      remote:
        enabled: true
version: v7
---
kind: role
metadata:
  description: Default Terraform provider role
  labels:
    teleport.internal/resource-type: preset
  name: terraform-provider
  revision: dd1053fc-a4ae-42ca-9e1b-014a5f66a58a
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - access_list
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - app
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_auth_preference
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_maintenance_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_networking_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - device
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - login_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - node
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - okta_import_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session_recording_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - bot
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - installer
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - access_monitoring_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - dynamic_windows_desktop
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - static_host_user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - workload_identity
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - git_server
      verbs:
      - list
      - create
      - read
      - update
      - delete
    windows_desktop_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v7
---
kind: role
metadata:
  description: Issue workload identities
  labels:
    teleport.internal/resource-type: preset
  name: wildcard-workload-identity-issuer
  revision: 94eb1af1-c40e-4f68-9eb3-23d5468295b9
spec:
  allow:
    rules:
    - resources:
      - workload_identity
      verbs:
      - list
      - read
    workload_identity_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v7
```

**Reply by webvictim** [reply, marked as answer]
The `editor` role only grants you the right to edit roles, permissions etc on the cluster - it doesn't grant any user access to servers or resources.

You should also assign the `access` role to your user (using the "Edit" link next to the user) then log out and back in again. This should then show resources you can access.

**Reply by Skyfay** [reply]
Yeah i can see them now. Thank you! It now says if i click on Connect (Search Logins...). Shouldn't this work directly since the client is installed?

**Reply by webvictim** [reply]
You need to add a login that you can use on the servers, then log out and log back in again: https://github.com/gravitational/teleport/discussions/11820#discussioncomment-8123577

You can also edit this under the "Users" section in the web UI (same place you added the `access` role)

**Reply by Skyfay** [reply]
Thank you, I somehow didn't understand it all although I have read up on it. Is there a guide for beginners somewhere that covers the most important things?

**Reply by webvictim** [reply]
Glad things are working for you now!

This guide is a good starter for how to get a server enrolled and access set up to it: https://goteleport.com/docs/enroll-resources/server-access/getting-started/

There is also a getting started guide for Teleport RBAC here: https://goteleport.com/docs/admin-guides/access-controls/getting-started/

**Comment by webvictim** [comment]
One other thing to check: have you customised the RBAC on your Teleport server at all? Do you have any `deny` rules in any of your roles? This can prevent the wizard from being able to "see" the server when it's added.

**Reply by Skyfay** [reply]
> One other thing to check: have you customised the RBAC on your Teleport server at all? Do you have any `deny` rules in any of your roles? This can prevent the wizard from being able to "see" the server when it's added.

The config files above is everything i did. I'm using Docker to deploy the Teleport Server:
```yaml
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:17.2.1
    container_name: teleport
    restart: always
    volumes:
      - /docker/teleport/data:/var/lib/teleport
      - /docker/teleport/config:/etc/teleport
    ports:
      - "3080:3080"
```
