### DISCUSSION TITLE
Create a new db

### DISCUSSION THREAD

**Discussion by DanielCastronovo** [gravitational/teleport#52570] [General]
Expected behavior:
DB created

Current behavior:
`creating resources of type "" is not supported`

Bug details:
- Teleport version : 
17.2.8
- Teleport CLI version : 
17.2.8
- Recreation steps
Create db.yaml file :
```
#
# Teleport database agent configuration file.
# Configuration reference: https://goteleport.com/docs/reference/agent-services/database-access-reference/configuration/
#
version: v3
teleport:
  nodename: "xxxxxxx-xxxxxxx"
  data_dir: "/var/lib/teleport"
  proxy_server: "https://xxxxxxxxxxxx:443"
  auth_token: "xxxxxxxxxxxxxxxxxx"
db_service:
  enabled: "yes"

  resources:
  - labels:
      "*": "*"
    aws:
      assume_role_arn: "arn:aws:iam::XXXXX:role/XXXXXXXXX-XXXXXXXXXXXX"

  aws:
  - types: ["rds", "rdsproxy","redshift", "redshift-serverless", "elasticache", "memorydb", "opensearch"]
    regions: ["eu-west-2"]
          assume_role_arn: "arn:aws:iam::XXXXX:role/XXXXXXXXX-XXXXXXXXXXXX"
    tags:
      "*": "*"
  databases:
  - name: "elastitest"
    protocol: "redis"
    uri: "XXXXXXX:6379"
    tls:
      mode: verify-full
    aws:
      region: "eu-west-2"
      assume_role_arn: "arn:aws:iam::XXXXX:role/XXXXXXXXX-XXXXXXXXXXXX"
      elasticache:
        replication_group_id: "elasticache-replication-group-1"
        transit_encryption_enabled: true
        user_group_ids:
        - teleport-groups

auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
```

`tctl create -f db.yaml `

- Debug logs
ERROR REPORT:
Original Error: *trace.BadParameterError creating resources of type &#34;&#34; is not supported
Stack Trace:
	github.com/gravitational/teleport/tool/tctl/common/resource_command.go:387 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create
	github.com/gravitational/teleport/tool/tctl/common/resource_command.go:270 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
	github.com/gravitational/teleport/tool/tctl/common/tctl.go:171 github.com/gravitational/teleport/tool/tctl/common.TryRun
	github.com/gravitational/teleport/tool/tctl/common/tctl.go:80 github.com/gravitational/teleport/tool/tctl/common.Run
	github.com/gravitational/teleport/tool/tctl/main.go:32 main.main
	runtime/proc.go:272 runtime.main
	runtime/asm_amd64.s:1700 runtime.goexit
User Message: creating resources of type &#34;&#34; is not supported
