### DISCUSSION TITLE
Teleport Connection is Broken Randomly 10-15 times a day on AWS and on-premise

### DISCUSSION THREAD

**Discussion by gokhankocak** [gravitational/teleport#52676] [Q&A]
Hello,

We are new to teleport and we installed the following version:
Teleport v16.4.15 git:v16.4.15-0-ga348834 go1.22.11

Our teleport connection is suddenly lost in a random manner.
We checked the logs but there is no message why the connection is broken.
We installed Teleport server on AWS and on-premise.
We face the same issue in both installations.
Sometimes the connections are broken 10-15 times a day and it is very annoying.

We added some parameters to keep connections alive (see below) but they did not help much.
What do you suggest to prevent sudden and random connection cuts?

We used the following configuration in our teleport server:
```
version: v3
teleport:
  nodename: x
  data_dir: /var/lib/teleport
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO
    format:
      output: json
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: x:3025
  cluster_name: x
  proxy_listener_mode: multiplex
  client_idle_timeout: 8h
  client_idle_timeout_message: "Client Idle Timeout"
  web_idle_timeout: 8h
  disconnect_expired_cert: no
  keep_alive_interval: 3m
  keep_alive_count_max: 5
  message_of_the_day: "Welcome to teleport"
  authentication:
    second_factor: otp
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  web_listen_addr: x:443
  public_addr: x:443
  https_keypairs:
  - key_file: /var/lib/teleport/privkey.pem
    cert_file: /var/lib/teleport/fullchain.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```
