### DISCUSSION TITLE
EC2 Instances Discovery Config State Stuck in DISCOVERY_CONFIG_STATE_UNSPECIFIED Without Documentation

### DISCUSSION THREAD

**Discussion by spiffaz** [gravitational/teleport#52881] [Q&A]
I'm encountering an issue with several of my AWS EC2 discovery configurations where their status is currently set to DISCOVERY_CONFIG_STATE_UNSPECIFIED. This is preventing proper discovery and management of these instances through Teleport.
When reviewing the discovery configurations through the Teleport CLI, I can see that affected instances are in this state rather than in an expected state of DISCOVERY_CONFIG_STATE_SYNCING.

Impact
Unable to properly discover and manage several critical EC2 instances
Cannot determine why these instances are in this state
No clear path forward to resolve the issue

Environment Information
Teleport Version: 17.2.9
Configuration: Using IAM roles for discovery as shown in sample

Requested Resolution
1. Please explain what DISCOVERY_CONFIG_STATE_UNSPECIFIED means and why my configs are in this state
2. Provide documentation on how to fix this issue
3. If this is a bug, please provide a workaround until it's fixed

Thank you for your help in resolving this urgent issue.

```
kind: discovery_config
metadata:
  expires: "0001-01-01T00:00:00Z"
  name: ec2-auto-discovery-accountname-accountid
  revision: 8797bf77-79ca-4610-bd9a-852a05bc2121
spec:
  aws:
  - install:
      enroll_mode: 1
      install_teleport: true
      join_method: iam
      join_token: aws-discovery-iam-token-ec2-accountid
      script_name: default-installer
      sshd_config: /etc/ssh/sshd_config
    integration: accountname
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - af-south-1
    - ap-east-1
    - ap-south-1
    - ap-south-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - ap-southeast-4
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ca-central-1
    - eu-central-1
    - eu-central-2
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - eu-south-1
    - eu-south-2
    - eu-north-1
    - me-central-1
    - me-south-1
    - sa-east-1
    ssm:
      document_name: TeleportDiscoveryInstaller
    tags:
      '*': '*'
    types:
    - ec2
  discovery_group: cloud-discovery-group
status:
  discovered_resources: 0
  last_sync_time: "0001-01-01T00:00:00Z"
  state: DISCOVERY_CONFIG_STATE_UNSPECIFIED
version: v1
```
