### DISCUSSION TITLE
tsh login error

### DISCUSSION THREAD

**Discussion by sauravpatar** [gravitational/teleport#53396] [Q&A]
Hi,

I am currently using Teleport **v15.4.30** and encountering an issue with the `tsh login` CLI command. Below are the details of the problem:

**Command Executed**: `tsh login --proxy=<DNS>:443 --auth=local --user=<username>`

The command prompts for credentials and an OTP as expected. However, after providing the required input, I encounter the following error:

`
ERROR REPORT:
Original Error: trace.aggregate connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Canceled desc = context canceled&#34;
Stack Trace:
	github.com/gravitational/teleport/lib/client/api.go:4497 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToRootCluster
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:2019 github.com/gravitational/teleport/tool/tsh/common.onLogin
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1472 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:623 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
	runtime/proc.go:272 runtime.main
	runtime/asm_arm64.s:1223 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Canceled desc = context canceled&#34;
`

I would appreciate any guidance on resolving this issue.

Thank you!

**Comment by webvictim** [comment]
How is your Teleport cluster deployed? To me, this looks like your local machine is unable to route traffic to Teleport correctly, perhaps due to a transparent proxy or some other kind of endpoint management/load balancer in front of your cluster.

Can you also please share the output of `tsh login --debug --proxy=<DNS>:443 --auth=local --user=<username>`?

**Reply by sauravpatar** [reply]
We are currently operating our teleport server with two network load balancers `proxy_listener_mode: separate`, one of which is internal and the other public facing. The server has been functioning seamlessly with teleport version 10, and we intend to upgrade it to version 15. However, we encounter difficulties during the upgrade process when attempting to connect to the server via TSH or TeleportConnect (the WebUI interface operates without any issues).
For your reference, I have provided the details of the teleport.yaml file below.

```
version: v2
teleport:
  nodename: teleport.example.com
  advertise_ip: 127.0.0.1
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO
  data_dir: /var/lib/teleport
  storage:
    type: dynamodb
    region: <region>
    table_name: test_table
    audit_events_uri: dynamodb://test-events
    audit_sessions_uri: s3://test/records

auth_service:
  enabled: yes
  proxy_protocol: off
  proxy_listener_mode: separate
  keep_alive_interval: 5m
  ssh_dial_timeout: 5m
  keep_alive_count_max: 3
  listen_addr: 0.0.0.0:3025
  authentication:
    type: local
    second_factor: on
    u2f:
     app_id: https://teleport.example.com
     facets:
       - https://teleport.example.com
  license_file: /var/lib/teleport/license.pem
  tokens:
  - db:testtoken1
  - node:tesktoken2

proxy_service:
  enabled: yes
  proxy_protocol: off
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:443
  public_addr: ['teleport.example.com:443','teleport-private.example.com:443']
  ssh_public_addr: teleport.example.com:3023
  tunnel_public_addr: teleport-private.example.com:3024
  https_keypairs:
    - cert_file: /var/lib/teleport/fullchain.pem
      key_file: /var/lib/teleport/privkey.pem
  mysql_listen_addr: 0.0.0.0:3306
  mysql_public_addr: ['teleport.example.com:3306','teleport-private.example.com:3306']
```

**Reply by webvictim** [reply]
Given that you're already using NLBs and terminating TLS on Teleport itself (with `https_keypairs`) I'd suggest that you could switch to `proxy_listener_mode: multiplex` and simplify your config a bit:

```yaml
version: v3
teleport:
  nodename: teleport.example.com
  advertise_ip: 127.0.0.1
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO
  data_dir: /var/lib/teleport
  storage:
    type: dynamodb
    region: <region>
    table_name: test_table
    audit_events_uri: dynamodb://test-events
    audit_sessions_uri: s3://test/records

auth_service:
  enabled: yes
  proxy_protocol: off
  proxy_listener_mode: multiplex
  keep_alive_interval: 5m
  ssh_dial_timeout: 5m
  keep_alive_count_max: 3
  listen_addr: 0.0.0.0:3025
  authentication:
    type: local
    second_factor: on
    u2f:
     app_id: https://teleport.example.com
     facets:
       - https://teleport.example.com
  license_file: /var/lib/teleport/license.pem
  tokens:
  - db:testtoken1
  - node:tesktoken2

proxy_service:
  enabled: yes
  proxy_protocol: off
  web_listen_addr: 0.0.0.0:443
  public_addr: ['teleport.example.com:443','teleport-private.example.com:443']
  https_keypairs:
    - cert_file: /var/lib/teleport/fullchain.pem
      key_file: /var/lib/teleport/privkey.pem
```
