### DISCUSSION TITLE
Kube App Discovery - teleport.dev/path annotation doesn't seem to work

### DISCUSSION THREAD

**Discussion by iamnoah** [gravitational/teleport#53863] [Q&A] [answered]
Proxy version: 17.4.2
Agent running: public.ecr.aws/gravitational/teleport-distroless:17.4.2
Everything 17.4.2

I have a service that is auto-discovered and includes a path annotation:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    teleport.dev/path: /river
  labels:
    river: ui
    teleport-discovery: enabled
  name: river
spec:
  ports:
  - name: river-ui
    port: 80
    protocol: TCP
    targetPort: 8124
  selector: ...
  type: ClusterIP
```

Discovery works fine, but when I launch it from the UI, it loads / and 404s instead of requesting /river.
