### DISCUSSION TITLE
Different apps with the same public_addr

### DISCUSSION THREAD

**Discussion by issvvv** [gravitational/teleport#54385] [Q&A] [answered]
Hey,

I've already seen discussions that using multiple addresses in the `public_addr` field for a single app doesn't work because Teleport only uses the first one.

Btw, I've encountered a problem where it's not possible to access different apps (with different headers) through the same `public_addr`:

```yaml
...
app_service:
  apps:
    - description: My ReadOnly service
      name: service-ro
      labels:
        cluster: service-ro
      public_addr: service.domain.com
      rewrite:
        headers:
          - 'Authorization: Bearer %JWT_RO%'
    - description: My ReadWrite service
      name: service-rw
      labels:
        cluster: service-rw
      public_addr: service.domain.com
      rewrite:
        headers:
          - 'Authorization: Bearer %JWT_RW%'
```

So, all the time I tried to access the service with RW permissions, I was always granted RO access — possibly because Teleport saw this address first in the configuration for the RO app?

Does the issue actually exist or is this case not covered — and the fact that assigning a different address solved my problem was just a coincidence?
