### DISCUSSION TITLE
Role, multiples logins

### DISCUSSION THREAD

**Discussion by alexei04** [gravitational/teleport#55864] [Q&A] [answered]
Hi all

I have a question about role and logins.
I created a role giving access for multiple ressources, and allowing two different logins (login1, login2).
Some ressources need login1 and others login2.
When the user want to connect to a ressource, the two logins are offered by teleport.
I want the user have only one login displayed for a ressource. How can I set up this ?
Thanks

**Comment by webvictim** [comment, marked as answer]
You would need separate roles to be able to do this, and you'd need to label each server with the login you wanted to use.

Say you have two servers: `server1` which requires the user `ubuntu`, and `server2` which requires the user `nobody` - you'd set up your Teleport SSH service configs like this:

server1:
```yaml
ssh_service:
  enabled: true
  labels:
    username: ubuntu
```

server2:
```yaml
ssh_service:
  enabled: true
  labels:
    username: nobody
```

You'd then make two roles:

```yaml
kind: role
metadata:
  name: username-ubuntu
spec:
  allow:
    logins:
    - ubuntu
    node_labels:
      username: ubuntu
```

```yaml
kind: role
metadata:
  name: username-nobody
spec:
  allow:
    logins:
    - nobody
    node_labels:
      username: nobody
```

Assign both these roles to your Teleport user, then this will then show the correct login against the correct server.
