### DISCUSSION TITLE
oidc keycloak connector - unable to map claims to role for connector

### DISCUSSION THREAD

**Discussion by pankajpandey9** [gravitational/teleport#5843] [Q&A] [answered]
Hi All,

I am getting  error "unable to map claims to role for connector" while using keycloak for oidc connection. I did check the groups and roles in the keycloak and everything seems fine

Teleport image:  quay.io/gravitational/teleport-ent:5.0 on Kubernetes RKE cluster
storage: etcd, session storage: IBM COS bucket (s3)

INFO [AUDIT]     user.login attributes:map[acr:1 at_hash:psFchHF4DrJGRtYttXdBAQ aud:oidc_client auth_time:1.614857615e+09 azp:oidc_client email:_<user.name>@<domain.name>_ email_verified:false exp:1.614857915e+09 family_name:*** given_name:*** group:[offline_access, uma_authorization, ***_admin, user] iat:1.614857615e+09 iss:https://keycloak.<domain.name>/auth/realms/skypad jti:41d054a4-3801-41e0-b789-4ea14fc5fcc4 name:****  preferred_username:<user.name> session_state:18b71d33-47c1-4539-83b4-07da7643b2ef sub:76642bfb-9244-462f-a0fc-366a1e840ee7 typ:ID] code:T1001W ei:0 error:unable to map claims to role for connector: oidc event:user.login message:unable to map claims to role for connector: oidc method:oidc success:false time:2021-03-04T11:33:35.157Z uid:e3ea4039-016f-4619-a3c9-064e688279f8 user: events/emitter.go:318

**Comment by stevenGravy** [comment]
@pankajpandey9 what is your connector setting to map the group to teleport roles?

**Reply by webvictim** [reply]
Yes, please post the connector with secrets (client_id/client_secret etc) redacted out. Please use markdown blocks (```) to preserve formatting,

**Reply by pankajpandey9** [reply]
@webvictim, @stevenGravy  Here is the oidc connector and admins group information:

Also, after using '*' we were able to map all the users to guest group however, none of the Keycloak role (system-admin/any other role) name are mapping. Moreover, almost similar configuration with different hostname works fine.  Please advise
```
kind: oidc
metadata:
  name: oidc
spec:
  claims_to_roles:
  - claim: group
    roles:
    - admin
    - admins
    value: system-admin
  - claim: group
    roles:
    - guest
    value: '*'
  client_id: oidc_client
  client_secret: 
  display: IaaS-Teleport
  issuer_url: https://keycloak.<domain>.internal/auth/realms/skypad
  provider: OIDC
  redirect_url: https://cloud-teleportlb-<domain>.internal/v1/webapi/oidc/callback
version: v2
```

```
kind: role
metadata:
  id: 15
  name: admins
spec:
  allow:
    app_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    logins:
    - <os_user>
    node_labels:
      '*': '*'
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 12h0m0s
    port_forwarding: true
version: v3
```
