### DISCUSSION TITLE
pgAdmin (on Ubuntu) via Application Access

### DISCUSSION THREAD

**Discussion by colinedwardwood** [gravitational/teleport#5952] [Show and tell]
Certain web applications require slight modifications to their configuration to make them work smoothly with Application Access. I discovered pgAdmin is one of those applications.

Here is my example configuration.

## Install pgAdmin
I installed pgAdmin on my Ubuntu 18.04.5 LTS system as follows:
1. Setup the repository
Install the public key for the repository (if not done previously):
`sudo curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add`

2. Create the repository configuration file:
`sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`

3. Install pgAdmin for web mode only: 
`sudo apt install pgadmin4-web`

4. Configure the webserver, if you installed pgadmin4-web:
`sudo /usr/pgadmin4/bin/setup-web.sh`

## Setup Teleport Application Access
On the same node, I installed the Teleport app service.
```
app_service:
  enabled: yes
  apps:
  - name: "pgadmin"
    uri: "http://localhost/pgadmin4"
    public_addr: pgadmin.myteleportserver.com
    rewrite:
      redirect:
        - "localhost"
```

## Handle Redirect Issue
pgAdmin will not render the javascript and will return an error of "The referrer does not match the host" if config changes are not made.

To get around this issue edit the file `/usr/pgadmin4/web/config.py`.

Change the line
```
# Number of values to trust for X-Forwarded-Proto.
PROXY_X_PROTO_COUNT = 1
```
to
```
# Number of values to trust for X-Forwarded-Proto.
PROXY_X_PROTO_COUNT = 2
```

To effect the change, restart apache.
`sudo systemctl restart apache2`

pgAdmin should now be accessible and correctly rendering javascript.
