### DISCUSSION TITLE
Issues setting up Application Access [answered]

### DISCUSSION THREAD

**Discussion by jdmedeiros** [gravitational/teleport#6147] [General]
Start a private window, login and go to applications.
Click on application and it opens a new tab, working perfectly.
Go back to the main application tab, click anywhere and this is what happens:
https://imgur.com/lG27Ij2

**The string did not match the expected pattern.**

The apps config section:

```
  apps:
    -
      name: certsrv1
      uri: "http://vpn.dev.blabla.com"
      public_addr: "vpn.dev.blabla.com"
      labels:
        env: normal
```

Tomorrow at the end of the day I will be presenting Teleport to my colleagues. Hopefully will be able to overcome this with your help. Thanks in advance.

**Comment by benarent** [comment]
Hi @jdmedeiros , this error is showing up on the servers page. Which version of Teleport are you using and can you share your role please.

**Reply by jdmedeiros** [reply]
Roles: https://pastebin.com/WGp0TAej
# teleport version
Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5

Thanks!

**Reply by jdmedeiros** [reply]
Using the `admin` role.

**Reply by benarent** [reply]
Can you add a new user with `sudo tctl users add teleport-admin --roles=editor,access --logins=root,ubuntu,ec2-user`

**Comment by jdmedeiros** [comment]
Did this and when I went to the webpage there was a few more thing there, specifically roles and users, which was nice.
```
[root@vpn ejbca]# tctl users add teleport-admin --roles=editor,access --logins=root,ubuntu,ec2-user
User "teleport-admin" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://vpn.dev.blabla.com:3080/web/invite/xxxxxxxxxx

NOTE: Make sure vpn.dev.blabla.com:3080 points at a Teleport proxy which users can access.
[root@vpn ejbca]# systemctl stop teleport
[root@vpn ejbca]# rm -fr /var/lib/teleport/
[root@vpn ejbca]# systemctl start teleport
[root@vpn ejbca]# 
```
However, it did not work. As long as I do not run an app everything works. As soon as I run an app, the only thing that works are the apps. Every other option gives this error **`"Unexpected token < in JSON at position 0"`** in a red bar and does not show the relevant information. This error occurs regardless of **app_service** being enabled or no. I am going to reinstall in the next hour, so if you need anything else for debugging do let me know. Thank you.

```
app_service:
  enabled: no
  debug_app: true
  apps:
    -
      name: certserver
      uri: "http://vpn.dev.blabla.com"
      public_addr: "vpn.dev.blabla.com"
      labels:
        env: normal
    -
      name: certadmin
      uri: "https://localhost"
      public_addr: "vpn.dev.blabla.com"
      labels:
      env: superadmin
      insecure_skip_verify: true
```
