### DISCUSSION TITLE
TLS handschake error | acme can't get a cert for domain

### DISCUSSION THREAD

**Discussion by dion22** [gravitational/teleport#6496] [Q&A]
### Description

Can anyone help me with the following issue?

I'm also running NGINX on this server. NGINX redirects 1 servername to my Docker container and 1 servername to my vhost directory.
Both servernames used inside NGINX are different subdomeins. When i disable NGINX and restart Teleport i get the same errors.

**What happened**:
Followed instruction:
https://goteleport.com/docs/getting-started/
and for TLS certs
https://goteleport.com/blog/letsencrypt-teleport-ssh/

DNS records: (renamed to teleport.com for this purpose)
A record connect.teleport.com
A record *.connect.teleport.com

**My problem:**
First 20/24 hours everything was working as it should be. Except for this TLS error showing in the server log.
After some time i noticed that the server section on the teleport webpage showed **No Data Available**

Error:
```
ERRO [PROXY:SER] "proxy2021/04/14 10:15:58 http: TLS handshake error from <client_ip>:46010: acme can't get a cert for domain 636f6e6e6563742e616c6c63732e636c6f7564.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: connect.teleport.com\n" utils/cli.go:304
ERRO [PROXY:SER] "proxy2021/04/14 10:15:58 http: TLS handshake error from <client_ip>:46008: acme can't get a cert for domain 636f6e6e6563742e616c6c63732e636c6f7564.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: connect.teleport.com\n" utils/cli.go:304
ERRO [PROXY:SER] "proxy2021/04/14 10:19:17 http: TLS handshake error from <client_ip>:46022: acme can't get a cert for domain 636f6e6e6563742e616c6c63732e636c6f7564.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: connect.teleport.com\n" utils/cli.go:304
ERRO [PROXY:SER] "proxy2021/04/14 10:19:17 http: TLS handshake error from <client_ip>:46020: acme can't get a cert for domain 636f6e6e6563742e616c6c63732e636c6f7564.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: connect.teleport.com\n" utils/cli.go:304
```

Server config:
```
teleport:
  nodename: connect.teleport.com
  data_dir: /var/lib/teleport
  auth_servers:
  - 127.0.0.1:3025
  log:
    output: stderr
    severity: INFO
  ca_pin: sha256:<ca_pin>
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: connect.teleport.com:3025
  cluster_name: connect.teleport.com
ssh_service:
  enabled: "yes"
  labels:
    teleport: server
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: connect.teleport.com:443
  https_keypairs:
    - key_file: /etc/letsencrypt/live/connect.teleport.com/privkey.pem
      cert_file: /etc/letsencrypt/live/connect.teleport.com/fullchain.pem
  acme:
    enabled: "yes"
    email: info@teleport.com
```

node config:
```
teleport:
  nodename: node-100101
  data_dir: /var/lib/teleport
  auth_token: <auth_token>
  ca_pin: sha256:<ca_pin>
  auth_servers:
    - connect.teleport.com:443
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: no
ssh_service:
  enabled: yes
  labels:
    teleport: node
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: no

```

### Server Details
- Teleport version (run `teleport version`): **Teleport v6.1.1 git:v6.1.1-0-geacd474d8 go1.15.5**
- Server OS (e.g. from `/etc/os-release`): **Ubuntu 18.04.5 LTS**

### Client Details
- Tsh version (`tsh version`): **Teleport v6.1.1 git:v6.1.1-0-geacd474d8 go1.15.5**
- Computer OS (e.g. Linux, macOS, Windows): **Ubuntu 20.04.2 LTS**
- Browser version (for UI-related issues): **Chrome**
- Installed via (e.g. apt, yum, brew, website download): **apt**

### Debug Logs
included

[teleport-log.txt](https://github.com/gravitational/teleport/files/6309327/teleport-log.txt)
[teleport-log-client.txt](https://github.com/gravitational/teleport/files/6309328/teleport-log-client.txt)
