### DISCUSSION TITLE
GitHub auth connector additional logins

### DISCUSSION THREAD

**Discussion by chrisdeeming** [gravitational/teleport#7248] [Q&A]
I followed the guide here to create a GitHub auth connector:
https://goteleport.com/docs/admin-guide/#github-oauth-20

It all works and after logging in it creates a user, e.g:

```
> Profile URL:        https://cluster:443
  Logged in as:       chrisdeeming
  Cluster:            cluster
  Roles:              access, admin, editor
  Logins:             chrisdeeming
  Kubernetes:         disabled
  Valid until:        2021-06-10 13:12:35 +0100 BST [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

However, for each user we want to populate `Logins:` with more than just their GitHub username. For our purposes, all users need to access the same, single, account, either in addition to their GitHub username or, preferably, instead of the GitHub username.

Is that possible without adding the login manually to the user after it is registered?

Cheers!

EDIT: Just realised that manually editing the user doesn't work either! What if your user accounts don't match your GitHub username or you have multiple user accounts you need to access? Hopefully I'm just missing something!

EDIT2: The logins have now been added via the relevant role configuration, but I still want to add, for example, `chris` (internal login name) rather than `chrisdeeming` (GitHub login name).

**Comment by ben-z** [comment]
I'd like the same feature where I can specify a lookup table from GitHub usernames to custom logins.

Adding to op's EDIT2, [here's the relevant documentation for setting up a common login for everyone in the GitHub team](https://goteleport.com/docs/access-controls/guides/role-templates/#sso-users).

**Comment by zen** [comment]
Sure, just use role:
```yaml
kind: role
version: v4
metadata:
  name: ssh-all-all # all nodes, all users
spec:
  allow:
    logins: ["root", "ec2-user", "admin", "ubuntu"]
    node_labels:
      "*": "*"
```
Create a team, add users.
Then map the role using GH connector:
```yaml
  teams_to_logins:
    - organization: your-gh-org
      team: your-team
      logins:
        - access
        - ssh-all-all
```
