### DISCUSSION TITLE
Can't connect a node to teleport-cluster

### DISCUSSION THREAD

**Discussion by Aman1994** [gravitational/teleport#7277] [Q&A] [answered]
Hello,
I am trying to use teleport for a while now. Followed `https://goteleport.com/docs/kubernetes-access/ ` to connect clusters to teleport and using them. From the kubernetes point of view i am able to join clusters to my teleport and access them - But I am facing issues while adding nodes/servers to my `teleport cluster` and access those nodes/server.
I have deployed two charts `teleport-cluster` and `teleport-kube-agent`

The yaml file(/etc/teleport/teleport.yaml) inside `teleport-cluster` looks like  -
```
teleport:
  log:
    severity: INFO
    output: stderr
auth_service:
  enabled: true
  cluster_name: teleport.example.com
kubernetes_service:
  enabled: true
  listen_addr: 0.0.0.0:3027
  labels:
proxy_service:
  public_addr: 'teleport.example.com:443'
  kube_listen_addr: 0.0.0.0:3026
  enabled: true
  acme:
    enabled: true
    email: info@hello.com
ssh_service:
  enabled: false
```
And yaml file(/etc/teleport/teleport.yaml) inside `teleport-kube-agent` look like -

```
teleport:
  auth_token: "/etc/teleport-secrets/auth-token"
  auth_servers: ["teleport.example.com:443"]
  log:
    severity: INFO
    output: stderr
kubernetes_service:
  enabled: true
  kube_cluster_name: astroid.earth.com
app_service:
  enabled: false
db_service:
  enabled: false
auth_service:
  enabled: false
ssh_service:
  enabled: false
proxy_service:
  enabled: false
```
Now, with the help of `teleport-kube-agent` being deployed i am able to join cluster `astroid.earth.com` to my teleport and access them. So kubernetes access is working fine.

But now when i am trying to add a node to my `teleport-cluster` its not working.
So, i did

`tctl tokens add --type=node `

And then ran -

```
teleport start \
>    --roles=node \
>    --token=--------------- \
>    --ca-pin=sha256:------------ \
>    --auth-server=teleport.example.com:443
```
on my node which i want to join to my `teleport-cluster` - but i can't see anything in `servers` in webUI of my teleport.
Am i missing something here ?
