### DISCUSSION TITLE
Github Auth Connector Errors: "unable to process callback" or "list of user teams is empty"

### DISCUSSION THREAD

**Discussion by travelton** [gravitational/teleport#7511] [General]
If you are seeing the following error, after attempting to log into Teleport via the Github Auth Connector... Check your Teleport Audit Logs for errors. 

<img src="https://user-images.githubusercontent.com/241714/125086384-317baa80-e091-11eb-8189-95b36cc86f25.jpg" width="50%">

Log in with your local user credentials, and go to the Audit Events tab.

<img src="https://user-images.githubusercontent.com/241714/125086736-84edf880-e091-11eb-869d-dbd585c9fc42.jpg" width="50%">

Review the details of the "SSO Login Failed" event. It may look similar to the following:

```json
{
	"ei": 0,
	"event": "user.login",
	"uid": "xxxxxx-xxxx-xxxx-xxxxx-xxxxx",
	"code": "T1001W",
	"time": "2021-07-09T02:49:52.861Z",
	"cluster_name": "demo.teleport-cloud.com",
	"success": false,
	"error": "list of user teams is empty, did you grant access?",
	"message": "list of user teams is empty, did you grant access?",
	"method": "github"
}
```

Here are a few items to check, if you are receiving a similar error. 

### Validate the Teleport Auth Connector configuration

Go to your Teleport Auth Connectors configuration within the Teleport Web UI. Edit the Github connector and validate the following...

1. Your `teams_to_logins` configuration contains a list of mappings. 
2. The `logins` key contains a list of existing Teleport roles. 
3. Your `organization` value contains the name of your Github Organization exactly as defined in Github (case sensitive). 
4. The `team` value is set as an existing team within your Github Organization. 

```yaml
kind: github
metadata:
  name: Github
spec:
  client_id: xxxxx
  client_secret: xxxxx
  display: Github
  redirect_url: https://teleport-demo.teleport.sh/v1/webapi/github/callback
  teams_to_logins:
  - logins:
    - admin
    organization: Teleport-Demo
    team: admin
```

### Review Github Organization Settings

1. Go to your Github Organization. https://github.com/settings/organizations
2. Select "Settings" next to the Organization.
3. Go to "Third-party access". 
4. If you have OAuth App access restrictions enabled, you need to either Grant access to your Teleport OAuth Application or remove restrictions from the Organization. Read more about App Access Policies [here](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/enabling-oauth-app-access-restrictions-for-your-organization).
