### DISCUSSION TITLE
Teleport without 2FA ( two factor authentication )

### DISCUSSION THREAD

**Discussion by kalhori124** [gravitational/teleport#7768] [Q&A] [answered]
Hi,

I want to have Teleport without 2FA on the **Intranet** without Internet access. so Teleport server does not have Internet access and we do not have UFA right now.

How can I disable 2FA ?

Thanks.

**Comment by webvictim** [comment, marked as answer]
EDIT: This is no longer possible with Teleport version 16 and above - MFA must now be used for additional security.

For older versions of Teleport, set this in `/etc/teleport.yaml` and restart your Teleport server:

```yaml
auth_service:
  authentication:
    second_factor: off
```

**Comment by PavelNiedoba** [comment]
it is nice, that i can remove it from all users, can i remove it from single user too ?

**Reply by webvictim** [reply]
No, this is a cluster-wide setting.

**Comment by dellarte** [comment]
Hi !
Not working.

```
version: v3
teleport:
  nodename: **********
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.*************
  proxy_listener_mode: multiplex
  authentication:
    second_factor: off
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```

then, after a `teleport start` : 

```
ERROR: initialization failed

Teleport requires second factor authentication for local users.
The auth_service configuration should be updated to enable it.

auth_service:
  authentication:
    second_factor: on
    webauthn:
      rp_id: example.com

For more information:
- https://goteleport.com/docs/access-controls/guides/webauthn/

                cannot disable multi-factor authentication
````

version:16.0.4
