### DISCUSSION TITLE
Multiple labels with the same key for services

### DISCUSSION THREAD

**Discussion by C4ArtZ** [gravitational/teleport#7779] [Q&A]
I'm trying to grant two Roles access to a server based on its label: "dev" and "infrastructure".

I tried doing that with the labels `group:dev` and `group:infrastructure`.
I can add multiple labels with the same key to the roles like this:

```
node_labels:
  group:
  - dev
  - infrastructure
```

But I can't do the same on the service itself, as the service always fails to start.
This is what I tried (I know the last one is invalid YAML):

```
labels:
  group: infrastructure, dev

labels
  group: ["infrastructure", "dev"]

labels:
  group:
  - infrastructure
  - dev

labels:
  group: infrastructure
  group: dev
```

Is there something I'm missing or is there a better approach to this?

**Comment by webvictim** [comment]
Labels are key:value pairs, so it's not possible to set a list of values on a node.

The way to do this would be to modify your role:

```yaml
node_labels:
  env:
  - dev
  group:
  - infrastructure
```
 
and then change the labels on your node:

```yaml
labels:
  env: dev
  group: infrastructure
```
