### DISCUSSION TITLE
Add new user Access Denied

### DISCUSSION THREAD

**Discussion by irwanshofwan** [gravitational/teleport#7793] [Q&A] [answered]
Hi Team, 
I'm trying running teleport with --insecure-no-tls flag in vagrant instance, when I try create user and input a password it always show access denied.

here my teleport configuration
```
teleport:
  nodename: ubuntu-bionic
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
auth_service:
  authentication:
    second_factor: off
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  https_keypairs: []
  acme: {}
```

Here my systemd for teleport

```[Unit]
Description=Teleport SSH Service
After=network.target

[Service]
Type=simple
Restart=on-failure
ExecStart=/usr/local/bin/teleport start --insecure-no-tls --config=/etc/teleport.yaml --pid-file=/run/teleport.pid
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/run/teleport.pid

[Install]
WantedBy=multi-user.target
```

I also attach the command error and the output error, I try inspect with journalctl log and no luck

![Screen Shot 2021-08-04 at 21 25 22](https://user-images.githubusercontent.com/23578970/128198507-1212290d-d19f-43be-b4c5-3f1de1fb4406.png)

 
![Screen Shot 2021-08-04 at 21 22 46](https://user-images.githubusercontent.com/23578970/128198198-96d70a63-18b5-4f38-868a-62bca6e01c3e.png)
