### DISCUSSION TITLE
You do not have access to add a server

### DISCUSSION THREAD

**Discussion by hakerakn** [gravitational/teleport#7832] [Q&A]
Hello, I have had the following problem for several days:
As a blade on the "Add server" button, the button is not active. He wrote me the following inscription "You do not have access to add a server"

The user is: teleport-admin
It has the following roles: access, admin

**Comment by stevenGravy** [comment]
@hakerakn please confirm you have `token` resource access in your `admin` role.

**Comment by hakerakn** [comment]
Admin Role
[https://pastebin.com/ZnfMLyBH](url)

Access Role
[https://pastebin.com/1cZcc8EK](url)

**Comment by hakerakn** [comment]
![image](https://user-images.githubusercontent.com/5690740/128730626-17d9991d-cedb-4970-b170-ec81d7df751f.png)

**Comment by stevenGravy** [comment]
@hakerakn please share the yaml content. of those roles.  Your pastebin links did not have content.

**Comment by webvictim** [comment]
You need `create` permissions on `token` - try a role like this:

```yaml
kind: role
metadata:
  name: allow-create-token
spec:
  allow:
    rules:
    - resources:
      - token
      verbs:
      - list
      - read
      - create
      - update
      - delete
version: v3
 ```
