### DISCUSSION TITLE
Teleport behind Nginx reverse proxy

### DISCUSSION THREAD

**Discussion by jackyougit** [gravitational/teleport#7857] [Q&A]
Excuse my naivety, but i'm having a difficult time getting Teleport set up behind Nginx.

It works fine when accessing it internally at teleport.example.com, however, it refuses to work when accessing it publicly.
I've added my own SSL certificate for teleport.example.com and added it in my config:

```
# By default, this file should be stored in /etc/teleport.yaml

# This section of the configuration file applies to all teleport
# services.
teleport:
    # nodename allows one to assign an alternative name this node can be reached by.
    # by default it's equal to hostname
    nodename: teleport

    # Data directory where Teleport daemon keeps its data.
    # See "Filesystem Layout" for more details
    # (https://goteleport.com/teleport/docs/admin-guide/#filesystem-layout).
    data_dir: /var/lib/teleport

    # Optional CA pin of the auth server. This enables more secure way of adding new
    # nodes to a cluster. See "Adding Nodes to the Cluster"
    # (https://goteleport.com/teleport/docs/admin-guide/#adding-nodes-to-the-cluster).
#    ca_pin: "sha256:7e12c17c20d9cb504bbcb3f0236be3f446861f1396dcbb44425fe28ec1c108f1"

    # When running in multi-homed or NATed environments Teleport nodes need
    # to know which IP it will be reachable at by other nodes
    #
    # This value can be specified as FQDN e.g. host.example.com
#    advertise_ip: teleport.example.com

    # Logging configuration. Possible output values to disk via '/var/lib/teleport/teleport.log',
    # 'stdout', 'stderr' and 'syslog'. Possible severity values are INFO, WARN
    # and ERROR (default).
    log:
      output: stderr
      severity: INFO

    # Log format configuration
    # Possible output values are 'json' and 'text' (default)
    # Possible extra_fields values include: timestamp, component, caller, and level.
    # All extra fields are included by default.
      format:
        output: text
        extra_fields: [level, timestamp, component, caller]

# This section configures the 'auth service':
auth_service:
    # Turns 'auth' role on. Default is 'yes'
    enabled: "yes"
    # IP and the port to bind to. Other Teleport nodes will be connecting to
    # this port (AKA "Auth API" or "Cluster API") to validate client
    # certificates
    listen_addr: 0.0.0.0:3025
    cluster_name: teleport.example.com
    tokens:
    # This static token allows new hosts to join the cluster as "proxy" or "node"
    - "proxy,node,app:jLxNWJZYLqZQZXNe9!R5_V9)AT2EzwyC"

    authentication:
        # default authentication type. possible values are 'local' and 'github' for OSS
        #  and 'oidc', 'saml' and 'false' for Enterprise.
        # 'false' is required for FedRAMP / FIPS, see
        #  https://gravitational.com/teleport/docs/enterprise/ssh-kubernetes-fedramp/
        #  only local authentication (Teleport's own user DB) & Github is supported in the open
        #  source version
        type: local
        # second_factor can be off, otp, or u2f
        second_factor: u2f
        u2f:
          app_id: https://teleport.example.com:443
          facets:
          - https://teleport.example.com:443
          - https://teleport.example.com
          - teleport.example.com:443
          - teleport.example.com
# This section configures the 'node service':
ssh_service:
    # Turns 'ssh' role on. Default is 'yes'
    enabled: "yes"
    # IP and the port for SSH service to bind to.
    listen_addr: 0.0.0.0:3022
#    labels:
#      env: server
    # List of the commands to periodically execute. Their output will be used as node labels.
    # See "Labeling Nodes" section for more information and more examples
    # (https://goteleport.com/teleport/docs/admin-guide/#labeling-nodes-and-applications).

    commands:
    - name: hostname
      command: [hostname]
    - name: ip
      command: ["/usr/bin/hostname", "-I"]
    - name: uptime
      command: ["/usr/bin/uptime", "-p"]


#    commands:
#    - name: hostname
#      command: [hostname]
#      period: 1m0s
    # Enables/disables TCP forwarding. Default is 'true'
    port_forwarding: true


# This section configures the 'proxy service'
proxy_service:
    # Turns 'proxy' role on. Default is 'yes'
    enabled: "yes"
    # SSH forwarding/proxy address. Command line (CLI) clients always begin their
    # SSH sessions by connecting to this port
    listen_addr: 0.0.0.0:3023
    web_listen_addr: teleport.example.com:443
    public_addr: teleport.example.com:443

    # TLS certificate for the HTTPS connection. Configuring these properly is
    # critical for Teleport security.
    https_key_file: /etc/letsencrypt/live/teleport.example.com/privkey.pem
    https_cert_file: /etc/letsencrypt/live/teleport.example.com/fullchain.pem
    # Get an automatic certificate from Letsencrypt.org using ACME via TLS_ALPN-01 challenge.
    # When using ACME, the cluster name must match the 'public_addr' of Teleport and
    # the 'proxy_service' must be publicly accessible over port 443.
    # Also set using the CLI command:
    # 'teleport configure --acme --acme-email=email@example.com --cluster-name=tele.example.com -o file'
    # acme:
    #  enabled: "yes"
    #  email: me@example.com
    #  acme: {}

```

Whenever I try and access it publicly, I get a untrusted certificate error, and when I accept the risk, I get redirected to my Nextcloud server that then gives me a Nextcloud trusted domain error. 

I'm at a loss with this. I've forwarded all the relevant ports for Teleport in pfSense. 
Also, when I test my SSL certificate for teleport.example.com, it gives me an error saying that the alternative name for that certificate is set to cloud.example.com.

Domain names changed for obvious reasons.

Any ideas on how to get this sorted out?
