### DISCUSSION TITLE
Connect 2 k8s clusters to teleport

### DISCUSSION THREAD

**Discussion by igtsekov** [gravitational/teleport#7932] [Q&A] [answered]
I want to do connect 2 k8s clusters with 1 teleport cluster.
The teleport cluster is working outside of the k8s. I want to do this using the [teleport-kube-agent](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-kube-agent) method. Unfortunately, I cannot use helm to launch and configure the pod. I need to do it manually.
I launched the auth/proxy process with this configuration
```
proxy_service:
  kube_public_addr: [root.example.com]
  kube_listen_addr: 0.0.0.0:3026
```
I launched a pod in the first k8s cluster with this configuration
```
kubernetes_service:
  enabled: true
  kube_cluster_name:leaf1
  public_addr: leaf1.example.com:3026
  listen_addr: 0.0.0.0:3026
  labels:
    env: lead1
    cluster: leaf1
```
After that, I see the cluster in the `kube ls` command and can successfully log in via the `kube login leaf1` command. The `~/.kube/config` file is generated correctly.
When I try to get some information from the k8s cluster I get this error
```
kubectl get node
Error from server: x509: certificate is valid for 127.0.0.1, ::1, not 172.28.0.159
```
The `172.28.0.159` in the output is the IP of the node that is hosting the `teleport-kube-agent` pod and the `leaf1.examaple.com` DNS points to it.
When I edit the `~/.kube/config` and change the `server: https://root.example.com:3026` to `server:https://leaf1.example.com:3026` everything is working perfectly.

How can I force teleport to put the connect URL in the `~/.kube/config` file?
