### DISCUSSION TITLE
Node disconnect with Azure Load Balancer

### DISCUSSION THREAD

**Discussion by RyanMesser** [gravitational/teleport#8060] [Q&A]
When using an Azure Load Balancer I'm load balancing, 443>3080, 3023,3024. I can join a node to the cluster with a yaml config and connect fine. If I disconnect and reconnect shortly afterwards I get the following message, this clears up after X amount of time and I can connect again but then I will get the below error again sometime afterwards..

```
Teleport proxy failed to connect to "node" agent "@local-node" over reverse tunnel:
no tunnel connection found: no node reverse tunnel for 3bb2431a-35eb-4659-b4ae-cf312b2f24d1.teleport-docker found

This usually means that the agent is offline or has disconnected. Check the
agent logs and, if the issue persists, try restarting it or re-registering it
with the cluster.

```

Teleport YAML for the Node

```
teleport:
  nodename: X
  auth_servers: ["proxy:443"]
  auth_token: X
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO

  data_dir: /var/lib/teleport
  storage:
      path: /var/lib/teleport/backend
      type: dir

auth_service:
  enabled: no

ssh_service:
  enabled: yes
  labels:
      enviroment: X
  commands:
      - name: kernel
        command: [/bin/uname, -r]
        period: 5m
proxy_service:
  enabled: no
```
