### DISCUSSION TITLE
How to enable debug mode for Teleport?

### DISCUSSION THREAD

**Discussion by WilliamLoy** [gravitational/teleport#8157] [Q&A] [answered]
Can someone explain in detail how to enable debug mode?

Thanks, Will

**Comment by programmerq** [comment, marked as answer]
The teleport service can be started with the `--debug` flag to enable debug mode. For example, instead of `teleport start`, you can run `teleport start --debug`. The short `-d` flag is equivalent to the long `--debug` flag. Additionally, the `tctl` and `tsh` commands also have a `--debug` to increase the output. See https://goteleport.com/docs/setup/reference/cli/ for reference.

**Reply by deusxanima** [reply]
Note that you can also set the log severity in the teleport config file to DEBUG and restart service to have it take effect (see config example below):

```
teleport:
  log:
    severity: DEBUG
```

**Reply by travelton** [reply]
It's also important to point out that the `output` of your logging configuration determines where the debug logs end up.

```yaml
    # Logging configuration. Possible output values to disk via '/var/lib/teleport/teleport.log',
    # 'stdout', 'stderr' and 'syslog'. Possible severity values are DEBUG, INFO, WARN
    # and ERROR (default).
    log:
        output: /var/lib/teleport/teleport.log
        severity: DEBUG

        # Log format configuration
        # Possible output values are 'json' and 'text' (default).
        # Possible extra_fields values include: timestamp, component, caller, and level.
        # All extra fields are included by default.
        format:
          output: text
          extra_fields: [level, timestamp, component, caller]
```
