### DISCUSSION TITLE
Sharing a local app using Teleport & Docker Compose

### DISCUSSION THREAD

**Discussion by benarent** [gravitational/teleport#8194] [Show and tell]
While creating a demo for a livestream, I want to show a cool feature of using Teleport Application Access. In this demo, I used Teleport to provide access to another Docker image. In this case, Grafana. This pattern could be used to share local dev environments or any other local ephemeral app. 

Note: Proxy URL and Auth Token needs to be set in a `.env` file, I'm also open to better approached to local networking. I was unable to get it working without defining an IP to the "grafana" app. 

```yaml
version: '2'

services:
  grafana:
    image: grafana/grafana:5.1.0
    hostname: grafana
    ports:
      - "3000:3000"
    user: '104'
    container_name: grafana
    networks:
      teleport:
        ipv4_address: 172.10.1.20
    environment:
      - GF_SECURITY_COOKIE_SECURE=false
      - GF_LOG_CONSOLE_LEVEL=debug
      - GF_LOG_LEVEL=debug
      - GF_SERVER_HTTP_ADDR=172.10.1.20
  teleport:
    image: quay.io/gravitational/teleport:7
    container_name: teleport-tmp
    entrypoint: /bin/sh
    command: -c "teleport start --roles=node,app --token={TELEPORT_INVITE}  --labels=env=local-docker --app-name=grafana-docker-local --app-uri=http://172.10.1.20:3000  --auth-server={TELEPORT_URL}"
    networks:
      teleport:
        ipv4_address: 172.10.1.21

networks:
  teleport:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.10.1.0/16
        ip_range: 172.10.1.0/24
        gateway: 172.10.1.254
```
