### DISCUSSION TITLE
Connecting and authenticating to Jenkins with Teleport Application Access via headers

### DISCUSSION THREAD

**Discussion by stevenGravy** [gravitational/teleport#8330] [Show and tell]
This shows integrating a Jenkins with Teleport Application Access for Access and Authentication.  The examples here assume a Linux environment.

Required for this example:
 - Existing Jenkins or `docker`/`docker-compose` available environment. See the Jenkins site for recommend hardware depending on usage.
- Teleport with Application Access.  See the [docs](https://goteleport.com/docs/application-access/introduction/) for info on DNS and TLS requirements.

Note the examples below use the fqdn `teleport.example.com`.  Replace with yours.
 
### Jenkins environment setup (skip if already have Jenkins)

 1. Install `docker` and `docker-compose`

2.  create the jenkins data directory `/var/jenkins_home` or choose a different name.

3. configure the `docker-compose` yaml 

`docker-compose.yml`:
```yaml
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
```
Jenkins on this machine will listen on port `8080`, `50000`.  Do not open to external access as Teleport will provide access. 

4. Start 
`docker-compose up -d`

Capture the admin password
`docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword`

###  Install Teleport On Machine

1. Install Teleport via https://goteleport.com/docs/installation/#linux steps or your preferred means. 

2. Get `app`,`node` token
`tctl tokens add --type=app,node --ttl=4h`

3. Configure the `/etc/teleport.yaml`

Replace the `auth_servers` with your proxy address and web port, the `ca_pin`, the `auth_token`, and the `teleport.example.com` with your fqdn. 

```yaml
teleport:
  nodename: jenkinsapp
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  auth_servers:
  - teleport.example.com:443
  ca_pin: "<ca-pin>"
  auth_token: <auth-token>
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
     serving_app: 
proxy_service:
  enabled: "no"

app_service:
  enabled: "yes"
  apps:
  - name: "jenkinsapp"
    uri: "http://localhost:8080"
    public_addr: jenkinsapp.teleport.example.com
    rewrite:
      redirect:
      - "localhost"
      - "jenkinsapp.teleport.example.com"
      headers:
      - "X-Forwarded-User: {{email.local(external.email)}}"
```
The `X-Forwarded-User` will set the userid in Jenkins.  

**Note** this assume a SSO that will have the  email trait.  You can use other traits.  For github you can change that to `'{{internal.logins}}'` and use a configured trait for a local user such as `'{{internal.email}}'`. 

4. Start Teleport
 
Run teleport directly, `teleport start`, or start a service which is the recommendation. 

### Access Jenkins from Applications

1. Press launch from the applications list
![jenkinsappconsole](https://user-images.githubusercontent.com/60704961/134182033-25390293-f3fb-45a0-987f-754bd8d26929.png)

2. Login with the admin password you captured earlier if this is your initial setup.  Go through the initial plugin configuration.

### Configure Plugin and Security

**Note** This will change your security authentication within Jenkins that may have adverse impact.  Make sure if this is an existing Jenkins you have this Jenkins backed up.

1. Go to Manage Plugins through Manage Jenkins and install the Reverse Proxy Auth Plugin

![reverseproxySelect](https://user-images.githubusercontent.com/60704961/134167615-ff96a92c-6f29-4d51-a44a-c1685c5d93e3.png)

2. Go to Configure Global Security to enable `HTTP Header by reverse proxy`
![configureGlobalSecurity](https://user-images.githubusercontent.com/60704961/134183333-c16b5455-dab5-4298-82c6-fe7a75cb5e9b.png)

3. Logout of the app session
`https://jenkinsapp.teleport.example.com/teleport-logout`

4. Select the Jenkins app to enter as the SSO email username
