### DISCUSSION TITLE
How do I configure default authentication type for Teleport Cloud?

### DISCUSSION THREAD

**Discussion by deusxanima** [gravitational/teleport#8495] [Show and tell]
1. Create a yaml config file with the following settings:

```
kind: cluster_auth_preference
metadata:
  name: cluster-auth-preference
spec:
  type: github
version: v2
```

<b>Note:</b> in my case I tested with github, but if your connector is SAML then use `saml` as the type, and if it's OIDC then use `oidc` as the type as discussed [here](https://goteleport.com/docs/setup/reference/authentication/).

2. Log into your cloud cluster with admin credentials.

3. Run `tctl create -f <auth_file> --confirm`

Next time you log in you can just run `tsh login` without having to specify auth type.
