### DISCUSSION TITLE
Dockerizing Teleport Access Plugins

### DISCUSSION THREAD

**Discussion by stevenGravy** [gravitational/teleport#8679] [Show and tell]
Here is an example of dockerizing a plugin that is reusable for the teleport plugins. In this case it uses the slack plugin example.  See the [guide](https://goteleport.com/docs/enterprise/workflow/ssh-approval-slack/) for creating the `access-plugin.pem` to connect through the web proxy. 

./slack/Dockerfile
```Dockerfile
FROM ubuntu:20.04
ARG TELEPORT_VERSION
ARG PLUGIN
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y ca-certificates dumb-init curl && \
    update-ca-certificates && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir /teleport-plugin-install && \
  curl -L https://get.gravitational.com/teleport-access-$PLUGIN-v$TELEPORT_VERSION-linux-amd64-bin.tar.gz -o /teleport-plugin-install/teleport-plugin.tar.gz && \
tar -xzf /teleport-plugin-install/teleport-plugin.tar.gz -C /teleport-plugin-install && \
/teleport-plugin-install/teleport-access-$PLUGIN/install && \
# moving to generically call teleport-plugin
mv /usr/local/bin/teleport-$PLUGIN /usr/local/bin/teleport-plugin && \
rm -rf /teleport-plugin-install
ENTRYPOINT ["/usr/bin/dumb-init", "teleport-plugin", "start", "-c", "/var/lib/teleport-plugins/plugin.toml"]
```

docker-compose.yml
```yaml
version: "3.3"
services:
  slack:
    build:
       context: ./slack
       dockerfile: Dockerfile
       args:
         TELEPORT_VERSION: 7.3.0
         PLUGIN: slack
    image: teleport-slack
    container_name: teleport-slack
    restart: unless-stopped
    volumes:
      - ./slack/config:/var/lib/teleport-plugins
    hostname: teleport-slack
```

./slack/config/plugin.toml
```toml
[teleport]
addr = "teleport.example.com:443"                        # peleport Auth Server GRPC API address
identity = "/var/lib/teleport-plugins/access-plugin.pem"

[slack]
token = "<token-id>"             # Slack Bot OAuth token
recipients = ["requests"] 

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/slack.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```
