### DISCUSSION TITLE
Failed Websockets using Teleport App

### DISCUSSION THREAD

**Discussion by Danny-SCNX** [gravitational/teleport#8821] [Q&A]
So I just started testing teleport application access.
Currently running this version.

 tctl version
Teleport v7.3.2 git:v7.3.2-0-gaa361fbc1 go1.16.2

Most of the simple web access using teleport app work as expected.
But when it comes to websocket, (we are trying to proxy the access to dataiku web UI),
we noticed the websocket errored with the following.

`
[18:37:40.965] [d.s.WebSocketService] - WS closed: 
close { target: WebSocket, isTrusted: true, wasClean: false, code: 1008, reason: "XSRF validation failed, please refresh the page.", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
`

Although the error is threw by the dataiku web server, but would like to check if there might be any headers modification for XSRF related.
From https://goteleport.com/docs/application-access/guides/connecting-apps/#advanced-options, I can found this. 
`
The following headers are reserved and can't be rewritten: X-Teleport-Jwt, Cf-Access-Token, X-Forwarded-*.
`
But that shouldn't be a problem here for the XSRF to the web server behind teleport.

Any suggestions how we can tackle this?
Will turning on debug log at teleport proxy here help to identify the list of headers being passed through?

**Comment by Danny-SCNX** [comment]
Hmm.. somehow works now after force setting a few more headers accordingly. Oh well.

What I did was this.
```
rewrite:
  headers:
    - "Host: URL"
    - "Connection: Upgrade"
    - "Upgrade: websocket"
```

**Reply by Danny-SCNX** [reply]
Ok, not fully working for websocket still.
Since the javascript is trying to establish connection with wss://<URL>, I am not sure if teleport is even handling this kind of request.

```
Starting WebSockets: wss://<URL>/jupyter/api/kernels/5b477e86-b86b-4563-a6cd-f7b651555e31
Firefox can’t establish a connection to the server at wss://<URL>/jupyter/api/kernels/5b477e86-b86b-4563-a6cd-f7b651555e31/channels?session_id=d8eaa3d381324191995b5a08a65f9539.
```

**Reply by webvictim** [reply]
Websocket support was fixed in Teleport 6.1 IIRC - see https://github.com/gravitational/teleport/issues/5264.

It should work correctly.

**Reply by Danny-SCNX** [reply]
Not quite sure if that was the case. @webvictim 
Any suggestion how to tweak the rewrites for teleport app if given a reverse proxy config from other tools (nginx, httpd etc)?

for instance.

nginx
```
server {
    # Host/port on which to expose Data Science Studio to users
    listen 80;
    server_name dss.example.com;
    location / {
        # Base url of the Data Science Studio installation
        proxy_pass http://DSS_HOST:DSS_PORT/;
        proxy_redirect off;
        # Allow long queries
        proxy_read_timeout 3600;
        proxy_send_timeout 600;
        # Allow large uploads
        client_max_body_size 0;
        # Allow protocol upgrade to websocket
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Apache
```
# Apache reverse proxy configuration for Dataiku Data Science Studio
# requires Apache version 2.4.5 or above
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
LoadModule rewrite_module modules/mod_rewrite.so

<VirtualHost *:80>
    ServerName dss.example.com
    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} WebSocket [NC]
    RewriteRule /(.*) ws://DSS_HOST:DSS_PORT/$1 [P]
    RewriteRule /(.*) http://DSS_HOST:DSS_PORT/$1 [P]
    ProxyPassReverse / http://DSS_HOST:DSS_PORT/
    ProxyPreserveHost on
    ProxyTimeout 3600
</VirtualHost>
```

I was using these but wss still not working as expected. 
```
rewrite:
  headers:
    - "Host: URL"
    - "Connection: Upgrade"
    - "Upgrade: websocket"
 ```

**Reply by Danny-SCNX** [reply]
Or does it work only with tsh cli? not with teleport web UI?

**Reply by webvictim** [reply]
It should work with the web UI. Try a configuration like this:

```yaml
app_service:
  enabled: yes
  apps:
    name: dss
    public_addr: dss.teleport.example.com
    rewrite:
      redirect:
      - 1.2.3.4
      - https://1.2.3.4
    uri: https://1.2.3.4
```

Replace 1.2.3.4 here with the host:port for DSS.

**Reply by Danny-SCNX** [reply]
I actually tried this. Unfortunately still not working as expected when it comes to using url with wss://.

**Reply by lord-kyron** [reply]
Yes, for me it is still not working too.
My situation is described in the comments below.

**Comment by Danny-SCNX** [comment]
Seems to be related to feature request from https://github.com/gravitational/teleport/issues/4716

**Comment by lord-kyron** [comment]
Hi, I am having the same problem here. Trying to access application which is behind nginx server as ngins id doing some hard rewrite stuff, which teleport is not able to do. However, websockets are working when I am directly accessing the web page from the nginx instance, but when I try to use the teleport app access before the nginx - everything seems to work fine except the websockets. I've tried everything described in this post and with no success. It seems wss:// just does not to pass through teleport.
Using teleport enterprise 7.3.3

**Comment by lordrip** [comment]
Tested with teleport@14 behind an nginx proxy manager and enabled the WebSockets support make it work for SSH connections
![image](https://github.com/gravitational/teleport/assets/16512618/7cf239bc-7d64-4d4c-9faf-2c67090338aa)

**Comment by tukusejssirs** [comment]
I believe I am affected by the same bug: I wanted to add MQTT over WS to Teleport.

I set `insecure_skip_verify` to `false`, I rewrite `Host`, `Connection` and `Upgrade` headers, but I still get an error:

```bash
WebSocket was closed before the connection was established
   Error code: N/A
   Error errno: N/A
   Error syscall: N/A
   Stack trace: Error: WebSocket was closed before the connection was established
    at WebSocket.terminate ($HOME/.local/share/pnpm/global/5/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:489:7)
    at Timeout._onTimeout ($repo_root/test-ws-raw.js:40:12)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
```

I too use NGINX and locally (without Teleport), the connections work as expected, but not when using TP. :thinking:

**Comment by TheoBrigitte** [comment]
Facing the same problem here with Grafana websocket communication (for `/api/live/ws` endpoint). All regular HTTP connections work but not the websocket connection.
The websocket connection works when accessing Grafana via nginx directly but does not when going through the Teleport app.

```
#### Works via nginx ####
$ curl -v 'wss://grafana.host.io/api/live/ws'
* Host grafana.host.io:443 was resolved.
* ...
* Connected to grafana.host.io (x.x.x.x) port 443
* using HTTP/1.x
> GET /api/live/ws HTTP/1.1
> Host: grafana.host.io
> User-Agent: curl/8.15.0
> Accept: */*
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Version: 13
> ...
* Request completely sent off
< HTTP/1.1 101 Switching Protocols
< Date: Mon, 29 Sep 2025 19:33:19 GMT
< Connection: upgrade
< Upgrade: websocket
< Sec-WebSocket-Accept: xxxx=
<
* [WS] Received 101, switch to WebSocket; mask 9215c657


#### Doest not work when going through Teleport app ####
~ $ curl -v 'wss://grafana.host.io/api/live/ws'
* Host grafana.host.io:443 was resolved.
* ...
* Connected to grafana.host.io (x.x.x.x) port 443
* using HTTP/1.x
> GET /api/live/ws HTTP/1.1
> Host: grafana.host.io
> User-Agent: curl/8.15.0
> Accept: */*
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Version: 13
> ...
* Request completely sent off
< HTTP/1.1 302 Found
< Content-Type: text/html; charset=utf-8
< Location: https://teleport.my-domain.io:443/web/launch/grafana.host.io?path=%2Fapi%2Flive%2Fws
< Date: Mon, 29 Sep 2025 19:33:25 GMT
< Content-Length: 129
* Refused WebSockets upgrade: 302
<
* closing connection #0
curl: (22) Refused WebSockets upgrade: 302

```

I tried using the `rewrite` mentioned above but it did not change anything.

**Comment by TheoBrigitte** [comment]
Ok I managed to get Grafana websocket working behind a Teleport app, I had 2 things configured wrong:

- **`Origin` header** for websocket HTTP upgrade needs to be set on Grafana to accept incoming websocket connections from Teleport
- Target port in the Teleport app was wrong Grafana only accepts websocket over port 3000

Here is my final configuration

```yaml
# Teleport app
apps:
  - name: grafana
    public_addr: grafana.teleport.my-domain.io
    uri: http://grafana.default.svc.cluster.local:3000
```


```yaml
# Grafana websocket Origin header
- name: GF_LIVE_ALLOWED_ORIGINS
  value: https://grafana.teleport.my-domain.io
```

I run all of this in a Kubernetes cluster where the Teleport app configuration is set via `teleport-kube-agent` and Grafana lives in `default` namespace without any proxy in front, just Teleport acting as the reverse proxy.

<details>
<summary>full Grafana deployment</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: default
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/name: grafana
    spec:
      containers:
      - env:
        - name: GF_LIVE_ALLOWED_ORIGINS
          value: https://grafana.teleport.my-domain.io
        - name: GF_LOG_LEVEL
          value: debug
        image: grafana/grafana:12.2.0
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: default
spec:
  ports:
  - name: service
    port: 3000
    protocol: TCP
    targetPort: grafana
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
```

</details>


<details>
<summary>full troubleshooting</summary>

#### wrong port: `/api/live/ws` does not exists on port 80
- `teleport-kube-agent`: `2025-09-30T11:55:07Z INFO [APP:SERVI] Round trip: GET http://grafana.default.svc.cluster.local:80/api/live/ws, code: 400, duration: 23.223317ms [tls...] reverseproxy/reverse_proxy.go:223`
- `grafana`: `[INF] context: Request Completed userId=6 orgId=1 uname=theobrigitte t=2025-09-30T11:55:07.715779144Z method=GET path=/api/live/ws status=400 remote-addr=x.x.x.x time-ms=18 duration=18.161005ms size=12 referer="" handler=/api/live/ws status-source=server`

#### using port 3000 but missing Origin header
- `teleport-kube-agent`: `2025-09-30T12:19:12Z INFO [APP:SERVI] Round trip: GET http://grafana.default.svc.cluster.local:3000/api/live/ws, code: 403, duration: 65.974343ms tls:version: 304, [tls...] reverseproxy/reverse_proxy.go:223`
- `grafana`: `[WRN] live: Request Origin is not authorized t=2025-09-30T12:19:12.697083102Z origin=https://grafana.teleport.my-domain.io host=grafana.default.svc.cluster.local:3000 appUrl=https://grafana.host.io/ allowedOrigins=""`

#### using port 3000 and Origin: 
- `teleport-kube-agent`: `2025-09-30T12:24:29Z INFO [APP:SERVI] Round trip: GET http://grafana.default.svc.cluster.local:3000/api/live/ws, code: 101, duration: 46.891777ms tls:version: 304, [tls...] reverseproxy/reverse_proxy.go:223 `
- `grafana`: `[INF] context: Request Completed userId=6 orgId=1 uname=theobrigitte t=2025-09-30T12:24:29.168909856Z method=GET path=/api/live/ws status=-1 remote-addr=10.0.3.145 time-ms=24 duration=24.238734ms size=0 referer="" handler=/api/live/ws status-source=server`
- `grafana`: `[DBG] live: Client connected t=2025-09-30T12:24:29.323859364Z user=6 client=xxxx`



</details>
