### DISCUSSION TITLE
Role template not picking up user `traits` for `node_labels`

### DISCUSSION THREAD

**Discussion by nikhil-31** [gravitational/teleport#8878] [Q&A] [answered]
### Type: 
How to

### Question
Role templates are not picking up user `traits` for `node_labels`? Using teleport version 6.1.5 

#### Role 1
```yaml
kind: role
version: v3
metadata:
  name: test-role
spec:
  allow:
    logins: ['ubuntu', 'ec2-user']
    node_labels:
      'group': ['{{internal.group}}']
```

#### User 1
```yaml
kind: user
version: v2
metadata:
  name: jane doe
spec:
  roles: ['test-role']
  traits:
    group: ['a-group']
```
