### DISCUSSION TITLE
Allow subdomain access for Web applications

### DISCUSSION THREAD

**Discussion by t3chboy** [gravitational/teleport#9171] [Q&A]
### Need to allow subdomains for web applications

**What**:
We had added application as per follows : 

```
app_service:
        enabled: yes
        debug_app: true
        apps:
        - name: "jadmin"
          uri: "https://jadmin.abccomm.com"
          public_addr: "jadmin.abcz0.de"
```
Our main application is hosted on : `https://jadmin.abccomm.com` in vpc and we dont have direct access from internet to this app, so we installed teleport on one of the ec2 in same vpc, now we are able to access this web application but there are some internal url/api which need to load, but since they are hosted on other subdomain they are forbidden.

url/api eg : 
```
- https://api.abccomm.com/auth
- https://auth.abccomm.com/library_init.js

```

**What you expected to happen**:
How can we enable above url/api via teleport config file.

### Server Details
- Teleport version : `Teleport v6.2.18-label-debug.2 git:v6.2.18-label-debug.2-0-ge57ea7951 go1.15.5`
- Server OS : Ubuntu 20.04.3 LTS
- Where are you running Teleport? : AWS
- Additional details:

**Comment by darius-fritsch** [comment]
Hey @t3chboy!

I would recommend adding another app_service for the API in the same teleport.yaml file that you are currently using.

**Reply by t3chboy** [reply]
Hey @darius-fritsch thank you for the reply.
Have tried this option, it works if i open it as a separate app,
but if its called within other apps it give same 403 error.

![Screenshot from 2021-12-01 19-33-45](https://user-images.githubusercontent.com/3822294/144249341-3b235a1c-b85d-4deb-951f-95154686838f.png)


This is my config :

```
app_service:
        enabled: yes
        debug_app: true
        apps:
        - name: "jadmin"
          uri: "https://jadmin.abccomm.com"
          public_addr: "jadmin.abcz0.de"
        - name: "jauth"
          uri: "https://auth.abccomm.com/library_init.js"  
```
