### DISCUSSION TITLE
phpmyadmin under Teleport

### DISCUSSION THREAD

**Discussion by rit001** [gravitational/teleport#9352] [Q&A] [answered]
Has anyone placed phpmyadmin under Teleport. I've just started to use Teleport due to things like portainer not working under Traefik. 

Getting portainer to work was not much of an issue and validates that I've got the basic environment and certs working, but I'm at a loss to what is stopping phpmyadmin which just throws an Internal Server Error / error 500 when accessed.

Thanks in advanced.

**Comment by rit001** [comment, marked as answer]
It seems that phpmyadmin does not like to have its port 80 remapped within a docker environment. So the fix was to just design out the port mapping.

**Comment by modem7** [comment]
@rit001 FYI - regarding portainer not working under Traefik, this is due to authentication middlewares. 

Try something like this (direct C+P of my config, so apologies for the additional labels you may not use):

```
 #############
 ##Portainer##
 #############

 #Portainer CE - Docker Frontend/GUI - Homecentr Deployment
  portainer:
    # image: homecentr/portainer # https://github.com/homecentr/docker-portainer
    image: modem7/portainer:latest
    container_name: Portainer
    hostname: Portainer
    environment:
      PUID: $PUID
      PGID: $PGID
      PORTAINER_ARGS: "-H unix:///var/run/docker.sock"
      WAIT_FOR_NS_RECORD: "hda.home.lan"
      WAIT_FOR_NS_RECORD_TIMEOUT: 30
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      start_period: 40s
    networks: #Prevents Docker from creating a default stack network
      pihole:
        ipv4_address: '172.22.0.101'
    ports:
      - "9000:9000/tcp"
      - "8000:8000/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $USERDIR/Portainer:/data
      - /etc/localtime:/etc/localtime
    labels: 
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portaineradmin.$DOMAINNAME`)"
      - "traefik.http.routers.portainer-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-no-auth@file, traefik-error-pages" # No Authentication
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file, traefik-error-pages" # Basic Authentication
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file, traefik-error-pages" # Google OAuth 2.0
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-authelia@file, traefik-error-pages" # Authelia
      ## HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
     # Healthcheck
      - "traefik.http.services.portainer-svc.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.portainer-svc.loadbalancer.healthcheck.timeout=5s"
      - "traefik.http.services.portainer-svc.loadbalancer.healthcheck.path=/"
      ## Flame Dashboard
      - flame.type=application # "app" works too
      - flame.name=Portainer
      - flame.icon=https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/portainer.png
      # - flame.icon=custom to make changes in app. ie: custom icon upload
    restart: always
    mem_limit: 50m
    mem_reservation: 25m
```

Then add SSO to Portainer directly for security.
