### DISCUSSION TITLE
Which all ports need to be exposed outside the K8s cluster ?

### DISCUSSION THREAD

**Discussion by alwaysastudent** [gravitational/teleport#9782] [Q&A] [answered]
For a single pod helm installation, we get the following Service definition created with all the ports exposed externally off a single service. This seems like a pretty broad stroke definition. 

Can you please tell us, which are the specific ports that we genuinely need to expose externally?

```
# Source: teleport-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: teleport
  namespace: teleport-cluster
  labels:
    app: teleport
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 3080
    protocol: TCP
  - name: sshproxy
    port: 3023
    targetPort: 3023
    protocol: TCP
  - name: k8s
    port: 3026
    targetPort: 3026
    protocol: TCP
  - name: sshtun
    port: 3024
    targetPort: 3024
    protocol: TCP
  - name: mysql
    port: 3036
    targetPort: 3036
    protocol: TCP
  selector:
    app: teleport
```
