### ISSUE TITLE
[App Access] Preserve initial URL after login redirect

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#10054]
### Description

Reported by a customer.

**What happened**: when redirected to login via App Access, the initially-requested URL is lost.

**What you expected to happen**: after Teleport login the user should be redirected to the initially-requested URL.

### Reproduction Steps

There are many ways to setup a repro, the example below uses a local, single-process Teleport.

Working dir is `/path/to/teleport`, change as you like.

1. Configure and start Teleport

    ```yaml
    # teleport.yaml

    teleport:
      nodename: zarquon
      data_dir: /path/to/teleport/local1

    auth_service:
      enabled: "yes"
      cluster_name: "teleport.zarquon.sh"
      listen_addr: 0.0.0.0:3025
      authentication:
        type: local
        second_factor: off

    proxy_service:
      enabled: "yes"
      public_addr: "teleport.zarquon.sh"
      # Optionally: create a certificates for `teleport.zarquon.sh` and
      #             `*.teleport.zarquon.sh`
      # https_keypairs:
      # - cert_file: /path/to/teleport/cert.pem
      #   key_file:  /path/to/teleport/key.pem

    ssh_service:
      enabled: "no"

    app_service:
      enabled: "yes"
      debug_app: true
      apps:
      - name: "app1"
        uri: "http://localhost:8000"
        public_addr: "app1.teleport.zarquon.sh"
    ```

    then run:

    `teleport start -c ./teleport.yaml`

2. Create a Teleport user

    `tctl -c ./teleport.yaml users add ...`

2. Run an HTTP app at `localhost:8000`

    `python3 -m http.server 8000`

3. Write hosts entries

    `/etc/hosts`:
    
    ```
    # teleport.zarquon.sh cluster
    127.0.0.1	teleport.zarquon.sh
    127.0.0.1	app1.teleport.zarquon.sh
    127.0.0.1	dumper.teleport.zarquon.sh
    ```

4. Open https://app1.teleport.zarquon.sh:3080/local1/log/ in your browser,
   without an active Teleport session

    This should take you to the login screen; after login it redirects to
    https://app1.teleport.zarquon.sh:3080/ (instead of the desired
    https://app1.teleport.zarquon.sh:3080/local1/log/).

    You may need to clear your browser's Local Storage / Cookies to repro.

### Server Details

Running on `master` / local Teleport, but I believe it repros for any version.

### Client Details

Same as above.

### Debug Logs

Not necessary, see repro steps.
