### ISSUE TITLE
Invalid SSH packlet length with ELB

### ISSUE THREAD

**Issue by dbabb-charter** [gravitational/teleport#1007]
We've got teleport deployed in AWS sitting behind an application load balancer vs a classic. The ELB is listening on https 443, 3080, and 3023 all secured with a cert that's installed on the teleport auth and proxy instances. 

In case it matters, it's a wildcard *.domain.com cert.

When I issue a tsh directly to the proxy server I get in with zero problems. As soon as I use the DNS name with route53 which goes to the ELB I get this:

```
tsh -d  ssh --proxy=<proxyaddress> --user=name user@machine
Enter password for Teleport user user:
Enter your OTP token:
xxxxxx

ERROR REPORT:
Original Error: *errors.errorString ssh: handshake failed: ssh: invalid packet length, packet too large
Stack Trace:
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/client/api.go:925 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToProxy
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/client/api.go:398 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/tool/tsh/common/tsh.go:304 github.com/gravitational/teleport/tool/tsh/common.onSSH
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/tool/tsh/common/tsh.go:179 github.com/gravitational/teleport/tool/tsh/common.Run
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/tool/tsh/main.go:29 main.main
	/usr/local/go/src/runtime/proc.go:192 runtime.main
	/usr/local/go/src/runtime/asm_amd64.s:2087 runtime.goexit
User Message:
```

I tried using the alpha client to see if that fixed it and the behavior/errors don't change.

**Comment by russjones** [comment]
@dbabb-charter Can you tell me a little more about your setup? I tried to reproduce and could not.

I have two proxies behind a classic ELB that use TCP forwarding to forward ports `3023` and `3080` to the instances running the proxy. The health check endpoint is a HTTPS check that points to `/webapi/ping`. I have a A record in Route53 that points to the ELB.

**Comment by kontsevoy** [comment]
marking as invlid for now, hoping @dbabb-charter will come back with more info.

**Comment by dbabb-charter** [comment]
Sorry for not updating, here's a more detailed explanation of the environment...it's been a little crazy lately.

We split the services up. Relevant config details are below the hosts

Host 1 - Proxy/SSH
 ```
ssh_service:
    enabled: yes
    listen_addr: 0.0.0.0:3022
    labels:
        role: master
        type: ssh-proxy

proxy_service:
    enabled: yes
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3024
    web_listen_addr: 0.0.0.0:3080
```
Host 2 - Auth
```
auth_service:
    enabled: yes
    dynamic_config: false
    authentication:
        type: local
        second_factor: otp

    listen_addr: <ip>:3025

    tokens:
        - "proxy,node:<snip>”
        - "auth:<snip>"
        - "node:<snip>"

    cluster_name: "<snip>"
```
This is all pointing to Amazon dynamodb.

The Auth service is configured with and local/otp for authentication. I think the problem lives in the load balancer however.

We’re running it behind an ALB. ALB is set to forward 443, 3023, and 3080. If the traffic isn’t otherwise handled they default to being forwarded to 443. 

The security group for the auth host allows 3023, 22, 3022, 3025, 3024 from our rfc1918 space /16’s. 
The security group for the proxy host allows ports 3023, 3025 and 3080 from the ALB.
