### ISSUE TITLE
tctl error when using types.AppV3.Spec: types.AppSpecV3.Rewrite: types.Rewrite.Headers:

### ISSUE THREAD

**Issue by zen** [gravitational/teleport#10138]
### Description

**What happened**:

After struggling setting up proper access to define dynamic resources (documentation is also missing crucial informacion here) i was trying to use `rewrite.redirect.headers` using example from documentation here:
https://goteleport.com/docs/application-access/reference/#application-resource

My example was bit modified (removed optional dynamic labels):
```
kind: app
version: v3
metadata:
  # Application name.
  name: example
  # Application description.
  description: "Example application"
  # Application static labels.
  labels:
    env: local
spec:
  # URI and port application is available at.
  uri: http://localhost:4321
  # Optional application public address.
  public_addr: test.example.com
  # Disable application certificate validation.
  insecure_skip_verify: true
  # Rewrites configuration.
  rewrite:
    # Rewrite the "Location" header on redirect responses replacing the
    # host with the public address of this application.
    redirect:
      - "grafana.internal.dev"
    # Headers passthrough configuration.
    headers:
      - "X-Custom-Header: example"
      - "X-External-Trait: {{external.env}}"
```
After launching:
`tctl create -f example.yaml`

I got and error:
`ERROR: types.AppV3.Spec: types.AppSpecV3.Rewrite: types.Rewrite.Headers: []*types.Header: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|eaders":["X-Custom-H|..., bigger context ...|c_addr":"test.example.com","rewrite":{"headers":["X-Custom-Header: example","X-External-Trait: {{ext|...`

**What you expected to happen**:

Example from documentation works

### Reproduction Steps
Described above

### Server Details
- Teleport version: quay.io/gravitational/teleport:8.1.1
- Server OS: AWS EKS
- Where are you running Teleport? AWS EKS HA set up
- Additional details: main teleport from Helm, kube agend with roles db and app deployed from modified Helm template (since Helm does not allow to configure dynamic app provisioning)

### Client Details
- Tsh version: Teleport v8.1.1 git: go1.17.6
- Computer OS: MacOS Monterey M1
- Installed via: brew
- Additional details: none

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

tctl --debug:

```
tctl create -f example.yaml --debug
DEBU             Debug logging has been enabled. common/tctl.go:288
DEBU             No config file or identity file, loading auth config via extension. common/tctl.go:314
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/myuser/.tsh/keys/tele.mydomain.com/myuser-x509.pem" valid until "2022-02-04 00:48:30 +0000 UTC". client/keystore.go:283
DEBU [KEYSTORE]  Reading certificates from path "/Users/myuser/.tsh/keys/tele.mydomain.com/myuser-ssh/tele.mydomain.com-cert.pub". client/keystore.go:306
DEBU             Found active profile. proxy:https://tele.mydomain.com:443 user:myuser common/tctl.go:409
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/myuser/.tsh/keys/tele.mydomain.com/myuser-x509.pem" valid until "2022-02-04 00:48:30 +0000 UTC". client/keystore.go:283
DEBU [KEYSTORE]  Reading certificates from path "/Users/myuser/.tsh/keys/tele.mydomain.com/myuser-ssh/tele.mydomain.com-cert.pub". client/keystore.go:306
DEBU             Setting auth server to web proxy tele.mydomain.com:443. common/tctl.go:451
DEBU             Connecting to auth servers: [{tele.mydomain.com:443 tcp }]. common/tctl.go:194
DEBU             Attempting GET tele.mydomain.com:443/webapi/find webclient/webclient.go:62
DEBU             Attempting to connect using reverse tunnel address tele.mydomain.com:3024. common/tctl.go:232
DEBU             Attempting GET tele.mydomain.com:3024/webapi/find webclient/webclient.go:62
DEBU             Attempting GET tele.mydomain.com:3024/webapi/find webclient/webclient.go:62
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:314
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:228
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:314
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:228
DEBU [CLIENT]    Validated host tele.mydomain.com:3024. client/keyagent.go:103
DEBU [CLIENT]    Validated host tele.mydomain.com:3024. client/keyagent.go:103

ERROR REPORT:
Original Error: *trace.BadParameterError types.AppV3.Spec: types.AppSpecV3.Rewrite: types.Rewrite.Headers: []*types.Header: readObjectStart: expect { or n, but found &#34;, error found in #10 byte of ...|eaders&#34;:[&#34;X-Custom-H|..., bigger context ...|c_addr&#34;:&#34;test.example.com&#34;,&#34;rewrite&#34;:{&#34;headers&#34;:[&#34;X-Custom-Header: example&#34;,&#34;X-External-Trait: {{ext|...
Stack Trace:
	/private/tmp/teleport-20220126-21302-1ml1hyi/teleport-8.1.1/lib/services/app.go:89 github.com/gravitational/teleport/lib/services.UnmarshalApp
	/private/tmp/teleport-20220126-21302-1ml1hyi/teleport-8.1.1/tool/tctl/common/resource_command.go:549 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).createApp
	/private/tmp/teleport-20220126-21302-1ml1hyi/teleport-8.1.1/tool/tctl/common/resource_command.go:277 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create
	/private/tmp/teleport-20220126-21302-1ml1hyi/teleport-8.1.1/tool/tctl/common/resource_command.go:153 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
	/private/tmp/teleport-20220126-21302-1ml1hyi/teleport-8.1.1/tool/tctl/common/tctl.go:166 github.com/gravitational/teleport/tool/tctl/common.Run
	/private/tmp/teleport-20220126-21302-1ml1hyi/teleport-8.1.1/tool/tctl/main.go:38 main.main
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/runtime/proc.go:255 runtime.main
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/runtime/asm_arm64.s:1133 runtime.goexit
User Message: types.AppV3.Spec: types.AppSpecV3.Rewrite: types.Rewrite.Headers: []*types.Header: readObjectStart: expect { or n, but found &#34;, error found in #10 byte of ...|eaders&#34;:[&#34;X-Custom-H|..., bigger context ...|c_addr&#34;:&#34;test.example.com&#34;,&#34;rewrite&#34;:{&#34;headers&#34;:[&#34;X-Custom-Header: example&#34;,&#34;X-External-Trait: {{ext|...
```

**Comment by zen** [comment]
After fiddling a bit i modified the example file as follows:

```
kind: app
version: v3
metadata:
  # Application name.
  name: example
  # Application description.
  description: "Example application"
  # Application static labels.
  labels:
    env: local
spec:
  # URI and port application is available at.
  uri: http://localhost:4321
  # Optional application public address.
  public_addr: test.example.com
  # Disable application certificate validation.
  insecure_skip_verify: true
  # Rewrites configuration.
  rewrite:
    # Rewrite the "Location" header on redirect responses replacing the
    # host with the public address of this application.
    redirect:
      - "grafana.internal.dev"
    # Headers passthrough configuration.
    headers:
      - X-Custom-Header: example
```

Simply removed "" around Header definition and this seems to work fine. Looks like some Yaml to Jason parsing error
