### ISSUE TITLE
Add Documentation for X11 Forwarding

### ISSUE THREAD

**Issue by Richard-Barrett** [gravitational/teleport#10346]
## Details
In version 8.2.0, we added the ability to utilize x11 forwarding. #9897

There is a new field in the role spec, and there is a new option in the `ssh_service` to enable `x11` forwarding:

```yaml
ssh_service:
  enabled: yes
  x11:
    enabled: yes
```

Our docs make no mention of this parameter or its enablement.
The teleport configuration reference does not have this and it should be added.

### Category

- New Feature
