### ISSUE TITLE
Add ability to configure dynamic discovery to agent Helm chart

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#10362]
For dynamic discovery to work on an agent, resource labels are defined on the agent at startup, ie: 

```
app_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
```

However, it is not possible to define this in the custom helm chart, as the resources keyword is already used to define [kubernetes limits](https://goteleport.com/docs/kubernetes-access/helm/reference/#resources).

Require the ability to define resource labels to enable dynamic registration feature on kube agents
