### ISSUE TITLE
Automatic user and sudoers provisioning

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10486]
Add the ability to automatically create (and remove) users to Teleport.

For user removal, we can attempt to remove the user upon each logout. Most Linux distros won't let you do this until the last user has logged out (has to be tested).

Investigate what an MVP would look like for sudoers provisioning.

**Comment by stevenGravy** [comment]
Potentially useful for SSH Servers and Windows

**Comment by r0mant** [comment]
@lxea So it looks like we have the following requirements for this feature:

- Ability to automatically provision a Linux user if it's not present on the node.
- Ability to add the provisioned user to existing Linux groups defined in the user traits/role.
- Ability to add the provisioned user to sudoers.
- Clean up the provisioned user / sudoers changes upon logout (being careful not to remove pre-existing users).

From the configuration/UX perspective, we can update our roles to support it for example:

```yaml
kind: role
version: v5
metadata:
  name: example
spec:
  options:
    # controls whether this role supports auto provisioning of users
    auto_create_user: true
    # controls whether this role allows adding auto provisioned users to sudoers
    add_to_sudoers: true
  allow:
    node_labels:
      "*": "*"
    logins: [root, "{{internal.logins}}"]
    # new field listing Linux groups assign provisioned user to
    # should support user and identity provider traits like other fields (e.g. "logins")
    groups: [ubuntu, "{{internal.groups}}", "{{external.xxx}}"]
```

All proposed field names are to be agreed upon. I also think there should be an option to disable this on the SSH node level, similar to how some of our other settings work e.g.

```yaml
ssh_service:
    enabled: yes
    # when disabled, takes precedence over the role setting
    disable_auto_create_user: true
```

For the cleanup, we should only attempt to clean up the user if it was auto-created by Teleport and be careful not to remove users that were already present. The question is how to distinguish them esp. considering there may be multiple concurrent sessions for the same auto-provisioned user. Maybe add Teleport-created users to a special group?
