### ISSUE TITLE
RBAC for sessions not allowing session playing for windows

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10507]
### Description

**What happened**:
RBAC for sessions setting is not allowing users to replay their own windows sessions.

```yaml
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
```
**What you expected to happen**:

As with ssh sessions a user could replay their own windows sessions.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure 9.0 with desktop access
2. Use the above setting in `access` role 
3. Open desktop sessions, exit. and attempt to replay sessions.  Will just get a blank screen that appears to be playing but no interaction.  If the auditor role is added on a user can replay since that has no `where` setting.
![image](https://user-images.githubusercontent.com/60704961/155170925-8f7267bd-5fd3-484b-9840-fb59c7853afa.png)

### Server Details
- Teleport version (run `teleport version`): 9.0
- Server OS (e.g. from `/etc/os-release`): ubuntu
