### ISSUE TITLE
Configurable Cipher, KEX, and MAC.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1062]
### Problem

At the moment, Teleport does not allow you to select the ciphers, key exchange algorithms, or MAC algorithms that the client and/or server support.

This is typically not an problem, as the Go SSH library supports sensible defaults and most users would not benefit from changing the defaults. However, in certain situations it would be clearly advantageous to control this:

* If a security vulnerability in the cipher, key exchange algorithm, or MAC is discovered, Teleport users have to wait for Teleport developers (and/or Go developers) to update Teleport and then redeploy.
* In certain restricted environments where only approved cryptographic primitives can be used, Teleport is a non-starter.

### Proposed Solution

To support both sensible defaults as well as configurability, Teleport should add a optional configuration section that allows defining the cipher, key exchange algorithm, and MAC used on the server initially (and potentially follow up with allowing you to configure the client at some time in the future). If either of the three are specified, we override the sensible defaults.

At the time of writing, the SSH library we use, supports the following [ciphers](https://github.com/golang/crypto/blob/c78caca803c95773f48a844d3dcab04b9bc4d6dd/ssh/common.go#L27-L32):

```
aes128-ctr
aes192-ctr
aes256-ctr
aes128-gcm@openssh.com
arcfour256
arcfour128
```

The following [key exchange algorithms](https://github.com/golang/crypto/blob/c78caca803c95773f48a844d3dcab04b9bc4d6dd/ssh/common.go#L34-L42):

```
kexAlgoCurve25519SHA256
kexAlgoECDH256
kexAlgoECDH384
kexAlgoECDH521
kexAlgoDH14SHA1
kexAlgoDH1SHA1
```

The following [MACs](https://github.com/golang/crypto/blob/c78caca803c95773f48a844d3dcab04b9bc4d6dd/ssh/common.go#L56-L61):

```
hmac-sha2-256-etm@openssh.com
hmac-sha2-256
hmac-sha1
hmac-sha1-96
```

#### Changes to configuration

The changes would be made to the `teleport` section of the file configuration. All three fields (`ciphers`, `kex_algos`, and `mac_algos`) are optional and are a list of strings. If any of the three fields is provided, at least one value should exist for it. If no value is provided, the default values that the Go SSH library provides will be used.

```yaml
teleport:
  ciphers:
    - cipher1
    - cipher
    ...
    - cipherN
  kex_algos:
    - kex1
    - kex2
    ...
    - kexN
  mac_algos:
    - mac1
    - mac2
    ...
    - macN
```

##### Examples

A few sample configurations:

```yaml
teleport:
```

```yaml
teleport:
  ciphers:
    - aes128-ctr
  kex_algos:
    - kexAlgoCurve25519SHA256
    - kexAlgoECDH256
  mac_algos:
    - hmac-sha2-256-etm@openssh.com
    - hmac-sha2-256
    - hmac-sha1
    - hmac-sha1-96
```

#### Changes in code

The server needs to be updated to propagate configuration to [Config](https://godoc.org/golang.org/x/crypto/ssh#Config) in [ServerConfig](https://godoc.org/golang.org/x/crypto/ssh#ServerConfig).

#### Changes to documentation

We should document the these additions fields and possible values for them.
