### ISSUE TITLE
TLS field is not found in config.Database

### ISSUE THREAD

**Issue by lkwjohn** [gravitational/teleport#10687]
### Description

**What happened**:
TLS field is not found in config.Database

**What you expected to happen**:
Based on the teleport.yaml guide in https://goteleport.com/docs/setup/reference/config/, I should be able to start teleport service with tls field declared under the databases field of teleport.yaml

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Update teleport.yaml (version 2) with database service enable
2. Add a database detail (AWS RDS)
3. Enable TLS field and save teleport.yaml
4. Run teleport start

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.7 git:v8.0.7-0-geb80764 go1.17.3
- Server OS (e.g. from `/etc/os-release`): RHEL 7.9
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:
teleport.yaml file:
```
db_service:
  enabled: "yes"
  databases:
  - name: "xxx"
    description: "xxx description"
    protocol: "mysql"
    uri: "xxxxx"
    tls:
     mode: insecure
    aws:
     region: "ap-southeast-1"
```

### Debug Logs
After teleport start, encountered the following
```
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 55: field tls not found in type config.Database
```
