### ISSUE TITLE
tsh db connect using MySQL connection for RDS DB

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#10703]
### Description

**What happened**:
Customer configured RDS Postgres DB w/ external Teleport Agent. RDS instance discovered on agent side, but `tsh db connect <rds-psql-db>` command debugging and proxy debugging show that the client connection keeps trying to use the MySQL port/connection instead of Postgres.

**What you expected to happen**:
Expect `tsh db connect <rds-psql-db>` command to use postgres settings.

### Reproduction Steps
Unable to repro internally. Only reproducible in customer env. 

### Server Details
- Teleport version (run `teleport version`): 8.3.2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Client Details
- Tsh version (`tsh version`): 8.3.2
- Computer OS (e.g. Linux, macOS, Windows): Linux/macOS

### Debug Logs
`tsh db connect <rds_db>` produces the following errors on the proxy side:

```
teleport-cluster-7d7db57bbc-8lsr7 teleport 2022-02-24T22:09:21Z ERRO [DB:PROXY]  Failed to handle MySQL client connection. error:[
teleport-cluster-7d7db57bbc-8lsr7 teleport ERROR REPORT:
teleport-cluster-7d7db57bbc-8lsr7 teleport Original Error: *net.OpError read tcp 10.1.1.1:3036-&gt;10.100.1.1:42641: read: connection reset by peer
teleport-cluster-7d7db57bbc-8lsr7 teleport Stack Trace:
teleport-cluster-7d7db57bbc-8lsr7 teleport 	/go/src/github.com/gravitational/teleport/lib/multiplexer/wrappers.go:76 github.com/gravitational/teleport/lib/multiplexer.(*Conn).Detect
teleport-cluster-7d7db57bbc-8lsr7 teleport 	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:164 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).maybeReadProxyLine
teleport-cluster-7d7db57bbc-8lsr7 teleport 	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:141 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).performHandshake
teleport-cluster-7d7db57bbc-8lsr7 teleport 	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:76 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).HandleConnection
teleport-cluster-7d7db57bbc-8lsr7 teleport 	/go/src/github.com/gravitational/teleport/lib/srv/db/proxyserver.go:188 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).ServeMySQL.func1
teleport-cluster-7d7db57bbc-8lsr7 teleport 	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
teleport-cluster-7d7db57bbc-8lsr7 teleport User Message: read tcp 10.1.1.1:3036-&gt;10.100.1.1:42641: read: connection reset by peer] db/proxyserver.go:190
```

**Comment by Aharic** [comment]
Agent config:

```
  teleport.yaml: |
    teleport:
      auth_token: "/etc/teleport-secrets/auth-token"
      auth_servers: ["proxy.example.com:443"]
      log:
        severity: INFO
        output: stderr

    kubernetes_service:
      enabled: true
      kube_cluster_name: tooling-tooling-test
      labels:
        cluster: tooling
        environment: tooling-test
        group: non-production
        location: region

    app_service:
      enabled: false

    db_service:
      enabled: true
      databases:
        - name: test
          protocol: postgres
          static_labels:
            environment: tooling-test
            group: non-production
            location: oregon
          uri: rds-lb:5432

    auth_service:
      enabled: false
    ssh_service:
      enabled: false
    proxy_service:
      enabled: false
```

Proxy Config:
```
proxy_service:
      public_addr: 'proxy.example.com:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      enabled: true
```
