### ISSUE TITLE
Dynamic apps without "public_addr" break Web UI

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10794]
### Description

**What happened**:

`tctl create` does not validate that dynamic app contains `public_addr` field. This breaks Web UI app listing. Instead of app list an error message is displayed: `Expected "publicAddr" to match "[^\/]+?", but received ""`

**What you expected to happen**:

Web UI does not break. Optionally: fix tctl to validate presence of `public_addr` field.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `tctl create` dynamic app without public_addr
2. Make sure it is assigned to the app_service (otherwise it won't display such an app)
3. Visit web UI listing apps, observe error.

### Server Details
- Teleport version: v9 beta

**Comment by kimlisa** [comment]
@Tener i wasn't able to reproduce, can you give me the file you created? here is mine:
```
kind: app
version: v3
metadata:
  name: example
  description: "Example application"
  labels:
    env: local
spec:
  uri: http://localhost:4321
```
then in tctl i ran `tctl create test-app`
