### ISSUE TITLE
New Clusters should have `v5` roles version by default

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10807]
### Description

**What happened**:

While trying Moderated sessions, I wasn't able to get it work due to having `v3` versions of role. If a user creates a fresh cluster we should make v5 the default for roles.

**Comment by stevenGravy** [comment]
would also recommend not giving full permissions by default.  Maybe just event and sessions with the `where` like the `access` is now. 

```yaml
    # RBAC rules for various resources within a cluster.
    rules:
    - resources: ['*']
      verbs: ['*']
```
