### ISSUE TITLE
Do not require `bot-` prefix when using IAM method

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10854]
When you create a bot user, you use a command that looks like the following.

```
$ tctl bots add foo --roles=access
```

This created a bot with prefix `bot-` as can be seen below.

```
$ tctl bots ls
Bot  User    Roles   
---  ------- ------- 
foo  bot-foo bot-foo 
```

Which then requires the token you create to also have to have the `bot-` prefix (see the `bot_name` field below).

```yaml
kind: token
version: v2
metadata:
  # The token name is not a secret because instances must prove that they are
  # running in your AWS account to use this token.
  name: iam-token
  # Set a long expiry time, the default for tokens is only 30 minutes.
  expires: "3000-01-01T00:00:00Z"
spec:
  # Only allow bots to join using this token.
  roles: [Bot]

  # Set the join method to be IAM.
  join_method: iam

  # Define the name of the bot that will be allowed to use this token. Note,
  # the "bot-" prefix is required, the name of the bot is simply "robot".
  bot_name: bot-robot

  allow:
  # Restrict the AWS account and (optionally) ARN that can use this token.
  # This information can be obtained from running the
  # "aws sts get-caller-identity".
  - aws_account: "111111111111"
    aws_arn: "arn:aws:sts::111111111111:assumed-role/teleport-bot-role/i-*"
```

This is confusing for the following reasons.

1. The user creates a bot with name `foo`, but to operate on that bot, the user has to use `bot-foo` everywhere.
2. The user has to create the IAM method token before creating the bot, so the user has to know internal implementation details on naming before creating the bot.
