### ISSUE TITLE
Invalid elements are ignored in role validation

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10885]
### Description

**What happened**:

A invalid element like `kubernetes_group` instead of `kubernetes_groups` is ignored like below instead of an error.

```yaml
kind: role
metadata:
  # insert the name of your role here:
  name: example
spec:
  # This example defines an administrative role. It maps to Kubernetes "admin"
  # group and allows SSH to every node.
  allow:
    # This role is mapped to Kubernetes 'admin' group.
    kubernetes_group: [admin]

    # List of allowed SSH logins
    logins: [root]

    # List of node labels that users can SSH into
    node_labels:
      '*': '*'

  options:
      # Limits user credentials to 8 hours. After the time to live (TTL) expires,
      # users must re-login
      max_session_ttl: 8h0m0s
version: v4
```

becomes

```yaml
kind: role
metadata:
  name: example
spec:
  allow:
    logins:
    - root
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
version: v4
```

**What you expected to happen**:

An error on invalid elements instead of ignoring.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a  role file or create a role in the UI with a invalid tag `k8sgroup` instead of `kubernetes_groups`

### Server Details
- Teleport version (run `teleport version`): 8.3.4
