### ISSUE TITLE
700x S3 ListParts requests since 8.1.5 update

### ISSUE THREAD

**Issue by ilpianista** [gravitational/teleport#10900]
### Description

**What happened**:

We upgraded from 8.0.7 to 8.1.5 on February 8th and we got an increase in the AWS S3 billing. We identified the increase due to an amount of S3 `ListParts` requests made by teleport. We also upgraded to 8.3.3 with no effect.

**What you expected to happen**:

No change in the amount of the S3 requests.

### Server Details
- Teleport version (run `teleport version`): 8.3.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 18.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details: teleport is configured to store audit sessions on S3

```
  storage:
    type: dynamodb
    region: eu-west-1
    table_name: teleport.mycompany.cluster_state
    audit_events_uri:
      - file:///var/lib/teleport/log
      - dynamodb://teleport.mycompany.audit_events
    audit_sessions_uri: s3://mycompany-teleport-bucket/sessions
```

### Debug Logs

[10 minutes of logs after a fresh start](https://github.com/gravitational/teleport/files/8196572/teleport.log)

![AWS Cost Explorer showing ListParts requests](https://user-images.githubusercontent.com/529436/157006969-9d331458-a304-4cd3-8da8-6c852683c7ed.png)
