### ISSUE TITLE
Trait Transforms

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#11042]
### What

Admins should be able to define variables within roles which can extend claims coming from internal and external user traits.

### How

Syntax can be similar to the following:
```
kind: role
metadata:
  name: response-team
spec:
  vars:
    - name: access_group
      select: "{{external.claims['group']}}":
        - "splunk": ["dbs", "{{external.claims['group']}}"]
        # by default, allow members of the group to request access to their own group
        - ".*": "{{external.claims['group']}}"
  allow:
    db_labels:
    - owner: "{{internal.vars.access_group}}"
```

Roles should be able to take variables as parameters as well, which are defined in other roles
```
kind: role
metadata:
  name: db-admin-role
spec:
  # This role accepts a parameter "access_group". This parameter 
  # is either supplied when evaluating the role during access check 
  # and it should be present in the cert, or it is passed as a local
  # variable as a part of "search-as"
  params:
    - name: access_group
  allow:
    logins: ["{{params.access_group}}"]
    # node_labels defines what nodes this role will be allowed to search 
    # as a part of search_as request and in addition to that will be used to evaluate access
    db_labels:
       owner: "{{params.access_group}}"
```

### Why
Local variables are necessary to specify additional rules that are not available in OIDC/SAML claims. 
Teleport admins don't always have control over OIDC/SAML.
Specifying local variables allows them to add additional cases used in roles. 
Having role-local variables simplifies computation and role evaluation, as role eval keeps everything in one place.
