### ISSUE TITLE
x509 Certificate isn't valid for main domain

### ISSUE THREAD

**Issue by KeepWannabe** [gravitational/teleport#11228]
### Description

**What happened**:
I try to run command `tsh login --proxy=teleport.domain.com:3025` but got some error like  
```
Get "https://teleport.domain.com:3025/webapi/ping": x509: certificate is valid for *CLUSTER_NAME*, *.teleport.cluster.local, teleport.cluster.local, not teleport.domain.com
```

On this case im using my own .pem cert, and the /etc/teleport.yaml look like this
```
#
# A Sample Teleport configuration file.
# Creates a single proxy, auth and node server.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v2
teleport:
  nodename: u1804-Rnd-PAM
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.domain.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.domain.com:443
  https_cert_file: /home/supervisor/.ssl_domain.pem
  https_key_file: /home/supervisor/.ssl_domain_key.pem
  https_keypairs: []
  acme:
    enabled: "no"
```

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.1 git:v9.0.1-0-g7bbe6f15c go1.17.7
- Server OS (e.g. from `/etc/os-release`): 
```
- ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.1 git:v9.0.1-0-g7bbe6f15c go1.17.7
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)
