### ISSUE TITLE
Cluster Access Rule [RBAC]

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1125]
## Proposal

Consider example:

```yaml
kind: role
version: v3
metadata:
  name: "developer"
spec:
  allow:
      rules:
          - resources: ["clusters"]
            verbs: ["TBD"]
```

@russjones lets discuss monday/10th
