### ISSUE TITLE
Unable to link nodes to a cluster/master

### ISSUE THREAD

**Issue by Kainzo** [gravitational/teleport#1134]
Using > sudo tctl nodes add
I got the invite token and copy/pasted it on a node (not on the same network) - this is what I get.

05:49 PM ethos@07635a 10.0.0.19 [169.1 hash] /home/ethos # teleport start --roles=node --token=XXXXXXXXXX--auth-server=x.x.x.x:3025                                                   
open /var/lib/teleport/host_uuid: permission denied, initializing teleport

**Comment by klizhentas** [comment]
It means that your node can't read/write to the directory `/var/lib/teleport`

**Comment by Kainzo** [comment]
It has SUDO - why would that be? doesnt make any sense to me...

**Comment by klizhentas** [comment]
teleport start does not have sudo so it can't access the directory, check the directory for permissions

**Comment by Kainzo** [comment]
Alright, I see the issue here, I did a chmod -R 777 /var/lib/teleport and now its giving me this error.

> access denied to '2f3e37cf-9144-40ec-8975-6622329d043a.2f3e37cf-9144-40ec-8975-6622329d043a': bad username or credentials

**Comment by kontsevoy** [comment]
@Kainzo I would suggest you wipe out the content of `/var/lib/teleport` (because it's unclear what happened earlier with your permissions) and start following the Quick Start manual from the beginning.

**Comment by Kainzo** [comment]
Hey @kontsevoy I've been following the guide but I have a weird locked down system.

Should I blow up the filesystem on the Master or the attempted node?
I reinstalled with root on the node I want to add and its still coming up with "Bad username or credentials" - I feel like I may be missing something very simple.

**Comment by kontsevoy** [comment]
That sounds like a token mismatch. Whatever token you're passing to your node needs to match the token in the auth server config file. See `examples/local-cluster` directory, it has configs for auth + node.

**Comment by kontsevoy** [comment]
Auth server config example:
```
teleport:
  nodename: graviton-auth
  data_dir: .data
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:5000
  tokens:
     - "proxy,node:SECRET_TOKEN"
```

Node config:
```
teleport:
  nodename: graviton-node
  auth_token: SECRET_TOKEN
  auth_servers:
  - ip-of-auth-server
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "no"
auth_service:
  enabled: "no"
```
