### ISSUE TITLE
Default User Role

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1136]
## Problem

For local users in Teleport (and Enterprise), we create a role for every user. However, all of these roles are identical other than the list of allowed logins. While roles are not exposed to users in open source Teleport, they are in Enterprise.

## Solution

With https://github.com/gravitational/teleport/issues/1120 we now have the machinery which allows us to use a single role across multiple users using role variables. We can consolidate all local users to a single default role for Teleport and Enterprise. In Enterprise users would be able to create additional roles and assign users to them, but by default would use the same single default role as Teleport.

## Implementation

I propose the following role named `Default` with the variable `{{internal.logins}}` as an allowed login. This variable should only be filled out by a system administrator when using local logins. This would be transparent to both Teleport and Enterprise users (they would not know they are using roles or role variables) because the `tctl users add ...` command would be used to set the traits on a `services.User` which would then be used to populate this role.

```yaml
RoleV3{
    Kind:    KindRole,
    Version: V3, 
    Metadata: Metadata{
        Name:      "Default",
        Namespace: defaults.Namespace,
    },
    Spec: RoleSpecV3{
        Options: RoleOptions{
            MaxSessionTTL: NewDuration(defaults.MaxCertDuration),
        },
        Allow: RoleConditions{
            Namespaces:      []string{defaults.Namespace},
            Logins:          []string{"{{internal.logins}}"}, 
            NodeLabels:      map[string]string{Wildcard: Wildcard},
            SystemResources: utils.CopyStringMapSlices(DefaultUserSystemResources),
        },
    },
}
```
### UX Changes

No changes for Teleport because Teleport does not expose roles to users.

For Enterprise, when running `tctl get roles`, by default users will only see a single role.

```
$ tctl get roles
Role          Allowed to login as         Node Labels      Rules
----          -------------------         ------------     -----------------
Default       {{internal.logins}}         <all nodes>      To be decided...
```

### Code Changes

**Create a default role**

When starting Teleport, always upsert the default role like we do the default namespace.

https://github.com/gravitational/teleport/blob/master/lib/auth/init.go#L208

**User Creation**

When creating a user, populate `AllowedLogins` in `services.UserV1` as before. During the conversion to `services.UserV2` copy this to to `logins` within the trait map.

https://github.com/gravitational/teleport/blob/master/tool/tctl/common/tctl.go#L316-L350
https://github.com/gravitational/teleport/blob/master/lib/auth/new_web_user.go#L174-L230

**Web UI**

When getting a list of users that can be logged in as, use `FetchRoles` so that we don't show users role variables.

https://github.com/gravitational/teleport/blob/master/lib/web/apiserver.go
https://github.com/gravitational/teleport/blob/master/lib/web/ui/roleaccess.go
