### ISSUE TITLE
Helm chart teleport-cluster: "Multi-Attach error for volume" when upgrading via "helm upgrade"

### ISSUE THREAD

**Issue by johanneskastl** [gravitational/teleport#11484]
### Description

I am running the teleport-cluster helm chart in my Kubernetes cluster.

Here is the values.yaml:
```
clusterName: teleport.<redacted>
kubeClusterName: nucs.<redacted>

standalone:
  volumeSize: 1Gi
service:
  type: ClusterIP
highAvailability:
  certManager:
    enabled: true
    issuerName: letsencrypt-production
    issuerKind: ClusterIssuer

podSecurityPolicy:
  enabled: false
```
**What happened**:

When upgrading via ` helm upgrade teleport-cluster teleport/teleport-cluster --namespace=teleport-cluster -f Teleport_Cluster/values.yaml` I get a second replicaset in the namespace, so I have one for the previous/running version and one for the one that I want to upgrade to.

However the pod for the new replicaset never starts, as it cannot attach to the volume:

```
Multi-Attach error for volume "pvc-2f570303-c1ee-43bb-b847-06686095b078" Volume is already used by pod(s) teleport-cluster-8487459d6c-gs2hb
  Warning  FailedMount             2m13s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-spk8f teleport-tls config]: timed out waiting for the condition
```

I can manually scale the old replicaSet to only 1 replica, then the volume can get attached and the new pod starts running and everything is fine.

**What you expected to happen**:

Ideally the upgrade would succeed without manual interaction.

**Possible solution**:

The default strategy for a deployment is `RollingUpdate`, if it is not set. It might be a good idea to use the `Recreate` strategy, as a rolling Upgrade is not possible due to the volume being only attachable to one pod.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install teleport-cluster via helm chart in older version
2. wait for everything to run
3. upgrade to latest version using `helm upgrade ...`

### Server Details
- Teleport version (run `teleport version`): 8.3.4 => 9.0.0 => 9.0.1 => 9.0.2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Three-node K3s cluster on baremetal
