### ISSUE TITLE
Duplicate Session Recordings

### ISSUE THREAD

**Issue by mattmelgard** [gravitational/teleport#11595]
### Description

**What happened**:

I'm using the open source, Helm-deployed HA Teleport cluster, and for some reason I'm seeing continual duplicates of session recordings for a particular user, even though they're not actively exec-ing into any pods, as seen below:

![Screen Shot 2022-03-30 at 4 14 05 PM](https://user-images.githubusercontent.com/14903000/160943025-80c16645-2c1c-4446-babe-d0ba74898da2.png)

**What you expected to happen**:

Session recordings to be recorded and show up in the UI once rather than many times.

### Reproduction Steps
> As minimally and precisely as possible, describe step-by-step how to reproduce the problem.

Not sure if I have exact steps to reproduce, but the values I'm using to install the cluster are fairly simple:

```yaml
chartMode: gcp
clusterName: "teleport.syndio.dev"
kubeClusterName: "realms"

authenticationType: github
authenticationSecondFactor:
  secondFactor: "on"

labels:
  env: realms
gcp:
  projectId: "realms-b5c8de3d"
  backendTable: "teleport-helm-backend"
  auditLogTable: "teleport-helm-events"
  sessionRecordingBucket: "realms-teleport-helm-sessions"
  credentialSecretName: teleport-gcp-credentials
highAvailability:
  replicaCount: 3
  requireAntiAffinity: false
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  certManager:
    issuerName: "letsencrypt-prod"

annotations:
  service:
    external-dns.alpha.kubernetes.io/hostname: "teleport.syndio.dev,*.teleport.syndio.dev"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
```

Aside from those values, I basically followed the HA Kubernetes cluster guide as closely as possible. Only major difference is that we use the [Cloudflare issuer](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/) with our cert-manager deployment and external-dns for creation of DNS records.

For configuration of the cluster itself, we use the basic GitHub SSO connection, and have two roles, one for our platform team and one for our backend team. I'm happy to share what that looks like here if requested.

### Server Details
- Teleport version (run `teleport version`):

`Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7`

- Server OS (e.g. from `/etc/os-release`):
```
root@teleport-89b8d75d-6znfp:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
GCP/GKE

- Additional details:

### Client Details
- Tsh version (`tsh version`):

`Teleport v9.0.0 git: go1.17.8`

- Computer OS (e.g. Linux, macOS, Windows):

macOS

- Browser version (for UI-related issues):

Chrome (latest)

- Installed via (e.g. apt, yum, brew, website download):

N/a

- Additional details:

None that I can think of

### Debug Logs
> Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
> - Start Teleport with --debug flag (`teleport --debug`)
> - Run tsh with --debug flag (`tsh --debug`)

Can provide these as needed, but I'd prefer to hear back from maintainers first to determine what kind of information would be useful.

**Comment by zmb3** [comment]
Hmmm. This is a new one!

This table is populated by looking for session.end events. 

If you look at the audit log page, do you see multiple session.end events for the same session ID, or only a single one?

**Comment by mattmelgard** [comment]
@zmb3 seems like there's multiple:

![Screen Shot 2022-03-30 at 5 19 23 PM](https://user-images.githubusercontent.com/14903000/160946277-3ef4961a-b091-4eb1-be5a-84b9814a6d9d.png)

**Comment by zmb3** [comment]
That @mattmelgard - that gives us something to go on.

Out of curiosity - are you running multiple auth servers?

**Comment by mattmelgard** [comment]
As far as I'm aware, no. I set replicas to 3 for high availability so there are 3 teleport pods, but I don't know what topology that sets up by default using the [HA Teleport Cluster deployment setup](https://goteleport.com/docs/kubernetes-access/helm/guides/gcp/).

**Comment by mattmelgard** [comment]
As far as logs go, this is generally what I see over and over again:
```
teleport-89b8d75d-c5kdg teleport {"ei":0,"event":"session.end","uid":"a1657787-013e-43f1-b5c2-3b6ddcac4c53","code":"T2004I","time":"2022-03-31T14:10:23.481Z","cluster_name":"teleport.syndio.dev","user":"melaniedavila","login":"melaniedavila","sid":"7dcb9fcb-eb09-487a-af1d-693a58697df7","addr.remote":"127.0.0.1:48976","proto":"kube","namespace":"default","server_id":"dd32feff-fa5a-4f37-af7a-7f9c65a47003","server_hostname":"teleport.syndio.dev","enhanced_recording":false,"interactive":true,"participants":["melaniedavila"],"session_start":"2022-03-25T19:49:30.304Z","session_stop":"2022-03-25T19:49:50.212Z","kubernetes_cluster":"realms","kubernetes_users":["melaniedavila"],"kubernetes_groups":["engineering","system:authenticated"],"kubernetes_pod_name":"payeq-scratch-69b944d887-fzhqw","kubernetes_pod_namespace":"demo","kubernetes_container_name":"payeq-scratch","kubernetes_container_image":"gcr.io/realms-b5c8de3d/payeq:17f7c08","kubernetes_node_name":"gke-syndio-default-payeq-apps-n2d-cus-6d839044-8hw9","initial_command":["bash"],"session_recording":"node"}
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:10:23Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"0efec928-59ca-40cc-bbd8-a0c08b5793c3","url":"gs://0efec928-59ca-40cc-bbd8-a0c08b5793c3.tar/0efec928-59ca-40cc-bbd8-a0c08b5793c3"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"a6d54b3b-b806-43ee-87c9-8936718817f8","url":"gs://a6d54b3b-b806-43ee-87c9-8936718817f8.tar/a6d54b3b-b806-43ee-87c9-8936718817f8"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"a44a9710-5c5e-410e-a1b6-c6cf71f6b5d0","url":"gs://a44a9710-5c5e-410e-a1b6-c6cf71f6b5d0.tar/a44a9710-5c5e-410e-a1b6-c6cf71f6b5d0"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"065de74a-df0c-4923-9ecb-d9961fcfa74e","url":"gs://065de74a-df0c-4923-9ecb-d9961fcfa74e.tar/065de74a-df0c-4923-9ecb-d9961fcfa74e"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"af0c19e9-a7cd-4e79-bf17-c628d5bfc165","url":"gs://af0c19e9-a7cd-4e79-bf17-c628d5bfc165.tar/af0c19e9-a7cd-4e79-bf17-c628d5bfc165"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"bfd43a54-db77-4dd7-920f-7a125d42b42b","url":"gs://bfd43a54-db77-4dd7-920f-7a125d42b42b.tar/bfd43a54-db77-4dd7-920f-7a125d42b42b"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"cff0ab33-1afa-47e4-bfa7-9a65534d932f","url":"gs://cff0ab33-1afa-47e4-bfa7-9a65534d932f.tar/cff0ab33-1afa-47e4-bfa7-9a65534d932f"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"7dcb9fcb-eb09-487a-af1d-693a58697df7","url":"gs://7dcb9fcb-eb09-487a-af1d-693a58697df7.tar/7dcb9fcb-eb09-487a-af1d-693a58697df7"}
teleport-89b8d75d-c5kdg teleport {"ei":2147483647,"event":"session.upload","code":"T2005I","time":"0001-01-01T00:00:00Z","sid":"1b17a2a8-034b-4811-8a90-a6de79b7ec3f","url":"gs://1b17a2a8-034b-4811-8a90-a6de79b7ec3f.tar/1b17a2a8-034b-4811-8a90-a6de79b7ec3f"}
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:21Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:21Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:21Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:22Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:22Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:22Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:23Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:23Z INFO [AUTH:COMP] got first event *events.SessionStart events/complete.go:221
teleport-89b8d75d-c5kdg teleport 2022-03-31T14:20:23Z INFO [AUTH:COMP] emitting *events.SessionEnd event for completed session 7dcb9fcb-eb09-487a-af1d-693a58697df7 events/complete.go:288
```

**Comment by zmb3** [comment]
In the screenshot, it looks like only user `melaniedavila`'s sessions are duplicated, and `mattmelgard`'s are not.

Is this just due to small sample size in the screenshot, or does this pattern appear to hold?

**Comment by mattmelgard** [comment]
Seems to just be that user for whatever reason. I checked with the user and they didn't seem to have anything odd going on when creating the session, at least from what I can tell.

**Comment by mattmelgard** [comment]
Just to add another data point to this, it does seem like the duplicate recordings stopped showing up in the UI yesterday, and I think that was due to @melaniedavila creating a new session

**Comment by zmb3** [comment]
👋 Hi @melaniedavila - thanks for joining the party!

We'll try to reproduce and see what we can find out. Please let us know if the issue starts reoccurring or if you think of anything else that may have changed since it stopped happening.

**Comment by mattmelgard** [comment]
> Just to add another data point to this, it does seem like the duplicate recordings stopped showing up in the UI yesterday, and I think that was due to @melaniedavila creating a new session

Seems I spoke to soon and these are actually back again unfortunately. @melaniedavila do you know if you closed your last session gracefully, or was it some kind of timeout or closing of the terminal?

**Comment by zmb3** [comment]
One thing to try, if you don't have a huge load, would be to temporarily scale down to a single auth server pod.

Your duplicate session.end events do appear to be in groups of 3, and you have 3 auth pods today..

We recently added a random jitter so that the auth pods don't all attempt to complete at the same time, which may help with this issue.

**Comment by melaniedavila** [comment]
> Seems I spoke to soon and these are actually back again unfortunately. @melaniedavila do you know if you closed your last session gracefully, or was it some kind of timeout or closing of the terminal?

@mattmelgard, the last session was closed due to timeout.

**Comment by mattmelgard** [comment]
@zmb3 just checking in to see if there's been any activity on this. Unfortunately I can't scale down to a single cluster pod with the way the chart is configured ([HA mode is enabled by the number of replicas](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L181) and different TLS options are used depending on the mode). I'm still seeing this bug in the 10.0.0 version of the chart as well.

**Comment by zmb3** [comment]
Hey @mattmelgard - thanks for bringing this back to my attention.

I've actually done some research into this area in the past 2 weeks and I believe this will be fixed when https://github.com/gravitational/teleport/pull/14521 is merged. 

To help confirm this theory, can you let me know:

- what session recording mode do you have configured? (look for `session_recording` in the auth server section of your teleport.yaml)
- What services are running in each of your 3 teleport pods?

**Comment by mattmelgard** [comment]
> Hey @mattmelgard - thanks for bringing this back to my attention.
> 
> I've actually done some research into this area in the past 2 weeks and I believe this will be fixed when #14521 is merged.
> 
> To help confirm this theory, can you let me know:
> 
> * what session recording mode do you have configured? (look for `session_recording` in the auth server section of your teleport.yaml)
> * What services are running in each of your 3 teleport pods?

To answer your first question - we're just using the default values for that configuration that are [provided by the chart](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L35). For the second question, that again really depends on the default behavior of the chart, but I don't see any sort of Kubernetes command entrypoint provided to the pods themselves, just the image used (`quay.io/gravitational/teleport:10.0.0`). I can try to dig in deeper if you like, but I'm basically just using the exact steps provided in the official guide for installing an [HA teleport cluster using Helm over GCP](https://goteleport.com/docs/setup/helm-deployments/gcp/).

**Comment by mattmelgard** [comment]
If I `cat` the config file on one of the pods, this is what I see:
```
teleport:
  log:
    severity: INFO
    output: stderr
    format:
      output: text
      extra_fields: ["timestamp","level","component","caller"]
  storage:
    type: firestore
    project_id: global-57d90528
    collection_name: teleport-cluster-backend
    credentials_path: /etc/teleport-secrets/gcp-credentials.json
    audit_events_uri: ['firestore://teleport-cluster-events?projectID=global-57d90528&credentialsPath=/etc/teleport-secrets/gcp-credentials.json', 'stdout://']
    audit_sessions_uri: "gs://teleport-cluster-sessions?projectID=global-57d90528&credentialsPath=/etc/teleport-secrets/gcp-credentials.json"
auth_service:
  enabled: true
  cluster_name: teleport.syndio.dev
  authentication:
    type: github
    second_factor: on
    webauthn:
      rp_id: teleport.syndio.dev
kubernetes_service:
  enabled: true
  listen_addr: 0.0.0.0:3027
  kube_cluster_name: global
  labels:
    env: global
proxy_service:
  public_addr: 'teleport.syndio.dev:443'
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
  enabled: true
  https_keypairs:
  - key_file: /etc/teleport-tls/tls.key
    cert_file: /etc/teleport-tls/tls.crt
ssh_service:
  enabled: false
```
