### ISSUE TITLE
SSH Moderated Sessions will work if only one role matches. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11601]
### Description

**What happened**:

I was using the below role. I would expect that it would require one person from `secops` and one person from `auditor`. When testing the session would happen if one person joins.

```
kind: role
metadata:
  id: 1648673364083158390
  name: devops
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_groups:
    - system:masters
    kubernetes_labels:
      '*': '*'
    logins:
    - '{{internal.logins}}'
    - root
    - ubuntu
    node_labels:
      '*': '*'
    require_session_join:
    - count: 1
      filter: contains(user.roles, "secops")
      kinds:
      - k8s
      - ssh
      modes:
      - peer
      - moderator
      - observer
      name: Security Team
      on_leave: ""
    - count: 1
      filter: contains(user.roles, "audit")
      kinds:
      - k8s
      - ssh
      modes:
      - peer
      - moderator
      - observer
      name: Security Team
      on_leave: ""
  deny: {}
  options:
    cert_format: standard
    desktop_clipboard: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v5
```
**What you expected to happen**:
Must wait for the second party to join.
