### ISSUE TITLE
tctl create should issue warning when it discards invalid fields

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#11670]
### Description

**What happened**:

When trying to use the iam token method with an 8.3.x backend, the `tctl create -f` command was silently discarding the `join_method` field. This was not clear why it was happening until we realized that it was a tctl 8.2.0 binary that didn't understand it.

In the case where the object is created successfully anyway, it can be very confusing as to why teleport has discarded part of the object.

Please note that this request is for a behavior change to tctl for similar situations going forward and it is not specifically about this particular scenario.

**What you expected to happen**:

If `tctl create` discards any part of the yaml (other than comments) for any reason, it should be at least noted as a warning. This will help not only situations where there is a version mismatch, but unintentional typos too.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.

With a teleport 8.3.x backend and a tctl 8.2.0 client, attempt to create an iam token.

```
echo <<EOF
kind: token
metadata:
  expires: "3000-01-01T00:00:00Z"
  name: iam-token
spec:
  allow:
  - aws_account: "1111111111111111"
  aws_iid_ttl: 1h0m0s
  roles:
  - Node
  join_method: iam
version: v2
EOF | tctl create -f 
```

After created, run `tctl get token/iam-token` and note that join_method is missing.

Other situations where yaml is discarded may happen too, so any discarding behavior should result in a warning.

### Server Details
- Teleport version (run `teleport version`): 8.3.6
- Server OS (e.g. from `/etc/os-release`): cloud
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): cloud

### Client Details
- Tsh version (`tsh version`): 8.2.0
- Tctl version: 8.2.0
- Computer OS (e.g. Linux, macOS, Windows): macos
