### ISSUE TITLE
Unable to establish connection to teleport cluster

### ISSUE THREAD

**Issue by ilbarone87** [gravitational/teleport#11686]
### Description

**What happened**: If I try to add a server to my teleport cluster the node is unable to establish a connection to the cluster. Also tried with tsh command but connection get refused. No issue accessing the Web GUI at teleport.domain.synology.me

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.copy "add server" script from web GUI on teleport.domain.synology.me
2. paste the script in node terminal
3.

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.1 git:v9.0.1-0-g7bbe6f15c go1.17.7
- Server OS (e.g. from `/etc/os-release`): Ubuntu server 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): RKE 1.21.9
- Additional details: using teleport just internally, the reverse proxy is handled by my Synology NAS and DNS server by pi-hole

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.1 git:v9.0.1-0-g7bbe6f15c go1.17.7
- Computer OS (e.g. Linux, macOS, Windows): Ubuntu Server 20.04
- Browser version (for UI-related issues): 
- Installed via (e.g. apt, yum, brew, website download): script
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
```
Apr 02 17:18:28 shinobicctv systemd[1]: Started Teleport SSH Service.
Apr 02 17:18:28 shinobicctv teleport[3976528]: 2022-04-02T17:18:28Z INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:382
Apr 02 17:18:28 shinobicctv teleport[3976528]: 2022-04-02T17:18:28Z INFO [AUTH]      Attempting registration via proxy server. auth/register.go:173
Apr 02 17:18:28 shinobicctv teleport[3976528]: 2022-04-02T17:18:28Z INFO [AUTH]      Successfully registered via proxy server. auth/register.go:180
Apr 02 17:18:28 shinobicctv teleport[3976528]: 2022-04-02T17:18:28Z INFO [PROC:1]    Node has obtained credentials to connect to the cluster. service/connect.go:416
Apr 02 17:18:28 shinobicctv teleport[3976528]: 2022-04-02T17:18:28Z ERRO [PROC:1]    Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining
```

- Run tsh with --debug flag (`tsh --debug`)
```
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/admingb/.tsh/keys/teleport.domain.synology.me/admingb-x509.pem" valid until "2022-04-03 04:59:26 +0000 UTC". client/keystore.go:285
DEBU [KEYSTORE]  Reading certificates from path "/home/admingb/.tsh/keys/teleport.domain.synology.me/admingb-ssh/teleport.seppthebaron87.synology.me-cert.pub". client/keystore.go:308
INFO [CLIENT]    no host login given. defaulting to admingb client/api.go:1123
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:3021
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/admingb/.tsh/keys/teleport.domain.synology.me/admingb-x509.pem" valid until "2022-04-03 04:59:26 +0000 UTC". client/keystore.go:285
DEBU [KEYSTORE]  Reading certificates from path "/home/admingb/.tsh/keys/teleport.domain.synology.me/admingb-ssh/teleport.domain.synology.me-cert.pub". client/keystore.go:308
INFO [KEYAGENT]  Loading SSH key for user "admingb" and cluster "teleport.domain.synology.me". client/keyagent.go:191
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.domain.synology.me:443 client/api.go:2986
DEBU             Attempting GET teleport.domain.synology.me:443/webapi/ping webclient/webclient.go:62
Enter password for Teleport user admingb:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.seppthebaron87.synology.me:443 client/api.go:2986
DEBU [CLIENT]    HTTPS client init(proxyAddr=teleport.domain.synology.me:443, insecure=false) client/weblogin.go:223
Enter an OTP code from a device: 821488

DEBU [KEYAGENT]  Adding CA key for teleport.domain.synology.me client/keyagent.go:313
DEBU [KEYSTORE]  Adding known host teleport.domain.synology.me with proxy teleport.seppthebaron87.synology.me and key: SHA256:xxxx client/keystore.go:551
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/admingb/.tsh/keys/teleport.domain.synology.me/admingb-x509.pem" valid until "2022-04-03 04:59:26 +0000 UTC". client/keystore.go:285
DEBU [KEYAGENT]  Deleting obsolete stored key with index {ProxyHost:teleport.domain.synology.me Username:admingb ClusterName:teleport.seppthebaron87.synology.me}. client/keyagent.go:514
INFO [KEYAGENT]  Loading SSH key for user "admingb" and cluster "teleport.domain.synology.me". client/keyagent.go:191
INFO [CLIENT]    Connecting proxy=teleport.domain.synology.me:3023 login="root" client/api.go:2218

ERROR REPORT:
Original Error: *net.OpError dial tcp 10.10.10.137:3023: connect: connection refused
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2267 github.com/gravitational/teleport/lib/client.makeProxySSHClient
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2220 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToProxy
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2139 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToProxy.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: failed to authenticate with proxy teleport.domain.synology.me:3023
        dial tcp 10.10.10.137:3023: connect: connection refused

```

- This is my teleport.yaml if can help:

```
teleport.yaml: |
    teleport:
      ca_pin: "sha256:2da0b178c17f4f080ce7aeeda15e29aba12aff0950524795e114d5d0cdce5e1c"
      log:
        severity: INFO
        output: stderr
        format:
          output: text
          extra_fields: ["timestamp","level","component","caller"]
    auth_service:
      enabled: true
      cluster_name: teleport.domain.synology.me
      tokens:
        - node:RANDOM
      authentication:
        type: local
        second_factor: on
        webauthn:
          rp_id: teleport.domain.synology.me
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: teleport.domain.synology.me
    proxy_service:
      public_addr: 'teleport.domain.synology.me:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      listen_addr: 0.0.0.0:3023
      web_listen_addr: 0.0.0.0:3080
      tunnel_listen_addr: 0.0.0.0:3024
      https_cert_file: /test/archive/RSA-cert.pem
      https_key_file:  /test/archive/RSA-privkey.pem
      enabled: true
      acme:
        enabled: false
        email: teleport@domaincom
    ssh_service:
      enabled: true

```

Thanks for your help
