### ISSUE TITLE
KubeVirt VM console not working when Kubernetes API is proxied via Teleport

### ISSUE THREAD

**Issue by pennycoders** [gravitational/teleport#11712]
### Description

**What happened**:

KubeVirt's **virtctl console** and **virtctl vnc vm01 --proxy-only** not working when accessing the Kubernetes API via Teleport

On the teleport cluster's side the following error output is present:

```bash
2022-04-04T19:03:35Z ERRO [PROXY:PRO] Unable to hijack the connection: does not implement http.Hijacker forward/fwd.go:268
2022/04/04 19:03:35 http: panic serving 10.42.0.1:50924: runtime error: invalid memory address or nil pointer dereference
goroutine 36015064 [running]:
net/http.(*conn).serve.func1()
	/opt/go/src/net/http/server.go:1802 +0xb9
panic({0x41759c0, 0x7e8d000})
	/opt/go/src/runtime/panic.go:1047 +0x266
github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).formatResponseError(0xc00173a000, {0x57da6a0, 0xc000ef95f0}, {0x0, 0x0})
	/go/src/github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:466 +0x4e
github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).formatForwardResponseError(...)
	/go/src/github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:457
github.com/gravitational/oxy/utils.ErrorHandlerFunc.ServeHTTP(0x4791db1, {0x57da6a0, 0xc000ef95f0}, 0x0, {0x0, 0x0})
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/utils/handler.go:37 +0x43
github.com/gravitational/oxy/forward.(*websocketForwarder).serveHTTP(0xc0032aba20, {0x57da6a0, 0xc000ef95f0}, 0x462f680, 0xc0032aba40)
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/forward/fwd.go:269 +0xbf0
github.com/gravitational/oxy/forward.(*Forwarder).ServeHTTP(0xc00000fa58, {0x57da6a0, 0xc000ef95f0}, 0xc00000e210)
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/forward/fwd.go:170 +0x55
github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).catchAll(0xc00173a000, 0xc0023a5770, {0x57e8d70, 0xc0037d07e0}, 0xc0019e8b00)
	/go/src/github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:1215 +0x37b
github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuthStd.func1({0x57e8d70, 0xc0037d07e0}, 0xc0019e8b00)
	/go/src/github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:439 +0xe2
github.com/gravitational/teleport/lib/httplib.MakeStdHandlerWithErrorWriter.func1({0x57e8d70, 0xc0037d07e0}, 0x0)
	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:90 +0x63
net/http.HandlerFunc.ServeHTTP(0xc00173a018, {0x57e8d70, 0xc0037d07e0}, 0xc00259caf0)
	/opt/go/src/net/http/server.go:2047 +0x2f
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00173a018, {0x57e8d70, 0xc0037d07e0}, 0xc0019e8b00)
	/tmp/gomodcache/github.com/julienschmidt/httprouter@v1.3.0/router.go:448 +0x649
github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP(0x582f8d8, {0x57e8d70, 0xc0037d07e0}, 0x5728830)
	/go/src/github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:303 +0x29
github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP(0xc00190c640, {0x57e8d70, 0xc0037d07e0}, 0xc0019e8900)
	/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:550 +0x35d
github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc000e92d00, {0x57e8d70, 0xc0037d07e0}, 0xc0019e8900)
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/ratelimit/tokenlimiter.go:118 +0x1ce
github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc00142e720, {0x57e8d70, 0xc0037d07e0}, 0x10000c00170a9f0)
	/tmp/gomodcache/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/connlimit/connlimit.go:75 +0x326
net/http.serverHandler.ServeHTTP({0xc001e7d500}, {0x57e8d70, 0xc0037d07e0}, 0xc0019e8900)
	/opt/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0031c8c80, {0x582f980, 0xc0015cc390})
	/opt/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:3034 +0x4e8
```

**What you expected to happen**:

I would have expected the same behaviour as a non-proxied kubernetes-api connection

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install KubeVirt on the cluster side
2. Install virtctl (The KubeVirt client) on the client side 
3. Create a sample VM (for instance, something similar to the one below, by using KubeVirt)

```yaml
kind: VirtualMachine
metadata:
  name: vm01
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm01
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 2Gi
            cpu: 2000m
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          - name: lan01
            bridge: {}
            bootOrder: 2
          - name: lan02
            bridge: {}
            bootOrder: 3
      networks:
      - name: default
        pod: {}
      - name: lan01
        multus:
          networkName: lan01
      - name: lan02
        multus:
          networkName: lan02
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIG5hbWU6IGRlbW8KICAgIGxvY2tfcGFzc3dkOiBmYWxzZQogICAgcGxhaW5fdGV4dF9wYXNzd2Q6IFA0c3N3b3JkCiAgICBzdWRvOiBbJ0FMTD0oQUxMKSBOT1BBU1NXRDpBTEwnXQogICAgZ3JvdXBzOiBzdWRvCiAgICBzaGVsbDogL2Jpbi9iYXNoCnJ1bmNtZDoKICAtIHVzZXJtb2QgLS1leHBpcmVkYXRlICcnIGRlbW8=
```
4. Install the virtctl binary as described in the official KubeVirt documentation: <https://kubevirt.io/user-guide/operations/virtctl_client_tool/>
5. Attempt connecting to the VM using any of the following methods:

```bash
virtctl console vm01
```
or
```bash
virtctl vnc vm01 --proxy-only
```

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7
- Server OS (e.g. from `/etc/os-release`): 
```bash
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated hardware
- Additional details: The teleport server was running within a Kubernetes cluster, where it was deployed using the official Helm chart

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download):  Website Download
- Additional details: Kubectl proxy works as expected

### Debug Logs
N/A
