### ISSUE TITLE
Provide documentation example on generating labels from AWS tags 

### ISSUE THREAD

**Issue by mechastorm** [gravitational/teleport#1175]
It would be great if the documentation provided examples on how to generate labels from AWS tags. There is a section on dynamic labels and the command examples are helpful for system info but it would be good to have an official example on how to get labels from AWS tags as well.

I am trying to figure out the current command myself so I can provide this example myself but I can't seem to get it to work

Here is a snippet of my YAML with the command
```yaml
      - name: name
        command: >
          [aws ec2 describe-tags --filters "Name=resource-id,Values=$(ec2-metadata --instance-id | cut -f2 -d " ")" "Name=key,Values=Name" --region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region) --output=text | cut -f5]
        period: 5m0s
      - name: environment
        command: >
          [aws ec2 describe-tags --filters "Name=resource-id,Values=$(ec2-metadata --instance-id | cut -f2 -d " ")" "Name=key,Values=environment" --region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region) --output=text | cut -f5]
        period: 5m0s
```

Yet when I start teleport with the commands above I get
```
  line X: cannot unmarshal !!str `[aws ec...` into []string
  line Y: cannot unmarshal !!str `[aws ec...` into []string
```
When X and Y corresponds to my command I am trying to run. Any suggestion to what should the command be that is parsable by Teleport.

The one sure solution is for me to upload a custom bash script to the server and have Teleport run the bash script. But I prefer not to do that and have a one liner command.

Any ideas on this?
