### ISSUE TITLE
helm chart should be able to populate dynamodb scaling options in teleport.yaml

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#12046]
### What

The teleport-cluster helm chart currently doesn't have a way for a user to specify [dynamodb settings](https://goteleport.com/docs/ver/9.0/setup/reference/backends/#dynamodb-autoscaling) such as:

```
teleport:
  storage:
    continuous_backups: [true|false]
    auto_scaling:  [true|false]
    read_min_capacity: int
    read_max_capacity: int
    read_target_value: float
    write_min_capacity: int
    write_max_capacity: int
    write_target_value: float
```

### How

There should be a provision in the values to set those settings and have them appear in the rendered teleport.yaml in the configmap.

### Why

When helm fires up teleport and teleport creates/configures the dynamodb on the backend, it should be possible to set the dynamo settings through the same interface to keep all the relevant deployment for a given helm release in one place (the release's values)

### Workaround

implement an out-of-band approach such as switching to standalone mode for the chart, manual steps to configure dynamo, or completely separate automation from helm for that dynamo instance.

gz#4818

gz#5153
