### ISSUE TITLE
Prefix Teleport Metrics with `teleport_` for Prometheus Best Practices

### ISSUE THREAD

**Issue by Richard-Barrett** [gravitational/teleport#12172]
### What
What would you like Teleport to do differently?
Currently, the Metrics for Teleport are not prefixed with `teleport` instead they are referenced with the service that they come from:

Currently we see:

```bash
auth_generate_requests_total
server_interactive_sessions_total
proxy_ssh_sessions_total
```

What we would like to see:

```bash
teleport_auth_generate_requests_total
teleport_server_interactive_sessions_total
teleport_proxy_ssh_sessions_total
```

### How
How would you implement this?

- Change the Metrics so that they are all prefixed with `teleport` within the codebase in `metrics.go`:
- Fix any breaking issues in terms of the Grafana Lucene Changes to account for the new types of alerting.

### Why
Why do you need this?

It makes it easier for filtering within Prometheus and it also is best practice alert naming and metrics conventions within the Prometheus community.

### Workaround
Currently, no workaround exists.

**Comment by webvictim** [comment]
If we do this, we should keep the old names for backwards compatibility with people who are currently using these metrics.

**Comment by c4milo** [comment]
the workaround is to rename the metrics using `metric_relabel_configs`. Ex: 

```
 metric_relabel_configs:
          - source_labels: [__name__]
            target_label: "__name__"
            regex: (.*)
            replacement: teleport_auth_${1}
            action: replace
```
