### ISSUE TITLE
Let users define which users match which DB.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#12191]
### What
We recently started to show users all of the 'DB' users in their role. This is a welcome addition, but in my case, I want to specific which user matches which Database. ee.g Alice for Postgres, and SRE-Team for Redis. 
```
➜  tsh db ls
Name          Description Allowed Users                Labels                    Connect
------------- ----------- ---------------------------- ------------------------- -------
aurora                    [alice default sre sre-team] engine=🐘,env=dev
bizops                    [alice default sre sre-team] engine=🐬,env=prod
mongodb                   [alice default sre sre-team] engine=🍃,env=dev-1
mongodb-atlas             [alice default sre sre-team] engine=🍃🌍,env=dev-1
redis                     [alice default sre sre-team] engine=🟥,env=redis
```

### Workaround
Adding a label to tell the user which role to use?

**Comment by greedy52** [comment]
this should be done at Teleport role level.

```
kind: role
metadata:
  name: access-db-dev
spec:
    db_labels:
      'env': dev
    db_users:
    - alice

...

kind: role
metadata:
  name: access-redis
spec:
    db_labels:
      'env': redis
    db_users:
    - default
```
