### ISSUE TITLE
User lock behavior

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#12255]
Current behavior:

The user lock is present on a system (our asteroid earth demo cluster). 

```bash
$ tctl get lock          
kind: lock
metadata:
  name: 22274f9f-585f-450b-8bed-0ed69a1426f6
spec:
  expires: "2022-04-14T07:58:31.626466Z"
  target:
    user: klizhentas
version: v2
---
kind: lock
metadata:
  name: 41836cde-ca3d-4906-9e13-e05814d11fd3
spec:
  expires: "2022-04-14T07:56:57.525596Z"
  target:
    user: klizhentas@gmail.com
version: v2
```

I can still login as this user and access the system:

```
$ tsh ssh ubuntu@ebpf
````

In about 3-4 minutes, I get disconnected with an error message

```
lock targeting User:\"bot-vun\" is in force: The bot user \"bot-vun\" associated with bot \"vun\" has been locked.
```

There is a lock present in the system that matches this description:

```
kind: lock
metadata:
  name: 7de03504-b9ab-4cae-af66-5915ff08029d
spec:
  message: The bot user "bot-vun" associated with bot "vun" has been locked.
  target:
    user: bot-vun
version: v2
---
kind: lock
metadata:
  name: 7f38279c-b54f-46aa-8c4a-33dc1ed046f6
spec:
  message: The bot user "bot-vun" associated with bot "vun" has been locked.
  target:
    user: bot-vun
version: v2
---
kind: lock
metadata:
  name: a00f93a2-057e-459a-b7e6-d5e3c0aa5331
spec:
  message: The bot user "bot-vun" associated with bot "vun" has been locked.
  target:
    user: bot-vun
version: v2
```

I see several problems:

* Why my user can log-in despite having a lock present and active?
* Why when I'm disconnected (3-4 minutes later, seemingly due to timeout) I get error message that is unrelated to my user?

You can reproduce this if you create a user, a lock and re-login with SSO user on our asteroid earth demo env

Bug details:
- Teleport version 9.1.0
- Recreation steps: see above
- Debug logs: n/a
