### ISSUE TITLE
Teleport UX must show/hide things based on RBAC rules

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1233]
## Intro

Currently Teleport UI will show user "access denied" errors when a user does not have access to something. It would be nice to hide UI elements that a user has no access to.

## Implementation

We also **do not want to have any rule-parsing or rule-evaluating logic on the client**. The web UI must be dumb and 100% driven by the server.

To achieve this, lets introduce a "UI capabilities" HTTP API call. The Web UI would call `get_ui_caps()` and the server will return a structure _roughly_ looking like this:

```yaml
settings:
    auth_connectors:
        visible: true/false
        allow_write: true/false
    roles:
        visible: true/false
        allow_write: true/false
    trusted_clusters:
        visible: true/false
        allow_write: true/false
        allow_toggle: true/false
```

This way the server will do the rule evaluation and will determine UI state. 

**NOTE:** the structure above is only an example!!! do not treat this as a design spec, the goal of this is to avoid rule-parsing and rule evaluation in the UI layer. Only the server should contain this logic.
