### ISSUE TITLE
Ability to toggle PIN verification for Yubikey MFA

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#12441]
What would you like Teleport to do?
Customers have requested the ability to toggle FIDO PIN verification when configuring Teleport MFA w/ Yubikeys.

Potential solution put forward by dev:

```
# teleport.yaml
auth_service:
  authentication:
    type: local
    second_factor: on # anything that allows webauthn
    webauthn:
      user_verification: required # <--this
```

What problem does this solve?
Adding a prompt for the PIN would add an extra layer of security.

If a workaround exists, please include it.
Currently none exists.
