### ISSUE TITLE
Teleport, with auto-discovery only detects one DB if there are multiple DBs with same instanceID (in different regions/accounts)

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#12446]
Description:

With `rds autodiscovery` where DB InstanceID is same across different regions, only one db is showing up in Teleport.

Expected behavior:

All DB instances (with auto-discovery) should show up in teleport, even if they have same InstanceID. These DB names can be changed to custom names or prefix/suffix some labels to identify specific Instance.

Current behavior:
Only one DB shows up in Teleport, which ever is discovered first.

Bug details:
- Teleport version: 9.1.2
- Recreation steps

#### Setup:

* DB instance `postgres01` created in both `ap-southeast-2` and `ap-southeast-1` and DBinstance `testpgdb` is created in `ap-southeast-1`.
* db-agent node is running in `ap-southeast-2`.

```
[root@ip-172-31-4-12 teleport]# for region in ap-southeast-2 ap-southeast-1
> do
> echo $region
> aws rds describe-db-instances --region=$region --query 'DBInstances[].DBInstanceIdentifier[]'
> done
ap-southeast-2
[
    "postgres01"
]
ap-southeast-1
[
    "postgres01",
    "testpgdb"
]
```

#### Scenario 1:  `regions` setting as below in `/etc/teleport.yaml` of db-agent. i.e. `ap-southeast1` is first in the list, db instance `postgres01` from `ap-southeast-1` shows in teleport.

``` 
aws:
  # RDS/Aurora databases auto-discovery.
  # For more information about RDS/Aurora auto-discovery: https://goteleport.com/docs/database-access/guides/rds/
  - types: ["rds"]
    # AWS regions to register databases from.
    regions:
    - ap-southeast-1
    - ap-southeast-2
    # AWS resource tags to match when registering databases.
    tags:
      "*": "*"
```

``` 
% tsh db ls
Name       Description                    Labels                                                                                                   Connect
---------- ------------------------------ -------------------------------------------------------------------------------------------------------- -------
postgres01 RDS instance in ap-southeast-1 account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1
testpgdb   RDS instance in ap-southeast-1 account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1
```

#### Scenario 2:  `regions` setting as below in `/etc/teleport.yaml` of db-agent. i.e. `ap-southeast2` is first in the list, db instance `postgres01` from `ap-southeast-2` shows in teleport.

```  
aws:
  # RDS/Aurora databases auto-discovery.
  # For more information about RDS/Aurora auto-discovery: https://goteleport.com/docs/database-access/guides/rds/
  - types: ["rds"]
    # AWS regions to register databases from.
    regions:
    - ap-southeast-2
    - ap-southeast-1
    # AWS resource tags to match when registering databases.
    tags:
      "*": "*"
```

``` 
% tsh db ls
Name       Description                    Labels                                                                                                   Connect
---------- ------------------------------ -------------------------------------------------------------------------------------------------------- -------
postgres01 RDS instance in ap-southeast-2 account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-2
testpgdb   RDS instance in ap-southeast-1 account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1
```

#### Scenario 3:  if I start two separate processes one each for separate region (on same db-agent node), `tctl` shows db is there but `tsh` doesnt show the DB.

``` 
% tctl db ls
Host                                              Name       Protocol URI                                               Labels                                                                                                   Version
------------------------------------------------- ---------- -------- ------------------------------------------------- -------------------------------------------------------------------------------------------------------- -------
ip-172-31-4-12.ap-southeast-2.compute.internal    postgres01 postgres postgres01.cgvd4dfsnp9h.ap-southeast-1.rds.ama... account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1 9.1.3
ip-172-31-4-12.ap-southeast-2.compute.internal    testpgdb   postgres testpgdb.cgvd4dfsnp9h.ap-southeast-1.rds.amazo... account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1 9.1.3
ip-172-31-4-12.ap-southeast-2.compute.internal... postgres01 postgres postgres01.c1qpy0jaasz7.ap-southeast-2.rds.ama... account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-2 9.1.3

 % tsh db ls
Name       Description                    Labels                                                                                                   Connect
---------- ------------------------------ -------------------------------------------------------------------------------------------------------- -------
postgres01 RDS instance in ap-southeast-1 account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1
testpgdb   RDS instance in ap-southeast-1 account-id=xxxxxxxxxxxx,endpoint-type=instance,engine-version=13.4,engine=postgres,region=ap-southeast-1

 %
```

- Debug logs
Attached DB agents logs. for scenario1 and scenario2.
[teleport-db-agent-logs-1.txt](https://github.com/gravitational/teleport/files/8629134/teleport-db-agent-logs-1.txt)
[teleport-db-agent-logs-2.txt](https://github.com/gravitational/teleport/files/8629135/teleport-db-agent-logs-2.txt)
