### ISSUE TITLE
tctl <resource command> user

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1247]
Currently we have a prototype for `tctl get/rm/create user`. It cannot be officially documented and supported because it contains a number of issues.

Here's the output:

```yaml
kind: user
metadata:
  name: joe
spec:
  created_by:
    time: 0001-01-01T00:00:00Z
    user:
      name: builtin-Admin
  expires: 0001-01-01T00:00:00Z
  roles:
  - default
  status:
    is_locked: false
    lock_expires: 0001-01-01T00:00:00Z
    locked_time: 0001-01-01T00:00:00Z
  traits:
    logins:
    - ekontsevoy
    - root
version: v2
```

Issues:

* `tctl get users/joe` prints all users, not just joe
* The created_by/time field is always showing the invalid (`0001-01-01T00:00:00Z`) creation time.
* `expires` makes no sense. Nowhere in Teleport we say that we support automatically expiring users.
* `status` does not work well. `locked_time` is never updated (and it is not even used in the code, I looked). 
* `tctl create user.yaml` does not work (because a user needs corresponding password/2fa fields).

I am removing this for 2.3 but it would be nice to have it actually work for manipulating the local user database.
