### ISSUE TITLE
OIDC authentication for stateless clients

### ISSUE THREAD

**Issue by eriksw** [gravitational/teleport#12536]
## What would you like Teleport to do?

I want to authenticate to Teleport by presenting an OIDC JWT issued by the environment the client is running in.

A simplified use case of this would be a Github Actions workflow that uses Terraform ssh to connect to a server and trigger a deployment process.

Many platforms including Google Cloud (Compute Engine, Cloud Functions, Cloud Run, etc..) and [GitHub Actions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect) provide the ability to obtain a JWT signed by an OIDC provider maintained by the platform.

I want to make Teleport accept such JWT's for purposes of obtaining a very-short-lived non-renewable certificate usable with tsh, tctl, etc. (Non-renewable because the authorized client can always just get a new JWT from the environment.)

<details><summary>Example JWT from Github Actions</summary>

Note: This isn't real, it's just from [the docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token).

Also note: There is no email!

```
{
  "jti": "example-id",
  "sub": "repo:octo-org/octo-repo:environment:prod",
  "environment": "prod",
  "aud": "https://github.com/octo-org",
  "ref": "refs/heads/main",
  "sha": "example-sha",
  "repository": "octo-org/octo-repo",
  "repository_owner": "octo-org",
  "run_id": "example-run-id",
  "run_number": "10",
  "run_attempt": "2",
  "actor": "octocat",
  "workflow": "example-workflow",
  "head_ref": "",
  "base_ref": "",
  "event_name": "workflow_dispatch",
  "ref_type": "branch",
  "job_workflow_ref": "octo-org/octo-automation/.github/workflows/oidc.yml@refs/heads/main",
  "iss": "https://token.actions.githubusercontent.com",
  "nbf": 1632492967,
  "exp": 1632493867,
  "iat": 1632493567
}
```

</details>

<details><summary>Example JWT from Google Cloud Instance</summary>

Obtained with:

```
curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://mycloudinstall.teleport.sh&format=full" -H "Metadata-Flavor: Google"
```

Data in the resulting token:

```
{
  "aud": "https://mycloudinstall.teleport.sh",
  "azp": "106803755355889312876",
  "email": "access-test-237@rn-sbx-202204-c9b4.iam.gserviceaccount.com",
  "email_verified": true,
  "exp": 1652143389,
  "google": {
    "compute_engine": {
      "instance_creation_timestamp": 1651782507,
      "instance_id": "2151173633666026885",
      "instance_name": "accesstest-2",
      "project_id": "rn-sbx-202204-c9b4",
      "project_number": 524102546484,
      "zone": "us-central1-a"
    }
  },
  "iat": 1652139789,
  "iss": "https://accounts.google.com",
  "sub": "106803755355889312876"
}
```

</details>

After obtaining such a token from the environment, I would present it to Teleport and obtain the certificate. JWT in request, cert in response. No creation of a user, this is straight to a role.

I imagine the configuration on Terraform's side would look something like this:

```
---
kind: oidc
metadata:
  name: github-actions
spec:
  claims_to_roles:
  - roles:
    - access
    # two claim=value's AND'd
    claims:
    - claim: repository
      value: octo-org/octo-repo
    - claim: workflow
      value: example-workflow
  # don't show this oidc to users logging in
  # The web UI and `tsh login` both act like this oidc doesn't exist.
  hide: true
  issuer_url: https://token.actions.githubusercontent.com
```

Note: There is no email/user for Github Actions!

--

Or this for a Google Service Account:

```
---
kind: oidc
metadata:
  name: google-cloud
spec:
  claims_to_roles:
  - claim: email
    roles:
    - auditor
    value: access-test-237@rn-sbx-202204-c9b4.iam.gserviceaccount.com
  # This isn't meant for users
  # The web UI and `tsh login` both act like this oidc doesn't exist.
  hide: true
  issuer_url: https://accounts.google.com
```

--

Aside: The first example demonstrates the need for AND between multiple claim matches. This is only a rough, not-very-considered idea. I would **strongly suggest** looking at the way Google Cloud's Workflow Identity Federation feature has highly flexible [attribute mapping and conditions](https://cloud.google.com/iam/docs/configuring-workload-identity-federation#mappings-and-conditions).

Bonus feature: This is ~98% of what's needed for secure enrollment of Google Compute Engine instances with no need for any kind of invite token. You even get secure identification of the instance's name, location, etc... as claimed attributes!

## What problem does this solve?

I want to authenticate to Teleport from a *stateless* environment like a Github Actions workflow or a Google Cloud Functions invocation. By stateless, I mean what I write needs to work even when there is **no passing of information from one invocation to the next**. (This rules out "impersonate then rotate"-type flows.)

I want to do this _without_ there being any long-lived secrets that I have any hand in managing. I trust my providers to manage their JWKs.

I have a lot of trust in Teleport being able to securely read https://token.actions.githubusercontent.com/.well-known/openid-configuration then https://token.actions.githubusercontent.com/.well-known/jwks when checking a presented JWT.

I have _overwhelmingly_ less trust in the security of some bodge like giving Github Actions access to a "secure" Cloud Storage bucket (or equivalent) where it could keep rotated certificate/key between invocations.

## If a workaround exists, please include it.

@yjperez suggested we run Machine ID on some persistent, stateful pet and have _that_ push certs into somewhere accessible to the stateless jobs.

This has not just the waste and operational burden of running a durably-stateful singleton pet 🤮, but also all the logistical issues of having secure storage for the certs and arranging secure access from the stateless actor to them.

(I'm filing this feature request because @yjperez asked me to—the ability to interact with Teleport from stateless workers like a Google Cloud Function is critical to us.)
