### ISSUE TITLE
Pagination of Applications

### ISSUE THREAD

**Issue by wtphilbrook** [gravitational/teleport#12555]
Current stack:
3 Teleport main nodes ( auth + proxy + app ) with a Dynamo backend. Each main node hosts an app service for our primary applications, which in this testing environment is 5 total applications.

I recently added a 6th application directly on a node to take advantage of the reverse tunnel.

After adding the 6th application, I noticed that Teleport is paginating the list and pushing the new service to the second page. My guess here is the first 5 applications are being counted three times each (once per main node), making Teleport think we have 16 applications rather than 6. 

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/50968385/167684063-4a44df79-a2cf-42d3-8403-a863ec823de8.png">

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/50968385/167683807-01471400-242a-435d-9a07-233619c7d534.png">

Here's the main node config:

```
version: v2
teleport:
    nodename: [redacted]
    data_dir: /var/lib/teleport
    ca_pin: []
    auth_servers:
        - [redacted]:3025
    storage:
      type: dynamodb
      region: us-east-2
      table_name: teleport
      audit_events_uri: [ 'dynamodb://teleport_events', 'file:///var/lib/teleport/audit/events', 'stdout://' ]
      audit_sessions_uri: s3://[redacted]/records
      audit_retention_period: 1y
auth_service:
    enabled: yes
    cluster_name: "[redacted]"
    proxy_protocol: on
    authentication:
        type: local
        second_factor: otp
        webauthn:
          rp_id: "[redacted]"
          disabled: false
        locking_mode: best_effort
    listen_addr: 0.0.0.0:3025
    public_addr: [redacted]:3025
    session_recording: "node"
    proxy_checks_host_keys: yes
    client_idle_timeout: 1h
    client_idle_timeout_message: ""
    web_idle_timeout: 10m
    disconnect_expired_cert: no
    keep_alive_interval: 5m
    keep_alive_count_max: 3
    routing_strategy: unambiguous_match
    message_of_the_day: "test"
    proxy_listener_mode: multiplex
ssh_service:
    enabled: yes
    listen_addr: 0.0.0.0:3022
    public_addr: [redacted]:3022
    labels:
      teleport_main: true
      hostgroup: [redacted]
    commands:
    - name: os_version
      command: ["lsb_release", "--release", "-s"]
      period: 1h
proxy_service:
    enabled: yes
    proxy_protocol: on
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3024
    web_listen_addr: 0.0.0.0:443
    public_addr: [redacted]:443
    ssh_public_addr: [redacted]:3023
    tunnel_public_addr: [redacted]:3024
    https_keypairs:
    - key_file: [redacted]
      cert_file: [redacted]
app_service:
  apps:
  - labels:
      category: internal_tools
      env: prod
    name: [redacted]
    uri: [redacted]
  - labels:
      category: security
      env: prod
    name: [redacted]
    uri: [redacted]
  - labels:
      category: internal_tools
      env: prod
    name: [redacted]
    uri: [redacted]
  - labels:
      env: qa
      vertical: ao
    name: [redacted]
    uri: [redacted]
  - labels:
      category: database
      env: prod
    name: [redacted]
    uri: [redacted]
  enabled: true
```

And here's the config for the node hosting the 6th application:

```
version: v2
teleport:
    nodename: [redacted]
    data_dir: /var/lib/teleport
    ca_pin: []
    auth_token: [redacted]
    auth_servers:
        - [redacted]

ssh_service:
    enabled: yes
    labels:
      hostgroup: [redacted]
    commands:
    - name: os_version
      command: ["lsb_release", "--release", "-s"]
      period: 1h
auth_service:
  enabled: no
proxy_service:
  enabled: no
kubernetes_service:
  enabled: no
db_service:
  enabled: no
app_service:
  apps:
  - insecure_skip_verify: true
    labels:
      category: security
      env: prod
    name: [redacted]
    uri: http://localhost:[redacted]/app/[redacted]
  enabled: true
```

Bug details:
Teleport version:

- Main nodes:
```Teleport v9.2.1 git:v9.2.1-0-gc6daeda62 go1.17.9```

- App Node:
```Teleport v9.2.1 git:v9.2.1-0-gc6daeda62 go1.17.9```
