### ISSUE TITLE
Can not connect to RDS Postgres - Teleport self-hosted servers

### ISSUE THREAD

**Issue by triethuynh1408** [gravitational/teleport#12695]
I have 2 servers:
1. Teleport Auth/Proxy server (public subnet): Use Github SSO, Route53 for DNS, Let's Encrypt. Allow ports inbound 80, 443, 3022-3026, 3028. Outbound All ports.
2. Teleport Database Service server (private subnet): Config auto-discovery RDS Instances. I can connect to RDS instances from this server by command `nc -vz xxx.rds.amazonaws.com 5432`. Allow ports inbound 80, 443. Outbound all ports

I can login by github account and can list all databases by command `tsh db ls`

But when I config and connect to database, it has error: 

`psql: error: connection to server at "localhost" (127.0.0.1), port 57688 failed: SSL connection has been closed unexpectedly
ERROR: exit status 2`

This is my configurations:

- Teleport Auth/Proxy
```version: v2
teleport:
  nodename: ip-xxx
  data_dir: /var/lib/teleport
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: abc.xyz.aaa.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: abc.xyz.aaa.com:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: abc@aaa.com
```
- Teleport Database Service
```
# Teleport database agent configuration file.
# Configuration reference: https://goteleport.com/docs/database-access/reference/configuration/
#
teleport:
  nodename: ip-xxx
  data_dir: /var/lib/teleport
  auth_token: /tmp/token
  auth_servers:
  - abc.xyz.aaa.com:3080
db_service:
  enabled: "yes"
  # Matchers for database resources created with "tctl create" command.
  # For more information: https://goteleport.com/docs/database-access/guides/dynamic-registration/
  resources:
  - labels:
      "*": "*"
  # Matchers for registering AWS-hosted databases.
  aws:
  # RDS/Aurora databases auto-discovery.
  # For more information about RDS/Aurora auto-discovery: https://goteleport.com/docs/database-access/guides/rds/
  - types: ["rds"]
    # AWS regions to register databases from.
    regions:
    - ap-southeast-1
    # AWS resource tags to match when registering databases.
    tags:
      "*": "*"
  # Lists statically registered databases proxied by this agent.
  # databases:
  # # RDS database static configuration.
  # # RDS/Aurora databases Auto-discovery reference: https://goteleport.com/docs/database-access/guides/rds/
  # - name: rds
  #   description: AWS RDS/Aurora instance configuration example.
  #   # Supported protocols for RDS/Aurora: "postgres" or "mysql"
  #   protocol: postgres
  #   # Database connection endpoint. Must be reachable from Database Service.
  #   uri: rds-instance-1.abcdefghijklmnop.us-west-1.rds.amazonaws.com:5432
  #   # AWS specific configuration.
  #   aws:
  #     # Region the database is deployed in.
  #     region: us-west-1
  #     # RDS/Aurora specific configuration.
  #     rds:
  #       # RDS Instance ID. Only present on RDS databases.
  #       instance_id: rds-instance-1
  # # Aurora database static configuration.
  # # RDS/Aurora databases Auto-discovery reference: https://goteleport.com/docs/database-access/guides/rds/
  # - name: aurora
  #   description: AWS Aurora cluster configuration example.
  #   # Supported protocols for RDS/Aurora: "postgres" or "mysql"
  #   protocol: postgres
  #   # Database connection endpoint. Must be reachable from Database Service.
  #   uri: aurora-cluster-1.abcdefghijklmnop.us-west-1.rds.amazonaws.com:5432
  #   # AWS specific configuration.
  #   aws:
  #     # Region the database is deployed in.
  #     region: us-west-1
  #     # RDS/Aurora specific configuration.
  #     rds:
  #       # Aurora Cluster ID. Only present on Aurora databases.
  #       cluster_id: aurora-cluster-1
  # # Redshift database static configuration.
  # # For more information: https://goteleport.com/docs/database-access/guides/postgres-redshift/
  # - name: redshift
  #   description: AWS Redshift cluster configuration example.
  #   # Supported protocols for Redshift: "postgres".
  #   protocol: postgres
  #   # Database connection endpoint. Must be reachable from Database service.
  #   uri: redshift-cluster-example-1.abcdefghijklmnop.us-west-1.redshift.amazonaws.com:5439
  #   # AWS specific configuration.
  #   aws:
  #     # Region the database is deployed in.
  #     region: us-west-1
  #     # Redshift specific configuration.
  #     redshift:
  #       # Redshift Cluster ID.
  #       cluster_id: redshift-cluster-example-1
  # # Self-hosted static configuration.
  # - name: self-hosted
  #   description: Self-hosted database configuration.
  #   # Supported protocols for self-hosted: postgres, mysql, mongodb, cockroachdb, redis, sqlserver.
  #   protocol: postgres
  #   # Database connection endpoint. Must be reachable from Database service.
  #   uri: database.example.com:5432
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
```

Expected behavior:
Can connect to RDS instances

Current behavior:
Can not connect to RDS instances 

Bug details:
- Teleport version
- Recreation steps
- Debug logs
