### ISSUE TITLE
Trusted Clusters - Leaf cluster cannot join root cluster

### ISSUE THREAD

**Issue by hydezhao** [gravitational/teleport#12818]
Expected behavior:
leaf cluster joins to root cluster successfully.

Current behavior:
when leaf cluster try join root cluster, I got following error messages on root cluster:
```
teleport[70383]: 2022-05-23T07:21:48Z WARN [REVERSE:T] Re-init the cache on error: connection error: desc = "transport: Error while dialing failed to dial: cluster teleport.srr is offline". cache/cache.go:753
teleport[70383]: 2022-05-23T07:21:48Z WARN [REVERSE:T] Cache "remote-proxy" first init failed, continuing re-init attempts in background. error:[
teleport[70383]: ERROR REPORT:
teleport[70383]: Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: Error while dialing failed to dial: cluster teleport.srr is offline&#34;
teleport[70383]: Stack Trace:
teleport[70383]: #011/go/src/github.com/gravitational/teleport/api/client/streamwatcher.go:40 github.com/gravitational/teleport/api/client.(*Client).NewWatcher
teleport[70383]: #011/go/src/github.com/gravitational/teleport/lib/cache/cache.go:824 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
teleport[70383]: #011/go/src/github.com/gravitational/teleport/lib/cache/cache.go:747 github.com/gravitational/teleport/lib/cache.(*Cache).update
teleport[70383]: #011/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
teleport[70383]: User Message: connection error: desc = &#34;transport: Error while dialing failed to dial: cluster teleport.srr is offline&#34;] cache/cache.go:710
teleport[70383]: 2022-05-23T07:21:48Z INFO [PROXY:SER] Connection <- 10.48.2.90:55602, clusters: 1. cluster:teleport.srr reversetunnel/srv.go:897
```

on UI/CLI of root cluster, I cannot see leaf cluster, while on leaf cluster I can see root cluster.
And I can see an established tcp connection:
`teleport  70383            root   12u  IPv6 537178      0t0  TCP <IP-ROOT>:3024-><IP-ROOT>:36500 (ESTABLISHED)`

Bug details:
- Teleport version: 9.2.4
- Recreation steps
cluster.yaml applied on leaf cluster:
```
# cluster.yaml
kind: trusted_cluster
version: v2
metadata:
  # The trusted cluster name MUST match the 'cluster_name' setting of the
  # root cluster
  name: teleport-root.example.com
spec:
  # This field allows to create tunnels that are disabled, but can be enabled later.
  enabled: true
  # The token expected by the "root" cluster:
  token: xxxxxxxxxxxx
  # The address in 'host:port' form of the reverse tunnel listening port on the
  # "root" proxy server:
  tunnel_addr: teleport-root.example.com:3024
  # The address in 'host:port' form of the web listening port on the
  # "root" proxy server:
  web_proxy_addr: teleport-root.example.com:443
  role_map:
  - remote: "*"
    local: [access,auditor,editor]
```

note: I am using self-signed certificates for root and leaf, and I installed the CA on both machines.

- Debug logs
