### ISSUE TITLE
where: statement in session block causes users to be unable to play their own session recordings

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#12865]
Expected behavior:
```
    - resources:
      - session
      verbs:
      - list
      - read
      where: contains(session.participants, user.metadata.name)
```

The where: conditional in this example should allow a user to play session recordings for sessions they participated in. 

Current behavior:
With `where: contains(session.participants, user.metadata.name)`, users assigned that role get the error “Session recording not available". If `where: contains(session.participants, user.metadata.name)` is removed the issue resolves. 
Bug details:
- Teleport version Cloud: 9.2.4  Self-hosted: 9.2.3 
- Recreation steps 1. Create role that restricts a user to only be able to play sessions recordings for sessions they participated in.  2. Create a session recording by accessing a resource with that same user. 3. Attempt to play the recording with the same user.
- Debug logs
2022-05-24T13:35:08Z WARN [WEB]       Request failed: bad bearer token. error:[
ERROR REPORT:
Original Error: *trace.NotFoundError &#34;/web/tokens/undefined&#34; is not found
Stack Trace:
	/go/src/github.com/gravitational/teleport/api/client/sessions.go:105 github.com/gravitational/teleport/api/client.(*webTokens).Get
	/go/src/github.com/gravitational/teleport/api/client/sessions.go:93 github.com/gravitational/teleport/api/client.(*Client).GetWebToken
	/go/src/github.com/gravitational/teleport/lib/web/sessions.go:885 github.com/gravitational/teleport/lib/web.(*sessionCache).readBearerToken
	/go/src/github.com/gravitational/teleport/lib/web/sessions.go:113 github.com/gravitational/teleport/lib/web.(*SessionContext).validateBearerToken
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:2613 github.com/gravitational/teleport/lib/web.(*Handler).AuthenticateRequest
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:2576 github.com/gravitational/teleport/lib/web.(*Handler).WithAuth.func1
	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:67 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
	/tmp/gomodcache/github.com/gravitational//router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/opt/go/src/net/http/server.go:2090 net/http.StripPrefix.func1
	/opt/go/src/net/http/server.go:2047 net/http.HandlerFunc.ServeHTTP
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:454 github.com/gravitational/teleport/lib/web.NewHandler.func1
	/opt/go/src/net/http/server.go:2047 net/http.HandlerFunc.ServeHTTP
	/tmp/gomodcache/github.com/gravitational/5/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:215 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	/tmp/gomodcache/github.com/gravitational/9/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	/tmp/gomodcache/github.com/gravitational//connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	/opt/go/src/net/http/server.go:2879 net/http.serverHandler.ServeHTTP
	/opt/go/src/net/http/server.go:1930 net/http.(*conn).serve
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: &#34;/web/tokens/undefined&#34; is not found] request:DELETE /webapi/sessions web/apiserver.go:2614
2022-05-24T13:35:09Z WARN [WEB]       Invalid session. error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError session is invalid or has expired
Stack Trace:

Caught:
	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:142 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:278 github.com/gravitational/teleport/lib/auth.(*Client).PostJSON
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:1018 github.com/gravitational/teleport/lib/auth.(*Client).AuthenticateWebUser
	/go/src/github.com/gravitational/teleport/lib/web/sessions.go:792 github.com/gravitational/teleport/lib/web.(*sessionCache).newSessionContext
	/go/src/github.com/gravitational/teleport/lib/web/sessions.go:685 github.com/gravitational/teleport/lib/web.(*sessionCache).validateSession
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:2601 github.com/gravitational/teleport/lib/web.(*Handler).AuthenticateRequest
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:487 github.com/gravitational/teleport/lib/web.NewHandler.func1
	/opt/go/src/net/http/server.go:2047 net/http.HandlerFunc.ServeHTTP
	/tmp/gomodcache/github.com/gravitational//router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:215 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	/tmp/gomodcache/github.com/gravitational//ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	/tmp/gomodcache/github.com/gravitational//connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	/opt/go/src/net/http/server.go:2879 net/http.serverHandler.ServeHTTP
	/opt/go/src/net/http/server.go:1930 net/http.(*conn).serve
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: session is invalid or has expired

**Comment by stevenGravy** [comment]
@WilliamLoy can you share the role(s)?  No problem with this in a `9.2.4` deployment:


```yaml
kind: role
metadata:
  id: 1653405114411811083
  name: testsession
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    - '*'
    db_users:
    - '{{internal.db_users}}'
    - developer
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    - developer
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    - dev
    logins:
    - '{{internal.logins}}'
    - ubuntu
    - debian
    node_labels:
      '*': '*'
    rules:
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
    - developer
  deny:
    logins:
    - guest
  options:
    cert_format: standard
    desktop_clipboard: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v5
```

**Comment by WilliamLoy** [comment]
There are 3 different roles being assigned to the same users. 
role1
```
kind: role
metadata:
  name: test-1
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - list
      - read
      where: contains(session.participants, user.metadata.name)
  deny: {}
  options:
    cert_format: standard
    desktop_clipboard: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v5
```
role2
```
kind: role
metadata:
  name: dev-access-general
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      teleport-role: dev-access-general
    db_names:
    - '*'
    db_users:
    - teleport_developer
    kubernetes_groups:
    - dev-access-general
    kubernetes_labels:
      type: general
    logins:
    - '{{internal.logins}}'
    - '{{email.local(external.email)}}'
    - ec2-user
    - ubuntu
    node_labels:
      restrict: all
      type: general
  deny: {}
  options:
    cert_format: standard
    desktop_clipboard: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 12h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v5
```
role 3
```
kind: role
metadata:
  description: Role for monday.com platform developers
  name: dev-access-2
spec:
  allow:
    db_labels:
      teleport-role: dev-access-2
    db_names:
    - '*'
    db_users:
    - teleport_developer
    kubernetes_groups:
    - dev-access-2
    kubernetes_labels:
      type:
      - monday
      - mgmt
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    desktop_clipboard: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 12h0m0s
    port_forwarding: true
    record_session:
      desktop: true
version: v5
```
