### ISSUE TITLE
RDS IAM policy max characters size

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#12871]
#### Current behavior:
When a large number (> 100)  of RDS databases are configured with auto IMA policy update the policy size can exceed max AWS policy chars [limit](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entities%23reference_iam-quotas-entity-length) (Role policy size cannot exceed 10,240 characters.) In result the db agent is unable to configure RDS iam auth: 
```
2022-05-22T23:30:22Z WARN [DB:SERVIC] "Failed to auto-configure IAM for Database(Name=... Type=rds, Labels=map[........]): 
LimitExceeded: Maximum policy size of 10240 bytes exceeded for role ....\n\tstatus code: 409, request id: 3c6c4a66-385b-488d-ba12-98cd7b976582."
```

#### Possible solutions: 
* implement automatically policy sharding by  creation of severals inline policy 
   Cons: AWS Allows to create only 10 inline policies so in large RDS (~1000 RDS) instance env AWS policy limit will be also exceeded. 
* Switch to Managed policy

**Comment by greedy52** [comment]
per managed policy has a smaller maximum quota (6144 vs role inline total of 10240), but you can have 10 managed policies attached to the role so using managed policy will extend our current limit by about 5 times. 10 times if the user request limit raises to 20 managed policies per user/role.

One problem I see with this approach is we have to name managed policies in a way they don't collide with others, and we will end up with so many of them it's hard to clean up one day.

Here's a list of suggestions from AWS on how to deal with the limit:
https://aws.amazon.com/premiumsupport/knowledge-center/iam-increase-policy-size/

One possible solution I think we can just do `"*"` for resource when we see this error or when n is large? Customers can limit the permission (likely through some prefixes) in boundary statements if they really want to.

**Comment by GavinFrazar** [comment]
I think that suggestion mostly alleviates the concerns raised by @tigrato about coupling our discovery IAM role to access IAM, so we can split the permissions. It still centralizes the decision for which role to assume in the discovery service - simpler but less flexible config - but maybe that doesn't matter.

Just to throw another idea in the ring here - what if we configure the db agent to assume a role for accessing a dynamic database based on labels?

```yaml
db_service:
  enabled: true
  resources:
    - labels: # proxy all the discovered databases
        "*": "*"
    - labels: # but for aws databases with these labels, assume a specific role
        "account-id": "111111111111"
        "type": "rds" # we dont add this label during discovery currently
        "env": "dev"
      aws_assume_role_arn: "arn:aws:iam::111111111111:role/role_for_dev_rds"
    - labels:
        "account-id": "111111111111"
        "type": "rds" # we dont add this label during discovery currently
        "env": "prod"
      aws_assume_role_arn: "arn:aws:iam::111111111111:role/role_for_prod_rds"

```
