### ISSUE TITLE
Trusted cluster CRUD issues

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1288]
I am creating a trusted cluster from this YAML:

```yaml
kind: trusted_cluster
version: v2
metadata:
  name: east
spec:
  enabled: false
  role_map:
  - local:
    - dba
    - backup
    remote: admin
  token: dogs-are-great
  tunnel_addr: ev-t1-master:3024
  web_proxy_addr: ev-t1-master:3080
```

## Problem One: cannot edit

I execute `tctl create cluster.yaml` and it succeeds.
Then I decide that I want to enable it, so I flip `enabled` from "false" to "true" and try to update:

```bash
$ tctl create cluster.yaml
trusted cluster 'east' already exists

# great success! lets --force it:
$ tctl create --force cluster.yaml
can not deactivate CertAuthority which does not exist: {user east}: [authorities user] east not found
```

At this point the user will be calling support.

## Problem Two: Enabled flag is not interpreted

The cluster actually is enabled, even if `enabled: false` in the original YAML.
This raises the priority of this issue because I cannot find a way to create a disabled cluster (or flip an enabled one) via `tctl`.
