### ISSUE TITLE
Application login issues

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#12913]
Expected behavior:
When customer logs in from Teleport UI to an application, it should redirect and login with out any issues. However, we are not seeing that.

Current behavior:
Their apps are hanging when you open it via application view with an x-teleport-auth but once that is removed the application loads successfully. This issue is observed on all leaf clusters and it has been going on for a while now.
https://company-staging.teleport.internal.corp.example.com/x-teleport-auth?state=de1dac8f06f44c00324e202d9e814165#value=a7e26481acb31282f773d2405b51f4ecee724e6e735aa706645c02849ffaf20e

In addition, they are getting 403 errors sometimes.
When they load the company application it points to the URI
uri: "https://company.internal.dev.example.com/"
when it should be pointing to the public_addr:
public_addr: "company-development.teleport.internal.corp.example.com"

Heartbeat errors:
2022-05-12T11:06:09Z [APP:SERVI] WARN Heartbeat failed connection error: desc = "transport: authentication handshake failed: context deadline exceeded". srv/heartbeat.go:273

Bug details:

Teleport version: 9.0.1
Recreation steps: At the moment, we are working on reproducing this issue with an alertmanger application.
Debug logs:
Here is the full config of the company application:
```
data:
  teleport.yaml: |
    teleport:
      cache:
        type: in-memory
      auth_token: "/etc/teleport-secrets/auth-token"
      auth_servers:
      - teleport.internal.dev.example.com:443
      log:
        severity: INFO
    app_service:
      enabled: yes
      apps:
      - name: "company-development"
        uri: "https://company.internal.dev.example.com/"
        public_addr: "company-development.teleport.internal.corp.example.com"
        labels:
          name: company
    auth_service:
      enabled: "no"
    ssh_service:
      enabled: "no"
    proxy_service:
      enabled: "no"
```
Next steps: 
- Reproduce the issue with their Terraform AWS cluster
- Collect USR1 logs 

ZD: 5127

gz#5127

## Logs

```
29T16:23:54Z WARN [APP:WEB] Request failed: state token does not match. app/fragment.go:88
```

**Comment by Erick-Reyes** [comment]
Following up on this issue, we reproduced this issue successfully. 
We configured an application on the leaf and root cluster (same application with different public addr for each cluster). When we attempted to access from the leaf cluster it kept sending us in a loop. After taking the `x-teleport-auth` it would load successfully. Here is the full config used, with `leafapp.xteleport.xy pointing to the teleport proxy`:

```
app_service:
  enabled: yes
  apps:
  - name: zdstats
     uri: "http:/xx.xxx.xxx.xxx:3000/"
     public_addr: "leafapp.xteleport.xy"
     labels:
       access: "cs" 
```

Customer has provided teleport configs for their root and leaf clusters if needed. Also, debug logs are are available as they captured when the app was directly launched while connecting to the leaf cluster; request looping in pending. 

In addition, customer did not provide goroutine profiling data. As per, latest update was that the issue has temporarily not been showing up as root proxy cluster have been restarted (restarting teleport-proxy-acm service), but this has happen in the past as well and then it starts happening again.
