### ISSUE TITLE
User lock issues

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1296]
Are we supporting locking users via resources? 

Here's an example:

```yaml
kind: user
version: v2
metadata:
  name: doggy
spec:
  created_by:
    time: 0001-01-01T00:00:00Z
    user:
      name: ""
  expires: 0001-01-01T00:00:00Z
  roles:
  - admin
  status:
    is_locked: true
    lock_expires: 2018-01-01T00:00:00Z
    locked_time: 0001-01-01T00:00:00Z
  traits:
    logins:
    - ekontsevoy
```

When I update this user, it continues to receive certificates. I also see that we have some code which locks users automatically for repeated failed logins. That code uses the same machinery, so lets make sure this flag is actually respected.
