### ISSUE TITLE
Remove 'connect' verb from 'role' resource

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1298]
The default "admin" role looks like this:

```yaml
kind: role
version: v3
metadata:
  name: interns
spec:
  options:
    max_session_ttl: 30h0m0s

  allow:
    logins: [root, '{{internal.logins}}']
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs: [connect, list, create, read, update, delete]
    - resources:
      - auth_connector
      verbs: [ connect, list, create, read, update, delete ]
    - resources:
      - session
      verbs: [list, read]
    - resources:
      - trusted_cluster
      verbs: [connect, list, create, read, update, delete]

  deny: {}
```

It lists "connect" verb for the role resource, which is a NOP and probably makes no sense.
