### ISSUE TITLE
Examples improvements

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1320]
In `examples/resources/trusted_cluster_enterprise.yaml` we should mention the old style simple mapping which is still useful if you have older versions of OpenSSH within your cluster where we can not embed your role name into the certificate. An example resource:

```
kind: trusted_cluster
version: v2
metadata:
   name: "one"
spec:
   enabled: true
   token: "bar"
   tunnel_addr: 127.0.0.1:3024
   web_proxy_addr: 127.0.0.1:3080
   roles: ["admin"]
```
----

In `examples/resources/saml-connector.yaml` we should mention that the entire XML document needs to be indented four spaces. That's how just the pipe works for embedding something within a YAML document.

----

In `examples/resources/adfs-connector.yaml` we may want to mention how to generate a self signed key pair to use for the `signing_key_pair `. I'll include a sample program in the comments.
