### ISSUE TITLE
Applications access auto discovery from AWS load balancers

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#13236]
## What would you like Teleport to do?

It will be great if Teleport can auto-discover ALB, ELB, NLB and configure them as applications

Example config (final form should be discussed. here is just an example to illustrate the possibility):
```
app_service:

  # Matcher to discover and register applications from route53.
  aws-lb:
  - region: us-east-1
    types: ["alb", "nlb"]
    tags: # tag matching
      "key": "value"  
```

## What problem does this solve?

Saves time from manually configuring applications, for better UX.

## If a workaround exists, please include it.

Today applications are manually input one by one in app configs.
