### ISSUE TITLE
Cluster level setting for enabling/disabling recording proxy

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1329]
We should be able to enable and disable https://github.com/gravitational/teleport/issues/1327 at the cluster level.

The proxy will use it for two purposes. The first is determine when it gets a request will it be running in the normal mode or will it be recording and forwarding traffic. The second is if it is running in recording and forwarding mode, it will need to request a role with `RW` access to `services.CertAuthority` resources.

Teleport nodes also need access to this setting so they can stop shipping audit logs to the Auth Server to prevent double logging.

The default setting for this should be normal mode.

**Comment by kontsevoy** [comment]
### Proposal

Implement a new global (cluster-level) configuration setting, set via YAML configuration:

```yaml
auth_service:
     # session_recording controls how a Teleport cluster records SSH sessions.
     # possible values: "node" (default), "proxy" and "off" (to turn session recording completely off) 
     session_recording: "proxy"
```

This allows us to implement #1263 as well, or at least pave way for it.

**Comment by russjones** [comment]
I like the ability to easily change cluster level configuration. Right now to make cluster level changes you have the following options:

1. If you are not running your Auth Server in HA mode cause a short outage to change cluster level configuration (if you are not using the caching ability we have).
1. If you are running the Auth Server in HA mode, make sure you organize all of our configuration files correctly so after doing a rolling restart you end with the right configuration.

In addition, it would be nice to consolidate all cluster level configuration (name, static tokens, and auth preferences) so we can easily add to it and operate on it.

**Comment by kontsevoy** [comment]
## Updated Proposal

We have decided that moving to a dynamic cluster config is better be done all-at-once, and it should include the ability to change things like static tokens and a cluster name.

For now, it's much better from user expectation's point of view to simply add a new setting to `/etc/teleport.yaml`

```yaml
# fragment of /etc/teleport.yaml
auth_service:
   # session_recording possible options: "node" (default) "proxy" and "off"
   session_recording: "node"
```
