### ISSUE TITLE
Dynamic Label using bash script with argument not running as expected

### ISSUE THREAD

**Issue by mechastorm** [gravitational/teleport#1346]
I did a re-usable bash script to get the aws tag values
https://gist.github.com/mechastorm/ada3a0038f9ad12e9f806fdf4966af31

The script allows me to run `./ec2_tag_data.sh tag_field` to get me the value of an EC2 tag in the current server.

And my teleport.yaml config looks like
```
    commands:
      - name: environment
        command: ["/usr/local/bin/ec2_tag_data.sh", "environment"]
        period: 120s
```

Running the script direct on the server works fine.

Yet on the Teleport auth servers, they show up empty.
```
Hostname                      UUID    Address         Labels
----------------------- ------- ------------- ------------------------------------------
dev-teleport-xxx            xxx      x.x.x.x:6022   environment=
```

When I tried configuring the command as a one line like below
```
    commands:
      - name: environment
        command: ["/usr/local/bin/ec2_tag_data.sh environment"]
        period: 120s
```

And instead I get a start-up error
```
level=error msg="fork/exec /usr/local/bin/ec2_tag_data.sh environment: no such file or directory" file="srv/sshserv...dateLabel"
```
