### ISSUE TITLE
Update recording_sessions for Node Restrictions using node_labels

### ISSUE THREAD

**Issue by Richard-Barrett** [gravitational/teleport#13482]
## What would you like Teleport to do?

I would like `Teleport` to implement `node_label` restrictions on the `deny` portion so people can only access recorded sessions on specified servers. Please restrict session recording replays by node labels so that a user can play all sessions that took place on the same server (but not on other servers).

## What problem does this solve?

Restrict session recording replays by node labels so that a user can play all sessions that took place on the same server (but not on other servers).

## If a workaround exists, please include it.

Current Workaround is to basically restrict users to specified nodes and restrict session_recordings to `node` conditions, but as soon as a person with more than one role to different servers exists, it overwrites the RBAC allowance.

**Comment by zmb3** [comment]
Does the `where` clause in RBAC for sessions solve this use case?

**Comment by Gary-Mansell** [comment]
> Does the `where` clause in RBAC for sessions solve this use case?

Sadly not from my testing. The [documented fields supported](https://goteleport.com/docs/ver/10.0/access-controls/reference/#filter-fields) only include current user attributes but ideally these would be expanded to include node labels stored as part of a session record.

**Comment by moabu** [comment]
Hey @zmb3 ,

We have a similar use case so i'll try to summarize it here.

So we are looking into allowing access to session records for each user that has a label coming from the central IDP.
Im looking here:
https://goteleport.com/docs/access-controls/reference/#filter-fields
Though I can't find any specific keys for the session besides `session.participants` . What I am looking for is to limit the user to view their own session plus their organizations sessions only. We currently pass the organization label and give them access to the vm resources that have the same label.
Here is a portion of the rule and what we want to do
```yaml
  allow:
    app_labels:
      organization: '{{external.org}}'
    db_labels:
      organization: '{{external.org}}'
    kubernetes_labels:
      organization: '{{external.org}}'
    logins:
    - gluu
    node_labels:
      organization: '{{external.org}}'
    rules:
    # Users can only view session recordings for sessions in which they
    # participated or which belong to their organization.
    - resources: [session]
      verbs: [list, read]
      where: contains(session.participants, user.metadata.name) || contains(session.metadata.labels["organization"], user.metadata.labels)
```
The assumed `where` rule `contains(session.metadata.labels["organization"], user.metadata.labels)`  is not right as the session doesn't seem to hold any labels but thats what we wish in some form to achieve.
