### ISSUE TITLE
Nodes showing up on 'sudo tctl nodes ls' but not in UI

### ISSUE THREAD

**Issue by maulik9898** [gravitational/teleport#13604]
Expected behavior:
After registering the node, it should show up in UI

Current behavior:
Node is not showing up on UI

Bug details:
- Teleport version : v9.3.6 git:v9.3.6-0-g83544812d go1.17.11
- Recreation steps
- Debug logs

teleport.yaml on server side
```
teleport:
  nodename: vpn
  auth_token: <token>
  ca_pin:
  - <capin>
  auth_servers:
  - 100.77.204.50:3025
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: yes
  cluster_name: teleport.example.com
  listen_addr: 0.0.0.0:3025
# private ip
  public_addr: 100.77.204.50:3025
  tokens:
  - proxy,node:<token>
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  # public address which caddy hosts in front of Teleport
  public_addr: teleport.example.com:443
  ssh_public_addr: 100.77.204.50:3023
  tunnel_public_addr: 100.77.204.50:3024
#  kube_public_addr: teleport.example.com:3026
```
teleport.yaml on node side
```
teleport:
  nodename: master-1
  auth_token: token
  ca_pin:
  - capin
  auth_servers:
  - 100.77.204.50:3025
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: no
ssh_service:
  enabled: yes
proxy_service:
  enabled: no
```

```
ubuntu@vpn:~$ sudo tctl nodes ls
Host     UUID                                   Public Address      Labels       Version
-------- -------------------------------------- ------------------- ------------ -------
vpn      11ab5da3-cc7d-4775-81eb-5b198c48409... 100.77.204.50:3022  hostname=vpn 9.3.6
master-1 6d0f63e3-c901-4ee7-b7ee-81cff2c6f53... 100.100.133.64:3022              9.3.6
media    bc60a817-b56b-4393-851b-c23c3f3dd4c... 100.94.157.76:3022               9.3.6
```

```
ubuntu@vpn:~$ tsh ls
Node Name Address Labels
--------- ------- ------

```
