### ISSUE TITLE
Non-existent token file not ignored with established services 

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#13605]
Expected behavior:

After the services have established connections a non-existent token file will not cause an error.   A expired or invalid token is ignored if specified directly in the configuration file or by parameter.

Current behavior:

If a non-existent token file, `/tmp/token`, is given, regardless of already established connection, an error is given.  That prevents from using temporary files in a configuration which will be reused.

```bash
ERROR: open /tmp/token: no such file or directory
```

Bug details:
- Teleport version: 9.3.6
- Recreation steps

1.Specify a temp file for the token.  
```yaml
teleport:
  # Data directory for the Application Proxy service. If running on the same
  # node as Auth/Proxy service, make sure to use different data directories.
  data_dir: /var/lib/teleport-app
  # Instructs the service to load the join token from the specified file
  # during initial registration with the cluster.
  auth_token: /tmp/token
```
2. Start teleport and establish a connection for the service
3. REstart the machine without putting a `/tmp/token` file
4. Teleport will fail to start due to missing file.
