### ISSUE TITLE
Dynamic node labels are not visible in the Web UI

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1364]
The web UI is not showing the dynamic labels.
Snippet from a node config:

```
ssh_service:
  enabled: "yes"
  commands:
  - name: arch
    command: [/bin/uname, -v]
    period: 1h0m0s
```

Output of `tsh ls`:

```
Node Name    Node ID                              Address        Labels                                   
------------ ------------------------------------ -------------- ---------------------------------------- 
ev-t1-master 33e52630-c09b-4dd2-97eb-d091c03845c8 127.0.0.1:3022 arch=#1 SMP Debian 4.12.6-1 (2017-08-12) 
```

The web UI says "No assigned labels".
