### ISSUE TITLE
unknown group teleport-system for existing users

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#13662]
Teleport fails to login ssh for existing users when `create_host_user` is set to `true`

Example:
```sh
ubuntu@teleport1:~$ tsh ssh ubuntu@localhost
group: unknown group teleport-system
ERROR: ssh: could not start shell
```

Group added to the user:
```yaml
kind: role
version: v5
metadata:
  name: auto-users
spec:
  options:
    # Allow automatic creation of users.
    create_host_user: true
  allow:
    logins: [ "ubuntu1", "ubuntu" ]
    host_groups: ["ubuntu-teleport-group"]
    host_sudoers: [
      "{{internal.logins}} ALL = (root) NOPASSWD: ALL"
    ]
    node_labels:
      '*': '*'
```

Login success when a group is created (it can be created by Teleport when login into an auto-created account) example:
```sh
ubuntu@teleport1:~$ tsh ssh ubuntu@localhost
group: unknown group teleport-system
ERROR: ssh: could not start shell

ubuntu@teleport1:~$ tsh ssh ubuntu1@localhost
$
the connection was closed on the remote side on  20 Jun 22 07:11 EDT
ubuntu@teleport1:~$ tsh ssh ubuntu@localhost
ubuntu@teleport1:~$ whoami
ubuntu
ubuntu@teleport1:~$ groups # group is not added which is correct
ubuntu adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd
```
Expected behavior:

Teleport should not fail to log in for existing accounts when `teleport-system` doesn't exist.

Bug details:
- Teleport version: v10-alpha
- Debug logs
```
2022-06-20T07:10:56-04:00 ERRO             Error during temporary user cleanup: group: unknown group teleport-system srv/usermgmt.go:341
```
