### ISSUE TITLE
Auto created users are not added to sudoers

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#13663]
Auto-created users are not added to sudoers. Here is my role assigned to the user:

```yml
kind: role
version: v5
metadata:
  name: auto-users
spec:
  options:
    # Allow automatic creation of users.
    create_host_user: true
  allow:
    logins: [ "ubuntu1", "ubuntu" ]
    host_groups: ["ubuntu-teleport-group"]
    host_sudoers: [
      "{{internal.logins}} ALL = (root) NOPASSWD: ALL"
    ]
    node_labels:
      '*': '*'
```

After logging in, `/etc/sudoers.d/` doesn't contain any new files.

Expected behavior:

When the role contains valid `host_sudoers` a new file should be created in `/etc/sudoers.d/`.

Bug details:
- Teleport version v10-alpha
