### ISSUE TITLE
LDAP attribute labeling does not add additional labels

### ISSUE THREAD

**Issue by LKozlowski** [gravitational/teleport#13680]
With this config for `windows_desktop_service`:

```yml
windows_desktop_service:
...
  discovery:
    base_dn: "*"
    label_attributes:
      - location
      - cn
      - primaryGroupID
```

it is expected that if matching LDAP attributes exists, then these labels will be added:
- `ldap/primaryGroupID: xxx`
- `ldap/location: xxx`
- `ldap/cn: xxx`

Right now none of these labels are added.
