### ISSUE TITLE
Node doesn't join cluster. Log repeats "has joined the cluster"

### ISSUE THREAD

**Issue by 0yz** [gravitational/teleport#13718]
Expected behavior:
Node joining the cluster

Current behavior:
The log is showing me this every ~30 seconds and doesn't show up in the Web UI.
```
2022-06-22T10:09:36+02:00 INFO [AUTH]      Node "mysql001" is trying to join with role: Node. auth/join.go:73
2022-06-22T10:09:36+02:00 INFO [CA]        Generating TLS certificate. tlsca/ca.go:800
2022-06-22T10:09:36+02:00 INFO [AUTH]      Node "mysql001" has joined the cluster. auth/join.go:165
2022-06-22T10:10:08+02:00 INFO [AUTH]      Node "mysql001" is trying to join with role: Node. auth/join.go:73
2022-06-22T10:10:08+02:00 INFO [CA]        Generating TLS certificate. tlsca/ca.go:800
2022-06-22T10:10:08+02:00 INFO [AUTH]      Node "mysql001" has joined the cluster. auth/join.go:165
```

Bug details:
- Teleport version
Teleport v9.3.6 git:v9.3.6-0-g83544812d go1.17.11
- Recreation steps
Install teleport server, run "automatic" installation script on node.
I'm trying to run Teleport through an Apache2 reverse proxy server. I can access the web ui but can't get any further with the setup.

/etc/teleport.yaml ( i replaced my domain and mail )
```
version: v2
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  advertise_ip: 10.254.2.73
  diag_addr: ""
  auth_servers:
    - 10.254.2.73:3025
    - teleport.example.org:443
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.org
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.org:443
  https_keypairs: []
#  acme:
#    enabled: "yes"
#    email: mail@example.org
```

ACME is disabled because when it was active i always got the following error: ( i replaced the domain )

```
ERROR REPORT:
Original Error: *errors.errorString acme/autocert: unable to satisfy &#34;https://acme-v02.api.letsencrypt.org/acme/authz-v3/122371169636&#34; for domain &#34;teleport.example.org&#34;: no viable challenge type found
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:376 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:314 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: acme/autocert: unable to satisfy &#34;https://acme-v02.api.letsencrypt.org/acme/authz-v3/122371169636&#34; for domain &#34;teleport.example.org&#34;: no viable challenge type found] alpnproxy/proxy.go:322
2022-06-22T10:05:05+02:00 WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *errors.errorString acme/autocert: missing certificate
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:376 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:314 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: acme/autocert: missing certificate] alpnproxy/proxy.go:322
2022-06-22T10:05:22+02:00 WARN [ALPN:PROX] Failed to handle client connection. error:[
```

If you need more info, i'll happily provide it. -- Thanks for any help.

**Comment by zmb3** [comment]
More information on the Apache reverse proxy would be helpful. Where does it sit in your setup and how is it configured?

**Comment by 0yz** [comment]
> More information on the Apache reverse proxy would be helpful. Where does it sit in your setup and how is it configured?

This is the configuration.
It's on the same network, they have full network access to each other.

```
<VirtualHost *:80>
Servername teleport.example.org
DocumentRoot /var/www/empty
CustomLog /var/log/apache2/teleport.example.org-access.log combined
ErrorLog /var/log/apache2/teleport.example.org-error.log
ServerAdmin support@example.org
LogLevel warn
ServerSignature Off

# Redirect to HTTPS
RewriteEngine On
RewriteCond %{HTTPS} !on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>
<VirtualHost *:443>
SSLEngine on
SSLCertificateKeyFile /var/lib/dehydrated/certs/teleport.example.org/privkey.pem
SSLCertificateFile /var/lib/dehydrated/certs/teleport.example.org/cert.pem
SSLCertificateChainFile /var/lib/dehydrated/certs/teleport.example.org/fullchain.pem
SSLProtocol all -SSLv2 -SSLv3
SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
SSLHonorCipherOrder on
Header always set Strict-Transport-Security "max-age=31536000"
SSLStrictSNIVHostCheck on


Servername teleport.example.org
DocumentRoot /var/www/empty
CustomLog /var/log/apache2/teleport.example.org-access.log combined
ErrorLog /var/log/apache2/teleport.example.org-error.log
ServerAdmin support@example.org
LogLevel warn
ServerSignature Off

SSLProxyEngine on
ProxyPreserveHost on
RequestHeader set X-Forwarded-Proto "https"
SSLProxyCheckPeerCN off
SSLProxyCheckPeerExpire off

Alias /.well-known/acme-challenge /var/www/dehydrated

ProxyPass              /.well-known !
ProxyPass              /        https://10.254.2.73/
ProxyPassReverse       /        https://10.254.2.73/

</VirtualHost>
```

**Comment by 0yz** [comment]
After adding the certiticates manually into teleport.yaml like this the node is now showing up in Teleport

```
proxy_service:
  https_cert_file: /var/lib/dehydrated/certs/teleport.example.org/fullchain.pem
  https_key_file: /var/lib/dehydrated/certs/teleport.example.org/privkey.pem
```

but now i get a different error when trying to connect

```
ERRO [WEBSOCKET] Error upgrading to websocket: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header web/terminal.go:206
```

I tried almost everything in the reverse proxy config so it would upgrade the connection to wss but without any success.
What address/port do i need to upgrade to wss for it to work?

**Comment by 0yz** [comment]
Ok, ignore my last reply. I didn't change anything and suddenly it started working.

In this scenario, 10.254.2.73 is my Teleport server, 443 is the proxy server port.

Teleport Config:

```
version: v2
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  advertise_ip: 10.254.2.73
  diag_addr: ""
  auth_servers:
    - 10.254.2.73:3025
    - teleport.example.org:443
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.org
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  https_cert_file: /var/lib/dehydrated/certs/teleport.example.org/fullchain.pem
  https_key_file: /var/lib/dehydrated/certs/teleport.example.org/privkey.pem
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.org:443
  https_keypairs: []
```

Apache2 Reverse Proxy config:
- don't forget to add your ports to /etc/apache2/ports.conf

```
<VirtualHost *:80>
Servername teleport.example.org
#ServerAlias x
DocumentRoot /var/www/empty
CustomLog /var/log/apache2/teleport.example.org-access.log combined
ErrorLog /var/log/apache2/teleport.example.org-error.log
ServerAdmin support@example.org
LogLevel warn
ServerSignature Off

# Dehydrated
Alias /.well-known/acme-challenge /var/www/dehydrated

# Redirect to HTTPS
RewriteEngine On
RewriteCond %{HTTPS} !on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>

<VirtualHost *:443>
SSLEngine on
SSLCertificateKeyFile /var/lib/dehydrated/certs/teleport.example.org/privkey.pem
SSLCertificateFile /var/lib/dehydrated/certs/teleport.example.org/cert.pem
SSLCertificateChainFile /var/lib/dehydrated/certs/teleport.example.org/fullchain.pem
SSLProtocol all -SSLv2 -SSLv3
SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
SSLHonorCipherOrder on
Header always set Strict-Transport-Security "max-age=31536000"
SSLStrictSNIVHostCheck on

Servername teleport.example.org
#ServerAlias x
DocumentRoot /var/www/empty
CustomLog /var/log/apache2/teleport.example.org-access.log combined
ErrorLog /var/log/apache2/teleport.example.org-error.log
ServerAdmin support@example.org
LogLevel warn
ServerSignature Off

# Dehydrated
Alias /.well-known/acme-challenge /var/www/dehydrated

SSLProxyEngine on
ProxyPreserveHost on
RequestHeader set X-Forwarded-Proto "https"
SSLProxyCheckPeerCN off
SSLProxyCheckPeerExpire off

# WSS Upgrade
RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
RewriteRule .* wss://10.254.2.73:443%{REQUEST_URI} [P,L]

ProxyPass              /.well-known !
ProxyPass              /        https://10.254.2.73/
ProxyPassReverse       /        https://10.254.2.73/
</VirtualHost>
```


Thank you
