### ISSUE TITLE
Mismatch: configuration dump and bootstraped files

### ISSUE THREAD

**Issue by moritzdietz** [gravitational/teleport#1374]
I have noticed the following:
When you run ```teleport start``` it auto-generates all the needed certificates and keys in ```/var/lib/teleport/```. These certs will then automatically be used the next time you start teleport from the command line.  This includes ```/var/lib/teleport/webproxy_key.pem``` and ```/var/lib/teleport/webproxy_cert.pem``` and are probably from here (?!):
https://github.com/gravitational/teleport/blob/7756bed69c88d2b7578d2b8b941427791a9255a2/lib/defaults/defaults.go#L209-L211
https://github.com/gravitational/teleport/blob/7756bed69c88d2b7578d2b8b941427791a9255a2/lib/defaults/defaults.go#L232-L240

When you dump sample configuration file from the command line https://github.com/gravitational/teleport/blob/6b85b01b465ceee168f341eb6ffb4949bdf112e6/tool/teleport/main.go#L195-L199
you get a config that references the cert and key above in a totally different location.
The dumped sample config shows the cert and key here:
https://github.com/gravitational/teleport/blob/6b85b01b465ceee168f341eb6ffb4949bdf112e6/lib/config/fileconf.go#L241-L242

Then I run into an issue that I can't start teleport with the configuration file due to an error.
See the output here:

```
moritz@vps:~$ sudo teleport start --config=/etc/teleport/teleport.yaml
unable to verify HTTPS certificate chain in /var/lib/teleport/webproxy_cert.pem: x509: certificate signed by unknown authority
moritz@vps:~$ cat /etc/teleport/teleport.yaml
#
# Sample Teleport configuration file.
#
teleport:
  nodename: vps
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  storage:
    type: bolt
  auth_token: cluster-join-token
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:cluster-join-token
  oidc_connectors: []
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  labels:
    db_role: master
  commands:
  - name: Uptime
    command: [/usr/bin/uptime]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /var/lib/teleport/webproxy_key.pem
  https_cert_file: /var/lib/teleport/webproxy_cert.pem
moritz@vps:~$ ls /var/lib/teleport/webproxy_*.pem
/var/lib/teleport/webproxy_cert.pem  /var/lib/teleport/webproxy_key.pem
moritz@vps:~$
```

Now I am not able to start teleport with the config file and I am not sure as to why that is.
But if I start teleport by just typing ```teleport start``` it runs without any issues.

It took me a while to figure this out to be honest. Maybe we can have this corrected?
Hope I made my findings clear and you get where I am coming from.
