### ISSUE TITLE
Fail to start with a warning if trying to join a service requiring a reverse tunnel via the auth server

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#13969]
**Expected behavior**

If you run an `app_service` in its own process and provide it with the address of an auth server (which will fail to successfully join the cluster due to lack of a reverse tunnel), Teleport should fail to start with a warning that a proxy server connection needs to be used instead.

**Current behavior**

Teleport will appear to start successfully and will output no errors, but the apps provided will not be visible in the cluster.

I’m raising this with the app service in mind, but we should do it for all services requiring reverse tunnels when not running in the same process as the auth/proxy.

Bug details:
- Teleport version: 9.3.7

```yaml
teleport:
  data_dir: /var/lib/teleport-app
  auth_token: /tmp/token
  # Proxy address to connect to. Note that it has to be the proxy address
  # because the app service always connects to the cluster over a reverse
  # tunnel.
  auth_servers:
  - [redacted]:3025
app_service:
  enabled: yes
  debug_app: true
  apps:
  - name: "jtest-phishing"
     uri: "https://0.0.0.0:3333"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
```
