### ISSUE TITLE
Teleport as generic Certificate Authority

### ISSUE THREAD

**Issue by stereobutter** [gravitational/teleport#14069]
# What would you like Teleport to do?
It would be really useful if teleport could be used as generic CA and `tctl` (or `tsh`?) as tool for users to create certificates for resources not managed by teleport. 

To allow a users to issue certificates for a resource they would require permissions to do so, maybe something like this:

**usage example**
```yaml
kind: role
version: v5
metadata:
  name: ssh-cert-issuer
spec:
  allow:
    certificates:
      - kind: ssh
        principals: ["*.example.com"]
        max_ttl: 24h
```

A user with that role could then issue a certificate

```bash
tctl create_cert --kind=ssh --principal=server001.example.com --ttl=8h
```

# What problem does this solve?
This would allow teleport to be also used for managing access to air-gapped environments that cannot connect to teleport. If `server001.example.com` is such an environment (that is configured to trust ssh certificates signed by teleport) the workflow for ssh-ing into it would be:

* login with teleport (using SSO) and create a short-lived ssh certificate
* use the certificate on-site to access the server

# If a workaround exists, please include it.
Someone with admin access to the CA private key used by teleport auth server could use that CA key for signing whatever they like.
