### ISSUE TITLE
Unable to enroll u2f device

### ISSUE THREAD

**Issue by Omeryl** [gravitational/teleport#1422]
I've configured my u2f stuff (correctly as far as I can tell) as follows:

```yaml
auth_service:
    # .... other auth_service stuff here.
    authentication:
        # default authentication type. possible values are 'local', 'oidc' and 'saml'
        # only local authentication (Teleport's own user DB) is supported in the open
        # source version
        type: local
        # second_factor can be off, otp, or u2f
        second_factor: u2f
        # this section is used if second_factor is set to 'u2f'
        u2f:
            # app_id must point to the URL of the Teleport Web UI (proxy) accessible
            # by the end users
            app_id: https://internal.elizabeth.codes:3080
            facets:
              - https://internal.elizabeth.codes:3080
```

However when I try to register a new user, the u2f token is never actually asked to enroll as far as I can tell. No errors in console. Am I missing something obvious?
