### ISSUE TITLE
Role logins does not allow variables

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1438]
### Problem

The `CheckAndSetDefaults` function for `services.Role` tries to validate `logins` to make sure they are valid Unix names. This is incorrect because they can be role variables like in the example below.

```yaml
kind: "role"
version: "v3"
metadata:
  name: "admin"
spec:
  options:
    max_session_ttl: 30h0m0s
  allow:
    logins: ['{{ external["http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"] }}' , "teleport", "root"]
    node_labels:
      "type": "*"
    rules:
      - resources: ["*"]
        verbs: ["*"]
```

### Proposed Solution

Remove this check from `CheckAndSetDefaults`.
