### ISSUE TITLE
RoleV3 node_labels should be a list, not a map

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1439]
### Problem

In a role `node_labels` is a map. This makes using `node_labels` difficult because either you can grant access to one key value or all (wildcard) but not a subset.

For example if you have the following nodes:

```
one.example.com   type:prod
two.example.com   type:stage
```

Then you have the following role:

```yaml
kind: "role"
version: "v3"
metadata:
  name: "admin"
spec:
  options:
    max_session_ttl: 30h0m0s
  allow:
    logins: ["root"]
    node_labels:
      "type": "prod"
      "type": "stage"
    rules:
      - resources: ["*"]
        verbs: ["*"]
```

This role would only give you access to either `type:prod` or `type:stage`.

### Proposed Solution

Make `node_labels` a list, which will allow us to grant access to subsets.

**Comment by stevenGravy** [comment]
recommend close as you can do:

```yaml
    node_labels:
      type: 
      - prod
      - stage
```
