### ISSUE TITLE
Questions related to teleport internals

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1444]
Hi @kontsevoy 

Please I would like to get answer from you to the following question, for programming purpose.

1) Regarding this part of the node configuration :
```
    # Pre-defined tokens for adding new nodes to a cluster. Each token specifies
    # the role a new node will be allowed to assume. The more secure way to 
    # add nodes is to use `ttl node add --ttl` command to generate auto-expiring 
    # tokens. 
    #
    # We recommend to use tools like `pwgen` to generate sufficiently random
    # tokens of 32+ byte length.
    tokens:
        - "proxy,node:xxxxx"
        - "auth:yyyy"
```
I understand the `proxy` and `node` tokens... What's the purpose of the `auth` token? If I consider the documentation, it means auth servers should use this token to reach the cluster, but In practice I never use this token and the `auth_token` value of the `teleport` section is always the same on every node in the cluster, regardeless the role (`auth`, `proxy`or `node`) :
``` 
teleport:
    # nodename allows to assign an alternative name this node can be reached by.
    # by default it's equal to hostname
    nodename: graviton

    # Data directory where Teleport keeps its data, like keys/users for 
    # authentication (if using the default BoltDB back-end)
    data_dir: /var/lib/teleport

    # one-time invitation token used to join a cluster. it is not used on 
    # subsequent starts
    auth_token: xxxx-token-xxxx
````
So please can you clarify the real and concrete purpose of these token, with use cases?

2) I would like to be sure if signup tokens generated by `tctl users add` command is always `32-length` characters. Is the token length configurable and/or hard-coded somewhere?

Thanks for the great work.

Cheers !
