### ISSUE TITLE
Teleport config flag `local_auth` doesn't seem to be respected

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#14480]
Expected behavior:

With `local_auth: false`, expected to not be able to login with my local credentials

Current behavior:

In v10, i'm able to login with local creds with `tsh login` (with web UI too, the `local_auth` flag returns always true despite setting), but on v9 `tsh login` returns error saying i have local auth disabled (the web UI does not render the login form)

Bug details:
- Teleport version
   - the v9 version that prevents me from logging in: Teleport Enterprise v9.3.9 git:v10.0.0-alpha.2-21-ga639f80e5 go1.18.2 (or the current `branch/v9`)
   - the v10 version that i noticed this issue: the current master
- Recreation steps
   - create a user with just a password 
   - login in through web UI or `tsh login --proxy=<proxy> --user=<user>`
   - config:

```yaml
auth_service:
  enabled: yes
  cluster_name: "im-a-cluster-name"
  authentication:
    type: local
    second_factor: optional
    local_auth: false
    require_session_mfa: no
    webauthn:
      rp_id: localhost
```
