### ISSUE TITLE
Unable to create tustred cluster resource!

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1451]
Hi,

I have main and my trusted configure well configured, with the right trusted token at the two sides.
But when I try to create the trusted resource, it doesn't work, and I don't understand the above error :
``` 
admin@trusted-bastion]~ ❯❯❯ sudo tctl create /etc/teleport/trusted_main_cluster.yaml -d -f              ⏎

ERROR REPORT:
Original Error: *trace.AccessDeniedError access denied: the cluster token has been rejected
Stack Trace:
	/gopath/src/github.com/gravitational/teleport/lib/auth/clt.go:1558 github.com/gravitational/teleport/lib/auth.(*Client).UpsertTrustedCluster
	/gopath/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:190 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).createTrustedCluster
	/gopath/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:72 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).(github.com/gravitational/teleport/tool/tctl/common.createTrustedCluster)-fm
	/gopath/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:169 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create
	/gopath/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:101 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
	/gopath/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:120 github.com/gravitational/teleport/tool/tctl/common.Run
	/gopath/src/github.com/gravitational/teleport/tool/tctl/main.go:33 main.main
	/opt/go/src/runtime/proc.go:194 runtime.main
	/opt/go/src/runtime/asm_amd64.s:2198 runtime.goexit
User Message: 
```

The main auth configuration :

```
admin@ip-10-20-1-6:~$ sudo cat /etc/teleport/teleport.yaml
teleport:
  nodename: main-teleport
  pid_file: /var/run/teleport.pid
  
  auth_token: mzjEwKih0Nwkf9CBj6583jZsu4cNsaVs
  auth_servers:
    - teleport-auth.mydomain.com:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: WARN
  storage:
    type: dynamodb
    region: eu-west-1
    table_name: teleport.state.prod
  data_dir: /var/lib/teleport
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  oidc_connectors: [] 
  cluster_name: main
  tokens:
    - "proxy,node:mzjEwKih0Nwkf9CBj6583jZsu4cNsaVs"
    - "auth:5eI8BC7Hlc0B7R8X4YaEVDWNCqgqDgKR"
    - trusted_cluster:cYXMz6BgsmSj3nLmJaUeR8LtE2wW4liG
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
```

The trusted cluster conf :

```
admin@trusted-bastion]~ ❯❯❯ sudo cat /etc/teleport/teleport.yaml
teleport:
  nodename: teleport-proxy.trusted.com
  pid_file: /var/run/teleport.pid
  advertise_ip: 10.3.0.11
  
  auth_token: HqQsJkjfdRnggfICskmS4hMWBCY52IZn
  auth_servers:
    - teleport-proxy.trusted.com:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: WARN
  storage:
    type: bolt
  data_dir: /var/lib/teleport
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  oidc_connectors: [] 
  cluster_name: main
  tokens:
    - "proxy,node:HqQsJkjfdRnggfICskmS4hMWBCY52IZn"
    - "auth:5MWXEjCbZIMA6eM0EEklQxYYCL65zIHM"
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  labels:
    role: trusted-bastion
    account : trusting
  commands:
    - name: hostname
      command: [/bin/hostname]
      period: 1m0s
    - name: kernel
      command: [/bin/uname, -r]
      period: 1h0m0s
    - name: uptime
      command: [/usr/bin/uptime, -p]
      period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /etc/teleport/private.key
  https_cert_file: /etc/teleport/cert.crt
```
And the trusted cluster resouorce on the trusted bastion :

```
admin@Bastion-sensee]~ ❯❯❯ sudo cat /etc/teleport/trusted_main_cluster.yaml
# cluster.yaml
kind: trusted_cluster
version: v2
metadata:
  # the trusted cluster name MUST match the 'cluster_name' setting of the
  # cluster
  name: main
spec:
  # this field allows to create tunnels that are disabled, but can be enabled later.
  enabled: true
  # the token expected by the "main" cluster:
  token: cYXMz6BgsmSj3nLmJaUeR8LtE2wW4liG
  # the address in 'host:port' form of the reverse tunnel listening port on the
  # "master" proxy server:
  tunnel_addr: teleport-proxy.mydomain.com:3024
  # the address in 'host:port' form of the web listening port on the
  # "master" proxy server:
  web_proxy_addr: teleport-proxy.mydomain.com:3080
```
Since the way of connecting trusted clusters has changes, I didn't two connect trusted clusters again.

Please help troubleshoot and make it work ;) 

Regards,
Eugène NG
