### ISSUE TITLE
Add flag to disable SFTP file copying

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#14661]
Add `disable_copy` flag to RBAC role that will disable copying file over SFTP and SCP. 
Example config:

```yaml
kind: role
version: v5
metadata:
  name: disable-file-copy
spec:
  options:
    # Disable copying files over SFTP and SCP.
    disable_copy: true
```

We should ensure that the implementation doesn't break GUI clients.

For #13216.
