### ISSUE TITLE
Choice of claim to use to identify users

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#14689]
What would you like Teleport to do?
We don’t use the email of our users as username but another claim. In all our other tools (Harbor, Kubernetes, Kibana, Gitlab  ….) connected to our OIDC provider we use the claim “preferred_username” as username. Would it be possible in the oidc connector to add a configuration option allowing us to choose which claim to use to identify the users? .It’s here in the code: https://github.com/gravitational/teleport/blob/1d1c38d0a4858edef72d5828f1d55897928c9cf7/lib/auth/oidc.go#L593-L597
 

What problem does this solve?
Allowing us to choose which claim to use to identify the users

If a workaround exists, please include it.

**Comment by russjones** [comment]
Before we start working on this, let's hammer down what the resource configuration changes will look like.

**Comment by rudream** [comment]
```
kind: oidc
metadata:
  name: Okta
spec:
  ...
  # If specified, use claim from OIDC provider as username. If unspecified, fallback to email.
  username_claim: "preferred_username" 
  ...
version: v2
```

We will default to email if this new field is not set. If the `username_claim` specifies a claim that doesn't exist, we will also default to email to avoid locking users out
