### ISSUE TITLE
Advanced RBAC for external OpenSSH servers

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1469]
## Description

Currently Teleport only supports advanced RBAC (label based access controls) for Teleport nodes. This proposal adds ability to enforce RBAC on OpenSSH servers as well.

### Server resource

System administrators will be able to register external servers using `Server` resource:

```yaml
kind: Node
version: v2
metadata:
   labels: 
       env: prod
spec:
   addr: 172.28.1.3:3022
```

```bash
# create servers entries
tctl create -f servers.yaml
```

### RBAC on proxy

Label based RBAC will be enforced on the proxy level in addition to server level. Proxy will pull the server list, fetch labels for external server and will check the roles.

###  Where rules for servers

There should be a way to allow advanced matching between LDAP groups/OIDC claims and the servers.
We have already implemented this in [Telekube](https://gravitational.com/docs/manage/#cluster-rbac-using-labels) This suggestion is a backport of the same feature set. 

Instead of `node_labels` we are applying `where` condition and adding `connect` verb support for `node`.

This example allows users that are members of the team `development` in LDAP to access servers marked with the same labels `development`

```yaml
kind: role
version: v3
metadata:
  name: developers
spec:
  allow:
    logins:
    - developers
    namespaces:
    - default
    rules:
      - resources: [node]
        verbs: [connect]
        where: contains(user.spec.traits["roles"], resource.metadata.labels["team"])
```

Note that existing static `node_labels` are not applicable for this use case because the name of the label is unknown, and we have to do dynamic matching, therefore we are using more advanced `where` function here.
