### ISSUE TITLE
tsh join requires ssh_recording_config read permission

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#14710]
Expected behavior:

The `tsh join --mode=peer` should work as the Web UI does

Current behavior:

If the user's role does not include the `session_recording_config` the `tsh join` will fail.  The same permission is not required in the UI join session.

```bash
tsh join --mode=peer --login=ubuntu feddb153-6af2-4ad0-901e-726542876e05
ERROR: access denied to perform action "read" on "session_recording_config"
```

Bug details:
- Teleport version 10.0.2
- Recreation steps

Add the following into the `access` role. 
```yaml
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - peer
      name: Join
      roles:
      - access
    ```

Have different users with the same role with a allowed login like `ubuntu`.  Have them join via web.  Then have a user attempt to join from the CLI.

tsh join --mode=peer --login=ubuntu feddb153-6af2-4ad0-901e-726542876e05

Add the following in the role that will allow joining. 

```yaml
    rules:
    - resources:
      - session_recording_config
      verbs:
      - list
      - read
 ```
