### ISSUE TITLE
Change in behavior and potential inconsistency with the in-memory Inventory Control Stream

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#14786]
A configuration like

```yaml
teleport:
  auth_servers: ["12.34.56.78"]
auth_service:
  enabled: yes
ssh_service:
  enabled: yes
```

(where `12.34.56.78` is the publicly reachable address of the server) will result in a ssh heartbeat with an address of `12.34.56.78` in v9, and an address of `::1` in v10, because the in-memory ICS doesn't have a way to extract the intended local address.

I'm not sure what the correct behavior should be, especially as we currently don't (can't?) really check that the auth server specified in `auth_servers` points to ourselves.
