### ISSUE TITLE
Unable to add trusted cluster in 2.3.5

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#1480]
tctl always reports that the cluster always exists.

I've completely blown away the dynamodb and the `/var/lib/teleport` on every system.

I've re-installed my main cluster from scratch, and then setup my second cluster from scratch.

After that I run `tctl create /path/to/trustedcluster.yml` which has the following contents 

```
kind: trusted_cluster
version: v2
metadata:
  description: "Trusted Cluster my-second-cluster"
  name: "my-second-cluster"
  namespace: "default"
spec:
  enabled: true
  token: 6786bdc9b737920xxx97256af0ccf923
  tunnel_addr: my-first-cluster.private.io:3024
  web_proxy_addr: my-first-cluster.private.io:3080
```

And I immediately get `teleport/authorities/host/my-second-cluster` already exists and it does not join.
