### ISSUE TITLE
Node behind NAT doesn't work Teleport v2.3.5 git:v2.3.5-0-gbc8dba6

### ISSUE THREAD

**Issue by kaplan2539** [gravitational/teleport#1485]
Hi I'm trying to realize the following setup with Teleport v2.3.5 git:v2.3.5-0-gbc8dba6:
 - Teleport proxy and auth server running on a single ec2 instance (ip 11.22.33.44, dns: my.domain.tld)
 - Enable incoming ports 3022,3023,3024,3025 and 3080 for the ec2 instance
 - Using Let's Encrypt for the proxy certificates
 - Teleport node running behind NAT/firewall (no incoming ports open, only outgoing traffic allowed)

This is the proxy and auth server `/etc/teleport.yaml` I'm using:
```
teleport:
    nodename: my.domain.tld
    data_dir: /var/lib/teleport
    auth_token: somethingsupersecret
    auth_servers:
        - 11.22.33.44:3025
    connection_limits:
        max_connections: 1000
        max_users: 250
    log:
        output: stdout
        severity: ERROR
    storage:
        type: bolt

auth_service:
    enabled: yes
    authentication:
        type: local
        second_factor: otp
        u2f:
            app_id: https://my.domain.tld:3080
            facets:
            - https://mydomain.tld:3080
    listen_addr: 0.0.0.0:3025
    tokens:
        - "proxy,node:somethingsupersecret"
    cluster_name: "main"

ssh_service:
    enabled: no

proxy_service:
    enabled: yes
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3024
    web_listen_addr: 0.0.0.0:3080
    https_key_file: /etc/letsencrypt/live/my.domain.tld/privkey.pem
    https_cert_file: /etc/letsencrypt/live/my.domain.tld/fullchain.pem
```

On the node, the contents of `/etc/teleport.yaml` is:
```
teleport:
    nodename: mynode
    data_dir: /var/lib/teleport
    auth_token: somethingsupersecret
    auth_servers:
        - 11.22.33.44:3025
    connection_limits:
        max_connections: 1000
        max_users: 250
    log:
        output: stdout
        severity: ERROR
    storage:
        type: bolt

ssh_service:
    enabled: yes
    listen_addr: 0.0.0.0:3022
    labels:
        role: debian_node
        type: my node running Debian
    permit_user_env: false

auth_service:
    enabled: no

proxy_service:
    enabled: no
```

Added a standard user on the proxy & auth server:
```
tctl users add elliot debian,root
```

Both proxy/auth server and node a running teleport.
I can login as `elliot` on https://my.domain.tld:3080 and the node shows up as running.
However, it is not possible to login to the node. Both web interface and `tsh` run into a timeout.

Am I doing sth. wrong here?

Running `teleconsole` on the node behind the NAT/firewall works fine btw.
