### ISSUE TITLE
StrictHostKeyChecking

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1486]
### Problem

Starting with Teleport 2.4, Teleport will support a recording mode proxy which re-establishes connections to the target host. When the proxy is making a connection to the target host, it needs to evaluate the host key or certificate.

The certificate can be evaluated by checking if the CA that signed it is known to the cluster. What should the behavior be when Teleport encounters a key? 

### Proposed Solution

@klizhentas has proposed the following:

```
I suggest we call this an option `StrictHostKeyChecking` just like in OpenSSH. and add 3
modes, `yes`, `no` and `warn`. `Warn` mode is useful for transition purposes so admins
can track if there are any servers/login attempts left in the fleet. Default is set to
`yes`.
```

**Comment by klizhentas** [comment]
Some notes:

* will be probably called `strict_host_key_checking` in Teleport's naming convention
* will be part of cluster config
* in all operation modes when presented with invalid/non trusted certificate, will return error
* only allows public keys "trust on all uses" scenario for hosts.

**Comment by kontsevoy** [comment]
@russjones the cluster config resource hasn't been documented yet. Shall we update this ticket to include what cluster options we're supporting here, i.e. dump the entire YAML resource, so it can be forwarded to me so I can update the docs too?

**Comment by russjones** [comment]
@kontsevoy The initial version was documented here: https://github.com/gravitational/teleport/issues/1329

The production version ended up looking very similar:

```yaml
kind: cluster_config
version: v3
metadata:
  name: cluster-config
spec:
  cluster_id: d7b55ca9-5d56-4235-b1b8-1c038e339afa
  session_recording: proxy
```

It gets populated by the `session_recording` field in Teleport configuration.

```yaml
# fragment of /etc/teleport.yaml
auth_service:
   # session_recording possible options: "node" (default) "proxy" and "off"
   session_recording: "node"
```
