### ISSUE TITLE
Applications are NOT accessible

### ISSUE THREAD

**Issue by aug70** [gravitational/teleport#14861]
Expected behavior:

Applications are accessible.

Current behavior:

Applications are NOT accessible.

Bug details:
- Teleport version: v10.0.2 git:v10.0.2-0-g47e0914fb go1.18.3
- Recreation steps: Create a simple app that runs on teleport host like nginx or just simply enable debug app dumper.
- Debug logs: Below

I'm trying to get teleport applications working, I tried every possible configuration, I have a virtual server forward on my router that connects to;
- An Nginx Proxy Manager (this configuration works for everything except doesn't work for applications)

or

- Directly to the Node (this configuration works for everything except  doesn't work for applications)

Below is my `teleport.yaml` file. I integrated with Github connector and everything seems to be working fine. I can add hosts and be able to open a session with them, all works fine as desired.
Except when I try to add applications, like enable debug app or just try to add a simple nginx app. They show on the dashboard but none of them work.

Bottom line, applications are visible on the dashboard but NOT accessible. I appreciate if I can get any help on this.

```
# teleport version
Teleport v10.0.2 git:v10.0.2-0-g47e0914fb go1.18.3
```

```
version: v2
teleport:
  nodename: node1
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.my.domain
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.my.domain:443
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: nginx
    uri: http://localhost
    insecure_skip_verify: true
    public_addr: ""
```

Errors appear with `DEBUG` 

```
 teleport[8041]: 2022-07-25T19:58:36Z DEBU [PROXY:AGE] Failed to create client to teleport.my.domain:443. error:[
 teleport[8041]: ERROR REPORT:
 teleport[8041]: Original Error: *errors.errorString ssh: handshake failed: ssh: overflow reading version string
 teleport[8041]: Stack Trace:
 teleport[8041]:         /go/src/github.com/gravitational/teleport/api/observability/tracing/ssh/ssh.go:98 github.com/gravitational/teleport/api/observability/tracing/ssh.NewClientConn
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent_dialer.go:74 github.com/gravitational/teleport/lib/reversetunnel.(*agentDialer).DialContext
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:350 github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:305 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:302 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).connectAgent
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:261 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).run
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:245 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).Start.func1
 teleport[8041]:         /opt/go/src/runtime/asm_arm64.s:1263 runtime.goexit
 teleport[8041]: User Message: ssh: handshake failed: ssh: overflow reading version string] cluster:teleport.my.domain reversetunnel/agent_dialer.go:81
 teleport[8041]: 2022-07-25T19:58:36Z DEBU [PROXY:AGE] Changing state connecting -> closed. leaseID:586 target:teleport.my.domain:443 cluster:teleport.my.domain reversetunnel/agent.go:273
 teleport[8041]: 2022-07-25T19:58:36Z DEBU [PROXY:AGE] Failed to connect agent. error:[
 teleport[8041]: ERROR REPORT:
 teleport[8041]: Original Error: *trace.BadParameterError failed to dial: all auth methods failed
 teleport[8041]: Stack Trace:
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent_dialer.go:98 github.com/gravitational/teleport/lib/reversetunnel.(*agentDialer).DialContext
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:350 github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:305 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:302 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).connectAgent
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:261 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).run
 teleport[8041]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:245 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).Start.func1
 teleport[8041]:         /opt/go/src/runtime/asm_arm64.s:1263 runtime.goexit
 teleport[8041]: User Message: failed to dial: all auth methods failed] cluster:teleport.my.domain reversetunnel/agentpool.go:263
````
