### ISSUE TITLE
Direct-tcpip

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1487]
### Problem

When using the recording proxy can establish a `direct-tcpip` connection to another node and then directly communicate with it bypassing session logging. Teleport should support an option to disable `direct-tcpip`.

**Comment by klizhentas** [comment]
Per `OpenSSH` protocol spec: https://github.com/metacloud/openssh/blob/master/PROTOCOL.certkeys

will be called:

`permit-port-forwarding` and should be part of existing SSH options in our RBAC ssh options key map.

**Comment by kontsevoy** [comment]
It's a bit unclear to me, what are we doing with this issue? Sounds like a legit use of SSH and folks should realize that session recording cannot possibly record other traffic. Update the docs?

**Comment by klizhentas** [comment]
no, add the flag to support turning `permit-port-forwarding` off in the RBAC like we did for pty

**Comment by knisbet** [comment]
Silly question, but even without being able to record the session, do we audit log the other traffic, like the user setup the following tunnel, or used SCP to copy a file of x bytes to the destination?

**Comment by klizhentas** [comment]
some of it  in audit events, yes

**Comment by kontsevoy** [comment]
makes sense, I didn't realize we haven't done it yet.
here's the updated role definition with a new flag:

```yaml
kind: role
version: v3
metadata:
  name: admin
spec:
  # SSH options used for user sessions 
  options:
    # max_session_ttl defines the TTL (time to live) of SSH certificates 
    # issued to the users with this role.
    max_session_ttl: 8h

    # forward_agent controls either users are allowed to use SSH agent forwarding
    forward_agent: true
   
    # port_forwarding controls either users are allowed to forward ports
    port_forwarding: true
```
