### ISSUE TITLE
Node add to cluster with the POST error

### ISSUE THREAD

**Issue by Samuel0227** [gravitational/teleport#14983]
When I try to add the teleport agent(2nd instance) in to the teleport cluster,it notice the following error 
```
022-07-28T08:11:34Z INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:382
2022-07-28T08:11:44Z ERRO [PROC:1]    Node failed to establish connection to cluster: Post "https://teleport-k8s.example.com:443/v1/webapi/host/credentials": EOF, Get "https://teleport.cluster.local/v2/cacert": EOF. service/connect.go:81
```
I set the same setting in another node , it could connect to the cluster, the `/etc/teleport.yaml` as the following 
```
teleport:
  nodename: test-instances
  advertise_ip: 10.20.95.27
  auth_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
  log:
    output: /tmp/teleport.log
    severity: INFO
  data_dir: /var/lib/teleport
  auth_servers:
      - teleport-k8s.example.com:443
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: yes
  labels:
      role: test
      stack: DEV
      type: VM
```

Bug details:
- Teleport v9.0.2,both agent and cluster
