### ISSUE TITLE
Proxy + Auth version mismatch can result in apparently broken audit log.

### ISSUE THREAD

**Issue by medains** [gravitational/teleport#14993]
Raising this issue for visibility (and web-searchability), though the resolution is straightforward (TLDR: bring proxy up to the same version as auth).

**Expected behavior:**

In a situation with auth and proxy on separate hosts; during the upgrade process whilst testing the functionality after upgrade of the auth host, but before proceeding to the proxy - the audit log should not appear to be broken.

**Current behavior:**

Audit log is broken.

**Bug details:**
- _Teleport version_
In this example, auth on version 8.3.15 and proxy on 8.0.0 - but other combinations may result in the same outcome when there is a change to the JSON of any audit log entry.

- _Recreation steps_
Deploy an auth host on version 8.3.15 with the following configuration (in this case in AWS on RHEL hosts with dynamodb storage)
```
#
# A Sample Teleport configuration file.
# Creates a single proxy, auth and node server.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v2
teleport:
  nodename: teleport1
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
  storage:
    type: dynamodb
    region: eu-west-2
    table_name: TeleportTest
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  acme: {}
```

Add an auth token for the proxy, and a user.

```
tctl tokens add -type=PROXY,NODE -value=test
tctl users add -roles=access,editor -logins=ec2-user testuser
```

Install teleport 8.0.0 on another host and execute in proxy mode with the command provided by the auth, e.g.
```
teleport start --roles=proxy,node --token=test --ca-pin=sha256:BLAHBLAH --auth-server=IP_ADDR:3025
```

Use the new proxy to register the testuser and log in - then attempt to access the audit log.

An error such as attached will be shown:   'failed to parse event, session record is corrupted'

![Screenshot 2022-07-28 at 14 54 16 (3)](https://user-images.githubusercontent.com/914674/181526207-003c3e3e-27c5-4231-a9f7-0aa0d1344ee3.jpg)

This also occurs with file-based audit log storage.
After some testing, in this case we determined that the audit log entry causing the problem was "cert.create"

**End user effect:**
Whilst the fix for this circumstance is easy to apply (upgrade the proxy to the same version as the auth host) - a team performing due diligence on the upgrade process may waste significant time due to the perceived error - and may even cancel or roll-back the upgrade.

**Recommendation:**
Perhaps a better handling of unmarshallable audit log entries would be to display them as "unknown" in the audit log, and show the JSON in the audit log details for that entry - rather than not showing any audit log at all.
