### ISSUE TITLE
Allow for multiple role request approval thresholds in the same role

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#15008]
What would you like Teleport to do?
The ability to specify different approval thresholds per role request within the same role. 

For instance, I want the requesting role to be able to request `test-request` and `k3-role`, but I want `test-request` to require 2 approvals and `k3-role` only to require 1 approval. 

I tried 

```
     request:
      roles:
      - test-request
      thresholds:
      - approve: 1
        deny: 1
    request:
      roles:
      - k3-role
      thresholds:
      - approve: 2
        deny: 1
```

I also tried

```
    request:
      roles:
      - test-request
      - k3-role
      thresholds:
      - approve: 1
        deny: 1
      - approve: 2
        deny: 1
```

What problem does this solve?
It allows users to consolidate the needed roles to accommodate custom approval thresholds. 

If a workaround exists, please include it.

Create multiple roles to specify different approval thresholds and assign those roles to the same user.
