### ISSUE TITLE
upgrading 2.2 to 2.3 thinks I am renaming my cluster

### ISSUE THREAD

**Issue by scottbessler** [gravitational/teleport#1501]
I currently have a 2.2.7 cluster running just fine with this config:

(redacted secrets and replaced the current auth server hostname with teleport.hostname.fake for purposes of this issue)

```yaml
teleport:
    # Logging configuration. Possible output values are 'stdout', 'stderr' and
    # 'syslog'. Possible severity values are INFO, WARN and ERROR (default).
    #log:
    #    severity: DEBUG

# This section configures the 'node service':
ssh_service:
    # Turns 'ssh' role on. Default is 'yes'
    enabled: yes

    # IP and the port for SSH service to bind to.
    #listen_addr: 0.0.0.0:3022
    # See explanation of labels in "Labeling Nodes" section below
    labels:
        role: auth

# List (YAML array) of commands to periodically execute and use
    # their output as labels.
    # See explanation of how this works in "Labeling Nodes" section below
    commands:
    - name: hostname
      command: [/bin/hostname]
      period: 1m0s
    - name: arch
      command: [/bin/uname, -p]
      period: 1h0m0s

auth_service:
    cluster_name: cfe5152a-5494-45f4-8ade-fb531de0c4f7
    # Turns 'auth' role on. Default is 'yes'
    enabled: true
    tokens:
       - "node:REDACTED"
    authentication:
      type: local
      second_factor: otp

# This section configures the 'proxy servie'
proxy_service:
    # Turns 'proxy' role on. Default is 'yes'
    enabled: yes

    # SSH forwarding/proxy address. Command line (CLI) clients always begin their
    # SSH sessions by connecting to this port
    #listen_addr: 0.0.0.0:3023

    # Reverse tunnel listening address. An auth server (CA) can establish an
    # outbound (from behind the firewall) connection to this address.
    # This will allow users of the outside CA to connect to behind-the-firewall
    # nodes.
    #tunnel_listen_addr: 0.0.0.0:3024

    # The HTTPS listen address to serve the Web UI and also to authenticate the
    # command line (CLI) users via password+HOTP
    #web_listen_addr: 0.0.0.0:3080

    # TLS certificate for the HTTPS connection. Configuring these properly is
    # critical for Teleport security.
    https_key_file: /etc/letsencrypt/live/teleport.hostname.fake/privkey.pem
    https_cert_file: /etc/letsencrypt/live/teleport.hostname.fake/fullchain.pem
```

when i try and upgrade by stopping the 2.2.7 server and swapping in the 2.3.5 binaries (using same config an data dir) I get this error on startup:
```
cannot rename cluster "teleport.hostname.fake" to "cfe5152a-5494-45f4-8ade-fb531de0c4f7": clusters cannot be renamed, initializing teleport
```
