### ISSUE TITLE
Memory error when attempting to join kube session

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#15494]
Expected behavior:

A user can join `kube` kube sessions as allowed for `ssh` sessions.

Current behavior:

If a user attempts to join a kube session they get this error.

```bash
$ tsh kube join a3eafa1f-9d2c-495e-82fe-4b6d24428fd7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2c39a65]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.NewKubeSession({0x3d856d8, 0xc0009908a0}, 0xc00099e380, {0x3d9bed0, 0xc000370000}, {0xc000ab5d00, 0x1f}, {0xc000d74520, 0x20}, {0x3857cc9, ...}, ...)
	/go/src/github.com/gravitational/teleport/lib/client/kubesession.go:64 +0x1a5
main.(*kubeJoinCommand).run(0xc000959540, 0xc00095d400)
	/go/src/github.com/gravitational/teleport/tool/tsh/kube.go:200 +0x5bb
main.Run({0x3d868c8, 0xc000958f40}, {0xc00004e090, 0x3, 0x3}, {0x0, 0x0, 0xc0000021a0?})
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:920 +0x12f9f
main.main()
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:401 +0x318
```

```yaml
kind: role
metadata:
  name: access-example
spec:
  allow:
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - peer
      name: join example
      roles:
      - '*'
version: v5
```

Bug details:
- Teleport version: 10.1.2
- Recreation steps. 
   Create a user with the above role.  Attempt to join a another user's kube session.
