### ISSUE TITLE
Teleport event handler `configure` command produces incorrect role.yaml

### ISSUE THREAD

**Issue by dumez-k** [gravitational/teleport#15500]
Expected behavior:
Should produce a role yaml that can be fed into `tctl create -f` directly. 

Current behavior:
Produces this:
```
kind: user
metadata:
  name: teleport-event-handler
spec:
  roles: ['teleport-event-handler']
version: v2
---
kind: role
metadata:
  name: teleport-event-handler
spec:
  allow:
    rules:
      - resources: ['event']
        verbs: ['list','read']
version: v5
```

The role should be defined before the user. If it isn't create will fail when creating the user with the error `role teleport-event-handler is not found`.

The two should be flipped.

Bug details:
- Teleport version 
Teleport Enterprise v10.1.2
- Recreation steps 
run `/teleport-event-handler configure . <PROXY_URL>` and then `tctl create -f teleport-event-handler-role.yaml`
- Debug logs
*trace.NotFoundError role teleport-event-handler is not found
