### ISSUE TITLE
Cannot start with insecure flag with self signed cert

### ISSUE THREAD

**Issue by anselmhou** [gravitational/teleport#15859]
Hi,

Following the quick start guide using the "Private network deployment" approach with Teleport v10.1.4

I found that the `insecure` flag doesn't take effect when trying to start my first teleport server, and the following is stack trace:

```
root@tele-host:/usr/local/iac/resource# teleport start --insecure --config=/etc/teleport.yaml

ERROR REPORT:
Original Error: *trace.BadParameterError unable to verify HTTPS certificate chain in : 
ERROR REPORT:
Original Error: x509.UnknownAuthorityError x509: certificate signed by unknown authority
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/utils/certs.go:192 github.com/gravitational/teleport/lib/utils.VerifyCertificateChain
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:799 github.com/gravitational/teleport/lib/config.applyProxyConfig
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:404 github.com/gravitational/teleport/lib/config.ApplyFileConfig
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:1831 github.com/gravitational/teleport/lib/config.Configure
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:379 github.com/gravitational/teleport/tool/teleport/common.Run
	/go/src/github.com/gravitational/teleport/tool/teleport/main.go:34 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: x509: certificate signed by unknown authority
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:800 github.com/gravitational/teleport/lib/config.applyProxyConfig
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:404 github.com/gravitational/teleport/lib/config.ApplyFileConfig
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:1831 github.com/gravitational/teleport/lib/config.Configure
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:379 github.com/gravitational/teleport/tool/teleport/common.Run
	/go/src/github.com/gravitational/teleport/tool/teleport/main.go:34 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: unable to verify HTTPS certificate chain in : 
ERROR REPORT:
Original Error: x509.UnknownAuthorityError x509: certificate signed by unknown authority
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/utils/certs.go:192 github.com/gravitational/teleport/lib/utils.VerifyCertificateChain
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:799 github.com/gravitational/teleport/lib/config.applyProxyConfig
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:404 github.com/gravitational/teleport/lib/config.ApplyFileConfig
	/go/src/github.com/gravitational/teleport/lib/config/configuration.go:1831 github.com/gravitational/teleport/lib/config.Configure
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:379 github.com/gravitational/teleport/tool/teleport/common.Run
	/go/src/github.com/gravitational/teleport/tool/teleport/main.go:34 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: x509: certificate signed by unknown authority
```

Please kindly advise.  Thanks

**Comment by webvictim** [comment]
Can you please share your `/etc/teleport.yaml` file (in particular the `https_keypairs` section under `proxy_service`) and provide some information about the contents of the file you're providing there?

- Are you providing a path to certificate and key files?
- Does the certificate file have more than one certificate in?
- If so, what's the order of the certificates in the file?

Thanks.

**Comment by PrettyABoy** [comment]
I'm also having trouble while trying to start teleport using `self-signed certificate `
and I have tried on both v13.0.2 and v12.4.3

``` shell
root@RC169:~# sudo teleport start --insecure --config="/etc/teleport.yaml"
ERROR: "unable to verify HTTPS certificate chain in : \x1b[31mERROR: \x1b[0mWARNING:"

  The proxy you are connecting to has presented a certificate signed by a
  unknown authority. This is most likely due to either being presented
  with a self-signed certificate or the certificate was truly signed by an
  authority not known to the client.

  If you know the certificate is self-signed and would like to ignore this
  error use the --insecure flag.

  If you have your own certificate authority that you would like to use to
  validate the certificate chain presented by the proxy, set the
  SSL_CERT_FILE and SSL_CERT_DIR environment variables respectively and try
  again.

  If you think something malicious may be occurring, contact your Teleport
  system administrator to resolve this issue.
```
And here is my config file generate by command `sudo teleport configure -o file     --cluster-name=xxx.org     --public-addr=xxx.org     --cert-file=/ssl/cert.pem     --key-file=/ssl/private.rsa`
```yml
version: v3
teleport:
  nodename: RC169
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: xxx.org
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: xxx.org:443
  https_keypairs:
  - key_file: /ssl/private.rsa
    cert_file: /ssl/cert.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```
