### ISSUE TITLE
Deny rules doesn't respect the "where" clause.

### ISSUE THREAD

**Issue by jingsun-teleport** [gravitational/teleport#15889]
**_Expected behavior:_**
Deny rules should respect the "where" clause.

**_Current behavior:_**
Deny rules doesn't respect the "where" clause, and apply to all users with the role.

**_Bug details:_**
**- Teleport version:** v10
**- Recreation steps**
1. Create a teleport role  testrole1 with deny rules,
```
kind: role
metadata:
  name: testrole1
spec:
  allow: {}
  deny:
    kubernetes_labels:
      region: 'testlabel'
    db_labels:
      region: 'testlabel'
    rules:
    - resources:
        - kube_service
      verbs: [create, update, delete]
      where: 'contains(user.spec.roles, "testrole2")'
    - resources:
        - db_server
      verbs: [create, update, delete]
      where: 'contains(user.spec.roles, "testrole2")'
version: v5
```
2. User with roles testrole1 and testrole2 will be denied to access kubernetes with label region:testlabel, and it is correct.
3. User with roles testrole1 only will also be denied to access kubernetes with label region:testlabel, and it should not be.

**_- Debug logs_**
