### ISSUE TITLE
kubernetes_labels does not respect where clause

### ISSUE THREAD

**Issue by codersofthedark** [gravitational/teleport#15897]
**Expected behavior:**
`kubernetes_labels` should respect the `where` clause

In the example, a `user` should be denied access to `kubernetes cluster` having label `test_label_name` with value `test_label_value` `where` `username` is `testuser`

**Current behavior:**
`kubernetes_labels` do not respect the `where` clause. 

In the example, access to `kubernetes cluster` having label `test_label_name` with value `test_label_value` was denied to all the users. 

**Bug details:**
- Teleport version: v10

**Recreation steps / Example:**

Create a teleport role `testrole` with `deny` rules:
```
kind: role
metadata:
  name: testrole
spec:
  deny:
    kubernetes_labels:
      test_label_name: 'test_label_value'
    rules:
    - resources:
        - kube_service
      verbs: [create, update, delete]
      where: 'contains(user.spec.traits["uername"], "testuser")'
version: v5
```
