### ISSUE TITLE
Step 3/3 Access your Kubernetes cluster: Confusing concepts around different users. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#15907]
## Details
We recently updated our Kubernetes docs to follow the principle of least privilege and discourage people from using the "system:masters" Kubernetes group. Step 3 of 3 https://goteleport.com/docs/kubernetes-access/getting-started/#grant-access-to-your-teleport-user 

We introduce the concept of two users, the Kubernetes user and the Teleport user.  It's not 100% clear that the USER in the role needs to be replaced. It would be good if we could provide a color prompt for items that need to be changed the docs. 

<img width="263" alt="image" src="https://user-images.githubusercontent.com/559288/187244449-696a04fe-9c4c-4bdf-aa21-c492fa943688.png">

When we say 'Retrieve your user' we should ay  'Retrieve your Teleport User', also this flow is good for local users, but does not take into account SSO users. 

Suggestions:
- [ ] Diagram to show RBAC mapping of Kubernetes user to Teleport user.
- [ ] Splitting it into 3a ( create Kubernetes role ), 3b (Apply K8s role to Teleport user ) 
- [ ] Improve visual clues for things that need to replaced & updated. 

### Category
- Improve Existing

**Comment by benarent** [comment]
DigitalOcean shows a different highlight for items that need to be updated by users. I've 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/559288/187245604-5f83d689-bbfe-4dbd-9e51-dce6650f6bf2.png">
 
I ran into the same problem with Ansible Docs, as there is no visual clue that it needs to be updated. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/559288/187245938-b4a59dd0-e843-428b-bd42-9e6a494180fb.png">

**Comment by alexfornuto** [comment]
I think there are two asks here. The first, which is immediately actionable, is to clarify the need to replace `USER` in the example config provided. 

The second is to add the ability to the docs stack to highlight specific sections of code blocks. PrismJS can [highlight lines](https://prismjs.com/plugins/line-highlight/) with a plugin, but I'm not sure how we'd do it for individual blocks of text. In any case, I'll split this into a feature request for the docs repo.

**Comment by ptgott** [comment]
@benarent There have been some changes to the `docs/pages/includes/kubernetes-access/rbac.mdx` partial, which this PR is referring to. E.g., it uses the `docs/pages/includes/add-role-to-user.mdx` partial to include SSO instructions, and also tells the reader to replace `USER` with the output of a command. Do these address this issue?

**Comment by benarent** [comment]
It's OK, but  would personally add a comment to make it clear. As I'm often quickly copy and paste examples. 

e.g.


```yaml
kind: role
metadata:
  name: kube-access
version: v6
spec:
  allow:
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: pod
        namespace: "*"
        name: "*"
    kubernetes_groups:
    - viewers
    # Update USER with Kubernetes user for your current context.
    kubernetes_users:
    - USER
  deny: {}
```
