### ISSUE TITLE
Add Azure discovery to helm chart

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#16019]
Add helm chart for Azure config in the `db_service` section, like we have for AWS.

Please also update the docs here: docs/pages/setup/helm-reference/teleport-kube-agent.mdx

Related PRs: #15629 #15986

Issue this supports: #14688 

example config:
```yaml
  # Matchers for registering Azure-hosted databases.
  azure:
    # Database types. Valid options are:
    # 'mysql' - discovers and registers Azure MySQL single-server databases.
    # 'postgres' - discovers and registers Azure PostgreSQL single-server databases.
  - types: ["mysql", "postgres"]
    # Azure regions to register databases from. Valid options are:
    # '*' - discovers databases in all regions (default).
    # Any valid Azure region name. List all valid regions using the Azure "az" cli: `az account list-locations -o table`
    regions: ["eastus", "westus"]
    # Azure subscription IDs to register databases from. Valid options are:
    # '*' - discovers databases in all subscriptions (default).
    subscriptions: ["11111111-2222-3333-4444-555555555555"]
    # Azure resource groups to register databases from. Valid options are:
    # '*' - discovers databases in all resource groups within configured subscription(s) (default).
    resource_groups: ["group1", "group2"]
    # Azure resource tags to match when registering databases.
    tags:
      "*": "*"
```

What problem does this solve?
* Configuring Teleport to use azure discovery via helm chart
