### ISSUE TITLE
DBeaver/PGAdmin not able to connect to postgres with non-multiplexing cluster

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#16384]
### Expected behavior:

After trying various combinations of connecting directly to the postgres proxy port, running `tsh proxy db`, and `tsh proxy db --tunnel`, it appears that a non-multiplexed instance of teleport with a separate DNS name for web and non-web services break accessing postgres with java clients.

### Current behavior:

Basic cluster info: this was set up with the terraform+aws scripts with ACM enabled. Some changes were made. A separate nlb for all non-web ports was set up with its own DNS name. The config file reflects this.

```yaml
proxy_service:
  enabled: "yes"
  public_addr: 'teleport.example.com:443'
  ssh_public_addr: 'nlb-teleport.example.com:3023'
  tunnel_public_addr: 'nlb-teleport.example.com:3024'
  kube_public_addr: 'nlb-teleport.example.com:3026'
  mysql_public_addr: 'nlb-teleport.example.com:3036'
  postgres_public_addr: 'nlb-teleport.example.com:5432'
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
  web_listen_addr: 0.0.0.0:3080
  postgres_listen_addr: 0.0.0.0:5432
```

The `teleport.example.com` DNS leads to an ALB with an ACM cert enabled.

All other services are set up on `nlb-teleport.example.com` with the respective ports in place.

---

DBeaver, pgadmin4, and other java-based database clients are not able to connect to redshift + postgres databases

When connecting to the postgres port on the proxy:

> Unable to connect to server: connection to server at "nlb-teleport.example.com" (10.0.0.22), port 5432 failed: server closed the connection unexpectedly. This probably means the server terminated abnormally before or while processing the request.

So we tried with the proxy even though multiplexing isn't used:

> An error occurred while setting up the SSL connection.

We realized that we were hitting https://github.com/gravitational/teleport/issues/6116 and manually converted the files generated by `tsh proxy db` from PEM to DER, but that resulting in the following error:

> Could not find a java cryptographic algorithm: Cannot find any provider supporting 1.2.840.113549.1.5.13.
>   Cannot find any provider supporting 1.2.840.113549.1.5.13

It seems that none of the jdbc providers know what to do with some of the x509 extensions that teleport uses, and they panic.

So we tried using `--tunnel` mode, but that resulted in behavior where tsh would report it is listening, but we got connection refused.

---

It seems like the Java / JDBC based clients can't quite handle the certs that Teleport generates for them (even with converting them to DER specifically). Additionally, the last resort tunnel mode of the proxy command failed.

It seems like we should add in some tests to deal with DER format certs and test them with various JDBC driver implementations out there.

### Bug details:
- Teleport version -  v9.3.18
- Recreation steps - set up a cluster with a separate ALB and NLB with distinct DNS names, and try to access redshift via dbeaver or pgadmin4.
- Debug logs

gz#6279
