### ISSUE TITLE
transport: authentication handshake failed: x509 [something.teleport.cluster.local]

### ISSUE THREAD

**Issue by m-abramovich** [gravitational/teleport#16446]
Expected behavior:
Agent on Kubernetes starts and joins the remote cluster.

Current behavior:
Fails with the message:
```ERROR REPORT:
Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: authentication handshake failed: x509: certificate is valid for auth.teleport.<REDUCTED_DOMAIN>, teleport.<REDUCTED_DOMAIN>, not 6d6f6f6e73746f6e652d746f6f6c736574.teleport.cluster.local&#34;
```

Bug details:
- Teleport version (both cluster and agent)
**10.1.9**
- Recreation steps

    create values.yaml
    ```
    authToken: ${auth_token}
    proxyAddr: ${proxy_addr}
    extraArgs:
      - --auth-server=${auth_addr}
      - --nodename=${nodename}
    ```
    run Helm installation and check logs
    ```
    helm install teleport-agent teleport/teleport-kube-agent --version 10.1.9 -f values.yaml
    kubectl logs -f teleport-kube-agent-0
    ```

- Debug logs
```ERROR REPORT:
Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: authentication handshake failed: x509: certificate is valid for auth.teleport.<REDUCTED_DOMAIN>, teleport.<REDUCTED_DOMAIN>, not 6d6f6f6e73746f6e652d746f6f6c736574.teleport.cluster.local&#34;
Stack Trace:
	/go/src/github.com/gravitational/teleport/api/client/client.go:2768 github.com/gravitational/teleport/api/client.(*Client).GetDomainName
	/go/src/github.com/gravitational/teleport/lib/auth/httpfallback.go:35 github.com/gravitational/teleport/lib/auth.(*Client).GetDomainName
	/go/src/github.com/gravitational/teleport/lib/service/connect.go:1158 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newClientDirect
	/go/src/github.com/gravitational/teleport/lib/service/connect.go:1051 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newClient
	/go/src/github.com/gravitational/teleport/lib/service/connect.go:628 github.com/gravitational/teleport/lib/service.(*TeleportProcess).firstTimeConnect
	/go/src/github.com/gravitational/teleport/lib/service/connect.go:232 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect
	/go/src/github.com/gravitational/teleport/lib/service/connect.go:195 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService
	/go/src/github.com/gravitational/teleport/lib/service/connect.go:70 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService
	/go/src/github.com/gravitational/teleport/lib/service/service.go:2406 github.com/gravitational/teleport/lib/service.(*TeleportProcess).registerWithAuthServer.func1
	/go/src/github.com/gravitational/teleport/lib/service/supervisor.go:539 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	/go/src/github.com/gravitational/teleport/lib/service/supervisor.go:276 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
```

**Comment by strideynet** [comment]
Hey, thanks for reporting this. Have you been able to connect other nodes successfully to your Teleport cluster, or is this your first node you are trying to add ?

We often see this issue when the `public_addr` has not been correctly configured in the Teleport Auth/Proxy service. It may help for us to take a look at the configuration of your Teleport service after any sensitive values have been redacted.

**Comment by m-abramovich** [comment]
Thank you @strideynet 
This is my first and single node

Regarding Teleport proxy/auth that reside outside of Kubernetes, there are two configs (I will omit SSL params as redundant):

Nginx:
```
server {
  server_name teleport.<REDUCTED_DOMAIN>;
  location / {
    proxy_pass https://localhost:3080/;
  }
  listen 443 ssl; # managed by Certbot
  ...
}

server {
  server_name auth.teleport.<REDUCTED_DOMAIN>;
  location / {
    proxy_pass https://localhost:3025/;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }
  listen 443 ssl; # managed by Certbot
  ...
}
```

Teleport (log, diag are omitted):
```
version: v1
teleport:
  nodename: teleport.<REDUCTED_DOMAIN>
  ca_pin: ""

proxy_service:
  enabled: true
  proxy_protocol: on
  # listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  # tunnel_listen_addr: 0.0.0.0:3024
  # kube_listen_addr: 0.0.0.0:3026
  public_addr: teleport.<REDUCTED_DOMAIN>:443
  # https_keypairs: []
  #acme:
  #  enabled: true
  #  email: noreply@<REDUCTED_DOMAIN>

auth_service:
  enabled: true
  cluster_name: toolset
  listen_addr: 0.0.0.0:3025
  public_addr: auth.teleport.<REDUCTED_DOMAIN>:443
  license_file: /var/lib/teleport/license.pem
  proxy_listener_mode: separate
  authentication:
    type: saml

kubernetes_service:
  enabled: false
ssh_service:
  enabled: false
app_service:
  enabled: false
db_service:
  enabled: false
```


Regarding Slack - I have an enterprise support and Slack support as well. And created ticket there pointing to this issue.
