### ISSUE TITLE
Unable to add new application to existing teleport config

### ISSUE THREAD

**Issue by ghost** [gravitational/teleport#16488]
Expected behavior:
upon adding an app to the app_service section it should be able to connect with a previously existing teleport configuration.

Current behavior:
application fails to be added despite no obvious issues with the teleport config.
The baffling aspect is I have two machines with the same version, yet one fails while the other succeeded with no obvious configuration differences. of note ssh works just fine on both machines.

Bug details:
- Teleport version:  v10.2.1 git:v10.2.1-0-g2560469 go1.18.6
- Recreation steps:
- configure an ssh server using the automated script provided by the web ui
- adjust the config to like below to add new web applications
- witness it fail
- Debug logs
```
Sep 17 22:14:23 localhost.localdomain teleport[727956]: 2022-09-17T22:14:23-04:00 ERRO [PROC:1]    App failed to establish connection to cluster: "toast" can not join the cluster with role "App", token expired or not found, connection error: desc = "transport: authentication handshake failed: remote error: tls: internal error". pid:727956.1 service/connect.go:117
```
- config:
```yaml
version: v2
teleport:
  nodename: toast
  data_dir: /var/lib/teleport
  join_params:
    token_name: [redacted]
    method: token
  auth_servers:
  - tele.[redacted]:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:[redacted]
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: [redacted]
    users: "toast"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: filebrowser
    uri: http://127.0.0.1:8080
    public_addr: "fbnd.tele.[redacted]"
    insecure_skip_verify: false
    labels:
      service: "filebrowser"
  - name: proxymanager
    uri: http://127.0.0.1:8081
    public_addr: "pmnd.tele.[redacted]"
    insecure_skip_verify: false
    labels:
      service: "proxymanager"
  - name: navidrome
    uri: http://127.0.0.1:4533
    public_addr: "nd.tele.[redacted]"
    insecure_skip_verify: false
    labels:
      service: "navidrome"

```
