### ISSUE TITLE
Can't view active sessions? 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#16693]
Expected behavior:
I'm unable to join a shared session with Teleport 10.2.0. I can also only see active sessions for my username, `benarent`, but not for ubuntu.  Maybe limit of https://goteleport.com/docs/access-controls/guides/moderated-sessions/ 

My RBAC / Roles is below. 

Current behavior:
<img width="2098" alt="image" src="https://user-images.githubusercontent.com/559288/192047363-7223c504-d08d-4628-a1d8-bae04b647970.png">

```
kind: role
metadata:
  description: Access cluster resources
  name: access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - '{{internal.aws_role_arns}}'
    - arn:aws:iam::1234567890:role/ec2-read-only
    db_labels:
      '*': '*'
    db_names:
    - '*'
    - '{{internal.db_names}}'
    - SNOWFLAKE_SAMPLE_DATA
    - NON_SENSITIVE_DATA
    - SUPER_SECRET_DATA
    db_users:
    - '*'
    - '{{internal.db_users}}'
    - alice
    - intern
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    - system:masters
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    - ubuntu
    node_labels:
      '*': '*'
    request:
      search_as_roles:
      - access
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - Administrator
  deny:
    windows_desktop_labels:
      teleport.dev/computer_name: DC*
  options:
    cert_format: standard
    create_host_user: true
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    pin_source_ip: true
    port_forwarding: true
    record_session:
      desktop: true
    ssh_file_copy: true
version: v5
```
Bug details:
- Teleport version
- Recreation steps
- Debug logs
