### ISSUE TITLE
Resource Request: consider the rendered role template when determining which requests a user can approve

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#16914]
### What would you like Teleport to do?

When approving a resource request, only the name of the role being requested is considered to determine if the current user is allowed to approve. In a case where the same role can grant access to completely different sets of resources, this can result in a situation where an approver might be allowed to approve a request for a resource that they themselves don't have access to.

The approval system should be able to take into account a rendered version of the role when determining if the approver can indeed approve the request.

### What problem does this solve?

In a case where there is a large number of dynamic groups in an sso provider, the role templating system can greatly simplify the total number of roles that a teleport instance may need to have available. The resource request feature seemed like it could extend this functionality and allow a user with access to a particular resource to be able to grant someone else access to the same one.

For example, if a role grants access to nodes labeled `"team": "{external.teams}"`, a user that is a member of team alpha and team beta would see those corresponding resources.

When another user logs in with the same role, but with team membership of team delta, they'd like to be able to submit a resource request for a resource that belongs to team alpha.

Since role templating is being used, both users have the same role membership. The approval logic only pays attention to the role name, so that means that anyone with access to approve any request for that role could potentially approve resource requests for any and every team.

### If a workaround exists, please include it.

The only workaround is to abandon the use of role templating in favor of having one role per team. Since the environment in question can have teams added and removed very quickly, this becomes a moving target for some external process to create and destroy roles on the fly. This can further be complicated since a role that may no longer need to exist won't be removable until the last sso user that references it expires from the backend or logs in again and removes it that way.

**Comment by klizhentas** [comment]
This ticket should solve it: https://github.com/gravitational/teleport/issues/6557 make sure we document it and check that we actually support `where(access_request.system_annotations["..."], user.labels)`

**Comment by nklaassen** [comment]
I don't think `where` expressions with `system_annotations` can solve this, it seems like a more fundamental issue to our role templating and access request system.

I take this quote from the description to be the root of the issue:

> For example, if a role grants access to nodes labeled "team": "{external.teams}", a user that is a member of team alpha and team beta would see those corresponding resources.
>
> When another user logs in with the same role, but with team membership of team delta, they'd like to be able to submit a resource request for a resource that belongs to team alpha.

In this scenario all users have a single Teleport Role assigned to them, call it `team-access`, here's an example:

```yaml
kind: role
version: v6
metadata:
  name: team-access
spec:
  allow:
    node_labels:
      team: '{{external.teams}}'
    request:
      roles: ["what goes here?"]
      search_as_roles: ["what goes here?"]
```

How can we allow members of team `delta` to request access to nodes owned by team `alpha`, and only allow members of team `alpha` to review the request, without creating a Role per team? What role should they even request?
It seems what they want to request is an extra value in their `external.teams` trait, not an extra Role.

There is only one way I can think of to possibly make this work, with Resource Access Requests only, but it's not trivial. The `team-access` role would look like:

```yaml
kind: role
version: v6
metadata:
  name: team-access
spec:
  allow:
    node_labels:
      team: '{{external.teams}}'
    request:
      search_as_roles: [access]
    review:
      roles: [access]
      preview_as_roles: [access]
      where: 'contains_all(reviewer.traits["team"], merged_label_values(request.resources, "team"))'
```

This would allow all users to request access to any node, but the request could only be approved by users in the team that owns the node.
The hard part is providing `request.resources` (with all the resource labels) in the `where` expression. This needs to be efficient because the expression will run for every request when listing active requests, so we'd need to store the node labels in the Access Request object, which we have [previously discussed](https://github.com/gravitational/teleport/issues/13897#issuecomment-1167804902) and avoided.
