### ISSUE TITLE
Unable to connect K8s cluster

### ISSUE THREAD

**Issue by avi1512** [gravitational/teleport#17208]
### Discussed in https://github.com/gravitational/teleport/discussions/17204

<div type='discussions-op-text'>

<sup>Originally posted by **avi1512** October  9, 2022</sup>
I was testing my local lab environment with deploying teleport in k8s and to connect the cluster. Deployment and pod is running fine and also I can able to access the teleport web through LB (MetalLB) IP. with no issues. But when I tried to connect the K8s cluster it's having some issues. It's seems something missing or wrong. 

```
Teleport deployed through Helm charts with below values 

helm install teleport teleport/teleport-cluster -n teleport --set clusterName=teleport.local.com --set  kubeClusterName=k8s

Chart and App version: 10.3.1
```

Teleport.yaml

```
teleport:
  log:
    severity: INFO
    output: stderr
    format:
      output: text
      extra_fields: ["timestamp","level","component","caller"]
auth_service:
  enabled: true
  cluster_name: teleport.local.com
  authentication:
    type: "local"
    local_auth: true
    second_factor: "otp"
kubernetes_service:
  enabled: true
  listen_addr: 0.0.0.0:3027
  kube_cluster_name: k8s
proxy_service:
  public_addr: 'teleport.local.com:443'
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
  enabled: true
ssh_service:
  enabled: false

```

```
Errors: 

root@teleport-7bd849cfc5-f58f8:/# tsh login --proxy=192.168.1.180:443 --auth=local --user=admin teleport.local.com
ERROR: Cannot establish https connection to 192.168.1.180:
x509: certificate is valid for ::1, 127.0.0.1, ::1, not 192.168.1.180
try a different hostname for --proxy or specify --insecure flag if you know what you're doing.


root@teleport-7bd849cfc5-f58f8:/# tsh login --proxy=192.168.1.180:443 --auth=local --user=admin teleport.local.com --insecure
Enter password for Teleport user admin:
Enter your OTP token:
WARNING: You are using insecure connection to SSH proxy https://teleport.local.com:443
ERROR: Post "https://teleport.local.com:443/v1/webapi/ssh/certs": dial tcp: lookup teleport.local.com on 10.96.0.10:53: no such host



root@teleport-7bd849cfc5-f58f8:/# tsh login --proxy=192.168.1.180:443 --auth=local --user=admin teleport.local.com --insecure --debug
DEBU [CLIENT]    open /root/.tsh/192.168.1.180.yaml: no such file or directory client/api.go:1056
INFO [CLIENT]    no host login given. defaulting to root client/api.go:1439
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:4015
DEBU [CLIENT]    not using loopback pool for remote proxy addr: 192.168.1.180:443 client/api.go:3974
DEBU             Attempting GET 192.168.1.180:443/webapi/ping/local webclient/webclient.go:119
Enter password for Teleport user admin:
Enter your OTP token:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.local.com:443 client/api.go:3974
DEBU [CLIENT]    HTTPS client init(proxyAddr=teleport.local.com:443, insecure=true) client/weblogin.go:252
WARNING: You are using insecure connection to SSH proxy https://teleport.local.com:443

ERROR REPORT:
Original Error: *trace.ConnectionProblemError Post &#34;https://teleport.local.com:443/v1/webapi/ssh/certs&#34;: dial tcp: lookup teleport.local.com on 10.96.0.10:53: no such host
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:153 github.com/gravitational/teleport/lib/httplib.ConvertResponse
        /go/src/github.com/gravitational/teleport/lib/client/https_client.go:131 github.com/gravitational/teleport/lib/client.(*WebClient).PostJSON
        /go/src/github.com/gravitational/teleport/lib/client/weblogin.go:363 github.com/gravitational/teleport/lib/client.SSHAgentLogin
        /go/src/github.com/gravitational/teleport/lib/client/api.go:3449 github.com/gravitational/teleport/lib/client.(*TeleportClient).directLogin
        /go/src/github.com/gravitational/teleport/lib/client/api.go:3416 github.com/gravitational/teleport/lib/client.(*TeleportClient).localLogin
        /go/src/github.com/gravitational/teleport/lib/client/api.go:3320 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1446 main.onLogin
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:994 main.Run
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:444 main.main
        /opt/go/src/runtime/proc.go:250 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: Post &#34;https://teleport.local.com:443/v1/webapi/ssh/certs&#34;: dial tcp: lookup teleport.local.com on 10.96.0.10:53: no such host
```</div>
