### ISSUE TITLE
Have the ability to differentiate between IAM roles used for application access in same aws account

### ISSUE THREAD

**Issue by akgoteleport** [gravitational/teleport#17352]
What would you like Teleport to do?
Currently, using the aws_role_arns field we can list all IAM roles ARNs, this particular role will permit its user to assume while Launching the application.
However, if there are 2 AWS apps (dev, stage) , both supported by their own kube agent. These kube agents run in the same AWS account. The roles the agents are allowed to assume are all in one aws account, because of which there is no distinction between roles. Dev app can assume stage roles and vice versa.

Ideally stage agent should assume stage roles (and dev agents can assume dev roles)

What problem does this solve?
Distinction between roles that are mapped to respective apps.
If a workaround exists, please include it.
N/A

**Comment by webvictim** [comment]
This should be doable today by using different labels in each app agent configuration, then having separate roles - one for dev, one for stage. The web UI should only show the appropriate role for each label.

## `dev`

### App agent configuration

```yaml
app_service:
  - name: "aws-console-dev"
    description: "AWS Console (dev)"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
    labels:
      aws_account_id: "123456789012"
      agent_environment: dev
```

### Role
 
```yaml
kind: role
metadata:
  name: aws-dev-role
spec:
  allow:
    app_labels:
      agent_environment: dev
    aws_role_arns:
    - arn:aws:iam::123456789012:role/aws-dev-role
  deny: {}
  options:
    max_session_ttl: 8h0m0s
version: v3
```

## Stage

### App agent configuration

```yaml
app_service:
  - name: "aws-console-stage"
    description: "AWS Console (stage)"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
    labels:
      aws_account_id: "123456789012"
      agent_environment: stage
```

### Role

```yaml
kind: role
metadata:
  name: aws-stage-role
spec:
  allow:
    app_labels:
      agent_environment: stage
    aws_role_arns:
    - arn:aws:iam::165258854585:role/aws-stage-role
  deny: {}
  options:
    max_session_ttl: 8h0m0s
version: v3
```
 
If that's not the way this works, this is a bug.
