### ISSUE TITLE
EC2 auto-discovery issues

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#17359]
A few issues have come up while testing new EC2 auto-discovery.

### Default install script doesn't work on Ubuntu

It fails with `jq: not found` error which hints that `apt-get install teleport jq` doesn't run. The suspicion is that it doesn't run because `-y` flag is not used so none of the packages are installed because it runs in interactive mode and requires user confirmation?

Once fixed, let's verify on:

- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] Ubuntu 22.04

### Hard to debug SSM failures

When SSM command fails, you have to go to AWS console, find it and see its output. Command output should be available in the `GetCommandInvocationOutput`, let's make sure we include it in the audit event.

Check if the included command output is truncated in the AWS response and if not, let's make sure to truncate it to some reasonable size (e.g. 10kb) to avoid large events. Truncate from the head, not tail, so if the script fails the errors are included.

### Misleading exit code in SSM events

Exit code is currently `0` when status is `Failed` which is confusing.

```yaml
{
  "account_id": "165258854585",
  "cluster_name": "tele1c",
  "code": "TDS00W",
  "command_id": "f38d983b-5b61-46fa-a4a5-2f5f5b9153b1",
  "ei": 0,
  "event": "ssm.run",
  "exit_code": 0,
  "instance_id": "i-0bfde635b9df7f8d7",
  "region": "us-east-1",
  "status": "Failed",
  "time": "2022-10-12T22:03:41.688Z",
  "uid": "6f3ded82-5173-430b-be7a-2907287ac9bb"
}
```

### SSM events are displayed as "unknown" in audit log in web UI

We did add them to web assets:

https://github.com/gravitational/webapps/pull/1192
https://github.com/gravitational/webapps/pull/1223

But @stevenGravy says he's still seeing them as "unknown" in the web UI. Let's verify on our side on latest v10, v11 and master.
