### ISSUE TITLE
Add fields users and groups for each kube cluster when querying with `ListResources`

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#17382]
For the `kube` discovery flow, we need a way to receive current kube users and groups (static + dynamic).
By static I mean the users and groups defined in roles like this:

```yaml
kind: role
spec:
  allow:
    kubernetes_groups:
    # dynamic
    - '{{internal.kubernetes_groups}}'
    # static groups
    - kubeGroup1
    - kubeGroup2
    kubernetes_users:
    # dynamic
    - '{{internal.kubernetes_users}}'
    # static users
    - kubeUser1
    - kubeUser2
 ```

I think we can use the same technique used when [querying for list of nodes](https://github.com/gravitational/teleport/blob/9f9461d5f0186800c184345d9102457fc28d4f3a/lib/web/apiserver.go#L2093), where for each node, we [EnumerateServerLogins](https://github.com/gravitational/teleport/blob/9f9461d5f0186800c184345d9102457fc28d4f3a/lib/services/role.go#L950) and add it as a field called [SSHLogins](https://github.com/gravitational/teleport/blob/9f9461d5f0186800c184345d9102457fc28d4f3a/lib/web/ui/server.go#L52). 

Similar references to kube
- [kube api](https://github.com/gravitational/teleport/blob/9f9461d5f0186800c184345d9102457fc28d4f3a/lib/web/servers.go#L30) used to query for kube clusters (that should now also return the users and groups)
- where we should [enumerate](https://github.com/gravitational/teleport/blob/9f9461d5f0186800c184345d9102457fc28d4f3a/lib/web/ui/server.go#L122) for users and groups
