### ISSUE TITLE
trustedclusters documentation is spartan or invalid...

### ISSUE THREAD

**Issue by sean-** [gravitational/teleport#1744]
**What happened**:

The documentation in `docs/trustedclusters.md` gives invalid commands.  I'm trying to setup a trusted cluster config so that a behind-the-firewall server can establish a trust relationship with a server that's publicly available.  

**What you expected to happen**:

There should be a walk through guide for setting up a trustedcluster.  The lack of sample `yaml` files to configure either end and step-by-step instructions is problematic.  What directions are available, appear to be invalid.

**How to reproduce it (as minimally and precisely as possible)**:

```
# tctl create -f admin.yaml
creating resources of type "role" is not supported
```

```
kind: role
version: v2
metadata:
  name: admin
  namespace: default
spec:
  logins: [ root ]
  max_session_ttl: 90h0m0s
  namespaces: ['*']
  node_labels:
    '*': '*'
  resources:
    '*': [read, write]
```

**Environment**:

```
% tctl version
Teleport v2.5.0-rc.2
% teleport version
Teleport v2.5.0-rc.2
% tsh version
Teleport v2.5.0-rc.2
```

In other news, a FreeBSD port of `teleport` should materialize soonish: https://reviews.freebsd.org/D14576
