### ISSUE TITLE
Add interpolation function "join()"

### ISSUE THREAD

**Issue by albertrdixon** [gravitational/teleport#17440]
## Proposal

Would love to have access to an interpolation function `join(separator, list)`

## Use Case

Several items accessible in the `external` and `internal` property objects are lists

e.g: given an SSO response with `"groups": ["one", "two" ...]`, then `external.groups` is a list

There are times when we want to pass the list to something that is expecting a string, such as in the case of headers

```yaml
# Application Access
app_service:
  enabled: true
  apps:
    - name: internal-tool
      uri: http://tool.namespace:80
      rewrite:
        headers:
          - "authorization: bearer {{internal.jwt}}"
          - 'x-sso-groups: {{join(",", external.groups)}}'
```

### Current Workaround

For the above use case, I am solving this with a hacky use of `regexp.replace` like so

```yaml
# Application Access
app_service:
  enabled: true
  apps:
    - name: internal-tool
      uri: http://tool.namespace:80
      rewrite:
        headers:
          - "authorization: bearer {{internal.jwt}}"
          - 'x-sso-groups: {{regexp.replace(external.groups, "^(.*)$", "$1,")}}'
```
