### ISSUE TITLE
Unable to enable/disable a Trusted Cluster

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1751]
**Problem**

If you attempt to disable a Trusted Cluster after creating it, it can never be enabled again.

**Reproduction**

First create a Trusted Cluster relationship:

```yaml
kind: trusted_cluster
version: v1
metadata:
   name: "example.com"
spec:
   enabled: true
   token: "bar"
   tunnel_addr: 127.0.0.1:3024
   web_proxy_addr: 127.0.0.1:3080
```

then disable it:

```yaml
kind: trusted_cluster
version: v1
metadata:
   name: "example.com"
spec:
   enabled: false
   token: "bar"
   tunnel_addr: 127.0.0.1:3024
   web_proxy_addr: 127.0.0.1:3080
```

and re-enable it:

```yaml
kind: trusted_cluster
version: v1
metadata:
   name: "example.com"
spec:
   enabled: true
   token: "bar"
   tunnel_addr: 127.0.0.1:3024
   web_proxy_addr: 127.0.0.1:3080
```

The reverse tunnel is not re-established and this is the last line you see in the logs of the Trusted Cluster.

```
DEBU [TRUSTED CLUSTER] Enabling existing Trusted Cluster relationship. auth/trustedcluster.go:59
```
