### ISSUE TITLE
Logs littered with User Message: failed to peek connection: tread tcp i/o timeout" multiplexer/multiplexer.go:225

### ISSUE THREAD

**Issue by tonedefdev** [gravitational/teleport#17538]
Expected behavior:
I saw an old thread that said this can be the result of a loadbalancer sending health probes and the multiplexer not knowing how to handle the traffic, but this should really be resolved as it clutters output of logs, especially in a k8s cluster where Teleport is going to be behind a Service. Is there a way to fix this?

Current behavior:
{"caller":"multiplexer/multiplexer.go:225","component":"mx:proxy:web:2","level":"warning","message":"\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 10.115.58.130:3080-\u0026gt;10.115.58.33:47626: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:399 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:260 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:222 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 10.115.58.130:3080-\u0026gt;10.115.58.33:47626: i/o timeout","timestamp":"2022-10-18T16:51:08Z"}

Config:
```yaml
version: v2
teleport:
  log:
    output: stderr
    severity: INFO
    format:
      output: json
auth_service:   
  enabled: yes
  cluster_name: <REDACTED>
  tokens:                                 
  # These commands will generate random 32-chacter alphanumeric strings to use as join tokens
  - "proxy,node:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"                              
  - "trusted_cluster:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
  proxy_listener_mode: multiplex                                    
proxy_service:                  
  enabled: yes
  web_listen_addr: 0.0.0.0:3080
  public_addr: <REDACTED>:443
  https_keypairs:                            
  - key_file: /etc/teleport-tls/tls.key
    cert_file: /etc/teleport-tls/tls.crt
ssh_service:                            
  enabled: no
app_service: 
  enabled: no
db_service:  
  enabled: no
windows_desktop_service:
  enabled: no 
```

Bug details:
- Teleport version
   10.3.2
