### ISSUE TITLE
Native AWS backend for the audit log

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1755]
## Proposal

* Lets use DynamoDB for audit log
* S3 for session replay

## Config

```
teleport:
  storage:
    type: dynamodb
    region: eu-west-1
    table_name: tablename
    audit_table_name: tablename.audit # if missing - use filesystem
    audit_sessions_uri: s3://<bucket>  # if missing - use filesystem
    access_key: <key>
    secret_key: <key>
```

**Comment by klizhentas** [comment]
@kontsevoy it turned out to be a big changeset, I'm thinking of moving to 2.6.0 instead

**Comment by klizhentas** [comment]
Here are working combinations for documentation:

**Upload from Nodes and proxies to NFS directly**

```yaml
# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  storage:
      audit_sessions_uri: file:///tmp
```

**Upload to records S3 and events in Dynamo**

```yaml
# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  storage:
      type: dynamodb
      table_name: test_grv8
      region: us-west-1
      audit_table_name: test_grv8_events
      audit_sessions_uri: s3://testgrv8records
```

This configuration wont't be accepted as we require external uploader when using external dynamo db event storage (just simplifies our internal design)

**NOT SUPPORTED**
```yaml
# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  storage:
      type: dynamodb
      table_name: test_grv8
      region: us-west-1
      audit_table_name: test_grv8_events
      # missing audit_sesions_uri
```
