### ISSUE TITLE
Manual Desktop Service Creation

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#17568]
Customer is running AD. Likes using AD for authentication but not inventory. Customer is willing to call Teleport API and create `types.WindowsDesktopService` themselves.

Customer wants to do this because existing regexp based labeling on hostname does not meet their needs. They would like more control of labels (based off own internal criteria).

Investigate if this work today and/or what else needs to be done to support this use case.

**Comment by ibeckermayer** [comment]
Confirmed that this is possible.

Beyond the scope of this issue, but to test this I updated tctl to allow for it. So if the customer doesn't want to build their own client, we can trivially add tctl support for `tctl create -f desktop.yaml`: 72c392b8d03d3d6950c48e63bf641c38fca42300

Desktop resources look like the following:

```yaml
kind: windows_desktops
version: v3
metadata:
  labels:
    testing: manually
    another: label
  name: manual-test-name
spec:
  addr: ec2-54-162-177-255.compute-1.amazonaws.com:3389
  host_id: "must not be empty if using tctl changes"
```
