### ISSUE TITLE
documentation update for tsh 

### ISSUE THREAD

**Issue by hdep** [gravitational/teleport#1757]
Hello,

On my setup  I start the proxy with this config : 

```
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  tunnel_listen_addr: 0.0.0.0:3024
```

I added a node without issue : 

./teleport start --roles=node --token=cluster-join-token --auth-server=teleport

Now I want to connect from teleport server to my node : 

```
# ./tsh  ssh --proxy=localhost --user=hdep hdep@admin
dial tcp [::1]:3080: getsockopt: connection refused
```

tsh client try to contact proxy server on port 3080 (which is default). But in my setup I use a custom port for this => 443 

the help menu or the website https://gravitational.com/teleport/docs/user-manual/ doesn't talk about this : 

`# ./tsh  ssh --proxy=localhost:443 --user=hdep@admin`
