### ISSUE TITLE
`tctl desktops ls --format json|yaml` doesn't produce results

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#17611]
Expected behavior:

These format flags should produce a list of the given format

Current behavior:

The output is either
```
[
    {}
]
```

or

```
{}
```

even if there are desktops present in the database (those can be seen by using no format flag (aka `--format text`)

**Comment by vitorenesduarte** [comment]
This can be fixed e.g. with b50bdf2f0fd0f53b6f0b65cad345ddd4d151e70a, and then we'll get the following:

```yaml
desktop:
  kind: windows_desktop
  metadata:
    ...
  spec:
    ...
  version: v3
service:
  kind: windows_desktop_service
  metadata:
    ...
  spec:
    ...
  version: v3
```

```json
[
    {
        "desktop": {
            "kind": "windows_desktop",
            "version": "v3",
            "metadata": {
                ...
            },
            "spec": {
                ...
            }
        },
        "service": {
            "kind": "windows_desktop_service",
            "version": "v3",
            "metadata": {
                ...
            },
            "spec": {
                ...
            }
        }
    }
]
```

@ibeckermayer Is this what we want (i.e. to have both the `desktop` and the `service`)?
