### ISSUE TITLE
PAM

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1766]
Teleport should support a subset of Pluggable Authentication Modules (PAM). Specifically Teleport should be a PAM-aware application that supports `account` and `session` module types and call the following PAM functions:

* `int pam_acct_mgmt(pam_handle_t *pamh, int flags);`
* `int pam_open_session(pam_handle_t *pamh, int flags);`
* `int pam_close_session(pam_handle_t *pamh, int flags);`

In the initial release, PAM should be optional at both compile time and runtime. If PAM headers are not available at compile time, Teleport should still build, but without PAM support. If Teleport is started with PAM support but PAM was not compiled in, Teleport should refuse to start. If PAM is not available at runtime (libpam is not installed) and PAM is enabled, Teleport should also refuse to start.

By default PAM should use the same policy at `sshd` typically located in `/etc/pam.d/sshd`, if a different policy is not specified.

The following will be the default PAM configuration for Teleport:

```yaml
teleport:
   ssh_service:
      pam:
         enabled: no 
```

To enable PAM with the default `sshd` policy:

```yaml
teleport:
   ssh_service:
      pam:
         enabled: yes
```

To use a policy different than the default:

```yaml
teleport:
   ssh_service:
      pam:
         enabled: yes
         service_name: "teleport"
```
