### ISSUE TITLE
Terraform provider auth issues

### ISSUE THREAD

**Issue by tonedefdev** [gravitational/teleport#17862]
Receiving this error when trying to authenticate with base64 crt, key, and ca:
```txt
all connection methods failed
	profile could not be decoded: current-profile is not set, 
	failed to connect to addr teleport.<REDACTED>:443 as an auth server
context deadline exceeded: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for *.<REDACTED>, not teleport.cluster.local"
```

Provider config:
```hcl
provider "teleport" {
  addr           = "teleport.<REDACTED>:443"
  cert_base64    = data.azurerm_key_vault_secret.teleport_cert_base64.value
  key_base64     = data.azurerm_key_vault_secret.teleport_key_base64.value
  root_ca_base64 = data.azurerm_key_vault_secret.teleport_root_ca_base64.value
}
```

From the Terraform server I can successfully netcat and I can see this error in the logs when I attempt it, but even with `DEBUG` level it's extremely vague:

```json
{"caller":"auth/middleware.go:673","component":"auth","level":"debug","message":"ClientCertPool -\u003e cert(teleport.<REDACTED> issued by teleport.<REDACTED>:67345291990561472878403373772039113637)","timestamp":"2022-10-26T21:23:19Z"}
{"caller":"auth/middleware.go:673","component":"auth","level":"debug","message":"ClientCertPool -\u003e cert(teleport.<REDACTED> issued by teleport.<REDACTED>:184463535367464942678353486346162463513)","timestamp":"2022-10-26T21:23:19Z"}
{"caller":"alpnproxy/proxy.go:335","component":"alpn:proxy","error":"remote error: tls: bad certificate","level":"warning","message":"Failed to handle client connection.","timestamp":"2022-10-26T21:23:19Z"}
```

Is there a certain way I need to issue these certs to authenticate? I used `tsctl auth sign --format tls`, base64 encoded the output, then stored them in an Azure Key Vault to be retrieved using the AzureRM data provider for Key Vault. The documentation is extremely lacking on the Terraform provider, and I have spent hours trying to figure this out on my own to no avail.

Bug details:
- Teleport version
10.3.2

**Comment by tonedefdev** [comment]
I did some digging by enabling debug logs for the provider, and I'm showing this seems to be the problem:
```txt
2022-10-27T11:58:51.888-0700 [DEBUG] provider.terraform-provider-teleport:   "ServerName": "teleport.cluster.local",
```

Where is the provider getting this name or where can I find how to configure the `ServerName` on Teleport so it's validating against the correct domain name and not `teleport.cluster.local`?

**Comment by tonedefdev** [comment]
Here's my teleport.yaml file as well:
```yaml
data:
  teleport.yaml: |
    version: v2
    teleport:
      log:
        output: stderr
        severity: {{ .Values.teleport.logLevel }}
        format:
          output: json
    auth_service:
      enabled: "yes"
      cluster_name: teleport.{{ .Values.teleport.env }}.<REDACTED>
      tokens:
      # These commands will generate random 32-chacter alphanumeric strings to use as join tokens
      - "proxy,node:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
      - "trusted_cluster:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
      proxy_listener_mode: multiplex
      public_addr: teleport.{{ .Values.teleport.env }}.<REDACTED>:443
    proxy_service:
      enabled: "yes"
      web_listen_addr: 0.0.0.0:3080
      public_addr: teleport.{{ .Values.teleport.env }}.<REDACTED>:443
      https_keypairs:
      - key_file: /etc/teleport-tls/tls.key
        cert_file: /etc/teleport-tls/tls.crt
    ssh_service:
      enabled: "no"
    app_service:
      enabled: "no"
    db_service:
      enabled: "no"
    windows_desktop_service:
      enabled: "no"
```
