### ISSUE TITLE
[v10][v11] Cloud Docs: Desktop Access update (`proxy_server` vs `auth_servers`)

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#17952]
In Desktop Access this is new for v11 and breaks cloud currently: 

`v10`: https://goteleport.com/docs/ver/10.0/desktop-access/getting-started/?scope=enterprise#step-67-configure-teleport

```
teleport:
  auth_token: /path/to/token
  auth_servers:
  - teleport.example.com:443 # replace with your proxy address
windows_desktop_service:

```

`v11`: https://goteleport.com/docs/desktop-access/getting-started/?scope=cloud#step-67-configure-teleport

```
version: v3
teleport:
  auth_token: /path/to/token
  proxy_server: mytenant.teleport.sh # replace with your cloud tenant
windows_desktop_service:
```

Customer on cloud was following the guide and it doesn’t work (gets error message for the version mismatch).

We probably need to keep our cloud docs as the same version as what is on Cloud (currently `10.3.2`).
