### ISSUE TITLE
Trusted Cluster Enterprise Documentation

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1797]
Open source Teleport allows a simple mapping between the clusters. As covered in the open source documentation, once a Trusted Cluster relationship is established between "main" and "east". All users from "main" and can connect to "east" as long as node labels allow them access.

Teleport Enterprise allows more sophisticated access controls between clusters using role mappings. In essence when establishing trust an administrator can define the relationship between the remote role and the local role a user will assume.

_Note, if interoperability with OpenSSH is required, OpenSSH nodes be running OpenSSH 7.2 or higher. This is due to a [bug in older versions of OpenSSH](https://bugzilla.mindrot.org/show_bug.cgi?id=2387 ) where certificates issued with non-default certificate extensions were always rejected._ 

For example, suppose we once again have two clusters like in the open source example: "main" and "east". Let's also assume that in the main cluster, two roles exist: `admin` and `developer`. The `admin` role should have access to all servers within the "main" cluster as well as all servers within the "east" cluster. The `developer` role should only have access to servers within the "main" cluster.

To accomplish this, first create the two roles in the "main" cluster using `tctl create -f ...` on the following two resources:

```yaml
kind: "role"
version: "v3"
metadata:
  name: "admin"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  allow:
    logins: ["root"]
    node_labels:
      "*": "*"
    rules:
      - resources: ["*"]
        verbs: ["*"]
```
```yaml
kind: "role"
version: "v3"
metadata:
  name: "developer"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  allow:
    logins: ["root"]
    node_labels:
      "*": "*"
```

A few things to note about the above two roles. Both roles have full access to all labels. However, only the `admin` role has access to cluster level configuration. For example, the developer role can not create additional roles, can not view all recorded sessions, can no create new trusted cluster relationships.

Now whenever a user in the "main" cluster is issued a certificate, the roles the user has in the local cluster will be packed into the certificate. This will allow Teleport to map roles in "main" to roles in "east" as we will see later.

Next, create the following two roles in the "east" cluster.

```yaml
kind: "role"
version: "v3"
metadata:
  name: "admin"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  allow:
    logins: ["root"]
    node_labels:
      "*": "*"
    rules:
      - resources: ["*"]
        verbs: ["*"]
```
```yaml
kind: "role"
version: "v3"
metadata:
  name: "remote-admin"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  allow:
    logins: ["root"]
    node_labels:
      "*": "*"
```

Once again, note the differences between the `admin` and `remote-admin` roles. Here any user with the `admin` role will have full access to cluster with the ability to create or remove roles, trusted cluster relationships, etc. However, while a user with `remote-admin` role will be able to access all servers within the cluster, the user will not be able to perform administrative actions.

Now to establish the trust relationship between the two, on the "east" cluster, create the following resource using `tctl create -f ...`:

```yaml
kind: trusted_cluster
version: v2
metadata:
  name: "main"
spec:
  enabled: true
  role_map:
    - remote: "admin"
      local: [ "remote-admin" ]
  token: "secret-token-to-add-new-clusters"
  tunnel_addr: proxy.main:3024
  web_proxy_addr: proxy.main:3080
```

This will establish the trust relationship. Now users with roles `admin` in the "main" cluster will be able to connect to the "east" cluster as "remote-admin". Users with the role `developer` will not be able to connect to nodes within the "east" cluster. Remember earlier the role of the user in the "main" cluster is packed into the certificate. When connecting to the "east" cluster, this role is extracted and the `role_map` field is consulted to see what remote role maps to what local role.

Note, if you further wish to restrict access, the `remote-admin` role can be updated to allow access to a subset of roles.
