### ISSUE TITLE
Make it easier to ship app session chunk data to SIEM

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#17987]
What would you like Teleport to do?
Make it easier to send session_chunk_data for app access sessions to an SIEM. Currently, you have to `tsh play ` the chunk to convert it to JSON format to make it consumable for most SIEM. 

What problem does this solve?
Customers cannot tie session chunk data to app audit events using default Teleport tools. The way around this is to send both s3 app session events and app audit log events to an external SIEM. However, this workaround is made difficult by having to use tsh play to convert the session chunks. 
If a workaround exists, please include it.

**Comment by WilliamLoy** [comment]
related to #16411

**Comment by programmerq** [comment]
When using the teleport event handler plugin, it will unwrap the session chunks into json for you.

Following the [Export Events with Fluentd](https://goteleport.com/docs/management/export-audit-events/fluentd/) guide, the `./teleport-event-handler configure . teleport.example.com:443` step writes toml for the handler that includes this config snippet:

```toml
[forward.fluentd]
ca = "/Users/jeff/workspace/exporter-teleport.example.com/teleport-event-handler/ca.crt"
cert = "/Users/jeff/workspace/exporter-teleport.example.com/teleport-event-handler/client.crt"
key = "/Users/jeff/workspace/exporter-teleport.example.com/teleport-event-handler/client.key"
url = "https://localhost:8888/test.log"
session-url = "https://localhost:8888/session"
```

The `session-url` setting tells the plugin to not only send over audit logs, but also sessions themselves. It will append `.<sessionid>.log` to this URL. The fluentd.conf file has a corresponding source listener to expect those. [more info](https://github.com/gravitational/teleport-plugins/blob/8f662129cc0a1669f2ce95119787128b5b3d4a16/event-handler/README.md#configuration-options)

Whether it's an app access, kube, or ssh session, it will unfurl the session info in the same way that `tsh play -f json` does.

Timestamps on the events in the chunk will correspond with the correct time that the access was made.
