### ISSUE TITLE
List of values in `app_labels` using traits does not work

### ISSUE THREAD

**Issue by vivekjainx86** [gravitational/teleport#17994]
I have configured an elastic application in teleport with label `app_name: elastic-master`

I am trying to restrict access to application using `app_labels` with user traits as follows:
```
# app-access role
kind: role
metadata:
  name: app-access
spec:
  allow:
    app_labels:
      'app_name': ['{{internal.app_names}}']
...
```

```
kind: user
metadata:
  name: vivekjainx86
spec:
  roles:
    - app-access
  traits:
    app_names:
    - 'elastic-master'
```

Expected behavior:
With this access policy, I should be able to see elastic-master application using `tsh app ls`.

Current behavior:
I don't get access to elastic-master application.
<img width="522" alt="Screenshot 2022-11-01 at 5 41 52 PM" src="https://user-images.githubusercontent.com/38214848/199229801-c535debb-c58e-4168-8193-cdc6cb1f7548.png">

Please let me know if I am missing something or if there is any other way to achieve this.

Bug details:
- Teleport version: `10.2.6`
