### ISSUE TITLE
Add Kube Cluster name into `kubeconfig`'s context when generated by `tctl auth sign`

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#18080]
What would you like Teleport to do?
Generate kubeconfig with unique context names when using  `tctl auth sign --format kubernetes --kube-cluster=...`

```
contexts:
- context:
    cluster: {teleport-cluster-name}
    user: {teleport-cluster-name}-{kube-cluster-name}
  name: {teleport-cluster-name}-{kube-cluster-name}
```

What problem does this solve?
It will be possible to merge multiple clusters when calling `tctl auth sign` multiple times.
