### ISSUE TITLE
Configuration parsing is too pedantic

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1820]
It's very convenient to use the same configuration file template for `/etc/teleport.yaml` when deploying a Teleport cluster via Chef/Ansible/etc.

Then you can use Ansible variables to set `proxy/enabled=true` for proxies, but to `false` for everything else. However, Teleport will try to validate proxy settings even if proxy_service is turned off.

Consider this example:

```yaml
proxy_service:
  enabled: false
  https_key_file: /etc/letsencrypt/live/example.com/privkey.pem
  https_cert_file: /etc/letsencrypt/live/example.com/fullchain.pem
```

## Problem

`teleport start` fails with:

```
https key does not exist: /etc/letsencrypt/live/sf.gravitational.io/privkey.pem
```

## Proposal

* Do not validate proxy settings if `enabled=false` 
* Review other config options to see if it would make sense for some settings as well

Lets be conservative though...
