### ISSUE TITLE
trusted cluster error : access denied: the cluster token has been rejected

### ISSUE THREAD

**Issue by samouds** [gravitational/teleport#1827]
Hello,

I'm trying to connect an RPi that is behind a firewall to my teleport server, so I tried to add it as a cluster node but get this error : 

```
DEBU [AUTH]      Sending validate request; token=cluster_token, CAs=[CA(name=dev-002, type=host)] auth/trustedcluster.go:222
ERRO [AUTH]      access denied: the cluster token has been rejected auth/trustedcluster.go:227
```

I'm running 2.5.3 version and here are my config :  

**main cluster : auth conf**
```
ssh_service:
  enabled: no
auth_service:
  enabled: yes
  cluster_name: "teleport.example.com"
  tokens:
    - "node,proxy:auth_token"
    - trusted_cluster:cluster_token
proxy_service:
  enabled: no
```

**main cluster : proxy conf**
```
teleport:
    nodename: teleport.example.com
auth_service:
    enabled: no
ssh_service:
    enabled: yes
proxy_service:
    enabled: yes
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3024
    web_listen_addr: 0.0.0.0:3080
    public_addr: teleport.example.com
```

On my main servers I run two commands : 
```
[auth server]: teleport start --nodename=teleport.example.com --roles=auth --token=auth_token -c /etc/teleport/teleport.yaml --insecure
[proxy server]: teleport start --nodename=teleport.example.com --roles=proxy --auth-server=auth --token=auth_token -c /etc/teleport/teleport.yaml --insecure --insecure-no-tls
```
everythings work fine. and I can access to any node that I add and don't is behind a firewall.
PS. the proxy run behind a traefik reverse proxy who take care of the ssl certificates and it's accessible at https://teleport.example.com

**Rpi cluster conf : cluster.yaml**
```
kind: trusted_cluster
version: v2
metadata:
  name: teleport.example.com
spec:
  enabled: true
  token: cluster_token
  tunnel_addr: teleport.example.com:3024
  web_proxy_addr: teleport.example.com
```

On my Rpi I run two commands (hostname: dev-002) : 
```
teleport start -d
tctl create cluster.yaml
```

I get this error : 
```
DEBU [AUTH]      Sending validate request; token=cluster_token, CAs=[CA(name=dev-002, type=host)] auth/trustedcluster.go:222
ERRO [AUTH]      access denied: the cluster token has been rejected auth/trustedcluster.go:227
```
