### ISSUE TITLE
Improve insecure symlinks error messaging in `tbot`

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#18305]
What would you like Teleport to do?

The error message for secure symlink failure should be amended to make it more clear which directory failed and which config file parameters are needed to enable insecure symlinks mode.

An entry on the [troubleshooting guide](https://goteleport.com/docs/machine-id/troubleshooting/) might also be worthwhile.

Potential alternatives / additional improvements:
 * Make secure symlinks a global flag
 * Detect symlink support in `tbot configure` and add the flags automatically (presumably with a warning)

What problem does this solve?

On systems where secure symlinks mode isn't supported, users are instructed to disable secure symlinks mode:

```
ERROR: could not read artifact "key-cert.pub" from destination directory /var/lib/teleport/bot
openSecure("/var/lib/teleport/bot/key-cert.pub") failed due to missing syscall; `symlinks: insecure` may be required for this system
```

This incorrectly refers to `/var/lib/teleport/bot` as a destination directory rather than a storage directory, but would still be confusing even if technically correct, especially if the user has already enabled insecure symlinks on one or more of their destination directories.

If a workaround exists, please include it.

Enable secure symlinks for all destinations and the storage directory:

```yaml
storage:
    directory:
        path: /var/lib/teleport/bot
        symlinks: insecure

destinations:
    - directory:
          path: /opt/machine-id
          symlinks: insecure
```
