### ISSUE TITLE
Where Condition for Roles

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#18390]
**What would you like Teleport to do?**

Limit what roles a role has permissions for. 

e.g.:

```
rules:
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
      where: contains(resource.metadata.name, "access" | "editor") 

```
**What problem does this solve?**

Some users need to edit roles, but they should not be able to edit everyone's roles. e.g. The devops manager needs to edit the roles of the devops team, but they should not be able to edit the roles of the security team. 

**If a workaround exists, please include it.**
n/a
