### ISSUE TITLE
add proxy protocol to helm chart

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#18457]
### What would you like Teleport to do?

The teleport.yaml template in the teleport-cluster helm chart doesn't currently have a way to enable the proxy protocol setting. Both the auth_service and proxy_service have this setting, and they should be controllable independently.

It would be ideal to also have the various chart modes set the appropriate load balancer annotation if proxy_protocol is enabled for the proxy_service.

```yaml
auth_service:
    proxy_protocol: on
proxy_service:
    proxy_protocol: on
```

```yaml
annotations:
    service:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

### What problem does this solve?

In order for the pin_source_ip option to be usable in a typical cluster, the proxy protocol option will need to be enabled in teleport.yaml and a corresponding load balancer annotation is needed.

### If a workaround exists, please include it.

custom chart mode instead of one of the other modes.
