### ISSUE TITLE
RBAC in mixed OpenSSH and Teleport environments

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1850]
Access control restrictions in pure OpenSSH can be done by restricting the list of allowed logins (principals in OpenSSH terminology). Teleport nodes also allow restricting logins, but also support restrictions on labels and roles.

For example, suppose you are using the Teleport Recording Proxy and running Teleport Auth and Proxy servers but all other nodes within your infrastructure use OpenSSH. If you wish to restrict SSH access to the Auth and Proxy servers to only admins while everyone has full access to OpenSSH servers, you can do that with the example below.

First, make sure that the Auth and Proxy roles have a label that can be filtered on in the role. In the below snippet from `teleport.yaml`, the label `role: teleport` will be used but any key/value pair can be used.

```yaml
ssh_service:
  enabled: yes

  listen_addr: 0.0.0.0:3022

  labels:
    role: teleport
```

Make sure the admin role has access to all nodes, this can be done using the `"*": "*"` identifier. Also note that admins can log in as the login that comes from the identity provider `{{external.logins}}` as well as `root`.

```yaml
kind: "role"
version: "v3"
metadata:
  name: "admin"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  allow:
    logins: ["{{external.logins}}", root]
    node_labels:
      "*": "*"
    rules:
      - resources: ["*"]
        verbs: ["*"]
```

Next create a role that non-admins will assume, in this case we'll call it `dev`. Note the deny rule, this means users with this role will be denied access to any node with the label `role: teleport` which earlier we marked Auth and Proxy servers with.

In addition note that users will only be able to login to nodes with the login that came from their identity provider. If for example the user should also be able to log in as root as well, update logins to `logins: ["{{external.logins}}, root"]`.

```yaml
kind: "role"
version: "v3"
metadata:
  name: "dev"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  deny:
    node_labels:
      "role": "teleport"
  allow:
    logins: ["{{external.logins}}"]
    node_labels:
      "*": "*"
```

Lastly make sure that OpenSSH is configured to allow the user to login.
