### ISSUE TITLE
Allow and Deny Rules

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1853]
Teleport supports `allow` and `deny` rules within a role. When checking access to a server, Teleport loops over all roles twice: first checking deny rules then allow rules.

1. The first time it checks deny rules. If `login` *or* `label` match, access is immediately denied. This means `login` and `label` are evaluated as logical OR condition for deny rules.

2. The second time Teleport checks allow rules. If any `login` *and* `label` match, access is granted. If no `login` or `label` matched, access is denied. This means `login` and `label` are evaluated as logical AND conditions for allow rules.

Here are a few examples.

```yaml
kind: "role"
version: "v3"
metadata:
  name: "dev"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  deny:
    node_labels:
      "role": "database"
  allow:
    logins: [root]
    node_labels:
      "*": "*"```
```

This role would allow the user to log in as root to any nodes other than the ones with label `role: database`.

----

```yaml
kind: "role"
version: "v3"
metadata:
  name: "dev"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  deny:
   logins: [root]
    node_labels:
      "role": "database"
  allow:
    logins: [foo]
    node_labels:
      "*": "*"```
```

This role would deny access to login to a server if the user tried to log in as root or to a node with label `role: database`. Access would be granted to any other server when attempting to log in as `foo`.

----

```yaml
kind: "role"
version: "v3"
metadata:
  name: "dev"
spec:
  options:
    max_session_ttl: "8h0m0s"
    forward_agent: true
    port_forwarding: true
  allow:
    logins: [foo]
    node_labels:
      "role": "database"
```
In this example, the user would only be allowed access when connecting to a server with login foo and if the node has `role: database`.
