### ISSUE TITLE
SAML connector roles validation breaks templating

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#18593]
In https://github.com/gravitational/teleport/pull/16565 we added extra validation when creating SAML connectors to make sure that role names specified in `attributes_to_roles` are actually existing Teleport roles.

This change breaks a legitimate scenario where a role name is actually a templating variable and not an actual valid role name:

```yaml
  attributes_to_roles:
    - name: groups
      roles:
        - ${service}
      value: ^okta-?P<service>.*)$
```

To fix this, let's not remove the roles validation completely but rather skip over role names which we can tell are using variable substitution syntax: `${...}`.

This should be backported to all active releases where https://github.com/gravitational/teleport/pull/16565 was merged.
