### ISSUE TITLE
PAM integration docs update

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1861]
Config snippet:
```
teleport:
   ssh_service:
      pam:
         enabled: yes
         # 
         service_name: "teleport"
```

See more at #1766
