### ISSUE TITLE
Implement agentless OpenSSH servers inventory

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#18627]
Allow adding OpenSSH nodes to Teleport as the `node` resource. As a result of this task, a user should be able to:

* Should be able to create a server resource using API / tctl create command.
* Registered server should be visible in web UI, tsh ls, etc.
* Connect to registered nodes

We should also make sure that:
* RBAC works:
  * Currently, RBAC is done by Teleport node (which we don’t have in this scenario), which only works in the proxy recording mode.
* Session recording works
  * Currently probably only work in proxy recording mode.

Example resource file:
```yaml
kind: node
metadata:
  name: ssh.example.com
  labels:
    banned: "yes"
spec:
  addr: ssh.example.com:22
  hostname: ssh.example.com
version: v5
```

Part of https://github.com/gravitational/teleport/issues/17865
