### ISSUE TITLE
Trusted cluster web UI error

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1868]
# Problem 1

* Open "Trusted Clusters"
* Paste the cluster definition YAML from below.
* Observe _"json: cannot unmarshal array into Go value of type map[string]interface {}"_ error. It must be translated into something a user can understand. If we cannot say which line contains an error, at least say _"Cluster definition contains errors"_

```yaml
kind: trusted_cluster
version: v2
spec:
  # this field allows to create tunnels that are disabled, but can be enabled later.
  # this is the only field that can be changed later.
  enabled: true
  token: dogs-are-great
  # the address in 'host:port' form of the reverse tunnel listening port on the
  # "master" proxy server:
  tunnel_addr: t1-master:3024
  # the address in 'host:port' form of the web listening port on the
  # "master" proxy server:
  web_proxy_addr: t1-master:3080
  role_map:
  - local: [admin]
    remote: admin
```

**NOTE** I verified that spaces are correct. And the value you see here is copy/pasted with great care :) I can even attach the YAML file to this ticket:

http://s3.gravitational.io/ev/cluster.yaml

Turns out, I had to add this section for this to work:

```
metadata:
  # the name of a trusted cluster 
  name: hello
```

# Problem 2

[EDIT] Ignore "problem 2", it happens for all `tsh` and `tctl` errors. Created a separate issue for it: #1889

Try to create a cluster using this definition (I used tctl):

```
kind: trusted_cluster
version: v2
metadata:
  # the name of a trusted cluster 
  name: hello
spec:
  # this field allows to create tunnels that are disabled, but can be enabled later.
  # this is the only field that can be changed later.
  enabled: true
  token: dogs-are-great
  # the address in 'host:port' form of the reverse tunnel listening port on the
  # "master" proxy server:
  tunnel_addr: t1-master:3024
  # the address in 'host:port' form of the web listening port on the
  # "master" proxy server:
  web_proxy_addr: t1-master:3080
```

You will get a duplicated error message:

_"missing 'role_map' parameter: missing 'role_map' parameter"_
