### ISSUE TITLE
Allow for fine-grained RBAC on locking

### ISSUE THREAD

**Issue by thg-jonnield** [gravitational/teleport#18741]
Background:

The reason for attempting this was to allow revoking access requests as described [here](https://github.com/gravitational/teleport/issues/10650#issuecomment-1110015136) without requiring some level of admin privileges.

Expected behavior:

When a user has privileges to create locks I would expect the ability to be limited to only the resources the user has access to.

Current behavior:

A user with only the below role assigned to them can lock user accounts, assuming they know the username, preventing logins. I assume they can lock other resources too, but I've only tested with user accounts.

<details>
<summary>locks role</summary>

```yaml
---
kind: role
metadata:
  name: allow_manage_locks
spec:
  allow:
    rules:
    - resources:
      - lock
      verbs:
      - create
      - delete
      - list
      - read
      - update
  deny: {}
```

</details>

Bug details:
- Teleport version
  - Teleport Cloud 10.3.8 
- Recreation steps
  - Create a user with the above role assigned. 
  - run `tctl lock --user '<username>'`
