### ISSUE TITLE
Provide a way to disable the kubernetes_service in the teleport-cluster Helm chart

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#18774]
What would you like Teleport to do?
Disable the ssh and kubernetes services. They are activated by default and the chart values don't offer a way to disable them.

What problem does this solve?
higher security

If a workaround exists, please include it.
Using the "custom" way of deployment could solve it, but that's unwanted in my case.

**Comment by stevenGravy** [comment]
which helm chart @aardbol ?  teleport-cluster or teleport-kube-agent?  `ssh` should be off for both.  How are you seeing `ssh` enabled other then custom?

**Comment by aardbol** [comment]
Good point; the cluster chart. I'm sorry, I didn't look properly, only the k8s service is also active, so not `ssh`:

configmap:
```
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:443
      kube_cluster_name: t.domain.com
```

**Comment by rkusler-intermedia** [comment]
I too would like to ability to disable the kubernetes_service in some cases

https://github.com/gravitational/teleport/pull/19334

**Comment by webvictim** [comment]
This should be resolved in v12 due to #18857

**Comment by hugoShaka** [comment]
This can be done since v12 with a config override:

```yaml
auth:
  teleport_config:
    kubernetes_service:
      enabled: false
```

It's not perfect, I'd like to have the service running in a separate pod but this solves the issue described here.
