### ISSUE TITLE
bash not found on tsh ssh

### ISSUE THREAD

**Issue by jolentes** [gravitational/teleport#1884]
When I try to `tsh ssh` into a single node cluster running on UCS 4.3 I get an error "Original Error: *trace.NotFoundError fork/exec /bin/bash: no such file or directory"

I did the following for setup:

- download most recent teleport release
- install teleport on server and client
- `teleport configure >/etc/teleport.yaml`
- adapt configuration (see below)
  - IP addresses (otherwise it bound to IPv6 addresses only)
  - paths of hostname and uname
  - generated token
  - set webserver certificates
- start teleport
- create a user with `tctl users add johndoe`
- register on web console as johndoe with OTP
- run on client "tsh login --proxy=myhostname.something.local --insecure" (insecure because of some certificate issue that I still need to fix"
- run on client "tsh ssh --proxy=myhostname.something.local --insecure johndoe@myhostname

Got error message "A fatal error occurred: ssh: could not start shell". Same error via web portal.

**Configuration File**
```
#
# Sample Teleport configuration file.
#
teleport:
  nodename: myhostname
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: some-generated-token
  auth_servers:
  - 10.1.1.1:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: DEBUG
auth_service:
  enabled: "yes"
  cluster_name: "local"
  listen_addr: 10.1.1.1:3025
  tokens:
  - proxy,node:some-generated-token
  session_recording: ""
ssh_service:
  enabled: "yes"
  listen_addr: 10.1.1.1:3022
  labels:
    db_role: master
    db_type: postgres
  commands:
  - name: hostname
    command: [/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/bin/uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 10.1.1.1:3023
  web_listen_addr: 10.1.1.1:3080
  public_addr: myhostname.something.local:3080
  tunnel_listen_addr: 10.1.1.1:3024
  https_key_file: /etc/univention/ssl/myhostname.something.local/private.key
  https_cert_file: /etc/univention/ssl/myhostname.something.local/cert.pem
```

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.5.6 git:v2.5.6-0-g81d77d2
- Tsh version (use `tsh version`): Teleport v2.5.6 git:v2.5.6-0-g81d77d2
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
I am running Univention Corporate Server 4.3 (www.univention.de), which is a Debian distribution.
