### ISSUE TITLE
Can't access WebUI in High Availability cluster

### ISSUE THREAD

**Issue by Jengah** [gravitational/teleport#18885]
I'm working on getting a High Availability cluster working in ECS Fargate as opposed to EC2 instances with ASG as described in the ha cluster example: https://github.com/gravitational/teleport/tree/master/examples/aws/terraform/ha-autoscale-cluster

I am following the LetsEncrypt setup, using 2 NLBs (one internal, and one external) for proxy and auth respectively. I have a bespoke docker image that pulls in public.ecr.aws/gravitational/teleport:11.1.0 and simply writes configuration files to `/etc/teleport.yaml` and starts up teleport with `teleport start`.

The logs show that the auth tasks are coming up as expected and the proxy nodes are joining the cluster successfully via token. I can see cerfticates being created and dynamo actions successfully happening on the auth tasks.  However, I cannot seem to get the WebUI to resolve via the Route53 address pointing to the proxy NLB.

The browser is returning a `ERR_SSL_PROTOCOL_ERROR` but I see no errors related to acme setup issues and the only messaging I get when I attempt to hit the WebUI is `WARN [SSH:PROXY] Error occurred in handshake for new SSH conn error:[ssh: overflow reading version string]`, which a cursor search of the issues in this PR relate to Layer 7 load balancing that is not relevant in this case 🤔.

Not sure where to keep digging on this as there aren't any SSL related errors in the debug logs. The only SSL related log I can find is on boot:
```
2022-11-29T14:21:50.008-07:00 | 2022-11-29T21:21:50Z [PROC:1] INFO Managing certs using ACME https://datatracker.ietf.org/doc/rfc8555/. pid:1.1 service/service.go:4144
-- | --
```

Expected behavior:
I can access the WebUI via Route53 address pointing to proxy NLB

Current behavior:
Can't access web UI and no relevant logs to help debug

Bug details:
- Teleport version: v11.1.0
- Recreation steps
- Debug logs
```
  | 2022-11-29T14:27:21.991-07:00 | 2022-11-29T21:27:21Z [SSH:PROXY] WARN Error occurred in handshake for new SSH conn error:[ssh: overflow reading version string] pid:1.1 remote_addr:10.3.107.101:24440 sshutils/server.go:459
-- | -- | --
  | 2022-11-29T14:27:30.735-07:00 | 2022-11-29T21:27:30Z [PROXY:1] DEBU List of known proxies updated: ["225d5068-2a91-43a0-a2a5-2fa326856909" "2ebd5920-88b6-4315-a5c7-c6c93b812a5d" "7472a8c3-ad12-4352-9397-5d90b2e798b2" "9a3491e0-5deb-4c2b-b233-e9a763840434"]. pid:1.1 services/watcher.go:455
  | 2022-11-29T14:29:51.339-07:00 | 2022-11-29T21:29:51Z [SSH:PROXY] WARN Error occurred in handshake for new SSH conn error:[ssh: overflow reading version string] pid:1.1 remote_addr:10.3.169.214:54544 sshutils/server.go:459
  | 2022-11-29T14:29:51.456-07:00 | 2022-11-29T21:29:51Z [SSH:PROXY] WARN Error occurred in handshake for new SSH conn error:[ssh: overflow reading version string] pid:1.1 remote_addr:10.3.169.214:25580 sshutils/server.go:459
  | 2022-11-29T14:30:31.447-07:00 | 2022-11-29T21:30:31Z [SSH:PROXY] WARN Error occurred in handshake for new SSH conn error:[ssh: overflow reading version string] pid:1.1 remote_addr:10.3.169.214:51754 sshutils/server.go:459
```

Proxy config:
```
version: v3
teleport:
  diag_addr: 0.0.0.0:3000
  auth_server: $AUTH_ADDRESS:3025
  auth_token: $AUTH_TOKEN
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3080
  web_listen_addr: 0.0.0.0:443
  public_addr: $PROXY_WEB_ADDRESS
  https_keypairs: []
  acme:
    enabled: yes
    email: baxter@homebot.ai
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
```

Auth config:
```
version: v3
teleport:
  diag_addr: 0.0.0.0:3000
  storage:
    region: $AWS_REGION
    type: dynamodb
    table_name: $MAIN_DYNAMODB_TABLE
    audit_events_uri: ["dynamodb://$EVENTS_DYNAMODB_TABLE", "stdout://"]
    audit_sessions_uri: s3://$S3_SESSIONS_BUCKET/records
    audit_retention_period: 365d
auth_service:
  enabled: "yes"
  public_addr: $AUTH_ADDRESS:3025
  cluster_name: $CLUSTER
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  tokens:
  - proxy:$AUTH_TOKEN
proxy_service:
  enabled: "no"
ssh_service:
  enabled: "no"
```

I'm using `envsubst` in my entrypoint script on the docker image to inject these env vars into the configs:
AUTH_ADDRESS is the load balancer DNS name for the internal auth NLB
AUTH_TOKEN is the token specified for proxy
CLUSTER is a cluster name
PROXY_WEB_ADDRESS is the route53 record suffixed with :443
All the AWS related vars point to existing cloud infra created for this purpose
