### ISSUE TITLE
Hide Access Request section from Teleport's Web UI

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#19054]
What would you like Teleport to do?
Add the functionality to Hide `Access Requests` section from the menu options on Web UI
Despite listing the resource `access_request` under the `deny` rule, the access request section is still displayed.

```yaml
kind: role
metadata:
  id: 1670345335157006566
  name: only-show-apps
spec:
  allow: {}
  deny:
    rules:
    - resources:
      - access_request
      verbs:
      - list
```

Similar to https://github.com/gravitational/teleport/discussions/11920

What problem does this solve?
Customer finds this a desirable option as they expect if service is not enabled then buttons should not be displayed in UI.
