### ISSUE TITLE
cannot unmarshal number into Go value of type webclient.PingResponse

### ISSUE THREAD

**Issue by parkerderek** [gravitational/teleport#19168]
Expected behavior:
Teleport starts successfully in pod and teleport.yml file is read. 

Current behavior:
When creating a teleport pod using a podman-compose file, receiving the following error: 

```text
2022-12-07T22:05:48Z INFO [PROC:1]    Node has obtained credentials to connect to the cluster. pid:2.1 service/connect.go:635
2022-12-07T22:05:49Z ERRO [PROC:1]    Failed to resolve tunnel address: json: cannot unmarshal number into Go value of type webclient.PingResponse pid:2.1 reversetunnel/transport.go:87
2022-12-07T22:05:49Z ERRO [PROC:1]    Node failed to establish connection to Teleport Proxy. We have tried the following endpoints: pid:2.1 service/connect.go:1106
```

Bug details:
Teleport version - Teleport v11.1.1 git:v11.1.1-0-gbf4e8ea go1.19.2

Recreation steps:
1. Create teleport.yml file 
2. Create teleport_compose.yml file
3. Run ``` podman-compose -f teleport_compose.yml up -d```

NOTE: The auth_service is commented out as this node will be joined to a cluster specified by auth_servers in teleport.yml.

teleport.yml
```yaml
version: v2
teleport:
  nodename: myhostname
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

  cache:
    enabled: yes

  advertise_ip: myhostnameip

  auth_servers:
    - myauthserver.com

#auth_service:
#  enabled: "yes"
#  listen_addr: 0.0.0.0:3025
#  license_file: /var/lib/teleport/license.pem
#  proxy_listener_mode: multiplex

ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s

#  listen_addr: 0.0.0.0:3022
#  public_addr: myhostname:443

proxy_service:
  enabled: "yes"
  https_keypairs:
- key_file: "/var/lib/teleport/data/mykeyfile.pem"
   cert_file: "/var/lib/teleport/data/mycertfile.key"
  acme: {}
  listen_addr: myhostname:3023
  tunnel_listen_addr: myhostname:3024
  web_listen_addr: myhostname:3080
  public_addr: myhostname:443
```

teleport_compose.yml
```yaml

version: "4.2"

services:
  teleport:
    image: "public.ecr.aws/gravitational/teleport:11.1.1"
    container_name: "teleport"
    hostname: "teleport"
    command:
      - "--insecure"
    ports:
      - "80:80"
      - "3080:3080"
      - "3024:3024"
      - "3023:3023"
      - "3025:3025"
      - "443:443"
      - "3000:3000"
    networks:
      - routable
    volumes:
      - "/root/teleport/config:/etc/teleport"
      - "/root/teleport/data:/var/lib/teleport"

networks:
  routable:
    external: true
```

- Debug logs

**Comment by zmb3** [comment]
`auth_service` is enabled by default, so if you want to run a standalone node the correct way to do this would be to explicitly disable it instead of commenting it out.

(The same is true for `proxy_service`)

```
auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
```
