### ISSUE TITLE
Auth preference from config with `message_of_the_day` gets `defaults` origin instead of `config-file`

### ISSUE THREAD

**Issue by vitorenesduarte** [gravitational/teleport#19272]
### Expected behavior:

A `cluster_auth_preference` created from a configuration that contains only `message_of_the_day` (as the one below) should have `config-file` origin.

```yaml
teleport:
  nodename: node.example.com

auth_service:
  enabled: yes
  cluster_name: "example.com"
  message_of_the_day: "welcome!"
```

### Current behavior:

A `cluster_auth_preference` created from a configuration that contains only `message_of_the_day` has `defaults` origin.

### Bug details:
- Teleport version: 11.1.2
- Recreation steps: See https://github.com/gravitational/teleport/pull/19106#issuecomment-1344293605

Fixing this may result in a breaking change as detailed in the comment above.
