### ISSUE TITLE
Idle timeout behavior.

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1935]
## Description

Many policies CJIS and PCI for example enforce 30 and 15 minutes idle connection termination as a requirement. Make sure that idle connection in teleport indeed terminates after 15 minutes of inactivity. 

We have set the timeout, but we need to make sure it actually works.

### Proposed solution

There is no single way that will work for everyone, after several conversations with customers here are the modes this ticket should enable:

* Terminate session after predefined max idle timeout has happened. Define idle timeout by setting period of inactivity (not client heartbeats)
* Do not terminate session after predefined max inactivity timeout has happened. This is required for some other important use cases who wish to issue very short lived certificate, but want to allow keeping session active.
* Force Terminate connection on the proxy when certificate has expired. This is required to implement temporary access pattern for some important use cases.
* Force terminate connection when local user has been deleted.
* Make the timeout duration configurable as well, as some customers indicated the desire to have this configurable.

**Comment by kontsevoy** [comment]
## Proposal

Lets add two settings to both `/etc/teleport.yaml` and the role definition:

```yaml
auth_service:
   # Maximum time a connection is allowed to remain idle, i.e. without any input from the client. 15m (default)
   disconnect_client_idle:  15m
   # When enabled, a connection will be terminated when the client certificate expires. OFF by default.
   disconnect_expired_cert: off
```

And in the role...

```yaml
kind: role
version: v3
metadata:
  name: intern
spec:
  options: 
     # these two settings override the global ones:
     disconnect_client_idle:  1m
     disconnect_expired_cert: on
```

**Comment by klizhentas** [comment]
what if we don't want to disconnect idle client behavior, should it be - `disconnect_client_idle:off`?

**Comment by klizhentas** [comment]
also, why not: `disconnect: {client_idle: 15m, expired_cert: off}`

**Comment by kontsevoy** [comment]
lets leave as-is as discussed.

**Comment by klizhentas** [comment]
See final result here:

Auth server now supports global
defaults for timeout behavior:
```
auth_service:
  # default value is 'never' - for backwards-compatibility reasons
  client_idle_timeout:  15m
  # default value is `no` for backwards compatibility reasons
  disconnect_expired_cert: no
```

New role options were introduced:

```
kind: role
version: v3
metadata:
  name: intern
  spec:
    options:
    # these two settings override the global ones:
    client_idle_timeout:  1m
    disconnect_expired_cert: yes
```

**Comment by klizhentas** [comment]
Global vs local options resolution:

Roles do not "relax" global default values when set. For example, in the following setup:

```yaml
auth_service:
   client_idle_timeout: 15m
```

and user's role:

```yaml
kind: role
version: v3
metadata:
  name: intern
  spec:
    options:
    client_idle_timeout:  20m
```

still, the most restrictive option will be used `15m`, so if administrator set global idle timeout of `15m` there is no way to override it in the system.

If there are two roles with two values available, the most restrictive option will be used as well, 
so if role A has `client_idle_timeout: 15m` and role `B` has `client_idle_timeout: 10m` the resulting value will be `10m`.

This means that default global values are permissive - for example default idle timeout is `never` in the cluster and `disconnect_expired_cert: no`.
