### ISSUE TITLE
tsh kube ls returns clusters that no longer exist

### ISSUE THREAD

**Issue by mdaniel** [gravitational/teleport#19357]
Expected behavior:

That teleport-agents which are no longer running will age out from teleport

Current behavior:

```console
$ tsh kube ls
Kube Cluster Name 
-----------------------------
md1206
$ tctl get kube_services --format=json | jq -r '.[].spec.kube_clusters[0].name' | sort | uniq | grep md
# nothing
```

and then, predictably, it doesn't really work
```console
$ tsh kube login md1206
Logged into kubernetes cluster "md1206". Try 'kubectl version' to test the connection.
$ kubectl get nodes
Error from server: Teleport proxy failed to connect to "kube" agent "remote.kube.proxy.teleport.cluster.local" over direct dial:

  dial tcp: address remote.kube.proxy.teleport.cluster.local: missing port in address
```

The cluster also appears on the website, but there's no obvious way of checking what it thinks is the status since "Connect" just emits generic instructions

Bug details:
- Teleport version:
```
$ tsh version
Teleport v11.1.2 git: go1.19.4
Proxy version: 11.1.2
```
(and I confirmed that "Proxy Version" squares up with the saas endpoint `$ curl -sf https://${SLUG}.teleport.sh/webapi/ping  | jq -r .server_version` = `11.1.2`)
- Recreation steps
- Debug logs

**Comment by tigrato** [comment]
@mdaniel this is the expected behavior.

Our heartbeat mechanism heartbeats the cluster each minute and once it stops, the resource is considered alive for ~10m. After that time, the cluster won't show anymore. This happens to all Teleport resources

If you want to remove it earlier, you can run  `tctl rm kube_server/<name>`  and temporarily you need to run also `tctl rm kube_service/<name>`

**Comment by mdaniel** [comment]
Sorry about that, my bug report failed to state that these phantom clusters (and it's multiple of them) have been there all week. The `expires:` field in the output of that command squares with my experience
```yaml
# tctl get kube_server/md1206
kind: kube_server
metadata:
  expires: "2022-12-08T16:28:44Z"
  name: md1206
spec:
  cluster:
    kind: kube_cluster
    metadata:
      labels:
        groupId: 00g1qn24oqlTjg0Ga0h8
      name: md1206
    spec:
      aws: {}
      azure: {}
      gcp: {}
    version: v3
  host_id: 1d5e34d1-1035-475d-8506-1224ff3da927
  hostname: remote.kube.proxy.teleport.cluster.local
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 10.2.2
version: v3
---
kind: kube_server
metadata:
  expires: "2022-12-08T16:29:29Z"
  name: md1206
spec:
  cluster:
    kind: kube_cluster
    metadata:
      labels:
        groupId: 00g1qn24oqlTjg0Ga0h8
      name: md1206
    spec:
      aws: {}
      azure: {}
      gcp: {}
    version: v3
  host_id: 47c1c46e-8885-4c64-98e0-8a6e6d9b57ff
  hostname: remote.kube.proxy.teleport.cluster.local
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 10.2.2
version: v3
```

I don't know how to readily prove to you that there are no teleport-agents running with that cluster name, but I'm willing to run whatever diagnostic commands you'd like

as for the `rm`, `tctl` disagrees
```console
$ tctl rm kube_server/md1206
ERROR: access denied to perform action "delete" on "kube_server"
$ tctl rm kube_service/md1206
ERROR: rpc error: code = PermissionDenied desc = access denied to perform action "delete" on "kube_service"
```

It's true that the `admin` role I have does not list `kube_server` in its `resources:` (partially because that's not in the "    # supported resources:" list of [the role reference](https://goteleport.com/docs/access-controls/reference/?scope=cloud#roles) although control-f on that page does in fact show `kube_service` which I don't have for the same reason); I'll try to PR that change in later today and try that again.

Although it is mysterious that I can `get` them, since my admin role doesn't include the resource at all
