### ISSUE TITLE
`certificate signed by unknown authority` after reconciling a dynamic RDS resource

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#19395]
## Expected behavior

Updating a dynamic `RDS` resource should not result in a loss of access to the database.

## Current behavior
Once the DB agent reconciliation ends, the DB becomes unavailable to everyone and returns the following error:

```
psql: error: connection to server at "localhost" (127.0.0.1), port 56481 failed: Database service cannot validate database's certificate: failed to connect to `...`: failed to write startup message (x509: certificate signed by unknown authority). Please verify if the correct CA bundle is used in the database config.
```

Fixing the problem requires restarting the DB agent.  The agent was running as a stateless pod and once restarted it downloads the CA bundle from AWS and becomes operational.

## Teleport version

`v10.3.2`

## Recreation steps

1. Create an RDS DB
2. Deploy a db agent with a dynamic db watcher
3. Create a dynamic db resource
4. Connect to the db with tsh db connect - works
5. `tctl get db/<db_name> > db.yaml`
6. Edit the file and add an extra label
7. Update the db resource: `tctl create -f  db.yaml`
8. Wait for reconciliation
9. `tsh db connect ... ` fails with: `certificate signed by an unknown authority`

<details>
<summary>db.yaml</summary>
```
kind: db
metadata:
  description: 
  labels:
    engine: postgres
    environment: prod
    teleport.dev/origin: dynamic
  name: testdb
spec:
  aws:
    rds:
      iam_auth: false
      instance_id: <instance>
    redshift: {}
    region: <region>
    secret_store: {}
  protocol: postgres
  tls:
    mode: 0
  uri: <uri>
version: v3
```

</details>
