### ISSUE TITLE
role template function should be able to change case

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#19554]
### What would you like Teleport to do?

When using the data sent over by an SSO IDP, sometimes there can be undesirable cases like upper case letters. Currently, there's no good way to force this external attribute to map to a lowercase version for consistency.

For example:

```
logins:
- "{{email.local(external.email)}}"
```

could map to `BRoss`, when it would be preferable for it to map to `bross` instead.

There should be something similar to the following:

```
logins:
- "{{tolower(email.local(external.email){}}"
```

### What problem does this solve?

It is common to use uniform cases for UNIX usernames, but the HR person doing data entry into the new hire database may think that mixed case looks better visually. Teleport should be able to force everything to lowercase in a role template if the teleport operator so chooses.

### If a workaround exists, please include it.

```
logins:
- {{regexp.replace("A", "a", regexp.replace("B", "b", ....., email.local(external.email))))))))))))))))))))))))))) }}
```

While I haven't tested this, The code indicates it can walk each template calculation up to a depth of 100. Doing 26 letters and the `email.local` calculation should be well within that limit.

**Comment by zmb3** [comment]
This is being addressed by login rules.

See https://github.com/gravitational/teleport.e/pull/651/files where we've added `upper`, `lower`, and `strings.replaceall`.

cc @nklaassen

**Comment by nklaassen** [comment]
This is now doable with login rules, the following example rule will convert the email to lowercase during login:
```yaml
kind: login_rule
version: v1
metadata:
  name: lowercase_email
spec:
  priority: 0

  # This example expression will return all input traits unmodified except for
  # the "email" trait which will be converted to lowercase
  traits_expression: |
    external.put("email", strings.lower(external.email))
```

Login rules are available in v11.3.0+ and draft docs are posted here: https://github.com/gravitational/teleport/pull/21195
