### ISSUE TITLE
EC2 Discovery Service does not work when using "wildcard" label matches

### ISSUE THREAD

**Issue by thameezb** [gravitational/teleport#19698]
Expected behavior:
SSM script should be attempted to run on all EC2 machines, irrespective of their tags when `tags` is set to `"*": "*"` as per documentation

Current behavior:
SSM script is not run on wildcard tags, changing this to a defined tag configures the discovery service to execute the SSM RunCommand against matching EC2 instances

Bug details:
- Teleport version: v11.1.2
- Recreation steps:
  * Create a Discovery Node as per docs
  * Configure service to use wildcard for tags ->
```
discovery_service:
  enabled: "yes"
  aws:
  - types: ["ec2"]
    regions: ["eu-central-1"]
    tags:
      "*": "*"
```
  * Restart Discovery service
  * Wait for scripts to run (they never do and nothing is noted even in debug logs
  * Stop Discovery service 
  * Update config to use a defined tag 
```
discovery_service:
  enabled: "yes"
  aws:
  - types: ["ec2"]
    regions: ["eu-central-1"]
    tags:
      "terraform": "true"
```
  * Restart Discovery service
  * Watch as SSM scripts run against EC2 instances, including the logging of results
