### ISSUE TITLE
Teleport HA cluster report 'proxy failed to connect to "node" agent over reverse tunnel'

### ISSUE THREAD

**Issue by get-set** [gravitational/teleport#19720]
I deployed a HA cluster with three nodes, and when I try to connect to server, I got error occasionally.

But if I change the three replicas to only one, this error stopped showing up. It seems the target server only establish reverse tunnel with only one cluster node through layer 4 proxy.

Is there a bug or something I've missed to configure for HA cluster regarding reverse tunnel? I haven't find anything about this in the documentation.

**Expected behavior:**

Connect to server and login SSH successfully.

**Current behavior:**

Try to login server through teleport repeatedly, Sometimes work as expected, sometimes report the following error (WebUI and `tsh ssh` command):

```
Teleport proxy failed to connect to "node" agent "@local-node" over reverse tunnel:

  no tunnel connection found: no node reverse tunnel for 65d8ad9e-9428-4db9-8688-1981265b8046.tele.jihulab.net found

This usually means that the agent is offline or has disconnected. Check the
agent logs and, if the issue persists, try restarting it or re-registering it
with the cluster.
```

**Bug details:**

- Teleport version: 11.1.4
- Recreation steps
  1. Deploy a HA teleport cluster (Proxy and Auth service) with more than one node.
      - I deployed 3 nodes
      - This issue happens no matter running [on VM](https://goteleport.com/docs/deploy-a-cluster/high-availability/) or [on K8S (deploy through Helm)](https://goteleport.com/docs/deploy-a-cluster/helm-deployments/custom/)
      - I enabled TLS routing by setting `proxy_listener_mode: multiplex`
      - I did not enable proxy peering (open source version)
      - I put a HAProxy (TCP mode) in front of cluster VMs, or use K8S service with type `LoadBalancer`
  2. Add a server from webUI, execute the given command `sudo bash -c "$(curl -fsSL https://tele.example.net/scripts/<join token>/install-node.sh)"`
  3. Connect to server from WebUI or via `tsh ssh <server>` command
      - Tried several times, sometimes can login but sometimes not.
  4. Change replica of K8S deployment to only `1`, and try to connect to server from WebUI or via `tsh ssh <server>` command repeatedly, no error.
- `teleport.yaml` for teleport cluster nodes:

```
apiVersion: v1
data:
  teleport.yaml: |-
    version: v3
    teleport:
      log:
        output: stderr
        severity: INFO
        format:
          output: text
          extra_fields: ["timestamp","level","component","caller"]
    auth_service:
      enabled: yes
      cluster_name: tele.example.net
      authentication:
        type: local
        second_factor: "off"
      proxy_listener_mode: multiplex
      client_idle_timeout: 4h
    proxy_service:
      enabled: yes
      public_addr: tele.example.net:443
      https_keypairs:
      - key_file: /etc/teleport-tls/tls.key
        cert_file: /etc/teleport-tls/tls.crt
    kubernetes_service:
      enabled: no
    ssh_service:
      enabled: no
```
