### ISSUE TITLE
[v.11.x] /docs/pages/machine-id/guides/github-actions.mdx

### ISSUE THREAD

**Issue by mnaser** [gravitational/teleport#19758]
## Applies To
Any clustered deployments that use `etcd` as a storage backend.

## Details
The documents show an expiry date of year 3000.  `etcd` doesn't like that since it has some 285 year lease maximum.  You end up with this error:

> ERROR: etcdserver: too large lease TTL

Setting it to 2030 works, and it's probably good enough. :)

**Comment by mnaser** [comment]
Also, saw the following:

> $ tctl bots add github-demo --roles=access --token=github-token –logins=username

The docs are incorrect here, it should be `--` and not an emdash.

**Comment by mnaser** [comment]
Another, the GitHub action seems to want a full version:

```
     - name: Fetch Teleport binaries
       uses: teleport-actions/setup@v1
       with:
         version: 11
```

This should be:

```
     - name: Fetch Teleport binaries
       uses: teleport-actions/setup@v1
       with:
         version: 11.1.4
```

or whatever version you're running :)
