### ISSUE TITLE
Using configuration file example provided for MongoDB Atlas connections leads to errors

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#19799]
## Applies To

Database Access with [MongoDB Atlas](https://goteleport.com/docs/database-access/guides/mongodb-atlas/)

## Details

Using the configuration file example provided leads to errors when starting the Teleport process:

![Screenshot 2023-01-03 at 18 07 53](https://user-images.githubusercontent.com/95687564/210416102-aad27e59-2eef-4da4-a9ef-2e32562e479a.png)

The configuration example should disable the `proxy_service`, `auth_service` and `ssh_service`: 

```
version: v3
teleport:
  auth_token: "/tmp/token"
  proxy_server: teleport.example.com:443
auth_service:
  enabled: "no"
proxy_service:
  enabled: "no"
ssh_service:
  enabled: "no"
db_service:
  enabled: "yes"
  databases:
  - name: "mongodb-atlas"
    protocol: "mongodb"
    uri: "mongodb+srv://cluster0.abcde.mongodb.net"
    ca_cert_file: "/path/to/letsencrypt/isrgrootx1.pem"
    static_labels:
      env: "dev"
```

## Related Issues

N/A
