### ISSUE TITLE
Cannot add a new auth/proxy server to my cluster

### ISSUE THREAD

**Issue by Ruchira-R** [gravitational/teleport#19949]
Expected behavior: Should connect to the cluster

Current behavior:  Proxy Failed to establish connection to cluster
Proxy failed to establish connection to cluster: connection error: desc = "transport: Error while dialing failed to dial: dial tcp lb-ip:3025: i/o timeout". pid:11409.1 service/connect.go:119

Bug details:
- Teleport version : Teleport v11.1.4 git:v11.1.4-0-ge4ac5f6 go1.19.4
- Recreation steps : Start a new auth and proxy server and try to connect a new node as auth and proxy server.
- Debug logs: 
 Proxy failed to establish connection to cluster: connection error: desc = "transport: Error while dialing failed to dial: dial tcp lb-ip:3025: i/o timeout". pid:11409.1 service/connect.go:119
2023-01-06T15:48:00Z ERRO [PROC:1]    Node failed to establish connection to Teleport Proxy. We have tried the following endpoints: pid:11409.1 service/connect.go:1106
2023-01-06T15:48:00Z ERRO [PROC:1]    - connecting to auth server directly: connection error: desc = "transport: Error while dialing failed to dial: dial tcp lb-ip:3025: i/o timeout" pid:11409.1 service/connect.go:1107
2023-01-06T15:48:00Z ERRO [PROC:1]    - connecting to auth server through tunnel: connection error: desc = "transport: Error while dialing failed to dial: context deadline exceeded" pid:11409.1 service/connect.go:1111
2023-01-06T15:48:00Z ERRO [PROC:1]    "Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tconnection error: desc = \"transport: Error while dialing failed to dial: dial tcp lb-ip:3025: i/o timeout\", connection error: desc = \"transport: Error while dialing failed to dial: context deadline exceeded\"." pid:11409.1 service/connect.go:119

Load Balancer : 
Listeners : 443 and 3025

Can connect to Web UI and register the nodes, cannot extend my env from a single auth/proxy node to a cluster.

Config File :
``` 
version: v2
teleport:
  auth_servers:
    - <cluster-name>:3025
  nodename: <nodename>
  log:
    output: stderr
    severity: INFO
  ca_pin: <ca_pin>
  join_params:
    token_name: <token>
    method: token
  storage:
    type: dynamodb
    region: <region>
    table_name: <tablename>
    audit_events_uri:  ['dynamodb://<tablename>', 'file:///var/lib/teleport/audit/events', 'stdout://']
    audit_sessions_uri: <s3_URL>
    audit_retention_period: 365d
proxy_service:
  enabled: true
  public_addr: <cluster_name>:443
  https_keypairs:
  - key_file: <pem file>
    cert_file: <pem file>
auth_service:
  enabled: true
  cluster_name: <cluster_name>
  license_file: <path to license file>
```

QUESTION : Should 3022 be a listener too?
The auth/proxy nodes are in different AZs.
