### ISSUE TITLE
Dynamically discover applications and databases running in a Kubernetes cluster

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#20036]
### What would you like Teleport to do?

A Teleport node running in a Kubernetes cluster should be able to automatically discover applications (and databases?) running in the cluster and expose them securely through app access. Teleport would act as an ingress-controller for admin UIs.

A user could expose rabbitmq's management interface with the following manifest:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-admin-management
spec:
  ingressClassName: teleport-application-access
  defaultBackend:
    service:
      name: rabbitmq-management
      port:
        number: 15672
```

### What problem does this solve?

As a developer deploying applications in a Kubernetes cluster, this allows me to quickly and securely expose my admin web UIs.

As a Teleport administrator, this allows me to delegate application declaration to my end users and not spend time adding their applications or developing a way to do it in an Infrastructure-as-Code fashion.

### If a workaround exists, please include it.

All workarounds imply the developers to ask the Teleport admins to add the application. Then, Teleport admins can declare the application using the following means:

- Manually edit teleport application access configuration to statically declare apps
- Manually create apps using `tctl` and configure teleport nodes to listen for dynamic resources
- Build an IaC pipeline to deploy apps using the API
