### ISSUE TITLE
Provide example of how to use Azure AD claims/traits in role definitions

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#20269]
## Applies To

[SSO Authentication with Azure Active Directory (AD)](https://goteleport.com/docs/access-controls/sso/azuread/)

## Details

The guide show typical claims in Azure AD:

![image](https://user-images.githubusercontent.com/95687564/212743469-f0171c76-ae30-482e-893f-7db94820d9a1.png)

And these will be mapped to `traits` on the user's profile in Teleport:

```
  traits:
    http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress:
    - john.doe@email.com
    http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname:
    - John
    http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name:
    - john.doe@email.com
    http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname:
    - Does
```

But the guide does not provide examples of the syntax to use to reference these claims in Teleport role definitions, e.g. to map to `logins`, for example:

```
logins:
  - "{{email.local(external["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"])}}"
```

The example shown in the [Create a new Teleport role](https://goteleport.com/docs/access-controls/sso/azuread/#create-a-new-teleport-role) section should be updated to include this:

```
kind: role
version: v5
metadata:
  name: dev
spec:
  options:
    max_session_ttl: 24h
  allow:
    logins: [ "{{external.username}}", "{{email.local(external["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"])}}", ubuntu ]
    node_labels:
      access: relaxed
```

## Related Issues

N/A
