### ISSUE TITLE
Errors in desktop access configuration scripts

### ISSUE THREAD

**Issue by mighty-services** [gravitational/teleport#20271]
Expected behavior:
the given teleport.yaml file should not throw any error when generated through the teleport script

Current behavior:
When I generate a teleport.yaml config according to the new [youtube-Guideline](https://www.youtube.com/watch?v=v36tlB8D5kk), it´s bringing up several error in the powershell file, because I have a separate CA-Authority and not one sitting on the Domain Controller. I fixed it with hrowing in some "invoke-command" Blocks to get the output working like expected, but the yaml file stil throws errors.

error 1 is:
` ERROR: failed parsing the config file: yaml: unmarshal errors:  line 44: field discovery not found in type config.LDAPConfig`

error 2 is:
` ERROR: failed parsing the config file: yaml: unmarshal errors:  line 46: field labels not found in type config.LDAPConfig`

this is my teleport.yaml file:
```
version: v3
teleport:
  auth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  proxy_server: teleport.exaplme-domain.com:443

auth_service:
  enabled: no
ssh_service:
  enabled: no
proxy_service:
  enabled: no

windows_desktop_service:
  enabled: yes
  ldap:
    addr:     '192.168.1.10:636'
    domain:   'dev.example-domain.local'
    username: 'DEV\svc-teleport'
    sid: 'S-1-5-21-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    server_name: 'dev_dc1.example-domain.local'
    insecure_skip_verify: false
    ldap_ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDiTCCAnGgAwIBAgIQQvbfEjREJrBPyPmJop5WhDANBgkqhkiG9w0BAQ0FADBX
        .............
        thegR2HWHqhIiJKgSYurIjSpFbFZXRwBxcx5rYqYXAPbZIbL5yyVMIN8lyYR
        -----END CERTIFICATE-----
    discovery:
      base_dn: '*'
    labels:
      teleport.internal/resource-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I am running teleport cluster version 11.2.1 and also telport clients are up to date.
