### ISSUE TITLE
Web UI doesn't show "Other sign-in options" on login

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#20432]
__Expected behavior:__

"Other sign-in options" is available on login (ie, https://myproxy/web/login).

__Current behavior:__

v11 doesn't show the "Other sign-in options" link, making it impossible to login using passwordless under certain settings.

The same setting does show the link when using v12-alpha1 binaries.

Example teleport.yaml:

```yaml
version: v3
teleport:
  nodename: zarquon
  data_dir: /path/to/data_dir

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: zarquon

proxy_service:
  enabled: "yes"
  https_keypairs:
  - cert_file: /path/to/cert.pem
    key_file:  /path/to/key.pem

ssh_service:
  enabled: "no"
```

__Bug details:__
- Teleport version: 11.2.2 (possibly others as well)
- Recreation steps: see above
- Debug logs: not necessary
