### ISSUE TITLE
Document new mapping

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2052]
This commit adds two extensions to template variables
in roles and adds support for regular expressions
and group captures in role mapping of trusted clusters.

1. Roles node_labels can refer to traits:

```yaml
allow:
  node_labels:
    '{{external.key}}': '{{external.key2}}'
deny:
  node_labels:
    '{{external.key}}': '{{external.key2}}'
```

If traits variable is not found, label key pair in allow or
deny rule will be set to empty key or value, so if 'external.val'
trait is missing, the resulting role will not match
allow or deny rule:

```yaml
allow:
  node_labels:
    '': 'val'
deny:
  node_labels:
    '': 'val'
```

Same thing will happen for missing value:

```yaml
allow:
  node_labels:
    'key': ''
deny:
  node_labels:
    'key': ''
```

2. Trusted cluster role mapping can now
support advanced expressions:

a. Glob values will match any string, including
empty one

```yaml
   role_map:
   - remote: 'cluster-*'
     local: [clusteradmin]
```

a. Regular expression syntax is supported:

Syntax: https://github.com/google/re2/wiki/Syntax

The syntax is only activated, when the expression starts
with `^` and ends with `$`, in this case expression 
is interpreted as a full string regexp match.

Brackets can be used as a capture group and referred
to with expand variable:

```yaml
   role_map:
   - remote: '^clusteradmin-(.*)$'
     local: [guest-$1]
```

Will map incoming role 'clusteradmin-account-1' to 'guest-account-1'.

3. Same regular expression syntax is supported for SAML and OIDC
mappings:

a. Glob matches of values instead of static matches:

```yaml
  claims_to_roles:
      - {claim: "roles", value: "gravitational/*", roles: ["clusteradmin"]}
```

`*` internally is converted to `(.*)`, and the glob expression above is treated as

`^gravitational/(.*)$`. All regular expression characters are not processed as regular
expressions in glob expressions.

b. Regexp matches with subgroup expands:

```yaml
  attributes_to_roles:
      - {name: "roles", value: "gravitational/(.*)", roles: ["cluster-$1", "$2", "partial-$1-$2"]}
```

In case if match occurs, but not all expand are matching, the following will happen:

`gravitational/test` will result in roles `cluster-test`, `partial-test-`,  the partial expand `$2` that did not match, was replaced with empty string. The value `"$2"` resulted in empty string and was removed from the resulting list of roles, but partial match `partial-$1-$2` was replaced with `partial-test-`
