### ISSUE TITLE
AWS EKS FailedMount

### ISSUE THREAD

**Issue by nathan-bowman** [gravitational/teleport#20660]
Expected behavior:
Running thru the steps in: https://goteleport.com/docs/deploy-a-cluster/helm-deployments/aws/?scope=enterprise

A proper running Teleport deployment...

Current behavior:
Teleport deployment to EKS stuck on ContainerCreating

```
# kubectl -n teleport get all
NAME                           READY   STATUS              RESTARTS   AGE
pod/teleport-b58654658-gcp8t   0/1     ContainerCreating   0          3h23m
pod/teleport-b58654658-x9zfd   0/1     ContainerCreating   0          3h23m

NAME               TYPE           CLUSTER-IP      EXTERNAL-IP                                                                     PORT(S)         AGE
service/teleport   LoadBalancer   10.100.166.42   a2b03df98882f42ffa821b46b55a2ee4-07ee1ce5e686b4ad.elb.us-east-1.amazonaws.com   443:32218/TCP   3h23m

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/teleport   0/2     2            0           3h23m

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/teleport-b58654658   2         2         0       3h23m
```

```
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  60m (x17 over 3h9m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[teleport-tls], unattached volumes=[teleport-tls config data kube-api-access-42twn license]: timed out waiting for the condition
  Warning  FailedMount  40m (x17 over 3h12m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[teleport-tls], unattached volumes=[config data kube-api-access-42twn license teleport-tls]: timed out waiting for the condition
  Warning  FailedMount  35m (x7 over 164m)      kubelet  Unable to attach or mount volumes: unmounted volumes=[teleport-tls], unattached volumes=[data kube-api-access-42twn license teleport-tls config]: timed out waiting for the condition
  Warning  FailedMount  6m26s (x24 over 3h14m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[teleport-tls], unattached volumes=[license teleport-tls config data kube-api-access-42twn]: timed out waiting for the condition
  Warning  FailedMount  72s (x104 over 3h16m)   kubelet  MountVolume.SetUp failed for volume "teleport-tls" : secret "teleport-tls" not found
```

Bug details:
- helm version
`version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`

- kubectl version
`Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4`

- eksctl version
`0.125.0`

teleport-eks.yaml:
```
apiVersion: eksctl.io/v1alpha5

availabilityZones:
- us-east-1a
- us-east-1b
- us-east-1c
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  vpcResourceControllerPolicy: true
  withOIDC: true

kind: ClusterConfig

managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 3
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: true
      certManager: true
      cloudWatch: true
      ebs: false
      efs: false
      externalDNS: true
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: t2.medium
  labels:
    alpha.eksctl.io/cluster-name: teleport-eks
    alpha.eksctl.io/nodegroup-name: teleport-eks
  maxSize: 3
  minSize: 2
  name: teleport-eks-nodegroup-1
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
    publicKeyPath: ""
  tags:
    alpha.eksctl.io/nodegroup-name: teleport-eks
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3

metadata:
  name: teleport-eks
  region: us-east-1
  version: "1.24"

privateCluster:
  enabled: false
  skipEndpointCreation: false

vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single

iamIdentityMappings:
  - arn: <redacted>
    username: <redacted>
    groups:
      - system:masters
    noDuplicateARNs: true # prevents shadowing of ARNs
  - arn: <redacted>
    groups:
      - system:masters
    username: eksctlrole
    noDuplicateARNs: true # prevents shadowing of ARNs
```

teleport-aws-values.yaml
```
---
clusterName: <redacted>
kubeClusterName: teleport-eks
authenticationType: local
proxyListenerMode: multiplex
enterprise: true
chartMode: aws

aws:
  region: us-east-1
  backendTable: teleport-helm-backend
  auditLogTable: teleport-helm-events
  auditLogMirrorOnStdout: false
  sessionRecordingBucket: teleport-helm-sessions
  backups: true
  dynamoAutoScaling: false

highAvailability:
  replicaCount: 2
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  certManager:
    addCommonName: true
    enabled: true
    issuerName: letsencrypt-production
    issuerKind: Issuer
    issuerGroup: cert-manager.io
```

teleport-aws-issuer.yaml:
```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: teleport
spec:
  acme:
    email: <redacted>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsZones:
          - "<redacted>"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: <redacted>
```

Kubernetes deployed with:
`eksctl create cluster -f teleport-eks.yaml`

Then:
```
helm repo add teleport https://charts.releases.teleport.dev
helm repo update
helm install cert-manager jetstack/cert-manager --create-namespace --namespace cert-manager --set installCRDs=true --set extraArgs="{--issuer-ambient-credentials}" --debug
cmctl check api

kubectl create namespace teleport
kubectl --namespace teleport create -f teleport-aws-issuer.yaml
kubectl -n teleport create secret generic license --from-file=license.pem
helm install teleport teleport/teleport-cluster --namespace teleport -f teleport-aws-values.yaml
```

The error is the same as: https://github.com/gravitational/teleport/issues/16619
