### ISSUE TITLE
Allow labels to be set by configuration when automatically enrolling EC2 instances

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#20676]
What would you like Teleport to do?

Allow labels to be configured on the `discovery_service` without having to [customize the default installer script](https://goteleport.com/docs/server-access/guides/ec2-discovery/#step-66-optional-customize-the-default-installer-script) for EC2 instance enrolment.

Some options are:

1. Add `discovery_service` tags automatically as labels in the installer script without the need to [enable tags in instance metadata](https://goteleport.com/docs/management/guides/ec2-tags/#enable-tags-in-instance-metadata).

2. Define static labels in the `discovery_service` configuration, e.g. 

```
discovery_service:
  aws:
    - types: ["ec2"] 
      tags:
       - "env": "prod"
      install: # optional section when default-installer is used.
        script_name: "default-installer"
      labels:
       - "environment": "production"
    - types: ["ec2"] 
      tags:
       - "env": "devel"
      install:
        script_name: "devel-installer"
      labels:
       - "environment": "development"
```

What problem does this solve?

Currently on v11.2.3 (preview), the only supported way to add custom labels is to create multiple different installer scripts.

If a workaround exists, please include it.

Customize the default installer script.
