### ISSUE TITLE
Log to fs and dynamo at the same time [TBD]

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2070]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by kontsevoy** [comment]
I am much in favor of simply converting `type` to array, i.e.

```
teleport:
    storage: 
        type: [dynamodb, dir]
```

but the old type (string) should also be supported.
If this is tricky, we can do:

```
teleport:
    storage: 
        type: "dynamodb, dir"
```

whatever the case, the existing storage configuration format has clearly reached its limits. in the future I'd love to see something like this:

```
audit_providers:
    - dir:
          path: /var/to/audit
    - https:
          addr: https://addr
    - dynamodb:
          region: xxx
          table: yyy
    - exec:
         path: /path/to/executable
```

People clearly have indefinite list of audit needs, so having a system of "audit sinks" that all accept a documented / standartized (say, JSON) audit events, is how it would be nice to have it in the ideal scenario.

But for now simply allowing multiple "type" values is the most natural and easy to extend (and to understand) way to do this IMO

**Comment by kontsevoy** [comment]
Will this example work?


```
teleport:
  storage:
      type: dir
      path: /var/lib/teleport
      region: us-west-1
      audit_events_uri:  [file:///var/lib/teleport/audit/events, dynamo://test_grv8_events]
```

this is "backwards", i.e. someone was using "dir" and decided to add dynamo to the existing setup.
