### ISSUE TITLE
The nodes with same labels are displayed as one node

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2116]
**What happened**:
1. Two nodes with same labels are displayed as one node, but changes intermittently.
I will just post the gif.

![jul-26-2018 22-52-08](https://user-images.githubusercontent.com/9734362/43266701-034c7b38-9127-11e8-9cda-ce6ea357fc34.gif)

**What you expected to happen**:
1. I expect to see two nodes with same labels, but with different addresses

**How to reproduce it (as minimally and precisely as possible)**:

```
teleport:
  auth_servers:
    - some-auth-servers.com
  auth_token: /var/lib/teleport/token
  nodename: ip-10-10-23-10
  public_addr: 10.10.23.10
  data_dir: /var/lib/teleport
  log:
    output: syslog
    severity: INFO

auth_service:
  enabled: no

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:3022
  labels:
    provider: aws
    env: stg
    service: web
    ver: 2.6.7
  commands:
  - name: node
    command: [/bin/sh, /usr/local/bin/tag-retriever, Name] // retrieves aws tag w/ Name
    period: 1h0m0s
  - name: application
    command: [/bin/sh, /usr/local/bin/tag-retriever, Application] // retrieves aws tag w/ Application
    period: 1h0m0s

proxy_service:
  enabled: no
```

**Environment**:
- Teleport version (use `teleport version`):Teleport Enterprise v2.6.7 git:v2.6.7-0-g280f0fe3
- Tsh version (use `tsh version`): Teleport v2.6.7 git:v2.6.7-0-g280f0fe3
- OS (e.g. from /etc/os-release):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Browser environment**

- Browser Version (for UI-related issues): Chrome 67.0.3396.99 (Official Build) (64-bit), Safari Version 11.1.2 (12605.3.8.1)
- Install tools: NA
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug
