### ISSUE TITLE
no cipher suite supported by both client and server | AWS EKS

### ISSUE THREAD

**Issue by itsmesuniljacob** [gravitational/teleport#21296]
Expected behavior:

Teleport welcome page

Current behavior:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/16597269/217007989-16e50ea4-db2b-4f01-a56d-e7dab8ef550f.png">

Pods are getting errors as below

```
ERROR REPORT:
Original Error: *errors.errorString tls: no cipher suite supported by both client and server
Stack Trace:
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:388 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:326 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: tls: no cipher suite supported by both client and server] alpnproxy/proxy.go:334
2023-02-06T15:03:48Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *errors.errorString tls: no cipher suite supported by both client and server
Stack Trace:
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:388 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:326 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
	runtime/asm_amd64.s:1594 runtime.goexit
```
Bug details:
- Teleport version: 11.1.4
- Recreation steps: Install teleport on EKS through helm. Used NLB, instead of classic, by adding the following annotations.
```
    service: 
      external-dns.alpha.kubernetes.io/hostname: teleport.utility-v7.engops.public.aws.cradlepointecm.com
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:010290182366:certificate/294df219-eb63-4eba-bef0-84437fad478e
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```
- Debug logs
<img width="481" alt="image" src="https://user-images.githubusercontent.com/16597269/217013420-3f1b81d7-e282-43c1-b163-4650d627b0e0.png">
