### ISSUE TITLE
Document how to backup, restore and bootstrap a cluster deployed with Helm

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#21300]
## Details

The page https://goteleport.com/docs/management/operations/backup-restore/ gives high-level guidelines on how users can backup and restore a Teleport cluster.

Users running Teleport on Kubernetes and using our `teleport-cluster` Helm chart need more detailed information on achieving this with the chart.

The guide should cover:
- how to backup a Teleport cluster running in any mode on Kubernetes (at least the CA)
- how to restore the cluster

Some of this information was in the `deploy-a-cluster/helm-deployment/migration.mdx` guide that has been removed in v12.

**Comment by zifeo** [comment]
@hugoShaka currently, the only way to restore using Kubernetes is to use extraArgs with a custom file mount, correct?

**Comment by hugoShaka** [comment]
Yes, you currently have to mount your cluster state backup and pass `--bootstrap`. Please note that this only works on clean uninitialized backends. If there's already a cluster state in your Dynamo/Firestore/... backend, Teleport will ignore the `--bootstrap` flag.

If you have a `my-backup` Secret containing a `backup.yaml` key, the chart values should look like this

```yaml
extraVolumes:
  - name: my-backup
    secret:
      secretName: my-backup
extraVolumeMounts:
  - name: my-backup
    mountPath: /var/lib/teleport-backup/
    readOnly: true
extraArgs: ["--bootstrap", "/var/lib/teleport-backup/backup.yaml"]
```
