### ISSUE TITLE
Cannot rename cluster and connect to trusted cluster.

### ISSUE THREAD

**Issue by sebakerckhof** [gravitational/teleport#2146]
**What happened**:
I'm trying to rename a cluster which should connect (reverse tunnel) to another (main) cluster.
At first I got an error when starting teleport stating: 
`Original Error: *trace.BadParameterError cannot rename cluster "foo" to "bar": clusters cannot be renamed`

The documentation is kinda vague on how to deal with a cluster rename. I understood certificates need to be regenerated, so I deleted the data dir (/var/lib/teleport). And restarted teleport daemon. Now teleport can run, but when trying to connect to the main cluster using:

`tctl create -f trusted_cluster.yaml --debug`. I now get:
```
Original Error: *trace.BadParameterError key is a directory
Stack Trace:
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/lib/auth/clt.go:1808 github.com/gravitational/teleport/lib/auth.(*Client).UpsertTrustedCluster
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:192 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).createTrustedCluster
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:73 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).(github.com/gravitational/teleport/tool/tctl/common.createTrustedCluster)-fm
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:171 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:103 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:117 github.com/gravitational/teleport/tool/tctl/common.Run
	/build/teleport-2.4.0+bora2/src/github.com/gravitational/teleport/tool/tctl/main.go:32 main.main
	/usr/lib/go-1.9/src/runtime/proc.go:194 runtime.main
	/usr/lib/go-1.9/src/runtime/asm_amd64.s:2338 runtime.goexit
```

From what I get by skimming through the code this error comes from the main cluster.

**What you expected to happen**:
Clusters can connect to each other.

**How to reproduce it (as minimally and precisely as possible)**:
1. have one teleport cluster as main cluster.
2. have a second teleport cluster. My config file:
```
teleport:
  nodename: myDevice
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: CLUSTER_SECRET
  auth_servers:
  - 127.0.0.1:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stdout
    severity: DEBUG
auth_service:
  enabled: "yes"
  cluster_name: foo
  listen_addr: 127.0.0.1:3025
  tokens:
  - trusted_cluster:CLUSTER_SECRET
  authentication:
    # default authentication type. possible values are 'local', 'oidc' and 'saml'
    # only local authentication (Teleport's own user DB) is supported in the open
    # source version
    type: local
    # second_factor can be off, otp, or u2f
    second_factor: off

ssh_service:
  enabled: "yes"
  listen_addr: 127.0.0.1:3022
proxy_service:
  enabled: "yes"
  listen_addr: 127.0.0.1:3023
  web_listen_addr: 127.0.0.1:3080
  tunnel_listen_addr: 127.0.0.1:3024
```
3. connect using `tctl create -f trusted_cluster.yaml --debug`, with `trusted_cluster.yaml`:
```
# trusted _cluster.yaml
kind: trusted_cluster
version: v2
metadata:
  # the trusted cluster name MUST match the 'cluster_name' setting of the
  # cluster
  name: main
spec:
  # this field allows to create tunnels that are disabled, but can be enabled later.
  enabled: true
  # the token expected by the "main" cluster:
  token: CLUSTER_SECRET
  # the address in 'host:port' form of the reverse tunnel listening port on the
  # "master" proxy server:
  tunnel_addr: teleport-proxy.my.cloud:443
  # the address in 'host:port' form of the web listening port on the
  # "master" proxy server:
  web_proxy_addr: teleport.my.cloud:443
```
4. stop teleport, remove data dir and restart with a changed cluster name
5. run step 3 again.

**Environment**:
- Teleport version (use `teleport version`): 2.4.0
- Tsh version (use `tsh version`): 2.4.0
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)

**Relevant Debug Logs If Applicable**
