### ISSUE TITLE
Cannot see newly added Nodes

### ISSUE THREAD

**Issue by danielslyman** [gravitational/teleport#21542]
I cannot seem to see new nodes. Log states that the node has successfully joined. 

              weirdly though, the node isn't listening to 3022

![image](https://user-images.githubusercontent.com/17143596/217851496-9992d7bb-0463-4c18-b9de-601cc2820e5b.png)

![image](https://user-images.githubusercontent.com/17143596/217851735-8e23f7a9-a81d-4a8d-9d6f-4845f1f24068.png)

_Originally posted by @danielslyman in https://github.com/gravitational/teleport/issues/21461#issuecomment-1424342994_

**Comment by marcoandredinis** [comment]
Extra info from the other issue
Teleport Version 12.0.1
Roles:
```
User   Roles
------ ---------------------
daniel editor,auditor,access
pvsv   editor,access
```
<details>
  <summary>Roles</summary>

```yaml

kind: role
metadata:
  description: Edit cluster configuration
  id: 1675951884021772258
  name: editor
spec:
  allow:
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    rules:
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - oidc_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github_request
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_audit_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_auth_preference
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_name
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_networking_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session_recording_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - remote_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - connection_diagnostic
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - database_certificate
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - installer
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - login_rule
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - db_service
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: false
    ssh_file_copy: true
version: v5


kind: role
metadata:
  description: Access cluster resources
  id: 1675692253357871621
  name: access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - '{{internal.aws_role_arns}}'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
    - resources:
      - instance
      verbs:
      - list
      - read
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: true
    ssh_file_copy: true
version: v5


kind: role
metadata:
  description: Review cluster events and replay sessions
  id: 1675692253374443269
  name: auditor
spec:
  allow:
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    logins:
    - no-login-ddf6ce34-0737-4502-bab6-8675a08e2417
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session_tracker
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: false
    ssh_file_copy: true
version: v5
  ```
</details>

**Comment by marcoandredinis** [comment]
> I have the same issue with standard roles, any ideas? Followed the Docker instruction, script was installed, logs say the nodes joined the cluster, yet they are not visible

Which instructions are you referring to? This guide? https://goteleport.com/docs/management/guides/docker/

**Comment by danielslyman** [comment]
correct :)

**Comment by danielslyman** [comment]
```
version: v3
teleport:
  nodename: teleport.domain.io
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: 49.12.222.14:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
  public_addr: teleport.domain.io:443

```

**Comment by danielslyman** [comment]
Prior to v12 I was able to manually add new nodes

**Comment by danielslyman** [comment]
```
version: v3
teleport:
  nodename: teleport.domain.io
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: teleport-auth.domain.io
  #proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
  public_addr: teleport.domain.io:443
```

this also worked, I am behind a CloudFlare Zero Trust Tunnel
