### ISSUE TITLE
Cannot connect trusted cluster : trusted cluster already exists

### ISSUE THREAD

**Issue by samouds** [gravitational/teleport#2158]
Hello,
I'm facing some difficulties to connect some trusted cluster to the main server.

I'm running version 2.6.6 but when I try to add some new clusters I get : 
```error: trusted cluster 'tpt.xxxx.xxxx' already exists```

My main cluster proxy is running behind a lets encrypt proxy that take care of the ssl certificate for the main domain tpt.xxxx.xxxx.

I have some cluster that join successfully and others don't.

Here are my configs :

**Main cluster :**
**auth :**
launch command : ```teleport start --roles=auth -c /etc/teleport/teleport.yaml --insecure```
```
teleport:
 nodename: tpt.xxxx.xxxx

ssh_service:
 enabled: no

auth_service:
 enabled: yes
 cluster_name: tpt.xxxx.xxxx
 tokens:
   - "node,proxy:TOKEN"
   - "trusted_cluster:CLUSTER_TOKEN"
   - "trustedcluster:CLUSTER_TOKEN"
 labels:
     cluster: tpt.xxxx.xxxx

proxy_service:
 enabled: no
```

**proxy :** 
launch command :  ```teleport start --roles=proxy -c /etc/teleport/teleport.yaml --insecure --insecure-no-tls```
```
teleport:
   nodename: "tpt.xxxx.xxxx-proxy"
   auth_token: "TOKEN"
   auth_servers:
       - auth:3025

auth_service:
   enabled: no

ssh_service:
   enabled: yes

proxy_service:
   enabled: yes
   listen_addr: 0.0.0.0:3023
   tunnel_listen_addr: 0.0.0.0:3024
   web_listen_addr: 0.0.0.0:3080
   public_addr: tpt.xxxx.xxxx
```

**Trusted cluster :**
**node :**
```
teleport:
 nodename: "RPI_HOSTNAME"
auth_service:
 enabled: yes
 session_recording: "off"
ssh_service:
 enabled: yes
proxy_service:
 enabled: yes
```

**trusted cluster :**
```
kind: trusted_cluster
version: v2
metadata:
 name: tpt.xxxx.xxxx
spec:
 enabled: true
 token: "CLUSTER_TOKEN"
 tunnel_addr: tpt.xxxx.xxxx:3024
 web_proxy_addr: tpt.xxxx.xxxx
```
