### ISSUE TITLE
Teleport Remote Access and teleport Client access on the same machine

### ISSUE THREAD

**Issue by mighty-services** [gravitational/teleport#21605]
Expected behavior:
Having a teleport Client running on an Ubuntu "jump host" for Windows Remote Desktop Access and having this Ubuntu client also in the "Servers" Area of the WebUI to access the jump host itself.

Current behavior:
I installed the teleport Client on the client on site with the remote desktop rollout-script and this was working fine, but I couldn’t access the teleport client itself through the Server-section in the WebUI.

Therefore, I backed up the yaml file, remove the teleport instance completely and reinstalled the teleport client through the Add resource ⇾ Server. Therefore, it installed the instance with access to the teleport Client itself.
Now I added the `windows_desktop_service` part of the old yaml file into the new one and starts the service. It didn’t start but throws the error 
`WindowsDesktop failed to establish connection to cluster: node "xxxx" [xxxxxxxxxxxxxx] can not join the cluster, the token does not allow "WindowsDesktop" role`

I commented out the `auth_token` in the `teleport`-section, and restarting the services worked now. But I can’t access the windows-desktops anymore. The error no says:
`WindowsDesktop failed to establish connection to cluster: "xxxx" can not join the cluster with role "WindowsDesktop", token expired or not found.`

That's how my yaml file looks like right now (with cleared secrets, of course):
```
version: v3
teleport:
  nodename: zabbix-proxy
  data_dir: /var/lib/teleport
#  join_params:
#    token_name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#    method: token
  proxy_server: tpxport.ecample.com:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  diag_addr: ""

  auth_token: xxxxxxxxxxxxxxxxxxxx
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: xxxxxxxxxxxxxxxxxxxx
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}

windows_desktop_service:
  enabled: yes
  ldap:
    addr:     'xxxxxxxxxxxxxxxxxxxx'
    domain:   'xxxxxxxxxxxxxxxxxxxx'
    username: 'xxxxxxxxxxxxxxxxxxxx'
    sid: 'xxxxxxxxxxxxxxxxxxxx'
    server_name: 'xxxxxxxxxxxxxxxxxxxx'
    insecure_skip_verify: false
    ldap_ca_cert: |
        -----BEGIN CERTIFICATE-----
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        -----END CERTIFICATE-----

  discovery:
    base_dn: '*'
  labels:
    teleport.internal/resource-id: xxxxxxxxxxxxxxxxxxxx
```
