### ISSUE TITLE
Document multiple node_labels value support

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2164]
## Description

The following formats have been added for `node_labels` support:

```yaml
allow:
  node_labels:
    # in case of multiple values, the condition reads as 'or'
    # allow access to qa or stage
    'env: ['qa', 'stage']
    # scalar values are fully supported as well
     'acceess': ok
deny:
  node_labels:
    # reads as 'or' - deny access to preprod or prod
    'env: ['preprod', 'prod']
    'acceess': ok
```
