### ISSUE TITLE
Can't rename trusted cluster

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2181]
I created a trusted cluster by running `teleport start --roles=proxy,node,auth` on a device and then running `tctl create cluster.yaml` with:

```
# cluster.yaml
kind: trusted_cluster
version: v2
metadata:
 name: main
spec:
 enabled: true
 token: omitted
 tunnel_addr: teleport.mydomain.com:3024
 web_proxy_addr: teleport.mydomain.com:3080

```

It created the cluster successfully, and when I went to the Web UI the dropdown of clusters showed two items: "main" and "hostnameofdevice" (where the latter was actually the host name of the device, which I am not including here).

I want to call this cluster something else, so I edited the `teleport.yaml` file on the `hostnameofdevice` device to include:

```
auth_service:
    cluster_name: "customclustername"
```
I then restart the teleport service on both the `main` teleport server and the `hostnameofdevice` device and run `tctl create --force cluster.yaml` on `hostnameofdevice`, but it doesn't work.

How can I rename the trusted cluster name?

Thank you

**Environment**:
- Teleport version (use `teleport version`): 2.7.4
- Tsh version (use `tsh version`): 2.7.4
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
I also experienced this on Ubuntu 16.0.4 before upgrading.
