### ISSUE TITLE
Database Access multi AWS Accounts Support

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#21872]
This is an umbrella ticket to track DB Access with AWS multi account support progress: 

### Phase 1 (12.2 -12.3 / April)

```[tasklist]
### Implementation
- [ ] https://github.com/gravitational/teleport/issues/15024
- [x] DB Access multi AWS Accounts support in teleport database bootstrap/configure commands
```

#### Success Criteria:
- Users can use a single database agent to provide access to databases in different AWS accounts.
- DB Agent can discover and configure DB access in different AWS Accounts. 

### Phase 2 (12.2 -12.3 / April)
```[tasklist]
### Post Items:  
- [ ] Documentation
```

**Comment by GavinFrazar** [comment]
`teleport db configure create aws` and `teleport db configure bootstrap` currently modify just one AWS IAM role/user/identity at a time. With support for cross-account AWS, there could be many roles to configure.For example:
```yaml
  databases:
    - name: "db1"
      protocol: "postgres"
      uri: "postgres-rds.abcdef123456.us-west-1.rds.amazonaws.com:5432"
      aws:
        region: "us-west-1"
        assume_role_arn: "arn:aws:iam::222222222222:role/some-role"
        external_id: "someUniqueID"
        rds:
          instance_id: "postgres-rds"
    - name: "db2"
      protocol: "postgres"
      uri: "postgres-rds.abcdef123456.us-west-1.rds.amazonaws.com:5432"
      aws:
        region: "us-west-1"
        assume_role_arn: "arn:aws:iam::333333333333:role/some-other-role"
        external_id: "someUniqueID"
        rds:
          instance_id: "postgres-rds"
 ```
In this case we need want to configure:
1. the identity that the database agent will use to assume these roles, such that it will have sts:AssumeRole permission to assume either of the external roles
2. both the role in account “222…”  and “333….” to each have a trust policy allowing the agent’s identity as a principal, as well as the permissions boundary and all the other permissions needed

I don’t think this can be done as a single command, because it would be trying to configure roles in multiple accounts.
Any suggestions for the UX here? @smallinsky @greedy52
