### ISSUE TITLE
Postgres tsh Database Config gives listen address port, not web port in multiplex mode

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#22047]
Expected behavior:

The `tsh db config` uses the web address port for Postgres.

Current behavior:

The listener address is given in a multiplex configuration.  The public port is `443` specified in the proxy config.

```bash
tsh db config
Name:      av-psqlrds-dev
Host:      samcluster.example.com
Port:      3080
User:
Database:
CA:        /Users/steven/.tsh/keys/samcluster.example.com/cas/samcluster.example.com.pem
Cert:      /Users/steven/.tsh/keys/samcluster.example.com/steven-db/samcluster.example.com/av-psqlrds-dev-x509.pem
Key:       /Users/steven/.tsh/keys/samcluster.example.com/steven
```

```yaml
{
  "auth": {
    "type": "",
    "private_key_policy": "",
    "has_motd": false
  },
  "proxy": {
    "kube": {
      "enabled": true,
      "listen_addr": "0.0.0.0:3080"
    },
    "ssh": {
      "listen_addr": "0.0.0.0:3080",
      "tunnel_listen_addr": "0.0.0.0:3080",
      "web_listen_addr": "0.0.0.0:3080",
      "public_addr": "samcluster.example.com:443"
    },
    "db": {
      "postgres_listen_addr": "0.0.0.0:3080",
      "mysql_listen_addr": "0.0.0.0:3080"
    },
    "tls_routing_enabled": true
  },
  "server_version": "12.0.2",
  "min_client_version": "11.0.0",
  "cluster_name": "samcluster.example.com"
}
```

Bug details:
- Teleport version: 12.0.2
- Recreation steps

1. Setup a multiplex deployment.
2. Add a postgres db
3. Run `tsh db config`
