### ISSUE TITLE
Regex expression for node_labels is not yet supported

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2205]
**What happened**:
 https://github.com/gravitational/teleport/issues/2136#issuecomment-410538313
The above comment is declaring to support regex-expression in node_labels; but following PR are not yet supporting it.

https://github.com/gravitational/teleport/pull/2162
https://github.com/gravitational/teleport/pull/2160

**What you expected to happen**:
2.4.7 Teleport has not yet supported regex-expression in node_labels.

**How to reproduce it (as minimally and precisely as possible)**:
Adding the config expressed in the comment.
https://github.com/gravitational/teleport/issues/2136#issuecomment-412160717

```
allow:
  node_labels:
    'env: '^production|staging$'
deny:
  node_labels:
    'env: '^test$'
```

```
allow:
  node_labels:
    'env: ['^production|staging$', 'test']
deny:
  node_labels:
    'env: ['^test$', 'list']
```

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v2.7.4 git:v2.7.4-0-g2fff1056
- Tsh version (use `tsh version`): na
- OS (e.g. from /etc/os-release): CentOS Linux, Amazon Linux2

**Browser environment**

- Browser Version (for UI-related issues): na
- Install tools: na
- Others: na

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug
