### ISSUE TITLE
Hide "Management" panel completely for a specific role

### ISSUE THREAD

**Issue by Sovenique** [gravitational/teleport#22123]
Greetings,

I've noticed that some users with "restrictive" roles, let's say this one below, can still access the Management panel. The only option which appears to their POV, is "Enroll New Resource" and the "NEXT" button is greyed out (as expected). 

```
kind: role
metadata:
  id: 1677059366742342912
  name: restricted_to_test_3
spec:
  allow:
    logins:
    - tester
    node_labels:
      hostname: test-3.devops.com
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v5
```

Is there a way to completely conceal the Management panel for such roles? Restricted users should only access the Resources panel and their "allowed" resources respectively. I couldn't find anything related in the documentation, am I missing something?

Thank you so much for your time!
