### ISSUE TITLE
Unable to join own session with v3 role on Teleport 10+

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#22162]
## Expected behavior:

I should be able to join my own sessions

## Current behavior:

As of Teleport 10.0.0, there is an `-internal-teleport-join` special username that gets used when joining a session. When attempting to join that session, the ssh node/agent checks to see if there is a newer role that has moderated sessions. If it does, it will handle the special case for session joining. If the role version is too old, it seems to treat it like the end user is literally trying to log in with that as the username.

The exact behavior varies by the specific tsh, web console, and ssh node/agent version involved.

In particular, upgrading from Teleport 9 to Teleport 10 is what prompted the investigation.

* tsh 9.x does not send the `-internal-teleport-join` when joining a session.
* tsh 10.x and up does use the special token, regardless of the role version the end-user a member of.
* Teleport web console 10.x and up also uses the special `-internal-teleport-join` token no matter what.
* Teleport 10.x ssh service only considers `-internal-teleport-join` if the user is in a v5 role: https://github.com/gravitational/teleport/blob/v10.3.9/lib/srv/authhandlers.go#L535-L538

I also tested this with 12.0.2 across the board, but still a v3 role. `tsh join 48ee9a07-d55c-41ff-8a59-7c3274592a33` still returns the error, but I can successfully join the same session from the 12.0.2 web console. I didn't test version 11.

Here's the error message that is seen in tsh and the web console when it occurs:

```
ERROR: access denied to -teleport-internal-join connecting to f1ea26bb-0a79-475b-a109-01f00af65eb5:0@default@teleport.example.com
```

Here's the log as it appears in the 10.3.9 node (debug off):

```
ERRO [NODE]      Permission denied: user minimal@nodename is not authorized to login as -teleport-internal-join@teleport.example.com: access to nodename denied. User does not have permissions. Confirm SSH login. fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:/5uGuVYhvL8EjUlirilfjVRoOoLfNzzLz4crUEkEHgw local:192.168.74.199:54554 remote:192.168.68.200:30754 user:-teleport-internal-join srv/authhandlers.go:387
```

I was able to reproduce this with the following role and user:

```yaml
kind: user
metadata:
  name: minimal
spec:
  roles:
  - minimal
  traits:
    logins:
    - root
    - ubuntu
    - minimal
version: v2
---
kind: role
metadata:
  description: minimal repro
  name: minimal
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v3
```

### Bug details:
- Teleport version - 10.3.9 and 12.0.2
- Recreation steps - create that user and role, start a session, attempt to join the session as the same user
- Debug logs - see above

### Workaround

The logic in authhandlers.go is specifically looking for the presence of a v5 role. If a Teleport admin changes the affected role(s) from v3 to v5, then the session joining logic is correctly handled.

The same exact v3 roles on teleport 9 allow a user to join their own role, so the same behavior should be preserved.
