### ISSUE TITLE
Feature request: Improve message of the day

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#22334]
### Discussed in https://github.com/gravitational/teleport/discussions/22277

<div type='discussions-op-text'>

<sup>Originally posted by **beliven-fabrizio-gortani** February 25, 2023</sup>
Hi everyone! I know that it's not an essential feature for the functionalities offered by the fantastic Goteleport, but if it doesn't require a huge implementation effort, it would be nice if the system could read the message of the day from a file, so that it can generate nicer and more personalized messages (such as multi-line or ASCII art).</div>

**Comment by zmb3** [comment]
Does this not work?

```yaml
auth_service:
    message_of_the_day: |
      This is a multiline
      message of the day!
```

**Comment by webvictim** [comment]
Yes, it does:

```yaml
auth_service:
  enabled: yes
  message_of_the_day: |
    ##### ######  ####  #####
      #   #      #        #
      #   #####   ####    #
      #   #           #   #
      #   #      #    #   #
      #   ######  ####    #
```

```console
$ tsh login --proxy teleport.example.com
##### ######  ####  #####
  #   #      #        #
  #   #####   ####    #
  #   #           #   #
  #   #      #    #   #
  #   ######  ####    #

Press [ENTER] to continue.
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:62385/e8655dea-d95f-41a8-83d2-7a1b8a3f6801
```

Reading from a file is probably still desirable to avoid YAML multi-line gotchas - a more detailed ASCII art didn't work, for example:

```yaml
auth_service:
  enabled: yes
  message_of_the_day: |
     _________
    < welcome >
     ---------
            \   ^__^
             \  (oo)\_______
                (__)\       )\/\
                    ||----w |
                    ||     ||
```

```console
$ sudo teleport configure --test /etc/teleport.yaml
FAIL /etc/teleport.yaml
ERROR: failed parsing the config file: yaml: line 23: did not find expected key
```
