### ISSUE TITLE
Provide a way to inject Teleport session ID as a header into `app_service` requests

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#22417]
**What would you like Teleport to do?**

As per https://github.com/gravitational/teleport/discussions/22238, there isn't currently an easy way to cross-reference a Teleport application access session with the logs on a downstream application.

One way we could handle this would be to support injecting an arbitrary header with the Teleport session ID into every request that the `app_service` makes, similar to the way we support [JWT injection](https://goteleport.com/docs/application-access/jwt/introduction/#inject-jwt):

```yaml
app_service:
  enabled: true
  apps:
  - name: "app"
    uri: https://localhost:3000
    public_addr: app.teleport.example.com
    rewrite:
      headers:
      - "X-Teleport-Session-ID: {{internal.session_id}}"
```

**What problem does this solve?**

Makes it easier to cross-reference actions inside an application with the Teleport user who performed them.

**If a workaround exists, please include it.**

None currently known, except manually searching audit logs for characteristics of requests.
