### ISSUE TITLE
Agent Failed to claim proxy with multi proxy server

### ISSUE THREAD

**Issue by saeroshi** [gravitational/teleport#22497]
Expected behavior:
-------------------

Agent (Node) connect to cluster Teleport

Current behavior:
-----------------

Agent loop connection to cluster node with error log.
Open many tcp port with this error.

This problem does not happen with 1 proxy.

Bug details:
------------

- Teleport version : 11.3.5 or 12.0.4

For recreation :

- 1 Reverse Proxy HAProxy :
```
peers teleport-peers
	peer ha-teleport-1 10.200.0.2:10000

listen tcp-teleport-prod-proxy
	bind X.X.X.X:3023

	mode tcp
	option tcplog
	timeout client 350s
	timeout server 350s

	option httpchk
        http-check connect
        http-check send meth GET uri /healthz
        http-check expect status 200

	default-server inter 2s fall 5 rise 2 port 3000

	balance leastconn
	stick-table type ip size 1m expire 4h peers teleport-peers
	stick on src
	server teleport-app-prod-1 10.200.0.5:3023 check send-proxy
	server teleport-app-prod-2 10.200.0.6:3023 check send-proxy
	server teleport-app-prod-3 10.200.0.7:3023 check send-proxy

listen tcp-teleport-prod-tunnel
	bind X.X.X.X:3024

	mode tcp
	option tcplog
	timeout client 350s
	timeout server 350s

	option httpchk
        http-check connect
        http-check send meth GET uri /healthz
        http-check expect status 200

	default-server inter 2s fall 5 rise 2 port 3000

	balance leastconn
	stick-table type ip size 1m expire 4h peers teleport-peers
	stick on src
	server teleport-app-prod-1 10.200.0.5:3024 check send-proxy
	server teleport-app-prod-2 10.200.0.6:3024 check send-proxy
	server teleport-app-prod-3 10.200.0.7:3024 check send-proxy

listen tcp-teleport-prod-web
	bind X.X.X.X:443

	mode tcp
	option tcplog
	timeout client 350s
	timeout server 350s

	option httpchk
        http-check connect
        http-check send meth GET uri /healthz
        http-check expect status 200

	default-server inter 2s fall 5 rise 2 port 3000

	balance leastconn
	stick-table type ip size 1m expire 4h peers teleport-peers
	stick on src
	server teleport-app-prod-1 10.200.0.5:443 check send-proxy
	server teleport-app-prod-2 10.200.0.6:443 check send-proxy
	server teleport-app-prod-3 10.200.0.7:443 check send-proxy
```

- 1 Auth server :
```
version: v3
teleport:
#  nodename: teleport-auth-prod-1
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  diag_addr: 0.0.0.0:3000

auth_service:
  enabled: true
  proxy_listener_mode: separate
  listen_addr: 0.0.0.0:3025
  cluster_name: bastion.mydomain.net
  authentication:
    type: local
    second_factor: off
  tokens:
    - "node:tY7g5ntUMVCtCoK289FcKWxVfo5bnwWU"
    - "proxy,node:PYggjm3Gb5DfdSGTusu2cD83876xAsX4"
    - "auth:KZYAmRq9cPA59U4m2zuBjk3b5Dtb6JR2"

proxy_service:
  enabled: no

ssh_service:
  enabled: "no"
```

- 2 proxy :
```
version: v3
teleport:
#  nodename: teleport-proxy-prod-X
  data_dir: /var/lib/teleport
  auth_token: PYggjm3Gb5DfdSGTusu2cD83876xAsX4
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  diag_addr: 0.0.0.0:3000
  auth_server: 10.200.0.8:3025

auth_service:
  enabled: false

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  ssh_public_addr: bastion.mydomain.net:3023
  tunnel_listen_addr: 0.0.0.0:3024

  web_listen_addr: 0.0.0.0:443
  public_addr: bastion.mydomain.net:443

  tunnel_public_addr: bastion.mydomain.net:3024

  https_keypairs:
  - key_file: /etc/teleport/bastion.mydomain.net/privkey.pem
    cert_file: /etc/teleport/bastion.mydomain.net/fullchain.pem
  https_keypairs_reload_interval: 1h

ssh_service:
  enabled: "no"
```

1 Agent :
```
version: v3
teleport:
  data_dir: /var/lib/teleport
  auth_token: tY7g5ntUMVCtCoK289FcKWxVfo5bnwWU
  proxy_server: bastion.mydmain.net:443
  log:
#    output: stderr
    output: stdout
    severity: DEBUG
    format:
      output: text
  diag_addr: ""
auth_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: true
```

Debug logs
-----------

Proxy :
```
DEBU [SSH:PROXY] Incoming connection 10.200.0.2:33184 -> 10.200.0.5:3024 version: SSH-2.0-Go, certtype: "host" pid:100213
.1 sshutils/server.go:509
DEBU [SSH:PROXY] Closed connection 10.200.0.2:33184. pid:100213.1 sshutils/server.go:514
```
Agent :
```
DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:323
DEBU [PROXY:AGE] Starting agent {bastion.mydomain.net:3024 tcp } leaseID:3 target:bastion.mydomain.net:3024 cluster:bastion.mydomain.net reversetunnel/agent.go:293
DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:3 target:bastion.mydomain.net:3024 cluster:bastion.mydomain.net reversetunnel/agent.go:281
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
DEBU [PROXY:AGE] Changing state connecting -> closed. leaseID:3 target:bastion.mydomain.net:3024 cluster:bastion.mydomain.net reversetunnel/agent.go:281
DEBU [PROXY:AGE] Failed to connect agent. error:[
ERROR REPORT:
Original Error: *errors.errorString Failed to claim proxy: [442b7311-d86d-42ce-be96-87df9b4c2e36.bastion.mydomain.net 442b7311-d86d-42ce-be96-87df9b4c2e36 teleport-app-prod-2.bastion.mydomain.net teleport-app-prod-2 localhost 127.0.0.1 ::1 bastion.mydomain.net 10.200.0.6 remote.kube.proxy.teleport.cluster.local] claimed by another agent
Stack Trace:
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:367 github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:313 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:308 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).connectAgent
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:267 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).run
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:251 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).Start.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Failed to claim proxy: [442b7311-d86d-42ce-be96-87df9b4c2e36.bastion.mydomain.net 442b7311-d86d-42ce-be96-87df9b4c2e36 teleport-app-prod-2.bastion.mydomain.net teleport-app-prod-2 localhost 127.0.0.1 ::1 bastion.mydomain.net 10.200.0.6 remote.kube.proxy.teleport.cluster.local] claimed by another agent] cluster:bastion.mydomain.net reversetunnel/agentpool.go:269
DEBU [PROXY:AGE] Active agent count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:450
DEBU [PROXY:AGE] Active agent count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:450
DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:323
```
