### ISSUE TITLE
Verbose error

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2259]
https://gravitational.zendesk.com/agent/tickets/353

The role:

```
kind: "role"
version: "v3"
metadata:
  name: "ssh_user"
spec:
  options:
    max_session_ttl: "10h0m0s"
    port_forwarding: true
    forward_agent: true
  allow:
    logins: [ '{{external.nickname}}' ]
    node_labels:
      '*': '*'
```

Produces many error log entries when users log in and use web UI:

```
core@zzz ~ $ docker logs -f 5ff8363ef021 --tail=10
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
ERRO             Unable to poll for events: access denied to perform action "read" on "session". web/terminal.go:351
```
