### ISSUE TITLE
Cloud customers should get stable/cloud releases in Teleport Discover

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22731]
All Cloud tenants who sign up after we roll out automatic upgrades will need to be served install scripts that use `stable/cloud` channel to install Teleport.

To achieve that, let's introduce an environment variable that the Cloud team will set for all new tenants who will be enrolled in automatic upgrades:

```
TELEPORT_AUTOMATIC_UPGRADES=yes
```

When this variable is set on the auth server, let's make sure that:

- [ ] It is returned as part of the auth server's [PingResponse](https://github.com/gravitational/teleport/blob/master/api/proto/teleport/legacy/client/proto/authservice.proto#L535-L554) (e.g. under `ServerFeatures.AutomaticUpgrades`).
- [ ] It is propagated to proxy's [PingResponse](https://github.com/gravitational/teleport/blob/master/api/client/webclient/webclient.go#L277-L290) as well.
- [ ] All agent install scripts in Teleport Discover flows use `stable/cloud` deb/rpm channel.
- [ ] Helm chart flow in Teleport Discover shows command that enables auto-upgrades as well.
  - the chart must have the following values
    ```yaml
    updater:
        enabled: true
        releaseChannel: "stable/cloud"
    highAvailability:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
     ```
   - the helm command line must set the version based on the auth version or a curl subcommand
     ```
     helm install --version 12.1.2
     # or
     helm install -- version "$([curl https://updates.gravitational.io/stable/cloud/version)"
     ```
   - the values MUST NOT contain `teleportVersionOverride` (and this is also true for non-automatic-upgrade clusters, we must use `--version` instead, else we'll end up with compatibility issues)
    

- [ ] EC2 auto-discovery script uses `stable/cloud` deb/rpm channel as well.
