### ISSUE TITLE
SCP event log is not uploaded on Dynamo

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2284]
**What happened**:
When storing audit logs in dynamodb, [the ssh event 'scp'](https://gravitational.com/teleport/docs/admin-guide/#ssh-events) is not uploaded at designated table.

**What you expected to happen**:
Seeing scp event in dynamo-db table

**How to reproduce it (as minimally and precisely as possible)**:
- Use following teleport config

```
teleport:
  nodename: ip-xxx-xxx-xxx-xxx.ap-northeast-1.compute.internal
  public_addr: xxx.xxx.xxx.xxx
  data_dir: /var/lib/teleport
  log:
    output: syslog
    severity: INFO
  storage:
   type: dynamodb
   region: ap-northeast-1
   table_name: sandbox-auth-backend
   audit_table_name: sandbox-events
   audit_sessions_uri: s3://recorded-sessions-sandbox/records
```

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v2.7.4 git:v2.7.4-0-g2fff1056
- Tsh version (use `tsh version`): Teleport v2.7.4 git:v2.7.4-0-g2fff1056
- OS (e.g. from /etc/os-release):Amazon Linux2

**Browser environment**

- Browser Version (for UI-related issues): na
- Install tools: na
- Others: na

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug
