### ISSUE TITLE
How to use about HA?

### ISSUE THREAD

**Issue by wllenyj** [gravitational/teleport#2298]
**What happened**:
I run two instances of Teleport Auth Server.
When I kill the one of them,  Web login show me “dial tcp 1.1.1.1:5000: connect: connection refused".
How to use about High Availability.
Please help me!

**Configuration**:
``` yaml
teleport:
  nodename: xxx-proxy
  auth_token: hello
  auth_servers: ["1.1.1.1:5000", "2.2.2.2:5000"]
  data_dir: ./data
proxy_service:
  enabled: "yes"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
```

**Environment**:
Teleport v3.0.0-rc.5 git:v3.0.0-rc.5-0-ga772718a-dirty
Centos 7.2
