### ISSUE TITLE
(docs) FIDO-U2F section needs an example

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2309]
Since U2F requires a dedicated `u2f` configuration section in the teleport config, [our docs](https://gravitational.com/teleport/docs/admin-guide/#local-connector) should provide an example of a valid U2F setup (like below) and `teleport` should throw an error if `u2f` section is missing. Right now we have none of it which leads to confusion https://github.com/gravitational/teleport/issues/2281 

```
        second_factor: u2f
        u2f:
            app_id: https://localhost:3080
            facets:
            - https://localhost:3080
```
