### ISSUE TITLE
u2f behind load balancer

### ISSUE THREAD

**Issue by asgoel** [gravitational/teleport#2323]
**What happened**:

I'm having trouble setting up U2F 2FA with teleport proxies behind an AWS load balancer. In my setup, I have two proxies each referenced by a private DNS, so `teleport001.internal.example.com` and `teleport002.internal.example.com`. I have a public address for the load balancer (`teleport.example.com`). The proxies also separately host the `appID` file @ `https://teleport.example.com/appID`.

Here is my config for the auth server:

```
auth_service:
  enabled: "yes"
  authentication:
    type: local
    second_factor: u2f
    u2f:
      app_id: https://teleport.example.com/appID

      # facets should list all proxy servers.
      facets:
        - https://teleport001.internal.example.com:3080
        - https://teleport002.internal.example.com:3080
  listen_addr: 0.0.0.0:3025

  tokens:
    - "proxy,node:<token1>"
    - "node:<token2>"

  cluster_name: "main"
```

And my appID file:

```
{
    "trustedFacets" : [{
        "version": { "major": 1, "minor" : 0 },
        "ids": [
            "https//teleport001.internal.example.com:3080",
            "https//teleport002.internal.example.com:3080",
        ]
    }]
}
```

When I add a user via `tctl` on the auth server, I get a URL @ https://teleport.example.com:3080/web/newuser/<token here>

but when trying to set up U2F, I see this error:

```
Please check your U2F settings, make sure it is plugged in and you are using the supported browser.
U2F error: BAD_REQUEST
```

I'm guessing I'm doing something wrong with how I've set up the hostnames on the proxies and/or the facets, but I'm struggling to determine what. Any ideas much appreciated!

EDIT: Forgot teleport version
**Environment:**

Teleport version (use teleport version): 3.0.1
