### ISSUE TITLE
Machine ID: Azure joining docs

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#23308]
## Details

We should either provide a full tutorial, similar to that for GitHub or GitLab - or just provide a short example for people to leverage before we have time to produce one.

## Related Issues

Implementation PR: https://github.com/gravitational/teleport/pull/23112

**Comment by strideynet** [comment]
Example join token

```yaml
kind: token
version: v2
metadata:
  name: azure-bot
spec:
  roles: [Bot]
  join_method: azure
  bot_name: azure-demo
  azure:
    allow:
      - subscription: 06xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxf2b5
        resource_groups: ["my-resource-group"]
```
