### ISSUE TITLE
MySQL tsh db env command with TLS Routing mode enabled.

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#23364]
Expected behavior:
If TLS Routing is enabled and teleport proxy is configured with a separate  MySQL listener (`proxy_service.mysql_listen_addr != ""`) 
The `tsh db env` and `tsh db config` commands should be supported.

Current behavior:
```
> tsh db env --db mysqldb
ERROR: "tsh db env" is not supported when:
  - database protocol is MySQL and cluster teleport.example.com proxy is using TLS routing.
```

where if a proxy runs on `proxy_service.mysql_listen_addr != ""` the direct connection to `mysql_listen_addr` via external tools is still supported and the TSH local proxy forwarding is not required to connect to MySQL instance. 

Related: 
https://github.com/gravitational/teleport/issues/16209

**Comment by GavinFrazar** [comment]
Just want to clarify something I noticed while working on this:

If `postgres_listen_addr != ""` and `postgres_public_addr == ""`, the proxy will advertise `postgres_public_addr: "<proxy-hostname>:<postgres_listen_addr-port>`.
https://github.com/gravitational/teleport/blob/4d3145b5bff2352bcc1449f2a6e2aa369b08b3ac/lib/service/proxy_settings.go#L133-L156

However, the same is not true for mysql. If `mysql_listen_addr != ""` and `mysql_public_addr == ""`, we don't advertise `mysql_public_addr`.

The postgres settings I linked above is consistent with our documentation, yet has a `DELETE IN V9` comment.
Mysql settings are not consistent with our docs.
See:
```yaml
  # By default database clients will be connecting to the Proxy over this
  # hostname. To override public address for specific database protocols
  # use postgres_public_addr and mysql_public_addr.
  public_addr: "teleport.example.com:3080"
  # Address advertised to MySQL clients. If not set, public_addr is used.
  mysql_public_addr: "mysql.teleport.example.com:3306"
  # Address advertised to PostgreSQL clients. If not set, public_addr is used. <- (my comment): we claim public_addr will be used, but that's not what the proxy advertises for mysql.
  postgres_public_addr: "postgres.teleport.example.com:443"
```

For both mysql and postgres, the proxy advertises listen_addr as the web port if TLS routing is enabled:
https://github.com/gravitational/teleport/blob/4d3145b5bff2352bcc1449f2a6e2aa369b08b3ac/lib/service/proxy_settings.go#L100-L106

So in order to use the separate mysql listener port, the user must set `mysql_public_addr`.
