### ISSUE TITLE
Teleport add kubernetes_resources in allow section automatically without my decision about it

### ISSUE THREAD

**Issue by 0hn0hn0** [gravitational/teleport#23420]
In [documentation](https://goteleport.com/docs/access-controls/reference/#roles) there is "full role specification" with next comment in it:
```
# The allow section declares a list of resource/verb combinations that are
# allowed for the users of this role. By default, nothing is allowed.
```

**Expected behavior:**
In case of creating new simple role for only ssh Teleport will not add kubernetes_resources in allow section by itself.

**Current behavior:**
In case of creating new simple role for only ssh Teleport add kubernetes_resources in allow section automatically without my decision about it.

**Bug details:**
- Teleport v12.1.1

Text based yaml:
```
kind: role
version: v5
metadata:
  name: simple_ssh
spec:
  allow:
    logins: ['{{external.username}}','almalinux','centos']
    rules:
      - resources: [session]
        verbs: [list,read]
  options:
    cert_format: standard
    client_idle_timeout: 10m
    create_host_user: false
    desktop_clipboard: false
    desktop_directory_sharing: false
    disconnect_expired_cert: yes
    enhanced_recording:
      - command
      - network
    forward_agent: true
    idp:
      saml:
        enabled: false
    lock: strict
    max_session_ttl: 8h
    pin_source_ip: false
    port_forwarding: false
    record_session:
      default: strict
      desktop: false
    ssh_file_copy: false
```
From WebUI (after `tctl create -f simple_ssh.yaml`):
```
kind: role
metadata:
  id: 102013
  name: simple_ssh
spec:
  allow:
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    logins:
    - '{{external.username}}'
    - almalinux
    - centos
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    client_idle_timeout: 10m0s
    create_host_user: false
    desktop_clipboard: false
    desktop_directory_sharing: false
    disconnect_expired_cert: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: false
    lock: strict
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    port_forwarding: false
    record_session:
      default: strict
      desktop: false
    ssh_file_copy: false
version: v5
```
