### ISSUE TITLE
Enhance tsh login 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#23569]
What would you like Teleport to do?
Open the Web UI and allow me to select an auth method when using `tsh login` with multiple auth providers configured. This is the current behavior when trying to log into the Web UI.

What problem does this solve?
Having to know the auth connector ID when doing `tsh login --auth`. 

If a workaround exists, please include it.

**Comment by Nitive** [comment]
You can set the default auth method in the teleport config

```yaml
auth_service:
  authentication:
    type: oidc
    connector_name: cu
```
