### ISSUE TITLE
Support configuring auth_service.proxy_listener_mode through teleport-generate-configuration

### ISSUE THREAD

**Issue by sklirg** [gravitational/teleport#23570]
### What would you like Teleport to do?

Support setting `auth_service.proxy_listener_mode` when booting from an AWS AMI.

When starting Teleport from an AWS AMI it configures itself using a script [`/usr/local/bin/teleport-generate-config`](https://github.com/gravitational/teleport/blob/v12.1.0/assets/aws/files/bin/teleport-generate-config). This script does not support configuring `auth_service.proxy_listener_mode` which means that if the `proxy_service` is configured to run in multiplex mode, clients are unable to authenticate using `tsh`. It is possible to configure `proxy_service` to multiplex connections through the same script if the tunnel and web listeners are set to the same port ([src](https://github.com/gravitational/teleport/blob/v12.1.0/assets/aws/files/bin/teleport-generate-config#L181-L183)), which results in a kind-of broken Teleport installation.

### What problem does this solve?

If starting the proxy_service in multiplex mode, it is not possible to `tsh login` because the auth_service informs the client to log in against another port than the one configured for multiplexing:

```
❯ tsh login --verbose --proxy=teleport.lab.example.com:443 --user teleport-admin
Enter password for Teleport user teleport-admin:
Enter your OTP token:
ERROR: Unable to connect to ssh proxy at teleport.lab.example.com:3023. Confirm connectivity and availability.
dial tcp 16.16.x.x:3023: connect: operation timed out
```

proxy_service config:
```yaml
proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3080
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.lab.example.com:443
  ssh_public_addr: teleport.lab.example.com3023
  tunnel_public_addr: teleport.lab.example.com:443
  https_keypairs:
    - cert_file: /var/lib/teleport/fullchain.pem
      key_file: /var/lib/teleport/privkey.pem
  kubernetes:
    enabled: yes
    listen_addr: 0.0.0.0:3026
    public_addr: ['teleport.lab.example.com:3026']
```

auth_service config:
```yaml
auth_service:
  enabled: yes
  public_addr: teleport-lab-auth-foo.elb.aws-region-0.amazonaws.com:3025
  keep_alive_interval: 1m
  keep_alive_count_max: 3
  listen_addr: 0.0.0.0:3025
  authentication:
    second_factor: otp
  cluster_name: teleport-lab
```

### If a workaround exists, please include it.

Manually setting the configuration option in `/etc/teleport.yaml` on the auth_service nodes works.

```
cat <<EOF >> /etc/teleport.yaml
  proxy_listener_mode: multiplex
EOF
systemctl restart teleport-auth
```

```
❯ tsh login --verbose --proxy=teleport.lab.example.com:443 --user teleport-admin
Enter password for Teleport user teleport-admin:
Enter your OTP token:
> Profile URL:        https://teleport.lab.example.com:443
  Logged in as:       teleport-admin
  Cluster:            teleport-lab
  Roles:              access, editor
  Logins:             ec2-user, root, -teleport-internal-join
  Kubernetes:         enabled
  Valid until:        2023-03-25 05:09:11 +0100 CET [valid for 12h0m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy
```

However, this is not easy to automate (if at all?) with the current tools as `/etc/teleport.yaml` is generated after the AWS userdata-script is ran, and if it is present beforehand the full `teleport-generate-config`-script is skipped, which means that it won't read the dynamically configured parameters set in the reference Terraform configuration.

### Related issue(s):

* https://github.com/gravitational/teleport/issues/16684

Resolving this issue partially implements #16684 by providing the appropriate configuration (generation) changes required to support configuring auth_service with proxy_service working in multiplex mode (wow, that was ... a sentence). Following this implementation, the Terraform configuration can implement conditionals for provisioning "the OG separate ports mode" or multiplexing.
