### ISSUE TITLE
teleport-cluster Helm Chart service account bug

### ISSUE THREAD

**Issue by nathan-bowman** [gravitational/teleport#23646]
EKS Config:
```
...
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: teleport-serviceaccount
      namespace: teleport-cluster
    roleName: teleport-serviceaccount
    attachPolicyARNs:
    - "arn:aws:iam::############:policy/ExternalSecretsPolicy-Teleport"
    - "arn:aws:iam::############:policy/TeleportDBPolicy"
    - "arn:aws:iam::############:policy/TeleportS3Policy"
...
```

```
root@test-kube:~# kubectl -n teleport-cluster describe serviceaccounts teleport-serviceaccount
Name:                teleport-serviceaccount
Namespace:           teleport-cluster
Labels:              app.kubernetes.io/managed-by=eksctl
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::############:role/teleport-serviceaccount
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

Expected behavior:

This setting in Helm values.yaml should result with Teleport installing and running happily against the service account:
```
serviceAccount:
  create: false
  name: teleport-serviceaccount
```

Current behavior:

Apparently Teleport wants two service accounts, one for each auth and proxy, but the Helm values.yaml only allows you to set one; and then uses `_helper.tpl` to create the separate service accounts. 

Ref `_helpers.tpl`:
```
{{- define "teleport-cluster.auth.serviceAccountName" -}}
{{- coalesce .Values.serviceAccount.name .Release.Name -}}
{{- end -}}

{{- define "teleport-cluster.proxy.serviceAccountName" -}}
{{- coalesce .Values.serviceAccount.name .Release.Name -}}-proxy
{{- end -}}
```

However, if you set `serviceAccount.create: false` because you manage the account via OIDC on AWS, the second service account for proxy is never created.

When I deploy the Helm chart `teleport-cluster`, my proxy replicaset shows:
```
pods "teleport-cluster-proxy-5f77ff886f-" is forbidden: error looking up service account teleport-cluster/teleport-serviceaccount-proxy: serviceaccount "teleport-serviceaccount-proxy" not found
```

I can overcome this by overriding the `_helper.tpl` template to point to the Helm value's `serviceAccount.name`:
```
{{- define "teleport-cluster.proxy.serviceAccountName" -}}
{{- coalesce .Values.serviceAccount.name .Release.Name -}}
{{- end -}}
```

But, my thought is that this might introduce an unnecessary security risk. 

Bug details:
- Teleport version: v12.1.2
- Recreation steps
- Debug logs

**Comment by webvictim** [comment]
Try adding this to your values, and see if it resolves the issue?

```yaml
auth:
  serviceAccount:
    create: false
    name: teleport-serviceaccount
proxy:
  serviceAccount:
    create: false
    name: teleport-serviceaccount
```
