### ISSUE TITLE
Proxy service UI config documentation appears to be inaccurate.

### ISSUE THREAD

**Issue by kraker** [gravitational/teleport#23667]
## Applies To

https://goteleport.com/docs/reference/config/#proxy-service

## Details

The following block in the example config appears to be inaccurate:

```yml
    # Configuration options for the Web UI served by the Proxy Service.
    ui_config:
      # The amount of scrollback in the terminal. Scrollback is the amount of
      # rows that are retained when lines are scrolled beyond the initial
      # viewport. Does not apply to session recording view.
      scrollback_length: 1000
```

This fails config tests with `teleport configure --test test-teleport.yaml`

```bash
labelakb01:~ # teleport configure --test test-teleport.yaml 
FAIL test-teleport.yaml
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 53: field ui_config not found in type config.Proxy
```

Example `test-teleport.yml` file:

```yml
---
# /etc/teleport.yaml

version: v3
teleport:
  nodename: labelakb01
  data_dir: /var/lib/teleport
  join_params:
    method: token
    token_name: <redacted>
  diag_addr: ""
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: "yes"
  cluster_name: labeltel01.nimbl.lab
  authentication:
    type: local
    second_factor: otp
    connector_name: local
  listen_addr: 0.0.0.0:3025
  session_recording: node
  client_idle_timeout: 4h
  client_idle_timeout_message: "Your Teleport session has timed out due to inactivity and you've been disconnected."
  web_idle_timeout: 15m
  proxy_listener_mode: multiplex
  tunnel_strategy:
    type: agent_mesh
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
  permit_user_env: false
  disable_create_host_user: false
  port_forwarding: true
  ssh_file_copy: true
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: labeltel01.nimbl.lab:443
  https_keypairs:
    - key_file: /var/lib/teleport/labeltel01.key
      cert_file: /var/lib/teleport/labeltel01.cert
  https_keypairs_reload_interval: 0s
  ui_config:
    scrollback_length: 10000
```

Review of the [source code](https://github.com/gravitational/teleport/blob/master/lib/config/fileconf.go) revealed that the following config is correct:

```yml
  ui:
    scrollback_lines: 10000
```

If this change is made in the `test-teleport.yaml` above example it passes:

```bash
labelakb01:~ # teleport configure --test test-teleport.yaml 
OK test-teleport.yaml
```

So either the documentation needs to be updated, or perhaps this is a bug in the code if it really is supposed to be as the docs say. 

## Related Issues

I wasn't able to find any related issues.

**Comment by zmb3** [comment]
Thanks for the report, it is just a docs bug, `ui` is what we intended here. Will have a docs fix out shortly.

**Comment by kraker** [comment]
The updated documentation still fails. The docs now have:

```yml
    # Configuration options for the Web UI served by the Proxy Service.
    ui:
      # The amount of scrollback in the terminal. Scrollback is the amount of
      # rows that are retained when lines are scrolled beyond the initial
      # viewport. Does not apply to session recording view.
      scrollback_length: 1000
```

Per my suggested changes above it needs to have `scrollback_lines` not `scrollback_length`.

See:
```bash
labelakb01:~ # teleport configure --test test-teleport.yaml 
FAIL test-teleport.yaml
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 54: field scrollback_length not found in type config.UIConfig
labelakb01:~ # grep -B1 scrollback_ test-teleport.yaml 
  ui:
    scrollback_length: 10000
labelakb01:~ # sed -i 's/scrollback_length/scrollback_lines/g' test-teleport.yaml 
labelakb01:~ # grep -B1 scrollback_ test-teleport.yaml 
  ui:
    scrollback_lines: 10000
labelakb01:~ # teleport configure --test test-teleport.yaml 
OK test-teleport.yaml
```
