### ISSUE TITLE
EKS auto-discovery removes eks cluster kubeconfig which doesn't match with labels

### ISSUE THREAD

**Issue by rahulinux** [gravitational/teleport#23699]
Expected behavior:

Running two discovery service and one per account to dynamically add EKS clusters. 

Account A:

```
    discovery_service:
      aws:
      - regions:
        - us-east-2
        tags:
          environment: "account-a"
        types:
        - eks
        - ec2
      enabled: "yes"
```

Account B:

```
    discovery_service:
      aws:
      - regions:
        - us-east-2
        tags:
          environment: "account-b"
        types:
        - eks
        - ec2
      enabled: "yes"
```

Discovery_service from Account A should only manage eks cluster with respective tags and should not remove other EKS clusters.

OR, one discovery service should support multiple aws accounts. 

Current behavior:

Discovery_service from Account A removes eks cluster added by discovery_service from Account B and vise versa. 

Bug details:
- Teleport version: `12.1.1`
- Recreation steps: 
   - Try to add EKS Cluster from multiple aws accounts 

- Debug logs

````
teleport-discovery-0 teleport 2023-03-28T16:03:11Z INFO [DISCOVERY] kube_cluster account-b-us-east-2 removed, deleting. kind:kube_cluster pid:7.1 services/reconciler.go:132
teleport-discovery-0 teleport 2023-03-28T16:03:11Z INFO [DISCOVERY] kube_cluster account-a-us-east-2 matches, creating. kind:kube_cluster pid:7.1 services/reconciler.go:148

````
