### ISSUE TITLE
[FR] Custom Credential Provider for Teleport DB Service

### ISSUE THREAD

**Issue by alexatcanva** [gravitational/teleport#23748]
## Background

When Implementing Teleport as a Identity-and-protocol-aware database proxy I have found Teleport to be very opinionated in regards to how Teleport establishes a connection to the database target. One of these opinions is the database credentials used. 

Teleport *strongly prefers* to avoid using usernames and passwords, and/or API keys/tokens to connect to resources, unfortunately however not all database implementations facilitate password-less authentication just yet. 

An example of this is Teleport's method of connecting to MongoDB. At the moment Teleport only supports connecting to MongoDB using x509 certificates. However MongoDB Atlas can also be connected via SCRAM, or AWS IAM, where as AsparaDB MongoDB can only be connected to via [username and password](https://www.alibabacloud.com/help/en/apsaradb-for-mongodb/latest/access-control). 

## What would you like Teleport to do?

In order to avoid users having to wait for development cycles to implement workarounds, or additional authentication protocols with a given data store, it would be great if Teleport was able to "call out" to an external credential provider plugin which can provide authentication method information, and (if successfully authorized) credentials to connect to a database. 

### How could I see this working? 

Without being an expert on the internals of Teleport, I think it would be nice to be able to define the structure of the credential provider in the Teleport DB Service config, with something like:

```yaml
version: v2
// teleport config ...

db_service:
  enabled: yes
  credential_plugin:
    kind: http
    endpoint: "https://foo-bar.com/teleport-credentials" 
    auth: iam
    database_types: ["mongodb", "..."]
...

// and/or alternatively

db_service:
  enabled: yes
  credential_plugin:
    kind: exec
    cmd: ["/usr/local/bin/my-plugin", "arg1", "arg2", ...]
    env: {...}
    database_types: ["mongodb", "..."]
...

// and/or alternatively again

db_service:
  enabled: yes
  credential_plugin:
    kind: "grpc"
    endpoint: "https://foo-bar.com/ 
    auth: iam
    database_types: ["mongodb", "..."]
...

```

Ideally, an `exec` option would be the _minimum_ option as it provides the maximum level of flexibility to the system owner. 
Upon a user's successful authorization challenge, we should be able to send a request to the credential plugin (if configured) and receive a response with something akin to:

```go
// Request to Plugin
type DbCredentialPluginRequest struct {
	// The URI for the Database we need credentials for
	DatabaseUri string
	// The user we want to authenticate as (readonly, write, admin, etc.)
	DatabaseUser string
	// The "kind" of database, MongoDB, RDS MySQL, etc
	DatabaseKind DbKind
}

// Response from Plugin
type DbCredentialPluginResponse struct {
	// The Authentication Mechanism we will use, SCRAM, Username/Password, Certificate, IAM, other..
	DatabaseAuthenticationMechanism
	// The credentials we will use
	Credentials DatabaseCredentials
}
```
An example flow of this type of implementation might look like this:

```mermaid
flowchart TB
    User --> Proxy(Teleport Proxy)
    Proxy --> DB(DB Service)
    subgraph Assumed AuthZ Granted
        DB -->|1. Credential Request| CredProvider
        CredProvider -->|2. Credential Response| DB
    end
    DB -->|Connect With Creds| Target((Resource Target))
```

### Additional Considerations

Obviously, this would put the onus on the user to be somehow managing their own database credentials in _some way_ themselves. With this in mind, this feature should really be only targeted towards advanced users who are comfortable with maintaining their own credential provider, and ideally have their own security practices to facilitate using an external credential provider like this.

## What problem does this solve?

Teleport has very opinionated methods for connecting to databases, in rapidly evolving environments these methods of connecting to databases may not be suitable for the user, and as such the user may have to forego the benefits of using Teleport to support their infrastructure. By providing a credential provider plugin, the user can provide Teleport with the means to connect to databases in ways it can't OOTB. 

## If a workaround exists, please include it.

If you're handy enough with GoLang and happy to maintain your own branch/fork then there's always a work around ;)
