### ISSUE TITLE
Don't ask for an auth connector name when there is only 1 auth connector configured

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#23914]
What would you like Teleport to do?
1. when connecting using the CLI, if only one connector is defined and local login is disabled. There should be no need to specify it using --auth .
```
# tsh login --proxy=cluster.example.com:3080
ERROR: unsupported authentication type: ""

# tsh version
Teleport v12.0.4 git:api/v12.0.4-0-gcf72ee5d59 go1.20.1

Cluster version is also v12
```
```
# tctl get cap
kind: cluster_auth_preference
metadata:
  labels:
    teleport.dev/origin: config-file
  name: cluster-auth-preference
spec:
  allow_local_auth: false
  allow_passwordless: false
  connector_name: saml
  device_trust:
    mode: optional
  disconnect_expired_cert: true
  idp:
    saml:
      enabled: true
  locking_mode: strict
  message_of_the_day: Teleport cluster
  second_factor: "off"
  type: saml
version: v2
```
2. Provide a way to make a auth connector the default connector so that's used when nothing is specified

What problem does this solve?
Removes the need for user side changes and "pre-knowledge" when connecting to a new cluster 

Potential solutions:

If a workaround exists, please include it.

Using the config file. but this is user side setting and not cluster side setting. It's better to give control to cluster admins control to handle this
