### ISSUE TITLE
[Login Rules] Ability to split a single-valued trait into a multi-valued trait

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#23921]
## What problem does this solve?

Some IDPs do not allow admins to configure multi-valued claims, so there is not a good way to put e.g. user logins in a claim like `"logins": ["user", "ubuntu", "root"]`

## What would you like Teleport to do?

It would be useful if Login Rules could support splitting a comma-separated single-valued claim into a multi-valued claim so that the admin can configure multiple values and they can be easily used in role templates.

Example:

Claim from IDP:
```json
{
  "logins": ["alice,ubuntu,root"],
  "username": ["alice"],
}
```

Login Rule:
```yaml
kind: login_rule
version: v1
metadata:
  name: split-logins
spec:
  priority: 0
  traits_expression: external.put("logins", strings.split(external.logins, ","))
```

Final Teleport user traits:
```json
{
  "logins": ["alice", "ubuntu", "root"],
  "username": ["alice"],
}
```

Role template:
```yaml
kind: role
version: v6
metadata:
  name: node-access
spec:
  allow:
    node_labels:
      '*': '*'
    logins: ['{{external.logins}}']
```

## If a workaround exists, please include it

A messy workaround is to use a separate trait for each login, eg:

Claims from IDP:
```json
{
  "login1": ["alice"],
  "login2": ["ubuntu"],
  "login3": ["root"],
  "username": ["alice"],
}
```

Role template:
```yaml
kind: role
version: v6
metadata:
  name: node-access
spec:
  allow:
    node_labels:
      '*': '*'
    logins:
      - '{{external.login1}}'
      - '{{external.login2}}'
      - '{{external.login3}}'
```
