### ISSUE TITLE
ssh to wrong node

### ISSUE THREAD

**Issue by wllenyj** [gravitational/teleport#2396]
**What happened**:
When i click the root button from web, ssh to wrong node. ifconfig display the different ip to the Address of web. And it is always ssh to the same wrong node. 

**What you expected to happen**:
SSH to right node.

**How to reproduce it (as minimally and precisely as possible)**:
The Hostname of the wrong node  is the same of all. And Tips：'abrt-cli status' timed out

**Environment**:
- Teleport version (use `teleport version`): v3.0.1
- Tsh version (use `tsh version`): v3.0.1
- OS (e.g. from /etc/os-release):Centos 7.2

**Browser environment**
chrome
- Browser Version (for UI-related issues): 70.0.3538.102
- Install tools: 
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
can you add a little more information for us?, for example, tctl get nodes output will be helpful here

**Comment by cove** [comment]
I think this is the same issue I ran into from our convo in slack.

It looks like `GuessHostIP()` might be picking up the IPv6 loopback on the node instead of the routable IPv4 address, though there was a fix for this 98be2a5. Since I'm testing the enterprise version I can't tell if that commit is applied and I haven't tested the OSS version. Here's how one of my nodes (the auth server shows up):

```
[root@auth ~]# tctl get nodes
- kind: node
  metadata:
    expires: 2018-11-30T19:03:26.006715312Z
    name: 4513166f-6a36-443e-bd19-c136950e8d60
  spec:
    addr: '[::1]:3022'
    hostname: auth
    rotation:
      current_id: ""
      grace_period: 0s
      last_rotated: 0001-01-01T00:00:00Z
      schedule:
        standby: 0001-01-01T00:00:00Z
        update_clients: 0001-01-01T00:00:00Z
        update_servers: 0001-01-01T00:00:00Z
      started: 0001-01-01T00:00:00Z
  version: v2
```

Here's what it looks like from the user perspective, where the short node name uses the IPv6 loopback address above and logins into the proxy, and if you use the FQDN is appears to resolve the IPv4 address in DNS and connects to the right node:
```
% tsh ssh root@auth
[root@proxy ~]# logout
the connection was closed on the remote side on  30 Nov 18 11:17 PST
% tsh ssh root@auth.<fqdn>
[root@auth ~]#
```

Secondly the reason that the SSH succeeds is due to `CheckHostSignature()` not validating the Principal.
