### ISSUE TITLE
potential regression in helm chart handling of `proxyListenerMode`

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#24302]
When upgrading from v11 to v12 helm chart (`gcp` mode), a user had their agents lose connectivity. 

After some investigation, it became apparent that the agents were all setup under the assumption that the proxy listener mode was `multiplex` (i.e. TLS routing enabled), but examining the post-upgrade control plane, multiplexing was not enabled in the auth config file.  The user's helm values had `proxyListenerMode: ""`.  Switching this to `multiplex` and redeploying fixed their connectivity issues.

We were unable to examine the actual previous configuration, but the relevant files were all under version control, so the customer is reasonably certain that no configuration was changed on their end.  We should therefore investigate the possibility of a regression in helm chart behavior when proxy listener mode is not specified.

**Comment by webvictim** [comment]
## Differences

Some changes I've noticed between v11 and v12:

`branch/v11`:
- `auth_service.proxy_listener_mode` is **not set** by default, or set to `multiplex` if `proxyListenerMode: multiplex` set in values
- config version is **not set** by default, unless `proxyListenerMode` is set to `multiplex`, in which case it's `version: v2`
- proxy listen addresses are **not set** - only ` kube_listen_addr: 0.0.0.0:3026` is set

`branch/v12`:
- `auth_service.proxy_listener_mode` is **always** set; to `separate` by default, or `multiplex` if `proxyListenerMode: multiplex` is set in values
- config version is **always** `version: v3`
- when `proxyListenerMode: separate`, the following proxy listen addresses are **explicitly set**:
```yaml
proxy_service:
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
```

## Theory/configs

This probably comes down to a difference between how the following two configs are handled:

`branch/v11` default proxy config:
```yaml
proxy_service:
  enabled: true
  kube_listen_addr: 0.0.0.0:3026
```

This defaults to `version: v1` and should enable separate listeners by default as part of that.

`branch/v12` default proxy config:
```yaml
version: v3
proxy_service:
  enabled: true
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
```

It seems that setting a newer config version by default and manually specifying the listener addresses may result in slightly different behaviour to the previous v11 default.
