### ISSUE TITLE
Configuration section missing parts

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2447]
## Description

Configuration section https://gravitational.com/teleport/docs/admin-guide/#configuration-file is missing new fields, here are some of them:

```
proxy_service:
    ssh_public_addr:
    # the whole kuberentes section is missing
    kubernetes:   
        enabled: no
    proxy_protocol: disabled
```
There are also a couple of typos here and there:

* `'proxy servie'`
* `locataed`
