### ISSUE TITLE
Discovery bootstrapping installation script URL is invalid. 

### ISSUE THREAD

**Issue by WillBartee** [gravitational/teleport#24488]
### Expected behavior:

The AWS SSM Document created when using the command `teleport discovery bootstrap` includes the correct URL for downloading the `installTeleport.sh` script.

```yaml
...
- action: aws:downloadContent
  name: downloadContent
  inputs:
    sourceType: "HTTP"
    destinationPath: "/tmp/installTeleport.sh"
    sourceInfo:
      url: "https://teleport.example.com:443/webapi/scripts/installer/{{ scriptName }}"
- action: aws:runShellScript
...
```

### Current behavior:

The AWS SSM Document includes an invalid URL for the script download.
```yaml
...
- action: aws:downloadContent
  name: downloadContent
  inputs:
    sourceType: "HTTP"
    destinationPath: "/tmp/installTeleport.sh"
    sourceInfo:
      url: "https://<proxy address>:3080/webapi/scripts/installer/{{ scriptName }}"
- action: aws:runShellScript
...
```

### Bug details:
- Teleport version
  ```bash
  $ teleport version
  Teleport Enterprise v12.1.5 git:api/v12.1.5-0-g54e910b019 go1.20.2
  ```
- Recreation steps
  1. Create a `teleport.yaml`
    ```yaml
	version: v3
	teleport:
	  join_params:
	    method: token
	    token_name: /tmp/token
	  proxy_server: teleport.example.com:443
	discovery_service:
	  aws:
	  - regions:
	    - us-east-1
	    tags:
	      env: prod
	    types:
	    - ec2
	  enabled: true
	app_service:
	  enabled: false
	auth_service:
	  enabled: false
	db_service:
	  enabled: false
	kubernetes_service:
	  enabled: false
	proxy_service:
	  enabled: false
	ssh_service:
	  enabled: false
    ```
  2. Authenticate with AWS
  3. Run command `teleport discovery bootstrap -c ./teleport.yaml`
  4. Review output. Shows invalid URL
  5. Confirm to apply to AWS.
  6. Review AWS SSM Document content.
    - https://us-east-1.console.aws.amazon.com/systems-manager/documents/TeleportDiscoveryInstaller/content
- Debug logs
  - None

**Comment by r0mant** [comment]
@WillBartee Looks like the command expects the proxy address to be set in `proxy_service.public_addr` and just falls back to `<proxy address>` placeholder if it's not set.

As a workaround, I think you should be able to update your discovery service config to set the public address while still keeping it disabled, just to appease the command:

```yaml
proxy_service:
  enabled: false
  public_addr:
  - teleport.example.com:443
```

And we will update the command to also consider `teleport.proxy_server` field when trying to determine the proxy address.

cc @lxea
