### ISSUE TITLE
Multiple discovery services remove each other's resources

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24585]
If you run 2 discovery services each discovering their own set of resources (e.g. EKS clusters):

```yaml
discovery_service:
  enabled: "yes"
  aws:
   - types: ["eks"]
     regions: ["us-east-2", "us-west-2"]
     tags:
       "AwsAccount": "development"
kubernetes_service:
  enabled: "yes"
  resources:
  - labels:
      "AwsAccount": "development"
```

```yaml
discovery_service:
  enabled: "yes"
  aws:
   - types: ["eks"]
     regions: ["us-east-2", "us-west-2"]
     tags:
       "AwsAccount": "staging"
kubernetes_service:
  enabled: "yes"
  resources:
  - labels:
      "AwsAccount": "staging"
```

They will fight each other and discovery service A will remove Kube clusters discovered by discovery service B because they don't match and reconciler always fetches all clusters and doesn't take into account labels matching its own discovery service labels:

https://github.com/gravitational/teleport/blob/master/lib/srv/discovery/kube_watcher.go#L43

I suspect this is the case for other resources as well e.g. databases.
