### ISSUE TITLE
[v.12.x] /docs/pages/access-controls/reference.mdx

### ISSUE THREAD

**Issue by janconj** [gravitational/teleport#25026]
## Applies To
https://goteleport.com/docs/access-controls/reference/

## Details
The part with `claims_to_roles` is confusing:

```yaml
      # the `claims_to_roles` mapping works the same as it does in
      # the OIDC connector, with the added benefit that the roles being mapped to
      # can also be matchers. the below mapping says that users with
      # the claims `groups: admins` can request any role in the system.
      claims_to_roles:
        - claim: 'projects'
          # matches all group names with a leading 'product-'
          value: '^product-(.*)$'
          # generates a role name from the value capture
          roles: ['$1-admin']
```

Description mentions `groups:admins` and any role, the code refers to `projects:product-*` and `*-admin` role.
