### ISSUE TITLE
Wrong port for GKE API server

### ISSUE THREAD

**Issue by madsonic** [gravitational/teleport#2512]
**What happened**:
After setting up kubernetes integration for GKE, called `kubectl get pods`. Received connection timeout

**What you expected to happen**:
Connection should not time out and return the results of kubectl command. teleport should configure kubeconfig to use the correct port for k8 API server instead of `3026`

**How to reproduce it (as minimally and precisely as possible)**:
```
# on proxy host
proxy_service:
...
  kubernetes:
    enabled: yes
    public_addr: [proxy.teleport.com:3026]
    listen_address: 0.0.0.0:3026

# on auth host
auth_service:
  kubeconfig_file: /path/to/kubeconfig
```

**Environment**:
- Teleport version (use `teleport version`): `Teleport v3.1.4 git:v3.1.4-0-g9b7b5b8b go1.11.4`
- Tsh version (use `tsh version`): `Teleport v3.1.4 git:v3.1.4-0-g9b7b5b8b go1.11.4`
- OS (e.g. from /etc/os-release): `Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64`

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

```
kubectl config view

clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://x.x.x.x:3026 # -----> should be 443 or empty
  name: x.x.x.x
```

After manually editing the kubeconfig to remove `3026` in the `server` value
`kubectl get pods --v=10` return `200` though I ran in other problems which I believe is unrelated

Running `nc` against the k8 API server with `3026` was also a `operation time out` while `443` is ok

[The typical port should be 443](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#transport-security)

**Comment by madsonic** [comment]
I believe the bug is [here](https://github.com/gravitational/teleport/blob/2003ceaa0bfcfd9bb7278fdbc53e2713b0c51069/lib/kube/client/kubeclient.go#L25)

The k8 proxy listening port is duplicated over to the kubeconfig

**Comment by klizhentas** [comment]
That's by design. You can set up the port by using `public_addr` section in the kubernetes section of the teleport proxy to set it to whatever you seem reasonable. By default it's the listening address of the proxy.

**Comment by madsonic** [comment]
I have updated my proxy config but after `tsh login` I am still getting the same kubeconfig as before. 
After the config update, I did the following:
1.  restarted proxy server, auth server
2. cleared the kubeconfig sections `tsh` has created
3. `tsh login`
4. `tsh ls` just to make sure I am correctly connected
5. `kubectl config view` 

PS: `tsh logout` doesn't seem to clear the generated kubeconfig sections. 

```
# updated config
proxy_service:
...
  kubernetes:
    enabled: yes
    public_addr: ["proxy.teleport.com:443"] <----- set to API server port
    listen_address: 0.0.0.0:3026
```
