### ISSUE TITLE
Display role request annotations in the corresponding Access Request Created Audit Log 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#25212]
What would you like Teleport to do?
Customer has asked that annotations specified in role definition be present in the audit log details of the corresponding access request. We do not currently provide that information in the audit log. Example below. This should be available in the Teleport UI and with tsh/tctl request commands. 

Example role definition. 

```
kind: role
metadata:
  description: The role allows admin access to all k8s nodes
  id: <id>
  name: k8s_admin
spec:
  allow:
    request:
      annotations:
        foo:
        - bar
      roles:
      - moderator_required
  deny: {}
  options:
    cert_format: standard
    client_idle_timeout: 15m0s
    create_host_user: false
    desktop_clipboard: false
    desktop_directory_sharing: false
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_connections: 3
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    port_forwarding: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
```

An access request for the above role is made, below is the corresponding audit log for the Access Request. 

```
{
  "cluster_name": "<tenant>.teleport.sh",
  "code": "T5000I",
  "ei": 0,
  "event": "access_request.create",
  "expires": "2023-04-27T00:47:21.082378846Z",
  "id": "<id>",
  "reason": "test\n",
  "roles": [
    "k8s_admin"
  ],
  "state": "PENDING",
  "time": "2023-04-26T16:47:21.087Z",
  "uid": "<uid>",
  "user": "<user>"
}

```

What problem does this solve?
The justification for annotations to be displayed in the audit logs is for troubleshooting purposes. The business case stated by the customer is that they are developing plugins for Teleport that will be looking for these annotations. 

If a workaround exists, please include it.
The annotations are available in protobuf so they can be programmatically obtained.
