### ISSUE TITLE
Clarify how multiple `app_labels` values work

### ISSUE THREAD

**Issue by janconj** [gravitational/teleport#25587]
## Applies To
https://goteleport.com/docs/application-access/controls/

## Details
Apparently, I can use multiple labels in the allow block:
```
allow:
  app_labels:
    env: "{{external.env}}"
    group: "{{external.group}}"
```

However, the documentation doesn't seem to say whether these labels are combined as OR or AND (i.e., does an allowed app need to satisfy both labels, or just one of them?).
