### ISSUE TITLE
{{internal.logins}} ignored on Teleport Enterprise roles

### ISSUE THREAD

**Issue by lrt512** [gravitational/teleport#2561]
**What happened**:

We're doing a PoC of Teleport Enterprise in k8s without using SSO to start. Every user with the admin role has only the `root` login, even though the role has

```
  logins:
    - '{{internal.logins}}'
    - root
```

Very much an edge case, but entertaining.

**What you expected to happen**:

I was expecting the local user login to be propagated

**How to reproduce it (as minimally and precisely as possible)**:

Just have a role where you have this

```
  logins:
    - '{{internal.logins}}'
    - root
```

In this case, `tsh status` will give only

```
Logins:     root
```

If you omit `root` and only give

```
  logins:
    - '{{internal.logins}}'
```

`tsh login` will return
```
*trace.AccessDeniedError this user cannot create SSH sessions, has no allowed logins
```

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v3.1.5git:v3.1.5-0-g7621bbd5 go1.11.5
- Tsh version (use `tsh version`): Teleport v3.1.5 git:v3.1.5-0-g7621bbd5 go1.11.5
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1

**Comment by klizhentas** [comment]
Hey Larry, thanks for your report. We will look into it.

**Comment by klizhentas** [comment]
And just to clarify, it's stopped working for existing users after upgrade or for new local users? If the latter, how did you add new users?

**Comment by lrt512** [comment]
I'm about to add some context, but all users are on a brand-new enterprise-trial-license deployment via the Helm chart.

Users are created with `tctl users add --roles=admin bob`

**Comment by lrt512** [comment]
A few bits of context. I played with this in several ways:

1) Specifiying the login in the role logins, i.e.

```
# tctl get roles/admin
kind: role
metadata:
  name: admin
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    logins:
    - '{{internal.logins}}'
    - ltremblay
    node_labels:
      '*': '*'
```

A `tsh status` then gives

> Profile URL:  https://teleport...
  Logged in as: ltremblay
  Cluster:      teleport...
  Roles:        admin*
  Logins:       ltremblay
  Valid until:  2019-02-14 02:04:51 -0500 EST [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty

2) Adding the login directly to the user's traits:

```
# tctl get users/ltremblay
kind: user
metadata:
  name: ltremblay
spec:
  created_by:
    time: 0001-01-01T00:00:00Z
    user:
      name: 00b119bc-923f-4d76-a6ab-88457baca6fb.teleport...
  expires: 0001-01-01T00:00:00Z
  roles:
  - admin
  status:
    is_locked: false
    lock_expires: 0001-01-01T00:00:00Z
    locked_time: 0001-01-01T00:00:00Z
  traits:
    kubernetes_groups: null
    logins:
    - ltremblay
```
And the output of `tsh status` is the same as in 1)

In these cases, login works as usual (after logging out, clearing out ~/.tsh for good measure, then logging in to get the reflected changes). It's a bit cumbersome to have to go back and add usernames to roles or user traits after the fact, though!

Of course, yes, SSO integration is the better choice.
