### ISSUE TITLE
Moderated session "waiting room" is terminated when an observer leaves

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#25667]
Expected behavior:

An observer who is present in the session but does not count towards the required `join_policy` should not be able to terminate the session.

Current behavior:

An observer can join the waiting room of a session that requires a moderator. The session correctly remains in the waiting room because the policy is not satisfied.

If the observer presses ctrl+c or closes the web UI tab, the session is terminated before a moderator can join.

Bug details:

Confirmed on v13 alpha.2 - likely present on all supported versions

Session initiator role has a require policy:

```
    require_session_join:
    - count: 1
      filter: contains(user.spec.roles, "moderator")
      kinds:
      - ssh
      - k8s
      modes:
      - moderator
      name: require-one-moderator
      on_leave: ""
```

Another participant has the following join policy, and joins as an observer instead of a moderator:

```
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - moderator
      - observer
      name: moderator-oversight
      roles:
      - requires_moderator
```
