### ISSUE TITLE
tctl get returns [CLIENT]  Cannot connect to the auth server: Get https://teleport.cluster.local/v2/configuration/name: x509: certificate signed by unknown authority.

### ISSUE THREAD

**Issue by vuzzlevuzz** [gravitational/teleport#2570]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
When running tctl get user with a public certificate, get error:

> [CLIENT]  Cannot connect to the auth server: Get https://teleport.cluster.local/v2/configuration/name: x509: certificate signed by unknown authority.
> Is the auth server running on 127.0.0.1:3025?

**What you expected to happen**:
Return a list of users

**How to reproduce it (as minimally and precisely as possible)**:
Basic install of teleport
Public (GoDaddy) pem files placed into /var/lib/teleport and chmod 600
/etc/teleport.yaml
```
teleport:
  nodename: proxy.mydomain.com
  data_dir: .data
auth_service:
  enabled: "yes"
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  public_addr: proxy.mydomain.com:3080
  ssh_public_addr: proxy.mydomain.com:3023
  https_key_file: /var/lib/teleport/mydomain_key.pem
  https_cert_file: /var/lib/teleport/mydomain_cert.pem

```
mydomain_cert.pem has the full chain, my cert first followed by the intermediate
Have also tried adding to /etc/pki/ca-trust/source/anchors and running update-ca-cert extract
And adding 127.0.0.1 proxy.mydomain.com to /etc/hosts

The proxy works correctly - I get the login page with the correct certificate presented but I cannot use tctl.  It seems like it doesn't recognise the GoDaddy CA but I can't work out why?

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.1.6 git:v3.1.6-0-gaada9001 go1.11.5
- Tsh version (use `tsh version`): Teleport v3.1.6 git:v3.1.6-0-gaada9001 go1.11.5
- OS (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core)

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug
