### ISSUE TITLE
Docker Container not useable with traefik

### ISSUE THREAD

**Issue by Arsur** [gravitational/teleport#2586]
**What happened**:
I'am trying to deploy the docker image, its running but i cant access the webui. Firefox says connection reset. 
**What you expected to happen**:
Access the webui, at least on the localhost. 
**How to reproduce it (as minimally and precisely as possible)**:
Requirements: docker + docker-compose
Copy all files at one location, remove .txt from name and run from this location
```
docker network create proxy
docker-compose -f ./teleport-docker-compose.yaml up -d
```

Files:
[teleport.yaml.txt](https://github.com/gravitational/teleport/files/2925866/teleport.yaml.txt)
[teleport-docker-compose.yaml.txt](https://github.com/gravitational/teleport/files/2925934/teleport-docker-compose.yaml.txt)

go to browser and try to reach localhost:3080

I guess the problem is connected to the  ` advertise_ip: `.

**Environment**:
https://quay.io/repository/gravitational/teleport?tag=latest&tab=tags

**Browser environment**
Firefox 65.0 (64-bit)
Ubuntu 18

**Relevant Debug Logs If Applicable**
docker logs:
```
[AUTH]    Auth service is starting on 0.0.0.0:3025.
[NODE]    Service is starting on 0.0.0.0:3022.
[PROXY]   Reverse tunnel service is starting on 0.0.0.0:3024.
[PROXY]   Web proxy service is starting on 0.0.0.0:3080.
[PROXY]   SSH proxy service is starting on 0.0.0.0:3023.
```
[teleport.log](https://github.com/gravitational/teleport/files/2925943/teleport.log)

**Comment by Arsur** [comment]
Okay i got parts of it running. The `advertise_ip` i put in the ip of the docker container. than its reachable over https://localhost:3080

**Comment by webvictim** [comment]
So, two issues:

1) Your problem with not being able to access the UI isn't to do with `advertise_ip` - it's that the UI needs to be accessed over HTTPS. I removed `advertise_ip` from the `teleport.yaml` file you uploaded and it works fine - you just need to go https://localhost:3080 rather than http://localhost:3080

2) If you really want to disable TLS, you can just add `command: "--insecure-no-tls"` to your `teleport-docker-compose.yaml` file under services.teleport:

```yaml
version: '3'
services:
  teleport:
    image: quay.io/gravitational/teleport:3.1.7
    command: "--insecure-no-tls"
    networks:
      - proxy
    ports:
      - "3080:3080"
      - "3023:3023"
      - "3025:3025"
    volumes:
      - ./data/one:/var/lib/teleport
      - ./teleport.yaml:/etc/teleport/teleport.yaml
networks:
   proxy:
      external: true
```
