### ISSUE TITLE
Terraform Teleport Provider | Resource teleport_app

### ISSUE THREAD

**Issue by itsmesuniljacob** [gravitational/teleport#25881]
Expected behavior:
The app service should be visible in applications 

Current behavior:

The app service is not visible in applications 
Bug details:
- Teleport version: 12.2.1
- Recreation steps
   Have a Teleport cluster in AWS. Use Teleport Terraform provider to create an app 
- Debug logs
  Below is the result from audit log which says app was created

```
{
  "app_labels": {
    "teleport.dev/origin": "dynamic"
  },
  "app_uri": "localhost:3000",
  "cluster_name": "teleport.example.com",
  "code": "TAP03I",
  "ei": 0,
  "event": "app.create",
  "expires": "0001-01-01T00:00:00Z",
  "impersonator": "<redacted>",
  "name": "example",
  "time": "2023-05-04T11:56:26.528Z",
  "uid": "3a5f3557-2a25-458b-b27f-549c8548b8d1",
  "user": "terraform"
}
```

<img width="1186" alt="image" src="https://github.com/gravitational/teleport/assets/16597269/6de68d44-2656-4115-9309-e8c5005c7302">

Terraform files info below:

```
provider "teleport" {

  addr               = "teleport.example.com:443"
  identity_file_path = "identity.pem"
}
```

```
terraform {
  required_providers {
    teleport = {
      source = "terraform.releases.teleport.dev/gravitational/teleport"
      version = ">= 12.2.4"
    }
  }
}
```

```
resource "teleport_app" "example" {
  metadata = {
    name = "example"
    description = "Test app"
    labels = {
        "teleport.dev/origin" = "dynamic" // This label is added on Teleport side by default
    }
  }

  spec = {
    uri = "localhost:3000"
  }
}

```

The information says , app is created but I don't see the same in the `Applications` menu

**Comment by zmb3** [comment]
Does your user have a role that permits access to the `example` app?

**Comment by itsmesuniljacob** [comment]
Yes @zmb3 , I have given the below role to the user:
```
kind: role
metadata:
  name: app-access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - arn:aws:iam::<redacted>
    logins:
    - '{{email.local(external.username)}}'
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 1h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v5
```
