### ISSUE TITLE
Address for openssh node def not allowed to put dns name

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25935]
Expected behavior:

DNS and IPs are valid for addresses for Node entries. In many cases the OpenSSH server is reachable by a DNS name, not just a fixed IP.  Also alternate IPs allows for dns names while this does not.

Current behavior:

Only IPs are allowed in the `addr` spec while you are allowed to put DNS entries in the 

Bug details:
- Teleport version: 13.0.0
- Recreation steps

Attempt to set the `addr` as something besides a IP

```yaml
kind: node
version: v2
sub_kind: openssh
metadata:
  name: ubuntu-openssh
  labels:
    tier: dev 
spec:
  addr: ubuntuhost:22
  hostname: openssh-node
```

```bash
tctl create -f openssh.yaml 
ERROR: invalid Addr "ubuntuhost:22": ParseAddr("ubuntuhost"): unexpected character (at "ubuntuhost")
```
