### ISSUE TITLE
[v13] [kube-agent] Teleport kube agent overwrites Kubernetes secret

### ISSUE THREAD

**Issue by MusicDin** [gravitational/teleport#26002]
## Expected behavior:

If `joinParams.tokenName` and `authToken` are empty, kube agent won't create a secret with join token ([docs link](https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/#secretname)).

Example config (helm-chart value):
```yaml
# Predefined Kubernetes secret containing auth-token.
secretName: teleport-agent-join-token

# Set empty value for joinParams.tokenName
# to enforce reading Kubernetes secret.
#
joinParams:
  method: token
  tokenName: ""
```
 
## Current behavior:

**[v13.0.0]**
Kube agent overwrites the existing Kubernets secret.

**[v12.3.3]**
Kube agent does not override the secret. In addition, the pod initialization fails, if the secret does not exist.
