### ISSUE TITLE
Teleport for EKS

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2613]
## Description

Teleport proxy to [use impersonation API](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) instead of the [CSR API](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#requesting-a-certificate)

## Benefits

This allows Teleport to work on EKS clusters, GKE and all
other CNCF compatible clusters. (Azure for example)

In addition to that it allows RBAC to be set up in a more fine grained way allowing Teleport to only assume identities with limtis, as in the examples:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limited-impersonator
rules:

# Can impersonate the groups "developers" and "admins" only
- apiGroups: [""]
  resources: ["groups"]
  verbs: ["impersonate"]
  resourceNames: ["developers","admins"]
```

## Configuration Changes

It introduces extra configuration flag to proxy_service
configuration parameter:

```yaml
proxy_service:
   kubernetes:
     # kubeconfig_file is used for scenarios
     # when Teleport Proxy is deployed outside
     # of the kubernetes cluster
     kubeconfig_file: /path/to/kube/config
```

It deprecates similar flag in auth_service that is now ignored.

```yaml
auth_service:
   # DEPRECATED. THIS FLAG IS IGNORED
   kubeconfig_file: /path/to/kube/config
```

Helm chart has updated RBAC as well.
