### ISSUE TITLE
Teleport Kubernetes SNI

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2614]
## Description

The major feedback from users is that there is a major confusion and a problem when 
users create cluster names with `.` and try to use kubernetes support with them.

What happens:

Main cluster is `main.example.com`
Remote cluster is `remote.example.com`

After `tsh login` the URL of the Kubernetes endpoint of `remote.example.com` when accessed via `main.example.com` looks like this: `remote.example.com.main.example.com`. 

For this to work, users have to add this address in `public_addr` section of kubernees service:

```yaml
proxy_service:
   enabled: yes
    kubernetes: 
       enabled: yes
        # this line is added so teleport can add DNSName to the issued proxy certificate:
        public_addr: ['remote.exmple.com.main.example.com`]
```

This is very tedious and counter intuitive. Folks try to workaround this by doing this:

```yaml
proxy_service:
   enabled: yes
    kubernetes: 
       enabled: yes
        # this line is added so teleport can add DNSName to the issued proxy certificate:
        public_addr: ['*.main.example.com`]
```

But DNS wildcards do not work on more than one extra `.` by design. so this solution does not work.

## Solution

First of all, customers should not worry about internal wildcards and other problems like that, so the following solution will be recommended and implemented:

Customers will only have to add this:

```yaml
proxy_service:
   enabled: yes
    kubernetes: 
       enabled: yes
        # this line is added so teleport can add DNSName to the issued proxy certificate:
        public_addr: ['main.example.com`]
```

To indicate that `main.example.com` is a publicly accessible part of the proxy. Teleport will automatically an internal proxy cert that contains `*.main.example.com` as well as `main.example.com`

The actual URL to access `remote.example.com.main.example.com` will be converted instead to:

`72656d6f74652e6578616d706c652e636f6d0a.main.example.com` URL in the kubeconfig `server` section.

The number part `72656d6f74652e6578616d706c652e636f6d0a` is a hex encoded `remote.example.com`.

The Teleport server will do SNI match and will decode the hex encoded part and do the actual forward.

This change will not affect users in any way, except that cluster names with DNS names in them will work and no additional dynamic entries will be required when new trusted clusters will be added.
