### ISSUE TITLE
Cannot apply login rules with --bootstrap

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#26296]
**Expected behaviour**
`teleport start --bootstrap` should be able to apply any resource type that Teleport supports.

**Current behaviour**
`teleport start --bootstrap` fails when attempting to provide a file containing `login_rule` resources.

`bootstrap.yaml`:
```yaml
kind: login_rule
version: v1
metadata:
  name: replace_open_brace_with_percent
spec:
  priority: 0
  traits_expression: |
    external.put("ScopedRoles", strings.replaceall(external["ScopedRoles"], "{", "%"))
```

Error on startup from `teleport start --bootstrap bootstrap.yaml`:
```
ERROR: cannot dynamically unmarshal resources of kind "login_rule"
```

Bug details:
- Teleport version: 13.0.0
