### ISSUE TITLE
PodDisruptionBudget settings in Helm Chart doesn't allow upgrading

### ISSUE THREAD

**Issue by FireDrunk** [gravitational/teleport#26375]
Expected behavior:
Pod's are upgraded during Helm Upgrade(s)

Current behavior:
The pod stays in the `Pending` state.

Bug details:
- Teleport version v13.0.0 (via Helm)
- Recreation steps
values.yaml
```yaml
teleport-cluster:
  clusterName: teleport.my.url
  proxyListenerMode: multiplex

  publicAddr:
    - teleport.my.url:9090

  operator:
    enabled: true

  service:
    type: LoadBalancer
    spec:
      loadBalancerIP: <internal-ip>
  
  highAvailability:
    replicaCount: 3
    requireAntiAffinity: true
    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    certManager:
      enabled: true
      issuerName: "letsencrypt-prod"
      issuerKind: ClusterIssuer
    
    minReadySeconds: 15
```
- Debug logs (not applicable)

This happens:
```
teleport-proxy-5d7f7b7cff-rzxkq   0/1     Pending             0               5m25s
teleport-proxy-79bbdb6f4b-tnq57   1/1     Running             0               9m19s
teleport-proxy-79bbdb6f4b-zb7kw   1/1     Running             0               9m19s
teleport-proxy-79bbdb6f4b-zksf6   1/1     Running             0               9m19s
```

This is because the anti-affinity is requiring an extra node to spinup the new pod with the new settings. My cluster has exactly 3 nodes, and I want exactly 3 replicas (one for each node).
This causes the upgrade to lock-up.

One of the solutions would be to set the `requireAntiAffinity` to false, but that would allow 2 teleport pods on a single node during upgrades, which would not be rescheduled afterwards.

The other solution is the ability to set the Deployment Strategy to `Recreate`. But this would allow all pods to be scaled down, and than recreated.

Another (perhaps better) solution is to change the maxUnavailable from the current 25% default to an explicit 33%. This is actually what is causing the pods to not be suspended, because with 3 replicas you cannot bring one down to upgrade, because that would bring the total unavailability to > 25% which is not allowed by default.

If this is something you agree on, I'm happy to create a PR.
