### ISSUE TITLE
Label order in the Role definition affects its behavior. [Teleport Web Console+Teleport Connect]

### ISSUE THREAD

**Issue by kaan-carbon** [gravitational/teleport#26501]
We are using labels for selection and filtering as they are supposed to be.
While working on OpenSearch integration, I faced this issue in the **Teleport Web console** and **Teleport Connect**.

In the **Role** definition, we must define labels in alphanumeric order (same as DB instance labels shown in the web console) [`allow - db_labels` section]. Otherwise, they are not working.

Expected behavior:

The following Role definitions are expected to work.

Ordered:
```yaml
...
db_labels:
      Environment: '*'
      Project: '*'
      engine: opensearch
db_users:
    - TeleportDatabaseServiceRole
...
```

Non-ordered:
```yaml
...
db_labels:
      Project: '*'
      engine: opensearch
      Environment: '*'
db_users:
    - TeleportDatabaseServiceRole
...
```

Current behavior:

Only the alphanumeric ordered labels (first one) are working in the **Role** definition (in **Teleport Web console**). 
When I use an alphanumeric ordered **Role** definition, I'm able to see the **TeleportDatabaseServiceRole** user in **Teleport Connect** (when I try to connect the DB). If the label order is changed, I can not be able to see this user.

<img width="1662" alt="Screenshot 2023-05-19 at 14 20 59" src="https://github.com/gravitational/teleport/assets/102513863/a3bb9b35-6b94-4a45-8c87-b558dc06b874">

<img width="1340" alt="Screenshot 2023-05-18 at 15 23 25" src="https://github.com/gravitational/teleport/assets/102513863/be2390ae-6754-4cad-852c-65198b13a050">

<img width="1420" alt="Screenshot 2023-05-19 at 14 30 11" src="https://github.com/gravitational/teleport/assets/102513863/23d83b3e-0ac4-4c6f-a343-78eff73bc545">

Bug details:
- Teleport version: 13.0.0 (Community Edition)
- OS: MacOS
- Recreation steps: defined above.
- Debug logs: Screenshots are shared.
