### ISSUE TITLE
Failed to connect to host 50% of the time when using agent_mesh in high available setup

### ISSUE THREAD

**Issue by WarmTestr** [gravitational/teleport#26665]
**Expected behavior:**
`tsh ssh servername` should always work, not just 50% of the time with two teleport nodes in a high availability setup using tunnel_strategy: agent_mesh.

**Current behaviour:**
I have setup HAProxy as a TCP load balancer between 10.100.1.1 and 10.100.1.2 in round robin mode. HTTP/web ui traffic is handled nicely. However, `tsh ssh servername` and attempting to connect to a server using the web UI will only work 50% of the time. It seems that a connection is only established to a single server. To test this theory i've set the DNS of teleport.example.com to 10.100.1.1 and joined a node. It was only possible to access the node from 10.100.1.1 consistently, when trying to connect from 10.100.1.2 the following error occurs 100% of the time:

```
ERROR: failed connecting to host hostname_removed:0: failed to dial target host
	Teleport proxy failed to connect to "node" agent "@local-node" over reverse tunnel:

  no tunnel connection found: no node reverse tunnel for e2b8e9e3-cd84-426a-8931-ea8fcf827cfb.teleport01 found

This usually means that the agent is offline or has disconnected. Check the
agent logs and, if the issue persists, try restarting it or re-registering it
with the cluster.
````

This seems to be the same issue as https://github.com/gravitational/teleport/issues/19720, however no solution is provided other than upgrade to version 12, we're currently using version 13.

**Details:**
Servers are using configuration below:
```
version: v3
teleport:
  nodename: teleport01
  storage:
    type: etcd
    prefix: /teleport/
    peers: ["http://10.100.1.1:2379", "http://10.100.1.2:2379"]
    etcd_max_client_msg_size_bytes: 15728640
    insecure: true
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: true
  tunnel_strategy:
    type: agent_mesh
  cluster_name: teleport.example.com:443
  tokens:
    - "proxy,node:removedforprivacy"
  authentication:
    type: "local"
    second_factor: on
    webauthn:
      rp_id: teleport.example.com
  proxy_listener_mode: multiplex
  client_idle_timeout: 8h
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.com
  https_key_file: /path/to/valid/key.pem
  https_cert_file: /path/to/valid/key.pem
  https_keypairs_reload_interval: 1h
```
 
 Nodes are running the configuration below:
 ```
 teleport:
  nodename: hostname.of.machine
  data_dir: /var/lib/teleport
  join_params:
    token_name: removedforprivacy
    method: token
  proxy_server: teleport.example.com:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:removed
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```

tsh version
```         
Teleport v13.0.0 git:v13.0.0-0-g6d0ce2bf go1.20.4
Proxy version: 13.0.0
Proxy: tele.example.com:443
```
Server version
```
Teleport v13.0.2 git:api/v13.0.2-0-ge55f844 go1.20.4
```

Node version:
```
Teleport v13.0.2 git:api/v13.0.2-0-ge55f844 go1.20.4
```
The same issue was also seen using v13.0.0 and v12

Recreation steps:
- Deploy a HA teleport cluster (Proxy and Auth service) with more than one node. I deployed 2 nodes
- I enabled TLS routing by setting proxy_listener_mode: multiplex
- I did not enable proxy peering (open source version)
- I put a HAProxy (TCP mode) in front of cluster VMs
- Add a server using a join token or using the command provided on the webui
- Connect several times to a server from WebUI or via tsh ssh <server> command, observe this works 50% of the time.

This issue seems to be very similar to https://github.com/gravitational/teleport/issues/19720. This issue was closed, however to explanation was provided other than upgrade to version 12.
