### ISSUE TITLE
Can't connect to self-hosted MariaDB with existing custom certificates.

### ISSUE THREAD

**Issue by andrei-bamboi** [gravitational/teleport#27086]
Expected behavior:
I should be able to add and connect to a managed self-hosted MariaDB instance with existing SSL certificates. As per documentation:

- https://goteleport.com/docs/database-access/guides/mysql-self-hosted/
- https://github.com/gravitational/teleport/blob/master/rfd/0011-database-access.md

Current behavior:

I am not able to connect to a self-hosted MariaDB with existing SSL configuration:

Teleport setting for proxy:

```
version: v3
teleport:
  nodename: teleport.mydomain.com
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  cluster_name: teleport.mydomain.com
  proxy_listener_mode: multiplex
  load_all_cas: true
  tokens:
    - "node,db:myprecioustoken"
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.mydomain.com:443
  https_keypairs:
  - key_file: /etc/ssl/teleport/teleport_key.pem
    cert_file: /etc/ssl/teleport/teleport_cert.pem
  https_keypairs_reload_interval: 10s
  acme: {}
```
Teleport settings for db mariadb node : 
```
version: v3
teleport:
  log:
    severity: DEBUG
  nodename: "mariadb-node"
  data_dir: "/var/lib/teleport"
  proxy_server: "teleport.mydomain.com:443"
  auth_token: "myprecioustoken"

db_service:
  enabled: true
  
  databases:
  - name: "mariadb-db"
    protocol: "mysql"
    uri: "teleport-db.mydomain.com:3306"
    tls:
      ca_cert_file: "/etc/certs/ca/ca-cert.pem" #custom CA of mariadb instance.

```
Mariadb user created as : 
`CREATE USER 'db-readonly'@'%' REQUIRE X509;
GRANT ALL ON `%`.* TO 'db-readonly'@'%';`

Bug details:
- Teleport version : Teleport v12.1.1 git:api/v12.1.1-0-gb9ee483 go1.19.7
- Recreation steps : provided above
- Debug logs

Logs on mariadb node were teleport db service is running :  
`ERRO [DB:SERVIC] Failed to handle connection. addr:192.100.0.1:443 error:[
 ERROR REPORT:
Original Error: syscall.Errno connection refused
 Stack Trace:
github.com/gravitational/teleport/lib/srv/db/common/errors.go:147 github.com/gravitational/teleport/lib/srv/db/common.ConvertConnectError
 github.com/gravitational/teleport/lib/srv/db/mysql/engine.go:267 github.com/gravitational/teleport/lib/srv/db/mysql.(*Engine).connect
github.com/gravitational/teleport/lib/srv/db/mysql/engine.go:90 github.com/gravitational/teleport/lib/srv/db/mysql.(*Engine).HandleConnection
github.com/gravitational/teleport/lib/srv/db/server.go:931 github.com/gravitational/teleport/lib/srv/db.(*Server).handleConnection
github.com/gravitational/teleport/lib/srv/db/server.go:841 github.com/gravitational/teleport/lib/srv/db.(*Server).HandleConnection
github.com/gravitational/teleport/lib/reversetunnel/transport.go:275 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
github.com/gravitational/teleport/lib/reversetunnel/agent.go:581 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
runtime/asm_amd64.s:1594 runtime.goexit
User Message: connection refused] db/server.go:843`
