### ISSUE TITLE
Teleport should use `X-Forwarded-For` headers to get client IP when running behind a reverse proxy

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#27120]
Expected behavior: `X-Forwarded-For` headers should be extracted and used to set client IP throughout Teleport when running behind a layer 7 LB. This wasn't a huge issue before as layer 7 LBs weren't officially supported, but in the wake of https://github.com/gravitational/teleport/issues/21870 being mostly merged this is going to become more of an issue.

Current behavior: `X-Forwarded-For` headers are not extracted (see `addr.remote` set to Class C `192.168.x.x` IP):

```yaml
{
  "addr.remote": "192.168.40.19:26086",
  "cluster_name": "example.teleportdemo.com",
  "code": "T1000I",
  "ei": 0,
  "event": "user.login",
  "method": "local",
  "mfa_device": {
    "mfa_device_name": "apollo",
    "mfa_device_type": "WebAuthn",
    "mfa_device_uuid": "0f8b031f-55c1-44f4-a60f-425fdef8d54e"
  },
  "success": true,
  "time": "2023-05-30T16:04:50.792Z",
  "uid": "bcaa7d84-9490-49ff-92d4-52f8691290e4",
  "user": "gus",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
}
```

This is Teleport running in EKS behind an ALB (with an IP-based target group).

Layer 7 LBs like ALBs don't support the use of proxy protocol (that's an L4 concept)

Bug details:
- Teleport version: 13.0.3
