### ISSUE TITLE
Specify the cluster and context

### ISSUE THREAD

**Issue by drewwells** [gravitational/teleport#27309]
We're using federated teleport v13. I'm reading the documentation about kubeClusterName, available here: https://goteleport.com/docs/reference/helm-reference/teleport-cluster/#kubeclustername

It reads that the kubeClusterName is used as the cluster to connect to. However, federation does not respect this setting. Instead we get this confusing set of cluster and contexts. Each federated server appears as the same server but different contexts. The contexts are {{ federated address }}.{{ kubeClusterName }}. I expect this to be `{{ kubeClusterName }}`.

Example:

```
teleport-kube-agent:
  proxyAddr: teleport-leaf.services.sdp.example.com:443
  roles: kube,db
  kubeClusterName: box-3
```

```
-> % k config get-clusters  
NAME
teleport-leaf.services.sdp.example.com
```
```
kubectl config get-contexts
teleport-leaf.services.sdp.example.com-box-3
teleport-leaf.services.sdp.example.com-box-4
```

How do I setup my teleport agents so the shortened context is used for kubectl.
