### ISSUE TITLE
Login page: "Login With" behavior

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2745]
"Login with Login...":

![Screenshot from 2019-05-28 10-17-03](https://user-images.githubusercontent.com/461020/58497895-c4fff480-8131-11e9-97ee-cdbba13436b2.png)

My connector:

```
kind: github
version: v3
metadata:
  name: github
spec:
  client_id: 7735072d4f7a5bab3371
  client_secret: ""
  display: Login with Github
  redirect_url: https://kontsevoy.com:3080/v1/webapi/github/callback
  teams_to_logins:
  - kubernetes_groups:
    - system:masters
    logins: 
    - admin
    organization: gravitational
    team: ssh
```

"Display" property is set to "Login with Github". So it's obviously appends another "Login with" in front of it.

## Question

1. Do we always prepend "Login with" to all connectors?
2. Have we done this before?

I've been using the same config for a while. Just want to make sure there's no regression here. If this is how it's always worked, close the ticket. Thanks.
