### ISSUE TITLE
Machine ID: New configuration format

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#27525]
See https://github.com/gravitational/teleport/pull/24033 for POC and reasoning

```yaml
version: v2
auth_server: noah.teleport.sh:443
storage:
  type: directory
  path: ./bot-data
  symlinks: try-secure
  acls: try
onboarding:
  join_method: token
  token: foobarbizz
oneshot: true
outputs:
  - type: identity
    roles: [access]
    destination:
      type: directory
      path: ./bot-user
  - type: application
    app_name: httpbin
    roles: [access]
    destination:
      type: memory
  - type: kubernetes
    cluster_name: my-cluster
    roles: [access]
    destination:
      type: memory
  - type: database
    subtype: mongo
    service: my-db-service
    database: my-db
    username: my-db-username
    roles: [access]
    destination:
      type: memory
  - type: ssh_host
    principals: [nodename.my.domain.com]
    roles: [access]
    destination:
      type: memory
```
