### ISSUE TITLE
Machine ID: Generated Kubeconfig does not have absolute destination path

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#27606]
Unlike with the `ssh_config`, the destination path is not converted to an absolute one before being included in the generated files. This means a kubeconfig generated from a destination specified with relative path must be  used from the same working directory as `tbot` runs in.

Fortunately, the docs suggest an absolute path, but we should fix this for relative paths.

Example kubeconfig with relative path:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://leaf.tele.ottr.sh:443
    tls-server-name: kube-teleport-proxy-alpn.leaf.tele.ottr.sh
  name: leaf.tele.ottr.sh-docker-desktop
contexts:
- context:
    cluster: leaf.tele.ottr.sh-docker-desktop
    user: leaf.tele.ottr.sh-docker-desktop
  name: leaf.tele.ottr.sh-docker-desktop
current-context: leaf.tele.ottr.sh-docker-desktop
kind: Config
preferences: {}
users:
- name: leaf.tele.ottr.sh-docker-desktop
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --destination-dir=./tbot-user-k8s # <-- Path not converted to absolute path
      command: /Users/noahstride/code/gravitational/teleport/build/tbot
      env: null
      provideClusterInfo: false
```
