### ISSUE TITLE
GCP support for stateless, HA installations

### ISSUE THREAD

**Issue by joshdurbin** [gravitational/teleport#2768]
Howdy, I'm looking to add Google GCS support to Teleport for recording storage. I have an ask to see this built out for Teleport for a proposed rollout within several Google projects/environments **and**, based on scroll back in Gravitational Community Slack forum, it seems a few others have asked for similar functionality. I have reviewed the implementation for S3, which is straight forward enough, essentially:

- add `lib/events/gcssessions`
- add `lib/events/gcssessions/gcshandler.go` mirror functionality in `lib/events/s3sessions/s3handler.go`
- add `SchemGCS` to `constants.go`
- add a case for aforementioned scheme to the switch in `initUploadHandler`, in `lib/service/service.go`
- update the `TestParseSessionsURI` in `lib/utils/utils_test.go`
- update the relevant documentation

Adding GCS as a storage backend would require an additional dependency, which is currently at [version 0.40.0](https://github.com/googleapis/google-cloud-go/releases):

```
[[constraint]]
  name = "cloud.google.com/go"
  version = "0.40.0"
```

**Comment by joshdurbin** [comment]
Something like [this](https://github.com/gravitational/teleport/compare/master...bigcommerce:gcs_sessions_support). I've built/tested this locally.

**Comment by benarent** [comment]
Thanks for the interest @joshdurbin and for the work to add Google Cloud Storage backend.  For us to productise this, it would be good to have a complete HA GCP Story. 

- GCS for Storage
- Firebase / Big Table as a backend alternative for DynanoDB
- Best practice for LB and firewall setup. 

I'm going to leave this open to gather more feedback from the community and team.

**Comment by joshdurbin** [comment]
@benarent Agreed. We're looking to house all the data for Teleport, stateless in GCP-native resources. In fact I'm working on Firestore logging and auth data storage right now and hope to have something done by end of the week. Should I update this issue to reflect a broader GCP story?

**Comment by benarent** [comment]
Yes @joshdurbin , that would be great. Let me know how you get on.

**Comment by klizhentas** [comment]
I was not familiar with firestore specifically, but looking at it, it seems like it supports server side encryption by default, which is very nice and [events](https://firebase.google.com/docs/firestore/query-data/listen). 

@benarent can you put this on the next product planning meeting to we can discuss this with mr @kontsevoy

**Comment by klizhentas** [comment]
@joshdurbin questions for you:

Who is going to use this feature in production (is this a hack project, production company policy, etc)

**Comment by joshdurbin** [comment]
@klizhentas I'm in the process of building several clusters in our environment(s) at BC. We'd prefer to keep our data in Google's systems/services, hence this effort. Ideally this work would get brought into core Teleport until then, though, we're running custom builds.

@benarent Current state of things; I should have cluster state working tomorrow, I'm a bit behind schedule. Currently implemented are:

- GCS storage
- Firestore-backed events

That work is all in the [BC fork](https://github.com/bigcommerce/teleport/tree/gcp_ha_support).

**Comment by joshdurbin** [comment]
Alright, this work is close to done. I've been testing the changes locally against GCS and Firestore for the last few days.

The data in the screenshots is junk data for a local cluster, no secrets.

Indexes remain created manually, I'll add support for ensuring their creation in the next day or two.

<img width="757" alt="Screen Shot 2019-07-01 at 1 25 09 PM" src="https://user-images.githubusercontent.com/532881/60464786-5caaa400-9c04-11e9-986f-2e55d88ffc41.png">

Events are stored in Firestore with the document ID equal to the session ID and event type.

<img width="1668" alt="Screen Shot 2019-07-01 at 1 26 59 PM" src="https://user-images.githubusercontent.com/532881/60464919-ae532e80-9c04-11e9-902b-f566696270d5.png">

Datastore documents cannot be stored with their IDs equal to the key as the value of the key violates Firestore document ID requirements (contain forward slashes, periods, etc...). The document IDs are encoded from the key to maintain fast fetching from a known point rather than a query.

<img width="1661" alt="Screen Shot 2019-07-01 at 1 27 11 PM" src="https://user-images.githubusercontent.com/532881/60465026-f5412400-9c04-11e9-838d-a50aa2f04ec4.png">

Both the Firestore Event "handler" and the Firestore backend have ticker-based expired entry removal. The Firestore Event "handler" does so by evaluating the timestamp on the record while the Firestore backend actually evaluates based on the "expires" property, if set.

The Firestore backend uses a document snapshot query stream to consume document changes for the collection -- allowing all auth servers watchers to receive updates.

**Comment by klizhentas** [comment]
@kontsevoy has approved the feature in the product, so I'll be helping you along the way. Once you are ready to review, let's do a zoom review kick off session once you are ready.

**Comment by klizhentas** [comment]
@joshdurbin can you please post the configuration of the teleport with the new changes, we would like to review it as well.

**Comment by joshdurbin** [comment]
Woot. What I'm using right now, outside GCP's environment, on my laptop is:

```
  storage:
    type: firestore
    collection_name: cluster-data
    credentials_path: /var/lib/teleport/gcs_creds
    project_id: bc-jdurbin
    audit_events_uri: 'firestore://events?projectID=bc-jdurbin&credentialsPath=/var/lib/teleport/gcs_creds'
    audit_sessions_uri: 'gs://teleport-session-storage-2?credentialsPath=/var/lib/teleport/gcs_creds&projectID=bc-jdurbin'
```

In GCP you'd likely make use of attached compute service accounts and forego credentials files.

**Comment by joshdurbin** [comment]
Full config being used at the moment is:

```yaml
#
# Sample Teleport configuration file.
#
teleport:
  nodename: C02WG09CHTDH
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: cluster-join-token
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: DEBUG
  ca_pin: ""
  storage:
    type: firestore
    collection_name: cluster-data
    credentials_path: /var/lib/teleport/gcs_creds
    project_id: bc-jdurbin
    audit_events_uri: 'firestore://events?projectID=bc-jdurbin&credentialsPath=/var/lib/teleport/gcs_creds'
    audit_sessions_uri: 'gs://teleport-session-storage-2?credentialsPath=/var/lib/teleport/gcs_creds&projectID=bc-jdurbin'
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:cluster-join-token
  session_recording: ""
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /var/lib/teleport/webproxy_key.pem
  https_cert_file: /var/lib/teleport/webproxy_cert.pem
```
