### ISSUE TITLE
Machine ID: Kubernetes Access support for Trusted Clusters

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#27790]
At the moment, you can only generate a `kubeconfig` for Kubernetes Clusters that are joined with the Teleport cluster that the bot is connected to. For users that leverage Trusted Clusters, this is inconvenient, as they need to create a bot per Teleport Cluster rather than just creating one against the root cluster.

We should use a config similar to that used for the Identity output (e.g the `cluster` field specifies which Teleport cluster to use)

```yaml
outputs:
- type: kubernetes
  destination: ...
  kubernetes_cluster: foobar
  cluster: leaf.tele.ottr.sh
```
