### ISSUE TITLE
Teleport's use of AWS credentials is inconsistent

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2781]
**What happened**:
Teleport doesn't use or prefer AWS credentials specified in the config file in certain situations.

1) When credentials are specified in `/etc/teleport.yaml` for DynamoDB, those credentials are used.
2) These same credentials are **not** used for storing audit logs in S3, however. For this, you must seemingly provide credentials using the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables.
3) If you specify credentials in `/etc/teleport.yaml` and the EC2 instance has an IAM profile, Teleport _sometimes_ seems to prefer to use the IAM profile. It's not particularly obvious where Teleport is getting its credentials from for each service.

Unknowns:
1) If environment variables are set, will DynamoDB use these?
2) Is there a way to provide credentials for audit log storage in S3 via the config file?
3) If the instance has an IAM role, will this override the config file? Will this be true for DynamoDB, S3 audit log storage or both?
4) If the instance has an IAM role, will this override environment variables? Will this be true for DynamoDB, S3 audit log storage or both?
5) What happens if credentials are provided via `~/.aws/credentials` and `~/.aws/config`?
6) Does `AWS_SDK_LOAD_CONFIG=1` (as per https://github.com/aws/aws-sdk-go#aws-shared-config-file-awsconfig and https://github.com/gravitational/teleport/issues/2015) work?

**What you expected to happen**:
1) There should be an explicitly listed order of precedence, something like:

```
Credentials in /etc/teleport.yaml >
Credentials in environment variables >
Credentials in ~/.aws/credentials >
Instance IAM role
```

2) If credentials are provided for one service in `/etc/teleport.yaml`, those same credentials should be used for all AWS-based services.

**How to reproduce it (as minimally and precisely as possible)**:
Install Teleport on an EC2 instance and try using different methods (e.g. https://gravitational.com/teleport/docs/admin-guide/#using-dynamodb) to provide AWS credentials.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v3.2.6git:v3.2.6-0-g67b4ddfb go1.11.5`
- Tsh version (use `tsh version`): `Teleport v3.2.6 git:v3.2.6-0-g67b4ddfb go1.11.5`
- OS (e.g. from /etc/os-release): `Fedora 29`

**Comment by webvictim** [comment]
The order of precedence should be the same as detailed here: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials

Not sure how this fits in with credentials specified directly in `/etc/teleport.yaml` though.

**Comment by thejosephstevens** [comment]
So I ran into this in my setup as well. I had this block in my teleport.yaml
```
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
  storage:
    type: dynamodb
    region: us-east-1
    table_name: teleport.{{ fullSubDomain }}
    access_key: {{ teleportAwsStateKey }}
    secret_key: {{ teleportAwsStateKeySecret }}
    # audit_events_uri: ['dynamodb://teleport.{{ fullSubDomain }}']
    # audit_sessions_uri: s3://teleport-sessions/{{ fullSubDomain }}
```
I determined that if I uncommented the audit events and audit session URIs, teleport would stop using the access key and secret in the teleport.yaml and start using the environment variables in my container.
