### ISSUE TITLE
Kubernetes operator only create v5 roles

### ISSUE THREAD

**Issue by xabufr** [gravitational/teleport#27938]
Expected behavior: When we create new Teleport roles in kubernetes using for example:

```yaml
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: some-role
  namespace: teleport-cluster
spec:
  allow:
    kubernetes_groups: [some-kubernetes-group]
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    kubernetes_users:
    - '{{ email.local(external.username) }}'
```

The operator should create the corresponding role in v6, as in the apiVersion field

Current behavior:

The operator create a v5 role

Bug details:
- Teleport version: v13.0.3

Going through the source code, I found that the RoleReconcilier only instantiate [v5 TeleportRole][instantiate].
This struct is then used to create the Teleport role with corresponding version (the [`ToTeleport`][to-teleport] function).

[v5][v5-role] and [v6][v6-role] of this struct are both available and should be used based on kubernetes field `apiVersion`.

[instantiate]:https://github.com/gravitational/teleport/blob/ef700dd83fd8fc103223c19acf54c9ba5f83d183/integrations/operator/controllers/resources/role_controller.go#LL107C25-L107C25
[to-teleport]: https://github.com/gravitational/teleport/blob/ef700dd83fd8fc103223c19acf54c9ba5f83d183/integrations/operator/controllers/resources/role_controller.go#L122
[v5-role]: https://github.com/gravitational/teleport/blob/v13.1.1/integrations/operator/apis/resources/v5/role_types.go#L46
[v6-role]: https://github.com/gravitational/teleport/blob/v13.1.1/integrations/operator/apis/resources/v6/role_types.go#L46
