### ISSUE TITLE
Teleport Test-Connection failed

### ISSUE THREAD

**Issue by mighty-services** [gravitational/teleport#28017]
Expected behavior:
Clicking on "Test Connection" produces "passed" in the WebUI

Current behavior:
Clicking on "Test Connection" produces "failed" in the WebUI
![grafik](https://github.com/gravitational/teleport/assets/71066192/916e11a4-0fe1-45c1-b887-493109bc80e0)

Bug details:
Teleport version 13.1.1

Recreation steps:
- I installed Teleport with the given bash-script and the script for local deployment
![grafik](https://github.com/gravitational/teleport/assets/71066192/b8cf04bc-ca8b-459d-bcdf-71e610503ade)
- the server is sitting behind a reverse NGINX-Proxy
- the nginx-server issues the Certificate from Let´s Encrypt
- the issued certificates from the Proxy into the teleport-machine and the path to the local stored certificates are defined in the teleport.yaml file
- as in [this issue](https://github.com/gravitational/teleport/discussions/15293) described, I removed "proxy_listener_mode: multiplex" from the preconfigured YAML-File
- added this lines to teleport.yaml file
   - tunnel_listen_addr: 0.0.0.0:3024
   - public_addr: teleport.example.com:443
   - tunnel_public_addr: teleport.example.com:3024
   - tunnel_listen_addr: 0.0.0.0:3024
   - peer_listen_addr: 0.0.0.0:3022
   - ssh_public_addr: teleport.example.com:3023
   - kube_listen_addr: 0.0.0.0:3026
   - kube_public_addr: teleport.example.com:3026
- added a new admin-user according to the [guideline](https://goteleport.com/docs/get-started/#step-34-create-a-teleport-user-and-set-up-two-factor-authentication)
- added the new node through the "add Server" button within the webUI, choose ubuntu 14+, pasted and ran the script on the ubuntu 22lts node without any error in the console according to [step 4 of the guideline](https://goteleport.com/docs/get-started/#step-44-enroll-your-infrastructure)

Debug logs
- within the teleport-cluster I see only one line created, when clickin on the test-connection button
`teleport Connecting to proxy=localhost:3023 login="root" client/api.go:3060`

teleport.yaml file on the cluster server:
```
version: v3
teleport:
  nodename: mighty-teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
#  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  listen_addr: 0.0.0.0:3023
  public_addr: teleport.example.com:443
  tunnel_public_addr: teleport.example.com:3024
  tunnel_listen_addr: 0.0.0.0:3024
  peer_listen_addr: 0.0.0.0:3022
  ssh_public_addr: teleport.example.com:3023
  kube_listen_addr: 0.0.0.0:3026
  kube_public_addr: teleport.example.com:3026
  https_keypairs:
  - key_file: /var/lib/teleport/privkey.pem
    cert_file: /var/lib/teleport/fullchain.pem
  https_keypairs_reload_interval: 0s
  acme: {}
```
