### ISSUE TITLE
Node failed to establish connection to cluster: identity Identity(hostuuid=UUID, role=Node) not found

### ISSUE THREAD

**Issue by jmsdrake** [gravitational/teleport#2814]
**What happened**: Starting teleport node fails with:
DEBU [PROC:1]    Connected state: never updated. service/connect.go:99
ERRO [PROC:1]    Node failed to establish connection to cluster: identity Identity(hostuuid=d634dea5-a6d2-4ec2-9817-fa8311df72bd, role=Node) not found. service/connect.go:65
DEBU [PROC:1]    Connected state: never updated. service/connect.go:99
ERRO [PROC:1]    Node failed to establish connection to cluster: identity Identity(hostuuid=d634dea5-a6d2-4ec2-9817-fa8311df72bd, role=Node) not found. service/connect.go:65
DEBU [PROC:1]    Connected state: never updated. service/connect.go:99
ERRO [PROC:1]    Node failed to establish connection to cluster: identity Identity(hostuuid=d634dea5-a6d2-4ec2-9817-fa8311df72bd, role=Node) not found. service/connect.go:65
DEBU [PROC:1]    Connected state: never updated. service/connect.go:99
ERRO [PROC:1]    Node failed to establish connection to cluster: identity Identity(hostuuid=d634dea5-a6d2-4ec2-9817-fa8311df72bd, role=Node) not found. service/connect.go:65
DEBU [PROC:1]    Connected state: never updated. service/connect.go:99
ERRO [PROC:1]    Node failed to establish connection to cluster: identity Identity(hostuuid=d634dea5-a6d2-4ec2-9817-fa8311df72bd, role=Node) not found. service/connect.go:65

**What you expected to happen**:
teleport to attempt to connect to auth server.

**How to reproduce it (as minimally and precisely as possible)**:
teleport start -d --config=/opt/ic/teleport/teleport.yaml --pid-file=/var/run/teleport.pid

**Environment**:
- Teleport version (use `teleport version`):
Teleport v4.0.1 git:v4.0.1-0-g853a715f go1.12.1

- Tsh version (use `tsh version`):
Teleport v4.0.1 git:v4.0.1-0-g853a715f go1.12.1

- OS (e.g. from /etc/os-release):
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"

**Relevant Debug Logs If Applicable**
- teleport --debug
DEBU [PROC:1]    Connected state: never updated. service/connect.go:99
ERRO [PROC:1]    Node failed to establish connection to cluster: identity Identity(hostuuid=d634dea5-a6d2-4ec2-9817-fa8311df72bd, role=Node) not found. service/connect.go:65

**Comment by Zwordi** [comment]
I had the same issue.
I'm running the auth server on a debian server without issue with other old version of teleport nodes client but i have this behavior with an 4.0.2 client nodes.

Thanks

**Comment by webvictim** [comment]
@jmsdrake @Zwordi Could either/both of you please post your Teleport config file (`/etc/teleport.yaml` by default) with any tokens/secrets redacted? It'd be very helpful for us in debugging this issue.

**Comment by Zwordi** [comment]
Hi @webvictim ,
There is the teleport config from my RancherOS nodes :

```
teleport version
Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1
```

```
teleport:
  nodename: donald
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: "NOTTODAY" 
  auth_servers:
  - Abydos:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: syslog
    severity: DEBUG 
  ca_pin: "miaouw"
  advertise_ip: A.R.E.A.51
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
proxy_service:
  enabled: "no"
```

Do you want to see my auth node config too ?

Thanks and have a good week-end.

**Comment by webvictim** [comment]
@Zwordi Thanks - yes, the auth server config would be helpful too.

**Comment by Zwordi** [comment]
Here we are 
```
teleport:
  nodename: teleport.duck
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: cluster-join-token
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: syslog
    severity: ERROR 
  advertise_ip: X.X.X.X
  ca_pin: ""
auth_service:
  enabled: "yes"
  cluster_name: "teleport.duck"
  listen_addr: 0.0.0.0:3025
  tokens:
  - "proxy,node:something"
  - "auth:anotherthing"
  session_recording: ""
  client_idle_timeout: 0s
  disconnect_expired_cert: true
  keep_alive_count_max: 0

  authentication:
      type:  local 
      second_factor: u2f
      u2f:
          # app_id must point to the URL of the Teleport Web UI (proxy) accessible
          # by the end users
          app_id: https://teleport.duck:3080
          # facets must list all proxy servers if there are more than one deployed
          facets:
          - https://teleport.duck:3080
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  labels:
    db_role: master
    hostname: teleport.duck
  commands:
  - name: arch
    command: [/bin/uname, -m ]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /etc/ssl/teleport.duck/teleport.duck.key
  https_cert_file: /etc/ssl/teleport.duck/bteleport.duck.fullchain
```
```
Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1
```
Have a nice week-end.
