### ISSUE TITLE
kubernete rbac not working

### ISSUE THREAD

**Issue by kmmanto** [gravitational/teleport#28262]
Expected behavior:

Expected the functionality to restrict access to pods.

https://goteleport.com/docs/ver/12.x/kubernetes-access/manage-access/rbac/

Current behavior:

`kubectl get pods -n [namespace]`: Pods that are restricted show up
`kubectl get pods --all-namespaces` : Pods in other namespaces show up

Bug details:
- Teleport version: v12.4.8
- Recreation steps: Followed the steps from the above URL with namespaces specific to my environment.
- Debug logs

**Comment by kmmanto** [comment]
I added a deny rule to test the functionality because `allow` only had:

```
allow:
  kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: allowed
```

```
deny:
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: restricted
```

```
kubectl auth can-i list/get pods -n restricted
no - access to pod restricted/ denied by Teleport: please ensure that "kubernetes_resources" field in your Teleport role defines access to the desired resource.

Valid example:
kubernetes_resources:
- kind: pod
  name: '*'
  namespace: restricted
```

```
kubectl auth can-i --list --namespace=restricted
Resources                                       Non-Resource URLs   Resource Names   Verbs
selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]
pods                                            []                  []               [get watch list]
                                                [/api/*]            []               [get]
                                                [/api]              []               [get]
                                                [/apis/*]           []               [get]
                                                [/apis]             []               [get]
                                                [/healthz]          []               [get]
                                                [/healthz]          []               [get]
                                                [/livez]            []               [get]
                                                [/livez]            []               [get]
                                                [/openapi/*]        []               [get]
                                                [/openapi]          []               [get]
                                                [/readyz]           []               [get]
                                                [/readyz]           []               [get]
                                                [/version/]         []               [get]
                                                [/version/]         []               [get]
                                                [/version]          []               [get]
                                                [/version]          []               [get]
podsecuritypolicies.policy                      []                  [restricted]     [use]

```

Below command returns the pods in `restricted` namespace.
```
kubectl get pods -n restricted
```

**Comment by kmmanto** [comment]
Additional information, `kubernetes_groups` is bound as below
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-viewer
subjects:
- kind: Group
  name: test-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io

```
