### ISSUE TITLE
File upload/download in web interface fails with "EOF" error behind a TLS load balancer

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#28302]
After upgrading to Teleport v12.2.4, the file upload/download functionality in the web interface no longer works for all users and results in a red "EOF" error message. The affected environment utilizes a terminating TLS load balancer. The customer noticed this issue after upgrading from v12.2.3 to v12.2.4.

The ssh node's Teleport logs appear to handle the file download request correctly, but the proxy logs show a "need auth" error message. The issue seems to occur after the session is created and the browser's subsequent request is not recognized as having a valid session/bearer token.

The closest reproduction attempt involved manually removing the header containing the session info using a tool like mitmproxy to modify the request on-the-fly.

**Environment:**
- Teleport version: v12.2.4
- Browsers: Chrome Version 113.0.5672.126 (Official Build) (arm64), and the issue occurs across multiple browsers
- Configuration: Teleport is running behind a terminating TLS load balancer with 1 auth+proxy.

**Steps to reproduce:**

Reproduce attempts have not been successful without extreme manual intervention.

1. Install Teleport v12.2.4
2. Access the web interface and attempt to upload/download a file
  a. Use mitmproxy to alter the request to remove the bearer token.
3. Observe the red "EOF" error message in the web UI

The 504 that the end user is experiencing appears to bo due to their load balancer timing out, but it still includes the teleport `need auth` content in the body of the response.

504 logs extracted from ELB log:

```
h2 2023-06-06T03:16:54.420723Z app/teleport-web-1/b7fe463108d038b9 192.0.2.18:30554 192.0.0.50:3080 0.001 -1 -1 504 - 1549 604 "GET https://teleport.example.com:443/v1/webapi/sites/teleport.example.com/nodes/ecabae3b-a5d5-4cf4-a42b-66e220c7c31b/user1/scp?location=~%2Ftest.txt&filename=~%2Ftest.txt HTTP/2.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:ap-southeast-1:000000000000:targetgroup/alb-teleport/0000000000000098 "Root=1-000000ea-0000000000000000000000ad" "teleport.example.com" "session-reused" 5 2023-06-06T03:15:54.419000Z "waf,forward" "-" "-" "192.0.0.50:3080" "-" "-" "-"
```

Clicking into the 504 in the chrome dev tool, it shows below:

```
{
"error": {
"message": "need auth"
}
}
```

**Comment by yu-jianshu** [comment]
Hello, may I check if there's any update for this issue? Thanks.

**Comment by wongherlung** [comment]
Hi, we are facing the same issue in the same version. Are there any updates on this?

**Comment by stevenGravy** [comment]
Good to double check the `teleport` binary permissions

```bash
ls -l /usr/local/bin/teleport
-rwxr-x---. 1 root root 231668000 Aug 25 12:09 /usr/local/bin/teleport
```
can cause these issues per SFTP permission.

You will want to make it ` -rwxr-xr-x` permission.

```bash
sudo chmod go+rx /usr/local/bin/teleport
```

**Comment by yu-jianshu** [comment]
> Good to double check the `teleport` binary permissions
> 
> ```shell
> ls -l /usr/local/bin/teleport
> -rwxr-x---. 1 root root 231668000 Aug 25 12:09 /usr/local/bin/teleport
> ```
> 
> can cause these issues per SFTP permission.
> 
> You will want to make it ` -rwxr-xr-x` permission.
> 
> ```shell
> sudo chmod go+rx /usr/local/bin/teleport
> ```
Hi @stevenGravy , Thanks for your suggestions.
I upgraded our teleport version to 14.0.1 and confirm file uploading/downloading issue persists at this version.
Then I exec into the teleport container to check, I think the permission should be fine.
```shell
docker exec -it 54d576c41523 /bin/bash
root@teleport:/# ls -l /usr/local/bin/teleport 
-rwxr-xr-x 1 1000 1000 237134304 Sep 27 10:24 /usr/local/bin/teleport
```

**Comment by jakule** [comment]
>I upgraded our teleport version to 14.0.1
Did you upgrade all components (auth + proxy + all nodes) or just some of them? If not all versions are the same can you please list your configuration?
Do you have SELinux/AppArmor enabled on your system?

**Comment by yu-jianshu** [comment]
Thanks both for looking into this issue.

We never use `tsh scp` before, I tried to use it but I encountered below error, do let me know if there is something wrong in my command.
```
root@teleport:/tmp# tsh scp -l yu_jianshu --proxy 127.0.0.1:3023 --user yu_jianshu  ./test.txt bifrost:/home/yu_jianshu -c main -d --insecure
2023-10-05T15:39:47+08:00 ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:4046
2023-10-05T15:39:47+08:00 DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:3453
2023-10-05T15:39:47+08:00 DEBU [CLIENT]    attempting to use loopback pool for local proxy addr: 127.0.0.1:3023 client/api.go:4008
2023-10-05T15:39:47+08:00 DEBU [CLIENT]    reading self-signed certs from: /var/lib/teleport/webproxy_cert.pem client/api.go:4016
2023-10-05T15:39:47+08:00 DEBU [CLIENT]    using local pool for loopback proxy: /var/lib/teleport/webproxy_cert.pem, err: <nil> client/api.go:4037
2023-10-05T15:39:47+08:00 DEBU             Attempting GET 127.0.0.1:3023/webapi/ping webclient/webclient.go:129
2023-10-05T15:39:47+08:00 WARN             Request for GET 127.0.0.1:3023/webapi/ping falling back to PLAIN HTTP webclient/webclient.go:148

ERROR REPORT:
Original Error: *url.Error Get &#34;http://127.0.0.1:3023/webapi/ping&#34;: EOF
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:152 github.com/gravitational/teleport/api/client/webclient.doWithFallback
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:216 github.com/gravitational/teleport/api/client/webclient.Ping
	github.com/gravitational/teleport/lib/client/api.go:3652 github.com/gravitational/teleport/lib/client.(*TeleportClient).Ping
	github.com/gravitational/teleport/tool/tsh/tsh.go:3454 main.makeClientForProxy
	github.com/gravitational/teleport/tool/tsh/tsh.go:3176 main.makeClient
	github.com/gravitational/teleport/tool/tsh/tsh.go:3146 main.onSCP
	github.com/gravitational/teleport/tool/tsh/tsh.go:1130 main.Run
	github.com/gravitational/teleport/tool/tsh/tsh.go:503 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Get &#34;http://127.0.0.1:3023/webapi/ping&#34;: EOF 
```
All teleport components are in one single container, so they are of the same version.
```
cat teleport.yaml 
teleport:
  nodename: teleport
  log:
    output: stdout
    severity: DEBUG
  data_dir: /var/lib/teleport
  storage:
      path: /var/lib/teleport/backend
      type: dir

auth_service:
  enabled: yes
  authentication:
    type: local
    second_factor: otp
  cluster_name: main
  listen_addr: 0.0.0.0:3025
  client_idle_timeout: 30m
  keep_alive_interval: 30s
  tokens:
    - "node:****************************"

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:3022
  labels:
    cluster: main
    role: teleport

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  public_addr: "teleport.***.***.***.***:443"


docker-compose exec teleport tctl status
Cluster      main                                                                    
Version      14.0.1                                                                  
host CA      never updated                                                           
user CA      never updated                                                           
db CA        never updated                                                           
openssh CA   never updated                                                           
jwt CA       never updated                                                           
saml_idp CA  never updated                                                           
oidc_idp CA  never updated                                                           
CA pin       sha256:*********************

docker-compose exec teleport tctl auth ls
kind: auth_server
metadata:
  expires: "2023-10-05T07:59:13.36786138Z"
  id: 1696492153367968443
  name: 06bcde28-eec3-4d21-a892-cc3bf9f3f649
spec:
  addr: 10.201.0.3:3025
  hostname: teleport
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 14.0.1
version: v2

docker-compose exec teleport tctl proxy ls
kind: proxy
metadata:
  expires: "2023-10-05T07:55:48.877380782Z"
  id: 1696491948884704969
  name: 06bcde28-eec3-4d21-a892-cc3bf9f3f649
spec:
  addr: 127.0.0.1:3080
  hostname: teleport
  public_addr: teleport.***.***.***.***:443
  public_addrs:
  - teleport.***.***.***.***:443
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 14.0.1
version: v2
```
SELinux is disabled in our system but AppArmor is enabled.

And yes I performed file permission check in the teleport node, which is the one and single node runs teleport/auth/proxy/ssh serivce.
