### ISSUE TITLE
Proxy subsystem appears to be case-sensitive.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2833]
When connecting to tunnel nodes, the proxy subsystem attempts to match the requested host against the name of the node. If the node name contains capital letters, it will never match.

To reproduce, create a `teleport.yaml` file like the following:

```
teleport:
  nodename: Server01
  auth_token: [...]
  auth_servers:
    - [...]:3080

auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
   enabled: yes
```

Then attempt to use OpenSSH like the following:

```
ssh -o "HostName Server01" \
    -o "ProxyCommand ssh -oPort=3023 proxy.example.com -s proxy:%h:%p@example.com" \
    Server01
```

But change `nodename` to lowercase `server01` and update the OpenSSH command and everything will work.
