### ISSUE TITLE
Support https scheme for audit_sessions_uri

### ISSUE THREAD

**Issue by djocas-nortal** [gravitational/teleport#28352]
What would you like Teleport to do?

Support `https` scheme for audit session recordings. It would allow sending session recordings to Oracle Cloud bucket. For example, projects like Velero works using https scheme while config properties look like if this is still S3. For example:

```yaml
 config:
    region: <my-oci-region>
    s3ForcePathStyle: 'true'
    s3Url: https://<my-bucket-namespace>.compat.objectstorage.<my-oci-region>.oraclecloud.com
  objectStorage:
    bucket: <my-oci-bucket>
    prefix: <my-oci-prefix>
  provider: aws
```

What problem does this solve?

It would allow users of Oracle Cloud to send session recordings to OCI Bucket 

If a workaround exists, please include it.

N/A

**Comment by programmerq** [comment]
Teleport does support using alternate endpoints for S3 compatible object storage.

https://goteleport.com/docs/reference/backends/#configuring-the-s3-backend

```yaml
teleport:
  storage:
    region: <my-oci-region>
    audit_sessions_uri: "s3://<my-oci-bucket>/path?endpoint=<my-bucket-namespace>.compat.objectstorage.<my-oci-region>.oraclecloud.com"
```

(some third party S3 providers need `&disablesse=true` at the end of the audit_sessions_uri value.)

Since Teleport uses the AWS go SDK, it will load the aws_access_key_id and aws_secret_access_key via the default credential loader-- env variables, or `~/.aws/config` / `~/.aws/credentials`.

Teleport's endpoint URI style is indeed specific to Teleport.
