### ISSUE TITLE
teleport kube agent can create the tls secret to desired namespace

### ISSUE THREAD

**Issue by yidongw** [gravitational/teleport#28509]
What would you like Teleport to do?

teleport kube agent can create the tls secret to desired namespace

For example, if I provide the following value to the teleport kube agent helm chart
```
auth_sign:
- format: db
  host: db.example.com
  out: server
  ttl: 2190h
  secretName: db-example-tls-secret
  secretNamespace: database
- format: db
  host: db.example2.com
  out: crt
  ttl: 2190h
  secretName: db-example2-tls-secret
  secretNamespace: database
```
It would create secrets there

What problem does this solve?
I can use my pg helm chart to reference the secret that is generated by teleport.

Registering a new db to teleport in the k8s would be really easy now.

If a workaround exists, please include it.
