### ISSUE TITLE
[v.13.x] Okta SSO guide asks to create a dev role but the connector doesn't use that role

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#28660]
## Applies To

* https://goteleport.com/docs/access-controls/sso/okta/

I _did not_ check if other SSO guides are affected in a similar way.

## Details

The Okta SSO guide asks you to [create a dev role](https://goteleport.com/docs/access-controls/sso/okta/#step-44-create-a-developer-teleport-role). However, unless I'm mistaken, the auth connector that the guide asks you to configure doesn't utilize the role in any way.

```yaml
kind: saml
metadata:
  name: okta
spec:
  acs: https://teleport.example.com:443/v1/webapi/saml/acs/okta
  attributes_to_roles:
  - name: groups
    roles:
    - editor
    value: okta-admin
  - name: groups
    roles:
    - access
    value: okta-dev
# …
```

This will give users from the okta-admin group the editor role and users from the okta-dev the access role. The dev role doesn't seem to be used in the connector.

## How will we know this is resolved?

When the guide either uses the dev role in the connector or doesn't mention the dev role. It seems to me that the intent might have been to grant the `dev` role to users from the okta-dev group – that would make sense. But if that's the case, the output of some of the commands needs to be updated to account for `access` being replaced with `dev`.
