### ISSUE TITLE
Allow use of environment variables in teleport.yaml

### ISSUE THREAD

**Issue by pirate** [gravitational/teleport#2914]
Proposed behavior:

`docker-compose.yml`:
```yaml
version: '3'
services:
  teleport:
    image: teleport:latest
    ...
    environment:
        - NODE_NAME=server.example.com
        ...
```

`teleport.yaml`:
```yaml
teleport:
  nodename: "$NODE_NAME"
  ...
```

This allows us to share a single static config between all our servers, and load server-specific config from a `.env` file or other environment variable source.
