### ISSUE TITLE
Prevent users from creating Kubernetes resources they don't have access to

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#29245]
What would you like Teleport to do?

Forbid users from creating Kubernetes resources they won't be able to access.

A user with the following role can only create pods in the test namespace.
```
kubernetes_resources:
- kind: pod
  namespace: test
  name: *
```
