### ISSUE TITLE
Non 's3:* resource: *' S3 Permissions don't let teleport start

### ISSUE THREAD

**Issue by redbeard0x0a** [gravitational/teleport#2934]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
I configured an IAM permission for an s3 bucket that isn't overly permissive. I expect this permission to work, but teleport doesn't start because of an s3 permission error (s3:* on * for resources works).

```
  TeleportEcosystemManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub "Teleport Policy for ${Ecosystem}"
      ManagedPolicyName: !Sub "teleport-${Ecosystem}-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:*
            Resource:
              - ...
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::vno-teleport-mars-sbx
              - arn:aws:s3:::vno-teleport-mars-sbx/*
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
            Resource:
              - '*'
```

Config yaml

```
storage:
        type: dynamodb
        region: us-west-2
        table_name: teleport.sbx.mars
        audit_events_uri:  ['dynamodb://teleport-events.sbx.mars']
        audit_sessions_uri: 's3://vno-teleport-mars-sbx'
```

This is running in kubernetes with my own docker container. It fails to start the container with an error shown below.

In order to get the service to start, I had to grant an overly permissive s3 policy:

```
- Effect: Allow
  Action:
  - s3:*
  Resource:
  - '*'
```

**What you expected to happen**:

The teleport service to start. (`teleport start --config=/etc/teleport/config.yaml --insecure-no-tls --diag-addr=0.0.0.0:8080`) with the first s3 permissions.

I also expected to find an example policy in the admin documentation, but I only found one for dynamodb.

**How to reproduce it (as minimally and precisely as possible)**:

Create an IAM user with the permissions listed above (specify a dynamodb table resource). 

**Environment**:
- Teleport version (use `teleport version`): 4.0.4
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release): docker `FROM ubuntu:18.04`

Environment Variables:

- AWS_ACCESS_KEY_ID=...
- AWS_SECRET_ACCESS_KEY=...

**Relevant Debug Logs If Applicable**

```
INFO [PROC]      Generating new host UUID: 7e1e5941-ea86-4d26-b2c6-7cd4e961f093. service/service.go:547
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:171
DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:218
INFO [MIGRATE]   Importing data from legacy backend. legacy/import.go:53
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/proc dir/migrate.go:42
INFO [MIGRATE]   Successfully imported 0 items. legacy/import.go:66
INFO [PROC]      Adding diagnostic debugging handlers. To connect with profiler, use `go tool pprof 0.0.0.0:8080`. service/service.go:1616
DEBU [PROC]      Adding service to supervisor. service:readyz.monitor service/supervisor.go:181
INFO [PROC:1]    Service diag is creating new listener on 0.0.0.0:8080. service/signals.go:213
INFO [DIAG:1]    Starting diagnostic service on 0.0.0.0:8080. service/service.go:1685
DEBU [PROC]      Adding service to supervisor. service:diagnostic.service service/supervisor.go:181
DEBU [PROC]      Adding service to supervisor. service:diagnostic.shutdown service/supervisor.go:181
DEBU [KEYGEN]    SSH cert authority is going to pre-compute 25 keys. native/native.go:103
DEBU [PROC:1]    Using dynamodb backend. service/service.go:2247
INFO [DYNAMODB]  Initializing backend. Table: "teleport.sbx.mars", poll streams every 0s. dynamo/dynamodbbk.go:180
DEBU [DYNAMODB]  AWS session is created. dynamo/dynamodbbk.go:264
INFO [S3]        Setting up bucket "vno-teleport-mars-sbx", sessions path "" in region "us-west-2". s3sessions/s3handler.go:92
DEBU [DYNAMODB]  Found latest event stream arn:aws:dynamodb:us-west-2:761022271947:table/teleport.sbx.mars/stream/2019-08-23T02:48:16.257. dynamo/shards.go:83

ERROR REPORT:
Original Error: *trace.BadParameterError Forbidden: Forbidden
	status code: 403, request id: 59186861376638E8, host id: 4imiw31TRtBAr7pBxWcaj04kJqKvMxXq51lVNPYKn9Ypm87ltACyC9QmFs7PNaMdcU3XudgaD3I=
Stack Trace:
	/gopath/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:249 github.com/gravitational/teleport/lib/events/s3sessions.ConvertS3Error
	/gopath/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:184 github.com/gravitational/teleport/lib/events/s3sessions.(*Handler).ensureBucket
	/gopath/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:92 github.com/gravitational/teleport/lib/events/s3sessions.NewHandler
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:775 github.com/gravitational/teleport/lib/service.initUploadHandler
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:906 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:640 github.com/gravitational/teleport/lib/service.NewTeleport
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:390 github.com/gravitational/teleport/lib/service.newTeleportProcess
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:400 github.com/gravitational/teleport/lib/service.Run
	/gopath/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:179 github.com/gravitational/teleport/tool/teleport/common.OnStart
	/gopath/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:179 github.com/gravitational/teleport/tool/teleport/common.OnStart
	/gopath/src/github.com/gravitational/teleport/tool/teleport/main.go:29 main.main
	/opt/go/src/runtime/proc.go:209 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1338 runtime.goexit
User Message: Forbidden: Forbidden
	status code: 403, request id: 59186861376638E8, host id: 4imiw31TRtBAr7pBxWcaj04kJqKvMxXq51lVNPYKn9Ypm87ltACyC9QmFs7PNaMdcU3XudgaD3I=, initialization failed
```
