### ISSUE TITLE
Support multiple URI values in Applications

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#29419]
What would you like Teleport to do?

Use Teleport as a protected Load Balancer that can spread requests across multiple URIs serving the same application using a single App Service.

There are several scenarios where replicas of the same application run in regional clusters to increase their availability guarantee. Applications are often hidden behind DNS domains where it is impossible to implement any sort of health checks, which means there is no guarantee that the regional cluster is healthy.

Teleport already allows application access sessions to be dispersed across multiple replicas of an `app_service` serving the same application however, this sort of load balancing and health checks is not supported just for a single agent.

This feature will allow the administrator to configure multiple URIs per application, and Teleport will spread the requests randomly or round-robin by each of these URIs. Each time the App service detects that one of the URIs is not operational, it will remove it from the load balancer targets until it becomes healthy again.

Each application session would continue to be tied to a URI just as it is now pinned to a single `app_service`.

```yaml

app_service:
    enabled: yes
    apps:
    - name: "grafana"
      uri: 
      - "https://grafana.us-west-1.test.com"
      - "https://grafana.us-west-2.test.com"
      public_addr: "test.tele.local"
      labels:
        env: "prod"


```
