### ISSUE TITLE
Local User CRUD Web UI 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2945]
We currently provide user CRUD for admins using `tctl`. We should provide the same functionality in the Teleport UI. 

Currently `tctl` admins can currently

```
  users add    Generate a user invitation token [Teleport DB users only]
  users ls     List all user accounts [Teleport DB users only]
  users rm     Deletes user accounts
```

```
User     Roles
-------- -----
benarent admin
jon      admin
twakes   admin
```

Things to considers:
- We should provide an option that an admin can reset a users password / 2FA
- The ability to add / invite new users without having to log into the auth server ( does this require more steps to verify the user )

**Comment by benarent** [comment]
Teleport 5.0 support local CRUD 
![image](https://user-images.githubusercontent.com/559288/99829637-64c4f580-2b11-11eb-97ce-3da6df99d6a6.png)

Note:
```yaml
   - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete 
   - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
```
