### ISSUE TITLE
Allow prompting for a custom reason on regular role requests

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#29475]
### What would you like Teleport to do?
Enhance the functionality of the `request_prompt` field in role configurations. The `request_prompt` field should not only provide a prompt for roles with the `request_access: reason` option set, but also define a custom message instructing users what they need to include with their access request.

For example, given the following role:

<details><summary>expand: `request_prompt: Please enter the Ticket ID`</summary>

```yaml
kind: role
metadata:
  name: example_role
spec:
  allow:
    request:
      roles:
      - example_role
  deny: {}
  options:
    request_prompt: Please enter the Ticket ID
version: v6
```

</details>

The web UI would output the reason in some way so the user can know what is expected of them.

![image](https://github.com/gravitational/teleport/assets/37278/61ccdfad-1eaf-4290-affc-2efdd1ed4f38)

It might even be ideal to prompt the user to rerun with `--request-reason` when requesting a role via `tsh request create` that has a prompt, but the user did not specify the reason.

### What problem does this solve?

Currently, the `request_prompt` field is designed to prompt a message when the role also has the `request_access: reason` option set. The only time this comes up is when using the waiting room / Advanced RBAC feature where the request is created at login.

More specific user-guidance is still helpful for cases where the user is creating a request manually. It will reduce confusion on Teleport end users.

### If a workaround exists, please include it.

There isn't really a good workaround-- The user would just need to know that their Teleport admins require a certain piece of information in the request reason field that is currently marked "(optional)" in the web ui.
