### ISSUE TITLE
Teleport Operator: no invite link after creating a new user

### ISSUE THREAD

**Issue by grossdaniel85** [gravitational/teleport#29626]
**Expected behavior:**

After creating a new user via Custom Resource, the invite link should be displayed in some form.

**Current behavior:**

No invite link, neither in operator logs, nor in the logs of any other teleport deployment. I have to login to the teleport cluster and reset the user manually, which is not intended. 
I also could not find anything in the documentation.

Bug details:
- Teleport version: 13.2.3
- Recreation steps
   - install teleport operator
   - create a new user by applying following configuration:
    ```yaml
    apiVersion: resources.teleport.dev/v2
    kind: TeleportUser
    metadata:
      name: test
    spec:
      roles: []
   ```
