### ISSUE TITLE
Teleport Operator CRD "TeleportRole.resources.teleport.dev" - enums are set as "int32"

### ISSUE THREAD

**Issue by michalbajer** [gravitational/teleport#29686]
Expected behavior:

To be able to set option "create_host_user_mode" correctly as documented as "string" with Teleport Operator

```
---
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: test
spec:
  options:
    create_host_user: true
    create_host_user_mode: drop
  allow:
[...]
```

or please to update the documentation:

- https://goteleport.com/docs/reference/resources/#role
```
    # Controls whether this role supports auto provisioning of SSH users.
    # Options: drop (remove user on session end), keep (keep users at session end)
    #          and off (disable host user creation)
    create_host_user_mode: drop
```

- https://goteleport.com/docs/server-access/guides/host-user-creation/#step-12-configure-a-role
```
    # Allow automatic creation of users.
    create_host_user_mode: drop
```

Current behavior:
the "create_host_user_mode" option was not available in the earlier version. The option was added in version 13.2.5 today.

But according to this commit https://github.com/gravitational/teleport/commit/891c0b6735ccbe049994bbf410f4f295db13ba15 IT was set as "Int32" while it shows as "string" everywhere else?

Bug details:
- Teleport version 
13.2.5

- Recreation steps

1. install teleport operator
2. Try to create "TeleportRole" with "create_host_user_mode" option set to "drop/keep"
```
---
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: test
spec:
  options:
    create_host_user: true
    create_host_user_mode: drop
  allow:
[...]
```

- Debug logs
```
"message: TeleportRole.resources.teleport.dev "test-role" is invalid:
spec.options.create_host_user_mode: Invalid value: "string": spec.options.create_host_user_mode in body must be of type integer
```
