### ISSUE TITLE
Not listening on port 3022 in iot/nat mode and hence ssh not possible

### ISSUE THREAD

**Issue by butsjoh** [gravitational/teleport#2971]
**What happened**:

We have a node that is setup with the iot/nat feature where all traffic is routed over the proxy instead of talking to the proxy and auth server directly. We want to connect to this node using normal ssh and when we do the following:

```
ssh -i /Users/[USER]/.tsh/keys/[PROXY_DOMAIN]/[USER] -p 3022 root@[IOT_NODE_IP] -o ProxyCommand='ssh -i /Users/[USER]/.tsh/keys/[PROXY_DOMAIN]/[USER] -p 3023 root@[PROXY_DOMAIN] -s proxy:%h:%p
```

the output is:

```
subsystem request failed on channel 0 
ssh_exchange_identification: Connection closed by remote host
```

**What you expected to happen**:

Like other nodes that we have in the cluster (that are not iot/nat) the above command works fine so we expected this also to work for an iot/nat node.

**How to reproduce it (as minimally and precisely as possible)**:

The only difference in configuration between the iot/nat node and a none iot/nat node is the following:

iot/nat node: (auth servers pointing to proxy for the tunneling to happen)

```
    auth_servers:
        - [PROXY_DOMAIN]:3080
```

iot/nat node: (directly talking to the proxy)

```
    auth_servers:
        - [AUTH_SERVER_IP]:3025
```

For the rest the configurations are identical and they are both configured to listen on port 3022

```
# This section configures the 'node service':
ssh_service:
    # Turns 'ssh' role on. Default is 'yes'
    enabled: yes

    # IP and the port for SSH service to bind to.
    listen_addr: 0.0.0.0:3022

    # The optional public address the SSH service. This is useful if administrators
    # want to allow users to connect to nodes directly, bypassing a Teleport proxy
    # (see public_addr section below)
    public_addr: [MY_NODE_DOMAIN]:3022

    # See explanation of labels in "Labeling Nodes" section below
    labels:
        role: node
```

Now when we check on the nodes which port they are listening on we see that the iot/nat node is NOT listening on port 3022 and it has all todo with the configuration of auth_servers. We believe that is the reason the ssh command does not work cause the proxy cannot connect to port 3022 of the node when ssh is proxing through the proxy.

Is this to be expected? And if so could we in another way connect to the iot/nat node using normal ssh? (tsh ssh root@[NODE] works for both)

I already filed a support ticket as well cause we have a paying license but are not getting any confirmation if this is expected or not ...

**Environment**:
- Teleport version (use `teleport version`): Teleport v4.0.4 git:v4.0.4-0-g1a2ed507 go1.12.1
- Tsh version (use `tsh version`): Teleport v3.1.5 git:v3.1.5-0-g7621bbd5 go1.11.4
- OS (e.g. from /etc/os-release): Debian 10 Buster
