### ISSUE TITLE
operator: CRDs generated for Tokens are invalid for github rules

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#30049]
### Expected behaviour:

I can create a TeleportProvisionToken with the spec:
```yaml
roles: 
  - Bot
join_method: github
bot_name: my-bot
github:
  allow:
    - repository: org/repo
```

### Current behaviour:

Kubernetes does not store the allow rules. The operator receives an empty allow list, which is illegal and fails to create the token resource.
