### ISSUE TITLE
Can't create u2f user. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3011]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
While working on 4.1 Test plan, I can't seem to sign up with a Yubi key, or Solo Key using Chrome. 

I double checked the input and my key works with Github. 

![image](https://user-images.githubusercontent.com/559288/65452762-b206e380-ddf6-11e9-9b2c-8949e1dff3b4.png)

**What you expected to happen**:
To provide more information about its waiting status / bubble up any errors to the user. 

**How to reproduce it (as minimally and precisely as possible)**:
Create new cluster, set teleport.yaml to below.  Create a new user `sudo tctl users add --roles=admin benarentu2f2`, input Password then test with Yubi Key / Solo Key. 

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

```
teleport:
  nodename: teleport-41Ent-auth
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: cluster-join-token
  auth_servers:
  - [HIDDEN]:3025
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:cluster-join-token
  session_recording: ""
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0
  authentication:
    type: local
    second_factor: u2f
    # this section is needed only if second_factor is set to 'u2f'
    u2f:
       # app_id must point to the URL of the Teleport Web UI (proxy) accessible
       # by the end users
       app_id: https://[HIDDEN]:3080
       # facets must list all proxy servers if there are more than one deployed
       facets:
       - https://[HIDDEN]:3080
proxy_service:
  enabled: "no"
ssh_service:
  enabled: "no"
```

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug
