### ISSUE TITLE
Can't sign into Teleport using G Suite via OIDC unless you're a G Suite admin

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3029]
**What happened**: Regular (non-admin) G Suite users cannot sign into Teleport using their accounts when G Suite is configured via OIDC.

**What you expected to happen**: All users for a given G Suite domain should be able to sign in.

**How to reproduce it (as minimally and precisely as possible)**: Configure G Suite as per instructions in docs.

Teleport OIDC connector:
```
kind: oidc
metadata:
  name: Google
spec:
  claims_to_roles:
  - claim: groups
    roles:
    - admin
    value: devops@example.com
  - claim: groups
    roles:
    - developer
    value: teleport-developers@example.com
  client_id: 2725xxxx.apps.googleusercontent.com
  client_secret: xxx
  issuer_url: https://accounts.google.com
  redirect_url: https://teleport.example.com:3080/v1/webapi/oidc/callback
  scope:
  - https://www.googleapis.com/auth/admin.directory.group.readonly
  - openid
  - email
version: v2
```

Error when trying to sign in as a regular user:
```
{"code":"T1001W","error":"OAuth2 error code=unsupported_response_type, message=bad status code: 403 {\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"forbidden\",\n    \"message\": \"Not Authorized to access this resource/api\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Not Authorized to access this resource/api\"\n }\n}\n","event":"user.login","method":"oidc","success":false,"time":"2019-09-27T08:57:09Z","uid":"60b1720a-8d6a-4994-a908-0844346d23d5"}
```

**Environment**:
- Teleport version (use `teleport version`): `4.0.9`
- Tsh version (use `tsh version`): `4.0.9`
- OS (e.g. from /etc/os-release): irrelevant
