### ISSUE TITLE
AWS app account and role ARN mapping

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#30318]
## Intro

When there are multiple AWS accounts and role names are unique in all the accounts like the below role template, 
```
kind: role
metadata:
 description: Teleport role for read-only access.
 name: read-only
spec:
 allow:
  app_labels:
   env:
   - aws-dev
   - aws-stage
   - aws-prod
  aws_role_arns:
  - arn:aws:iam:acc1:role/readonly 
  - arn:aws:iam::acc2:role/readonly
  - arn:aws:iam:acc3:role/readonly 
```
All the account roles will be shown under the launch icon of the app access as `readonly`
Here in our role example we have 3 ARN's for different accounts so all the roles will be shown as `readonly` on UI.

## Problem

Since there is no differentiation between the roles from a different account, the end-user has no clue which one is the right one. 

## Proposals

It would be nice if mapping the app labels with the `aws_role_arns` is possible on role templates and show only that account-specific role under the launch icon. 

## Work Around

The only workaround is to have a prefix of account alias on the AWS role name eg `acc1-read-only` but for uniformity of naming and AWS governance, it is better to use the same name for all the accounts.
