### ISSUE TITLE
Trying to use a long-lived certificate with the wrong/incorrect system login makes tsh segfault

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3032]
**What happened**:
Issuing a certificate with `tctl auth sign` on an auth server and then trying to use that certificate for `tsh ssh` with an incorrect login username makes `tsh` segfault.

**What you expected to happen**:
The error message from `tsh` should say `access denied to test@server` or similar, rather than segfaulting.

**How to reproduce it (as minimally and precisely as possible)**:
For information: the `logins` for this user are actually not specified, but the user has the `clusteradmin` role which grants login as the `root` user - not sure if this is relevant here but thought I'd include it in case it's important.

User:
```
root@gus-main-auth-0:/# tctl get user/test
kind: user
metadata:
  id: 1569865631292691176
  name: test
spec:
  created_by:
    time: 0001-01-01T00:00:00Z
    user:
      name: ""
  expires: 0001-01-01T00:00:00Z
  roles:
  - clusteradmin
  status:
    is_locked: false
    lock_expires: 0001-01-01T00:00:00Z
    locked_time: 0001-01-01T00:00:00Z
  traits:
    kubernetes_groups: null
    logins: null
version: v2
```

Role:
```
root@gus-main-auth-0:/# tctl get role/clusteradmin
kind: role
metadata:
  id: 1569863314494056944
  name: clusteradmin
spec:
  allow:
    kubernetes_groups:
    - system:masters
    logins:
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
  deny:
    logins: null
  options:
    cert_format: standard
    forward_agent: true
    max_session_ttl: 12h0m0s
    port_forwarding: true
version: v3
```

To repro - issue a long-lived certificate using `tctl` on the auth server:
```
root@gus-main-auth-0:/# tctl auth sign --ttl=14800h --user=test --out=test.pem

The certificate has been written to test.pem
```

Copy that certificate to the local machine, then use it with a local `tsh` client (with a system username that is not `root`) and observe the segfault:
```
$ tsh --debug ssh -i test.pem --proxy=gus-main.gravitational.co:3080 test@gus-main-auth-0                                                                                                                                                                                                                gus@antaeus
INFO [TSH]       Reading identity file: test.pem tsh/tsh.go:1002
DEBU [TSH]       Extracted username "test" from the identity file test.pem. tsh/tsh.go:864
INFO [CLIENT]    Connecting proxy=gus-main.gravitational.co:3023 login='test' method=0 client/api.go:1465
DEBU [CLIENT]    Activating relogin on ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain. client/api.go:306
DEBU [CLIENT]    not using loopback pool for remote proxy addr: gus-main.gravitational.co:3080 client/api.go:1883
DEBU [CLIENT]    HTTPS client init(proxyAddr=gus-main.gravitational.co:3080, insecure=false) client/weblogin.go:252
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xc6337c]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).UpdateProxyHost(...)
	/gopath/src/github.com/gravitational/teleport/lib/client/keyagent.go:118
github.com/gravitational/teleport/lib/client.(*TeleportClient).applyProxySettings(0xc00000d0e0, 0x1, 0xc0005084a0, 0x1e, 0xc00059c6f0, 0xc, 0xc00059c700, 0xc, 0xc0005084e0, 0x1e, ...)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1702 +0x8cc
github.com/gravitational/teleport/lib/client.(*TeleportClient).Login(0xc00000d0e0, 0x1843a00, 0xc0000df980, 0xc0002f1901, 0x1, 0x1, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1530 +0x191
github.com/gravitational/teleport/lib/client.RetryWithRelogin(0x1843a00, 0xc0000df980, 0xc00000d0e0, 0xc0002f1a00, 0x0, 0x1)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:306 +0x12e
main.onSSH(0xc000589200)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:710 +0xd7
main.Run(0xc0000e0010, 0x6, 0x6, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:325 +0x5183
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:170 +0x11c
```

Run the same command again (but use the correct, allowed `root` user this time) and see that the command works as intended:
```
$ tsh --debug ssh -i test.pem --proxy=gus-main.gravitational.co:3080 root@gus-main-auth-0
INFO [TSH]       Reading identity file: test.pem tsh/tsh.go:1002
DEBU [TSH]       Extracted username "test" from the identity file test.pem. tsh/tsh.go:864
INFO [CLIENT]    Connecting proxy=gus-main.gravitational.co:3023 login='root' method=0 client/api.go:1465
INFO [CLIENT]    Successful auth with proxy gus-main.gravitational.co:3023 client/api.go:1471
DEBU [CLIENT]    Found clusters: [{"name":"gus-main.gravitational.co","lastconnected":"2019-09-30T17:58:25.347073669Z","status":"online"},{"name":"gus-east.gravitational.co","lastconnected":"2019-09-30T17:53:36.13399115Z","status":"online"}] client/client.go:104
INFO [CLIENT]    Client= connecting to node=gus-main-auth-0:0@default@gus-main.gravitational.co client/client.go:363
root@gus-main-auth-0:~#
```

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.0.4git:v4.0.4-0-g1a2ed507 go1.12.1
`
- Tsh version (use `tsh version`): `Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1`
- OS (e.g. from /etc/os-release): `Fedora 29`

**Comment by webvictim** [comment]
This may be the same thing as #3365

**Comment by webvictim** [comment]
This also happens when trying to run `tsh ls`.

Default case (with no `-l` or `--login`):
```
$ tsh -d --proxy=gus-main.gravitational.co -i ~/longtest/jenkins.pem ls
INFO             Reading identity file: /home/gus/longtest/jenkins.pem common/identity.go:44
DEBU [TSH]       Extracted username "jenkins" from the identity file /home/gus/longtest/jenkins.pem. tsh/tsh.go:967
INFO [CLIENT]    no host login given. defaulting to gus client/api.go:784
INFO [CLIENT]    Connecting proxy=gus-main.gravitational.co:3023 login='gus' method=0 client/api.go:1599
DEBU [CLIENT]    Activating relogin on ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain. client/api.go:324
DEBU [CLIENT]    not using loopback pool for remote proxy addr: gus-main.gravitational.co:3080 client/api.go:2022
DEBU [CLIENT]    HTTPS client init(proxyAddr=gus-main.gravitational.co:3080, insecure=false) client/weblogin.go:252
^[[Apanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xc8e733]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).UpdateProxyHost(...)
	/gopath/src/github.com/gravitational/teleport/lib/client/keyagent.go:118
github.com/gravitational/teleport/lib/client.(*TeleportClient).applyProxySettings(0xc000203400, 0x1, 0xc0001b5e60, 0x1e, 0xc0004fa4c0, 0xc, 0xc0004fa4d0, 0xc, 0xc0001b5f00, 0x1e, ...)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1840 +0x853
github.com/gravitational/teleport/lib/client.(*TeleportClient).Login(0xc000203400, 0x14846a0, 0xc0003d6d40, 0xc00049f901, 0x1, 0x1, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1664 +0x193
github.com/gravitational/teleport/lib/client.RetryWithRelogin(0x14846a0, 0xc0003d6d40, 0xc000203400, 0xc00049f990, 0x0, 0x12ade08)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:324 +0x12e
main.onListNodes(0xc000340fc0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:642 +0xf4
main.Run(0xc00003c1f0, 0x5, 0x5, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:354 +0x5392
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:185 +0xea
```

It works fine if I specify a login that the `jenkins` user should have access to (`root` in this case):

```
$ tsh -d --proxy=gus-main.gravitational.co -i ~/longtest/jenkins.pem --login=root ls
INFO             Reading identity file: /home/gus/longtest/jenkins.pem common/identity.go:44
DEBU [TSH]       Extracted username "jenkins" from the identity file /home/gus/longtest/jenkins.pem. tsh/tsh.go:967
INFO [CLIENT]    Connecting proxy=gus-main.gravitational.co:3023 login='root' method=0 client/api.go:1599
INFO [CLIENT]    Successful auth with proxy gus-main.gravitational.co:3023 client/api.go:1590
DEBU [CLIENT]    Found clusters: [{"name":"gus-main.gravitational.co","lastconnected":"2020-04-02T14:14:44.232766169Z","status":"online"},{"name":"gus-east.gravitational.co","lastconnected":"2020-04-02T14:13:05.967866464Z","status":"online"}] client/client.go:106
DEBU [CLIENT]    Client  is connecting to auth server on cluster "gus-main.gravitational.co". client/client.go:469
Node Name       Address         Labels                                                    
--------------- --------------- --------------------------------------------------------- 
gus-main-auth-0 127.0.0.1:3022  environment=demo, kernel=4.14.138+                        
                                role=auth, uptime=up 6 weeks, 5 days, 3 hours, 56 minutes 
gus-main-node-0 10.4.0.224:3022 environment=demo, kernel=4.14.138+                        
                                role=node, uptime=up 6 weeks, 5 days, 3 hours, 56 minutes 
gus-main-node-1 10.4.0.223:3022 environment=demo, kernel=4.14.138+                        
                                role=node, uptime=up 6 weeks, 5 days, 3 hours, 56 minutes 
gus-main-node-2 10.4.0.222:3022 environment=demo, kernel=4.14.138+                        
                                role=node, uptime=up 6 weeks, 5 days, 3 hours, 56 minutes 
```

**Extra info**
- I added the `jenkins` user with `tctl users add jenkins --roles=clusteradmin`
- I generated the `jenkins.pem` cert with `tctl auth sign --ttl=87600h --user=jenkins --out=jenkins.pem`
- This is the `clusteradmin` role which the `jenkins` user has:
```yaml
root@gus-main-auth-0:~# tctl get role/clusteradmin
kind: role
metadata:
  id: 1585759087035857451
  name: clusteradmin
spec:
  allow:
    kubernetes_groups:
    - system:masters
    logins:
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
  deny:
    logins: null
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 12h0m0s
    port_forwarding: true
version: v3
```
