### ISSUE TITLE
[Helm Chart] Unable to start auth service after switching to dynamodb backend

### ISSUE THREAD

**Issue by drewwells** [gravitational/teleport#3056]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
Deployed a pod using the teleport.storage.type=dynamodb. The auth service does not start in fact no services will start once dynamodb is enabled. Changing storage back to `dir` resolves the issue.

**What you expected to happen**:
Auth web service to start
**How to reproduce it (as minimally and precisely as possible)**:
helm upgrade -i {helm chart} with this yaml
```
teleport:
  auth_servers:
  - arealdomain.com:3080
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
  storage:
    audit_sessions_uri: s3://s3-bucket
    region: us-east-1
    table_name: teleport
    type: dynamodb
```
**Environment**:
- Teleport version (use `teleport version`): 4.1.0
- Tsh version (use `tsh version`): N/A
- OS (e.g. from /etc/os-release): container image, appears to be debian based

**Relevant Debug Logs If Applicable**

- tctl --debug status

```
tctl status -d
DEBU             DEBUG logging enabled logrus/exported.go:117
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:173
DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:220

ERROR REPORT:
Original Error: *trace.AccessDeniedError tctl must be used on the auth server
Stack Trace:
        /gopath/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:141 github.com/gravitational/teleport/tool/tctl/common.connectToAuthService
        /gopath/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:109 github.com/gravitational/teleport/tool/tctl/common.Run
        /gopath/src/github.com/gravitational/teleport/tool/tctl/main.go:34 main.main
        /opt/go/src/runtime/proc.go:209 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1338 runtime.goexit
User Message: tctl must be used on the auth server
```
