### ISSUE TITLE
audit_table_name doesn't appear in the DynamoDB section of the admin guide

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3071]
**What happened**: Customer asked how to configure DynamoDB integration to use two separate tables for cluster state storage and audit log storage, because it isn't clear from the docs.

**What you expected to happen**: This should be clear from the docs.

Here's the actual way the config works (as taken from https://github.com/gravitational/teleport/blob/master/assets/marketplace/files/bin/teleport-generate-config#L61-L66):

```
teleport:
  storage:
    type: dynamodb
    region: us-west-2
    table_name: teleport_state
    audit_table_name: teleport_audit
    audit_sessions_uri: s3://example.s3.bucket/records
```
