### ISSUE TITLE
Helm Chart does not apply TLS Certificate to Ingress

### ISSUE THREAD

**Issue by andeke07** [gravitational/teleport#30722]
Expected behavior:
Using the Helm Chart to spin up a Teleport Cluster (v13.3.4) in MicroK8s I set the following settings:
```yaml
clusterName: teleport.my.domain
service:
  spec: {}
  type: ClusterIP
highAvailability:
  certManager:
    addCommonName: true
    enabled: true
    issuerGroup: cert-manager.io
    issuerKind: ClusterIssuer
    issuerName: letsencrypt-prod
ingress:
  enabled: true
  spec:
    ingressClassName: public
  suppressAutomaticWildcards: false
```
Cert-Manager goes off and generates my certificate (automatically named teleport-tls) and should be applied to my ingress

Current behavior:
The TLS certificate is not applied to my ingress. It is created and valid, but not applied:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  ingressClassName: public
  tls:
    - hosts:
        - teleport.my.domain
        - '*.teleport.my.domain'
  rules:
    - host: teleport.my.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport
                port:
                  number: 443
    - host: '*.teleport.my.domain'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport
                port:
                  number: 443
```

I need to manually add this to my ingress:
```yaml
spec:
  ingressClassName: public
  tls:
    - hosts:
        - teleport.my.domain
        - '*.teleport.my.domain'
      secretName: teleport-tls # this line here needs manually adding to the ingress after it is created
```

If I try to add this in to the ingress config myself in the helm chart, there is an error presented about duplicate keys
```yaml
ingress:
  enabled: true
  spec:
    ingressClassName: public
    tls: 
      - hosts:
        secretName: teleport-tls
  suppressAutomaticWildcards: false
```

Am I missing something, or should the certificate that is automatically generated by cert-manager be applied to the ingress?

**Comment by andeke07** [comment]
Additionally, I have discovered that the ingress will return a 502 error because it is trying to contact the backend with HTTP. I needed to add the following annotation to the Ingress to allow it to work: `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"`

**Comment by webvictim** [comment]
Can you share the full error regarding the duplicate keys? I agree that the `Ingress` should take the cert-manager secret into account if that section is present in the config, that's a bug that can be fixed.

**Comment by IlyaPvd** [comment]
Hello!
I get the same error when installing teleport from helm chart:

values.yml:

```
proxyListenerMode: multiplex
acme: false

proxy:
  service:
    type: ClusterIP

annotations:
  ingress:
    cert-manager.io/cluster-issuer: letsencrypt

proxy_service:
  enabled: true
  listen_addr: 0.0.0.0:3080
  public_addr: <public address>:443

ingress:
  enabled: true
  suppressAutomaticWildcards: true
  spec:
    ingressClassName: nginx

```
CHART VERSIONS - 14.0.0.

after installing the chart, it becomes necessary to manually set spec.tls.secretName. The certificate was issued, but nginx gives an error 502.

```
kubectl get all -n teleport-cluster
NAME                                          READY   STATUS    RESTARTS   AGE
pod/teleport-cluster-auth-8f8b87f5-gjkj8      1/1     Running   0          5m14s
pod/teleport-cluster-proxy-6978c84bb8-mwr6b   1/1     Running   0          5m14s

NAME                                TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
service/teleport-cluster            ClusterIP   10.43.24.85   <none>        443/TCP             5m14s
service/teleport-cluster-auth       ClusterIP   10.43.55.7    <none>        3025/TCP,3026/TCP   5m14s
service/teleport-cluster-auth-v13   ClusterIP   None          <none>        <none>              5m14s
service/teleport-cluster-auth-v14   ClusterIP   None          <none>        <none>              5m14s

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/teleport-cluster-auth    1/1     1            1           5m14s
deployment.apps/teleport-cluster-proxy   1/1     1            1           5m14s

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/teleport-cluster-auth-8f8b87f5      1         1         1       5m14s
replicaset.apps/teleport-cluster-proxy-6978c84bb8   1         1         1       5m14s
```
