### ISSUE TITLE
Agent joins the wrong port using https schema for `proxy_server`

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#30863]
Expected behavior:
Sample config:
```
ersion: v3
teleport:
  nodename: "iam_join"
  data_dir: "/var/lib/teleport"
  join_params:
    token_name: iam-token
    method: iam
  proxy_server: https://exmaple.teleport.com
```
Agent should join successfully to Proxy `exmaple.teleport.com:443`.

Current behavior:
Agent attempts port `:3080`
```
2023-08-22T17:22:30Z DEBU [AUTH]      Registering node to the cluster. proxy-server:{example.teleport.com:3080 https } auth/register.go:256
```

Bug details:
- Teleport version: v13.1.1
