### ISSUE TITLE
Improve Labels for Desktops

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#30886]
What would you like Teleport to do?

When adding a lot of Windows Servers, adding static labels is a bit tricky. The UX could be improved with better alias names. 
<img width="1016" alt="image" src="https://github.com/gravitational/teleport/assets/559288/5d88cbbb-352c-4c5f-bd48-551d791eb6b5">

What problem does this solve?
Better usability / navigation when a user has a lot of servers. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
I'm thinking we probably deprecate `hosts:` and `non_ad_hosts:` in the config file (they are just list of strings) in favor of a composite data type. Something like:

```
static_hosts:
- name: bens-desktop
  addr: 44.224.121.139
  labels:
    foo: bar
    baz: quux
  ad: true
- name: non-ad
  addr: desktop.example.com
  labels:
    env: dev
  ad: false
```
