### ISSUE TITLE
Teleport node agent registering wrong ip

### ISSUE THREAD

**Issue by jorgeimar** [gravitational/teleport#31013]
Hello, i installed the node agent on a new server i want to enable ssh access to that server, i have several servers already working ok. But this new server is in another cloud provider, i have all the network rules in place and i see the server record on the teleport GUI, but the record says that the ip of the server is 10.xxx.xxxx.xxx, so that ip is not available from the teleport proxy, when i try to connect i got:

failed connecting to node xxxxxxxxxx. Teleport proxy failed to connect to "node" agent "10.xxx.xxx.xxx:3022" over reverse tunnel:

  no tunnel connection found: no node reverse tunnel for 233f475a-xxxxx-xxxx-xxxx found

This usually means that the agent is offline or has disconnected. Check the
agent logs and, if the issue persists, try restarting it or re-registering it
with the cluster.

I think the problem is because the agent i installed on the new server reports a local ip to teleport (instead the public ip), i checked the docs but didnt find a variable or config to record the public ip of the server. Is there a way to achieve this?

Thanks in advance.

**Comment by zmb3** [comment]
If you have a node in a different cloud, you probably want to use tunneling instead of direct dial. Can you share the teleport.yaml you're using on the new node? (Please redact any secrets like join tokens)

**Comment by jorgeimar** [comment]
Sure, this is:

teleport:
  data_dir: /var/lib/teleport
  nodename: estafeta-prod
  log:
    output: stderr
    severity: INFO
    format:
      output: text

  auth_token: xxxxxxx
  ca_pin: sha256:xxxxxxx
  auth_servers:
  - xx.xxx.xxx.xxx:3025
ssh_service:
  enabled: true
  labels:
    env: xxxx
    hostname: xxxx
    provider: xxxx
auth_service:
  enabled: false
proxy_service:
  enabled: false



I tried adding:

  listen_addr:
  public_addr:
  
  
 With the public address of my server but didint work.
 
 Thanks for your help.

**Comment by jorgeimar** [comment]
The new node appears on the teleport gui, so the communication is ok from new node to teleport server, but the ip registered on teleport servers is the local ip of the new node, not the public ip.

**Comment by zmb3** [comment]
You have two options.

If you want to use direct dial (which is what you have set up now) then you'll need the following configuration.

```
teleport:
  auth_servers:
  - xx.xxx.xxx.xxx:3025

auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:3022
  public_addr: foo.example.com:3022
```

This requires that your Teleport proxy can dial the public addr of the node. This means you likely need both a public IP and an inbound firewall rule to allow traffic incoming on port 3022.

The simpler approach (IMO) is to use tunneling. For that, you'd change your config to `v3` and specify proxy server instead.

```
version: v3
teleport:
  proxy_server: proxy.example.com:3080 # (or 443)

auth_service:
  enabled: no

proxy_service:
  enabled: no

ssh_service:
  enabled: yes
```
