### ISSUE TITLE
failed to switch Protocols 400 when running behind GCP ALB

### ISSUE THREAD

**Issue by jamesagarside** [gravitational/teleport#31202]
Expected behavior:
When logging in via `tsh` I get the error `failed to switch Protocols 400`, I would expect this to login.

Current behavior:
```
tsh login --proxy teleport.example.co --auth github
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:52164/xxxxxxxxxxxxxxxxxxxxxxxx
ERROR: Unable to connect to ssh proxy at teleport.example.co:443. Confirm connectivity and availability.
failed to switch Protocols 400
```
I can login successfully via browser. 

Bug details:
- Teleport version: 13.3.5
- Debug logs
### Helm Values
```
acme: false
service.type: NodePort
proxyListenerMode: multiplex
ingress:
  enabled: "true"
  proxyListenerMode: "multiplex"
  service.type: "LoadBalancer"
annotations:
  ingress:
    ingress.gcp.kubernetes.io/pre-shared-cert: "teleport-cert"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
  service: 
    cloud.google.com/app-protocols: '{"tls":"HTTPS"}'
    cloud.google.com/backend-config: '{"default": "teleport-backend-config"}'
proxy:
  teleportConfig:
    proxy_service:
      trust_x_forwarded_for: "false"
```
The backend config just sets the health check path and protocol.

### WebAPI Ping
```
curl https://teleport.example.co/webapi/ping | jq . 
{
  "auth": {
    "type": "local",
    "second_factor": "on",
    "preferred_local_mfa": "webauthn",
    "allow_passwordless": true,
    "allow_headless": true,
    "local": {
      "name": ""
    },
    "webauthn": {
      "rp_id": "teleport.example.co"
    },
    "private_key_policy": "none",
    "device_trust_disabled": true,
    "device_trust": {
      "disabled": true
    },
    "has_motd": false,
    "default_session_ttl": "12h0m0s"
  },
  "proxy": {
    "kube": {
      "enabled": true,
      "listen_addr": "0.0.0.0:3080"
    },
    "ssh": {
      "listen_addr": "0.0.0.0:3080",
      "tunnel_listen_addr": "0.0.0.0:3080",
      "web_listen_addr": "0.0.0.0:3080",
      "public_addr": "teleport.example.co:443"
    },
    "db": {
      "postgres_listen_addr": "0.0.0.0:3080",
      "mysql_listen_addr": "0.0.0.0:3080"
    },
    "tls_routing_enabled": true,
    "assist_enabled": false
  },
  "server_version": "13.3.5",
  "min_client_version": "12.0.0",
  "cluster_name": "teleport.example.co",
  "automatic_upgrades": false
}
```
