### ISSUE TITLE
GCP discovery config should say labels instead of tags

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#31388]
Right now the discovery config uses `tags` as a filter name:

```yaml
discovery_service:
  enabled: "yes"
  gcp:
    - types: ["gce"]
      project_ids: ["<redacted>"]
      locations: ["us-central1-a"]
      tags:
        "project": "*"
```

But in the code we actually match against labels: https://github.com/gravitational/teleport/blob/bf95126ea140aed72f07678fb2666b952afdcedb/lib/cloud/gcp/vm.go#L173

It is very confusing because users set instance tags and then wonder why matching doesn't work.
