### ISSUE TITLE
[Web] Bad error handling when selecting "User Groups" in the Access Requests dropdown without permission to list them

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#31459]
With the role below, if you navigate to `Access Requests > New Requests` and select "User Groups" in the dropdown selector, an `action denied to perform action "list" on "user_group"` error appears which renders the page unusable.

```
kind: role
metadata:
  name: rbac
spec:
  allow:
    app_labels:
      '*': '*'
    logins:
    - root
    node_labels:
      '*': '*'
  options:
    max_session_ttl: 8h0m0s
version: v3
```

![image](https://github.com/gravitational/teleport/assets/56373201/f7f8bf81-1cf5-4dad-9039-278f7b31f285)

We should ideally not have the option be selectable if you don't have permission. However for now we should just make sure the error message doesn't replace the entire page and the dropdown is still visible so you can select something else.
