### ISSUE TITLE
teleport-kube-agent helm-chart: delete-hook job fails due insufficient permission

### ISSUE THREAD

**Issue by NeuroticalT** [gravitational/teleport#31486]
Expected behavior:
The delete hook succeeds when the service account names are customised via the values.yaml.

Current behavior:

The delete hook fails due to an absent permission.
```ERROR: secrets is forbidden: User "system:serviceaccount:inst-system:teleport-kube-agent" cannot list resource "secrets" in API group "" in the namespace "inst-system"```

The error is caused by a typo on `teleport-kube-agent/templates/delete_hook.yaml` template. The subject of the corresponding role binding does not respect the `serviceAccount.name`.

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport-kube-agent.deleteHookServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-delete-hook
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
```

Bug details:
- Chart: `teleport-kube-agent`
- Chart version: `13.3.7 `
- Recreation steps:
  - Deploy a teleport-kube-agent using the provided helm chart and have the service account name set on the values.yaml
  ```yaml
    serviceAccount:
      create: true
      name: "my-test-sa"
  ```
  - Perform a deploy
  - Trigger the delete hook by either rolling out a change or deleting the the agent
