### ISSUE TITLE
Teleport Does not Add Expires Field to DynamoDB Records

### ISSUE THREAD

**Issue by mabrikan** [gravitational/teleport#31878]
### Expected behavior:
Add `Expires` field to records created in DynamoDB audit events table.

### Current behavior:
When using DynamoDB as a storage for audit events and having `audit_retention_period` set , Teleport is expected to add field `Expires` to records added to DynamoDB table. This is needed in order for DynamoDB TTL to work properly.

In fact, when table creation is delegated to Teleport, the auth service will create the table and set the TTL property to watch for the `Expires` field. However, the field does not exist in any record, making TTL effectively useless.

### Bug details:
- Teleport version: 12.3.0
- Recreation steps
  1. In `teleport.yaml` config file, set DynamoDB as audit log destination. Example:

  ```yaml
            teleport:
              storage:
                type: dynamodb
                table_name: <dynamodb-state-table-name>
                audit_events_uri:  ['dynamodb://<dynamodb-audit-table-name>', 'stdout://']
                audit_retention_period: 5m
                audit_sessions_uri: s3://<teleport-sessions-bucket>/sessions
                region: <aws_region>
  ```

  2. Install Teleport v12.3.0
  3. Examine DynamoDB table rows, there will be no `Expires` field added to any new record.

### Debug logs
N/A
