### ISSUE TITLE
Allow selective Traits and Roles to be included in the Teleport JWT

### ISSUE THREAD

**Issue by nloveupgrade** [gravitational/teleport#32162]
## What would you like Teleport to do?
The Teleport agent should **allow customers to selectively include traits and roles that are placed in the teleport JWT token**. 

By default it would include all roles and traits. Ideally it would take regex to select data that gets sent.

For example:
```
apps:
  - name: my-awesome-app
     public_addr: my-awesome-app.teleport.awesome.com
     uri: "http://awesome-app.awesome.svc.cluster.local"
     rewrite:
       -  jwt_include_traits:
           - email
           - name
           - groups: 
               - ROLE_AWESOME_ADMIN
               - ROLE_AWESOME_USER
               - "*_AWESOME_*"
        -  jwt_include_roles:
           - role-awesome-admin
           - role-awesome-user
           - "*-awesome-*"
```

## What problem does this solve?
This solves the issue of headers being too large when the teleport agent passes the request to an app and the app rejecting the request.

Most apps have a 12kb-16kb header limit. If the average trait name (i.e. Okta) is 20 characters and it gets translated into a teleport role of 20 characters each role a user has takes up 40 characters/bytes. Currently Teleport injects the JWT twice in the headers (Cf-Access-Token & Teleport-Jwt-Assertion) and if used as a bearer token (Authorization: Bearer {{ internal.jwt }}) or another user configured header it's injected 3 times. 

Using Teleport without additional user configured headers means that Teleport effectively has a limit of ~125 roles and using teleport with a user configured header has a limit of ~83 roles.

If this solution is implemented your customers will be able to control which roles get injected into the JWT for specific apps. This means a user can have an unlimited amount of traits/roles without overloading the headers.

With large companies having hundreds or thousands of roles this feature will be the key to Teleport's scalability.

## If a workaround exists, please include it.
None

**Comment by zmb3** [comment]
See also #21849 which is not specific to the app access JWT but the login process in general.

**Comment by webvictim** [comment]
Since this issue was opened, Teleport has partly addressed it in a couple of ways:

1) We now only send the `Teleport-Jwt-Assertion` header by default to all downstream apps, meaning the set of roles/traits is only included once rather than twice - `Cf-Access-Token` is no longer included.

2) We also introduced the ability to configuration whether `roles`, `traits`, `roles-and-traits` or `none` are sent on a per-app basis - see the docs here: https://goteleport.com/docs/application-access/guides/connecting-apps/#configuring-the-jwt-token

This functionality means that for apps where a JWT Bearer token is injected, the base claims can be removed to further reduce the header size:

```yaml
apps:
- name: "dashboard"
  uri: https://localhost:4321
  public_addr: dashboard.example.com
  rewrite:
    jwt_claims: none
    headers:
    - "Authorization: Bearer {{internal.jwt}}"
```

With this said, the original issue raises a good point which is that in the interests of security as well as header size, it may be beneficial to further filter roles/traits sent on a per-app basis. As such, the issue will remain open until this feature request is addressed.
