### ISSUE TITLE
It should be possible to select the attribute to use as username when creating a new user with the OIDC connector

### ISSUE THREAD

**Issue by gpr** [gravitational/teleport#3228]
Currently it's statically set to Email.

https://github.com/gravitational/teleport/blob/46eefa1e0fcf4ab39860151741b07ab0933936f6/lib/auth/oidc.go#L416

Configuration example:

```YAML
kind: oidc
metadata:
  name: oidc_connector
spec:
  username_attribute: username
```
