### ISSUE TITLE
Move full configuration file reference to its own section of the documentation, then provide a more relevant example configuration

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3244]
https://gravitational.com/teleport/docs/admin-guide/#configuration-file contains a very detailed configuration file reference which is very useful as a reference, but is way too over-the-top for most users who are starting out with Teleport.

For an example of how this affects people, see https://community.gravitational.com/t/teleport-add-cluster-err/509 - the config file pasted in that post is very long and lists ciphers/kex algos etc which 99.99% of Teleport users will have absolutely no need to specify. It just needlessly complicates the config file.

I am basing this on the assumption that most people won't read our quick start guide, they'll just go straight to the admin guide and ctrl+F "config" to get something they can copy/paste. I've seen so many posts on the forums and Github with configs that specify ciphers and all those things when there's no need.

We should tidy this up - probably by replacing the example configuration file in the admin guide with a cut-down version containing all the essential features that people will need to set (similar to the output of `teleport configure`, but even that is probably too detailed).

We should then move the current configuration reference to a separate section of the docs and add a note saying that it's intended as a reference, and that if someone wants an example config file they should use the other one in the admin guide section. We can link to one from the other.

**Examples**

This is a sample config file of the type I think we should start people off with (it's got some extra bits removed which most people won't need to set) - we should add the appropriate documentation to each setting though so people know what it does:

```
#
# Sample Teleport configuration file.
#
teleport:
  nodename: examplenode
  auth_token: cluster-join-token
  auth_servers:
  - 127.0.0.1:3025
  log:
    output: stderr
    severity: INFO
  ca_pin: example_ca_pin_hash
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:cluster-join-token
ssh_service:
  enabled: "yes"
  labels:
    db_role: master
    db_type: postgres
  commands:
  - name: hostname
    command: [/usr/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/usr/bin/uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /var/lib/teleport/webproxy_key.pem
  https_cert_file: /var/lib/teleport/webproxy_cert.pem
```

Here is the `teleport configure` output for reference:
```
#
# Sample Teleport configuration file.
#
teleport:
  nodename: graviton
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: cluster-join-token
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:cluster-join-token
  session_recording: ""
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0
ssh_service:
  enabled: "yes"
  labels:
    db_role: master
    db_type: postgres
  commands:
  - name: hostname
    command: [/usr/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/usr/bin/uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /var/lib/teleport/webproxy_key.pem
  https_cert_file: /var/lib/teleport/webproxy_cert.pem
```
