### ISSUE TITLE
Not working proxy to app server

### ISSUE THREAD

**Issue by Andrejd102** [gravitational/teleport#32457]
Good everyone.
I use a teleport to open a randeck in a closed network.
On one site proxying does not work - instead of opening a URL consisting of the application name, the teleport domain takes out the address where proxying is going and sends it to the browser.
Tries to open this link, but ends up getting http://172.31.14.11:4440/user/login - (the application is proxied here in the config)
https://sso.example.com/web/launch/rundeck-pc-frankfurt.sso.example.com/teleport-test.example.com/rundeck-pc-frankfurt.sso.example.com

teleport version 14

Expected behavior: 
The domain rundeck.sso.example.com opens.

Actual behavior:
opens the uri where you need to proxy

**Comment by zmb3** [comment]
This is likely a misconfiguration. Please share the configuration of your app service and we'll do our best to help.

**Comment by Andrejd102** [comment]
Config teleport agent
```
app_service:
  enabled: "yes"
  debug_app: true
  apps:
  - name: prometheus-pc
    uri: http://127.0.0.1:9090
    labels:
      service: prometheus
      landing: aws-pc-prod
    public_addr:
    insecure_skip_verify: False

    rewrite:
      # Rewrite the "Location" header on redirect responses replacing the
      # host with the public address of this application.
      redirect:
      - ""
  - name: rundeck-pc
    uri: http://rundeck-pc.example.com
    labels:
      service: rundeck
      landing: aws-pc-prod
    public_addr:
    insecure_skip_verify: False

    rewrite:
      # Rewrite the "Location" header on redirect responses replacing the
      # host with the public address of this application.
      redirect:
      - "http://rundeck-pc.example.com"
```

config nginx 
```
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

server {
   listen 80 default_server;
   server_name rundeck-pc.example.com;

   # default rundeck location is the root URL
       # and this is the default rundeck location from
       # rundeck container
 location / {
        proxy_pass http://127.0.0.1:4440/;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout  90;
        proxy_redirect   http://127.0.0.1:4440 http://rundeck-pc.example.com;
 }
}
```
