### ISSUE TITLE
Fix YAML syntax in `rewrite.headers` example

### ISSUE THREAD

**Issue by simplcode** [gravitational/teleport#32460]
## Applies To

- https://goteleport.com/docs/ver/13.x/application-access/troubleshooting-apps/

## Details

Below headers part causes "failed parsing the config file: yaml: unmarshal errors:  cannot unmarshal !!map into []string" error
```
    rewrite:
      headers:
      - Origin: https://grafana.teleport.example.com # Teleport application subdomain prepended with "https://"
      - Host: grafana.teleport.example.com # Teleport application subdomain itself
```
headers items must be surrounded by double quotes.

fixed version:
```
    rewrite:
      headers:
      - "Origin: https://grafana.teleport.example.com"
      - "Host: grafana.teleport.example.com"
```
