### ISSUE TITLE
Helm upgrade converting "on" to "true" for proxy_protocol which is giving the error - ERROR: invalid 'proxy_protocol' value "true". Available options are: [on off]

### ISSUE THREAD

**Issue by pvnstty** [gravitational/teleport#32490]
Expected behavior:
Teleport-cluster will be updated with the proxy_protocol without any issues.

Current behavior:
Helm upgrade converting "on" to "true" for proxy_protocol which is giving the error - ERROR: invalid 'proxy_protocol' value "true". Available options are: [on off]
Tried with --set-string for this parameter but it is including quotes which teleport-cluster chart is not allowing and throwing a different error.

Bug details:
- Teleport version - Teleport v14.0.0 git:api/v14.0.0-0-g599429b go1.21.1
- Recreation steps - upgrade teleport-cluster to 14.0 and use proxy_protocol in values file for the helm chart
- Debug logs

**Comment by tigrato** [comment]
@pvnstty 

using the values quoted in the values.yaml fixes the problem
``` 
proxy_protocol: "off"
``` 

This happens because in YAML spec, "on", "ON", "off" and "OFF" are valid boolean. https://github.com/helm/helm/issues/5497

**Comment by pvnstty** [comment]
Thanks @tigrato for the response.

I tried it already with quotes on and off. 
**Without** quotes -  ERROR: invalid 'proxy_protocol' value "true". Available options are: [on off]

With quotes (proxy_protocol: "on") - Error:  {"caller":"loglimit/loglimit.go:119","component":"mx:proxy:web:1","level":"warning","message":"\nERROR REPORT:\nOriginal Error: *trace.BadParameterError connection  rejected because PROXY protocol is enabled but required\nPROXY protocol line wasn\u0026#39;t received. \nMake sure you have correct configuration, only enable \u0026#34;proxy_protocol: on\u0026#34; in config if Teleport is running behind L4 \nload balancer with enabled PROXY protocol.\nStack Trace:\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:571 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detect\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:287 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\truntime/asm_amd64.s:1650 runtime.goexit\nUser Message: connection rejected because PROXY protocol is enabled but required\nPROXY protocol line wasn\u0026#39;t received. \nMake sure you have correct configuration, only enable \u0026#34;proxy_protocol: on\u0026#34; in config if Teleport is running behind L4 \nload balancer with enabled PROXY protocol
.","timestamp":"2023-09-28T10:46:11Z"}
![Screenshot 2023-09-28 at 11 49 17](https://github.com/gravitational/teleport/assets/136603523/4839dde6-1922-44cd-ba05-c868ad5f57de)


I tried proxy_protocol: "on" with teleport version 13.4.0 and it is working fine without any issues.

**Comment by tigrato** [comment]
Can you run 
```
helm template teleport/teleport-cluster --output-dir=./yaml  -f your_values.yaml [--set ...] 

```
And give me the `./yaml/teleport-cluster/templates/proxy/config.yaml` file - you can strip any sensitive information if you have them.

**Comment by pvnstty** [comment]
Please check the attached output. I updated the sensitive values with the generic info
[yaml.zip](https://github.com/gravitational/teleport/files/12751531/yaml.zip)

**Comment by tigrato** [comment]
@pvnstty 

The config is correct. The issue is that your LB doesn't send the proxy header. Either you use a L7 LB or if you use a L4 LB the proxy protocol is disabled there. 
Since Teleport 14,  `proxy_protocol: on` means that Teleport REQUIRES the proxy line. If it doesn't receive it, we reject the request,

Attention, if you run behind a L4 LB, the IP reported by Teleport will be incorrect unless you enable the PROXY protocol.

If you are behind a L7 LB or you don't have Proxy protocol enabled, set  `proxy_protocol: off`

**Comment by pvnstty** [comment]
@tigrato 

1. I have a classic LB created with nginx controller helm - extract from the values-override.yaml used for this helm chart
```
  service:
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: nginx-ingress
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    type: LoadBalancer
  config:
    use-proxy-protocol: true
  metrics:
    port: 10254
    portName: metrics
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true
    serviceMonitor:
      enabled: true
tcp:
  3023: "teleport-cluster/teleport:3023"
  3024: "teleport-cluster/teleport:3024"
  3026: "teleport-cluster/teleport:3026"
portNamePrefix: "tp"
``` 
2. Installed teleport-cluster using the below helm command - As I have LB already created in the above I used service.type=clusterip . And I created ingress in the step 3 manually so I didn't enable ingress in this helm values file.

```
helm upgrade --install --kube-context teleport-dev teleport teleport/teleport-cluster --set service.type=ClusterIP --create-namespace --namespace teleport-cluster -f tp-dev-aws-values.yaml

``` 


3. created ingress for this 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport
  namespace: teleport-cluster
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <url>.com
    secretName: <certname>
  rules:
  - host: <url>.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: teleport
              port:
                number: 3080
``` 

So can you please let me know what would be the proxy-protocol value?

**Comment by tigrato** [comment]
@pvnstty your message is no longer available but your nginx ingress is acting as a L7 lb, thus teleport doesn't receive any traffic with proxy header prefix.
Either use NLB directly or disable proxy_protocol

**Comment by pvnstty** [comment]
It got deleted by accidentally. 
In summary, we have an aws classic LB ->nginx controller (nginx rules) -> proxy/auth.

I disabled proxy_protocol: "off" and its giving the below warning:
{"caller":"loglimit/loglimit.go:159","component":"mx:proxy:tunnel:web:1","level":"warning","message":"\nERROR REPORT:\nOriginal Error: *trace.BadParameterError external PROXY protocol support is disabled\nStack Trace:\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:452 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detect\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:287 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\truntime/asm_amd64.s:1650 runtime.goexit\nUser Message: external PROXY protocol support is disabled","timestamp":"2023-09-29T12:49:23Z"}

And also now I am not able to connect to teleport via terminal using tsh 
ERROR: Unable to connect to ssh proxy at teleport-dev3.cloudops-dev.actiandatacloud.com:3023. Confirm connectivity and availability. Error: ssh: handshake failed: EOF

**Comment by tigrato** [comment]
@pvnstty 

Since you run `proxy_listener_mode: separate`, it looks that some of your traffic goes directly from the NLB to Teleport and other traffic (web is going through the nginx ingress).

Teleport has two modes:
- `on` - requires the proxy line to be present
- `off` - denies any request with the proxy line present

Given this, you can't have requests that include/don't include the PROXY line because teleport will deny them.

What I would suggest you is to remove the ingress from the equation and expose Teleport web via NLB directly, or if you need the ingress you can transform it into a L4 passthrough that consumes and produces Proxy line. With that you can enable proxy protocol and everything will work correctly

**Comment by pvnstty** [comment]
@tigrato 

The same architecture with proxy_protocol: "on" is working in 13.4.0 but why not from 14.0?
And also with ingress we can't implement L4 as kubernetes ingress works with L7. 
So you are advising --- AWS NLB -> proxy pods (no nginx controller in the middle) ?

**Comment by tigrato** [comment]
@pvnstty 

Yeah, with Teleport 14 we improved the overall security by editing the definition of the on mode.
Previously the on mode was acting as maybe teleport receives the proxy header and if so, it will parse it. This is a security problem for most users because of misconfigured LBs when proxy_protocol: on.
If the LB doesn't send the proxy line, an attacker can bypass all IP pinning restrictions by injecting a malicious proxy header. This is a quite common scenario and it's not that trivial to debug because teleport works correctly with and without the proxy line.
So, for 14 we had to prevent that situation and change the default behavior of on, so it will require the proxy line in order to accept the connection.

Yes, I meant removing nginx and exposing teleport via the LB.
If you don't want to expose so many ports, I recommend you to use the multiplex mode where all connections (kube, ssh, web) are multiplexed in the same web port.

Feel free to ping me if you need further help.
We also have an RFD that explains the proxy protocol change. It lives in our rfd folder and the number is 146. 

https://github.com/gravitational/teleport/blob/master/rfd/0146-proxy-protocol-default-value.md

**Comment by pvnstty** [comment]
@tigrato 

I removed the nginx completely and let helm teleport chart create the NLB as I am using https://goteleport.com/docs/deploy-a-cluster/helm-deployments/aws/#using-your-own-tls-credentials and updated DNS records in route 53 and security groups and also set the `proxy_listener_mode: multiplex`.

Now I am able to login via web UI and tsh from my terminal but not able to get the pods from the cluster. Do I need to open any other ports?
`values % tsh kube login teleport-dev-cluster
Logged into Kubernetes cluster "teleport-dev-cluster". Try 'kubectl version' to test the connection.
values % kubectl get pods -A
Unable to connect to the server: EOF`

**Comment by tigrato** [comment]
@pvnstty can you share your kubeconfig and the output of https://<public_address>/webapi/ping

**Comment by pvnstty** [comment]
@tigrato 

kubeconfig for teleport-dev-cluster from teleport cluster
```
- name: <tp-cluster>.com-teleport-dev-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=teleport-dev-cluster
      - --teleport-cluster=<tp-cluster>.com
      - --proxy=<tp-cluster>.com:443
      command: /usr/local/bin/tsh
      env: null
      provideClusterInfo: false
``` 
Output of https://<public_address>/webapi/ping
```

{"auth":{"type":"local","second_factor":"on","preferred_local_mfa":"webauthn","allow_passwordless":true,"allow_headless":true,"local":{"name":""},"webauthn":{"rp_id":"<tp-cluster>.com"},"private_key_policy":"none","device_trust_disabled":true,"device_trust":{"disabled":true},"has_motd":false,"default_session_ttl":"12h0m0s"},"proxy":{"kube":{"enabled":true,"listen_addr":"0.0.0.0:3080"},"ssh":{"listen_addr":"0.0.0.0:3080","tunnel_listen_addr":"0.0.0.0:3080","web_listen_addr":"0.0.0.0:3080","public_addr":"<tp-cluster>.com:443","ssh_public_addr":"<tp-cluster>.com:3023","ssh_tunnel_public_addr":"<tp-cluster>.com:3024"},"db":{"postgres_listen_addr":"0.0.0.0:3080","mysql_listen_addr":"0.0.0.0:3080"},"tls_routing_enabled":true,"assist_enabled":false},"server_version":"14.0.0","min_client_version":"13.0.0","cluster_name":"<tp-cluster>.com","automatic_upgrades":false}% 
```

**Comment by pvnstty** [comment]
@tigrato 
One more thing I am still seeing this warning in logs whenever I am issuing kubectl get pods to get the list of pods from the cluster 
```
{"caller":"loglimit/loglimit.go:119","component":"mx:proxy:proxy:kube","level":"warning","message":"\nERROR REPORT:\nOriginal Error: *trace.BadParameterError connection (<my-ip>:13680 -\u0026gt; <private-ip>:443) rejected because PROXY protocol is enabled but required\nPROXY protocol line wasn\u0026#39;t received. \nMake sure you have correct configuration, only enable \u0026#34;proxy_protocol: on\u0026#34; in config if Teleport is running behind L4 \nload balancer with enabled PROXY protocol.\nStack Trace:\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:571 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detect\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:287 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\truntime/asm_amd64.s:1650 runtime.goexit\nUser Message: connection (<my-ip>:13680 -\u0026gt; <private-ip>:443) rejected because PROXY protocol is enabled but required\nPROXY protocol line wasn\u0026#39;t received. \nMake sure you have correct configuration, only enable \u0026#34;proxy_protocol: on\u0026#34; in config if Teleport is running behind L4 \nload balancer with enabled PROXY protocol.","timestamp":"2023-10-02T12:57:03Z"}

```

**Comment by tigrato** [comment]
@pvnstty 
Can you show me the server part of the kubeconfig?

**Comment by pvnstty** [comment]
@tigrato 

Teleport cluster kubeconfig after logged in to the teleport-cluster

```
- name: <tp-cluster>.com-<tp-cluster>.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=<tp-cluster>.com
      - --teleport-cluster=<tp-cluster>.com
      - --proxy=<tp-cluster>.com:443
      command: /usr/local/bin/tsh
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Comment by tigrato** [comment]
@pvnstty 

Those are the `users` entry, I need the `clusters` entry where you can see the `server` and `tls-server-name` entry.

**Comment by pvnstty** [comment]
@tigrato 

```
- cluster:
    certificate-authority-data: <cert>
    server: https://<tp-cluster>.com:443
    tls-server-name: kube-teleport-proxy-alpn.<tp-cluster>.com
```
