### ISSUE TITLE
Unable to access the AWS Console via UI

### ISSUE THREAD

**Issue by shrutijodevops** [gravitational/teleport#32542]
Expected behavior: 

Teleport application should be able to access the AWS console

Current behavior:

I am running both the teleport agent and application on my EKS cluster. When trying to access the application using the tsh cli, it works. However, when I launch the application by selecting the role, it gives me an Access denied error like so:-
<img width="1728" alt="image" src="https://github.com/gravitational/teleport/assets/138460381/e440f90a-1283-4ce3-9727-cb3f15e50459">

If I directly hit the domain "https://awsconsoleqa.zept**.dev/" it gives me a 404 error.

Below is my configuration, I am using the helm chart:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-kube-agent
spec:
  chart:
    spec:
      version: 13.3.5
  values:
    proxyAddr: "go****.zept***.dev:443"
    kubeClusterName: "dev-zepto"
    roles: "kube,app"
    labels:
      cluster: "dev"
    joinParams:
      method: "iam"
      tokenName: "dev-kube-iam-token"
    serviceAccount:
      name: "dev-teleport-kube-agent"
    annotations:
      serviceAccount:
        eks.amazonaws.com/role-arn: "arn:aws:iam::149*****:role/dev-zepto-teleport"
    apps:
    - name: awsconsoleqa
      uri: https://console.aws.amazon.com/ec2/v2/home
      public_addr: awsconsoleqa.zept**.dev
```

**Note that I am using ACM certificate with AWS and not a self signed cert. However, the certificate accepts only subdomains for  `*.zept**.dev `and not two levels down domain like`*.gotele****.zept**.dev`. Hence, I have used the public_address to override the domain as `awsconsoleqa.zept**.dev` instead of `awsconsoleqa.gotel***.zept**.dev`

Bug details:
- Teleport version :       version: 13.3.5
- Recreation steps: follow the steps here : https://goteleport.com/docs/application-access/cloud-apis/aws-console/
- Debug logs
There is only a single pod created for teleport agent:
Failed to handle client connection. error:[
ERROR REPORT:
```
Original Error: *trace.NotFoundError no application at awsconsoleqa.goteleport.zeptonow.dev found
Stack Trace:
	github.com/gravitational/teleport/lib/srv/app/server.go:1014 github.com/gravitational/teleport/lib/srv/app.(*Server).getApp
	github.com/gravitational/teleport/lib/srv/app/server.go:901 github.com/gravitational/teleport/lib/srv/app.(*Server).getConnectionInfo
	github.com/gravitational/teleport/lib/srv/app/server.go:716 github.com/gravitational/teleport/lib/srv/app.(*Server).handleConnection
	github.com/gravitational/teleport/lib/srv/app/server.go:682 github.com/gravitational/teleport/lib/srv/app.(*Server).HandleConnection
	github.com/gravitational/teleport/lib/reversetunnel/transport.go:335 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:581 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: no application at awsconsoleqa.goteleport.zeptonow.dev found] app/server.go:690
```

**Comment by philip-teleport** [comment]
Could it be this issue #30361? Is the DNS record for `*.zept**.dev` pointing at the Teleport Proxy or Proxy Load Balancer?

**Comment by shrutijodevops** [comment]
I have set my DNS like so:



I have a record for`goteleport.zept**.dev` which is the address for my teleport proxy  and that points to the ALB DNS like so


goteleport.zeptonow.dev | A | Simple | - | Yes | zeptonow-15267**.ap-south-1.amazonaws.com)

The I have this public address record like so:-

awsconsoleqa.zeptonow.dev | A | Simple | - | Yes | zeptonow-15267**.ap-south-1.amazonaws.com)

What is this public address field used for? Is it not to override the default domain that teleport uses for the application. 

I didn't want it to have the app domain like awsconsoleqa.gotele**.zept**.com and hence I used the above param in helm

**Comment by shrutijodevops** [comment]
> Could it be this issue #30361? Is the DNS record for `*.zept**.dev` pointing at the Teleport Proxy or Proxy Load Balancer?

I don't have a record for *.zeptonow.dev pointing to teleport proxy. Instead I have `*.goteleport.zeptonow.dev `pointing to proxy. But I don't want to use a domain like `awsconsole.goteleport.zeptonow.dev` for my application. Hence, I used the public address field. Is there something I am missing here? It works fine from CLI though.

**Comment by webvictim** [comment]
The `public_addr` field works the way you think it does. I think this should work.

Can you share the `/etc/teleport.yaml` config file (or Helm values) for the Teleport cluster that this `teleport-kube-agent` is connecting to?

**Comment by shrutijodevops** [comment]
I have removed the `public_addr` field and created a new ACM certificate to resolve `awsconsoleqa.goteleport.zeptonow.dev` and it is working now.

But still curious to know why the `public_addr` didn't work. Here are the helm values for the teleport cluster:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-cluster
spec:
  chart:
    spec:
      version: 13.3.5
  values:
    clusterName: gotel**.zept***.dev
    kubeClusterName: "qa-zepto"
    proxyListenerMode: multiplex
    service:
      type: ClusterIP
    podSecurityPolicy:
      enabled: false
    authentication:
      type: "github"
    labels:
      cluster: qa
    ingress:
      enabled: true
      spec:
        ingressClassName: alb
    annotations:
      ingress:
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/backend-protocol: HTTPS
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/group.name: "external"
        alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=350
        alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
        alb.ingress.kubernetes.io/success-codes: 200,301,302
        external-dns.alpha.kubernetes.io/hostname: 'gotel**.zept**.dev'
        alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:1493*****:certificate/dded3e74-e1***a,arn:aws:acm:ap-south-1:1493*****:certificate/d5f1377e-3****"
```
