### ISSUE TITLE
PAM service name not respected.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3271]
A customer has reported that `service_name` is only respected when it's the first value under PAM.

For example, the following works:

```
ssh_service:
   pam:
      service_name: "teleport"
      enabled: true
```

But the following does not work.

```
ssh_service:
   pam:
      enabled: true
      service_name: "teleport"
```
