### ISSUE TITLE
Installing a teleport in k8s with a steering wheel and ingress, get 502

### ISSUE THREAD

**Issue by IlyaPvd** [gravitational/teleport#32747]
Hello!
I get the same error when installing teleport from helm chart:

values.yml:

```
proxyListenerMode: multiplex
acme: false

proxy:
  service:
    type: ClusterIP

annotations:
  ingress:
    cert-manager.io/cluster-issuer: letsencrypt

proxy_service:
  enabled: true
  listen_addr: 0.0.0.0:3080
  public_addr: <public address>:443

ingress:
  enabled: true
  suppressAutomaticWildcards: true
  spec:
    ingressClassName: nginx
```

CHART VERSIONS - 14.0.0.

after installing the chart, it becomes necessary to manually set spec.tls.secretName. The certificate was issued, but nginx gives an error 502.

```
kubectl get all -n teleport-cluster
NAME                                          READY   STATUS    RESTARTS   AGE
pod/teleport-cluster-auth-8f8b87f5-gjkj8      1/1     Running   0          5m14s
pod/teleport-cluster-proxy-6978c84bb8-mwr6b   1/1     Running   0          5m14s

NAME                                TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
service/teleport-cluster            ClusterIP   10.43.24.85   <none>        443/TCP             5m14s
service/teleport-cluster-auth       ClusterIP   10.43.55.7    <none>        3025/TCP,3026/TCP   5m14s
service/teleport-cluster-auth-v13   ClusterIP   None          <none>        <none>              5m14s
service/teleport-cluster-auth-v14   ClusterIP   None          <none>        <none>              5m14s

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/teleport-cluster-auth    1/1     1            1           5m14s
deployment.apps/teleport-cluster-proxy   1/1     1            1           5m14s

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/teleport-cluster-auth-8f8b87f5      1         1         1       5m14s
replicaset.apps/teleport-cluster-proxy-6978c84bb8   1         1         1       5m14s
```
