### ISSUE TITLE
Access List page is showing in Management when user doesn't have access

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#32900]
Expected behavior:

Like other pages (users, roles,...) this wouldn't show unless the user has access to it.

Current behavior:

Users with minimal access will always see Access Lists.

<img width="995" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/56ed3cd2-60a5-4b06-9b85-18682e9f3b05">

Bug details:
- Teleport version: 13.4.1
- Recreation steps

Configure  a user with this minimal role.  Login with a user with that role.

```
kind: role
metadata:
  name: requester
spec:
  allow:
    request:
      max_duration: 168h0m0s
      roles:
      - '*'
      search_as_roles:
      - access
  deny: {}
  options:
version: v6
```
