### ISSUE TITLE
TeleportRole/v6 has no effect: Failed to calculate user attributes. Role administrators is not found

### ISSUE THREAD

**Issue by dmitry-mightydevops** [gravitational/teleport#32995]
Expected behavior:

When I apply the following manifests

```yaml
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: administrators
spec:
  allow:
    logins:
      - 'administrators'
    kubernetes_groups:
      - 'system:masters'
    node_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: '*'
        namespace: '*'
        name: '*'
        verbs: ['*']

---
apiVersion: resources.teleport.dev/v3
kind: TeleportGithubConnector
metadata:
  name: github
spec:
  api_endpoint_url: ''
  endpoint_url: ''
  client_id: xxx
  client_secret: xxx
  display: 'github'
  redirect_url: https://teleport.domain.comv1/webapi/github/callback
  teams_to_roles:
    - organization: 'org-name'
      team: 'team-devops'
      roles:
        - 'administrators'
```

```
➜ kg teleportrole        
NAME                 AGE
administrators       6m15s

➜ kg githubconnector,githubconnectors
NAME     AGE
github   6m20s
```

I should be able to authenticate into GUI with github SSO

Current behavior:

```
➜ klo -l app.kubernetes.io/component=proxy

{"auth":"github","caller":"web/apiserver.go:1590","component":"web","level":"debug","message":"Web login start.","timestamp":"2023-10-04T20:56:35Z"}
{"auth":"github","caller":"web/apiserver.go:1664","component":"web","level":"debug","message":"Callback start: map[code:[9f793970dfdfdaab2c02] state:[29c34bb79390ca865a5fff55e3c8d076]].","timestamp":"2023-10-04T20:56:36Z"}
{"auth":"github","caller":"web/apiserver.go:1668","component":"web","error":"Failed to calculate user attributes.\n\trole administrators is not found","level":"error","message":"Error while processing callback.","timestamp":"2023-10-04T20:56:36Z"}
```

However if I change the manifest and apply:

```yaml
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: administrators
spec:
  allow:
    logins:
      - 'administrators'
    kubernetes_groups:
      - 'system:masters'
    node_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
```

I.e removed **spec.allow.kubernetes_resources** and apply - then I can authenticate without any problems.

After change back to 

```yaml
apiVersion: resources.teleport.dev/v6
kind: TeleportRole
metadata:
  name: administrators
spec:
  allow:
    logins:
      - 'administrators'
    kubernetes_groups:
      - 'system:masters'
    node_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: '*'
        namespace: '*'
        name: '*'
        verbs: ['*']
```

I can still authenticate

Bug details:
- Teleport version

```
➜ k ice image                                            
PODNAME                         CONTAINER         PULL          IMAGE                                             TAG
teleport-auth-5bb97b4df6-hq695  teleport          IfNotPresent  public.ecr.aws/gravitational/teleport-distroless  14.0.2
teleport-auth-5bb97b4df6-hq695  operator          IfNotPresent  public.ecr.aws/gravitational/teleport-operator    14.0.2
teleport-proxy-ddc945b47-5l2zl  wait-auth-update  IfNotPresent  public.ecr.aws/gravitational/teleport-distroless  14.0.2
teleport-proxy-ddc945b47-5l2zl  teleport          IfNotPresent  public.ecr.aws/gravitational/teleport-distroless  14.0.2

➜ k version  
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

Running as helm chart in **AWS EKS 1.27** with

```yaml
chartMode: aws
  operator:
    enabled: true
    resources: {}
```
