### ISSUE TITLE
Database Access - Add support for Session Tags in STS Assume Role API call

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#33131]
## What 

In case of handing many AWS DB Resource (like DynamoDB table) a separate IAM role needs to be created with proper hardcoded IAM permission. That lead to following problems: 

**IAM Role Management**: Separate IAM roles need to be created and managed for different AWS database resources (like various DynamoDB tables). Each role should ideally follow the principle of least privilege (POLP).
**Scalability Concern:** The creation and management of multiple IAM roles can lead to configuration overhead and might be perceived as not very scalable, especially in environments with numerous AWS resources.

### Proposed Solution:
Using Session Tags in STS Assume Role API:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html 
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "dynamodb:Scan",
      "Resource": "arn:aws:dynamodb:::table/$${aws:PrincipalTag/ddb_table_name}"
    }
  ]
}
```

The above policy allows the entity assuming the role to access the DynamoDB table specified by the TableID session tag dynamically, thus potentially reducing the number of IAM roles required.

Where AWS session Tags can be managed and defined  in Teleport  Role definition: 
```yaml
kind: role
metadata:

  id: 111
  name: dynamodb-dev-write
spec:
  allow:
    db_labels:
      env: dev
    db_names:
    - '*'
    db_users:
    - teleportDDBWriteRole
    - teleportDDBReadRole
    request: {}
    review_requests: {}
  deny: {}
  options:
    aws:
      session_tags: [ { 'ddb_table_name' : "{{internal.db_name}}" } ]
    cert_format: standard
```

 #### 
 **Example Code Snippet (in Go, using the AWS SDK):**
```go
awsConfig.Credentials = aws.NewCredentialsCache(
		stscreds.NewAssumeRoleProvider(sts.NewFromConfig(awsConfig), roleARN, func(options *stscreds.AssumeRoleOptions) {
			options.Tags = tags
		}),
	)
```
