### ISSUE TITLE
Document scalability settings for proxies

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3334]
## Description

In case of 10K+ IOT clusters, the following settings should be set on auth and proxies:

**hardware**

m4.4xlarge | 16 | 64 | EBS-only | 2,000 | High

**proxy server**

```yaml
#proxy
teleport:
  cache:
    # use in memory cache to speed up connections of many teleport nodes
    # back to proxy 
    type: in-memory
  # set up connection limits to prevent throttling of many iot nodes connecting to proxies
  connection_limits:
    max_connections: 65000
    max_users: 1000
```

**auth server**

```yaml
#proxy
teleport:
  connection_limits:
    max_connections: 65000
    max_users: 1000
```
