### ISSUE TITLE
tsh ssh with identity file causes a segfault if you try to use a *nix login that the cert doesn't have privileges for

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3365]
**What happened**: Bit of a long and complicated one. Bear with it. Reported by a customer and verified by me.

Add a `jenkins` user to a host (via `adduser jenkins`) or similar.

Create a `jenkins` role:

```yaml
$ tctl get role/jenkins
kind: role
metadata:
  id: 1582062832369723662
  name: jenkins
spec:
  allow:
    logins:
    - jenkins
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - connect
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - connect
      - list
      - create
      - read
      - update
      - delete
  deny:
    logins: null
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 1h0m0s
    port_forwarding: true
version: v3
```

Create a user:
```bash
$ tctl users add jenkins --roles=admin --logins=jenkins
Signup token has been created and is valid for 1 hours. Share this URL with the user:
https://example.gravitational.co:3080/web/newuser/e28375da1026c303222510459607b56e

NOTE: Make sure example.gravitational.co:3080 points at a Teleport proxy which users can access.
When the user 'jenkins' activates their account, they will be assigned roles [admin]
```

Sign up via the web UI, set up TOTP. Sign in successfully. Then check that the user exists:

```yaml
$ tctl get user/jenkins
kind: user
metadata:
  id: 1582065125543673177
  name: jenkins
spec:
  created_by:
    time: 0001-01-01T00:00:00Z
    user:
      name: ""
  expires: 0001-01-01T00:00:00Z
  roles:
  - admin
  status:
    is_locked: false
    lock_expires: 0001-01-01T00:00:00Z
    locked_time: 0001-01-01T00:00:00Z
  traits:
    kubernetes_groups: null
    logins:
    - jenkins
version: v2
```

Note the addition of `jenkins` as a user under `logins`.

Get a long-lived cert:
```bash
$ tctl auth sign --ttl=87600h --user=jenkins --out=jenkins.pem

The certificate has been written to jenkins.pem
```

Attempt to use the cert to log in as `jenkins`. Observe segfault:

```bash
$ tsh -d ssh -i jenkins.pem --proxy=example.gravitational.co --user=jenkins --auth=local jenkins@example-auth-0
INFO             Reading identity file: jenkins.pem common/identity.go:44
DEBU [TSH]       Extracted username "jenkins" from the identity file jenkins.pem. tsh/tsh.go:945
INFO [CLIENT]    Connecting proxy=example.gravitational.co:3023 login='jenkins' method=0 client/api.go:1588
DEBU [CLIENT]    Activating relogin on ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain. client/api.go:324
DEBU [CLIENT]    not using loopback pool for remote proxy addr: example.gravitational.co:3080 client/api.go:2010
DEBU [CLIENT]    HTTPS client init(proxyAddr=example.gravitational.co:3080, insecure=false) client/weblogin.go:252
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xc72fc3]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).UpdateProxyHost(...)
	/gopath/src/github.com/gravitational/teleport/lib/client/keyagent.go:118
github.com/gravitational/teleport/lib/client.(*TeleportClient).applyProxySettings(0xc0002ca200, 0x1, 0xc00054c1e0, 0x1e, 0xc0002c5340, 0xc, 0xc0002c53c0, 0xc, 0xc00054c200, 0x1e, ...)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1828 +0x853
github.com/gravitational/teleport/lib/client.(*TeleportClient).Login(0xc0002ca200, 0x145f580, 0xc00035c500, 0xc0005b5901, 0x1, 0x1, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1653 +0x193
github.com/gravitational/teleport/lib/client.RetryWithRelogin(0x145f580, 0xc00035c500, 0xc0002ca200, 0xc00015f9a0, 0x0, 0x1)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:324 +0x12e
main.onSSH(0xc000466b40)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:782 +0xd7
main.Run(0xc0000e0010, 0x8, 0x8, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:344 +0x54a5
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:185 +0xea
```

Running `tsh -d ssh -i jenkins.pem --proxy=example.gravitational.co --user=jenkins --auth=local root@example-auth-0` works fine:

```bash
$ tsh -d ssh -i jenkins.pem --proxy=example.gravitational.co --user=jenkins --auth=local root@example-auth-0
INFO             Reading identity file: jenkins.pem common/identity.go:44
DEBU [TSH]       Extracted username "jenkins" from the identity file jenkins.pem. tsh/tsh.go:945
INFO [CLIENT]    Connecting proxy=example.gravitational.co:3023 login='root' method=0 client/api.go:1588
INFO [CLIENT]    Successful auth with proxy example.gravitational.co:3023 client/api.go:1579
DEBU [CLIENT]    Found clusters: [{"name":"example.gravitational.co","lastconnected":"2020-02-18T22:35:23.084264737Z","status":"online"},{"name":"example-east.gravitational.co","lastconnected":"2020-02-18T22:30:35.745282195Z","status":"online"}] client/client.go:106
INFO [CLIENT]    Client= connecting to node=example-auth-0 on cluster example.gravitational.co client/client.go:551
root@example-auth-0:~#
```

**What you expected to happen**: As the user itself has permissions to use the `jenkins` user and the `jenkins` role references `{{internal.logins}}`, I would expect to be able to use `jenkins` as a login.

This may be related to #2561.

In addition, I would not expect trying to use a cert in this way and discovering that it doesn't have permissions to cause a segfault. It should at least print an error detailing that the user's access is denied.

**How to reproduce it (as minimally and precisely as possible)**: See above.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.2.2git:v4.2.2-0-gb06a05d2 go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.2.2 git:v4.2.2-0-gb06a05d2 go1.13.2`
- OS (e.g. from /etc/os-release): `Fedora 30`
