### ISSUE TITLE
Add kube_users impersonation 

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3369]
### Kubernetes user

Sometimes there is a need to impersonate an existing IAM user. Existing teleport mapping only supports `kubernetes_groups`, however there is a need to support `kubernetes_user`.

Here is an example for IBM kubernets clusters:

```yaml
kind: role
spec:
  allow:
    kubernetes_user:
    - 'IAM#{{external.email}}'
```

This will result in `Impersonate-User` to be set to `IAM#sasha@ibm.com`

**Comment by fspmarshall** [comment]
How should teleport handle a scenario where a user holds multiple roles with differing `kubernetes_user` directives?  Would the caller explicitly request a specific user that they want to impersonate (e.g. `tsh login --k8s-user='IAM#alice@example.com'`)?

**Comment by klizhentas** [comment]
I would avoid adding an extra flag, but it's a good question

**Comment by klizhentas** [comment]
I think the way to address that is to allow them to pick the impersonation using native kubernetes tools:

`kubectl --as=IAM#alice@example.com` should work for them in this case, because they can select an identity they prefer from the list of allowed ones.

**Comment by klizhentas** [comment]
So this means that we will have `kubernetes_users` setting that is non scalar, and is a list, by default the first one will be picked if present and we will allow `kubectl --as` impersonation for them to select the identity.

**Comment by fspmarshall** [comment]
> by default the first one will be picked if present

I'd need to run some experiments to be sure, but given that the `Backend` abstraction doesn't guarantee ordering and golang's maps are randomized, this seems equivalent to selecting a random user.  Selecting a random user feels like a confusing default behavior.

**Comment by klizhentas** [comment]
@fspmarshall it's not a map though, but a list

**Comment by klizhentas** [comment]
@fspmarshall I think I understand - you mean that role set is not deterministic? Good point. In this case, how about that - if the role set has just one user to impersonate, it will be picked, otherwise, no user will be picked by default, and client has to specify `kubectl --as` to narrow down the choice.

**Comment by benarent** [comment]
Since we are adding this, I had a look at Kubernetes RBAC. Some thoughts below. 

### Kubernetes Groups & User naming. 
**Current Proposed**
```
kind: role
version: v3
metadata:
  name: admin
spec:
  allow:
    kubernetes_groups: ["system:masters"] 
    kubernetes_user: ["IAM#{{external.email}}"]
```

**Align with Kubernetes RBAC**
Example, that aligns roles to better match Kubernetes. https://kubernetes.io/docs/reference/access-authn-authz/rbac/ RBAC Examples. 

The downside of this is extra YAML and we'll have to still support `kubernetes_groups`, it does provide a framework that aligns with upstream K8s. 

```
kind: role
version: v3
metadata:
  name: admin
spec:
  allow:
     kubernetes: 
     - kind: User
        name: "IAM#{{external.email}}"
     - kind: Group
        name: "system:masters"
```

### Aligning with IBM K8s Flow.
We should make sure this aligns with IBMs guide on setting up `ibmcloud` CLI and subsequent `kubectl` commands. I still need to think about how we provide the smoothest UX for these users.  https://cloud.ibm.com/docs/containers?topic=containers-cs_cli_install
