### ISSUE TITLE
Teleport Ingress Controller

### ISSUE THREAD

**Issue by AlyRagab** [gravitational/teleport#33873]
Expected behavior:
Helm Chart to create Ingress resource

Current behavior:
Nothing is being created
and the below is my values.yaml

```yaml
teleport-cluster:
  create-namespace: True
  namespace: teleport-dev
  publicAddr: teleport.example.com
  clusterName: teleport.example.com
  acme: true
  acmeEmail: acme@example.com
  service:
    type: ClusterIP
  podSecurityPolicy:
    enabled: false
  proxyListenerMode: multiplex
  ingress:
    enabled: true
```

the below is my Chart.yaml

```yaml
apiVersion: v2
name: teleport
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name:  teleport-cluster
  version: 14.1.1
  repository: https://charts.releases.teleport.dev
```

Bug details:
- Teleport Chart version is 14.1.1
- below is the error

```
Error: template: teleport/templates/ingress.yaml:1:14: executing "teleport/templates/ingress.yaml" at <.Values.ingress.enabled>: nil pointer evaluating interface {}.enabled
```
