### ISSUE TITLE
ssh disconnected

### ISSUE THREAD

**Issue by Mario-liemar** [gravitational/teleport#33932]
a fresh install  not able to ssh into the it teleport server

Expected behavior:
ssh to work

Current behavior:
![image](https://github.com/gravitational/teleport/assets/90034463/20e36dc9-c0f2-4da6-b102-84863e5f76fb)
![image](https://github.com/gravitational/teleport/assets/90034463/ccaedca1-87ba-4241-a299-4396192780bd)

config is:
``` 
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022  
  commands:
  - name: hostname
    command: [hostname]
  period: 10m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  peer_listen_addr: 0.0.0.0:3021
  ssh_public_addr: teleport.manti-core.com:3023
  public_addr: teleport.manti-core.com:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```

Log is :

```
ERROR REPORT:
Original Error: *trace.AccessDeniedError invalid username, password or second factor
Stack Trace:

Caught:
        github.com/gravitational/teleport/lib/httplib/httplib.go:206 github.com/gravitational/teleport/lib/httplib.ConvertResponse
        github.com/gravitational/teleport/lib/client/https_client.go:123 github.com/gravitational/teleport/lib/client.(*WebClient).PostJSON
        github.com/gravitational/teleport/lib/client/weblogin.go:452 github.com/gravitational/teleport/lib/client.SSHAgentLogin
        github.com/gravitational/teleport/lib/client/api.go:3984 github.com/gravitational/teleport/lib/client.(*TeleportClient).directLogin
        github.com/gravitational/teleport/lib/client/api.go:3937 github.com/gravitational/teleport/lib/client.(*TeleportClient).localLogin
        github.com/gravitational/teleport/lib/client/api.go:3569 github.com/gravitational/teleport/lib/client.(*TeleportClient).getSSHLoginFunc.func2
        github.com/gravitational/teleport/lib/client/api.go:3767 github.com/gravitational/teleport/lib/client.(root@teleport:/var/lib/teleport/log/54020bf5-650e-4caf-ae89-584192a18b92# 
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs
