### ISSUE TITLE
Support OpenSSH Extensions: permit-X11-forwarding

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3401]
We've a paying customer who's currently patched Teleport to support X11 forwarding as an extension for Teleport.   The team then uses the certificate with OpenSSH to provide access. 

We might want to consider this as an optional extension, set in the role. It should be off by default. 
```
kind: role
metadata:
  name: clusteradmin
spec:
  allow:
...
  options:
    cert_format: standard
    forward_agent: false
    forward_x11: true
    max_session_ttl: 12h0m0s
```
