### ISSUE TITLE
RBAC Rules for session recordings don't work with resource name

### ISSUE THREAD

**Issue by anconrad** [gravitational/teleport#34069]
Expected behavior:
Display a filtered list of session recordings in the WebGui.

Current behavior:
Error Message: "access denied to perform action "list" on "session""

Bug details:
- Teleport version // 14.1.0
- Recreation steps
  - create this role
```yaml
kind: role
metadata:
  description: Review sessions
  id: <my-id>
  name: session-recording-auditor
spec:
  allow:
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
      where: equals(resource.metadata.name, "<my-resource-name>")
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v5
```
  - Record a Session to a host with the filtered name
  - Display the Session Recordings with a user which has this role assigned
