### ISSUE TITLE
Unable to use dedicated kube port when tls routing is enabled

### ISSUE THREAD

**Issue by dboslee** [gravitational/teleport#34178]
Expected behavior:
1. tbot should prefer to use the multiplex tls port (443) when tls routing is enabled even when a dedicated kube port is available.
2. The teleport proxy should be able to handle kubernetes client connections to the dedicated kube port regardless of whether tls routing is enabled.

Current behavior:
1. tbot uses the dedicated kube port when tls routing is enabled.
2. Teleport proxy does not properly handle connections on the dedicated kube port when tls routing is enabled.

Bug details:
- Teleport version

Observed on Teleport Cloud v14.1.1. Works properly on Teleport Cloud v13.4.5.
tbot version 14.1.1

- Recreation steps
1. Configure proxy_listener_mode: multiplex on the auth service
```yaml
auth_service:
...
proxy_listener_mode: multiplex
...
```

3. Configure a dedicated kube_public_addr/kube_listener_addr in the proxy service
```yaml
proxy_service:
...
kube_listen_addr: 0.0.0.0:3026
kube_public_addr: example.teleport.sh:11057
...
```

4. Configure tbot to generate a kubernetes config
```yaml
version: v2

debug: true
auth_server: "example.teleport.sh:443"
certificate_ttl: "1h"

renewal_interval: "1m"

oneshot: false
onboarding:
  token: "xxxxxx"
  join_method: "token"
storage:
  type: directory
  path: ./tbot/data

outputs:
  - type: kubernetes
    kubernetes_cluster: cloud-docker-minikube
    destination:
      type: directory
      path: ./tbot/kube
```
5. Observe ./tbot/kube/kubeconfig.yaml is configured to point at the dedicated port.

```yaml
server: https://example.teleport.sh:11387
tls-server-name: kube-teleport-proxy-alpn.example.teleport.sh
```

6. Observe running a kubectl command using the kubeconfig from tbot fails.
`kubectl version --kubeconfig kubeconfig.yaml`

- Debug logs
```bash
kubectl version --kubeconfig kubeconfig.yaml
Unable to connect to the server: EOF
```
