### ISSUE TITLE
Machine ID: more options in allow rules with support of regex/glob matching for gitlab join method

### ISSUE THREAD

**Issue by Monster1290** [gravitational/teleport#34199]
What would you like Teleport to do?

We would like to have ability to use **_any_** [custom claim field](https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html#token-payload) from gitlab id token JWT in allow rules of a machine id token, such as `ref_protected`, `user_login`, `user_email` etc. Also ability to use glob/regex pattern matching for validating JWT fields values.

Ex. desired config:
```yaml
kind: token
version: v2
metadata:
  name: gitlab-demo-prod-access
spec:
  roles: [Bot-prod-access]
  join_method: gitlab
  bot_name: gitlab-demo
  gitlab:
    domain: gitlab.example.com
    allow:
      - project_path: "my-root-group/my-subgroup/*"
        ref_type: tag
        ref_protected: true
```

As reference point we have similar setup using [bound_claims](https://developer.hashicorp.com/vault/api-docs/auth/jwt#bound_claims) in Vault JWT auth method  and it works great.

What problem does this solve?

This gives us ability to more versatile setup polices to fit our organisation internal security and development standards without a lot of manual work or fussy workarounds. For ex. we want to give SSH access to some host from any gitlab job within projects with mask `someGroup/someSubgroup/*`. Currently we are limited to use `namespace_path` (too wide access for us) or manually add each project to machine id token and maintaining up-to-date state (too much work with 5k+ of projects). Another ex. is restrict access to prod environment only from gitlab jobs which running for protected ref. Ref protection tell us that access to prod is allowed by maintainers/owners of a project.

If a workaround exists, please include it.

Only visible workaround is to self implement sync services. This services will constantly scan Gitlab and using set of rules will keep machine id tokens up-to-date to reflect desired behaviour.
