### ISSUE TITLE
Teleport Kubernetes Operator supports `Bot` resource

### ISSUE THREAD

**Issue by tuladhar** [gravitational/teleport#34285]
## What would you like Teleport to do?
Ability to add Bot resource using [Teleport Kubernetes Operator](https://goteleport.com/docs/management/dynamic-resources/teleport-operator/), currently, it's only available via `tctl`:

```
tctl bots add my-bot --token my-bot-token --roles my-bot-role
```

## What problem does this solve?
- Automates addings bot through Teleport Kubernetes Operator.

## If a workaround exists, please include it.
```
tctl bots add my-bot --token my-bot-token --roles my-bot-role
```

**Comment by strideynet** [comment]
Likely dependent on https://github.com/gravitational/teleport/issues/33808

**Comment by TeleLos** [comment]
[Zendesk 9890](https://gravitational.zendesk.com/agent/tickets/9890) c-cv expressed that they try to manage all their Teleport roles via the Kubernetes operator. Adding this feature would be beneficial to their work flow.

**Comment by yair-segal** [comment]
We would also like to use this feature. Currently this is done manually with the tctl command, post Teleport k8s/helm deployment .

**Comment by MattiasAng** [comment]
Any update on this one? Having to workaround this with `tctl` commands is quite cumbersome in terms of scaling.

**Comment by bfeuillet** [comment]
Hey there,
On my side i'm using FluxCD to automate the deployment of kubernetes resources (helm & co) on my k8s clusters.
I recently deployed the teleport-operator to have role, users, tokens and co as code (yaml).

But like user in this thread, i'm obliged to use tctl one shoot manual command to create bot, would it be possible to create the teleport CRD for bot so the teleport-operator handle the deployment automatically ?

Thanks!

**Comment by strideynet** [comment]
Just an update - this ticket still remains blocked on a problem with an upstream dependency we use to build the Teleport Kubernetes Operator - https://github.com/kubernetes/kubernetes/issues/124154

**Comment by kachi-app** [comment]
Hi @bfeuillet 
Could you please share how you done it ?
I tried concat the yaml, and failed
```
# tbot-operator.yaml
kind: bot
version: v1
metadata:
  # name is a unique identifier for the bot in the cluster.
  name: tbot-operator
spec:
  # roles is a list of roles that the bot should be able to generate credentials
  # for.
  roles:
    - editor
    - mongodb-admin
    - operator

# Kustomize 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: common

configMapGenerator:
  - name: tbot-operator-cm
    options:
      disableNameSuffixHash: true
    files:
      - tbot-operator.yaml=tbot-operator.yaml


# Teleport Cluster YAML
    ## Add tbot-operator for auto generate role
    extraVolumes:
      # Generated from ./configs/bots/kustomization.yaml
      - name: "tbot-operator-cm"
        configMap:
          name: "tbot-operator-cm"
      - name: "apply-on-startup"
        emptyDir: {}

    extraVolumeMounts:
      - name: tbot-operator-cm
        mountPath: /tbot
      - name: apply-on-startup
        mountPath: /opt/teleport

    initContainers:
      - name: "combine-tbot-operator"
        image: "alpine"
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            echo "========================"
            echo "Show tbot-operator.yaml"
            echo "========================"
            cat /tbot/tbot-operator.yaml
            echo "========================"
            echo "Show apply-on-startup.yaml"
            echo "========================"
            cat /etc/teleport/apply-on-startup.yaml
            echo "================================================================================================"
            echo "Concat /tbot/tbot-operator.yaml to /etc/teleport/apply-on-startup.yaml"
            echo "================================================================================================"
            cat /tbot/tbot-operator.yaml /etc/teleport/apply-on-startup.yaml > /opt/teleport/apply-on-startup.yaml
            echo "========================"
            echo "After Merge"
            echo "========================"
            cat /opt/teleport/apply-on-startup.yaml
    extraArgs:
      - "--apply-on-startup=/opt/teleport/apply-on-startup.yaml"
```

**Comment by kachi-app** [comment]
Updates Workaround
------------------------
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-cluster
spec:
  releaseName: teleport-cluster
  chart:
    spec:
      chart: teleport-cluster
      sourceRef:
        kind: HelmRepository
        name: teleport
      version: "17.0.2"
  interval: 10m
# Patch the ClusterRole to allow patching the configmaps
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ClusterRole
              name: teleport-cluster
            patch: |
              - op: add
                path: /rules/0
                value: { "apiGroups": [""], "resources": ["configmaps"], "resourceNames": ["teleport-cluster-auth"], "verbs": ["patch", "get", "update"] }

  values:
    ## Add tbot-operator for auto generate role
    extraVolumes:
      # Generated from ./configs/bots/kustomization.yaml
      - name: "tbot-operator-cm"
        configMap:
          name: "tbot-operator-cm"
      - name: "apply-on-startup"
        emptyDir: {}

    extraVolumeMounts:
      - name: tbot-operator-cm
        mountPath: /tbot
      - name: apply-on-startup
        mountPath: /opt/teleport

    initContainers:
      - name: "patch-tbot-operator"
        image: "bitnami/kubectl:latest"
        command: [ "/bin/sh", "-c" ]
        securityContext:
          runAsUser: 0 # Root user
          runAsGroup: 0
          allowPrivilegeEscalation: true
        env:
          - name: TELEPORT_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            if [ "$TELEPORT_APP_NAME" != "teleport-cluster-auth" ]; then
              echo "TELEPORT_APP_NAME is not equal to 'teleport-cluster-auth'. Exiting with status 0."
              exit 0
            fi
            echo "========================"
            echo "Show tbot-operator.yaml"
            echo "========================"
            cat /tbot/tbot-operator.yaml
            echo "========================"
            echo "Show apply-on-startup.yaml"
            echo "========================"
            cat /etc/teleport/apply-on-startup.yaml
            echo "========================"
            echo "Concat and Generate YAML"
            echo "========================"
            cat <<EOF > /opt/teleport/output.yaml
            data:
              apply-on-startup.yaml: |
            $(cat /etc/teleport/apply-on-startup.yaml | sed 's/^/    /')
                ---
            $(cat /tbot/tbot-operator.yaml | sed 's/^/    /')
            EOF
            
            apt-get update -y
            apt-get install yamllint -y
            
            cat <<EOF > /opt/teleport/.yamllint
            extends: default
            rules:
              document-start: disable  # Disable warnings for missing '---'
              line-length:
                max: 120               # Increase the maximum line length to 120 characters
                level: warning         # Change level to warning
            EOF
            
            yamllint --version
            cat /opt/teleport/.yamllint
            yamllint -c /opt/teleport/.yamllint /opt/teleport/output.yaml
            cat /opt/teleport/output.yaml
            
            cat /etc/os-release
            kubectl patch configmap teleport-cluster-auth -p "$(cat /opt/teleport/output.yaml)" --type=strategic -o yaml
```

Results:
![Image](https://github.com/user-attachments/assets/eb33f505-11bc-4ffe-a697-9fed92dd2cf2)
**teleport-cluster-auth configmap**
```
    ---
    kind: token
    version: v2
    metadata:
      name: "teleport-operator"
    spec:
      roles: [Bot]
      join_method: kubernetes
      bot_name: operator
      kubernetes:
        allow:
          - service_account: "teleport:teleport-cluster-operator"
    ---
    kind: bot
    version: v1
    metadata:
      # name is a unique identifier for the bot in the cluster.
      name: tbot-operator
    spec:
      # roles is a list of roles that the bot should be able to generate credentials
      # for.
      roles:
        - editor
        - mongodb-admin
        - operator
```
Notes:
- After few minutes, the configmap will rollback to previous state without `tbot-operator`. However the bot is still there

**Comment by pksukumar** [comment]
Hi,
There is another workaround to create a bot in programmatic way.
We have to create roles, user and token before this and these can be created through teleport operator automation.
```
apiVersion: resources.teleport.dev/v5
kind: TeleportRole
metadata:
  labels:
    teleport.internal/bot: access-plugin
  name: access-plugin
spec:
  allow:
    rules:
    - resources:
      - access_request
      verbs:
      - list
      - read
      - update
---
apiVersion: resources.teleport.dev/v5
kind: TeleportRole
metadata:
  labels:
    teleport.internal/bot: access-plugin
  name: bot-access-plugin
spec:
  allow:
    impersonate:
      roles:
      - access-plugin
    rules:
    - resources:
      - cert_authority
      verbs:
      - readnosecrets
  deny: {}
---
apiVersion: resources.teleport.dev/v2
kind: TeleportUser
metadata:
  labels:
    teleport.internal/bot: access-plugin
  name: bot-access-plugin
spec:
  roles:
  - bot-access-plugin
---
apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: access-plugin
spec:
  allow:
  - aws_account: "0123456789"
  bot_name: access-plugin
  join_method: iam
  roles:
  - Bot
```

Once above resources are created, you can setup a bot programatically like below. 
(I have changed this New() function as per my requirement - https://github.com/gravitational/teleport/blob/v15.4.24/integrations/lib/embeddedtbot/bot.go#L51)

I need to create a bot which exposes its identity in a directory. You can try identity output to expose identity file as a kubernetes secret to let multiple pod use it to create teleport client object to interact with teleport server.

```
func New(botConfig *config.BotConfig) (*TeleportBot, error) {
	credential := &config.UnstableClientCredentialOutput{}
	idenityOutput := &config.IdentityOutput{
		Destination: &config.DestinationDirectory{
			Path: "/teleport/identity",
		},
		Roles:         []string{"access-plugin"},
		SSHConfigMode: "off",
		Cluster:       strings.Replace(teleportHost, ".freshworkscorp.com", "", -1),
	}

	cfg := (*config.BotConfig)(botConfig)
        cfg.AuthServer: os.Getenv("TELEPORT_PROXY_HOST"), //teleport proxy URL
        cfg.Oneshot:    false,
	cfg.CertificateTTL: time.Duration(12 * time.Hour),
	cfg.Onboarding: config.OnboardingConfig{
		TokenValue: "access-plugin",
		JoinMethod: "iam",
	},
	cfg.Storage = &config.StorageConfig{Destination: &config.DestinationDirectory{
		Path: "/teleport",
	}}
	cfg.Services = config.ServiceConfigs{credential, idenityOutput}

	err := cfg.CheckAndSetDefaults()
	if err != nil {
		return nil, trace.Wrap(err)
	}

	bot := &TeleportBot{
		cfg:            cfg,
		credential:     credential,
		identityOutput: idenityOutput,
	}

	return bot, nil
}

```
