### ISSUE TITLE
Add a new RBAC verb to allow joining current sessions

### ISSUE THREAD

**Issue by jkendzorra** [gravitational/teleport#3439]
### Feature Request
The current verbs for `session` are `[list, read]`; as soon as these are granted, all sessions can be listed and replayed globally. While it's possible to assign `read` only and provide specific session links to restricted users, it currently is not possible for a user to list and join all currently "active" sessions only. It would be really helpful to have a dedicated `join` verb that provides access to currently active sessions [to nodes they have access to] only and allowing them to join these sessions. 

### Motivation
It should be possible to distinguish between a user's ability to see all session history for a team/all team members and actively collaborating with their peers on current work.

### Who's it for?
Enterprise

**Comment by benarent** [comment]
Thanks for the feature request @jkendzorra . This is a timely issue as we'll be changing how we show session in the new Teleport UI scheduled for 5.0. https://github.com/gravitational/teleport/milestone/37 

I'm going to propose that we support.

**Proposal**
```yaml
kind: role
version: v3
metadata:
  name: block-joining-active-sessions
spec:
  # SSH options used for user sessions with default values:
  options:
    # 
   allow:
    # ...
    - resources: [session]
    verbs: [list, read]
   deny:
    # ...
    - resources: [active_session]
    verbs: [list, read, join]
```
