### ISSUE TITLE
teleport configure --test does not validate apps name

### ISSUE THREAD

**Issue by jryberg** [gravitational/teleport#34579]
If a none "domain name" is entered as a name for an app_service then teleport configure --test will be valid but the daemon reload will fail and not start again due to the misconfiguration. 

Expected behavior:
teleport configure --test should fail with exit code != 0

Current behavior:
teleport configure --test does not fail, it's exiting with code == 0

Bug details:
- Teleport version: 14.1.1
- Recreation steps
Add the following snippet to existing config
```
app_service:
  enabled: yes
  apps:
  - name: "incorrect name"
    uri: "http://127.0.0.1:8080"
    labels:
      application: "testing"
```
Execute
`teleport configure --test <path to config>`
The test will pass
- Debug logs
