### ISSUE TITLE
[Teleport Connect] Cannot connect after upgradeing to 14.2 & Changing OIDC settings

### ISSUE THREAD

**Issue by FireDrunk** [gravitational/teleport#34889]
Expected behavior:
Teleport Connect logs in properly.

Current behavior:
Teleport Connect fails with error:
```
Unable to retrieve cluster auth preferences, 2 UNKNOWN:
```

Bug details:
- Teleport version -> 14.1.5 | Connect: 14.2
- Recreation steps
Not sure, I've had GitHub OIDC configured, but have 'disabled' it because I've switched to Local Auth & Passkeys keys.

- Debug logs
Relevant Helm Config options:
```
  authentication:
    type: "local"
    secondFactor: "on"
    connectorName: "passwordless"
```

Auth preference config file in the cluster:
```
❯ tctl get cluster_auth_preference
kind: cluster_auth_preference
metadata:
  id: 1700499669223750648
  labels:
    teleport.dev/origin: config-file
  name: cluster-auth-preference
spec:
  allow_headless: true
  allow_local_auth: true
  allow_passwordless: true
  connector_name: passwordless
  default_session_ttl: 12h0m0s
  disconnect_expired_cert: false
  idp:
    saml:
      enabled: true
  locking_mode: best_effort
  okta: {}
  second_factor: "on"
  type: local
  webauthn:
    rp_id: <public url>
version: v2
```

The error in the debug logs in Teleport Connect:
```
[22-11-23 14:35:19] Original Error: *errors.errorString invalid connector name: github; valid options:
[22-11-23 14:35:19] Stack Trace:
[22-11-23 14:35:19]   github.com/gravitational/teleport/lib/client/api.go:4168 github.com/gravitational/teleport/lib/client.(*TeleportClient).Ping
[22-11-23 14:35:19]   github.com/gravitational/teleport/lib/teleterm/clusters/cluster_auth.go:41 github.com/gravitational/teleport/lib/teleterm/clusters.(*Cluster).SyncAuthPreference
[22-11-23 14:35:19]   github.com/gravitational/teleport/lib/teleterm/apiserver/handler/handler_auth.go:104 github.com/gravitational/teleport/lib/teleterm/apiserver/handler.(*Handler).GetAuthSettings
[22-11-23 14:35:19]   github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go:1175 github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1._TerminalService_GetAuthSettings_Handler.func1
[22-11-23 14:35:19]   github.com/gravitational/teleport/lib/teleterm/apiserver/middleware.go:36 github.com/gravitational/teleport/lib/teleterm/apiserver.New.withErrorHandling.func1
[22-11-23 14:35:19]   github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go:1177 github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1._TerminalService_GetAuthSettings_Handler
[22-11-23 14:35:19]   google.golang.org/grpc@v1.59.0/server.go:1343 google.golang.org/grpc.(*Server).processUnaryRPC
[22-11-23 14:35:19]   google.golang.org/grpc@v1.59.0/server.go:1737 google.golang.org/grpc.(*Server).handleStream
[22-11-23 14:35:19]   google.golang.org/grpc@v1.59.0/server.go:986 google.golang.org/grpc.(*Server).serveStreams.func1.1
[22-11-23 14:35:19]   runtime/asm_amd64.s:1650 runtime.goexit
[22-11-23 14:35:19] User Message: invalid connector name: github; valid options: ] apiserver/middleware.go:38
[22-11-23 14:35:30] INFO             Captured interrupt, stopping service. teleterm/teleterm.go:91
[22-11-23 14:35:30] INFO [DAEMON]    Stopping daemon/daemon.go:650
```
I'm pretty sure this is related to the removal of the OIDC connector, but I think the auth preference file should point Teleport Connect to the local auth connector.

I'm not sure whether this behavior is new in 14.2.
