### ISSUE TITLE
Do multiple postgres server require multiple TLS certificats or one?

### ISSUE THREAD

**Issue by jhoelzel** [gravitational/teleport#34978]
## Applies To

[Selfhosted postgres docs, but i suppose others too](https://goteleport.com/docs/database-access/guides/postgres-self-hosted/)

## Details

I would like to see a mention for multiple database INSTANCES. We are testing teleport right now for our org and would like to find out if multiple servers require multiple certs, or one cert with multiple hostnames.

## How will we know this is resolved?

It would be amazing to add a little note to the self hosted docs that make this clear

## Related Issues

i serach issues and discussions and could not find a mention. if i overlooked it im sorry.

Sidenode:
Thanks for an awesome product

**Comment by greedy52** [comment]
> i tried that and i would always only be able to connect to one of the two instances i have provisioned. It would return a certificate error for the other

Hmm.. what error were you getting? By default, the Database Service will verify both the CA and the server name so the server cert must be signed with all hostnames of the instances, in order to work. Alternatively, you can change the verification mode (usually not recommended):
```yaml
# Lists statically registered databases proxied by this agent.
  databases:
    # Name of the database proxy instance, used to reference in CLI.
  - name: "prod"
    protocol: "postgres"

    # Database connection endpoint. Must be reachable from Database Service.
    uri: "postgres.example.com:5432"

    # Optional TLS configuration.
    tls:
      # TLS verification mode. Valid options are:
      # 'verify-full' - performs full certificate validation (default).
      # 'verify-ca' - the same as `verify-full`, but skips the server name validation.
      # 'insecure' - accepts any certificate provided by database (not recommended).
      mode: verify-full

```
https://goteleport.com/docs/database-access/reference/configuration/

But in general, it's recommended that each instance serves its own cert.

**Comment by greedy52** [comment]
> well the problem starts on the pgadmin end, it simply would not recognize my cert. My environment is two postgres clusters setup with two zalando postgres operators in different namespaces.
> 
> I am providing both tls certificates in different secrets, yet i was never able to connect using pgadmin in the end.
> 
> Therefore i reverted to use one cert for both clusters

Sorry, I am a little confused about the setup now. Does pgadmin access the database, through Teleport or directly?

BTW, you can always use your own self-signed TLS cert for your databases, instead of `tctl auth sign`. In this case, for mTLS between Teleport and your database:
- On database side, just append Teleport's CA to the list that database needs to trust (aka `ssl-ca`). To export Teleport's database CA:
```bash
$ tctl auth export --type db-client
```
(Use `db` instead of `db-client` for older versions that don't have a separate `db-client` CA yet)

- On Teleport side, configure Teleport to trust your self-hosted CA
```
# Lists statically registered databases proxied by this agent.
  databases:
    # Name of the database proxy instance, used to reference in CLI.
  - name: "prod"
    protocol: "postgres"

    # Database connection endpoint. Must be reachable from Database Service.
    uri: "postgres.example.com:5432"

    # Optional TLS configuration.
    tls:
      # TLS verification mode. 
      mode: verify-full
      # Optional path to the CA used to validate the database certificate.
      ca_cert_file: /path/to/your-CA
```

As for the documentation, we usually want to limit the main guide to a single/simple scenario so it's easy to follow. You are welcome to discuss your scenario here or maybe start a discussion thread.
