### ISSUE TITLE
Resource request disappears

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#35112]
Good day colleagues!

First of all, I want to mention that I am user of enterprise teleport and I can provide additional details regarding license.

Secondly, I found an interesting behaviour. I am describing it below.

We are using a bunch of precreated static kubernetes clusters. One cluster per env. So effectively, I have 4 clusters at the moment (common tooling, dev env, uat env, prod env). The cluster dev, uat and prod contains the same set of services. As devops engineer I want to leverage a secure access to clusters and to internal services of the cluster. So I deployed teleport agent in every cluster with means of FluxCD (GitOps) and teleport agent helm chart. All custom settings were pasted into kustomization files - the settings for a particular cluster. I made a mistake and defined a so-called application on the template level side, so all teleport agent picked up a service called test-app:

```yaml
            apps:
              - name: testapp
                uri: http://testapp.******.svc.cluster.local:5000
                description: Internal testapp instance
                labels:
                  env: uat
                  app: testapp
```

So in my webui I see only one button representing this service. I think that first of all it would be nice to have an option to have a several services from different environments under one name. Right now it looks like that the name must be unique and if (by mistake) several teleport agents will expose the same serice name, we will get clash. Or probably we could have better logging from teleport side to find such an issues. Right now it's my task like a devops engineer to prepare a proper teleport config.

The second thing - I think that this clash could affect the access request. I have no strong clues right now, but it is very probable, as I think.

Teleport version 14.2.0
Teleport agent version 14.2.0
On-premise installation
