### ISSUE TITLE
Explicit error when using application in k8s during installation

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#35186]
Good day!

As a DevOps engineer I am installing teleport agent by helm means. I prepared the next values file:

```yaml
    roles: kube,app
    kubeClusterName: huntica-us
    proxyAddr: teleport.***.***.eu:443
    authToken: ****
    apps:
    - name: Weave Gitops
      uri: http://ww-gitops-weave-gitops.flux-system.svc.cluster.local:9001
```

When installing the helm chart I am getting failure without any meaningful error. Particularly when installing by GitOps means - like ArgoCD or FluxCD.

After small debug I understood that the issue is written in the logs:

```bash
gaal@bigsur components % kubectl logs -n teleport teleport-agent-0 
ERROR: application name "Weave GitOps" must be a valid DNS subdomain: https://goteleport.com/docs/application-access/guides/connecting-apps/#application-name
```

In my case the fix was easy:

So I am kindly asking to add a helm helper that will check the name for each element in `apps` array against the proper mask. In such a way I will get the explicit error message and the helm release won't be applied.

```yaml
    roles: kube,app
    kubeClusterName: huntica-us
    proxyAddr: teleport.***.***.eu:443
    authToken: ****
    apps:
    - name: weave # change this line
      uri: http://ww-gitops-weave-gitops.flux-system.svc.cluster.local:9001
```

But the precious time was spent. Also I could not imagine what will happen when using massive amount of apps - any typo could ruin the whole config and lead to many hours of debug.
