### ISSUE TITLE
Trusted Clusters - Mirror Mode

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3546]
### Feature Request
As a user I have central command and control of all my trusted clusters. I’ve over 100+ clusters and as I bring new clusters online I want to be able to add them using as little config as possible. Since I’ve already outlined all of my roles, I want to mirror the same role mapping on the leaf cluster. E.g If I’m ‘admin’ on leaf, I want to be ‘admin’ on root. 

[Google Doc Spec](https://docs.google.com/document/d/1Jf1KzeyX71-E40wqTONq7Gr2ngh3V3Uir7bqc99Y9CE/edit)

**Mapping**
```yaml
# save this as root-cluster.yaml on the auth server of "east" /leaf  and then execute:
# tctl create main-cluster.yaml. In this setup it'll Mirror any permissions 
# from the root. 
kind: trusted_cluster
version: v1
metadata:
  name: root
spec:
  enabled: true
  # in mirror mode leaf cluster will fetch and use the roles of the root
  # cluster, this cluster will not have local users and roles
  # in case if the leaf cluster has non empty local user, role or 
  # connector list, setting mirror mode will fail 
  mode: mirror
  token: "join-token"
  tunnel_addr: root.example.com:3024
  web_proxy_addr: root.example.com:3080
```

Other notes: 
We send the full claims for the root cluster in the certificate. 
What do we need to copy over ? User Object, Role.

Other Questions: This current copies over users and roles only, not auth connectors. 

### Motivation
Describe why we should work on this feature request.

### Who's it for?
OSS User, Pro, Enterprise

gz#4180
