### ISSUE TITLE
Session streaming

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3549]
### Feature Request

* [ ] Session events and commands should be streamed to the auth server in real-time
* [ ] There should be a mode when auth server does not accept the session stream, the session should end
* [ ] Make sure that all session streams are not stored on disk in transit to make sure FedRamp requirements are easy to implement
* [ ] Optimize session streaming for large and long sessions (think gigabytes and hour long sessions)
* [ ] Reconcile all the sessions if abruptly terminated

#### Log format

* [ ] Step 1 is to migrate all session events to protobuf for efficient and fast streaming. The disk format will represent a version of protobuf marshal linear event log using a variation of [Merkle Trees](https://static.usenix.org/event/sec09/tech/full_papers/crosby.pdf) for future validation. 
* [ ] Events are backwards compatible with existing JSON implementation.
* [ ] Compression is achieved by removing gzip and using protobuf instead

### Streaming modes

* [ ] Implement two session streaming modes as RBAC option - `sync` and `async`. In sync streams, session is sent in real time and back pressure (user or process activity is not being processed) is activated if auth server can not be reconnected. In async streams, the stream is sent to the disk and then forwarded to the auth server.

```
kind: role
version: v3
metadata:
  name: admin
spec:
  # SSH options used for user sessions with default values:
  options:
    # recording controls recording modes:
   # sync makes sure streams are sent sync mode with back-pressure and disconnects (slower, more secure)
   # async streams sessions to disk and forwards after the session end (faster, less secure)
   # off turns recording off. This setting is backwards compatible and overrides existing `session_recording` 
   # that is currently available as cluster global setting only and extends more features:
   # * existing `proxy` means `proxy-async`
   # * existing `node` means `node-async`
   # *existing  `off` means session is not recorded
   # * `proxy-sync` and `node-sync` and `proxy-async` and `node-async` are supported
    session_recording: `proxy-sync|proxy-async|node-sync|node-async|off`
```

*  [ ] To resume, the upload will take advantage of the [AWS](https://www.quora.com/Does-Amazon-S3-support-resumable-uploads) multi part upload API. This will allow to achieve a hybrid of real-time and streaming behavior that allows resuming the uploads to another auth server.

When starting upload, the following `stream` resource will be created by the auth server

```yaml
kind: stream
version: v3
name: <session-id>
created: 
updated: 
spec: 
    session_id: <sid>
    # last event committed to the session storage
    last_event_id: 1000
    # last upload part E-Tag
    last_upload_part: <...>
    # all e-tags for upload (will be relevant for GCP that does not have any accounting for part uploads)
    upload_parts: [E-TAGs ] 
    # for amazon, multipart upload ID
    upload_id: <id>
```

Having this object will allow clients to resume streaming if lost connection to the auth server and reconnect to another auth server.

I will also allow auth servers to reconcile uploads that were terminated in flight after period of inactivity what is not happening now.

## Backwards compatibility

For backwards compatibility with all other API, when downloading new stream file for playback, it will be converted to the old format using gzip and json

### Relevant papers

* [Logs and Merkle Trees](https://research.swtch.com/tlog)
  + [Experimental implementation](https://github.com/golang/exp/blob/master/sumdb/internal/tlog/tlog.go)
* [Tamper Evident Logging](https://static.usenix.org/event/sec09/tech/full_papers/crosby.pdf)
* [Streaming for protobuf](https://developers.google.com/protocol-buffers/docs/techniques#streaming)
  + [Stack overflow answer](https://stackoverflow.com/questions/14227355/store-a-set-of-protobufs-on-disk)
* [Resumable uploads](https://www.quora.com/Does-Amazon-S3-support-resumable-uploads)
  [Minio GCS to S3 gateway](https://github.com/minio/minio/blob/master/cmd/gateway/gcs/gateway-gcs.go)

### Duplicate issues

* Dupe https://github.com/gravitational/teleport/issues/3182
