### ISSUE TITLE
Unable to use `tctl` on teleport nodes

### ISSUE THREAD

**Issue by SergeyTsimfer** [gravitational/teleport#35547]
Hi everyone

Great work with Teleport! However, I'm having a following issue:

## Expected behavior:
After I login with `tsh` into cluster, I am able to use `tctl` commands. For example:
```
tsh login --proxy=... --user=teleport-admin
tctl status
```
User teleport-admin has the `access, editor` (default) roles.
I can use `tsh` functionality: ssh into nodes, inspect apps, use apps with the provided certs/keys.

## Current behavior:
Getting `ERROR: tctl must be either used on the auth server or provided with the identity file via --identity flag` error. I've tried to disable teleport config (`TELEPORT_CONFIG_FILE=""`), but to no avail.

## Bug details:
- Teleport version: 14.2.1
- Recreation steps:
- Debug logs

## Config of the master machine:
```yaml
version: v3
teleport:
  nodename: master-machine
  data_dir: /var/lib/teleport
  auth_token: "token"
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.ex
  proxy_listener_mode: multiplex
  authentication:
    second_factor: off

proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.ex:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: ttttt@gmail.com

ssh_service:
  enabled: "yes"
  labels:
    type: ssh
```

## Config of the node machine:
```yaml
version: v3
teleport:
  nodename: node-machine-5
  data_dir: /var/lib/teleport
  join_params:
    token_name: "token"
    method: token
  proxy_server: teleport.example.ex:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}

ssh_service:
  enabled: "yes"
  labels:
    type: ssh
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
```
