### ISSUE TITLE
Allow overrides to the liveness and readiness probes in the teleport-kube-agent helm chart

### ISSUE THREAD

**Issue by nloveupgrade** [gravitational/teleport#35704]
What would you like Teleport to do?
Allow users the ability to override the readiness/liveness probe settings in the teleport-kube-agent's helm chart. In the values.yaml file add the following:
```yaml
livenessProbe:
  httpGet:
    path: /healthz
    port: diag
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 6
  timeoutSeconds: 1
readinessProbe:
  httpGet:
    path: /readyz
    port: diag
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 12
  timeoutSeconds: 1
```

What problem does this solve?
1. We want to restart the Teleport agent if the connection to the teleport cluster is lost for a certain amount of time. Because the `/healthz` endpoint only checks if the teleport process is running we can't currently do this. By allowing us to change the livenessProbe path to `/readyz` and adjust the scrape periods/thresholds we would be able to restart on a pod if the connection has dropped - as is we wait ~15 minutes for the `/healthz` endpoint to finally fail.
2. We get alerts saying that teleport agent pods aren't ready because the initialDelay isn't long enough. Users should have the ability to configure their intialDelay, failure, and threshold settings to meet the needs of their environments.

If a workaround exists, please include it.
There is no workaround right now, however I have read through the `CONTRIBUTING.md` document and have code ready for a PR.
