### ISSUE TITLE
Auth and Proxy should have separate affinity rules on the Teleport Cluster Helm Chart

### ISSUE THREAD

**Issue by nloveupgrade** [gravitational/teleport#35802]
### What would you like Teleport to do?
There is a [single affinity parameter](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L547) for both the proxy and auth deployments in the teleport-cluster helm chart. This prevents users from creating their own podAffinity rules.

For example if I want to create affinity rules to run pods in different AWS AZs it might look like:
```yaml
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - {{ .Release.Name }}
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - auth
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

If I set `app.kubernetes.io/component` to `auth` then my proxy pods will try to avoid AZ where auth pods are and if I set it to `proxy` then my auth pods will avoid AZs where proxy pods are.

The solution is to have individual affinity sections for each of the deployments i.e.
```yaml
affinity:
    proxy:
    auth:
```

Or the following if you intend to bring more deployment specific overrides in (i.e. resources, annotations, labels, etc):

```yaml
proxy:
    affinity:
auth:
    affinity:
```

### What problem does this solve?
Affinity override rules are unusable.

### If a workaround exists, please include it.
We can continue to use the existing host antiaffinity rules built into the chart, but this does not guarantee us running teleport in multiple AZs.
