### ISSUE TITLE
Discovery service alone does not provide a healthy readyz monitoring message

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#35808]
Expected behavior:

As with Teleport ssh service running just the discovery service would show a healthy message.

Current behavior:

A Teleport machine that just has the `discovery_service` enabled will not return the a healthy message on the readyz health monitoring.

```bash
curl http://127.0.0.1:3000/readyz
{"status":"teleport is starting and hasn't joined the cluster yet"}
```

Bug details:
- Teleport version: 14.2.3
- Recreation steps

1. Configure a discovery service such as below

```yaml
version: v3
teleport:
  join_params:
    token_name: "/tmp/token"
    method: token
  proxy_server: example.teleport.sh:443
  diag_addr: 127.0.0.1:3000
auth_service:
  enabled: off
proxy_service:
  enabled: off
ssh_service:
  enabled: off
discovery_service:
  enabled: "yes"
  aws:
   - types: ["ec2"]
     regions: ["us-east-1"]
     tags:
       "enroll": "sam" # Match EC2 instances where tag:env=prod
     install: # optional section when default-installer is used.
        script_name: "default-installercopy"
```
2. Retrieve the value of `readyz`

```bash
curl http://127.0.0.1:3000/readyz
```
