### ISSUE TITLE
Incorrect `teleport.dev/app-rewrite` annotation example

### ISSUE THREAD

**Issue by olegenii** [gravitational/teleport#35816]
## Applies To

https://goteleport.com/docs/application-access/enroll-kubernetes-applications/reference/

## Details

Current example of teleport.dev/app-rewrite annotation for App discovery set up headers rewriting incorrectly and cause errors in agent log and skipping the App to be added, 

## How will we know this is resolved?

Annotation headers rewrite example should use this way:
```          
          teleport.dev/app-rewrite: |
            headers:
            - name: "Host"
              value: "grafana.teleport.k8s.olegen.fun"
            - name: "Origin"
              value: "https://grafana.teleport.k8s.olegen.fun" 
```
