### ISSUE TITLE
Is "u2f" not working?

### ISSUE THREAD

**Issue by JUN-KOBAYASHI** [gravitational/teleport#3588]
### Description
I am configuring u2f using "OSS version" teleport, but when I create the account as "tctl users add username root", the web page does not show a popup to load yubikey.

"web console" contains "Please check your U2F settings, make sure it is plugged in and you are using the supported browser.
U2F error: BAD_REQUEST "message appears.

### Environment
- Teleport version (use `teleport version`):
Teleport v4.2.8 git:v4.2.8-0-ga9015b33 go1.13.2

- Tsh version (use `tsh version`):
Teleport v4.2.8 git:v4.2.8-0-ga9015b33 go1.13.2

- OS (e.g. from `/etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
On-premises server (virtual server by vmware)

**Browser environment**
Google chrome 81.0.4044.92（Official Build） （64 bit）
firefox 75.0 (64bit)

**configuration teleport.yaml**

```
teleport:
  nodename: maskmaskmaskmask
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: cluster-join-token
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: yes
  cluster_name: "main"
  authentication:
    type: local
    second_factor: u2f

  listen_addr: 0.0.0.0:3025

  tokens:
  - proxy,node:cluster-join-token
  session_recording: ""
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0

ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [/usr/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/usr/bin/uname, -p]
    period: 1h0m0s

proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_cert_file: /etc/letsencrypt/archive/maskmaskmaskmask/fullchain1.pem
  https_key_file: /etc/letsencrypt/archive/maskmaskmaskmask/privkey1.pem

```
