### ISSUE TITLE
Add RollingUpdate strategy to Proxy Deployment in Teleport Cluster Helm Chart

### ISSUE THREAD

**Issue by nloveupgrade** [gravitational/teleport#35898]
### What would you like Teleport to do?
In the Teleport Cluster helm chart allow the user to configure a RollingUpdate strategy for the Proxy Deployment. The Auth Deployment already has a RollingUpdate strategy set, but it would be nice for the user to be able to configure it to their needs.

**An example of what this might look like**

`values.yaml`
```yaml
proxy: 
    rollingUpdate:
        maxSurge: 25%           # Should be able to take a percent or int
        maxUnavailable: 50%  # Should be able to take a percent or int
auth: 
    rollingUpdate:
        maxSurge: 0           # Should be able to take a percent or int
        maxUnavailable: 1  # Should be able to take a percent or int
```

`auth/deployment.yaml`
```yaml
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ $auth.rollingUpdate.maxSurge }}
      maxUnavailable: {{ $auth.rollingUpdate.maxUnavailable }}
```

`proxy/deployment.yaml`
```yaml
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ $proxy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ $proxy.rollingUpdate.maxUnavailable }}
```

### What problem does this solve?
When the Teleport Proxy pods restart they restart quicker than the agents are able to reestablish connections to the new proxy pods. Adding a RollingUpdate would allow the user to roll these out more slowly and ensure there isn't a time where agents aren't connected to any proxies.

In my specific test case I am running the following:
- 6 proxy and 6 auth pods
- PDB set to 3 minimum
- Peer Proxying is enabled, with agent_connection_count set to 4
- 9 Teleport Agents (3 agents for each type - app, db, kube)
- minReadySeconds set to 30

With this setup I would expect a restart on the proxy and auth pods wouldn't cause any disruptions, however I saw the readiness probes on the agents fail with both 503s and 400s and my 1 second loop to run `kubectl version` against the teleport kube agent failed 3 times.

### If a workaround exists, please include it.
None
