### ISSUE TITLE
Provide option to set `cluster_display_name`

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3604]
### Feature Request

We currently recommend that people set cluster name to something meaningful, and since we show this in the UI and CLI we should provide an easy way to change the name without having to wipe out `/var/lib/teleport`.

```yaml
# This section configures the 'auth service':
auth_service:
    # Turns 'auth' role on. Default is 'yes'
    enabled: yes

    # A cluster name is used as part of a signature in certificates
    # generated by this CA.
    #
    # We strongly recommend to explicitly set it to something meaningful as it
    # becomes important when configuring trust between multiple clusters.
    #
    # By default an automatically generated name is used (not recommended)
    #
    # IMPORTANT: if you change cluster_name, it will invalidate all generated
    # certificates and keys (may need to wipe out /var/lib/teleport directory)
    cluster_name: "main"
    cluster_display: "Acme Cluster"
    # See explanation of labels in "Labeling Clusters" section below
    labels:
        location: azure
        type: MSP 
        status: standby
```

https://github.com/gravitational/teleport/issues/2317

### Motivation
I was reminded about this from https://github.com/gravitational/teleport/issues/2317, as we show more UI for trusted cluster and expand the CLI these extra labels and context will improve the Ops/Dev Experience. 

### Who's it for?
OSS User, Pro, Enterprise
