### ISSUE TITLE
helm: `teleport-kube-agent` chart should support Kubernetes joining

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#36116]
### What would you like Teleport to do?

Support v14 Kubernetes joining for teleport-kube-agents deployed via the chart.

### What problem does this solve?

Teleports supports the handy Kubernetes JWKS joining for all Kubernetes users to get rid of their secret/long-lived tokens. However the chart does not support it currently.

### If a workaround exists, please include it.

Fork the chart, deploy the agent without the chart

### TODO:

- add the clusterName in the chart values
- mount a SA token with the correct audience
- add safeties to block users from using the `kubernertes` join method without a cluster name
- add a guide for this setup
- add a test plan item

**Comment by zifeo** [comment]
@hugoShaka is there a current alternative to use jwks with teleport-kube-agent?

**Comment by hugoShaka** [comment]
You should be able to workaround with:

```
joinParams:
  method: "kubernetes"
  tokenName: "your-kube-jwks-token-name"

extraEnv:
  - name: KUBERNETES_TOKEN_PATH
    value: /var/run/secrets/tokens/join-sa-token

extraVolumeMounts:
  - mountPath: /var/run/secrets/tokens
    name: join-sa-token

extraVolumes:
  - name: join-sa-token
    projected:
      sources:
        - serviceAccountToken:
          path: join-sa-token
          expirationSeconds: 600
          # `example.teleport.sh` must be replaced with the name of
          # your Teleport cluster.
          audience: example.teleport.sh
```

**Comment by tuladhar** [comment]
In above, there's missing indentation for the `serviceAccountToken` field which will result in following error:
```
W0503 00:22:14.166702   20801 warnings.go:70] unknown field "spec.template.spec.volumes[3].projected.sources[0].audience"
W0503 00:22:14.166764   20801 warnings.go:70] unknown field "spec.template.spec.volumes[3].projected.sources[0].expirationSeconds"
W0503 00:22:14.166838   20801 warnings.go:70] unknown field "spec.template.spec.volumes[3].projected.sources[0].path"
```


Here's the corrected YAML:

```
... same as above

extraVolumes:
  - name: join-sa-token
    projected:
      sources:
        - serviceAccountToken:
            path: join-sa-token
            expirationSeconds: 600
            # `example.teleport.sh` must be replaced with the name of
            # your Teleport cluster.
            audience: example.teleport.sh
```

**Comment by zifeo** [comment]
@hugoShaka thanks! What should exactly your-kube-jwks-token-name contain/do? is it the name of the secret containing a key `jwks` and the jwks of the cluster hosting the teleport cluster? getting kind of confused based on what that [doc](https://goteleport.com/docs/reference/join-methods/#kubernetes-jwks).

**Comment by hugoShaka** [comment]
`your-kube-jwks-token-name` is the name of the Provision Token created in Teleport.

The token would look like
```yaml
kind: token
version: v2
metadata:
  name: your-kube-jwks-token-name
spec:
  roles: [Kube]
  join_method: kubernetes
  kubernetes:
    type: static_jwks
    static_jwks:
      jwks: |
        # Place the data returned by the command `kubectl get --raw /openid/v1/jwks`
        {"keys":[--snip--]}
    allow:
    - service_account: "<namespace>:<pod service account>"
```
