### ISSUE TITLE
QR code generation works only from the second attempt

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#36126]
Hi!

I installed the teleport cluster via flux means into regular kubernetes cluster. I used the default settings like:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: teleport-cluster
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teleport
  namespace: teleport-cluster
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport-cluster
spec:
  chart:
    spec:
      chart: teleport-cluster
      sourceRef:
        kind: HelmRepository
        name: teleport
      version: '*'
  interval: 1m0s
  values:
    acme: true
    acmeEmail: gb12335@gmail.com
    clusterName: teleport.conbo.gecube.eu
```

It created the deployment for me and assigned an IP address to the LoadBalancer service. I attached it to domain with the means of my DNS panel. Then I went into shell and got the link to create an admin user:

```bash
kubectl --namespace teleport-cluster exec deployment/teleport-auth -- tctl users add tadmin --roles=access,editor --logins=ubuntu
User "tadmin" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://teleport.conbo.gecube.eu:443/web/invite/d11f0bf9137d15fb0a7a86dae9a01e59

NOTE: Make sure teleport.conbo.gecube.eu:443 points at a Teleport proxy which users can access.
```

I entered the password and then I was prompted to select OTP and scan QR. I did it with Google authenticator on my phone. I typed the shown OTP into teleport web page and... got the error.
<img width="733" alt="Screenshot 2023-12-29 at 18 35 15" src="https://github.com/gravitational/teleport/assets/2912732/10a24a03-0fa1-40c1-a695-7597d488f405">

So I started the process from the pasting the setup link into my browser and the second time it worked for me.

I checked multiple times - for some reason the first QR code with OTP codes are not working. I experienced this issue on several installations and it is really annoying, because there are no obvious reason for a such behaviour.
