### ISSUE TITLE
Can't access an application with basic auth

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#36178]
Expected behvaiour:

I can click on application button and get the web page of application on teleport subdomain

Observerd behaviour:

the application feature of teleport is generally working - I can prove it by entering elasticsearch instance and coroot instance.

<img width="1525" alt="Screenshot 2024-01-02 at 13 02 29" src="https://github.com/gravitational/teleport/assets/2912732/cd04b518-bd66-40e7-b0df-e70f0f471149">
<img width="1411" alt="Screenshot 2024-01-02 at 13 02 45" src="https://github.com/gravitational/teleport/assets/2912732/407b2625-6918-44da-9b07-e6d635722517">

When I try to click on Weave gitops dashboard service:

<img width="1476" alt="Screenshot 2024-01-02 at 13 03 08" src="https://github.com/gravitational/teleport/assets/2912732/82000e50-2a59-4a05-bf61-da01dd1b1894">

I am getting the next error:

<img width="577" alt="Screenshot 2024-01-02 at 13 03 23" src="https://github.com/gravitational/teleport/assets/2912732/fa099cfd-3cb0-4391-b3cd-56c0ae1bf69c">

In the same time I can access this dashboard with plain port-forward feature of kubectl:

```
gaal@bigsur teleport % kubectl port-forward -n flux-system svc/ww-gitops-weave-gitops 9001:9001
Forwarding from 127.0.0.1:9001 -> 9001
Forwarding from [::1]:9001 -> 9001
```

<img width="1343" alt="Screenshot 2024-01-02 at 13 04 11" src="https://github.com/gravitational/teleport/assets/2912732/62ee02c0-ae7a-4b43-b30f-62d390c4e078">

Looking for guidelines how to publish Weave GitOps Dashboard via teleport application means.

**Comment by gecube** [comment]
Worked after applying the workaround from #36179

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: *******
      username: admin
    service:
      annotations:
        teleport.dev/name: ww-gitops-tt-k8s-prod # here is the magic
```
