### ISSUE TITLE
Disable auto generation of app for k8s service

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#36177]
What would you like Teleport to do?

Hi! Like a devops engineer I want to precisely disable generation of application inside of teleport installation for particular services. Let's say I have the list of services:

<img width="1501" alt="Screenshot 2024-01-02 at 12 40 50" src="https://github.com/gravitational/teleport/assets/2912732/761068f0-db87-44c3-a101-e9c0389c75c3">

I want to easily remove webhook-receiver-flux-system-tt-k8s-dev and webhook-receiver-flux-system-tt-k8s-prod from the list. Bases on the annotations on these services.

What problem does this solve?

Not every services needs to be published inside of teleport. For instance, there is no reason to publish cm acme solvers:

<img width="1487" alt="Screenshot 2024-01-02 at 12 41 55" src="https://github.com/gravitational/teleport/assets/2912732/6a2b6b96-ec4f-43ab-b1ac-75f0ccac7062">

In the same time I don't want to change drastically the helm values for teleport agent. Right now they are as simple as:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: teleport-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teleport
  namespace: teleport-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-agent
  namespace: teleport-system
spec:
  chart:
    spec:
      chart: teleport-kube-agent
      sourceRef:
        kind: HelmRepository
        name: teleport
      version: '14.3.0'
  interval: 1m0s
  values:
    roles: kube,app,discovery
    authToken: ***********
    proxyAddr: teleport.****.****.eu:443
    kubeClusterName: tt-k8s-prod
    labels:
      teleport.internal/resource-id: ****-****-****-****-****
    enterprise: false
```

I want to disable autoaddition of services with a specific already existing annotation like `teleport.dev/discovery-type: none` or a separate annotation like "teleport.dev/disable-discovery: true"

If a workaround exists, please include it.

Set up custom labels according to the official doc in the helm chart values: https://goteleport.com/docs/application-access/enroll-kubernetes-applications/reference/#teleportdevdiscovery-type
