### ISSUE TITLE
Provide a good way how to disable a teleport k8s integration on the main cluster

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#36182]
Expected behavior:

As a devops engineer I want to disable a button with k8s integration for the main cluster of teleport (I am installing it on top of k8s cluster), so I am getting this:

<img width="1530" alt="Screenshot 2024-01-02 at 15 05 09" src="https://github.com/gravitational/teleport/assets/2912732/b46f7e61-481c-4a82-89c0-653e46f867bc">

After teleport will be deployed on the k8s cluster (auth + proxy services), I want to manually go to teleport WebUI and enroll an existing k8s cluster into teleport installation. Why? For instance, if I am deploying a teleport kube agent separately, right now I am getting out-of-the box integration with k8s service discovery and this approach looks to me more configurable.

Current behavior:

No obvious options to remove k8s integration from the start.
The installation of teleport looks like as simple as applying the next manifest:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: teleport-cluster
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teleport
  namespace: teleport-cluster
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport-cluster
spec:
  chart:
    spec:
      chart: teleport-cluster
      sourceRef:
        kind: HelmRepository
        name: teleport
      version: '*'
  interval: 1m0s
  values:
    acme: true
    acmeEmail: (paste here any email)
    clusterName: (paste here the domain name where teleport WebUI will be accesible)
```

**Comment by tigrato** [comment]
You can set the following values to disable the out of the box kubernetes service

```yaml
auth:
  teleportConfig:
    kubernetes_service:
       enabled: false
``` 

I will leave this issue open for a few days.
