### ISSUE TITLE
Machine ID: Adjust `tbot` internals to support long-lived services

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#36204]
Support long-lived services within tbot's configuration as per https://github.com/gravitational/teleport.e/pull/2745

Example of a hypothetical service's configuration:

```yaml
# services is a new section of the tbot configuration that controls long-lived
# services that tbot should run.
services:
- type: example-tunnel
  listen: tcp://0.0.0.0:3000
  roles: [editor]
```
