### ISSUE TITLE
Document kubernetes_users support. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3626]
## Summary
Docs ticket for https://github.com/gravitational/teleport/pull/3612 

Using local users, it should be possible to write k8s RBAC bindings for User subjects.
Plumb kubernetes_users field of teleport user through to k8s client cert.

Also add `--k8s-users` flag to tctl users add, which defaults to the local login (same as for SSH).

With this, the UX is:
```
admin:
tctl users add awly, have user go through registration flow
create k8s RBAC binding with:
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: some-role-here
subjects:
- kind: User
  name: awly
user:
```
tsh login
kubectl ..., based on what the above role binding allows

### Audience
OSS, CLI and Enterprise

### Location
CLI Docs, Kubernetes Docs and Admin Guide
