### ISSUE TITLE
Warn that Teleport v14 is required for machine-id V2 bot definition.

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#36460]
## Applies To

https://goteleport.com/docs/machine-id/deployment/ and guides within.

## Details

V2  such as this example is supported in Teleport V14 and up. There currently isn't a warning that V14 is required to use `v2`
for the `tbot` configuration.

```yaml
version: v2
auth_server: example.teleport.sh:443
onboarding:
  join_method: iam
  token: example-bot
storage:
  type: memory
# outputs will be filled in during the completion of an access guide.
outputs: []

```

## How will we know this is resolved?

Users who have Teleport <V14 would have a warning that this configuration would not work.
