### ISSUE TITLE
Unable to promote access request for Windows non-AD resource to an Access List. 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#36577]
Expected behavior:
The reviewer should be able to promote this access request, selecting the the Access List to add the user as a member. This works for node resources but not windows desktop resources. 

Current behavior:
The reviewer cannot select "Approve long-term access via Access List with the requested resources" because it is grey out. The work around is to edit the access list and enroll the user as member. User will have access as needed. 

Bug details:
- Teleport version
Self hosted enterprise v14.3.0
- Recreation steps

1. Create a windows-desktop-admins role providing access to the desktop resource
2. Create an access list that grants users access to this desktop-admin role. 
3. Create access request for windows desktop resource. 
4. Login in as admin with reviewer role to approve access request
5. Attempt to Approve long-term access via Access List with the requested resources. Item is greyed out. 

- Debug logs

```
kind: role
metadata:
  name: windows-desktop-admins
spec:
  allow:
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
```

```
kind: access_list
metadata:
  expires: "0001-01-01T00:00:00Z"
  id: 1704987900762438718
  name: f7c8946a-78ff-4287-a56d-7f24573bd382
spec:
  audit:
    next_audit_date: "2024-02-01T17:00:00Z"
    notifications:
      start: 336h0m0s
    recurrence:
      day_of_month: "1"
      frequency: 1 month
  description: ""
  grants:
    roles:
    - windows-desktop-admins
    traits: {}
  membership: explicit
  membership_requires:
    roles: null
    traits: {}
  owners:
  - description: ""
    ineligible_status: INELIGIBLE_STATUS_ELIGIBLE
    name: cvasquez
  ownership: explicit
  ownership_requires:
    roles: null
    traits: {}
  title: desktop
version: v1
```
```
kind: role
metadata:
  description: Review access requests
  labels:
    teleport.internal/resource-type: preset
  name: reviewer
spec:
  allow:
    review_requests:
      preview_as_roles:
      - access
      - windows-desktop-admins
      roles:
      - '*'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
```
```
kind: role
metadata:
  description: Request all resources
  id: 1704988605929750818
  labels:
    teleport.internal/resource-type: preset
  name: requester
spec:
  allow:
    request:
      roles:
      - '*'
      search_as_roles:
      - access
      - windows-desktop-admins
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    require_session_mfa: true
    ssh_file_copy: true
version: v6

```
