### ISSUE TITLE
Support "dual level authorisation" of Access Requests

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#36854]
What would you like Teleport to do?

Currently Teleport only supports "dual authorisation' of Access Requests on a single level (i.e. within a threshold). It does not support multiple or "dual level authorisation" of Access Requests. This request is to support the use case where 2 approvers must be from 2 different roles (or teams). For example, a peer review (from the same team) and a supervisor/manager/admin review in addition.

What problem does this solve?

Currently, multiple review thresholds can be set on a Access Request but if any one of these thresholds is met, the request is approved; i.e. there is an logical `OR` condition between thresholds:

```
  allow:
    request:
      roles: ['dbadmin']
      thresholds:
        - approve: 1
          deny: 1
          filter: '!contains(reviewer.traits.team, "dev")'
        # -- OR --
        - approve: 1
          deny: 1
          filter: 'contains(reviewer.roles, "admin")'
```

In order to support "dual level authorisation", support for a logical `AND` condition  between thresholds is required (or a new separate approach is taken):

```
  allow:
    request:
      roles: ['dbadmin']
      thresholds:
        - approve: 1
          deny: 1
          filter: '!contains(reviewer.traits.team, "dev")'
        # -- AND --
        - approve: 1
          deny: 1
          filter: 'contains(reviewer.roles, "admin")'
```

If a workaround exists, please include it.

N/A
