### ISSUE TITLE
tsh login requires explicit port number, prints a confusing error message

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#36922]
Expected behavior:
`tsh login` should correctly assume default proxy port or at least print a helpful error message.

Current behavior:
`tsh login` fails to correctly assume port 443 and prints a confusing message:
```
tsh login --proxy=cluster.example.com --auth=github
ERROR: Teleport proxy not available at proxy address cluster.example.com:3080 or cluster.example.com:443
	context deadline exceeded
```

Bug details:
Teleport version: 15.0.0-alpha.5
Recreation steps:

1. Create a cluster in the FIPS mode, configure Github connector (not sure about which part exactly causes the issue). Proxy service config:
```yaml
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: cluster.example.com:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: someuser@example.com
```
2. Attempt to sign in with `tsh login --proxy=cluster.example.com --auth=github`: failure
3. Attempt to sign in with `tsh login --proxy=cluster.example.com:443 --auth=github`: success
