### ISSUE TITLE
Roles get deleted immediately after creation

### ISSUE THREAD

**Issue by grossdaniel85** [gravitational/teleport#37021]
Expected behavior: It should be possible to create and attach teleport roles within a teleport cluster.

Current behavior: the roles get created. This is also shown in the audit log. However they seem to get deleted immediately after creation, without any entry in the audit logs.

Bug details:
- Teleport version: v14.3.3, deployed as HA Helm Chart on EKS 1.25
- Recreation steps:
1. in the teleport cluster, apply the role defined in following yaml. The role is visible in the ui.
2. refresh the screen or navigate to arbitrary session in the side bar.
 
```yaml
apiVersion: resources.teleport.dev/v5
kind: TeleportRole
metadata:
  name: my-test-role
  namespace: teleport
spec:
  allow:
    app_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
      where: contains(session.participants, user.metadata.name)
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
  deny:
    logins:
    - guest
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
```
