### ISSUE TITLE
Account Settings offers to add an MFA device or a passkey when it should not be available

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#37033]
Expected behavior:
- The UI shouldn't offer adding a passkey or an MFA device when there's no local authentication.

Current behavior:
- The UI allows the user to click "add passkey" and "add MFA device". The dialog is defunct, but it shouldn't show in the first place.

Bug details:
Teleport version: 15.0.0-alpha.5
Recreation steps:
1. Disable local auth, use some form of SSO.
2. Go to account settings.

**Comment by zmb3** [comment]
You should be able to add MFA devices even for SSO users, right?

**Comment by kimlisa** [comment]
> The dialog is defunct

i'm not sure i understand what was defunct?

this is how i tested: 

```
// works as intended (able to add a otp, didn't test a passkey but i'd imagine it work)
authentication:
    type: github
    local_auth: false
    webauthn:
      rp_id: proxy.0.0.0.0.nip.io
    second_factor: on
```

```
// works as intended (the add buttons are disabled)
authentication:
    type: github
    local_auth: false
    webauthn:
      rp_id: proxy.0.0.0.0.nip.io
    second_factor: off
```
