### ISSUE TITLE
Graphical glitches when connecting to a Windows 2022 Server instance

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#37032]
Expected behavior:
No glitches.

Current behavior:
When signing in, I often see glitches in form of various regions of screen repeated in unexpected places. Moving windows around also frequently leaves parts of their images, and sometimes even areas of "random noise".

![Screenshot 2024-01-22 at 18 36 27](https://github.com/gravitational/teleport/assets/9391503/71781720-1c97-4a4b-a0ea-c2f9ee269f03)

Bug details:
Teleport version: v15.0.0-alpha.2
Browser: Chrome 120 / arm64 (MacOS)
Recreation steps:
1. Set up a single-node v15 cluster.
2. Get a Windows Server 2022 instance from Amazon Lightsail.
3. Add a Windows service to your cluster's auth node, replacing `hostname` and `host-ip`.
```yaml
windows_desktop_service:
  listen_addr: 0.0.0.0:3028
  enabled: yes
  static_hosts:
  - name: hostname
    ad: false
    addr: host-ip
```
4. Add Windows access to your Teleport role and connect to the Windows instance using our Web desktop client.
5. If you don't see the problem, open any window and move it around.
