### ISSUE TITLE
Provide trait username for logins for GitHub auth connector for OSS

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3711]
### Feature Request
Provide a method that allows for users to specify the GitHub username as a login with the GitHub auth connector.  As shown below a github configuration like like would let user `jsmith` get `logins` for root and `jsmith`.

```yaml
  teams_to_logins:
    - organization: ExampleOrg
      team: admins           # Github team name within that organization
      # allowed UNIX logins for team ExampleOrg/admins:
      logins:
        - root
        - '{{external.username}}'
```

### Motivation
The local username configuration allows for specifying unique usernames per user.  To get a unique username for the user with the github connector you would have to separate each user to their own github group.

### Who's it for?
OSS
