### ISSUE TITLE
Assuming role with hardware key touch failed

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#37134]
When I tried to assume a role with `hardware_key_touch` the below error was returned:

```
 tsh login --request-id=b776b6e3-1a4a-43ed-a54b-d3eb7d30447a

Approval received, getting updated certificates...

Unmet private key policy "hardware_key_touch".
Enter password for Teleport user tim:
Tap any security key
Detected security key tap
Tap your YubiKey
ERROR: connection error: desc = "transport: authentication handshake failed: tls: failed to sign handshake: selecting piv applet: command failed: transmitting request: an attempt was made to end a non-existent transaction"
```
the assumed role

```
kind: role
metadata:
  name: require-session-mfa-touch
spec:
  allow:
    logins:
    - root
    - ubuntu
    node_labels:
      env: example
    request: {}
  deny: {}
  options:
    require_session_mfa: hardware_key_touch
version: v6
```

I was able to assume the role on the second attempt

Bug details:
- Teleport version v15.0 alpha 5
- Recreation steps
- Debug logs
