### ISSUE TITLE
Provide method for approval roles to replace/take precedence over user default roles.

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3720]
### Feature Request
In cases where a user has been granted roles via the Approval Flow have those roles take precedence over denials in user assigned roles.  As an example here's portions of a default role that restricts access to nodes labeled tier=production and allows all others.

```yaml
allow:
    node_labels:
      tier: '*'
deny:
    node_labels:
      tier: production
```
The role approved could have this setting allowing specifically for production.

```yaml
allow:
    node_labels:
      tier: 'production'
```

Currently the user would not receive access since the denials of all roles takes precedence.  This feature request would take precedence or provide a method for the user to switch their roles to the approved ones.

### Motivation
This allows for escalating access with approved roles in cases like above.  Otherwise, denials will be difficult to use in combination with role approvals.

### Who's it for?
Pro, Enterprise
