### ISSUE TITLE
Teleport Node Agents Fail to Reconnect After too many `/webapi/ping` Endpoint Errors

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#37211]
### Expected behavior:
Teleport node agents should continuously attempt to reconnect to the Teleport cluster, with a jittered backoff until a connection is established, regardless of any errors encountered during the initial connection attempts to the `/webapi/ping` endpoint.

### Current behavior:
A Teleport node agent can stop attempting to reconnect to the Teleport cluster after encountering too many subsequent errors with the `/webapi/ping` endpoint during an upgrade process. Specifically, the agents get into a state where they do not log any activity and do not seem to attempt reconnection, effectively becoming unresponsive and requiring manual intervention to recover.

In this case, the behavior was reported during a rollout of a non-HA Teleport Cluster that could encounter several minutes of downtime.

### Bug details:

**Teleport version**: v14.3.3

#### **Recreation steps**:

1. On an existing cluster, perform an action that will cause agents to lose connection and start to reconnect (such as restarting all proxies at once).
2. Allow one or more agents several minutes of experiencing any sort of `/webapi/ping` error. In my lab, I was able to trigger the issue by forcing two types of errors:
    - Point the proxy hostname to an IP address that simply closes every connection attempt on port 443. (This causes an EOF error). This simulates a load balancer with no healthy targets to handle the connection. 
    - Create a fake DNS zone in my local DNS resolver that causes DNS resolution to fail. This doesn't cause the EOF error, but it still triggers the issue where the agent stops attempting to connect.
3. Observe that some node agents stop attempting to reconnect and become unresponsive, as indicated by a lack of log activity post-upgrade. While this issue is relatively reproducible with a self-hosted 14.3.3, I didn't see that every agent was guaranteed to fail. I believe this may have something to do with how long the agent has been running, but I don't have enough data to show that is really the case.

**Debug logs**:

I have included `3016852.log` that shows the entire lifetime of the PID of one of my agents in my lab. `journalctl -u teleport _PID=3016852` This host issues a `systemctl reload teleport` nightly, so this covers 24 hours of logs.

I initially caused the failure at `2024-01-19T19:10:15Z` by restarting all the proxies in the cluster. I had set up a DNS failure on this particular agent. It retried for several minutes, but by `2024-01-19T19:32:42Z` it had stopped retrying. I cleared the artificially caused DNS error a little after that time. I sent a USR1 at `2024-01-19T21:20:50Z` and the goroutines are included.

I noticed that at `2024-01-19T21:26:45Z` there was one more `*trace.ConnectionProblemError watcher is closed: error reading from server` that showed up, and I sent another USR1 to get an updated goroutine list. It was left broken all night, and it didn't reconnect until after the nightly `systemctl reload teleport` at `2024-01-20T04:17:46Z`

[3016852.log](https://github.com/gravitational/teleport/files/14043805/3016852.log)

I reproduced this with a typical `teleport-cluster` self-hosted deploy that has TLS multiplexing enabled. The agent has a fairly standard `teleport.yaml` that runs only the ssh_service.

<details><summary>node `teleport.yaml`</summary>

```
version: v3
teleport:
  nodename: mynode1
  data_dir: /var/lib/teleport
  join_params:
    token_name: aaabbbccc
    method: token
  proxy_server: teleport.example.com:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    env: lab1
  commands:
  - name: hostname
    command: [hostname]
    period: 9999h
  - name: arch
    command: [uname, -m]
    period: 9999h
  - name: uptime
    command: [uptime, -p]
    period: 1m0s
  - name: version
    command: [/proc/self/exe, version]
    period: 9999h
  - name: ip
    command: [/bin/bash, "-c", "ip -4 -br addr sh dev eth0 | awk '{print $3}'"]
    period: 9999h
  - name: distro
    command: [lsb_release, "-ds"]
    period: 9999h
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
```
</details>
