### ISSUE TITLE
Add support for selecting a non-default Firestore database in the project

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#37227]
It looks like Firestore added multiple database support in a single project in July 2023: https://cloud.google.com/blog/products/databases/manage-multiple-firestore-databases-in-a-project

That feature went to general availability on 23 Jan 2024: [January 2024: Firestore sum and average operations, and best practices for Firebase Cloud Messaging | 0:12 - Firestore: support for multiple databases is generally available](https://www.youtube.com/watch?v=lesCn6Q-yss&t=12s)

As of 24 January 2024, Teleport 14.3.3 is the current version. Only the default database is selectable for both the backend and the audit event storage. Our config file will likely need to be extended to accommodate a non-default database. All the upstream Google SDKs for Firestore already support multiple databases in the project.

```
teleport:
  storage:
    type: firestore
    project_id: Example_GCP_Project_Name
    # TODO specify database name somehow
    collection_name: Example_TELEPORT_FIRESTORE_TABLE_NAME
    credentials_path: /var/lib/teleport/gcs_creds
    audit_events_uri:  ['firestore://Example_TELEPORT_FIRESTORE_EVENTS_TABLE_NAME'] # TODO specify database name
```
