### ISSUE TITLE
Make configuring teleport nodes easier using teleport configure

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3732]
### Feature Request
As a follow up to https://github.com/gravitational/teleport/issues/2891, it would be helpful to have modes to `teleport configure`. We currently output a working example setup for proxy, auth and node.

While setting up some nodes at home, I wanted to quickly bootstrap them and having a default `teleport configure --roles=node`, also having a systemd unit for nodes would be super handy out of the box. 

<details>
  <summary>$ teleport configure</summary>
  

    ```
    #
    # Sample Teleport configuration file
    # Creates a single proxy, auth and node server.
    #
    # Things to update:
    #  1. ca_pin: Obtain the CA pin hash for joining more nodes by running 'tctl status'
    #     on the auth server once Teleport is running.
    #  2. license-if-using-teleport-enterprise.pem: If you are an Enterprise customer,
    #     obtain this from https://dashboard.gravitational.com/web/
    #
    teleport:
    nodename: teleport5auth
    data_dir: /var/lib/teleport
    auth_token: 6c0ef44ded8d57c07bf741ee0b2b9a8cf1def9ff8fdecbc3
    auth_servers:
    - 127.0.0.1:3025
    log:
        output: stderr
        severity: INFO
    ca_pin: sha256:ca-pin-hash-goes-here
    auth_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3025
    tokens:
    - proxy,node:6c0ef44ded8d57c07bf741ee0b2b9a8cf1def9ff8fdecbc3
    license_file: /path/to/license-if-using-teleport-enterprise.pem
    ssh_service:
    enabled: "yes"
    labels:
        db_role: master
        db_type: postgres
    commands:
    - name: hostname
        command: [/usr/bin/hostname]
        period: 1m0s
    - name: arch
        command: [/usr/bin/uname, -p]
        period: 1h0m0s
    proxy_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3023
    web_listen_addr: 0.0.0.0:3080
    tunnel_listen_addr: 0.0.0.0:3024
    ```

</details>

<details>
  <summary>$ teleport configure --roles=node</summary>
  

    ```
    #
    # Sample Teleport configuration file
    # Setup a Teleport node.
    #
    # Things to update:
    #  1. auth_token: Obtain this from the Teleport Auth Server
    #  2. auth_location:  The FQDN/IP of the Teleport Auth server and Port. e.g. 127.0.0.1:3025
    #  3. ca_pin: Obtain the CA pin hash for joining more nodes by running 'tctl status'
    #     on the auth server once Teleport is running.
    #  Optional:
    #  4. labels: Update static and dynamic labels. 
    teleport:
    nodename: [auto-detect-hostname]
    data_dir: /var/lib/teleport
    auth_token: UPDATE_auth_token
    auth_servers:
    - UPDATE_auth_location:auth_port
    log:
        output: stderr
        severity: INFO
    ca_pin: sha256:ca-pin-hash-goes-here
    auth_service:
    enabled: "no"
    ssh_service:
    enabled: "yes"
    labels:
        example_label_db_type: postgres
    commands:
    - name: hostname
        command: [/usr/bin/hostname]
        period: 1m0s
    - name: arch
        command: [/usr/bin/uname, -p]
        period: 1h0m0s
    proxy_service:
    enabled: "no"
    ```

</details>

### Motivation
For new users trying to Teleport on different machines / clusters. 

### Who's it for?
OSS User, Pro, Enterprise
