### ISSUE TITLE
Specify schema for PostgreSQL auto-user provisioning

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#37609]
What would you like Teleport to do?
Allow specifying the schema used for installing auto-user provisioning procedures. Example:
```
db_service:
  enabled: "yes"
  databases:
  - name: "example"
    protocol: "postgres"
    uri: "localhost:5432"
    admin_user:
      name: "teleport-admin"
      default_schema: "teleport"
```

What problem does this solve?
Currently, Teleport installs auto-user provisioning without specifying a schema. 
https://github.com/gravitational/teleport/blob/b8deacfaffc25073f22ff0dadf157344b2fd2688/lib/srv/db/postgres/sql/activate-user.sql#L1

One issue found is the procedure creation will fail with the following
> ```your Teleport role requires automatic database user provisioning but an attempt to activate database user "STeve" failed due to the following error: ERROR: no schema has been selected to create in (SQLSTATE 3F000)```

when `USAGE` is not allowed, e.g `revoke usage on schema public from public`. By specifying the schema explicitly, procedure creation will exceed as long the admin user can `CREATE` (so no need for `USAGE`).

Also, this feature would allow admin user to manage procedures in a different schema other than `public`.
