### ISSUE TITLE
Expand documentation of logins / principals on leaf clusters. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3762]
## Summary
We a good summery of how trusted clusters work, but when referring to leaf clusters the RBAC UX can be confusing. Teleport always requires the root to have possible principles for a leaf cluster, under https://gravitational.com/teleport/docs/trustedclusters/#rbac we say `Both clusters "main" and "east" have their own locally defined roles.` but **for Trusted Cluster to work correctly it requires the root to have all principles**.

E.g. 
```
# root cluster
kind: role
version: v3
metadata:
  name: admin
spec:
  # SSH options used for user sessions with default values:
  options:
    ...
    # logins array defines the OS/UNIX logins a user is allowed to use.
    logins: [root,ec2_user]
```

```
# leaf cluster
kind: role
version: v3
metadata:
  name: admin
spec:
  # SSH options used for user sessions with default values:
  options:
    ...
    # The user can now login as `root` and `ec2_user` but NOT `dave` since 
    # this wasn't set in the root cluster RBAC. 
    logins: [dave,"{{internal.logins}}"]
```

The examples currently don't show unix principles which adds to this confusion. 

https://gravitational.com/teleport/docs/admin-guide/#adding-and-deleting-users
https://community.gravitational.com/t/what-is-the-difference-between-internal-and-external-variables-in-teleport-templates/159

### Audience
Enterprise / RBAC users

### Location
Update Trusted Clusters & RBAC Guide
