### ISSUE TITLE
Setting specific user and group privileges in the `sudoers` file using host user creation

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#37838]
Expected behavior:

It should be possible to set specific user and group privileges in the `sudoers` file using host user creation.

A second requirement (perhaps a feature request and not a bug?) is to dynamically pass a username based on an existing trait and to pass a group name using %. 

See examples below

Current behavior:

These role definitions lead to errors.

Using static user and group names:
```
kind: role
metadata:
  name: sudo-access
spec:
  allow:
    host_sudoers:
    - 'root ALL = (ALL:ALL) ALL'
    logins:
    - '{{email.local(external.email)}}'
    - '{{internal.logins}}'
```
```
kind: role
metadata:
  name: sudo-access
spec:
  allow:
    host_groups:
    - teleport-access
    host_sudoers:
    - '%teleport-access ALL = (ALL:ALL) ALL'
    logins:
    - '{{email.local(external.email)}}'
    - '{{internal.logins}}'
``` 

Using traits interpolation in `host_groups` and `host_sudoers`:
```
kind: role
metadata:
  name: sudo-access
spec:
  allow:
    host_sudoers:
    - '{{internal.logins}} ALL = (ALL:ALL) ALL'
    logins:
    - '{{email.local(external.email)}}'
    - '{{internal.logins}}'
```
```
kind: role
metadata:
  name: sudo-access
spec:
  allow:
    host_groups:
    - '{{external.department}}'
    host_sudoers:
    - '%{{external.department}} ALL = (ALL:ALL) ALL'
    logins:
    - '{{email.local(external.email)}}'
    - '{{internal.logins}}'
```
    
They all throw the same error:
```
disconnected
parse error in stdin near line 1

visudo: invalid sudoers file
ssh: could not start shell
```

Bug details:
- Teleport version: 14.3.3
- Recreation steps: See above
- Debug logs: N/A
