### ISSUE TITLE
Auto Discover for Nodes using agentless script

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#38035]
Expected behavior:
I'm able to add a Node using the agentless script

Current behavior:
The script executes the first step which downloads the script
When executing, it fails because `SSHD_CONFIG` variable doesn't exist.

Bug details:
- Teleport version: 15.0.1
- Recreation steps
Follow this guide https://goteleport.com/docs/server-access/guides/ec2-discovery/
But use the agentless installer script:
```yaml
discovery_service:
  enabled: "yes"
  poll_interval: 1m
  discovery_group: "prod-resources"
  aws:
    - types: ["ec2"]
      regions: ["eu-west-2"]
      tags:
        Discover: YesPlease
      install:
        script_name: "default-agentless-installer"
      ssm:
        document_name: "TeleportDiscoveryInstallMarco"
```

The matching EC2 instance is a brand new Amazon Linux 2023 box with SSM enabled and correctly running.

I'm getting the following error:

- Debug logs
