### ISSUE TITLE
Cannot set RDS proxy for SQL Server as static databases

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#38308]
Expected behavior:
```yaml
db_service:
  enabled: true
  databases:
  - name: "sample-rdsproxy-mssql"
    uri: "my-proxy.proxy-abcdefghijklmnop.us-west-1.rds.amazonaws.com:1433"
    protocol: "sqlserver"
```
Service should start

Current behavior:
```
ERROR REPORT:                                                                                                           
Original Error: *trace.BadParameterError missing keytab file path or kdc_host_name for database &#34;sample-rdsproxy-mssql&#34;             
Stack Trace:
    github.com/gravitational/teleport/lib/service/servicecfg/database.go:346 github.com/gravitational/teleport/lib/service/servicecfg.(*DatabaseAD).CheckAndSetDefaults
    github.com/gravitational/teleport/lib/service/servicecfg/database.go:128 github.com/gravitational/teleport/lib/service/servicecfg.(*Database).CheckAndSetDefaults
    github.com/gravitational/teleport/lib/config/configuration.go:1799 github.com/gravitational/teleport/lib/config.applyDatabasesConfig
    github.com/gravitational/teleport/lib/config/configuration.go:546 github.com/gravitational/teleport/lib/config.ApplyFileConfig
    github.com/gravitational/teleport/lib/config/configuration.go:2382 github.com/gravitational/teleport/lib/config.Configure
    github.com/gravitational/teleport/tool/teleport/common/teleport.go:544 github.com/gravitational/teleport/tool/teleport/common.Run         
```

Bug details:
- Teleport version: v15

RDS Proxy should be exempted from this:
https://github.com/gravitational/teleport/blob/3701a0f5ace68731f4a004334eed06aa1cf60cd2/lib/service/servicecfg/database.go#L126-L131
