### ISSUE TITLE
Headers change not working when using Kubernetes discovery for Grafana

### ISSUE THREAD

**Issue by idrikay** [gravitational/teleport#38414]
**Expected behavior**

Being able to access Grafana when using teleport. 

**Current behavior**

Getting "origin not allowed" on login page

**Setup**

We use teleport agents on our leaf clusters. The root teleport cluster is an ec2 machine. 
Apps are discovered with app_labels including Grafana. 

**What we have tried**

_1. Change Grafana config_ 

We are currently trying a simple Grafana statefulset and are passing environment variables in the following way:
```
env:
            - name: GF_MANAGED_IDENTITY_ENABLED
              value: 'true'
            - name: GF_SERVER_DOMAIN
              value: domain.net
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana-url-given-by-teleport.teleport.domain.net"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: 'true'
 ```
 
 We have tried changing the root url with or without protocol, switch to localhost etc.. without luck.
 We added the GF_SERVER_PROTOCOL variable and this didn't work either. 
 
 _2. Change teleport config directly_

``` 
 app_service:
  enabled: yes
  apps:
  - name: "grafana-test"
    uri: "http://localhost:3000"
    public_addr: grafana-url-given-by-teleport.teleport.domain.net
    rewrite:
       headers:
       - "Host: grafana-url-given-by-teleport.teleport.domain.net"
       - "Origin: grafana-url-given-by-teleport.teleport.domain.net"
  ```
  
Both 1 and 2 fail with the same errors.

**Comment by idrikay** [comment]
We eventually found a workaround. We needed to add the following to the Grafana Kubernetes service:

```
metadata:
  annotations:
    teleport.dev/app-rewrite: |
      headers:
      - name: "Host"
        value: "grafana-url-given-by-teleport.teleport.domain.net"
      - name: "Origin"
        value: "https://grafana-url-given-by-teleport.teleport.domain.net/"
```
