### ISSUE TITLE
Improve aws console app and IAM ARN correlation while creating the role

### ISSUE THREAD

**Issue by ba1ajinaidu** [gravitational/teleport#38538]
What would you like Teleport to do?

when users have n aws console apps in teleport, we have to add  n AWS IAM arns while creating a role and if all the IAM role names are same (as all of them are in AWS different accounts) then in the teleport UI all the arns are listed for each aws console app.

for eg: this is my role spec 
```
spec:
  allow:
    aws_role_arns:
    - arn:aws:iam::12345678910:role/teleport-FennelOperator
    - arn:aws:iam::98765432101:role/teleport-FennelOperator
 ```
and this is what I see on teleport UI and only one of them is the correct IAM role for the app
![image](https://github.com/gravitational/teleport/assets/72434180/98ffedcd-8a19-448f-a2a1-0643854283fd)

To avoid this there can be a correlation between the aws-console app and the aws IAM ARN which is added in the role which makes sure the IAM role if for that specific console app and shouldn't list any other roles.

What problem does this solve?
Listing multiple roles(of different accounts) on every aws console app even though the IAM ARN  doesn't belong to that app.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
FYI @roraback this is similar to the customer request I shared with you ~2 weeks ago.

**Comment by marcoandredinis** [comment]
> If a workaround exists, please include it.

As a workaround for this, you can filter the listed roles by setting a `aws_account_id` label in the AWS App Access Service's `teleport.yaml` configuration.

Eg
```yaml
app_service:
  enabled: "yes"
  apps:
  - name: "awsconsole"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
    labels:
      aws_account_id: "123456789012"
```
