### ISSUE TITLE
teleport doesn't forward port from subdirectory link

### ISSUE THREAD

**Issue by r0bin30n** [gravitational/teleport#38540]
Teleport v15.0.0 git:v15.0.0-0-ge126e8cd go1.21.6

**Purpose:** Teleport to an application https://hostname.int:2443/sub1/sub2/admin

**What happens:** Teleport forwards to address https://hostname.int/sub1/sub2/admin without port 2443 so the application is not accessed. If I change the uri to "https://hostname.int:port" I'm forwarded correctly with port 2443.

/etc/teleport.yaml
```
version: v3
teleport:
  nodename: teleport_server_hostname
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.ext
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.ext:443
  https_keypairs:
  - key_file: /certs/teleport.key
    cert_file: /certs/teleport.crt
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: yes
  apps:
  - name: "teleport-webapp"
    uri: "http://localhost:9000"
    public_addr: "teleport.ext"
  - name: "app-admin"
    uri: "https://hostname.int:2443/sub1/sub2/admin"
    public_addr: ""
    insecure_skip_verify: true
```
