### ISSUE TITLE
Make it easier to contact internal teams who run Teleport. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3863]
### Feature Request
As part of https://github.com/gravitational/teleport/issues/3774 the term "system administrator" is confusing, along with being a potentially dated term it isn't clear who would need to be contacted. 

This issue suggests adding a contact, that if set would be exposed via web and cli error message. To expand the contact concept, I've provided the optional best practice of linking to a /security.txt which would be shown at proxy.example.com:3080/.well-known/security.txt . 

```yaml
# This section configures the 'proxy service'
proxy_service:
    # Turns 'proxy' role on. Default is 'yes'
    enabled: yes

    #...
    public_addr: proxy.example.com:3080
    
    # Optional: contact
    contact: mailto:devops@example.com
    # Allow URLs to deep link to support tool / Slack
    # contact: https://join.slack.com/t/grv8/shared_invite/enQtNTE
    # For a fully hosted solution, we can provide our own email. 
    # contact: mailto:teleport-cloud@gravitational.com

    # Optional: securitytxt
    # Extend the config to add a security.txt to contact teams running / managing teleport. 
    securitytxt: https://www.example.com/.well-known/security.txt
```

- https://tools.ietf.org/html/draft-foudil-securitytxt-09
- https://securitytxt.org/

Related Issues:
 - https://github.com/gravitational/teleport/pull/3862

### Motivation
This makes it easier to contact the people who are running Teleport. Quickly debug errors and contact internal security teams if teams had misconfigured Teleport. 

### Who's it for?
OSS User, Pro, Enterprise
