### ISSUE TITLE
Application Access: Allow headers from Teleport -> browser to be rewritten/changed for certain apps

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#38702]
## What would you like Teleport to do?

Application Access allows you to rewrite the headers from Teleport -> app with `rewrite.headers`.

In some cases it would be useful to be able to inject or rewrite certain headers from Teleport to the client (browser) so that the app can be embedded into iframes or have its CSRF parameters tinkered with.

## What problem does this solve?

Allowing the use of Teleport to proxy access to apps in iframes.

Rough example:

```yaml
rewrite:
  client_headers:
  - "X-Frame-Options: ALLOW-FROM https://<target-url>/"
  - "Content-Security-Policy: frame-ancestors https://<target-url>/"
```

## If a workaround exists, please include it.

Use a reverse proxy between Teleport and the browser to inject the headers instead. Cumbersome and a bit unnecessary.

## Related issues

https://github.com/gravitational/teleport/issues/17588 - this doesn't solve the problem, but is in the same sort of space.

**Comment by ekrekeler** [comment]
I have a similar use case for such a feature.

I recently began using [MCSManager](https://github.com/MCSManager/MCSManager) and decided to configure the application service in the teleport agent for access to the web interface. Now, this application normally requires the use of two unique ports for access over a network, one for the frontend and one for the backend. With Teleport, access to the frontend and backend can be accomplished with a couple subdomains pointing to the Teleport proxy service listening on TCP 443 (HTTPS). However, this introduces a new problem because the browser needs to send requests to the backend while the origin is the frontend. That means the responses from the backend need to have the correct CORS headers present to permit the use of session cookies Teleport sets for authenticating through the proxy.

That's alot to unravel, so let me provide an example. Let's say `frontend.example.com` is the domain name for the frontend, and `backend.example.com` is the domain name for the backend. The backend is configured as a required app for the frontend in agent config. After authenticating to Teleport in the browser and launching `https://frontend.example.com`, Teleport returns the session cookies for the backend automatically in a `POST` request to `https://backend.example.com/x-teleport-auth`, then redirects the browser to the frontend. When browsing the frontend, `https://frontend.example.com` is the origin, and any XHR requests made to `https://backend.example.com` must follow CORS policy in order to authenticate through the Teleport proxy with the cookies set earlier. The browser will throw a CORS error and refuse the response from Teleport if either:

- `Access-Control-Allow-Origin` response header does not contain `https://frontend.example.com`
- `Access-Control-Allow-Credentials` response header is not `true`

I tested this extensively and documented it in [#1576](https://github.com/MCSManager/MCSManager/issues/1576) over in the MCSManager repo. As a workaround, I can configure the application to respond with the correct headers, or configure another proxy like nginx in the middle to add those headers in the response like @webvictim described. Ideally though, I should have the ability to set these headers in the Teleport application service configuration as it is a problem introduced by Teleport's authentication mechanism. We don't need these headers in the response for internal clients/apps making requests made directly to the application (bypassing Teleport proxy).

**Comment by ekrekeler** [comment]
As a bonus, it would be nice to have a template variable for the `public_addr` of each application defined in the agent config. This would circumvent the need to update the header values when changing the name of apps or the Teleport proxy's domain name. For example, the backend application could make use of this variable in the header rewrites:
```
app_service:
    apps:
    - name: "frontend"
      uri: "http://127.0.0.1:8080"
      required_apps:
          - "backend"
    - name: "backend"
      uri: "http://127.0.0.1:8081"
      rewrite:
          response_headers:
          - "Access-Control-Allow-Origin: https://{{app.frontend.public_addr}}"
          - "Access-Control-Allow-Credentials: true"
      cors:
          allowed_origins:
              - "https://{{app.frontend.public_addr}}"
          allow_credentials: true
          allowed_headers:
              - "Content-Type"
```

If it's not too difficult to implement as a separate feature, I figured this could be addressed here.
