### ISSUE TITLE
App session certs of impersonate user aren't deleted in etcd

### ISSUE THREAD

**Issue by pQraus** [gravitational/teleport#38787]
In our teleport setup with etcd (3 member) as storage backend, the size of the database is continuously growing.
I looked in etcd and saw that there are a lot of app sessions entries (`/teleport//apps/sessions/<id>`).
These ~ 54000 session entries are all from our special robot user (stbot, look in the setup section). 
I don't understand why there are so many sessions and why there are sessions that have already expired but have not been deleted.

## Setup
We have set up a teleport cluster in k8s with the helm chart. It's a HA cluster. For this reason we use etcd as the storage backend.

As described in this [comment](https://github.com/gravitational/teleport/issues/22484#issuecomment-1582720730), we need a way to dynamically access different teleport applications from other processes. Since MachineId doesn't currently support this feature, we created our own robot user (the stbot). We used the impersonation feature to create the non-interactive stbot user (like descried in the [docs](https://goteleport.com/docs/ver/13.x/access-controls/guides/impersonation/)).

Our stbot service gets an identity file that is vaild for 180 days. With this identity, our stbot service creates short-lived certificates for various teleport applications and a short-lived identity file. These short-lived secrets are used by other services that need access to the applications. The stbot creates new certificates / identity file every 10 minutes with a validity period of 2 hours.
(After 180 days we to manually exchange the identity file used by the stbot itself.)

It seems that every time the stbot creates new certs, a new entry `/teleport//apps/sessions/<id>` is created in etcd. 

## Expected behavior:
When the stbot creates a cert, a new session (`/teleport//apps/sessions/<id>`) is created by teleport in etcd. This session has a validity period of 2h. When the session expires, it should be deleted from etcd by teleport.

## Current behavior:
When the stbot creates a cert, a new session in etcd is created. The expirtion time in the session entry is equal to the expiration time of the identity file that the stbot uses to create the certs. It isn't 2h. Each session that is created has same metadata and expiration time. After ~ 180 days there are ~ 55000 session entries in etcd. The storage space used for these sessions is almost 0.5 GB.

The sessions are not deleted. All sessions that were valid until 21.02.2024 are also still contained in etcd.

Perhaps everything is already working as expected and it is not a bug. Then the design of the stbot would have to be updated.

## Bug details:
- Teleport version: 13.4.14, Teleport Community Edition deployed via Helm in k8s

## Logs / Snipptes

**content of a session entry (without real certs):**
```json
{
    "kind":"web_session",
    "sub_kind":"app_session",
    "version":"v2",
    "metadata":{
        "name":"0000c89293765ef84b3e6af711082b87o7e059c98599540d32ka5fda0901d54c",
        "expires":"2024-02-21T09:29:41.008793061Z"
    },
    "spec":{
        "user":"stbot",
        "pub": "<pub-cert>",
        "priv":"<private-cert>",
        "tls_cert":"<tls-cert>",
        "bearer_token":"<bearer-token>",
        "bearer_token_expires":"0001-01-01T00:00:00Z",
        "expires":"2024-02-21T09:29:41.008793061Z",
        "login_time":"0001-01-01T00:00:00Z",
        "idle_timeout":"0s"
    }
}
```
- each session has different certs and same metadata, expiration time

**stbot service mockup:**
```
while True:
    tctl auth sign --identity=<stbot-identity-file> --auth-server=myteleport.com --user=stbot --out=<short-lived-identity-file> --ttl=2h --overwrite
    for app in apps:
        tctl auth sign --identity=<stbot-identity-file> --auth-server=myteleport.com --user=stbot --app-name=app --out=<short-lived-identity>/app --format=tls --ttl=2h
    sleep(10min)

```

**cluster config (`values.yaml`):**
```
chartMode: scratch
clusterName: <my-teleport.com>
persistence:
  enabled: false

highAvailability:
  replicaCount: 2

auth:
  extraVolumeMounts:
    - name: etcd-secrets
      readOnly: true
      mountPath: /etc/etcd
  extraVolumes:
    - name: etcd-secrets
      secret:
        secretName: etcd-client-cert
  teleportConfig:
    version: v3
    auth_service:
      enabled: true
      proxy_listener_mode: multiplex
      listen_addr: 0.0.0.0:3025
      cluster_name: <my-teleport.com>
      session_recording: "off"
    teleport:
      storage:
        type: etcd
        peers: ["etcd.etcd.svc.cluster.local:2379"]
        tls_cert_file: /etc/etcd/tls.crt
        tls_key_file: /etc/etcd/tls.key
        tls_ca_file: /etc/etcd/ca.crt
        prefix: /teleport/
proxyListenerMode: multiplex
tls:
  existingSecretName: teleport-certs

proxy:
  teleportConfig:
    version: v3
    teleport:

      join_params:
        method: kubernetes
        token_name: "teleport-proxy"
      auth_server: "teleport-auth.teleport.svc.cluster.local:3025"
      log:
        output: stderr
        severity: INFO
    proxy_service:
      enabled: true
      web_listen_addr: 0.0.0.0:3080
      public_addr: <my-teleport.com>
      ssh_public_addr: <my-teleport.com>
      tunnel_public_addr: <my-teleport.com>
      https_keypairs:
        - key_file: /etc/teleport-tls/tls.key
          cert_file: /etc/teleport-tls/tls.crt
      https_keypairs_reload_interval: 12h

podSecurityPolicy:
  enabled: false
service:
  type: ClusterIP
```
