### ISSUE TITLE
Fix default auth server address

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#38822]
Expected behavior:
- If user configures other services alongside `auth_service`, but does not specify `auth_server` or `auth_servers`, then the default should be to use `localhost:<auth listener port>`

Here's an example config that should work:
```yaml
teleport:
  nodename: example
  log:
    output: stderr
    severity: INFO

ssh_service:
  enabled: yes

auth_service:
  enabled: yes
  keep_alive_interval: 1m
  keep_alive_count_max: 3
  listen_addr: 0.0.0.0:3025
  authentication:
    type: saml
    second_factor: off
  cluster_name: example
  proxy_listener_mode: separate
  web_idle_timeout: 15m
  license_file: /var/lib/teleport/license.pem

proxy_service:
  enabled: no
```

Current behavior:

By default, the configuration set auth server address for the `ssh_service` to be `0.0.0.0:3025`. Whether or not that address actually works when dialing auth depends on the environment. On my mac it seems to be ok. On linux hosts, it can fail. `0.0.0.0` is not a real target ipv4 address.

In this case, we can infer that the service should just dial over the loopback interface.

Bug details:
- Teleport version: master
- Recreation steps: see above config. run on a linux box.
- Debug logs:
```
Feb 26 17:16:08 ip-10-151-50-70 teleport[1609]: 2024-02-26T17:16:08Z ERRO [PROC:1]    "Instance failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tconnection error: desc = \"transport: Error while dialing: failed to dial: unable to proxy connection: 403 Forbidden\", connection error: desc = \"transport: Error while dialing: failed to dial: Get \\\"https://0.0.0.0:3025/webapi/find\\\": Forbidden\"." pid:1609.1 service/connect.go:108
```
