### ISSUE TITLE
Add "engine" tag for ElastiCache Redis cluster

### ISSUE THREAD

**Issue by rifler** [gravitational/teleport#38922]
### What would you like Teleport to do?
Teleport Database Service adds several labels for auto discovered clusters/databases, including `engine` - https://goteleport.com/docs/database-access/reference/labels/#auto-discovery

Unfortunately, there is no `engine` label for Elasticache Redis.

It would be nice to add `"engine": "elasticache-redis"` label.

### What problem does this solve?
Labels unification

### If a workaround exists, please include it.

**Comment by GavinFrazar** [comment]
@rifler Is there a specific use-case for which you want this label for auto-discovered ElastiCache Redis databases?

I ask because we have been considering adding the discovery matcher `type` as a label to auto-discovered databases.
I wonder if that might suit your use case as well?

The use-case we have in mind for that: split permissions into separate IAM roles and use `assume_role_arn` to assume a role for a specific "type" of discovered database.

For example, Teleport has matcher types "redshift" and "elasticache", and if we added a label for discovered databases that corresponds to these discovery matcher type then I could make the Teleport db_service assume a different role based on the type of matcher. That would allow me to split the permissions into separate roles:
```yaml
db_service:
  enabled: true
  resources:
    - labels:
        "teleport.dev/origin": "cloud"
        # hypothetical new label for matcher type
        "teleport.dev/matcher_type": "redshift"
      aws:
        assume_role_arn: "arn:aws:iam::123456789012:role/gavin-tf-redshift-access"
    - labels:
        "teleport.dev/origin": "cloud"
        "teleport.dev/matcher_type": "elasticache"
      aws:
        assume_role_arn: "arn:aws:iam::123456789012:role/gavin-tf-elasticache-access"
```

and a discovery service which also separates the permissions for elasticache/redshift discovery for example:
```yaml
discovery_service:
  enabled: true
  discovery_group: "example"
  aws:
    - types:
      - "redshift"
      regions:
        - "us-west-1"
        - "us-west-2"
      assume_role_arn: "arn:aws:iam::123456789012:role/gavin-tf-redshift-discovery"
    - types:
      - "elasticache"
      regions:
        - "us-west-1"
        - "us-west-2"
      assume_role_arn: "arn:aws:iam::123456789012:role/gavin-tf-elasticache-discovery"
```
