### ISSUE TITLE
Kubernetes Application Discovery fails when the cluster DNS suffix is not cluster.local

### ISSUE THREAD

**Issue by oliverfrye** [gravitational/teleport#39007]
I have been attempting to get Teleport's Kubernetes Application Discovery to work with a new GKE cluster I have created. This GKE cluster has a non-standard DNS suffix, `gke.local`. Although the Teleport Agent appears to successfully discover the application, I am not able to connect to it - instead I receive an `Internal Server Error`.

Looking in the logs reveals that the Teleport Agent is attempting to forward my request to a hostname with the suffix `cluster.local`.

I have located what I believe is the cause - the `cluster.local` suffix is hardcoded in the `getServiceFQDN()` function, which the autodiscovery code seems to rely upon.

https://github.com/gravitational/teleport/blob/4c26c2a426315292a905db33e351813764933ac3/lib/srv/discovery/fetchers/kube_services.go#L284

I would expect that the Teleport Agent would either not append a suffix (allowing the normal FQDN search to take place on the upstream DNS server), or would lookup the correct suffix to append instead of assuming it will be `cluster.local`.

**Comment by zzvara** [comment]
The Teleport guys have hard-coded the `cluster.local` to unimaginable places if you search for it. Therefore, five of the clusters I use are not supported.

**Comment by zzvara** [comment]
@oliverfrye, the issue can be fixed in Kubernetes by rewriting DNS queries against the missing `cluster.local` domain. You must:

1. Update the DNS server configurations.
2. Tweak DNS query settings on the Teleport `Pods`.

### Update `nodelocaldns` `ConfigMap`

Add the following to the `ConfigMap:kube-system/nodelocaldns`:

```
cluster.local:53 {
    errors
    cache 30
    reload
    loop
    bind 169.254.25.10
    forward . 10.233.0.3 {
        force_tcp
    }
    prometheus :9253
}
```

Then restart all `nodelocaldns` instances.

### Update the `coredns` `ConfigMap`

Add the following to the `ConfigMap:kube-system/coredns`:

```
# Add this
rewrite stop {
   name regex (.*)\.cluster\.local {1}.custom-domain
   answer name (.*)\.custom-domain {1}.cluster.local
}
# This is already there, just add "cluster.local" into the list 
kubernetes custom-domain cluster.local in-addr.arpa ip6.arpa {
  pods insecure
  fallthrough in-addr.arpa ip6.arpa
}
```

Then restart all `coredns` instances.

### Ensure that `nDots` is `1` for Teleport services

The default `nDots` is `5` in `/etc/resolv.conf` for all `Pods` in Kubernetes.

Create a Kyverno policy for updating the `nDots` to `1`. Teleport is already using FQDN's, therefore the setting of 1 is good enough.

```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: teleport-dns-tweak
  namespace: teleport-system
spec:
  background: false
  rules:
    - name: set-dns-config-ndots
      match:
        resources:
          kinds:
            - Pod
          selector:
            matchLabels:
              app.kubernetes.io/instance: teleport
      mutate:
        patchStrategicMerge:
          spec:
            dnsConfig:
              options:
                - name: ndots
                  value: "1"
```

### Delete Teleport `Pods`

![image](https://github.com/gravitational/teleport/assets/8371789/75c47113-9b87-4b33-821f-769bb681c178)
