### ISSUE TITLE
Newly created desktop user not assigned to Administrators group. 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#39153]
Expected behavior:
A newly created desktop user should be assigned to the administrators group with the appropriate role rules in place. 

```yaml
kind: role
version: v7
metadata:
  name: windows-desktop-admins
spec:
  allow:
    desktop_groups:
    - Administrators
    windows_desktop_labels:
      '*': '*'
    windows_desktop_logins:
    - Administrator
    - alice
  deny: {}
  options:
    cert_format: standard
    client_idle_timeout: 1h0m0s
    create_db_user: false
    create_desktop_user: true
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
```

Current behavior:

Despite having the setting `spec.allow.desktop_groups: Admininstrators`  the user does not get assigned to Administrators. 

Bug details:
- Teleport version v15.1.1 Teleport Cloud 
- Teleport Agent 14.3.6 
- Recreation steps
- Debug logs

```
C:\Users\alice>net user alice
User name                    alice
Full Name                    alice
Comment                      This user is managed by Teleport
User's comment               
Country/region code          000 (System Default)
Account active               No
Account expires              Never

Password last set            3/8/2024 7:09:20 PM
Password expires             Never
Password changeable          3/8/2024 7:09:20 PM
Password required            No
User may change password     No

Workstations allowed         All
Logon script                 
User profile                 
Home directory               
Last logon                   Never

Logon hours allowed          All

Local Group Memberships      *Teleport Users       
Global Group memberships     *None                 
The command completed successfully.
```
```
C:\Users\alice>whoami
ec2amaz-d6lum45\alice
```

```
C:\whoami /groups
GROUP INFORMATION
-----------------

Group Name                             Type             SID                                            Attributes                                        
====================================== ================ ============================================== ==================================================
Everyone                               Well-known group S-1-1-0                                        Mandatory group, Enabled by default, Enabled group
EC2AMAZ-D6LUM45\Teleport Users         Alias            S-1-5-21-2670300200-3167696898-4194707200-1000 Mandatory group, Enabled by default, Enabled group
BUILTIN\Users                          Alias            S-1-5-32-545                                   Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\REMOTE INTERACTIVE LOGON  Well-known group S-1-5-14                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\INTERACTIVE               Well-known group S-1-5-4                                        Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Authenticated Users       Well-known group S-1-5-11                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\This Organization         Well-known group S-1-5-15                                       Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Local account             Well-known group S-1-5-113                                      Mandatory group, Enabled by default, Enabled group
LOCAL                                  Well-known group S-1-2-0                                        Mandatory group, Enabled by default, Enabled group
BUILTIN\Remote Desktop Users           Alias            S-1-5-32-555                                   Mandatory group, Enabled by default, Enabled group
Mandatory Label\Medium Mandatory Level Label            S-1-16-8192  
```
