### ISSUE TITLE
let tbot accept a URL for auth_server 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#39209]
What would you like Teleport to do?
I've some automation that uses `"${auth_servers}:443"`, I was using this for both tbot and teleport, but I noticed that tbot won't work if it has the FQDN supplied, and only `auth_server: teleport-ent-15.asteroid.earth:443` works.  To keep things consistent and streamline my config it would be good to accept both.

```yaml
# ${auth_server} = https://mid.teleport.sh/
write_files:
  - path: /etc/teleport.yaml
    content: |
        teleport:
            nodename: vuls-io
            auth_token: ${auth_token}
            auth_servers:
                - "${auth_server}:443"

...

  - path: /etc/tbot.yaml
    content: |
      version: v2
      debug: true
# Note: tbot only accepts mid.teleport.sh/, it doesn't work if it's a URL, e.g. https:// is added. 
      auth_server: ${auth_server}:443
      onboarding:
...
```

What problem does this solve?
DX and standards across tooling. 

If a workaround exists, please include it.
