### ISSUE TITLE
Audit log still appears when your role doesn't grant you access to it

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3922]
**What happened**: In 4.3, I set up this role:

```yaml
kind: role
metadata:
  name: testrole
spec:
  allow:
    logins:
    - root
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny:
    logins: null
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```

The test says:
Verify that a user has access only to: "Cluster List", "Nodes", and "Active Sessions"

I have access to those things, but I also have access to the "Audit Log" menu item even though I shouldn't. Nothing loads because I don't have permission to view it, so it seems like "Audit Log" appearing at all is a bug and we should hide it.

![2020-06-26-153245__1935x338__maim](https://user-images.githubusercontent.com/897821/85890164-368df480-b7c3-11ea-85a4-1728cff147c3.png)

In 4.2, there is no audit log for me to have access to.

![2020-06-26-153613__2436x294__maim](https://user-images.githubusercontent.com/897821/85890199-43124d00-b7c3-11ea-8e1c-980db0936534.png)

**What you expected to happen**: Audit log should not be accessible with the above role.

**How to reproduce it (as minimally and precisely as possible)**: Add the above role, give it to a user, log in with that user, observe.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-master.1git:v4.2.0-alpha.5-444-g3976a9977-dirty go1.13.2`
