### ISSUE TITLE
Web UI should show GCP/Azure logos for GCP and Azure CLI App Access

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#39342]
<img width="1410" alt="Screenshot 2024-03-14 at 10 21 21 AM" src="https://github.com/gravitational/teleport/assets/12417665/84b3e22e-268f-4cec-afe1-67ecc8f1a3b5">

Expected behavior:
Azure/GCP cli apps should use their logos similar to AWS app.

Current behavior:
See above screenshot

Bug details:
- Teleport version:v15
- Recreation steps
```
app_service:
  enabled: "yes"
  apps:
  - name: "redis-tcp"
    uri: tcp://localhost:6381
  - name: "some-app"
    uri: http://localhost:8080
  - name: "aws"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
  - name: "azure"
    cloud: "Azure"
  - name: "gcp"
    cloud: "GCP"
```
