### ISSUE TITLE
Logins of GitHub User are overwritten

### ISSUE THREAD

**Issue by naimo84** [gravitational/teleport#39552]
Expected behavior:
To be able to update the logins of a github connected user with
``tctl users update --set-logins naimo84,naimo naimo84``

Current behavior:
After setting the logins via ``tctl users update --set-logins naimo84,naimo naimo84``, the next login resets the logins to ``naimo84``

Bug details:
- Teleport version: v15.1.1 git:v15.1.1-0-g33b3ad2 go1.21.7
- Recreation steps

  - enable the github Connector
  ![image](https://github.com/gravitational/teleport/assets/11535502/f8ef6b9b-5db3-4cf1-88ba-9cd9bfa1cd01)

  - set logins and check ``tctl get user/naimo84``
      ```
      kind: user
      metadata:
        expires: "..."
        id: ...
        name: naimo84
        revision: ...
      spec:
        created_by:
          connector:
            id: github
            identity: naimo84
            type: github
          time: "..."
          user:
            name: system
        expires: "0001-01-01T00:00:00Z"
        github_identities:
        - connector_id: github
          username: naimo84
        roles:
        - access
        status:
          is_locked: false
          lock_expires: "0001-01-01T00:00:00Z"
          locked_time: "0001-01-01T00:00:00Z"
        traits:
          github_teams:
          - home
          kubernetes_groups: null
          kubernetes_users: null
          logins:
          - naimo84
          - naimo      
          - benjamin
      version: v2
      ```
  - login via github 
  - see that logins are reset to naimo84
      ```
        kind: user
        metadata:
          expires: "..."
          id: ...
          name: naimo84
          revision: ...
        spec:
          created_by:
            connector:
              id: github
              identity: naimo84
              type: github
            time: "..."
            user:
              name: system
          expires: "0001-01-01T00:00:00Z"
          github_identities:
          - connector_id: github
            username: naimo84
          roles:
          - access
          status:
            is_locked: false
            lock_expires: "0001-01-01T00:00:00Z"
            locked_time: "0001-01-01T00:00:00Z"
          traits:
            github_teams:
            - home
            kubernetes_groups: null
            kubernetes_users: null
            logins:
            - naimo84
        version: v2```

- Debug logs

**Comment by strideynet** [comment]
This is likely expected behaviour - SSO Users are not intended to be modified and if we allowed their modification, then we would not be able to reflect changes to the SSO connector configuration. If you need to customise SSO created users, then login rules (https://goteleport.com/docs/access-controls/login-rules/)  or the connector config itself should be used.

**Comment by naimo84** [comment]
Thanks for sharing your idea behind SSO Users 👍  and the link to the login roles. I'll try it later.
I'll close the issue. 

Sry for that, but after searching for some hours I didn't find it... Googling the right term is sometimes hard 😉

**Comment by naimo84** [comment]
Ok, unfortunately it's only a Enterprise feature. So, as a homelabber, I'm out...

**Comment by naimo84** [comment]
The connector config itself is working 👍 : https://goteleport.com/docs/access-controls/sso/github-sso/#step-23-create-a-github-authentication-connector

```yaml
---
kind: role
metadata:
  description: naimo Access cluster resources
  name: naimo
spec:
  allow:
    app_labels:
      "*": "*"
    logins:
      - "{{internal.logins}}"
      - "naimo"
    node_labels:
      "*": "*"
    rules:
      - resources:
          - event
        verbs:
          - list
          - read
      - resources:
          - session
        verbs:
          - read
          - list
        where: contains(session.participants, user.metadata.name)
      - resources:
          - instance
        verbs:
          - list
          - read
      - resources:
          - assistant
        verbs:
          - list
          - create
          - read
          - update
          - delete
          - use
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
      - command
      - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: true
    ssh_file_copy: true
version: v5
```
