### ISSUE TITLE
Starting etcd in insecure mode returns missing PEM block error.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3961]
It's not clear how the `insecure` flag is used with etcd. If my storage section looks like the following:

```
  storage:
    type: etcd
    prefix: rusty-backend

    insecure: true
    peers: ["http://127.0.0.1:2379"]
```

I get the following error.

```
ERROR REPORT:
Original Error: *trace.BadParameterError missing PEM encoded block
```

We should document how the `insecure` flag works (you still need certs, it's just that Teleport won't verify them) and improve the error message above to explain what the user has to do.
