### ISSUE TITLE
Cannot use kubectl on Kubernetes cluster but can access applications

### ISSUE THREAD

**Issue by idrikay** [gravitational/teleport#39666]
**We have configured our Kubernetes clusters and are able to access applications there. However no kubectl command goes through on teleport connect.** 

_Expected behavior:_

Able to access Kubernetes resources

_Current behavior:_

Unable to access Kubernetes resources

When looking at the logs of the root cluster we get the following:
```
Failed to handle client connection: received kube request but k8 service is disabled alpnproxy/proxy.go:334
```
The teleport connect terminal returns
```
$ kubectl get pods
couldn't get current server API group list: an error on the server ("Internal Server Error") has prevented the request from succeeding
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding
```

_Teleport version: 15.1.8_

**Comment by tigrato** [comment]
Can you please share your teleport's proxy config file?

**Comment by idrikay** [comment]
```
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.${DOMAIN}
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: webauthn
    webauthn:
      rp_id: teleport.${DOMAIN}
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.${DOMAIN}:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: ${MY_EMAIL}
```

**Comment by tigrato** [comment]
```yaml
version: v3

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.${DOMAIN}
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: webauthn
    webauthn:
      rp_id: teleport.${DOMAIN}
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.${DOMAIN}:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: ${MY_EMAIL}
```

add the first line to your config. When not specifying the version, we default to v1 which doesn't automatically enable kube proxy.
