### ISSUE TITLE
Support natively Access Monitoring in `teleport-cluster` Helm chart

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#39900]
Followup on https://github.com/gravitational/teleport/issues/35205, blocked by <replace when we have the docs issue ID>.

### What would you like Teleport to do?

`teleport-cluster` Helm chart should offer a flag to enable Access Monitoring.

### What problem does this solve?

Ease of deployment and time-to-value for Access Monitoring users.

### If a workaround exists, please include it.

Since https://github.com/gravitational/teleport/pull/39801 the AWS mode supports Athena properly. You can configure the Athena backend and pass the access monitoring values with

```yaml
auth:
  teleportConfig:
    auth_service:
      access_monitoring:
        enabled: true
        # AWS role ARN that Teleport will assume to execute Athena SQL queries.
        role_arn: arn:aws:iam::111111111111:role/access-monitoring-role
        # S3 bucket where Access Monitoring reports will be stored.
        report_results: s3://audit-log-example/report_results
```

However, you must know how to set up the bucket and IAM role/permissions for impersonation/athena queries.
