### ISSUE TITLE
Sessions list, read no longer allow viewing past sessions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3999]
### Description

**What happened**:
Users that have session `list` and `read` could view past sessions.  Now they can only see active sessions. 

**What you expected to happen**:

Users can see if not the event log but the sessions replayable.

**How to reproduce it (as minimally and precisely as possible)**:

Create a role that only has session list and read, not event access.  The user will only be able to see active sessions.  

```yaml
  - resources:
      - session
      verbs:
      - list
      - read
```

### Environment
- Teleport version (use `teleport version`): 4.3.0
- OS (e.g. from `/etc/os-release`): Amazon 2 linux

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aWS EC2

**Browser environment**

- Browser Version (for UI-related issues): Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by alex-kovoy** [comment]
@stevenGravy 

> What you expected to happen:  Users can see if not the event log but the sessions replayable.

If a user does not have an access to audit events (resource: event) then they cannot replay a session (which is a series of  events). This behavior has not changed.

"Archive Sessions" are not part of Audit Log.

**Comment by alex-kovoy** [comment]
(closing as by design, feel free to re-activate it if I misunderstood it)

**Comment by benarent** [comment]
@alex-kovoy Could you please inline document what our RBAC UI rules are in 4.3, and please add the verbs for `events`

```   
 # list of allow-rules. see below for more information.
    rules:
    - resources: [role]
      verbs: [list, create, read, update, delete]
    - resources: [auth_connector]
      verbs: [connect, list, create, read, update, delete]
    - resources: [session]
      verbs: [list, read]
    - resources: [trusted_cluster]
      verbs: [connect, list, create, read, update, delete]
```
