### ISSUE TITLE
Display Account when picking the IAM Role to use in AWS App Access

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#40652]
**What would you like Teleport to do?**
Teleport should show the AWS Account ID when listing the IAM Roles for AWS App Access.

![image](https://github.com/gravitational/teleport/assets/689271/37ff096d-c640-4df1-92db-a73118ab7400)

To reduce clutter, we should only show the account id if there's at least two distinct account ids.

**What problem does this solve?**
If the user has access to multiple AWS Accounts, and if the configured role name is the same in all of them, it will show the exact same name:
![image](https://github.com/gravitational/teleport/assets/689271/878ac435-16d7-4ef6-a6bb-16c30fff42c6)

**If a workaround exists, please include it.**
Change the Role Name in AWS and in the Teleport's Role AWS ARN (or user's traits).

**Comment by dmsergeevN26** [comment]
This is something we've been missing as well.

**Comment by greedy52** [comment]
In general, you should have separate AWS apps per AWS account
https://goteleport.com/docs/application-access/cloud-apis/aws-console/#multiple-aws-accounts

```yaml
app_service:
  enabled: "yes"
  apps:
  - name: "awsconsole-test"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
    labels:
      aws_account_id: "1234567890"
      env: test
  - name: "awsconsole-prod"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
    labels:
      aws_account_id: "0987654321"
      env: prod
```
