### ISSUE TITLE
Provide configuration example for cross account AWS EKS auto-discovery

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#41353]
## Applies To

[AWS EKS Auto-Discovery - Configure the Teleport Kubernetes and Discovery Services](https://goteleport.com/docs/auto-discovery/kubernetes/aws/#configure-the-teleport-kubernetes-and-discovery-services)

## Details

The additional configuration required for cross account EKS auto-discovery is not provided in the guide. Here is an example of the configuration required for this:

```
kubernetes_service:
    enabled: true
    labels:
      'somelabel': 'somevalue'
    resources:
    - labels:
        'account-id': 'A'
      aws:
        assume_role_arn: arn:aws:iam::A:role/cp_teleport_auto_discovery
    - labels:
        'account-id': 'B'
      aws:
        assume_role_arn: arn:aws:iam::B:role/cp_teleport_auto_discovery
```

## How will we know this is resolved?

When cross account EKS auto-discovery is documented.

## Related Issues

N/A
