### ISSUE TITLE
Provide a configuration example of a Database Service in the AWS Database Auto-Discovery guide

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#41354]
## Applies To

[AWS Database Auto-Discovery - List Registered Databases](https://goteleport.com/docs/auto-discovery/databases/#list-registered-databases)

## Details

Provide a configuration example of a Database Service in this guide so that you can quickly access discovered databases. This will improve the "time to value" and not require you to read other guides on how to connect to discovered databases.

```
## This section configures the Database Service
db_service:
    enabled: "yes"
    # Matchers for dynamic database resources created with the "tctl create" command or by database auto-discovery.
    resources:
    - labels:
        "*": "*" # can be configured to limit the databases to be watched by this service.
```

Note that this is documented for Kubernetes auto-discovery [here](https://goteleport.com/docs/auto-discovery/kubernetes/#forwarding-requests-to-the-kubernetes-cluster).

## How will we know this is resolved?

The guide is updated to include the configuration above.

## Related Issues

N/A
