### ISSUE TITLE
Web UI Audit log page errors with fresh Firestore backend

### ISSUE THREAD

**Issue by kinghrothgar** [gravitational/teleport#4142]
### Description

**What happened**:
Setup fresh 4.3.2 teleport server with Firestore and Google Storage backend. Audit Log page in web UI shows no sessions and displays error:

```
rpc error: code = FailedPrecondition desc = The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/<REDACTED>/firestore/indexes?create_composite=Cltwcm9qZWN0cy9leHBlbC1lbmdpbmVlcmluZy1pbnRlcm5hbC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGVsZXBvcnQvaW5kZXhlcy9fEAEaEgoOZXZlbnROYW1lc3BhY2UQARoNCgljcmVhdGVkQXQQARoMCghfX25hbWVfXxAB
```

**What you expected to happen**:
It to work

**How to reproduce it (as minimally and precisely as possible)**:
Setup fresh 4.3.2 teleport server with Firestore and Google Storage backend

### Environment
- Teleport version (use `teleport version`): 4.3.2
- OS (e.g. from `/etc/os-release`): Gravitatonal Released docker image

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
GKE

- Storage section of config:
```
      storage:
        type: firestore
        project_id: <REDACTED>
        collection_name: teleport
        credentials_path: /opt/sa/sa.json
        audit_events_uri:  ['firestore://teleport?credentialsPath=/opt/sa/sa.json&projectID=<REDACTED>']
        audit_sessions_uri: gs://expel-teleport-staging?credentialsPath=/opt/sa/sa.json&projectID=<REDACTED>
```

**Browser environment**

- Browser Version (for UI-related issues): Chrome
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`
