### ISSUE TITLE
Example of a Config file contains a mistake

### ISSUE THREAD

**Issue by MoogyG** [gravitational/teleport#41487]
## Applies To

https://goteleport.com/docs/reference/backends/

## Details

```
storage:
  teleport:
    audit_events_uri:
      - postgresql://user_name@database-address/teleport_audit?sslmode=verify-full#disable_cleanup=false&retention_period=2160h
```

should be

```
teleport:
  storage:
    audit_events_uri:
      - postgresql://user_name@database-address/teleport_audit?sslmode=verify-full#disable_cleanup=false&retention_period=2160h
```
