### ISSUE TITLE
app launcher dropdown shows aws roles that are not allowed for app

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#41499]
Expected behavior:
- the app launcher dropdown should only display usable (i.e. allowed by RBAC) aws roles for an app.

Current behavior:
- the app launcher shows all the available aws roles that a user has across their roleset, regardless of whether those roles are actually allowed by Teleport's RBAC.

For example, here I have an aws console app with this spec:
```yaml
---
kind: app
version: v3
metadata:
  name: "app"
  description: "example"
  labels:
    env: "dev"
    host: "mbp"
spec:
  uri: "https://console.aws.amazon.com"
  public_addr: ""
```

My user has the preset access role, and these user traits:
```yaml
  traits:
    aws_role_arns:
    - arn:aws:iam::999999999999:role/allowed_one
    - arn:aws:iam::999999999999:role/allowed_two
```

and my user also has the following role:
```yaml
kind: role
version: v5
metadata:
  name: aws-dynamodb-access
spec:
  allow:
    app_labels:
      env: prod
    aws_role_arns:
    - arn:aws:iam::123456789012:role/ProdAdmin
  deny: {}
```

NOTE: the `aws-dynamodb-access` role's `app_labels` do not match the labels for my example app, therefore RBAC will not allow me to actually use the `ProdAdmin` aws IAM role.
So the only thing I should see in the launcher are the two allowed roles from my user traits.
However, I see all of them:
![image](https://github.com/gravitational/teleport/assets/16846283/7b51a406-ecf4-4a9c-8807-b8477d40d53c)

If I click on the `ProdAdmin` role in the launcher, access is denied and I get an unhelpful "Not found" page (we intentionally obscure access errors with "not found"):
![image](https://github.com/gravitational/teleport/assets/16846283/4a3bb93e-543d-4a55-9c76-3005521e5f7d)

This is poor UX and has tripped up at least one customer in a support ticket.

Bug details:
- Teleport version: master / v16.0.0-dev
- Recreation steps: see above example.
