### ISSUE TITLE
Upgrading from 14.3.18 to 14.3.20 broke configured agent applications

### ISSUE THREAD

**Issue by voidburn** [gravitational/teleport#42040]
Expected behavior: Upgrade did not interrupt app services
Current behavior: Most of the applications configured in agents stopped working

Bug details:
- Teleport version: 14.3.20
- Recreation steps: upgrade from 14.3.18 
- Debug logs:

# Auth service logs
`Omitting service "App" for control stream of instance {UUID} (unknown or unauthorized). auth/auth_with_roles.go:1005`

# Affected agents logs
`Inventory control stream failed: inventory control stream closed: control stream not configured to support app server heartbeats inventory/inventory.go:196`

# Description
After upgrading to 14.3.20 for the security fix most of the apps exposed by the agents stopped working (not all). Others came up and went down a few times, but remained unreliably available, until they stopped appearing among available resources.

SSH services were unaffected and working.

I tried generating new tokens valid for both node and app types with `tctl tokens add --type=node,app`, thinking that might solve the authentication issues, but it didn't.

We reverted to version 14.3.18 (last known working) and everything returned to normal.

Our agents are installed in virtual environments and typically expose an ssh node and 1+ apps, using a config similar to this:

```yaml
version: v3
teleport:
  nodename: REDACTED
  data_dir: /var/lib/teleport
  join_params:
    token_name: REDACTED
    method: token
  proxy_server: REDACTED:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: REDACTED
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    env: "REDACTED"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: "REDACTED"
    uri: https://REDACTED:8006
    public_addr: "REDACTED"
    insecure_skip_verify: true
    labels:
      env: "REDACTED"
  - name: "REDACTED"
    uri: https://REDACTED:443
    public_addr: "REDACTED"
    insecure_skip_verify: true
    labels:
      env: "REDACTED"
      type: "REDACTED"
      machine: "REDACTED"
```

Proxy log since the service restart (post-upgrade to 14.3.20) and until the first issues appeared: [teleport-proxy.txt](https://github.com/gravitational/teleport/files/15443217/teleport-proxy.txt)
