### ISSUE TITLE
 SSH Service: Add config on node itself to control logins without the need of pam

### ISSUE THREAD

**Issue by C-Logemann** [gravitational/teleport#42222]
Because I just started evaluating Teleport and maybe I have been missing something. So I only find rule sets controlled on the proxy.

## What would you like Teleport to do?
It would be nice to have an easy way to configure on a node /etc/teleport.yaml which logins can be accessed via teleport on this node.

## What problem does this solve?
Easy implementing of security concepts like disable root and other privileged users or only allow a list of users or users with a naming scheme like "app-*".

## If a workaround exists, please include it.
I successfully tested the following workaround with Debian 12 on Proxy and Node.
Following https://goteleport.com/docs/reference/config/#ssh-service I activated pam but I needed to use "use_pam_auth: false".

```
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: 06axxxxx-027f-411b-ba55-2xxxxxxxxxxx
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  pam:
        # "no" by default
        enabled: yes
        # use /etc/pam.d/sshd configuration (the default)
        service_name: "sshd"
        # use the "auth" modules in the PAM config
        # "false" by default
        use_pam_auth: false
```

In /etc/pam.d/sshd I activated the usage of /etc/security/access.conf :
```
# Uncomment and edit /etc/security/access.conf if you need to set complex
# access limits that are hard to express in sshd_config.
account  required     pam_access.so
```

In "/etc/security/access.conf" I successfully used a rule like:
`-:testuser:sshd`
