### ISSUE TITLE
Unable to connect to an agentless instance using tsh after changing its hostname

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#42315]
Expected behavior:
I should be able to access an agentless node using `tsh ssh` after customizing its hostname

Current behavior:
I can access an OpenSSH host only as long as I keep its original hostname

Bug details:
Teleport version: 16.0.0-alpha.3
Recreation steps:

1. Add an OpenSSH node using the official instructions (https://goteleport.com/docs/ver/16.x/server-access/openssh/openssh/)
2. Use `tsh ssh` to confirm it can be accessed.
3. Change the name using `tctl edit`, as suggested by the above document.
4. Use `tsh ssh` again. A following error message appears:

```
ERROR: ssh: unexpected packet in response to channel open: <nil>
```

Logs:

```
Jun 03 17:59:40 ip-172-31-26-77.eu-central-1.compute.internal teleport[221788]: 2024-06-03T17:59:40Z ERRO [NODE:FORW] Unable to create remote connection: ssh: handshake failed: ssh: principal "osnode1" not in the set of valid principals for given certificate: ["bc5c4100-2ceb-46a8-866d-1389d97f81cf.root1.bartosz.teleportdemo.net" "bc5c4100-2ceb-46a8-866d-1389d97f81cf" "ip-172-31-23-201.eu-central-1.compute.internal.root1.bartosz.teleportdemo.net" "ip-172-31-23-201.eu-central-1.compute.internal" "localhost" "127.0.0.1" "::1" "172.31.23.201"] trace.fields:map[dst-addr:172.31.23.201:22 src-addr:89.234.244.87:7706] forward/sshserver.go:636
Jun 03 17:59:40 ip-172-31-26-77.eu-central-1.compute.internal teleport[221788]: 2024-06-03T17:59:40Z ERRO [TRANSPORT] ssh stream terminated unexpectedly: rpc error: code = Canceled desc = context canceled pid:221788.2 transportv1/transport.go:248
```

**Comment by zmb3** [comment]
@bl-nero could this be the same as the Windows issue you reported? Missing public_addr?

**Comment by bl-nero** [comment]
@zmb3 It bears some resemblance, indeed. I'll double check this once I'm done with FIPS (should be later today).

**Comment by bl-nero** [comment]
@zmb3 I investigated, and it looks like this is not related. OpenSSH nodes are configured via resources, and the `public_addr` field is not available (it's reserved in the proto file and `tctl edit` ignores it). There is a `public_addrs` field, but validation rejects it — it's only available for Teleport agent nodes. My resource, however, has the `addr` field set, which looks like it should give the proxy a hint about where it should go to contact the node. I verified the IP address there, and it's correct. I also tried to replace it with a FQDN (ip-172-31-23-201.eu-central-1.compute.internal), but it also didn't work.

Here's the complete resource definition on my side:

```
kind: node
metadata:
  labels:
    env: foo
  name: bc5c4100-2ceb-46a8-866d-1389d97f81cf
  revision: 8c999b9d-8b23-4f3c-9f39-1ac50fbc5386
spec:
  addr: 172.31.23.201:22
  hostname: osnode1
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: ""
sub_kind: openssh
version: v2
```
