### ISSUE TITLE
EC2 auto discovery does not honour the TeleportHostname tag if set

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#42314]
## Expected behavior

When a `TeleportHostname` tag is set on an EC2 instance and the instance is added to Teleport, the displayed nodename/hostname in Teleport should be set to match this tag (as described in https://goteleport.com/docs/management/guides/ec2-tags/)

## Current behavior

When using EC2 auto discovery (https://goteleport.com/docs/auto-discovery/servers/ec2-discovery/) the `TeleportHostname` tag is not obeyed.

Sample payload:
```yaml
kind: node
metadata:
  expires: "2024-06-03T17:53:19.81146884Z"
  id: 1717432494178548311
  labels:
    Name: Zabbix
    TeleportHostname: Zabbix
    account-id: <removed>
    project: dev ops
    region: us-east-2
    teleport: "true"
    teleport.dev/account-id: <removed>
    teleport.dev/instance-id: i-09f597e981232XXXX
  name: <removed>-i-09f597e981232XXXX
  revision: 33512ebc-2e34-453a-8baa-7fe4b83c7364
spec:
  addr: 1.2.3.4:22
  cloud_metadata:
    aws:
      account_id: <removed>
      instance_id: i-09f597e981232XXXX
      integration: aws-teleport
      region: us-east-2
      subnet_id: subnet-0115234b0e5b2XXXX
      vpc_id: vpc-032c5850cbb7dXXXX
  hostname: ip-removed.us-east-2.compute.internal
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: ""
sub_kind: openssh-ec2-ice
version: v2
```

This appears to be related to the logic which reads tags from EC2 instances to register them in the Teleport backend - it doesn't special-case the `TeleportHostname` tag which leads to confusion when people read the docs suggesting it will.

Bug details:
- Teleport version: 15.3.7
