### ISSUE TITLE
tsh issues with nginx using ssl-passthrough

### ISSUE THREAD

**Issue by mlhynfield** [gravitational/teleport#42327]
Expected behavior:

I've deployed the teleport-cluster and teleport-kube-agent helm charts (version 15.4.0) in an RKE2 (Kubernetes) cluster behind the nginx reverse proxy which comes bundled with RKE2, and I've configured SSL passthrough. I had expected this to function as a layer 4 load balancer, since SSL passthrough is not supported for layer 7 load balancing using nginx and what I've read so far suggests that most teleport/tsh functionality works behind a layer 4 LB.

Current behavior:

Logging in via browser works fine, but I've experienced a series of issues when connecting with `tsh`:

```
❯ tsh login --proxy example.domain.com:443
Using platform authenticator, follow the OS prompt
ERROR: connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for *.domain.com, not xxxxxxxxxxxxxxxxxxxxxxxxxxxx.teleport.cluster.local"

❯ export TELEPORT_TLS_ROUTING_CONN_UPGRADE=true 

❯ tsh login --proxy example.domain.com:443         
Using platform authenticator, follow the OS prompt
> Profile URL:        https://domain.example.com:443
  Logged in as:       user
  Cluster:            example.domain.com
  Roles:              access, auditor, editor, kubeadmin
  Kubernetes:         enabled
  Kubernetes users:   cluster-admin
  Kubernetes groups:  system:masters
  Valid until:        2024-06-04 03:40:39 -0400 EDT [valid for 12h0m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy

❯ tsh kube login example.domain.com --set-context-name example
Logged into Kubernetes cluster "example.domain.com".

Your Teleport cluster runs behind a layer 7 load balancer or reverse proxy.

To access the cluster, use "tsh kubectl" which is a fully featured "kubectl"
command that works when the Teleport cluster is behind layer 7 load balancer or
reverse proxy. To run the Kubernetes client, use:
  tsh kubectl version

Or, start a local proxy with "tsh proxy kube" and use the kubeconfig
provided by the local proxy with your native Kubernetes clients:
  tsh proxy kube -p 8443

Learn more at https://goteleport.com/docs/architecture/tls-routing/#working-with-layer-7-load-balancers-or-reverse-proxies-preview

❯ export TELEPORT_TLS_ROUTING_CONN_UPGRADE=false

❯ tsh kube login example.domain.com --set-context-name example
ERROR: Unable to connect to ssh proxy at example.domain.com:443. Confirm connectivity and availability.
	remote error: tls: no application protocol

❯ unset TELEPORT_TLS_ROUTING_CONN_UPGRADE

❯ tsh kube login example.domain.com --set-context-name example
Logged into Kubernetes cluster "example.domain.com". Try 'kubectl version' to test the connection.

❯ kubectl get pods
ERROR: Cannot connect Kubernetes clients to Teleport Proxy directly. Please use `tsh proxy kube` or `tsh kubectl` instead.

Unable to connect to the server: getting credentials: exec: executable /usr/local/bin/tsh failed with exit code 1

❯ tsh kubectl get pods         
No resources found in default namespace.
```

Ideally I'd like to expose the teleport-proxy service via nginx with ssl-passthrough in order to achieve direct `kubectl` access to the cluster; please let me know if this is simply unsupported and if so we can close the issue.

teleport-cluster values.yaml:

```
clusterName: "example.domain.com"
proxyListenerMode: multiplex

auth:
  teleportConfig:
    auth_service:
      authentication:
        webauthn:
          rp_id: domain.com
proxy:
  teleportConfig:
    proxy_service:
      public_addr: example.domain.com:443

operator:
  enabled: false

log:
  level: INFO

authentication:
  type: local
  connectorName: passwordless

publicAddr:
  - example.domain.com
  - app.domain.com
  - etc.

service:
  type: ClusterIP

tls:
  existingSecretName: teleport-tls

ingress:
  enabled: true
  spec:
    ingressClassName: nginx

annotations:
  ingress:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

podSecurityPolicy:
  enabled: false

```

teleport-kube-agent values.yaml:

```
proxyAddr: "https://example.domain.com:443"
roles: "kube,app"

kubeClusterName: example.domain.com

apps:
  - name: app
    uri: http://app-svc.namespace.svc.cluster.local
    public_addr: app.domain.com
  - etc.

joinTokenSecret:
  create: false
  name: teleport-kube-agent-join-token

podMonitor:
  enabled: true

```

Bug details:
- Teleport version 15.4.0
