### ISSUE TITLE
Terraform: BoolOption sets to false when null rather than the default

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#42429]
When set to null, BoolOption values are not treated as null and are instead treated as if they were explicitly set to false. This means that default values are not set.

```hcl
terraform {
  required_providers {
    teleport = {
      source  = "terraform.releases.teleport.dev/gravitational/teleport"
      version = "14.2.1"
    }
  }
}

provider "teleport" {
  addr               = "leaf.tele.ottr.sh:443"
  identity_file_path =  "/Users/noah/code/gravitational/teleport-scratch/bin/admin_identity"
}

resource "teleport_role" "terraform-test" {
  metadata = {
    name        = "terraform-role-test"
    description = "Terraform test role"
    labels = {
      example = "yes"
    }
  }

  spec = {
    options = {
    }

    allow = {
      logins = ["this-user-does-not-exist"]
    }

    deny = {
      logins = ["anonymous"]
    }
  }
}
```

Results in

```yaml
kind: role
metadata:
  description: Terraform test role
  id: 1704368039824145000
  labels:
    example: "yes"
  name: terraform-role-test
  revision: 2c32327a-cd75-4d96-8878-03e94b33fb50
spec:
  allow:
    logins:
    - this-user-does-not-exist
  deny:
    logins:
    - anonymous
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    create_host_user: false
    desktop_clipboard: false
    desktop_directory_sharing: false
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: false
version: v7
```

See that all options are set to `false` - this differs from the behaviour of `tctl create -f` which would default these if unspecified to true.
