### ISSUE TITLE
Terraform: bump hashicorp/terraform-plugin-framework to 1.4.0

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#42445]
There are a lot of breaking changes from v0.10.0 until v1.1.1

https://github.com/hashicorp/terraform-plugin-framework/releases

Not entirely necessary, but we should update the lib here as well
https://github.com/gravitational/protoc-gen-terraform/pull/25

**Comment by hugoShaka** [comment]
Things to look into after the v1 migration in teleport:

#### Custom types
- Custom schema types (`DurationType`, `TimeType`) must now implement a `basetype` `Typable` interface.
See https://developer.hashicorp.com/terraform/plugin/framework/handling-data/types/custom#schema-type
- Custom value types (`DurationValue`, `TimeValue`) must now implement a `basetype` `Valuable` interface.
See https://developer.hashicorp.com/terraform/plugin/framework/handling-data/types/custom#value-type
- Note: Custom Types are incompatible with plan modifiers until `v1.3.1+`.
See https://github.com/hashicorp/terraform-plugin-framework/issues/754

#### YAML file config:
- Custom types must be mapped to a base attribute type. The current solution is to use a new option `attribute_mapping` that maps custom types to the base attribute type. Open to alternative ideas or names.
```yaml
# These suffixes for custom methods called when field has custom_type flag. By default they might be weird.
suffixes:
    "BoolOption": "BoolOption"
    "Labels": "Labels"
    "github.com/gravitational/teleport/api/types/wrappers.Traits": "Traits"
    "github.com/gravitational/teleport/api/types/wrappers.Strings": "Strings"

attribute_mapping:
  "BoolOption": "BoolAttribute"
  "Labels": "MapAttribute"
  "github.com/gravitational/teleport/api/types/wrappers.Traits": "MapAttribute"
  "github.com/gravitational/teleport/api/types/wrappers.Strings": "ListAttribute"
```
- Path to validators and plan modifiers have been migrated to type specific packages.
- Schema attribute name validation has become more strict. Camelcase attribute names are no longer valid.
  `SamlSingleLogoutURL` attribute name must be converted to snake case using `name_overrides` option.
- Unsure yet if we will require separate configuration options for data source schema.

#### Validators
- Validators now implement a type specific interface (`validator.String`, `validator.Object`, ...)
#### Modifiers
- Modifiers now implement a type specific interface (`planmodifier.String`, `planmodifier.Object`, ...)

#### `GenSchema`, `CopyTo`, `CopyFrom`
- Separate schema generation functions will be available for resources and datasources, but the attribute behaviors should remain the same for now.
- Resources should now generate schema using `GenSchema*Resource()`.
- Data sources should now generate schema using `GenSchema*DataSource()`.

#### DurationValue
Now that Terraform `attr.Value` is immutable, we need to ensure that the raw string value (`5m` vs `5m0s`) is preserved. Otherwise the provider will complain with a `provider produced invalid plan` error:
```sh
Error: Provider produced invalid plan

Provider "registry.terraform.io/hashicorp/teleport" planned an invalid value
for teleport_role.test.spec.options.max_session_ttl: planned value
cty.StringVal("2h3m0s") does not match config value cty.StringVal("2h3m") nor
prior value cty.StringVal("30h0m0s").
```

One option considered was to use the [semantic equality](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/types/custom#semantic-equality) for custom types that is available in v1.0.0+. Unfortunately, semantic equality is not applied when validating Terraform config/planned values. It's use case is for comparing new state to prior state and detecting drift.

In this specific case, the role plan modifier passes the `spec.options` through `CopyFrom` and `CopyTo` losing the raw string value of the duration after the round trip.

One idea to address this issue is to use a custom conversion functions `CopyToDuration` to that copies the raw string value of the existing duration.
