### ISSUE TITLE
Teleport refusing to use SSL certificates to login to PostgreSQL Server Backend

### ISSUE THREAD

**Issue by jstewart612** [gravitational/teleport#42468]
Expected behavior:

Following the instructions in https://goteleport.com/docs/reference/backends/#postgresql works for Certificate Authentication to PostgreSQL.

Current behavior:

It does not work.  It ignores that I told it to use certificates and tries to login via password.  It should not be doing so with this configuration.

Bug details:
- Teleport version: 15.4.0
- Recreation steps:

Install teleport-cluster helm chart using the following Helm chart values:

```
        auth:
          teleportConfig:
            teleport:
              storage:
                audit_events_uri:
                  - "postgresql://teleport@teleport-pgsql-rw:5432/teleport_audit?sslcert=/certs/teleport-pgsql-teleport/tls.crt&sslkey=/certs/teleport-pgsql-teleport/tls.key&sslrootcert=/certs/teleport-pgsql-ca/ca.crt&sslmode=verify-full"
                conn_string: "postgresql://teleport@teleport-pgsql-rw:5432/teleport_backend?sslcert=/certs/teleport-pgsql-teleport/tls.crt&sslkey=/certs/teleport-pgsql-teleport/tls.key&sslrootcert=/certs/teleport-pgsql-ca/ca.crt&sslmode=verify-full&pool_max_conns=20"
                type: "postgresql"
        chartMode: "standalone"
        extraVolumeMounts:
          - mountPath: /certs/teleport-pgsql-teleport
            name: teleport-pgsql-teleport
          - mountPath: /certs/teleport-pgsql-ca
            name: teleport-pgsql-ca
        extraVolumes:
          - name: teleport-pgsql-teleport
            secret:
              secretName: teleport-pgsql-teleport
          - name: teleport-pgsql-ca
            secret:
              secretName: teleport-pgsql-ca
```
- Debug logs

```
{"caller":"pgbk/pgbk.go:194","component":"pgbk","level":"info","message":"Setting up backend.","timestamp":"2024-06-05T01:26:44Z"}
{"caller":"common/utils.go:69","component":"pgbk","error":"failed to connect to `host=teleport-pgsql-rw user=teleport database=postgres`: failed SASL auth (FATAL: password authentication failed for user \"teleport\" (SQLSTATE 28P01))","level":"warning","message":"Failed to connect to the \"postgres\" database.","timestamp":"2024-06-05T01:26:44Z"}
{"caller":"common/utils.go:262","component":"pgbk","error":"failed to connect to `host=teleport-pgsql-rw user=teleport database=teleport_backend`: failed SASL auth (FATAL: password authentication failed for user \"teleport\" (SQLSTATE 28P01))","level":"debug","message":"Failed to confirm the existence of the \"backend_version\" table.","timestamp":"2024-06-05T01:26:44Z"}
ERROR REPORT:
Original Error: *pgconn.ConnectError failed to connect to `host=teleport-pgsql-rw user=teleport database=teleport_backend`: failed SASL auth (FATAL: password authentication failed for user &#34;teleport&#34; (SQLSTATE 28P01))
Stack Trace:
github.com/gravitational/teleport/lib/backend/pgbk/common/utils.go:219 github.com/gravitational/teleport/lib/backend/pgbk/common.RetryTx.func1
github.com/gravitational/teleport/lib/backend/pgbk/common/utils.go:120 github.com/gravitational/teleport/lib/backend/pgbk/common.retry[...]
github.com/gravitational/teleport/lib/backend/pgbk/common/utils.go:218 github.com/gravitational/teleport/lib/backend/pgbk/common.RetryTx
github.com/gravitational/teleport/lib/backend/pgbk/common/utils.go:266 github.com/gravitational/teleport/lib/backend/pgbk/common.SetupAndMigrate
github.com/gravitational/teleport/lib/backend/pgbk/pgbk.go:203 github.com/gravitational/teleport/lib/backend/pgbk.NewWithConfig
github.com/gravitational/teleport/lib/backend/pgbk/pgbk.go:152 github.com/gravitational/teleport/lib/backend/pgbk.NewFromParams
github.com/gravitational/teleport/lib/backend/pgbk/pgbk.go:44 github.com/gravitational/teleport/lib/backend/pgbk.init.0.func1
github.com/gravitational/teleport/lib/backend/backend.go:125 github.com/gravitational/teleport/lib/backend.New
github.com/gravitational/teleport/lib/service/service.go:5846 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthStorage
github.com/gravitational/teleport/lib/service/service.go:1750 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
github.com/gravitational/teleport/lib/service/service.go:1211 github.com/gravitational/teleport/lib/service.NewTeleport
github.com/gravitational/teleport/lib/service/service.go:739 github.com/gravitational/teleport/lib/service.newTeleportProcess
github.com/gravitational/teleport/lib/service/service.go:755 github.com/gravitational/teleport/lib/service.Run
github.com/gravitational/teleport/tool/teleport/common/teleport.go:681 github.com/gravitational/teleport/tool/teleport/common.OnStart
github.com/gravitational/teleport/tool/teleport/common/teleport.go:572 github.com/gravitational/teleport/tool/teleport/common.Run
github.com/gravitational/teleport/tool/teleport/main.go:33 main.main
runtime/proc.go:267 runtime.main
runtime/asm_amd64.s:1650 runtime.goexit
User Message: initialization failed
failed to connect to `host=teleport-pgsql-rw user=teleport database=teleport_backend`: failed SASL auth (FATAL: password authentication failed for user &#34;teleport&#34; (SQLSTATE 28P01))
```
