### ISSUE TITLE
Invalid login given on external ADFS trait windowaccountname

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4259]
### Description
**What happened**:

The login `{{external.http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname}}` is giving the error `User Message: invalid login found:` when in a role.  The trait is available in the typical ADFS SSO configuration.

**What you expected to happen**:

The login can be set in a role and the trait will populate into the login.

**How to reproduce it (as minimally and precisely as possible)**:

Install a enterprise 4.3.5 teleport.  Populate a role file and attempt to add

`tctl create devrole.yaml`

```yaml
kind: role
version: v3
metadata:
  name: dev
spec:
  options:
    # regular users can only be guests and their certificates will have a TTL of 1 hour:
    max_session_ttl: "1h"
  allow:
    # only allow login as either ubuntu or the 'windowsaccountname' claim
    logins:
    - '{{external.http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname}}'
    - ubuntu
    node_labels:
      "access": "relaxed"
```

### Environment
* Teleport version (use `teleport version`): 4.3.5
* Tsh version (use `tsh version`): 4.3.5
* OS (e.g. from `/etc/os-release`): Ubuntu 18.04
* Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Relevant Debug Logs If Applicable**

* `tsh --debug`

```bash
# tctl -d create -f testuserrole.yaml 
DEBU             DEBUG logging enabled logrus/exported.go:117
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:173
DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:218
DEBU             Connecting to auth servers: [{127.0.0.1:3025 tcp }]. common/tctl.go:167

ERROR REPORT:
Original Error: *trace.BadParameterError invalid login found: {{external.http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname}}
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/services/role.go:695 github.com/gravitational/teleport/lib/services.(*RoleV3).CheckAndSetDefaults
        /go/src/github.com/gravitational/teleport/lib/services/role.go:2466 github.com/gravitational/teleport/lib/services.UnmarshalRole
        /go/src/github.com/gravitational/teleport/lib/services/role.go:2509 github.com/gravitational/teleport/lib/services.(*TeleportRoleMarshaler).UnmarshalRole
        /go/src/github.com/gravitational/teleport/e/tool/tctl/resource_command.go:61 main.(*ResourceCommandE).createRole
        /go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:231 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create
        /go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:117 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
        /go/src/github.com/gravitational/teleport/e/tool/tctl/resource_command.go:55 main.(*ResourceCommandE).TryRun
        /go/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:137 github.com/gravitational/teleport/tool/tctl/common.Run
        /go/src/github.com/gravitational/teleport/e/tool/tctl/main.go:28 main.main
        /opt/go/src/runtime/proc.go:212 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message: invalid login found: {{external.http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname}}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190799031159936) by [Unito](https://www.unito.io/learn-more)
