### ISSUE TITLE
Proposal: Add proxy address suffix to kubeconfig context names

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#4266]
### Feature Request
When logging into a Teleport cluster, currently the kubeconfig context name matches the cluster name, for example:

```yaml
clusters:
- cluster:
    server: https://main.gravitational.co:3026
  name: main
- cluster:
    server: https://k74656e736f722e646576.main.gravitational.co:3026
  name: leaf
contexts:
- context:
    cluster: main
    user: admin
  name: main
- context:
    cluster: leaf
    user: admin
  name: leaf
current-context: leaf
```

In the scenario where there's another “leaf” cluster with the same name behind a different “main” cluster, logging into those leafs will override one another’s contexts. This means a user would alway need to do `tsh login` first and can’t just use `kubectl` to switch between contexts.

The proposal is to include a suffix with the proxy address in the context name to be able to distinguish non-unique cluster names located behind different proxies, for instance the above example would change to:

```yaml
contexts:
- context:
    cluster: leaf
    user: admin
  name: leaf.main.gravitational.co
current-context: leaf.main.gravitational.co
```

That would allow the users to use kubectl to switch between the contexts if they have multiple clusters named "leaf" behind different proxies.

### Motivation
This is relevant for scenarios where a user can have multiple identical environments (dev/stage/prod) and a number of leaf clusters in each of them with the same names.

Most often we see this among Gravity users where they have different Hubs ("main" clusters in Teleport terminology) as entry-points to different environments and a number of "leaf" clusters with the same names (to avoid redundancy) behind each Hub.

### Who's it for?
OSS User, Pro, Enterprise
