### ISSUE TITLE
SCP Downloads Fail in Moderated Sessions for Leaf Clusters

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#42911]
# Summary
SCP  downloads fail in moderated sessions when the target is in a leaf cluster and the root cluster roles do not enforce moderation.

# Steps to Reproduce
1. Set up a multi-cluster environment with one root cluster and one or more leaf clusters.
2. Create a user with the following root role:
    ```yaml
    kind: role
    metadata:
      name: prod-access-stripped
    version: v7
    spec:
      allow:
        logins:
        - ubuntu
    ```
3. Map the `prod-access-stripped` role to `prod-access` in the leaf cluster:
    ```yaml
    kind: role
    metadata:
      name: prod-access
    version: v7
    spec:
      allow:
        require_session_join:
          - name: Auditor oversight
            filter: 'contains(user.spec.roles, "auditor")'
            kinds: ['k8s', 'ssh']
            modes: ['moderator']
            count: 1
        logins:
        - ubuntu
        - debian
        node_labels:
          '*': '*'
    ```
4. Create a moderated session to a leaf cluster node, requiring a moderator to join.
5. Once the moderator joins, attempt to create a file download.

# Expected Behavior
SCP downloads within moderated sessions to a leaf cluster should work even if only the leaf cluster enforces moderation.

# Current Behavior
When the root cluster roles do not enforce moderation and the leaf cluster roles do, SCP downloads fail with the error message `lacking privileges to start unattended session`.

# Detailed Explanation
During the process of creating a moderated session to a leaf cluster node, the moderator joins successfully. However, when attempting to download a file, instead of triggering the approval/deny flow in the moderator session, it automatically tries to download the file and fails. This is because when the session is created, the `moderated` flag is incorrectly set to `false`.

Example session creation log:
```json
{
  "session": {
    "kind": "ssh",
    "id": "ed7da973-fa0c-4515-9975-1319d9eabd80",
    "namespace": "default",
    "parties": null,
    "terminal_params": {
      "w": 0,
      "h": 0
    },
    "login": "ubuntu",
    "created": "2024-06-13T10:06:07.486604626Z",
    "last_active": "2024-06-13T10:06:07.486606046Z",
    "server_id": "b5bf6720-90e7-4446-8b87-9c58c7213ce7",
    "server_hostname": "host",
    "server_hostport": 0,
    "server_addr": "",
    "cluster_name": "leaf",
    "kubernetes_cluster_name": "",
    "desktop_name": "",
    "database_name": "",
    "app_name": "",
    "owner": "tiago2",
    "moderated": false, <- this is set to false
    "command": ""
  }
}
```

This occurs because the moderation evaluation, allowed logins, and other session properties are based on the root cluster roles instead of the leaf cluster roles when the request reaches the root cluster proxy. This causes major issues for moderated sessions, making it impossible to download files under these conditions.

# Impact
This bug prevents users from performing SCP downloads in moderated sessions from leaf clusters, disrupting workflows that depend on secure file transfers.

# Workaround
Temporarily adjust the root cluster roles to enforce moderation, although this may not be desirable or feasible in all setups.

# Proposed Solution
If the target is a leaf node, the system should use leaf roles, leaf logins, and leaf moderation policies instead of relying on the root cluster details.
