### ISSUE TITLE
Scoped Approvals for Access Workflows

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4309]
### Feature Request

EDIT (@klizhentas ): this description has the latest spec

Customer would like define *who* may approve role requests for a specified role. 

Imagine if you had 4 teams/roles configured: `dev`, `qa`, `dba`, `admin`. 

A request from role `dev` to `dba` is initiated. Currently, anyone with approval permissions could approve the request. However, this feature request is to limit *who* can approve the requests for access to the `dba` role. Users in the `dba` role should be the approving entity for request into the `dba` role. The `qa` team should not have the authority to approve this request. 

Add `where` clause to allow devs to approve roles from their peers, but except themselves

```yaml
kind: role
metadata:
  name: dev
spec:
  allow:
    request:
      roles: ['dba']
      where: contains(request.annotations, user.traits[team])
  deny:
    approve:
      roles: ['*']
     where: equals(request.user, user.metadata.name)
```

In this sample, the dev role lets developers to grant access to access requests containing annotations matching their team.

### Motivation
Roles are typically built around software or ops teams. These teams should have the ability to grant access to their own infrastructure. This would push the approval process down to the team, and reduce the operational burden of a single team managing approval requests. 

### Who's it for?
Enterprise

@klizhentas @fspmarshall @travelton updated the description with more detailed spec

**Comment by fspmarshall** [comment]
I like the sound of this!

#### Minor Correction:

> the `dba` role permits users of role `dev` to request access

Other way around actually.  Roles always specify the capabilities of the users that hold them, so the above example actually gives `dba` the ability to request `dev`.  If you want `dev` to be able to request the `dba` role, you would specify this as part of the `dev` role like so:

```yaml
kind: role
metadata:
  name: dev
spec:
  allow:
    request:
      roles: ['dba']
    # ...
```

You can basically read the above as: "users with role `dev` are allowed to request role `dba`"

#### Thoughts:

Any new syntax for scoped approvals should probably stick to the "roles define the capabilities of their holders" rule if possible.  In the case of the example scenario where access to `dba` can be approved either by members of `dba` or members of `admin`, we'd probably want to end up with something like this:

```yaml
kind: role
metadata:
  name: dba
spec:
  allow:
    approve:
      roles: ['dba']
    # ...
---
kind: role
metadata:
  name: admin
spec:
  allow:
    approve:
      roles: ['dba']
    # ...
```

And if we wanted to prevent `dev`s from turning around and granting `dba` once they themselves were granted it:

```yaml
kind: role
metadata:
  name: dev
spec:
  allow:
    request:
      roles: ['dba']
  deny:
    approve:
      roles: ['dba']
    # ...
```
