### ISSUE TITLE
FedRAMP / FIPS Version should support local robot users. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4323]
### Feature Request
We currently don't allow local users when running Teleport in FedRAMP / FIPS mode. This was by design, as Teleport couldn't enforce all login requirements. There is a use case for Teams being able to create robot users to obtain credentials for automation systems as requested by https://github.com/gravitational/teleport/issues/4099 

https://gravitational.com/teleport/docs/enterprise/ssh_kubernetes_fedramp/

This user shouldn't be able to login to Teleport, and should only be able to 

`tctl auth sign --user=jenkins --auth=local-bot --ttl=24h`

Open Question: How do we want to deal with traits for these bots? 

File Config?
```
  # To Support FIPS local_auth needs to be turned off and a SSO connector is
  # required to log into Teleport.
  authentication:
    # local_auth needs to be set to false in FIPS mode.
    # local_auth: false
    # local_auth: robots  
   type: saml
```
### Adding local users
```
tctl users add jenkins root,ec-2user --k8s-users=jenkins
```

### Motivation
Companies that want to enforce FIPS and integrate with CI/CD systems. 

### Who's it for?
Enterprise

**Comment by benarent** [comment]
Note: This is currently possible with local auth off. 


Create a user using tctl then and export the credentials. This creates a service account that’s unable to log into Teleport

Save this as user.yaml
```yaml
kind: user
version: v2
metadata:
  name: functional-id
spec:
  expires: "0001-01-01T00:00:00Z"
  roles:
  - iks_user
  - teleport_admin
  traits:
    Kubernetes_groups:
    - “My Access Group”
    Kubernetes_users: 
    - IAM#functional-id@co.blah.com
    logins:
    - functional-id@co.blah.com
```

### Export User
```
tctl create -f user.yaml 
```
### Export Auth: 
```
tctl auth sign --ttl=2160h --user=functional-id --out=jenkins.pem
```
###  Export Kubernetes Config:
```
tctl auth sign --ttl=2160h --user=functional-id --out=kubeconfig --format=kubernetes
```
