### ISSUE TITLE
desktop discovery: support multiple search paths

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#43354]
Teleport's LDAP-based discovery for Windows desktops is configured via two parameters:

- `base_dn`: specifies _where_ to search
- `filters`: specifies _what_ to search for

Because `base_dn` is a single value, searching across multiple separate OUs is difficult. Sometimes you can find a common root and set `base_dn` to something that contains both OUs, and then use filters to select only the OUs you care about, but that gets difficult quickly and most people resort to running multiple `windows_destop_service`s so that they can configure each to search a separate DN.

Proposal: deprecate `base_dn` in favor of `search_paths`, which will be an array.

```
windows_desktop_service:
  enabled: yes
  ldap:
    discovery:
      search_paths:
      - CN=foo,DC=example,DC=com
      - CN=bar,DC=example,DC=com
```

If `base_dn` and `search_paths` are both specified, then we just append `base_dn` to the set of search paths and search all of them.
