### ISSUE TITLE
Machine ID: ArgoCD Integration

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#43403]
Integrate more tightly with ArgoCD to provide a better Kubernetes Access story with Machine ID. We'll need to look into how `tbot` could be injected into the ArgoCD image to act as an on-the-fly execProviderPlugin.

Resources:
- https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters
- Bear in mind that Argo doesn't seem to handle nicely reloading credentials from a secret.
- Bear in mind support for negotiating ALPN and L7 LB.

**Comment by pradithya** [comment]
@strideynet I am working on integrating my ArgoCD setup with Teleport. Any pointer if there is any documentation / work on going to have this feature?

**Comment by carlosjgp** [comment]
Hey, @strideynet looks like #40405 is now closed.

Is there any progress on this front, or plan to work on it soon?

I'm very keen to see this feature released!

**Comment by strideynet** [comment]
Hey @carlosjgp - definitely on our short/mid term roadmap. I can't make any promises as to exactly when it'll get scheduled, but, now that it's unblocked, it's towards the top of the team's list.

**Comment by timothyb89** [comment]
Related discussion: https://github.com/gravitational/teleport/discussions/41459. 

The new `kubernetes/v2` service would probably at least remove `tsh` from the mix from this workaround. I wonder if it's worth probing at Argo's secret reloading a bit more, since a reconciler implementation could be much simpler, even just a new destination type.

**Comment by boxofrad** [comment]
Hey folks! 👋🏻 

Having done some early exploration into this today, I'm thinking the lowest-friction option might be to make the `kubernetes/v2` service "Argo-aware" and have it manage clusters [via Kubernetes secrets](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters). If we inline the certificate and private key, we'd avoid the need to add `tbot` to your Argo container image so that you can call it as an exec plugin.

Here's how the `tbot` configuration could look:

```yaml
services:
  - type: kubernetes/v2
    selectors:
      - name: cluster-1
      - name: cluster-2
      - labels:
          env: prod
    destination:
      type: argocd_cluster
      secret_name_prefix: argocd-cluster-
      project: foo
      namespaces: [bar, baz]
      cluster_resources: true
```

Note the new `argocd_cluster` destination. This is based on our `kubernetes_secret` destination, but different in that it operates on multiple secrets, and writes them in the format Argo expects. The secret names would be derived from the Kubernetes cluster names but you could specify a prefix.

For simplicity, it's probably best to make the `project`, `namespaces`, and `cluster_resources` options apply to all clusters. If you want to override them for a specific cluster, you'd simply add another service with a selector targeting just that cluster.

What do you think?
