### ISSUE TITLE
Provide a waiting room post login to enable an external API to create or check a users roles. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4384]
### Feature Request
Provide a waiting room post login in the UI and CLI to enable an external API to create or check a users roles. This API could integrate with internal or external ticketing systems, it'll look up a users traits and the API will return back a custom role for that session. 

As part of  Extended approval workflows RFD #4305, roles will have a new `request_access` option. This will provide the 3 modes listed below, this option will kick in after Teleport Login has been complete. 

```yaml
kind: role
metadata:
  name: contractor
spec:
  options:
     # 'none' - default value if not set
     # 'auto' - blocks the login screen and creates an access request
     # 'note' - requests for a note to be filled in and creates access request
     request_access: 'note'
```

If the external service is unavailable, a user should be able to add note which can be reviewed by an admin using `tctl` .

### Motivation
This feature lets companies check external systems, or enable developers to request access on login.

### UI Updates

This feature should be included in Teleport 4.4. For this example, the background isn't required. For 4.4 backports, existing style can be used. 

**request_access: 'note'**
![Authorization Screen - Request Access](https://user-images.githubusercontent.com/559288/95785636-f9bf0e00-0c8a-11eb-8bb0-50f39eaf1656.png)
![Authorization Screen - Please Wait](https://user-images.githubusercontent.com/559288/95785551-d4320480-0c8a-11eb-955e-863a14d26708.png)

**request_access: 'auto'**
![Authorization Screen - Please Wait](https://user-images.githubusercontent.com/559288/95785551-d4320480-0c8a-11eb-955e-863a14d26708.png)

### Who's it for?
Enterprise
