### ISSUE TITLE
Postgres on Cloud SQL doesn't require using Public IP, Private IP work too

### ISSUE THREAD

**Issue by gdubicki** [gravitational/teleport#44090]
## Applies To

https://goteleport.com/docs/database-access/enroll-google-cloud-databases/postgres-cloudsql/

## Details

This doc says:
> public-ip - The Cloud SQL instance public IP address. The address can be found on the "Connect to this instance" panel on the "Overview" page in the Cloud SQL instance's dashboard.
...but in reality you can omit this field, set `instance-url` instead, pointing to the Private IP and it works.

The downside is that the TLS doesn't work then, but if you are using a Private IP then maybe you are ok with that.

An example of a configuration for the [teleport-kube-agent](https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/) chart that works looks like this:
```
databases:
  - name: foobar
    uri: 192.168.0.1:5432 # private IP
    gcp:
      project_id: foo
      instance_id: foobar
    protocol: postgres
    tls:
      mode: insecure # sadly, even the 'verify-ca' value doesn't work here in this case
```

I am guessing that you can configure the same with `teleport db configure create`.

## How will we know this is resolved?

When you update the docs/accept a PR that updates it
