### ISSUE TITLE
Provide an easy onramp for SSO users to add a MFA device when first joining a cluster. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#44154]
What would you like Teleport to do?

I would like Teleport to provide smooth onboarding for SSO users to add a MFA token when first joining a cluster. When a user first logs in with SSO and the cluster has `require_session_mfa: yes` we should provide an easy onramp to add a MFA device.  Self-Device Trust enrollment is a little tricky but at minimum we could provide instructions for the user to send their asset tag to the Teleport admin so they can start the enrollment ceremony. 

```
  authentication:
    type: github
    second_factor: webauthn
    webauthn:
      rp_id: "teleport.example.com"
    require_session_mfa: yes
    device_trust:
      mode: "required"
```

What problem does this solve?

Easier onramp for teams looking down users, and following out best practices for our Defending against Identity Provider (IdP) Compromise  https://goteleport.com/resources/white-papers/defend-against-idp-compromise/ 

Internal bug reported by @webvictim. 

> how do you enroll an MFA device when you don't have one already? i'm trying to sign myself into this cluster (for an access monitoring demo) and can't register a trusted device or MFA device due to lack of an existing MFA device

If a workaround exists, please include it.
