### ISSUE TITLE
Show commands available to an `observer` within a moderated session

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#44371]
Moderated Sessions supports `join_sessions` functionality which allows a user to join a session and view what is happening without the ability to terminate the session. Within the role, it's the `auditor` mode [as outlined in the documentation](https://goteleport.com/docs/access-controls/guides/moderated-sessions/#configure-an-allow-policy).

```yaml
kind: role
metadata:
  name: auditor
version: v7
spec:
  allow:
    join_sessions:
      - name: Join prod sessions
        roles : ['prod-access']
        kinds: ['k8s', 'ssh']
        modes: ['moderator', 'observer']
```

Customer has requested that Teleport show the command that are available to the observer when they join a session similar to what Teleport does for a `require_session_join` session. Something like below.

```
Teleport > Creating session with ID: 00000000-0000-0000-0000-000000000000...
Teleport > Controls
  - CTRL-C: Leave the session
Teleport > User foo joined the session with participant mode: observer.
Teleport > Connecting to server01 over ssh
$
```
