### ISSUE TITLE
Unexpected behavior with role mapping using Trusted Cluster using AWS role ARNS

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#44410]
Expected behavior:
The local role aws_role_arns should map properly when connecting to leaf cluster. 

Current behavior:
The user is not able to select the appropriate aws_role_arn. 

Bug details:
- Teleport version : Teleport Cluster 15.4.7
- Recreation steps

1. Assuming a functional trusted cluster configuration
2. Assign remote role `team-a-aws-write-access` to root cluster test user. 
3. Login to Teleport UI as root cluster test user
4.  In the resources window, toggle to the root cluster
5.  Select Launch on the awsconsole access application. 
6. Observe that the IAM role is the root cluster aws_role_arn and not the leaf cluster aws_role_arn 

Trusted Cluster 
```
kind: trusted_cluster
metadata:
   name: xyz-teleport-cluster
spec:
  enabled: true
  role_map:
  - local:
    - team-a-aws-write-access
    remote: 'team-a-aws-write-access'
  token:  secret-token-from-root-cluster
  tunnel_addr: root-proxy.example.com:3024
  web_proxy_addr: root-proxy.example.com:443
version: v2 
```

Remote Role (Root Cluster) 
```
kind: role
metadata:
  name: team-a-aws-write-access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - arn:aws:iam::111111111111:role/TeamAAWSWrite
  deny: {}
version: v7
```

Local Role (Leaf Cluster) 
```
kind: role
metadata:
  name: team-a-aws-write-access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - arn:aws:iam::111111222222:role/TeamAAWSWrite
  deny: {}
version: v7
```

- Debug logs
