### ISSUE TITLE
AWS App Access not working (using integration)

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#44553]
After enabling the AWS App Access for an integration, we are not able to log into it.

The app_server that exists looks like this
```yaml
kind: app_server
metadata:
  name: teleportdev
spec:
  app:
#...
    spec:
      integration: teleportdev
      public_addr: teleportdev.dinis.cloud.gravitational.io:443
      uri: https://console.aws.amazon.com
#...
version: v3
```

When I click to open the AWS Console, I can see that at first the url looks like this
```
https://dinis.cloud.gravitational.io/web/launch/teleportdev.dinis.cloud.gravitational.io:443/dinis.cloud.gravitational.io/teleportdev.dinis.cloud.gravitational.io:443/arn:aws:iam::123456789012:role%2FMarcoTestReadOnlyAccess
```

But then, it loses the port in the URL right after `/launch/` when generating the 2nd URL (the one that has the state)
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/2ffa32d6-8177-4b38-a316-3109b9cccc88">

This happens in `master` but I suspect it will be the same in release branches.

Possibly related to https://github.com/gravitational/teleport/pull/43525

Confirmed that removing the check added in the PR above solves the problem.
