### ISSUE TITLE
Re-init the cache on error: "{{ external.email }}" is not a valid matcher expression

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4493]
### Description

**What happened**:

User has built with master and received 
```log
WARN [NODE:1:CA] Re-init the cache on error: "{{ external.email }}" is not a valid matcher expression - no variables and transformations are allowed. cache/cache.go:333
```
```yaml
kind: role
metadata:
  name: security-user
spec:
  allow:
    logins:
    - '{{email.local(external.email)}}'
```

**What you expected to happen**:

Need to check if `{{email.local(external.email)}}` is working on 4.4-rc1
