### ISSUE TITLE
AWS roles not visible in the UI after assuming a Teleport role

### ISSUE THREAD

**Issue by joaoubaldo** [gravitational/teleport#45050]
Expected behavior:
I expect that, after assuming a Teleport role using access request, the AWS roles that I now have access to are displayed in the web UI's roles dropdown, similarly to the CLI experience.

Current behavior:
After assuming a Teleport role using access request, the AWS roles that I now have access to are not displayed in the UI's roles dropdown but these are visible from the CLI.  
After looking at the code, [this is the PR](https://github.com/gravitational/teleport/pull/41585) that introduced this behavior as part of [15.3.6](https://github.com/gravitational/teleport/releases/tag/v15.3.6). Confirmed that a previous v15 version doesn't have this issue.

![image](https://github.com/user-attachments/assets/1f6a7632-0c74-4cfd-a4f7-3fd4c73f7552)

The `/v1/webapi/sites/CLUSTER/resources` web request does not return the awsRoles property in versions >= v15.3.6.
![image](https://github.com/user-attachments/assets/4922f37c-6b91-4709-8387-baa85ced6063)

However, running `tsh apps login aws` returns the expected roles.

Bug details:
- Teleport version - 16.1.0
- Recreation steps
1. Log in to the root cluster
2. Make an access request to the AWS app for a specific Teleport role
3. Assume the Teleport role from the access requests web view
4. On the resources web view, select `Launch` to pick a AWS role assigned to the requested Teleport role
5. Dropdown is empty

- Debug logs - see above

**Comment by marcoandredinis** [comment]
Thank you for reporting this issue.

I was not able to reproduce it. When I click on `Assume Role`, I can see the expected AWS Roles in the AWS App dropdown. I tried clicking using the review screen or using directly from the notification bubble, and both worked.

Can you please provide more information about your scenario? The reviewer role, the assumed role and the role that allows requesting access. Can you please also let me know if logging out before assuming the role makes any difference?

**Comment by joaoubaldo** [comment]
@marcoandredinis, I've reran the recreation steps again to ensure I wasn't missing something. The issue is still there:

> Can you please also let me know if logging out before assuming the role makes any difference?

That didn't make any difference.

> reviewer role
```
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  annotations:
    description: Role for review access requests for sysdev
    teleport.dev/keep: "true"
  name: sysdev-access-request-reviewer
  namespace: teleport
spec:
  allow:
    review_requests:
      preview_as_roles:
      - eu-prod-sysdev-aws-write-access
      roles:
      - cicd-sysdev-aws-write-access
  deny: {}
```

> assumed role
```
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  annotations:
    description: Role for sysdev write access to AWS
    teleport.dev/keep: "true"
  name: sysdev-aws-write-access
  namespace: teleport
spec:
  allow:
    app_labels:
      name: aws
    aws_role_arns:
    - arn:aws:iam::111111111111:role/SysDevAWSWrite
  deny: {}
```

> role that allows requesting access
```
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  annotations:
    description: role for requesting write access to AWS for sysdev
    teleport.dev/keep: "true"
  namespace: teleport
spec:
  allow:
    request:
      annotations:
        teleport.dev/schedules:
        - SysDev - Primary
        - SysDev - Secondary
        teleport.dev/teams:
        - Froot Loops - SysDev
      max_duration: 2h
      search_as_roles:
      - cicd-sysdev-aws-write-access
      - eu-dev-sysdev-aws-write-access
      - eu-prod-sysdev-aws-write-access
      - eu-staging-sysdev-aws-write-access
      - wezatele-sysdev-aws-write-access
  deny: {}
```

Note: the assumed role is mapped on the leaf cluster as such:
```
     - remote: eu-prod-sysdev-aws-write-access
      local: [sysdev-aws-write-access]
```
