### ISSUE TITLE
tbot: Support configuring `kubernetes_secret` destination for `kubernetes` type

### ISSUE THREAD

**Issue by tuladhar** [gravitational/teleport#45078]
# What would you like Teleport to do?

In `tbot` [kubernetes configuration](https://goteleport.com/docs/enroll-resources/machine-id/reference/configuration/#kubernetes), if output type is `kubernetes` then would like to use `kubernetes_secret` as destination type. Currently, it only supports `directory` destination type.

```
WARN [TBOT:OUTP] Failed to render output kubernetes (kubernetes_secret: my-cluster-secret) error:[
ERROR REPORT:
Original Error: *trace.BadParameterError Destination kubernetes_secret: my-cluster-secret must be a directory
Stack Trace:
    github.com/gravitational/teleport/lib/tbot/config/template_kubernetes.go:145 github.com/gravitational/teleport/lib/tbot/config.(*templateKubernetes).render
    github.com/gravitational/teleport/lib/tbot/config/output_kubernetes.go:74 github.com/gravitational/teleport/lib/tbot/config.(*KubernetesOutput).Render
    github.com/gravitational/teleport/lib/tbot/service_outputs.go:148 github.com/gravitational/teleport/lib/tbot.(*outputsService).renewOutputs
    github.com/gravitational/teleport/lib/tbot/service_outputs.go:185 github.com/gravitational/teleport/lib/tbot.(*outputsService).Run
    github.com/gravitational/teleport/lib/tbot/tbot.go:283 github.com/gravitational/teleport/lib/tbot.(*Bot).Run.func5
    golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 golang.org/x/sync/errgroup.(*Group).Go.func1
    runtime/asm_amd64.s:1650 runtime.goexit
User Message: rendering template kubernetes
    Destination kubernetes_secret: my-cluster-secret must be a directory] tbot/service_outputs.go:149
```

Here's the tbot config:
```
version: v2
onboarding:
  join_method: kubernetes
  # ensure token is set to the name of the join token you created earlier
  token: bot-golem
certificate_ttl: 24h
storage:
  # a memory destination is used for the bots own state since the kubernetes
  # join method does not require persistence.
  type: memory
# ensure this is configured to the address of your Teleport Proxy or
# Auth Server. Prefer the address of the Teleport Proxy.
proxy_server: teleport.giantswarm.io:443
# outputs will be filled in during the completion of an access guide.
outputs:
- destination:
    name: my-cluster-secret
    type: kubernetes_secret
  disable_exec_plugin: true
  kubernetes_cluster: my-cluster
  type: kubernetes
```

# What problem does this solve?
It helps with automation where by getting kubeconfig as a secret for teleport-registered Kubernetes cluster similar to how Cluster API does where it creates kubeconfig for cluster it creates.

# If a workaround exists, please include it.

No workaround found yet, but asked in `#teleport` slack:
- https://goteleport.slack.com/archives/CEZH6UL64/p1722875044961649
