### ISSUE TITLE
Disallow the configuration of Bot tokens using the Static Token config 

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#45208]
Today, you can create a "Bot" role token using the static tokens config. This token will not work because it does not specify a specific bot. Static tokens also do not work with other elements of the bot join process.

E.G
```
auth_service:
  enabled: yes
  tokens:
    - "bot:mybottoken"
```

We should throw an explicit error rather than silently allowing this misconfiguration.
