### ISSUE TITLE
Run firestore tests with emulator

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4540]
### Feature Request

It is possible to run firestore emulator in K8s. Here is a docker compose example:

https://github.com/melchoir55/firebase-emulator-docker

I have tweaked it a bit

```yaml
version: "3.0"
services:
  firebase:
    build: .
    image: firebase-emulator:firebase-emulator
    volumes:
      - .:/src
    ports:
      - 8618:8618
    command: firebase emulators:start --only firestore
```

and firestore.json:

```json
{
  "database": {
    "rules": "database.rules.json"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "firestore": {
      "host": "0.0.0.0",
      "port": 8618
    }
  }
}

```

Our firestore tests will run with emulator.

### Motivation
Describe why we should work on this feature request.

### Who's it for?
OSS User, Pro, Enterprise
