### ISSUE TITLE
Multiple roles with different `kubernetes_resources` result in unexpected behavior

### ISSUE THREAD

**Issue by Caomoji** [gravitational/teleport#45475]
Expected behavior:

When a user has multiple roles, we expect that Kubernetes groups granted by one role are only added to the impersonation headers if the `kubernetes_resources` criteria are met for that role and that request. This is what we understand from the documentation [here](https://goteleport.com/docs/enroll-resources/kubernetes-access/controls/#multiple-roles).

Current behavior:

When a user with multiple roles makes a request, if one role verifies its `kubernetes_resources` constraints, Kubernetes groups from all owned roles are added to the impersonation headers, even the ones from roles which do not allow the request because they are more restrictive on namespace for instance.

Recreation steps:

Consider these 2 roles:
- One role specific to a namespace.
```
version: v7
kind: role
metadata:
  name: team-a-service-a
spec:
  allow:
    kubernetes_groups:
    - team-a
    kubernetes_labels:
      env: dev
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: 'service-a'
      verbs:
      - '*'
```
 - One global role.
```
version: v7
kind: role
metadata:
  name: default
spec:
  allow:
    kubernetes_groups:
    - baseline
    kubernetes_labels:
      env: dev
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: '*'
      verbs:
      - '*'
```

And that the Kubernetes RBAC would give the following permissions:

`team-a` as a RoleBinding inside the namespaces `service-a` & `service-a-bis`.
```
rules:
  - apiGroups:
      - ""
    resources:
      - "pod"
    verbs:
      - "list"
      - "get"
```

`baseline` as ClusterRoleBinding, allowing to list all namespaces accross the cluster.
```
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "list"
      - "get"
```

A user with these roles would be able to list pods in the namespace `service-a-bis`, which we don't want. We can observe in the audit logs that in fact, the user has the groups `baseline` & `team-a` while running the request. We would expect only the group `baseline` as it's the one granted by the role `default` which allows requests on any namespace, and therefore on the namespace `service-a-bis` (while the role `team-a-service-a` is restrictive to the namespace `service-a`). 
If we were to remove the role `default`, then they would not longer be able to list pods inside `service-a-bis` although it's not the Kubernetes group `baseline` which gives that permission but `team-a`.

Bug details:
- Teleport version: 16.1.6
