### ISSUE TITLE
Access Requests Failing with JavaScript Error in Teleport v16.1.4

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#45542]
Expected behavior:

Access requests should be processed without errors, and the web UI should function as expected without throwing JavaScript errors.

Current behavior:

We're experiencing an issue with Access Requests on Teleport versions v16.1.4 and v15 The issue occurs when attempting to view or interact with resources after submitting an access request. The web UI throws JavaScript errors, and we receive a 403 error in the network tab of the browser's developer tools.

Environment:

Teleport Version: v16.1.4
Deployment: Self-hosted on a single node & SaaS tenant 

Bug details:
Observe the errors in the JavaScript console and the network tab.
Observed Behavior:

JavaScript Error in Console:

```
app.js:166 [components/CatchError] render TypeError: Cannot read properties of undefined (reading 'value')
at ZKe (app.js:2071:37359)
```

Additionally, we observed this error in the logs:

```
Skipping trait value. field:login value:{{internal.username}} error:[
Original Error: *trace.BadParameterError unsupported variable &#34;username&#34;
```

Steps to Reproduce:

Which roles should I be assigned before submitting the request?
The contractor role needs to be assigned to the fresh user.
should I request access to a role or a specific resource?
In this case, both are running into the same issue.
Do I have to have the request approved and assume the request to recreate the error?
When I selected the DBA role or resource request and clicked to proceed, I got the error below.
![image](https://github.com/user-attachments/assets/53ea996c-47cf-4625-bada-0cabc9ad054e)

Submit an access request using the below role.

```
kind: role
metadata:
  name: contractor
  revision: aaacb833-d55b-4e65-aa05-3bfadeddc1d7
spec:
  allow:
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
      verbs:
      - '*'
    request:
      roles:
      - dba
    rules:
    - resources:
      - access_list
      verbs:
      - list
      - create
      - read
      - update
      - delete
  deny: {}
version: v5
```

DBA Role:

```
kind: role
metadata:
  name: dba
  revision: 5ac3f468-63a8-4f0d-8e6b-7806589f7a89
spec:
  allow:
    db_labels:
      '*': '*'
    db_names:
    - '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
      verbs:
      - '*'
  deny: {}
```

Approver Role:

```
  name: reviewer
  revision: 3d3c5ce0-92b9-401b-9a83-d8cdef8fd8a6
spec:
  allow:
    db_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
      verbs:
      - '*'
    review_requests:
      preview_as_roles:
      - access
      - admin
      roles:
      - access
      - dba
      - admin
      - backend
      - backend-requester
  deny: {}
version: v5
```

Attempt to interact with the requested resources via the web UI.

Troubleshooting Steps Taken:

- Tested on Teleport v15, v16.1.0, v16.1.4; the issue persists.
- Restarted the cluster multiple times; the issue remains.
- Checked and modified roles, ensuring proper permissions were granted for access_list.
- The issue does occur in a SaaS tenant but is reproducible on the self-hosted environment
