### ISSUE TITLE
u2f bugs found during the test plan. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4556]
### Description

While running the test plan https://github.com/gravitational/teleport/issues/4359 I ran into a range of issues / error message when trying a hardware token.  I'm unsure if this is a bug or my user error on setup.. regardless the error messages in the logs aren't very explicit. 

**What happened**:

```log
[shared/hooks/useAttempt] attempt Error: Please check your U2F settings, make sure it is plugged in and you are using the supported browser.
U2F error: BAD_REQUEST
    at Object._getU2fErr (app.1e4cadff34a9c090d68f.js:1)
    at app.1e4cadff34a9c090d68f.js:1
    at n.responseHandler_ (vendor.4fed7f784fb7334b4548.js:37)
    at vendor.4fed7f784fb7334b4548.js:37
```

##### Safari
![Safari](https://user-images.githubusercontent.com/559288/96050717-f82e4b00-0e2e-11eb-8d6f-fa34c03d517f.png)

##### Firefox
![Firefox](https://user-images.githubusercontent.com/559288/96050726-fc5a6880-0e2e-11eb-8df2-aac1dad3a0bb.png)

##### Chrome
![Chrome](https://user-images.githubusercontent.com/559288/96050733-ff555900-0e2e-11eb-9d95-ea974d39510a.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

This is my config:
```yaml
  authentication:
    type: local
    second_factor: u2f
    u2f:
      app_id: https://teleport-4-4-fips.asteroid.earth:3080
      facets:
       - https://teleport-4-4-fips.asteroid.earth:3080
```

**Browser environment**

- Browser Version (for UI-related issues): Mixture of browsers.

**Comment by webvictim** [comment]
You might try expressing the facets as a quoted string instead:

Either:
```yaml
facets: ['https://teleport-4-4-fips.asteroid.earth:3080']
```

Or:
```yaml
facets:
- 'https://teleport-4-4-fips.asteroid.earth:3080'
```

**Comment by benarent** [comment]
Thanks Gus, I'll try this tomorrow. ( and also update the docs )

**Comment by benarent** [comment]
I tried it again, with no luck.. maybe something else funky is happening. 

Have you tried u2f with Teleport 5?

**Comment by webvictim** [comment]
Yes - I just signed into my home lab on `5.0.0-beta.2` with a username/password and the U2F key I set up before (somewhere around `4.3.0` I think)

If there is a bug, it seems to be related to signups rather than existing logins.

**Comment by webvictim** [comment]
I just signed up a new user on my `5.0.0-beta.2` cluster with a different U2F key as well - worked fine.

**Comment by benarent** [comment]
Thanks for testing @webvictim. This must be something with my setup or my key. I'll mark as closed for now, as we'll come back and fix other u2f fixes in an upcoming release.

**Comment by webvictim** [comment]
Just to try and close this out, I tested this on AWS with `4.4.0-rc.3` and a U2F key, it worked fine.

```yaml
auth_service:
  authentication:
    second_factor: u2f
    u2f:
      app_id: https://gus-tfnewtwo.gravitational.io
      facets:
        - https://gus-tfnewtwo.gravitational.io
```

**Comment by webvictim** [comment]
OK, there's definitely some weirdness with U2F.

With the config from the comment above, I was able to log in via the web UI but not via `tsh login --proxy=gus-tfnewtwo.gravitational.io:443` - I get this error:

```console
Please press the button on your U2F key
*press*
ERROR REPORT:
Original Error: *trace.AccessDeniedError invalid U2F response
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/client/weblogin.go:570 github.com/gravitational/teleport/lib/client.SSHAgentU2FLogin
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2122 github.com/gravitational/teleport/lib/client.(*TeleportClient).u2fLogin
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2007 github.com/gravitational/teleport/lib/client.(*TeleportClient).localLogin
	/go/src/github.com/gravitational/teleport/lib/client/api.go:1703 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:483 main.onLogin
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:353 main.Run
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:190 main.main
	/opt/go/src/runtime/proc.go:212 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message: 
```

Looking into the auth server logs, this is the actual error:

`Oct 15 20:09:54 ip-172-31-1-51.ec2.internal /usr/local/bin/teleport[1007]: DEBU [AUTH]      Failed to authenticate: u2f: untrusted facet id. auth/methods.go:149`

I think the reason is because the facet is specified without the `:443` on the end, which has to be used via the command line because the default is to use the Teleport proxy port (3080). The code is doing a direct string comparison on the two.

I updated the config to this instead:

```yaml
auth_service:
  authentication:
    second_factor: u2f
    u2f:
      app_id: https://gus-tfnewtwo.gravitational.io
      facets:
        - https://gus-tfnewtwo.gravitational.io
        - https://gus-tfnewtwo.gravitational.io:443
```

This makes `tsh login` work, but then I can't register via the web UI. Finally, I tried this:

```yaml
auth_service:
  authentication:
    second_factor: u2f
    u2f:
      app_id: https://gus-tfnewtwo.gravitational.io
      facets:
        - 'https://gus-tfnewtwo.gravitational.io'
        - 'https://gus-tfnewtwo.gravitational.io:443'
```

This works, and I can both register and log in via the web UI and log in via `tsh`.

This is why I hate YAML. Thanks for coming to my TED talk.
