### ISSUE TITLE
Local User Passwords not synced with DynamoDB

### ISSUE THREAD

**Issue by ryanpodonnell1** [gravitational/teleport#4557]
### Description
When using DynamoDB as the backend for state local users credentials do not get backed up properly after recreating the auth server. I've confirmed DynamoDB entries for the state table have been made, indicating proper access has been provisioned via AWS IAM

**What happened**:'
1. I set the user creds with `sudo tctl users add --roles admin <username>`
1. confirm successful login in the UI
1. destroy auth server
1. recreate auth server
1. Session is still active and session resumes in the UI. Manually logout 
1. attempt to login with same creds, get `bad auth credentials` in the UI

**What you expected to happen**:

I expect local users passwords to get hashed to dynamodb so that when the new auth server comes up the credentials work accordingly

1. I set the user creds with `sudo tctl users add --roles admin <username>`
1. confirm successful login in the UI
1. destroy auth server
1. recreate auth server
1. attempt to login with same creds
1. successful login

**How to reproduce it (as minimally and precisely as possible)**:
teleport.yaml from auth server

```yaml
teleport:
  nodename: teleport-auth
  log:
    output: syslog
  storage:
     type: dynamodb
     table_name: ${dyndb_state_table}
     region: us-east-1
     audit_events_uri: ['dynamodb://${dyndb_events_table}']
     audit_sessions_uri: s3://${teleport_bucket_name}/sessions

auth_service:
  enabled: yes
  listen_addr: 0.0.0.0:${teleport_auth_server_port}
  cluster_name: midas-teleport
  tokens:
    - "proxy:${proxy_auth_token}"
    - "node:${node_auth_token}"
proxy_service:
  enabled: no
```

### Environment
- Teleport version (use `teleport version`):
```bash
Teleport Enterprise v4.3.5git:v4.3.5-0-g122349e78 go1.13.2
```
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS
**Browser environment**

- Browser Version (for UI-related issues):
`Google Chrome Version 86.0.4240.75 (Official Build) (x86_64)`

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by webvictim** [comment]
I tried to reproduce this issue but can't. I followed the same pattern - set up a Teleport cluster with 1 auth instance in an ASG, add a local user, set a password and configure a TOTP token, then terminate the auth instance and let the ASG launch a new one. When it came back up, the local user I configured before termination still worked fine to log in via the web UI.

If you can reproduce this reliably, take a look in the DynamoDB state table and check the value of `teleport/web/users/<user>/pwd` - it should be the same before and after the auth server is relaunched. You can also look at `tctl get users/<user> --with-secrets` on the auth server to see the values that Teleport is loading from DynamoDB for the user.

In my case the `pwd` (or `password_hash` in `tctl get users/<user> --with-secrets` output) value was the same before and after the auth server was restarted.

**Comment by ryanpodonnell1** [comment]
@webvictim I think I know where I messed up. I was putting the 

```yaml
    storage:
        audit_events_uri: ['dynamodb://events_table_name', 'firestore://events_table_name', 'file:///var/lib/teleport/log', 'stdout://']
        audit_sessions_uri: 's3://example.com/path/to/bucket?region=us-east-1'
```

on all nodes since it was under the `teleport` section in the YAML file, being a new user I thought this had to be configured on all nodes not just the auth server. Works now if I just put it on the auth server. Would it be better under the `auth_service` section?
