### ISSUE TITLE
Application browser is forcing the use of sentence case for no reason

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4570]
**What happened**: 

We seem to be inserting sentence case where there shouldn't be sentence case. With this config:

```yaml
app_service:
  enabled: yes
  apps:
  - name: grafana-zeus
    uri: "http://zeus:<port>"
    public_addr: "grafana-zeus.teleport.w<redacted>"
    labels:
      name: grafana
      server: zeus
  - name: librenms
    uri: "http://zeus:<port>"
    public_addr: "librenms.teleport.w<redacted>"
    labels:
      name: lidarr
      server: zeus
  - name: unifi
    uri: "https://unifi:<port>"
    public_addr: "unifi.teleport.w<redacted>"
    labels:
      name: unifi
      server: zeus
    insecure_skip_verify: true
  - name: pihole
    uri: "http://artemis"
    public_addr: "pihole.teleport.w<redacted>"
    labels:
      name: pihole
      server: artemis
  - name: ombi
    uri: "http://hades:<port>"
    public_addr: "ombi.teleport.w<redacted>"
    labels:
      name: ombi
      server: hades
  - name: plexpy
    uri: "http://hades:<port>"
    public_addr: "plexpy.teleport.w<redacted>"
    labels:
      name: plexpy
      server: hades
```

This is how my applications are actually displayed:

![2020-10-15-103232__808x584__maim](https://user-images.githubusercontent.com/897821/96265121-6f80ed80-0f9b-11eb-9ced-7807c046fa8c.png)

Also, the UI doesn't show any of the labels which have been set on the apps  - not sure if that's deliberate or an oversight. We do show them for Teleport nodes, so I figure we should here as well.

**What you expected to happen**: My app names and `public_addr`s should display verbatim, not have arbitrary capital letters inserted.

**How to reproduce it (as minimally and precisely as possible)**: Set up an app, load application browser.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v5.0.0-beta.2 git:v5.0.0-beta.2-0-g412fb2062 go1.14.4`
