### ISSUE TITLE
Provide method of listing dynamic services

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#45804]
What would you like Teleport to do?

Provide a method to list the dynamic services and labels connected to Teleport. 

What problem does this solve?

Admins would want to know what dynamic resources (app, db) are connected to the Teleport cluster. You
can list in the inventory the db services. There isn't a way to list the ones that have dynamic resource label configuration.
If you are registering or troubleshooting a dynamic registration that makes it difficult to know which db service would
apply a matching label.

Per the relation to discovery the discover flow uses dynamic registration for dbs. Without knowing what db dynamic registrations 
are available that makes it difficult to know  all the regirations esp if there is an existing `*`: `*`.

If a workaround exists, please include it.

An admin can go on each `db` or `app` service to list the available dynamic services.

**Comment by zmb3** [comment]
Dynamic resources are not services that are "connected to the cluster" - they are just resources in the backend. They can be queried with tctl get. 

Is there something that's still missing?

**Comment by stevenGravy** [comment]
> Dynamic resources are not services that are "connected to the cluster" - they are just resources in the backend. They can be queried with tctl get. 
> 
> Is there something that's still missing?

To be more clear this is the db service and the resource labels it accepts. There's not method I believe to query the db services available and the specified labels accepted. You only get db_server and db for resources that are active. There's not a method to list which db services are running with the dynamic resource matches. You would want to know for example if there is a *: * match or an existing match to a dynamic label.

**Comment by marcoandredinis** [comment]
You can do `tctl get discovery_config`.
That lists the currently configured matchers.
I'm also adding stats for discovered instances https://github.com/gravitational/teleport/pull/45637
```yaml
kind: discovery_config
metadata:
  name: dc001
spec:
  aws:
    - install:
        enroll_mode: 1
        install_teleport: true
        join_method: iam
        join_token: iam-token-teleportdev-nodes
        script_name: default-installer
        sshd_config: /etc/ssh/sshd_config
      integration: teleportdev
      regions:
        - eu-west-2
      ssm:
        document_name: MarcoSSMInstaller
      tags:
        RunDiscover: Please
      types:
        - ec2
  discovery_group: aws-prod
status:
  discovered_resources: 3
  integration_discovered_resources:
    teleportdev:
      aws_ec2:
        failed: 3
        found: 3
  last_sync_time: "2024-08-27T10:24:40.351926Z"
  state: DISCOVERY_CONFIG_STATE_SYNCING
version: v1
```

Is that what you are looking for? Or is it something else?

**Comment by stevenGravy** [comment]
Listing which hosts have the `resources` mapping for app and db.  I've updated first description to make this more clear.

```yaml
app_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
```

**Comment by marcoandredinis** [comment]
So the ones that are being proxied. Correct?
What would be the ux here?
`tctl get db_services/2b5207e3-a258-423e-a41d-e50ea2f0dfdc` and then get something like:
```yaml
kind: db_service
metadata:
  name: 2b5207e3-a258-423e-a41d-e50ea2f0dfdc
spec:
  resources:
  - aws: {}
    labels:
      '*': '*'
status:
  proxied_databases:
  - name: my-sql-prod
  - name: my-psql-dev
version: v1
```

Or should it be the other way around?
Where each database would return the `db_services` that are proxying it?
Eg.
`tctl get db/my-sql-prod`
```yaml
kind: db
metadata:
  name: my-sql-prod
spec:
# ....
status:
  proxying_db_services:
  - name: 2b5207e3-a258-423e-a41d-e50ea2f0dfdc
  - name: 2b5207e3-a258-423e-a41d-e50ea2f0dfdc
version: v1
```
