### ISSUE TITLE
Provide method of listing app dynamic services

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#45916]
What would you like Teleport to do?

Provide the ability to list dynamic application services like those available for databases.

What problem does this solve?

When a app service with dynamic resource is enabled an adminstrator cannot get a central list of those. The database service does provide that (`tctl get db_service`).  Without that you can't confirm if there's existing agents  or not with resource labels.

```yaml
app_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
```

If a workaround exists, please include it.

Once a app is registered you can tie back to the host it's being run on.
