### ISSUE TITLE
Joining sessions blocked with create host mode set to keep

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#46252]
Expected behavior:

Joining sessions is supported with `    create_host_user_mode: keep` set in the role.

Current behavior:

If `create_host_user_mode` is set to `keep` the user cannot join the session.

<img width="138" alt="image" src="https://github.com/user-attachments/assets/0f48fb6f-3781-4347-845b-88aef4aa1a8c">

```bash
Sep 04 18:37:47 dev-1 teleport[1706]: 2024-09-04T18:37:47Z WARN [SSH:NODE]  "Dropping inbound ssh connection due to error: error while creating user\n\texit status 2" sshutils/server.go:580
```

Bug details:
- Teleport version: 16.2.0
- Recreation steps

1. Create the role as below with two users assigned to it. 

```yaml
kind: role
metadata:
  name: dev-access
  descripton: Provides the development level access to resources
spec:
  allow:
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - moderator
      - observer
      - peer
      name: Join sessions
      roles:
      - 'dev-access'

    logins:
    - '{{internal.logins}}'
    - '{{email.local(external.username)}}'
    - '{{email.local(external.email)}}'
    node_labels:
      env: dev

  deny: {}
  options:
    cert_format: standard
    create_db_user: true
    create_desktop_user: true
    create_host_user_mode: keep
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v7
```

2. Add a node with the label `env: dev`. 
3. Connect with the first user via ssh to user getting created (jeff, alice,...)
4. Attempt to join as a peer from the second user.
