### ISSUE TITLE
Change/Document the default Admin role to allow access to Tokens and Apps

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4638]
Teleport 5.0 comes with the following features:

Local User Management
Add Node 
Add Application
Application List

These features require the following resources and permissions.

```yaml

# token permissions are used to generate install-node-sh script
- token
  verbs:
  # "create" lets a user to generate the install script for nodes and apps. 
  - create
  - read
  - update
  - delete
# node enables/disables the node tab in Web UI. 
- node
  verbs:
  - list

- user
  verbs:
  - list
  - create
  - delete
  - udpate
 
# appServer enable/disable the app list in Web UI
- appServer
   verbs:
   - list
```

We need to:
- [ ] Document above changes
- [ ] Change the default `Admin` role to allow above permissions.
- [ ] Answer this question: do we need a separate token type for the app servers?
