### ISSUE TITLE
AAP tab gives "missing parameter hostname" error if proxy public_addr is not set

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#4652]
### Description

**What happened**:

Given the following configuration file (leaving only relevant sections):

```yaml
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024

app_service:
  enabled: "yes"
  apps:
  - name: "grafana"
    uri: http://localhost:3000
    public_addr: 127.0.0.1
```

Teleport starts just fine, but navigating to the Applications tab in web UI the following error is shown:

<img width="1028" alt="Screen Shot 2020-10-28 at 10 17 32 AM" src="https://user-images.githubusercontent.com/339322/97474586-7d266380-1909-11eb-9f22-0800e7637bc1.png">

Tracing this down in the code, it seems like the error comes from here:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by juliaogris** [comment]
**Suggested next step:** close as fixed. 
PR https://github.com/gravitational/teleport/pull/63683 adds a startup warning for this misconfiguration (take out of draft or close).

---

This was fixed at some point after v5. The code path that called
`utils.Host("")` with an empty proxy address now falls back to the cluster name
when `proxy_service.public_addr` is not set (`proxyDNSNames()` in
`lib/web/apps.go`). The app FQDN becomes `<appname>.<clustername>` instead of
erroring.

There's no real fix for the underlying behavior - without `public_addr`,
Teleport can't know what DNS name to use for app subdomains. The fallback to
cluster name is about the best it can do. However, https://github.com/gravitational/teleport/pull/63683 adds a startup
warning when `app_service` is enabled without `proxy_service.public_addr` so
admins get a clear signal about the misconfiguration instead of silently broken
app URLs.

### Reproduction

**Version:** Teleport Enterprise v18.6.6 (git:v18.6.6-0-g6750243, go1.24.12)

**Config** (`config.yaml`) - note `proxy_service` has no `public_addr`:

```yaml
version: v3
teleport:
  nodename: tp-4652
  data_dir: /path/to/data
  log:
    severity: DEBUG

auth_service:
  listen_addr: 0.0.0.0:4025
  authentication:
    type: local
    second_factor: "on"
    webauthn:
      rp_id: localhost

proxy_service:
  # public_addr intentionally NOT set - this is the bug trigger.
  web_listen_addr: 0.0.0.0:3080
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024

ssh_service:
  enabled: "no"

app_service:
  enabled: "yes"
  apps:
    - name: "testapp"
      uri: http://localhost:9652
```

**Steps:**

1. Start a target app on port 9652 (any static HTTP server will do):
   ```
   go run foxygo.at/servedir@latest -p 9652 /path/to/www/
   ```
2. Start Teleport: `teleport start --config /path/to/config.yaml`
3. Create a user: `tctl users add test --roles=editor,access`
4. Open `https://localhost:3080`, log in, navigate to Applications.

**Results:** The Applications tab loads without error - the original "missing
parameter hostname" crash is gone. The app FQDN falls back to
`testapp.tp-4652` (appname + clustername). Clicking the app tries to navigate
to `https://testapp.tp-4652:3080/x-teleport-auth`, which doesn't resolve -
but that's expected behavior when `public_addr` isn't configured, not a bug.
