### ISSUE TITLE
Add API to change authentication settings in config file

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4667]
### Feature Request
Add an API to change the following authentication settings in the Teleport config file:

1) Default authentication type (can be `local`, `github`, `saml` or `oidc`):

```yaml
auth_service:
  authentication:
    type: github
```

2) Two-factor method used (can be `off`, `otp` or `u2f`):

```yaml
auth_service:
  authentication:
    second_factor: u2f
```

(for `u2f` we also probably need to automatically infer the `app_id` and `facets` from the `proxy_service.public_addr`, or provide a way to set these as well):

```yaml
auth_service:
  authentication:
    second_factor: u2f
    u2f:
      app_id: https://teleport.example.com:3080
      facets:
      - teleport.example.com:3080
      - https://teleport.example.com:3080
```

3) Whether local auth is allowed or not (can be `true` or `false`):

```yaml
auth_service:
  authentication:
    local_auth: true
```

### Who's it for?
Programmatic users of Teleport
