### ISSUE TITLE
Discovery Service regression after upgraded to 16.2.x and above

### ISSUE THREAD

**Issue by tunguyen9889** [gravitational/teleport#46877]
Expected behavior:

- Teleport Discovery Service is running healthy and functioning correctly.

Current behavior:

- Teleport Discovery Service is facing following errors after upgrading to 16.2.x and above:

```
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:2692","message":"Successfully registered instance client.","component":"proc:1","pid":"7.1","component":"instance:1"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3117","message":"starting upload completer service","component":"proc:1","pid":"7.1","component":"upload:1"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log/upload"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log/upload/streaming"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log/upload/streaming/default"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log/upload"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log/upload/corrupted"}
{"timestamp":"2024-09-23T21:02:35Z","level":"info","caller":"service/service.go:3133","message":"Creating directory.","component":"proc:1","pid":"7.1","component":"upload:1","directory":"/var/lib/teleport/log/upload/corrupted/default"}
{"caller":"filesessions/fileasync.go:196","component":"upload","level":"info","message":"uploader will scan /var/lib/teleport/log/upload/streaming/default every 5s","timestamp":"2024-09-23T21:02:35Z"}
{"caller":"events/complete.go:167","component":"upload:1:completer","level":"info","message":"upload completer will run every 5m0s","timestamp":"2024-09-23T21:02:35Z"}
{"timestamp":"2024-09-23T21:02:48Z","level":"info","caller":"service/connect.go:471","message":"Joining the cluster with a secure token.","component":"proc:1","pid":"7.1"}
{"caller":"join/join.go:284","component":null,"level":"info","message":"Attempting registration via proxy server.","timestamp":"2024-09-23T21:02:48Z"}
{"caller":"join/join.go:291","component":null,"level":"info","message":"Successfully registered via proxy server.","timestamp":"2024-09-23T21:02:48Z"}
{"timestamp":"2024-09-23T21:02:48Z","level":"info","caller":"service/connect.go:531","message":"Successfully obtained credentials to connect to the cluster.","component":"proc:1","pid":"7.1","identity":"Discovery"}
{"timestamp":"2024-09-23T21:02:48Z","level":"info","caller":"service/connect.go:1118","message":"Reusing Instance client.","component":"proc:1","pid":"7.1","identity":"Discovery","additional_system_roles":["App","Discovery","Db","Kube","Node","WindowsDesktop"]}
{"timestamp":"2024-09-23T21:02:48Z","level":"info","caller":"service/connect.go:566","message":"The process successfully wrote the credentials and state to the disk.","component":"proc:1","pid":"7.1","identity":"Discovery"}
{"caller":"cache/cache.go:1022","component":"discovery:service:1:cache","level":"info","message":"Cache \"discovery\" first init succeeded.","timestamp":"2024-09-23T21:02:48Z"}
{"timestamp":"2024-09-23T21:02:48Z","level":"info","caller":"service/connect.go:700","message":"The new service has started successfully. Starting syncing rotation status.","component":"proc:1","pid":"7.1","max_retry_period":256000000000}
{"caller":"common/watcher.go:116","component":"discovery:service","kind":"kube_cluster","level":"info","message":"Starting watcher.","pid":"7.1","timestamp":"2024-09-23T21:02:48Z"}
{"timestamp":"2024-09-23T21:02:48Z","level":"info","caller":"service/discovery.go:129","message":"Discovery service has successfully started","component":"proc:1","pid":"7.1","component":"discovery:service:1"}
{"caller":"common/watcher.go:116","component":"discovery:service","kind":"kube_cluster","level":"info","message":"Starting watcher.","pid":"7.1","timestamp":"2024-09-23T21:02:48Z"}
{"caller":"common/watcher.go:116","component":"discovery:service","kind":"db","level":"info","message":"Starting watcher.","pid":"7.1","timestamp":"2024-09-23T21:02:48Z"}
{"caller":"discovery/status.go:61","component":"discovery:service","discovery_config_name":"","error":"discovery config \"\" not found","level":"info","message":"Error updating discovery config status","pid":"7.1","timestamp":"2024-09-23T21:02:48Z"}
{"caller":"discovery/status.go:61","component":"discovery:service","discovery_config_name":"","error":"discovery config \"\" not found","level":"info","message":"Error updating discovery config status","pid":"7.1","timestamp":"2024-09-23T21:02:48Z"}
{"caller":"discovery/status.go:61","component":"discovery:service","discovery_config_name":"","error":"discovery config \"\" not found","level":"info","message":"Error updating discovery config status","pid":"7.1","timestamp":"2024-09-23T21:02:48Z"}
```

- Version prior to 16.1.8 is working fine.

Bug details:
- Teleport version: 16.2.x, 16.3.x and 16.4.x
- Recreation steps: Run Teleport Discovery Service with following configuration:

```
apiVersion: v1
data:
  teleport.yaml: |-
    "app_service":
      "enabled": false
    "auth_service":
      "enabled": false
    "db_service":
      "enabled": false
    "discovery_service":
      "aws":
      - "install":
          "script_name": "linux-installer-fips"
        "regions":
        - "us-west-2"
        "ssm":
          "document_name": "TeleportDiscoveryInstaller"
        "tags":
          "os": "linux"
          "teleport-discovery": "True"
        "types":
        - "ec2"
      "discovery_group": "agent-install"
      "enabled": true
    "kubernetes_service":
      "enabled": false
    "proxy_service":
      "enabled": false
    "ssh_service":
      "enabled": false
    "teleport":
      "auth_token": "/var/lib/join-token/token"
      "log":
        "format":
          "extra_fields":
          - "timestamp"
          - "level"
          - "component"
          - "caller"
          "output": "json"
        "output": "stderr"
        "severity": "INFO"
      "proxy_server": "teleport.<proxy_server>:443"
    "tracing_service":
      "enabled": true
      "exporter_url": "grpc://otel-collector.tempo.svc.cluster.local:4317"
      "sampling_rate_per_million": 100000
    "version": "v3"
    "windows_desktop_service":
      "enabled": false
kind: ConfigMap
metadata:
  name: teleport-cluster-discovery
  namespace: teleport
```

- Debug logs:

```
{"caller":"cache/cache.go:1022","component":"discovery:service:1:cache","level":"info","message":"Cache \"discovery\" first init succeeded.","timestamp":"2024-09-23T21:07:00Z"}
{"timestamp":"2024-09-23T21:07:00Z","level":"debug","caller":"service/discovery.go:175","message":"Access graph is disabled or not configured. Falling back to the Auth server's access graph configuration.","component":"proc:1","pid":"8.1","component":"discovery:service:1"}
{"caller":"cloud/clients.go:807","component":null,"level":"debug","message":"Initializing AWS session for region xx-xxxx-xx using environment credentials.","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"service/supervisor.go:224","component":"proc:1","level":"debug","message":"Adding service to supervisor.","pid":"8.1","service":"discovery.stop","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"service/supervisor.go:426","component":"proc:1","event":"DiscoveryReady","level":"debug","message":"Broadcasting event.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"service/supervisor.go:451","component":"proc:1","in":"DiscoveryReady","level":"debug","message":"Broadcasting mapped event.","out":"EventMapping(in=[InstanceReady TracingReady DiscoveryReady], out=TeleportReady)","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"services/watcher.go:249","component":"discovery:service","level":"debug","message":"Starting watch.","pid":"8.1","resource-kind":"node","timestamp":"2024-09-23T21:07:01Z"}
{"timestamp":"2024-09-23T21:07:01Z","level":"info","caller":"service/connect.go:700","message":"The new service has started successfully. Starting syncing rotation status.","component":"proc:1","pid":"8.1","max_retry_period":256000000000}
{"caller":"common/watcher.go:116","component":"discovery:service","kind":"kube_cluster","level":"info","message":"Starting watcher.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"services/reconciler.go:113","component":"discovery:service","kind":"kube_cluster","level":"debug","message":"Reconciling 0 current resources with 0 new resources.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"service/supervisor.go:312","component":"proc:1","level":"debug","message":"Service has started.","pid":"8.1","service":"discovery.stop","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"automaticupgrades/channel.go:60","component":null,"level":"debug","message":"'default' automatic update channel manually specified, honoring it.","timestamp":"2024-09-23T21:07:01Z"}
{"timestamp":"2024-09-23T21:07:01Z","level":"info","caller":"service/discovery.go:129","message":"Discovery service has successfully started","component":"proc:1","pid":"8.1","component":"discovery:service:1"}
{"caller":"common/watcher.go:116","component":"discovery:service","kind":"kube_cluster","level":"info","message":"Starting watcher.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"timestamp":"2024-09-23T21:07:01Z","level":"debug","caller":"service/state.go:118","message":"Teleport component has started.","component":"proc:1","pid":"8.1","component":"discovery:service"}
{"caller":"common/watcher.go:116","component":"discovery:service","kind":"db","level":"info","message":"Starting watcher.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"services/reconciler.go:113","component":"discovery:service","kind":"db","level":"debug","message":"Reconciling 0 current resources with 0 new resources.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/discovery.go:1062","component":"discovery:service","level":"debug","message":"EC2 instances discovered (AccountID: xxxxxxxxxxxxx, Instances: [i-xxxxxxxxxxxxx]), starting installation","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/discovery.go:973","component":"discovery:service","level":"debug","message":"All discovered EC2 instances are already part of the cluster.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/status.go:61","component":"discovery:service","discovery_config_name":"","error":"discovery config \"\" not found","level":"info","message":"Error updating discovery config status","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/discovery.go:1062","component":"discovery:service","level":"debug","message":"EC2 instances discovered (AccountID: xxxxxxxxxxxxx, Instances: [i-xxxxxxxxxxxxx]), starting installation","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/discovery.go:973","component":"discovery:service","level":"debug","message":"All discovered EC2 instances are already part of the cluster.","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/status.go:61","component":"discovery:service","discovery_config_name":"","error":"discovery config \"\" not found","level":"info","message":"Error updating discovery config status","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
{"caller":"discovery/discovery.go:1062","component":"discovery:service","level":"debug","message":"EC2 instances discovered (AccountID: xxxxxxxxxxxxx, Instances: [i-xxxxxxxxxxxxx]), starting installation","pid":"8.1","timestamp":"2024-09-23T21:07:01Z"}
```
