### ISSUE TITLE
Role-based access control

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#4706]
### Feature Request
We would like to be able to restrict access to individual applications protected by the Teleport Application Access Proxy (AAP) according to the users' Teleport [Role](https://gravitational.com/teleport/docs/enterprise/ssh-rbac/#roles). Some applications could be open to anyone who can log into Teleport at all, some should be restricted to people with Admin access. This restriction should be part of the application configuration, whether the application is configured statically or dynamically (#4705).

### Motivation
The current all-or-nothing access to applications does not support the principle of [least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

### Who's it for?
Anyone using Teleport Roles.

**Comment by webvictim** [comment]
I believe that this is already possible (via the use of `labels` and `allow`/`deny` rules within roles, as with Teleport nodes) but is not documented yet.

**Comment by webvictim** [comment]
This is already possible (via the use of `labels` on entries under `app_service` and `allow`/`deny` rules for `app_labels` within roles, similar to Teleport nodes) but is not documented yet. The documentation will be added before Application Access is officially released.

**Comment by josegonzalez** [comment]
Now that App Access is out, any chance we can see documentation for this? I was going through the docs (prepping a doc for my manager to see if we should buy this thing) and I saw no way to limit app access based on groups folks were in (we use okta in case I can request a specific guide).

**Comment by r0mant** [comment]
@josegonzalez Yes! We're working on the access controls section for App Access docs as we speak, should be able to get it online by our 6.2 release which is in a couple of weeks.

Meanwhile, RBAC for application access works in a very similar fashion to servers/K8s/databases - using labels. When configuring the applications in your teleport.yaml file, each app can be assigned a set of static or dynamic labels, e.g.:

```yaml
app_service:
  enabled: "yes"
  apps:
  - name: "grafana"
    uri: "http://localhost:3000"
    # Static labels
    labels:
      env: prod
    # Dynamic labels
    commands:
    - name: date
      command: [/bin/date]
      period: 1s
```

Then in your role configuration you can use `app_labels` field to allow/deny access to specific applications e.g.

```yaml
kind: role
version: v3
metadata:
  name: dev
spec:
  allow:
    # ... other fields skipped ...
    app_labels:
      "env": "prod"
```

For SSO users you can use claims/attributes from your identity provider in the role templates, for example:

```yaml
app_labels:
  # Will be populated with "env" attribute of SSO user.
  "env": "{{external.env}}"
```

Check out [Role Templates](https://goteleport.com/docs/access-controls/guides/role-templates/) (and [AC Getting Started](https://goteleport.com/docs/access-controls/getting-started/) guide) for more details. Hope this helps!
