### ISSUE TITLE
Support automatic approval workflow with Access Monitoring Rules

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/teleport#47067]
## What would you like Teleport to do?
The PagerDuty and Datadog access request plugins support an automatic approvals workflow. This workflow allows the plugin to automatically review requests for users that are on-call. The current workflow requires the Teleport requester role to be configured with the proper annotations to enable automatic approvals. See: https://goteleport.com/docs/admin-guides/access-controls/access-request-plugins/ssh-approval-pagerduty/ for an example guide.

Now that Teleport supports Access Monitoring Rules, it would be a nice UX improvement to be able to configure automatic approval rules using the Access Monitoring Rules, similarly to how notification routing rules are configure.

![image](https://github.com/user-attachments/assets/9f2ac141-ba6f-459b-88b7-7a2d6dd2c00e)

The `access_monitoring_rule` could be extended to support something like the following:
```yaml
kind: access_monitoring_rule
version: v1
metadata:
  name: your-plugin-name
spec:
  subjects: ['access_request']
  condition: 'access_request.spec.roles.contains("role-name")'
  states: ['approve']
  automatic_approval:
    name: 'pagerduty'
    on_call: ['service-name']
```
