### ISSUE TITLE
Provide more information on unavailable web app connection

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#47330]
Expected behavior:

Provide more information to the user that a connection failed and how to resolve. 

Current behavior:

If the app access service can't reach a web url the user just gets Bad Gateway. The user wouldn't be clear this is Teleport failing to connect or their own browser.

![Image](https://github.com/user-attachments/assets/75eec7b2-d931-4105-a1bc-6dc6e122c512)

Bug details:
- Teleport version: 16.4.2
- Recreation steps

1. Add a app service with a url that isn't connected.

```yaml
  - name: "grafana"
    uri: "http://localhost:3000"
    public_addr: "grafana.enterprise.teleportdemo.com"
    labels:
      env: dev
```

2. Attempt to access from the web ui
