### ISSUE TITLE
Add audit strict mode

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4755]
After working on https://github.com/gravitational/teleport/pull/4696 

I've been struggling to find a balance between security and audits, but decided to get on the side use not being waken up with S1s over hanging sessions.

However I think we need to add strict mode role option - for some sessions, if audit fails to emit at least once, the session should be terminated while letting admins troubleshoot the session.

```yaml
spec:
   options:
       # terminate session on any event loss, default is best-effort
       audit: best_effort|strict
```
