### ISSUE TITLE
Make role permissions more explicit when displaying a role details.

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4759]
@benarent  I think that our access should be more `explicit`. For example, by looking at the above role, what permissions does it give to a user? It turns out `a lot`. 

```
kind: role
metadata:
  id: 1604944504797641728
  name: new_role_name
spec:
  allow:
    app_labels:
      '*': '*'
    logins:
    - root
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
