### ISSUE TITLE
Add support for pass through headers for application access

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4762]
### Feature Request

Splunk, Grafana support pass through headers:

https://docs.splunk.com/Documentation/Splunk/8.1.0/Security/ConfigureProxySSO
https://grafana.com/docs/grafana/latest/auth/auth-proxy/

Add a line in application access to template headers with interpolating teleport users and groups

**Comment by russjones** [comment]
@klizhentas @ben I need file configuration to specify what these two headers should be named.

What should this field be called? `{username,roles}_header`?

```
app_service:
   enabled: yes
   apps:
   - name: "dumper"
     uri: "http://localhost:8080"
     rewrite:
       username_header: x-teleport-username
       roles_header: x-teleport-roles
```

**Comment by russjones** [comment]
Just chatted with @benarent about this, the following is better:

```yaml
app_service:
   enabled: yes
   apps:
   - name: "dumper"
     uri: "http://localhost:8080"
     rewrite:
       headers:
         - "x-auth-user: {{external.email}}"
         - "x-auth-groups: {{external.groups}}"
```

This allows you name and inject an arbitrary number of additional headers and even inject claim information from the identity into them.
