### ISSUE TITLE
Remove `spec.allow.app_labels` with request_access

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#4766]
### Description
Running teleport built from master, inserts wild card access to `app_labels` by default (this was a existing role):

```
kind: role
metadata:
  id: 1604623301589910300
  name: restrict
spec:
  allow:
    app_labels:
      '*': '*'
    request:
      roles:
      - contractor-a
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
    request_access: always
version: v3

```

**What happened**:
- Existing roles inserts the wild card access to `app_labels`
- Deleting this setting, re-inserts the wild card access

**What you expected to happen**:
- Roles with `request_access` should not have this access by default, or when removing from allow list, should not re-insert itself (like `node_labels`)

**How to reproduce it (as minimally and precisely as possible)**:
- Create a role with `request_access` set to `reason` or `always`
- Delete everything in deny, and allow (except for request roles)
### Environment
- Teleport version (use `teleport version`): latest 5.0.0-dev
