### ISSUE TITLE
Slack integration should show rendered result in Logins(s) field rather than templated value

### ISSUE THREAD

**Issue by gearlbrace** [gravitational/teleport#47685]
What would you like Teleport to do?
Slack integration should show rendered result in `Logins(s)` field rather than templated value when access requests are generated.

We use Google OIDC for our RBAC federation. To provide for proper login names we have to template the logins field as such:

```
spec:
  allow:
    logins:
      - '{{regexp.replace(external.email, "^(.*)@chicken.com$", "$1")}}'
```
In the slack request it shows `Role: funky Login(s): {{regexp.replace(external.email, "^(.*)@chicken.com$", "$1")}}`

What problem does this solve?
No ambiguity about the Login name.

If a workaround exists, please include it.
