### ISSUE TITLE
Document continuous backups and auto scaling settings.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4780]
```
teleport:
  storage:
    type: "dynamodb"
    table_name: "rusty-backend"
    region: "us-east-1"
    [...]

    # continuous_backups is used to enable or disable continuous backups.
    continuous_backups: [true|false]

    # auto_scaling is used to enable (and define settings for) or disable auto scaling.
    auto_scaling:  [true|false]
    read_min_capacity: int
    read_max_capacity: int
    read_target_value: float
    write_min_capacity: int
    write_max_capacity: int
    write_target_value: float
```

```
        {
            "Action": [
                "application-autoscaling:PutScalingPolicy",
                "application-autoscaling:RegisterScalableTarget"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "iam:CreateServiceLinkedRole"
            ],
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": [
                        "dynamodb.application-autoscaling.amazonaws.com"
                    ]
                }
            },
            "Effect": "Allow",
            "Resource": "*"
        }
```

For more details see: 

* https://github.com/gravitational/teleport/pull/4662
* https://github.com/gravitational/teleport/pull/4745
