### ISSUE TITLE
SSO user adding MFA becomes passkey

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#48056]
Expected behavior:

A sso user adding a MFA would only become a MFA, not a passkey.

Current behavior:

If the Teleport cluster supports passkey SSO users adding MFA become passkeys.

![Image](https://github.com/user-attachments/assets/0d78b079-b955-453e-a181-15feb370a2db)

Bug details:
- Teleport version: 17 alpha 1
- Recreation steps

1. Configure Teleport instance with webauthn support to this config

```yaml
  authentication:
    type: saml
    second_factor: on
    webauthn:
      rp_id: "teleport.example.com"
      disabled: false
```
2. Configure SSO
3. Login as SSO user
4. Add MFA
5. It will list as a passkey when a SSO user can't login with a passkey

![Image](https://github.com/user-attachments/assets/ae0145f4-59d2-4b18-8e1a-4e4e7294601b)
