### ISSUE TITLE
Application resource enrollment page doesn't render (WebUI)

### ISSUE THREAD

**Issue by gabrielcorado** [gravitational/teleport#48389]
## Expected behavior:

When opening the guided application resource enrollment, the page should render correctly.

## Current behavior:

The page doesn't render correctly:

![Image](https://github.com/user-attachments/assets/6d5d6881-56e1-4299-9d70-bc8ad8ff672f)

## Bug details
- Teleport version: v17.0.0-alpha.2
- Recreation steps:
  1. Go to the "Discover"/"Enroll New Resource" page.
  2. Select the "Application (Guided)" option.
- Debug logs (from web console):
```
app.js:101 [components/CatchError] render TypeError: Cannot read properties of undefined (reading 'expiryText')
    at $ne (app.js:1612:448)
    at V6 (app.js:38:17018)
    at yy (app.js:40:44058)
    at xy (app.js:40:39790)
    at DM (app.js:40:39718)
    at K1 (app.js:40:39570)
    at up (app.js:40:35934)
    at P9 (app.js:40:36738)
    at da (app.js:38:3279)
    at app.js:40:34263
```

**Comment by kimlisa** [comment]
that bug looks like from when we try to display the token (part of the command), i'm not able to replicate.

can you check my recording to make sure i got the flow right?
i'm on the latest branch/v17

https://github.com/user-attachments/assets/c9a7b3a0-6839-47ea-9832-d8368db9f338

**Comment by gabrielcorado** [comment]
@kimlisa I just noticed that it is only broken to me on the community edition; if I run the enterprise binary, it works fine. The community edition was always broken to me, even compiled from the source.

> can you check my recording to make sure i got the flow right?

Yes, it is the same thing I do. When I click the "Application" button, it shows the page I've attached to the issue description.

> self hosted or cloud?

Self-hosted. I tested using the binary from CDN and ECR images (both show the same error).

> did it ask you to re-authenticate?

No. The error is already present if I go from a fresh cluster, create my account, and go to this page.

Here is my Teleport config (but it is straightforward):

```yaml
version: v3
teleport:
  advertise_ip: root
  nodename: root
  data_dir: /data/
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: "yes"
  license_file: /licenses/license.pem
  proxy_listener_mode: multiplex
  cluster_name: "root"
  session_recording: node
  tokens:
  - "kube,node,auth,proxy,app,db:hard-token"
  - "trusted_cluster:clustertoken"
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: proxy.teleport.dev
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  public_addr: proxy.teleport.dev
  web_listen_addr: 0.0.0.0:4443
  https_keypairs:
  - key_file: /certs/teleport/key.pem
    cert_file: /certs/teleport/cert.pem
db_service:
  enabled: false
```
