### ISSUE TITLE
The Web UI EC2 Auto Enrollment should allow for all and/or multiple regions

### ISSUE THREAD

**Issue by milos-teleport** [gravitational/teleport#48532]
## Current situation

Right now, when a user goes through the UI Wizard, they are greeted with a step to select a singular region in which this EC2 Auto Enrollment will function.

 ## What would you like Teleport to do?
Extend the Web UI "EC2 Auto Enrollment" to support all and/or multiple regions (click-to-select)

## What problem does this solve?

Reduces unnecessary toil to the user. Imagine going through the wizard as it is now for several accounts and many regions per account.

If a workaround exists, please include it.

1. Run through the integration normally
   1. SSM document `TeleportDiscoveryInstaller` 
   2. Use `us-east-1` as the region
1. Confirm that the resources are discovered in `us-east-1`
2. Create an SSM document with the same name, properties and tags of `TeleportDiscoveryInstaller` from `us-east-1` in `us-east-2`
3. Run `tctl edit discovery_config`
   4. Remove `status` and `metadata.revision` from the existing `discovery_config` object
   5. Add the `us-east-2` region into the list where `us-east-1` already resides

Example edit:

```yaml
kind: discovery_config
metadata:
  expires: "0001-01-01T00:00:00Z"
  name: REDACTED-some-uuid
spec:
  aws:
  - install:
      enroll_mode: 1
      install_teleport: true
      join_method: iam
      join_token: teleport-ui-iam-12345678
      script_name: default-installer
      sshd_config: /etc/ssh/sshd_config
    integration: milos-cloud-audit
    regions:
    - us-east-1
    - us-east-2
    ssm:
      document_name: TeleportDiscoveryInstaller
    tags:
      '*': '*'
    types:
    - ec2
  discovery_group: cloud-discovery-group
version: v1
```

This workaround proves that we could simply loop over the user-provided SSM document name across regions they selected to provision it, and then just fill the list with all the selected regions instead of being restricted to a singular region.
