### ISSUE TITLE
Be smarter about automatically setting public_addr

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4864]
### Feature Request

With this config file:

```yaml
teleport:
  nodename: gusone
  advertise_ip: gusone.gravitational.io
  log:
    output: stderr
    severity: DEBUG

  data_dir: /var/lib/teleport
  storage:
    type: dir
    path: /var/lib/teleport/backend

auth_service:
  enabled: yes
  keep_alive_interval: 1m
  keep_alive_count_max: 3
  listen_addr: 0.0.0.0:3025
  authentication:
    second_factor: u2f
    u2f:
      app_id: https://gusone.gravitational.io
      facets:
        - gusone.gravitational.io:443
        - https://gusone.gravitational.io

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:3022

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3080
  web_listen_addr: 0.0.0.0:3080
  https_keypairs:
    - cert_file: /etc/letsencrypt/live/gusone.gravitational.io/fullchain.pem
      key_file: /etc/letsencrypt/live/gusone.gravitational.io/privkey.pem
```

When I add a user, I get the wrong URL to access the web UI:

```console
[root@ip-172-31-52-229 ~]# sudo tctl users add testuser --roles=admin
DEBU[0004] Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s  trace.component=sqlite
DEBU[0004] Synchronous: 0, busy timeout: 10000           trace.component=sqlite
DEBU[0004] Connecting to auth servers: [{0.0.0.0:3025 tcp }]. 
DEBU[0004] GRPC(CLIENT): keep alive 1m0s count: 3.       trace.component=auth
User testuser has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h0m0s:
https://gusone:3080/web/invite/9a29054ee5e6629b3527926c463636f5
```

Given that `advertise_ip` is set to a hostname (and `public_addr` is not set at all) we already have enough information to be able to give the correct hostname in the signup link (`gusone.gravitational.io:3080`, rather than `gusone:3080`)

### Motivation
Make it easier to get started with Teleport without needing to set lots of values in the config file.

### Who's it for?
New Teleport users
