### ISSUE TITLE
UI waiting room isn't activated in Teleport 5.0-beta-10

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4866]
### Description

**What happened**:

While testing `5.0.0-beta.10`,  I created a role with the below definition. The CLI will require a request reason, but the user can log into the Teleport without seeing the waiting room. 

```yaml
kind: role
metadata:
  id: 1605640386793863477
  name: employee
spec:
  allow:
    app_labels:
      '*': '*'
    request:
      roles:
      - common
      - admin
      - dev-*
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
    request_access: reason
version: v3
```

```bash
tsh login --proxy=teleport.asteroid.earth:3080 --user=greg --request-reason="need db access"
Enter password for Teleport user greg:
Enter your OTP token:
340665

Seeking request approval... (id: e721c841-f790-49c0-95c5-df6d720cc54b)
```

```bash
tctl request ls
Token                                Requestor Metadata    Created At (UTC)    Status  Reasons
------------------------------------ --------- ----------- ------------------- ------- ------------------------
e721c841-f790-49c0-95c5-df6d720cc54b greg      roles=admin 17 Nov 20 19:18 UTC PENDING request="need db access"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`
