### ISSUE TITLE
Expose cluster configuration resource

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4867]
### Feature Request

Cloud and terraform users need to set second factor authentication, session recording and others.

[Cluster config](https://github.com/gravitational/teleport/blob/master/lib/services/clusterconfig.go) is already a resource.

Add tests to cover RBAC for it, add `tctl get/update` and client libraries

If there are no values set in config files, dynamic configuration will not be overwritten with defaults. Otherwise, teleport config file overrides the cluster configuration.

**Comment by webvictim** [comment]
We should also provide a way to output the current cluster config to a YAML file so that it can be stored on disk/copied around.

**Comment by klizhentas** [comment]
@webvictim `tct get cluster_config` should work with this change just fine

**Comment by awly** [comment]
Would it make more sense to not whitelist resource names and provide a getter/setter for any backend resource?
That way you can manipulate all resources without us writing client wrappers for each one.

**Comment by andrejtokarcik** [comment]
Just to make sure my understanding is correct: the mention of `tctl update` is inappropriate here since this subcommand updates the metadata (labels/ttl). Instead, what needs to be provided is support for `tctl create -f`; creating without `-f` is also inapplicable inasmuch as the cluster config is a singleton.

**Comment by webvictim** [comment]
@andrejtokarcik I believe you're right. There is only one cluster config and it should be updated in place.

**Comment by andrejtokarcik** [comment]
Unfortunately, it turns out I'm not sure about how the config update is supposed to work, cf. the last paragraph of Sasha's original feature request.

Let's say our current cluster config corresponds to the following YAML:
```yaml
kind: cluster_config
metadata:
  id: 1607528227958034783
  name: cluster-config
spec:
  audit: {}
  client_idle_timeout: 0s
  cluster_id: d5e4417c-aeb0-4e49-adc7-77a86861e243
  disconnect_expired_cert: false
  keep_alive_count_max: 99
  keep_alive_interval: 5m0s
  local_auth: true
  proxy_checks_host_keys: "yes"
  session_control_timeout: 0s
  session_recording: "off"
version: v3
```
This corresponds to the default config except for `keep_alive_count_max` (which defaults to `3`) and `session_recoding` (which defaults to `node`).

Then we attempt to update using `tctl create -f` with the following:
```yaml
kind: cluster_config
metadata:
  name: cluster-config
spec:
   keep_alive_count_max: 3
version: v3
```
(Setting `keep_alive_count_max` to its default value.)

Now, I see several possible options how to proceed:

1. Update only the specified field `keep_alive_count_max` to the given value, keeping the other fields with their current values. Although this could be achieved within the `tctl` tool itself using the existing `SetClusterConfig` endpoint (+ available data of the current config), the preference appears to be to have a separate update/upsert Auth API endpoint for this purpose.

2. Update the cluster config as a whole where the omitted fields are understood to be assigned their default value. In our example, this would set `keep_alive_count_max` to `3` and incidentally reset `session_recording` to `node`.

3. Check whether all the specified values are equal to their default in which case do not update the current configuration. Our example would therefore preform no update.

4. Require that all the cluster config fields be specified in the updating YAML and not perform the update if they are all equal to the default config.

Finally, as can be also seen from the YAML declarations above, the `ClusterConfig` resource does not seem to allow for configuring 2FA so perhaps there is something lacking in the original descpription of the issue and/or wrong in my approach?
