### ISSUE TITLE
ssh: handshake failed: could not find matching keys for @ops at ops

### ISSUE THREAD

**Issue by woohgit** [gravitational/teleport#489]
Ok, I'm soon giving up.

Every hour a new error comes up. I added a new cluster to the "main" cluster, called "ops". 

- started up a brand new xenial ubuntu (ops)
- installed teleport on it
- created a basic teleport.yaml on ops
- started the teleport server
- run `tctl export auth`
- registered the output and put it under /etc/teleport/ops.ca on main.
- edited the /etc/teleport.yaml on main and added the new CA (key_file) to the trusted_clusters part
- edited the /etc/teleport.yaml on ops and added the main CA + key_file definition to the trusted_clusters part.

Everything was working fine, I'm able to list the clusters:

```
wooh@otaku:~/repos/dna-ops/servers$  git:(master) tsh --proxy=main --user=apapai --login=ubuntu clusters
Cluster Name     Status
------------     ------
main             online
ops              online
```

I was able to list the nodes (although no nodes were joined)

```
wooh@otaku:~/repos/dna-ops/servers$  git:(master) tsh --proxy=main --user=apapai --login=ubuntu --cluster=ops ls
Node Name     Node ID     Address     Labels
---------     -------     -------     ------
```

- I tried to join a node to ops, but I tried with a wrong token, token had been cached on the node
- I had to remove the /var/lib/teleport on the node to make sure it'll re-register itself
- The node registered itself, but I was unable to connect to it, unfortunately I forgot to record the error, but was something like `"user apapai@main is not authorized to login as ubuntu@prd"`
- So I finally deleted the node.
- I stopped teleport on ops
- I removed /var/lib/teleport on ops
- I started everything from scratch on ops
- Re-exported the new CA on ops and added to main
- restarted everything

The problem now:

Can't list the nodes behind the "ops" cluster anymore. The clusters are connected:

```
wooh@otaku:~/repos/dna-ops/servers$  git:(master) tsh --proxy=main --user=apapai --login=ubuntu clusters
Cluster Name     Status
------------     ------
main             online
ops              online
```

But when I want to ls:

```
wooh@otaku:~/repos/dna-ops/servers$  git:(master) tsh --proxy=teleport.cloudbees.com --user=apapai --login=ubuntu --cluster=ops ls
access denied to login "ubuntu" when connecting to : ssh: handshake failed: could not find matching keys for @ops at ops
```

auth ls on ops:

```
tctl auth ls
CA keys for the local cluster ops:

CA Type     Fingerprint
-------     -----------
user        37:ff:e8:58:7c:10:71:c7:2b:84:08:0d:ec:4a:c3:1f
host        74:46:87:60:98:bb:34:59:7a:00:bf:f8:3b:f2:af:c3

CA Keys for Trusted Clusters:

Cluster Name     CA Type     Fingerprint                                         Allowed Logins
------------     -------     -----------                                         --------------
main             user        46:a4:44:cf:81:6d:e8:a7:e5:e1:47:2f:b4:51:7f:1a     apapai
main             host        a5:1f:39:35:8e:a8:e2:43:e1:18:f2:c5:71:07:f9:21     N/A
```

auth ls on main:

```
CA keys for the local cluster main:

CA Type     Fingerprint
-------     -----------
user        46:a4:44:cf:81:6d:e8:a7:e5:e1:47:2f:b4:51:7f:1a
host        a5:1f:39:35:8e:a8:e2:43:e1:18:f2:c5:71:07:f9:21

CA Keys for Trusted Clusters:

Cluster Name     CA Type     Fingerprint                                         Allowed Logins
------------     -------     -----------                                         --------------
ops              user        37:ff:e8:58:7c:10:71:c7:2b:84:08:0d:ec:4a:c3:1f     <nobody>
ops              host        74:46:87:60:98:bb:34:59:7a:00:bf:f8:3b:f2:af:c3     N/A
```

config on ops:

```
teleport:
  nodename: ops
  pid_file: /var/run/teleport.pid
  auth_token: xxxx
  auth_servers:
  - teleport-ops:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  storage:
    type: bolt
  data_dir: /var/lib/teleport
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  oidc_connectors: []
  cluster_name: ops
  tokens:
    - "proxy,node:xxx"
    - "auth:xxx"
  trusted_clusters:
    - key_file: /etc/teleport/main-cluster.ca
      allow_logins: apapai
      tunnel_addr: 172.18.64.17
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /etc/teleport/ops.key
  https_cert_file: /etc/teleport/ops.crt
```

config on main:
```
teleport:
  nodename: main
  pid_file: /var/run/teleport.pid
  auth_token: xxx
  auth_servers:
  - main:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: WARN
  storage:
    type: bolt
  data_dir: /var/lib/teleport
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  oidc_connectors: []
  cluster_name: main
  trusted_clusters:
    - key_file: /etc/teleport/ops.ca
  tokens:
    - "proxy,node:xxx"
    - "auth:xxx"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /etc/teleport/main.key
  https_cert_file: /etc/teleport/main.crt
```

I have a bad feeling that it's something on the "main", but don't know what to delete/remove in order to make it work again. 

Please advice. 

There are too many small things blocking me from setting this up. The documentation does not say anything about things like this.

*update 1*:

Hm, and again I did a  `tsh --user=apapai logout --proxy=main` && `tsh --user=apapai login --proxy=main` and it's working again.

What's happening in teleport when I stop/start an auth server? Is it loosing the auth?

Although I can't connect to the Ops joined node:

List nodes on cluster ops:
```
wooh@otaku:~/repos/dna-ops/servers$  git:(master) tsh --proxy=main --user=apapai --login=ubuntu --cluster=ops ls
Node Name             Node ID                                  Address               Labels
---------             -------                                  -------               ------
prd-nagios-ops-01     688363f3-b831-4b2c-83e1-4b58c4af6d81     172.18.64.19:3022     arch=x86_64,hostname=ip-172-18-64-19
```

Try to connect

```
wooh@otaku:~/repos/dna-ops/servers$  git:(master) tsh --proxy=main --user=apapai --login=ubuntu --cluster=ops ssh prd-nagios-ops-01
access denied to login "ubuntu" when connecting to prd-nagios-ops-01:3022: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Error on the node itself

```
Aug 04 13:34:20 ip-172-18-64-19 /usr/local/bin/teleport[2434]: time="0001-01-01T00:00:00Z" level=error msg="user apapai@main is not authorized to login as ubuntu@ops" file="srv/sshserver.go:524" fingerprint="ssh-rsa-cert-v01@openssh.com 59:8d:fc:4b:bd:be:30:69:cc:57:a9:1f:bc:05:1e:0b" local=172.18.64.19:3022 remote=172.18.64.4:60958 user=ubuntu
```

*update 2:*

I updated the `allowed_users` on `ops` and changed it to: `allowed_users: ubuntu`.

It allows me to log in now... but this is not what I want. I want to allow "apapai" to be able to login as "ubuntu" and "root". I don't want to allow everyone to be able to login as "ubuntu" from the main cluster.
