### ISSUE TITLE
Controlling user access in a trusted cluster

### ISSUE THREAD

**Issue by woohgit** [gravitational/teleport#490]
So what I want:

I want to have only 1 cluster (`main`) for maintaining users. All other clusters would be joined as trusted cluster.

Let's say we have a user `bob`. Bob is an Administrator and should be able to login to all servers as `ubuntu,root`. So we add bob.

```
tctl users add bob ubuntu,root
```

Let's say we have another user `alice`. Alice is a developer and we don't want her to login to `cluster-b` at all, but she would be able to login to `cluster-c` as `ubuntu`.

```
tctl users add alice ubuntu
```

On a trusted-cluster `cluster-b` the relevant config would be:

```
  trusted_clusters:
    - key_file: /etc/teleport/main-cluster.ca
      allow_logins: bob
      tunnel_addr: main-cluster-ip
```

On a trusted-cluster `cluster-c` the relevant config wold be:

```
  trusted_clusters:
    - key_file: /etc/teleport/main-cluster.ca
      allow_logins: bob, alice
      tunnel_addr: main-cluster-ip
```

It seems this setup won't work, because the `allow_logins` requires "real" UNIX logins and since we don't have neither bob nor alice users on the servers, they won't be able to connect as "ubuntu" or "root".

So if I change the `cluster-b` config to:

```
  trusted_clusters:
    - key_file: /etc/teleport/main-cluster.ca
      allow_logins: ubuntu,root
      tunnel_addr: main-cluster-ip
```

In this case `bob` will be able to login to cluster-b nodes as `ubuntu` and `root`, BUT alice could also login to `cluster-b`  nodes as `ubuntu`.

I don't want `alice` to be able to login to any `cluster-b` nodes.

I don't want to create ANY users on the servers , just use the default `root` and `ubuntu` ones.

I thought the `allow_logins` are teleport user logins, but it seems I'm wrong.

So how can I securely restrict `alice`, so she could only login to `cluster-c` nodes as `ubuntu` but not to `cluster-b`.

Please advice
