### ISSUE TITLE
Debug database servers hosted by database service supp

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#49192]
Allow database service to host debug/test database servers, similar to [`app_service.debug_app`](https://github.com/gravitational/teleport/blob/e5c8a5a92265e34de797585d6bff2b634da8b174/lib/service/service.go#L5889-L5891).

This allows quick testing of many features without configuring an actual database. You can test most features that happens before the actual database connection, like RBAC, routing, etc. You can also perform some basic testing over features that only require "simple" database connections like postgres web shell,  postgres session playback, or even load testing.

Sample design:
```yaml
db_service:
  # Simple bool to launch an in-memory fake PostgreSQL server. Only supports simple queries like "SELECT 1".
  debug_db_server: true

  # Or  launch the database server with more detailed configuration:
  debug_db_server:
    # (optional) name of the database server. default to "debug-db-server"
    name: "debug-db-server"
    # (optional) default to "localhost:0"
    listen_addr:  "localhost:0"
    # (optional) default to postgres
    protocol: postgres
    # (optional) default to {"teleport.dev/debug": "true"}
    static_labels:
      "teleport.dev/debug": "true"
    # (optional) use TestContainers to launch a real database in docker. default false.
    test_containers: false
```

Database service should generate proper server certs for the planned debug server:
https://github.com/gravitational/teleport/blob/e5c8a5a92265e34de797585d6bff2b634da8b174/lib/auth/db.go#L61-L63

The debug server implementation can reuse existing test servers used in unit tests (or a simpler version):
https://github.com/gravitational/teleport/blob/e5c8a5a92265e34de797585d6bff2b634da8b174/lib/srv/db/postgres/test.go#L142-L143

Once the debug server is started, it can be appended to the list of "static" databases.

It would be nice to have the option to use real docker containers with [Testcontainers](https://testcontainers.com/). Here is a POC to configure a Redis server using Testcontainers:
- https://github.com/gravitational/teleport/pull/47232
