### ISSUE TITLE
Kubernetes warning message every time I log into a cluster

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4928]
### Description

**What happened**: With this config (basically stock from `teleport configure` with a couple of extra `public_addr`s set):

```yaml
teleport:
  nodename: gus-gcp-test
  data_dir: /var/lib/teleport
  auth_token: <token>
  log:
    output: stderr
    severity: DEBUG
  ca_pin: sha256:<hash>
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:<token>
  storage:
ssh_service:
  enabled: "yes"
  labels:
    env: staging
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  - name: arch
    command: [uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: gus-gcp-test.gravitational.io:3080
  tunnel_public_addr: gus-gcp-test.gravitational.io:3024
  ssh_public_addr: gus-gcp-test.gravitational.io:3023
  https_keypairs: []
```

 I get this warning message in my Teleport log every time a user logs in:

```
Nov 19 21:07:42 gus-gcp-test teleport[2123]: WARN [AUTH]      Failed setting default kubernetes cluster for user login (user did not provide a cluster); leaving KubernetesCluster extension in the TLS certificate empty error:no kubernetes clusters registered auth/auth.go:612
```

**What you expected to happen**: No warning should be printed as nothing is actually wrong. I don't have Kubernetes support enabled for this cluster so the fact that no default cluster was set is not relevant here.

**How to reproduce it (as minimally and precisely as possible)**: Deploy with the above config and log in.

### Environment
- Teleport version (use `teleport version`): `Teleport v5.0.0-rc.2 git:v5.0.0-rc.2-0-g29725a1c0 go1.15.5`
- Tsh version (use `tsh version`): `Teleport v5.0.0-rc.2 git:v5.0.0-rc.2-0-g29725a1c0 go1.15.5`
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP
