### ISSUE TITLE
Access requests max_duration is not respected

### ISSUE THREAD

**Issue by carloscastrojumo** [gravitational/teleport#49403]
## Access Requests max_duration inconsistencies

There are two scenarios where issues with access request durations are observed:
- When creating an access request using tsh.
- When selecting multiple roles with different max_duration values in the Web UI.

### Expected behavior:

When a role defines `max_duration`, creating an access request using `tsh request create` should result in the access duration being limited to the specified `max_duration`. The behavior stands correct when creating the access request for the same role in the web UI. 

### Current behavior:

The access duration is incorrectly set to the remaining session duration instead of adhering to the role's `max_duration`.

### How to reproduce:

```yaml
kind: role
metadata:
  name: production-write-access-request
spec:
  allow:
    request:
      max_duration: 2h0m0s
      search_as_roles:
      - production-write
```

```sh
$ tsh request create --resource /teleport.example.com/kube_cluster/test-cluster --reason "test max duration"
```

![Image](https://github.com/user-attachments/assets/6a7a26c3-c5d2-4052-a661-99ffef8649f2)

### Expected behavior:

In the web UI, when having multiple roles with different `max_duration`, I expect the `max_duration` of all selected roles to be the lowest one, and that value to be updated when I add or remove roles from my selection.

### Current behavior:

When having multiple roles selected and creating an access request using the web UI, the max duration is the one with lowest value between all roles. The problem is, when we add or remove roles from the roles checkboxes list, there is no request to the backend to update that duration field based on the new roles selection.

## Bug details:
- Teleport version: 17.0.1 but was present in 16.x as well.

**Comment by zmb3** [comment]
> When a role defines max_duration, creating an access request using tsh request create should result in the access duration being limited to the specified max_duration.

I don't think this is the expected behavior according to our docs. It may be the behavior you desire, but this looks like it would be more of a behavior change than a bug fix.

**Comment by programmerq** [comment]
In my environment, I found that doing `tsh request create` while _omitting_ `--max-duration` would lead to a value of `12h` being used regardless of the `max_duration` on the role. The Web UI likely always specifies the equivalent of `--max-duration` and doesn't trigger the issue.

I agree that this feels like a `tsh` bug, but I would still expect the backend API to apply the `max_duration` logic when the object is created.

I created a user that was a member of this role only:

```
---yaml
version: v7
kind: role
metadata:
  name: deleteme-production-write-access-request
spec:
  allow:
    request:
      max_duration: 2h0m0s
      search_as_roles:
      - access
```

To determine the calculated `max_duration`, I looked at the storage backend of the auth server (SQLite in a single-instance lab) to see the calculated value.


* `tsh request create --resource /teleport.example.com/kube_cluster/mycluster --reason 'test'` - 12h in the future based on create time. (incorrect)
* `tsh request create --resource /teleport.example.com/kube_cluster/mycluster --reason 'test' --max-duration 16h` - 2h in the future based on create time. (correct)
* `tsh request create --resource /teleport.example.com/kube_cluster/mycluster --reason 'test' --max-duration 1h` - 1h in the future based on create time. (correct)
