### ISSUE TITLE
Suggested reviewers calculation issue for AWS access apps

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#49446]
There is some jankiness going on when calculating suggested reviewers when requesting access to apps representing [AWS console access](https://goteleport.com/docs/enroll-resources/application-access/cloud-apis/aws-console/).

The gist is, when requesting access to an app representing AWS console access, Teleport adds owners of **ALL** access lists as suggested reviewers to the request, even those that have nothing to do with that application or not grant any roles or traits at all.

Here's reproduction scenario (you don't need to actually have AWS console access configured to see this behavior).

- First, have an application representing AWS console registered in the cluster. Here's what I have in my static config:

```yaml
app_service:
  enabled: "yes"
  apps:
  - name: "aws"
    uri: "https://console.aws.amazon.com/ec2/v2/home"
```

- Next, have a couple of roles that, say, grant access to AWS account, read-only and full access:

```yaml
# aws-read-only
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - arn:aws:iam::123456789012:role/ReadOnlyAccess
```

```yaml
# aws-full-access
spec:
  allow:
    app_labels:
      '*': '*'
    aws_role_arns:
    - arn:aws:iam::123456789012:role/FullAccess
```

- Create 2 access lists: one that grants `aws-read-only` role and another one that grants `aws-full-access` role. Assign different owners to them. Add your Teleport user to the one that grants `aws-read-only` role.
- Create another access list that has yet another owner and that grants nothing.
  - In my case I called the list "My Completely Random List" and it has user "my-completely-random-user" as an owner.

![Image](https://github.com/user-attachments/assets/33a2a3b4-f7c6-4cb9-acfe-eb828ace0628)
![Image](https://github.com/user-attachments/assets/7d2976d4-ebf3-4922-b5f8-f57978a5ed89)

- Log in as your Teleport user (make sure it has proper requester permissions to be able to request access to everything), go to Access Requests page and attempt to submit an access request for the "aws" application. Observe that the owner from the "completely random list" gets added as a suggested reviewer despite the list itself not even granting anything.

![Image](https://github.com/user-attachments/assets/8fa02e46-48a0-4c7f-86fc-423fa8e8f95c)
