### ISSUE TITLE
Changing target cluster incorrectly updates kubeconfig in 5.0.0-rc.2

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#4945]
Running `tsh login <leaf-cluster-name>` while already logged in (i.e. when switching to a new target cluster), teleport will update the `kubeconfig` and update `current-target` to point to the newly targeted cluster even if no kubernetes clusters are active for that target.  This has the effect of unexpectedly breaking a working `kubectl` when you switch clusters.

Discovered while running trusted cluster soak tests as part of #4846

**Comment by awly** [comment]
@fspmarshall do you have the k8s port open on the root proxy?

**Comment by webvictim** [comment]
@alex-kovoy Is this the same problem you had?

**Comment by alex-kovoy** [comment]
@webvictim yes.  `tsh` switches my currect k8s context upon login. This was a bit unexpected while I was testing cloud instances especially when following manual steps of adding a server. One suggestion is that `tsh` could prompt me with a question whether I want to switch my k8s context or not on the first login. I expect this would confuse a first time Teleport cloud user as well.

**Comment by webvictim** [comment]
`tsh` switching contexts when you log into a Teleport cluster which has Kubernetes support configured is an intentional feature. I'm fairly sure it shouldn't do it if you don't actually have any Kubernetes clusters configured in Teleport, though, which is what this bug is tracking.

I'm having the same issue:

```
~ » kubectl config current-context
monster

~ » tsh login --proxy gustest.cloud.example.com:443 --user=gus@example.com --auth=local
Enter password for Teleport user gus@gravitational.com:
Enter your OTP token:
> Profile URL:        https://gustest.cloud.example.com:443
  Logged in as:       gus@example.com
  Cluster:            gustest.cloud.example.com
  Roles:              admin*
  Logins:             root
  Kubernetes:         disabled
  Valid until:        2020-11-25 04:56:59 -0400 AST [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise

~ » kubectl config current-context
gustest.cloud.example.com-gustest.cloud.example.com
```

This is my proxy config:

```yaml
    teleport:
      data_dir: /var/lib/teleport
      log:
        output: stderr
      auth_servers:
        - <redacted>:3025
      auth_token: <redacted>

    auth_service:
      enabled: no

    ssh_service:
      enabled: no

    proxy_service:
      enabled: yes
      web_listen_addr: 0.0.0.0:3080
      public_addr: gustest.cloud.example.com:443
      listen_addr: 0.0.0.0:3023
      ssh_public_addr: gustest.cloud.example.com:3023
      tunnel_listen_addr: 0.0.0.0:3024
      tunnel_public_addr: gustest.cloud.example.com:3024
      kubernetes:
        enabled: yes
        listen_addr: 0.0.0.0:3026
        public_addr: gustest.cloud.example.com:3026
```
