### ISSUE TITLE
Can't tctl create -f `autoupdate_version` without knowing the singleton name

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#49525]
### Expected behavior:

I create the following file:
```yaml
kind: autoupdate_version
version: v1
metadata:
spec:
  tools:
    target_version: 1.2.3
  agents:
    start_version: 1.2.3
    target_version: 1.2.4
    schedule: regular
    mode: enabled
```

I can `tctl create -f version.yaml`

### Current behavior:

I get:

```
ERROR: Metadata is nil
```

### Workaround

Go in teleport's source code and find
```
	MetaNameAutoUpdateVersion = "autoupdate-version"
```
