### ISSUE TITLE
Windows Tsh executable is expected in .kube folder for accessing kube_service

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4968]
### Description

**What happened**:

The user value in the config in the .kube folder uses the path .\tsh.exe for the windows client executable.  That is then requiring the `tsh.exe` to be in the `.kube` folder instead of using the executable in the path as the linux version does.
```yaml
- name: tele1c-samexample
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=samexample
      - --teleport-cluster=tele1c
      command: .\tsh.exe
```

**What you expected to happen**:

The executable population would just be `tsh.exe` to use it from the PATH, not requiring installing in the `.kube` folder.  

**How to reproduce it (as minimally and precisely as possible)**:

Have a  `kube_service` installed on a 5.0.rc2 instance and a 5.0.rc2 tsh windows executable.  Login with `tsh` to the proxy and attempt to access the k8s cluster.

Ex:
```bash
tsh.exe login --proxy=myproxy
tsh kube login mycluster
kubectl get po
>kubectl get po
Unable to connect to the server: getting credentials: exec: executable C:\Users\user1\.kube\tsh.exe not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

```

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`): 5.0.rc2
- OS (e.g. from `/etc/os-release`): Windows client
