### ISSUE TITLE
Seeing Unknown in Audit Log for App Session requests

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5004]
### Description

**What happened**:
Seeing Unknown activity in audit log for `T2009I`.
![image](https://user-images.githubusercontent.com/60704961/100639017-ac623300-3302-11eb-8fa2-6d75edd3deaa.png)

JSON of Unknown entry
```yaml
{
  "code": "T2009I",
  "ei": 0,
  "event": "app.session.request",
  "method": "GET",
  "path": "/34038/bundles/plugin/indexManagement/2.plugin.js",
  "raw_query": "",
  "status_code": 200,
  "time": "2020-11-30T16:49:10.622Z",
  "uid": "3b79465d-0b7d-48d1-94d3-dbf9d63ac4d6"
}
```
**What you expected to happen**:

Show descriptive names for app.session.requests

**How to reproduce it (as minimally and precisely as possible)**:

Configure apps in 5.0.0.  

### Environment
- Teleport version (use `teleport version`): 5.0.0
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws
