### ISSUE TITLE
Look at docs lints build "prepare docs site configuration" optimization

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#50065]
The "prepare docs site configuration" of the lint docs process can take several minutes (5-7) to even longer in some cases (1.5 hours) to setup the container to run docs checks.  As the actual checks are much quicker and this is likely a step this can probably be optimized.

**Comment by ptgott** [comment]
While `Lint (Docs)` takes less time to run now that we've switched to the Docusaurus site (around 2.5 minutes), the `actions/cache` step never seems to find a hit. This is worth looking into before we close this.

**Comment by mmcallister** [comment]
I think this is the Workflow in question - https://github.com/gravitational/teleport/actions/workflows/doc-tests.yaml

```
      # Cache node_modules. Unlike the example in the actions/cache repo, this
      # caches the node_modules directory instead of the yarn cache. This is
      # because yarn needs to build fresh packages even when it copies files
      # from the yarn cache into node_modules.
      # See:
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: '${{ github.workspace }}/docs/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}/docs/yarn.lock', github.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```

It's a bit over my head, but I'll dig around! Maybe we can add some debug logic to catch what is going wrong
