### ISSUE TITLE
`tbot` helm chart should account for `in_cluster` Kubernetes token joining

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#50170]
### Expected Behavior

The `tbot` helm chart and instructions should work equally well with either Kubernetes `static_jwks` or `in_cluster` join tokens.

### Current Behavior

Currently, when attempting to deploy the `tbot` helm chart as documented, it will _always_ include the `audience` field for the token. It populates this based on the `clusterName` chart value. Users are instructed to specify this as the Teleport cluster name, and it is a required value.

https://github.com/gravitational/teleport/blob/v17.0.5/examples/chart/tbot/values.yaml#L7-L11

This leads to errors when using an `in_cluster` token.

```
kubernetes failed to validate token: [invalid bearer token, token audiences [&#34;teleport.example.com&#34;] is invalid for the target audiences [&#34;https://kubernetes.default.svc&#34;], unknown]
```

#### Teleport Version

`tbot` chart versions between 15.4.20-15.4.23 were in the initial report, although all current chart versions appear to be affected. Latest supported versions are currently: 15.4.24, 16.4.11, 17.0.5.

#### Recreation Steps

Create an `in_cluster` kubernetes join token.

```yaml
kind: token
metadata:
  name: tbot
spec:
  join_method: kubernetes
  bot_name: tbot
  kubernetes:
    allow:
    - service_account: teleport:tbot
    type: in_cluster
  roles:
  - Bot
version: v2
```

Create a `values.yaml` for the helm release:

```yaml
# clusterName(string) -- should be the name of the Teleport cluster that your
# Bot will join. You can retrieve it by running `tctl status`.
#
# For example: `clusterName: "test.teleport.sh"`
clusterName: teleport.example.com

teleportProxyAddress: teleport.example.com:443
joinMethod: kubernetes
token: tbot
tbotConfig:
  outputs:
    - destination:
        name: teleport-event-handler-identity
        type: kubernetes_secret
      type: identity
  storage:
    name: tbot-storage
    type: memory
```

Deploy the chart. `helm install tbot teleport/tbot --version 15.4.23 --values myvalues.yaml`

When Helm generates the resources, it will include the `audience` field, which leads to the error.

```yaml
  volumes:
  - name: join-sa-token
    projected:
      sources:
        - serviceAccountToken:
            path: join-sa-token
            # 600 seconds is the minimum that Kubernetes supports. We
            # recommend this value is used.
            expirationSeconds: 600
            audience: teleport.example.com
```

#### Debug Logs 

```
{"timestamp":"2024-12-10T15:58:26Z","level":"info","caller":"config/service_identity.go:115","message":"Note: no ssh_config will be written for non-filesystem destination","component":"tbot","destination":"kubernetes_secret: teleport-event-handler-identity"}
{"timestamp":"2024-12-10T15:58:26Z","level":"debug","caller":"config/service_identity.go:124","message":"Defaulting to SSHConfigModeOn","component":"tbot"}
W1210 15:58:26.988096       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"timestamp":"2024-12-10T15:58:26Z","level":"info","caller":"tbot/anonymous_telemetry.go:84","message":"Anonymous telemetry is not enabled. Find out more about Machine ID's anonymous telemetry at https://goteleport.com/docs/machine-id/reference/telemetry/","component":"tbot"}
{"timestamp":"2024-12-10T15:58:27Z","level":"info","caller":"tbot/service_bot_identity.go:146","message":"Initializing bot identity.","component":"tbot","component":"tbot:identity"}
{"timestamp":"2024-12-10T15:58:27Z","level":"info","caller":"tbot/service_bot_identity.go:348","message":"Fetching bot identity using token","component":"tbot","component":"tbot:identity"}
{"level":"debug","msg":"Registering node to the cluster.","proxy-server":{"addr":"teleport.example.com:443","network":"tcp"},"time":"2024-12-10T15:58:27Z"}
{"level":"info","msg":"Attempting registration via proxy server.","time":"2024-12-10T15:58:27Z"}
{"level":"debug","msg":"HTTPS client init(proxyAddr=teleport.example.com:443, insecure=false, extraHeaders=map[])","time":"2024-12-10T15:58:27Z"}
{"level":"debug","msg":"Attempting https://teleport.example.com:443/v1/webapi/host/credentials","time":"2024-12-10T15:58:27Z"}
{"error":"reviewing kubernetes token with in_cluster\n\tkubernetes failed to validate token: [invalid bearer token, token audiences [\"teleport.example.com\"] is invalid for the target audiences [\"https://kubernetes.default.svc\"], unknown]","level":"debug","msg":"Registration via proxy server failed.","time":"2024-12-10T15:58:27Z"}
{"timestamp":"2024-12-10T15:58:27Z","level":"debug","caller":"tbot/tbot.go:142","message":"Unlocking bot storage.","component":"tbot"}
 
ERROR REPORT:
Original Error: trace.aggregate reviewing kubernetes token with in_cluster
	kubernetes failed to validate token: [invalid bearer token, token audiences [&#34;teleport.example.com&#34;] is invalid for the target audiences [&#34;https://kubernetes.default.svc&#34;], unknown]
Stack Trace:
	github.com/gravitational/teleport/lib/auth/join/join.go:255 github.com/gravitational/teleport/lib/auth/join.Register
	github.com/gravitational/teleport/lib/tbot/service_bot_identity.go:402 github.com/gravitational/teleport/lib/tbot.botIdentityFromToken
	github.com/gravitational/teleport/lib/tbot/service_bot_identity.go:182 github.com/gravitational/teleport/lib/tbot.(*identityService).Initialize
	github.com/gravitational/teleport/lib/tbot/tbot.go:204 github.com/gravitational/teleport/lib/tbot.(*Bot).Run
	github.com/gravitational/teleport/tool/tbot/main.go:527 main.onStart
	github.com/gravitational/teleport/tool/tbot/main.go:330 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:56 main.main
	runtime/proc.go:271 runtime.main
	runtime/asm_amd64.s:1695 runtime.goexit
User Message: reviewing kubernetes token with in_cluster
	kubernetes failed to validate token: [invalid bearer token, token audiences [&#34;teleport.example.com&#34;] is invalid for the target audiences [&#34;https://kubernetes.default.svc&#34;], unknown]
```
