### ISSUE TITLE
Constant "TLS Handshake Error: EOF" log entries when deployed behind AWS network load balancer in EKS 

### ISSUE THREAD

**Issue by Chili-Man** [gravitational/teleport#5032]
### Description
I'm using the official Helm chart (0.0.7) to deploy Teleport in AWS EKS. The only way to expose the service is through a service of LoadBalancer type; in particular I am using an AWS Network load balancer to do so via service annotations. 

**What happened**:
Things seem to be working fine, but every few seconds, dozens of `TLS Handshake Error`s occur, presumably caused by the TCP health check that the Network load balancer is running against all of the TCP ports. 

```conosle
2020/12/02 04:12:21 http: TLS handshake error from 10.200.57.164:39525: EOF
2020/12/02 04:12:21 http: TLS handshake error from 10.200.169.99:15458: EOF
2020/12/02 04:12:22 http: TLS handshake error from 10.200.86.68:31460: EOF
2020/12/02 04:12:22 http: TLS handshake error from 10.200.178.47:1753: EOF
2020/12/02 04:12:22 http: TLS handshake error from 10.200.179.85:53811: EOF
ERRO             read tcp 10.200.15.110:3023->10.200.163.89:30186: read: connection reset by peer sshutils/server.go:649
2020/12/02 04:12:23 http: TLS handshake error from 10.200.175.226:11579: EOF
2020/12/02 04:12:23 http: TLS handshake error from 10.200.169.99:44730: EOF
2020/12/02 04:12:23 http: TLS handshake error from 10.200.19.232:34603: EOF
```

I thought the error messages would go away if I set network load balancer's backend protocol to be plain `tcp` instead of `ssl`, but it still produced the above errors nonstop; so it really does seem to be an issue with Teleport handling the TCP health check from the network load balancer. 

**What you expected to happen**:
I don't expect it to throw a non-stop barrage of handshake errors from a tcp health check by the AWS network loadbalancer. It's important that the logs aren't polluted which too many of these messages because we also output the audit event logs to stdout so that our log collector can analyze it as well (for SIEM).  

**How to reproduce it (as minimally and precisely as possible)**:
Using Helm chart `0.0.7`, use these following Helm value overrides:

```yaml
  proxy:
    tls:
      enabled: true

      # This tells it to generate a self signed certificate
      usetlssecret: false

  service:
    type: LoadBalancer
    annotations:
      # External-DNS
      external-dns.alpha.kubernetes.io/hostname: "teleport.example.com"

      ##### AWS ELB settings
      # Use NLB
      service.beta.kubernetes.io/aws-load-balancer-type: nlb

      # ELB will talk with the pods through TCP
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp

  config:
    highAvailability: false
    public_address: teleport.example.com

    teleport:
      log:
        output: stdout

      storage:
        type: dir
        audit_events_uri:
          - file:///var/lib/teleport/log
          - stdout://

      auth_service:
        authentication:
          type: local
          second_factor: otp

      # There are no applications we want to proxy
      app_service:
        enabled: false

      # We don't make use of SSH
      ssh_service:
        enabled: false
```

### Environment
- Teleport version (use `teleport version`): `Teleport v5.0.0 git:v5.0.0-0-gac4971801 go1.15.5`
- Tsh version (use `tsh version`): `Teleport v5.0.0 git: go1.15.5`
- OS (e.g. from `/etc/os-release`): `Amazon Linux 2`

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS EKS 1.18.9
AWS Network Loadbalancer

**Relevant Debug Logs If Applicable**

- Details on the AWS Network load balancer health check: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html
