### ISSUE TITLE
tbot helm chart generates invalid configuration when custom outputs are specified

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#50392]
### Expected behavior:

I can use both the default output and additional ones.

```yaml
defaultOutput:
  enabled: true
outputs:
  - myOutput1
  # ...
```

### Current behavior:

The chart indents differently the custom outputs and the default one, crafting invalid YAML and causing tbot to crash.

Bug details:
- Teleport version: every version with the tbot chart

### Workaround

Disable the default output, this will solve the indentation mismatch and the YAML will be valid.

```yaml
defaultOutput:
  enabled: false
outputs:
  - myOutput1
  # ...
```
