### ISSUE TITLE
Application Redirects Fail with 'Access Denied' Error After Updating to Teleport Version 17.1.1 Due to Certificate Validation Issues

### ISSUE THREAD

**Issue by fabriciofeijo** [gravitational/teleport#50556]
--- bug report ---
**Expected behavior:**  
After updating the Teleport clients to version 17.1.1, application redirects should work normally using valid certificates automatically generated by Teleport with ACME (Let's Encrypt).

**Current behavior:**  
After the update to version 17.1.1, application redirects stopped working, showing the error message "Access Denied" and indicating that the certificate is invalid or self-signed. However, the certificate generated by the self-hosted Teleport server is valid, as we can access the server without any issues.

**Bug details:**  
- **Teleport version:**  
  - Server: 17.1.1  
  - Client: 17.1.1  
- **Recreation steps:**  
  1. Update the Teleport clients from version 16.4.6 to 17.1.1.  
  2. Configure the server and client using the following configuration files:  

     **Server (proxy_service):**  
     ```yaml
     proxy_service:
       enabled: "yes"
       web_listen_addr: 0.0.0.0:443
       public_addr: teleportdomain:443
       https_keypairs: []
       https_keypairs_reload_interval: 0s
       acme:
         enabled: "yes"
         email: support@teleportdomain
     ```

     **Client (app_service):**  
     ```yaml
     app_service:
       enabled: yes
       debug_app: false
       apps:
       - name: "oban"
         uri: "https://localhost:4002/oban"
         rewrite:
           headers:
             - "Authorization: Basic XXX"
         insecure_skip_verify: true
         labels:
           apptype: oban
     ```
  3. Attempt to access the configured application redirect on the client.  
  4. Observe that the "Access Denied" error appears, indicating certificate-related issues.

- **Debug logs:**  
  Error message displayed:
