### ISSUE TITLE
Tighten teleport.yaml validation

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5056]
### Feature Request

Use strict YAML validation when reading `teleport.yaml`.
Any fields that don't map to a config value should be treated as errors.

To prevent breaking customers on upgrade, we should spread this over 2 releases:
- 6.0: run strict validation in warning more and fall back to old validation on failure; the warning should be _very visible_ at startup, perhaps with a short sleep to prompt users to look at the logs
- 7.0: always run strict validation

### Motivation

The current validation of `teleport.yaml` checks that keys are one of a hardcoded valid set:
https://github.com/gravitational/teleport/blob/307040886efd7d2776369fada460c5998022c37e/lib/config/fileconf.go#L244-L272
But it doesn't validate that it's in the right place in the config.

Some examples of invalid configs that pass validation:
```yaml
auth_service:
  data_dir: /custom/path # this must be under "teleport:", not "auth_service:"
```

```yaml
proxy_service:
  kubernetes_service: # this must be "kubernetes"
    enabled: yes
    listen_addr: 0.0.0.0:3026

kubernetes: # this must be "kubernetes_service"
  enabled: yes
  listen_addr: 0.0.0.0:3027
```

### Who's it for?
OSS User, Pro, Enterprise
