### ISSUE TITLE
Load connector credentials from separate file

### ISSUE THREAD

**Issue by drewwells** [gravitational/teleport#5058]
### Feature Request
We want to be able to install teleport connectors on deployment of the chart. The --bootstrap flag is very handy for this.
One problem we run into is that the file being bootstrapped is a combination of application configuration and credentials/keys. Are there any plans to support separating the keys from these files?
As an example, this oidc connector has keys unencrypted in the config
```
kind: oidc
version: v2
metadata:
  name: new_oidc_connector
spec:
  display: Google
  client_secret: <unencrypted secret client secret>
  scope: [scope]
  claims_to_roles:
    - {claim...}
```

Something like this would be helpful
```
kind: oidc
version: v2
metadata:
  name: new_oidc_connector
spec:
  display: Google
  client_secret: /path/to/client/secret
  scope: [scope]
  claims_to_roles:
    - {claim...}
```

### Motivation
With this, we can separate the application configuration from the keys. The keys can then be loaded securely from a different location while the normal configuration is easy to mutate.

### Who's it for?
OSS User, Pro, Enterprise
