### ISSUE TITLE
Teleport Role permissions behaves differently in UI compared to CLI in Teleport 17.1.3

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#50767]
Expected behavior:
A user with the following role permission should be able to examine teleport roles details via the Teleport UI. Similarily, **tctl get roles** will return the Teleport Cluster roles details. 

```
kind: role
metadata:
  name: test_role
spec:
  allow:
    rules:
    - resources:
      - role
      verbs:
      - list
      - read
  deny: {}
version: v7
```

Current behavior:

The behavior has changed in Teleport 17.1.3. Test user with this role cannot examine the Teleport Roles via the Teleport UI. The UI omits the Options button. The same user and role allows view of roles via CLI using command **tctl get roles**. 

Bug details:
- Teleport version 17.1.3 
- Recreation steps
   1.    Create test user with only the test_role assigned. 
   2.    Login to Teleport UI as this test user. 
   3.    Visit Access > Roles 
   4.    Teleport Roles are visible but the button option to view the details of these roles is omitted.
