### ISSUE TITLE
Invalid input error (space) in the RBAC login section silently breaks the server access

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#5084]
Use an extra space to add a new login (user1) as shown on example below: 

```yaml
 - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    - root, user1
    node_labels:
      '*': '*'  
```

Using web ui go back to the server list and notice that it's empty.

Proxy logs will show the following (notice the skipping login line):

```bash
DEBU [SSH:PROXY] Closed connection 100.96.71.1:43489. sshutils/server.go:440
DEBU [SSH:PROXY] Incoming connection 10.0.1.216:19940 -> 100.96.71.102:3024 vesion: SSH-2.0-Go. sshutils/server.go:438
DEBU [SSH:PROXY] Closed connection 10.0.1.216:19940. sshutils/server.go:440
DEBU             Skipping login root, ec2-user, not a valid Unix login. services/role.go:360
DEBU [SSH:PROXY] Incoming connection 10.0.2.228:42184 -> 100.96.71.102:3024 vesion: SSH-2.0-Go. sshutils/server.go:438
```

Expected behavior would be to show at least a validation error when saving a role if this format is not supported.
