### ISSUE TITLE
Bring back session.upload event

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5088]
### Feature Request

Some teams would like to track `session.upload` event that is gone with stream refactoring. Emit the event at the end of the `stream` upload in async mode.

**Comment by russjones** [comment]
@quinqu 

Take a look at branch/4.3 you will be restoring the `session.upload` event from that release of Teleport.

For an example of how to create new events, take a look at the following PR and the AppSessionStart event, mirror that. Once you have the event, call `EmitAuditEvent`.

https://github.com/gravitational/teleport/pull/4582/files

Make sure `~/.aws/credentials` exists, then update `teleport.yaml` to have the following:

```yaml
  storage:
    type: "dynamodb"
    table_name: "jane-backend"
    audit_events_uri:  ["dynamodb://jane-audit-events"]
    audit_sessions_uri: "s3://jane-sessions"
```

Make sure you test success and failure modes.

Start with S3, then expand out to disk based, and IBM COS as well. Ideally you want your `session.upload` event hooked at a common point for all different upload types. That way you don't have to implement the `session.upload` event for three or four different providers.
