### ISSUE TITLE
Using a non-UUID name for OpenSSH causes Web UI to not find node in inventory

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#50914]
Expected behavior:

The node name could be both uuid and other strings w/o impacting access.

Current behavior:

Creating a node def with a non-UUID will make present an error like below when access is attempted.

```yaml
kind: node
metadata:
  name: node-host-1
spec:
  addr: 192.168.1.108:22
  hostname: my-server
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: ""
sub_kind: openssh
version: v2
```

![Image](https://github.com/user-attachments/assets/612e0aa7-7d55-4480-9940-68fc69747aac)

Bug details:
- Teleport version: 17.1.4
- Recreation steps
1. Define a node using a non-UUID `metadata.name` like above
2. Attempt to access in the Web UI
