### ISSUE TITLE
Add proxy_service.kube_public_addr field in teleport.yaml

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5110]
### Feature Request

```
proxy_service:
  kube_listen_addr: 0.0.0.0:3026
  kube_public_addr: k8s.example.com
```
should work just like
```
proxy_service:
  kubernetes:
    enabled: yes
    listen_addr: 0.0.0.0:3026
    public_addr: k8s.example.com
```

### Motivation

Follows the pattern used for ssh/web/tunnel endpoints on the proxy.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by defreng** [comment]
agree on this one :-) without this option we are struggling to run teleport proxy in a HA mode behind a load balancer

**Comment by klizhentas** [comment]
@russjones @awly can we bump this one up to 6.1 perhaps? We'd need HA K8s to work well

**Comment by awly** [comment]
PR is out for review.

To reiterate, you can still use
```yaml
proxy_service:
  kubernetes:
    enabled: yes
    listen_addr: 0.0.0.0:3026
    public_addr: k8s.example.com
```
like pre-5.0, so HA should work.

`kube_listen_addr` just made it confusing that you can use the old format.
