### ISSUE TITLE
RBAC model for Moderated Sessions needs more documentation

### ISSUE THREAD

**Issue by milos-teleport** [gravitational/teleport#51116]
Unsure if this should be a bug or a feature request.

### Observations

The current RBAC for Moderated Session is underdocumented and implicitly allows certain access when customers don't necessarily expect that to be the case.

#### Implicit allow on `ssh_session`
A user can both **list** and join session, even though we don't provide an explicit `list` on `ssh_sessions` given this role:
```
version: v7
kind: role
metadata:
  name: moderator
spec:
  allow:
    join_sessions:
    - kinds:
      - ssh
      modes:
      - moderator
      name: ""
      roles:
      - 'access'`
```

A workaround is to add the following deny statement which can block us from viewing sessions, while still allowing us to join them if we know the UUID:

```
  deny:
    rules:
    - resources:
      - ssh_sessions
      verbs:
      - list
```

#### Unclear purpose of `session_tracker`

Another observation is that it is unclear what `session_tracker` does. A user can still list and join sessions given this added deny statement:

```
  deny:
    rules:
    - resources:
      - session_tracker
      verbs:
      - read
      - list
```

Edit:

`list` on `session_tracker` can be explicitly allowed in cases where no `allow.session_join` exists, so the users can list sessions without having access to them:

```
version: v7
kind: role
metadata:
  name: moderator
spec:
  allow:
    rules:
    - resources:
      - session_tracker
      verbs:
      - list
```    

### What would you like Teleport to do?

 Document the desired behavior and usage patterns. Rework Moderated sessions RBAC if needed

### What problem does this solve?

Avoids the situation where customers run into implicit allows they were not expecting

### If a workaround exists, please include it.

To deny listing sessions while allowing joins, Teleport customers can currently add the following deny statement to their roles:

```
version: v7
kind: role
metadata:
  name: moderator
spec:
  allow:
    join_sessions:
    - kinds:
      - ssh
      modes:
      - moderator
      name: ""
      roles:
      - 'access'`
  deny:
    rules:
    - resources:
      - ssh_sessions
      verbs:
      - list
```

If users need only to **list** sessions without being able to join, this role would be appropriate:

```
version: v7
kind: role
metadata:
  name: moderator
spec:
  allow:
    rules:
    - resources:
      - session_tracker
      verbs:
      - list
```
