### ISSUE TITLE
Teleport Node Behind NAT Ignores advertise_ip / public_addr, Always Shows Unreachable External IP

### ISSUE THREAD

**Issue by arthur-avato** [gravitational/teleport#51223]
# Teleport Node Behind NAT Ignores `advertise_ip` / `public_addr`, Always Shows Unreachable External IP

## What happened

I have a Teleport **node** that sits behind NAT (or on a WiFi interface) without a true public IP. Despite configuring `version: v3` and explicitly setting all known NAT overrides (`advertise_ip`, `public_addr`, forcing the SSH service to bind `127.0.0.1`, etc.), the Teleport Auth server **always** displays this node’s **Public Address** as `60.xxx.xxx.xxx:3022` in `tctl nodes ls`. The cluster then attempts a direct TCP dial of that unreachable IP and times out (`i/o timeout`) rather than using the reverse tunnel.

**Even** referencing the node by its UUID fails for the same reason: it tries `dial tcp 60.xxx.xxx.xxx:3022`, times out, and never falls back to the reverse tunnel. The node is definitely connecting to the cluster (it “Successfully registered” and no handshake errors appear), so it’s online from the node’s perspective, but the **public address** the cluster sees is always the real external IP.

## What I expected to happen

- With `advertise_ip: 127.0.0.1` or `ssh_service.public_addr: ["127.0.0.1:3022"]`, Teleport should show `127.0.0.1:3022` in `tctl nodes ls`, or at the very least skip any direct dial and use the node’s reverse tunnel.  
- Then, `tsh ssh <nodename>` or `tsh ssh <node-uuid>` should succeed by means of the reverse tunnel, not attempt a direct IP connection that’s unreachable.

## What actually happens

- **`tctl nodes ls`** keeps listing the node as `avato-box-proto   <uuid> 60.xxx.xxx.xxx:3022 ...`.  
- All `tsh ssh` attempts against that node or its UUID attempt direct dial, time out, never succeed.  
- The node logs show “Successfully registered” with the cluster, no sign of config errors, but the cluster refuses to connect via reverse tunnel.

## Relevant config

**Central Auth&Proxy Server:** (Ubuntu)
```yaml
version: v3
teleport:
  nodename: teleport.avato.cc
  data_dir: /var/lib/teleport
  log:
    output: /var/log/teleport.log
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: true
  listen_addr: 0.0.0.0:3025
  cluster_name: avato.cc
  authentication:
    type: local
    second_factor: otp
  tokens:
    - "proxy,node:<proxy&node token>"
    - "node:<node-only-token>"
  license_file: /etc/teleport/license.pem
  proxy_checks_host_keys: false
#  routing_strategy: "tunnel"
proxy_service:
  enabled: true
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.avato.cc
  tunnel_listen_addr: 0.0.0.0:3024  
  https_cert_file: /etc/teleport/teleport.crt
  https_key_file: /etc/teleport/teleport.key
  acme:
    enabled: false
ssh_service:
  enabled: true
  listen_addr: 0.0.0.0:3022
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
```

**Node:** (Fedora)
```yaml
version: v3   # tried this explicitly

teleport:
  nodename: avato-box-proto
  data_dir: /var/lib/teleport
  auth_token: "node-only-token"
  auth_server: teleport.avato.cc:3025
  ca_pin: "sha256:..."
  advertise_ip: 127.0.0.1  # also tried 127.0.0.1:0, or removing it, etc.

ssh_service:
  enabled: true
  # tried 0.0.0.0:3022, then tried 127.0.0.1:3022
  listen_addr: 127.0.0.1:3022
  # also tried:
  # public_addr: "127.0.0.1:3022"
auth_service:
  enabled: false
proxy_service:
  enabled: false
```

I also tested:
- Removing `public_addr`
- Keeping `listen_addr: 0.0.0.0:3022` vs. `127.0.0.1:3022`
- Using `ssh_service.advertise_addr: "avato-box-proto:0"` (legacy approach)
- Wiping `/var/lib/teleport`, removing the node from `tctl nodes ls`, re-registering  
- Ensuring `systemctl teleport` is stopped and disabled so only one Teleport process runs.  
- Using `auth_server:` vs. `proxy_server:`, both show the same result.

**Every** time, the node logs no error and registers, but the cluster identifies it with `60.xxx.xxx.xxx:3022`.

## Node logs snippet

An example of the node’s logs (`--debug`) on startup:

```
Successfully registered. method:with auth server
Got connected state...
Service is creating new listener. type:node address:127.0.0.1:3022
SSH Service is starting...
...
```
No mention that it’s ignoring `advertise_ip`; it just eventually sees `Public Address = 60.xxx.xxx.xxx:3022` in the cluster.

## `tctl nodes ls` output

```
Host              UUID         Public Address           Labels   Version
----------------- -----------  ------------------------ --------- -------
teleport.avato.cc 01ed34dd...  127.0.0.1:3022          hostname=... 17.1.4
avato-box-proto   f196274e...  60.186.136.253:3022                 17.1.4
```
**Any** `tsh ssh avato-box-proto` or `tsh ssh <node-uuid>` tries direct dial to `60.186.136.253:3022` => times out.

## Additional details

- **Teleport Version**: 17.1.4 (open source).  
- **OS**: Fedora (node side).  
- **Network**: Node on WiFi behind a NAT router, 192.168.x.x local IP, Teleport sees some interface as 60.xxx external IP.  
- **We can `nc -v teleport.avato.cc 3025`** from the node, so outbound is working fine. Registration never fails.  
- No additional Teleport processes or Docker containers are present. Verified with `ps aux | grep teleport`.  
- We systematically tried all known NAT override fields: `version: v3`, replaced `auth_servers:` with `auth_server:`, used `advertise_ip`, `listen_addr` = `127.0.0.1:3022`, `public_addr`, etc. The node still shows up as `60.xxx.xxx.xxx:3022` in the cluster.

## Reproduction steps

1. On the node behind NAT:
   - `version: v3` in `/etc/teleport.yaml`
   - `advertise_ip: 127.0.0.1`
   - `listen_addr: 127.0.0.1:3022` in `ssh_service`
   - `auth_service` + `proxy_service` both off
   - Wipe `/var/lib/teleport`
   - `teleport start -c /etc/teleport.yaml --debug`
2. On the Teleport auth server:  
   - `tctl nodes ls` => sees new node’s UUID with Public Address = the external IP `60.xxx.xxx.xxx:3022`
3. `tsh ssh node-name` or `tsh ssh <uuid>` times out on direct dial.

## Please help

1. Is there some known bug in Teleport 17.x ignoring `advertise_ip` + `public_addr`?  
2. Should Teleport fallback to the reverse tunnel, but it’s not?  
3. Are there any additional config knobs or environment variables we might be missing?

Any workaround or fix is greatly appreciated!
