### ISSUE TITLE
App MFA disable keeps failing MFA challenge

### ISSUE THREAD

**Issue by carloscastrojumo** [gravitational/teleport#51350]
Expected behavior:

When I have a role to access an application with MFA disabled, even when there is other roles with different allows with MFA enabled, I expect to be able to access the application. 

Current behavior:
It returns 

![Image](https://github.com/user-attachments/assets/08e41d11-6c12-4cca-8d8c-c96ee043453c)

Bug details:
- Teleport version: v17.1.6

**Recreation steps:** 
Root leaf architecture.  Kubernetes auto discovery
```yaml
    discovery_service:
      discovery_group: cicd-eu-aug24
      enabled: true
      kubernetes:
      - labels:
          foo/teleport-app: "true"
        namespaces:
        - '*'
        types:
        - app
```

App object
```
kind: app
metadata:
  description: Discovered application in Kubernetes cluster "cicd-eu-aug24"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.13.2
    helm.sh/chart: argo-cd-7.7.10
    foo/teleport-app: "true"
    teleport.dev/discovery-type: app
    teleport.dev/kubernetes-cluster: cicd-eu-aug24
    teleport.dev/origin: discovery-kubernetes
    teleport.internal/discovery-group-name: cicd-eu-aug24
  name: argocd
  revision: acf49a4b-c044-488d-8bb5-3d46e84aff8e
spec:
  insecure_skip_verify: false
  uri: http://argo-argocd-server.argocd-system.svc.cluster.local:80
version: v3
```

![Image](https://github.com/user-attachments/assets/43f333e8-2d7a-4456-aa84-721af0cb7760)

User has 2 roles: 

One for the application. Same role in the root and the leaf that are mapped in trusted cluster
```yaml
kind: role
metadata:
  labels:
    teleport.dev/origin: kubernetes
  name: argocd-read-access
spec:
  allow:
    app_labels:
      app.kubernetes.io/name: argocd-server
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v7
```
Other for SSH access 
```yaml
kind: role
metadata:
  labels:
    teleport.dev/origin: kubernetes
  name: server-access
spec:
  allow:
    logins:
    - ec2-user
    node_labels:
      Owner: foo
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    require_session_mfa: true
    ssh_file_copy: true
version: v7
```

If I set `require_session_mfa: false` on the server-access role, Im able to access the application.

Another test that I did for troubleshooting before I found the MFA thing, was to add the same app in the root cluster that just points the uri the one defined in the leaf and it works. In this scenario MFA is not an issue. Not sure why. 
```
apps:
  - name: "argocd"
    uri: "<uri defined in leaf app>"
    labels:
      visibility_control: "hide_from_root"
```

**Comment by Joerger** [comment]
I wasn't able to reproduce this with static apps or dynamic apps, I'm wondering if there is some mismatch in the labels due to the kubernetes auto-discovery service.

@carloscastrojumo Can you run `tctl get app_server` and share the spec for the `app_server` holding the argocd dynamic app resource?

**Comment by Joerger** [comment]
> Root leaf architecture.

Can you ellaborate? Is the app in question a leaf app, and the roles are root roles? or something different?

**Comment by carloscastrojumo** [comment]
Hi @Joerger 

app_server
```yaml
kind: app_server
metadata:
  expires: "2025-01-22T21:18:18Z"
  name: argocd
spec:
  app:
    kind: app
    metadata:
      description: Discovered application in Kubernetes cluster "cicd-eu-aug24"
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: argo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: argocd-server
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/version: v2.13.2
        helm.sh/chart: argo-cd-7.7.10
        foo/teleport-app: "true"
        teleport.dev/discovery-type: app
        teleport.dev/kubernetes-cluster: cicd-eu-aug24
        teleport.dev/origin: discovery-kubernetes
        teleport.internal/discovery-group-name: cicd-eu-aug24
      name: argocd
      revision: 57de2dc1-8c0b-4b99-8ee0-3e2aa0011a73
    spec:
      insecure_skip_verify: false
      public_addr: argocd.example.com
      uri: http://argo-argocd-server.argocd-system.svc.cluster.local:80
    version: v3
  host_id: 54568c9a-a0c3-48bb-955e-690d117e1ac9
  hostname: teleport-kube-agent-0
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 17.1.4
version: v3
```

As for the roles, they have exactly the same spec (in the root and in the leaf cluster)
