### ISSUE TITLE
Built-in auto-approval of access requests

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#51682]
Extend access monitoring rules and the web UI to support configuring automatic approval of access requests within Teleport without having to use a 3rd party plugin (hosted or self-hosted) like PagerDuty.

Some related requests:

https://github.com/gravitational/teleport/issues/12079
https://github.com/gravitational/customer-sensitive-requests/issues/381

**Comment by bernardjkim** [comment]
Started hacking on this feature and had some ideas for implementation.

Proposal: Extend the AMR conditions to support additional plugin specific fields.
- `plugin.spec.name`: specifies the name of the plugin the rule applies to.
- `plugin.spec.external_annotations`: specifies an arbitrary map of annotations that can be dynamically provided by the plugin.

The `plugin.spec.name` will replace the `spec.notification.name`. This is more of a UX change. We can deprecate the `spec.notification.name` but continue to support it. With the built-in/native auto approvals, we'd like to support auto approvals without notifications. It would be a bit confusing to have to use the `spec.notification.name` in this scenario.

The `plugin.spec.external_annotations` can be used to provide arbitrary annotations, such as, "teleport.dev/roles", "teleport.dev/team", etc... These annotations can be used to identify whether a user is on-call or pre-approved for this access request.

Here is what an example AMR would look like with the new plugin fields. 
```yaml
# This AMR would allow users with the "admin" role to be pre-approved/auto-approved
# for the specific access request.
kind: access_monitoring_rule
version: v1
metadata:
  name: teleport-pre-approved-roles
spec:
  notification: # Omitted because notifications are not supported here.
  condition: >
    plugin.spec.name == "teleport-native" &&
    contains_any(plugin.spec.external_annotations["teleport.dev/roles"], set("admin")) &&
    contains_any(access_request.spec.roles, set("prod"))
  subjects:
    - access_request
  # states.approved indicates that matching access requests should be automatically approved.
  states:
    - approved
```

- `plugin.spec.name == "teleport-native"` ensures that this rule is only applied to the "teleport-native" plugin.
- `contains_any(plugin.spec.external_annotations["teleport.dev/roles"], set("admin"))` ensures that that plugin provides a set of roles that includes the "admin" role. It is up to the plugin implementation to decide what annotations are provided in the "teleport/dev/roles" set. In this case, the native plugin will provide the set of roles assigned to the requesting user.
