### ISSUE TITLE
Machine ID: Generation counter mismatches should target specific bot instances

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#52021]
What would you like Teleport to do?

Locks generated automatically when a generation counter mismatch is detected should target particular bot instances rather than named bots.

What problem does this solve?

If a generation counter mismatch is detected, a lock targeting the bot is created preventing future join attempts. The lock looks like this:

```yaml
kind: lock
metadata:
  id: 1658359514703080513
  name: 5cee949f-5203-4f3b-9805-dac35d798a16
spec:
  message: The bot user "bot-example" has been locked due to a certificate generation    mismatch, possibly indicating a stolen certificate.
  target:
    user: bot-example
version: v2
```

Note the target only includes a username and not a bot instance UUID.

With bot instances, potentially many token-joined bot lineages can be active under the same bot/user. If any single one of them fails and generates a lock, all instances will immediately stop working. This means the risk of a total lockout increases for each additional active bot instance, which is not really acceptable. Additionally, this means it applies even to bot instances using other join methods which ordinarily can't be locked out in this way.

If a workaround exists, please include it.

The lock can be manually deleted.
