### ISSUE TITLE
Machine ID generates broken `ssh_config` with TLS Routing disabled

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#52159]
### Expected behavior:

Machine ID should produce a working `ssh_config` when connected to a cluster with TLS multiplexing disabled.

The `ProxyCommand` line should pass the port 3023 tunnel host:port to the `--proxy-server` argument to `tbot ssh-proxy-command`. Also, the `ssh-multiplexer`` output type should also work with a cluster in this configuration.

```
ProxyCommand '/usr/local/bin/tbot' ssh-proxy-command --destination-dir='/opt/machine-id' --proxy-server='nlb-teleport.example.com' --cluster='teleport-dev' --no-tls-routing --no-connection-upgrade --resume --user=%r --host=%h --port=%p
```

### Current behavior:

The `ssh_config` file generates a `ProxyCommand` that refers to the Teleport web port instead of the Teleport tunnel port.

```
ProxyCommand '/usr/local/bin/tbot' ssh-proxy-command --destination-dir='/opt/machine-id' --proxy-server='teleport.example.com:443' --cluster='teleport-dev' --no-tls-routing --no-connection-upgrade --resume --user=%r --host=%h --port=%p
```

Additionally, when using the `ssh-multiplexer` output type, the `fdpass-teleport` binary doesn't have an equivalent `--proxy-server` argument.  In both cases, the result in the same X509 error output when either `tbot` or `fdpass-teleport` see the Web Port certificate. The bug likely affects whatever controls the `fdpass-teleport` binary as well as the generated `ssh_config` file.

```
$ ssh -F /opt/machine-id/ssh_config user@host
ERROR: failed connecting to host host:3022: unable to establish proxy stream
        rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

### Bug details:

`/webapi/ping` output for affected cluster:

```json
{
  "auth": {"type": "saml","second_factor": "webauthn","preferred_local_mfa": "webauthn","saml": {"name": "saml","display": "SAML","SSO": "https://saml.example.com/provider"},"private_key_policy": "none","piv_slot": "","device_trust": {},"has_motd": false,"default_session_tt1": "12h0m0s"},
  "proxy": {
    "kube": {"enabled":true,"public_addr":"nlb-teleport.example.com:3026","listen_addr":"0.0.0.0:3026"},
    "ssh": {
      "listen_addr": " [::]:3023",
      "tunnel_listen_addr": "0.0.0.0:3024",
      "web_listen_addr": "0.0.0.0:3080",
      "public_addr": "teleport.example.com:443",
      "ssh_public_addr": "nlb-teleport.example.com:3023",
      "ssh_tunnel_public_addr": "nlb-teleport.example.com:3024",
      "dial_timeout": 30000000000
    },
    "db": {"postgres_public_addr": "nlb-teleport.example.com:5432", "mysql_listen_addr": "0.0.0.0:3036", "mysql_public_addr": "nlb-teleport.example.com:3036"},
    "tls_routing_enabled": false
  },
  "server_version": "17.0.5",
  "min_client_version": "16.0.0-aa",
  "auto_update": {"tools_version": "17.0.5","tools_auto_update": false},
  "cluster_name": "teleport-dev",
  "automatic_upgrades": false
}
```

Basic Machine ID configuration with optional ssh-multiplex variant present as a separate output:

```yaml
version: v2
proxy_server: teleport.example.com:443
onboarding:
  join_method: token
  token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
storage:
  type: directory
  path: /var/lib/teleport/bot
  outputs:
  - type: identity
    destination:
      type: directory
      path: /opt/machine-id
  - type: ssh-multiplex
    destination:
      type: directory
      path: /opt/multiplex
    proxy_command:
    - /usr/local/bin/fdpass-teleport
```
