### ISSUE TITLE
Provide tbot docker image which can setup local proxy as GHA Service Container

### ISSUE THREAD

**Issue by taraspos** [gravitational/teleport#52231]
### What would you like Teleport to do?

I would like to be able to run [tbot proxy](https://goteleport.com/docs/reference/cli/tbot/#tbot-proxy) as [GitHub Service container](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers#creating-service-containers). 

GHA job configuration could look like:

```yaml
jobs:
  my_tbot_job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      my_teleport_app:
        image: public.ecr.aws/gravitational/tbot-proxy:17
        env:
          PROXY: platform.teleport.sh:443
          TOKEN: my-tbot-token
          APP: my_app
        ports:
          - 8000:8000

    steps:
    - run: |
         curl localhost:8000
```

### What problem does this solve?

Currently we're providing set of GHA [teleport-actions](https://github.com/teleport-actions) to authenticate K8S/Application/Database access for the workflows. However this type of configuration requires you to configure client certificates[^1] to communicate with application behind teleport, which might be not possible at all with some tooling or just simply less convenient as having local proxy running.

[^1]: https://github.com/teleport-actions/auth-application?tab=readme-ov-file#outputs

### If a workaround exists, please include it.

Existing docker images can't be used due to GHA Service configuration limitations where `entrypoint` or `command` settings cannot be used
- https://github.com/orgs/community/discussions/26688
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idservices

In order to be used as [GitHub Service container](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers#creating-service-containers), image has to start `tbot proxy` as a default entrypoint/command and should be configurable via env variables, see following images as example:
- https://hub.docker.com/_/postgres
- https://hub.docker.com/_/mysql

**Comment by taraspos** [comment]
After testing this a bit more I found that Github joining method doesn't work when called from service container because of lack of `ACTIONS_ID_TOKEN_REQUEST_TOKEN` and `ACTIONS_ID_TOKEN_REQUEST_URL` environment variables.

- https://github.com/gravitational/teleport/blob/d15466c5371fd8a2456932891afbffe0b2a67cb6/lib/githubactions/token_source.go#L43-L52


It seems like those environment variables are available only through shell environment expansion and not through contexts like:
- ✅ - `echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN`
- ✅ - `echo $ACTIONS_ID_TOKEN_REQUEST_URL`
- ❌ - `echo ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN}}`
- ❌ - `echo ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL}}`
- ❌ - `echo ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN}}`
- ❌ - `echo ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL}}`

Relevant runner code: https://github.com/search?q=repo%3Aactions%2Frunner%20ACTIONS_ID_TOKEN_REQUEST_TOKEN&type=code

Attempt to configure service container without providing env variable value din't work either:
```
    services:
      my_teleport_app:
        image: tbot-test:latest
        env:
          TBOT_CONFIG: ${{ needs.configure.outputs.tbot_base64_config }} 
          ACTIONS_ID_TOKEN_REQUEST_URL:  ""
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ""
```

_potentially providing docker flag like `-e VARIABLE` without value supposed to pass host variable into the container_
