### ISSUE TITLE
Unable to `terraform import` an Access List.

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#52313]
### Expected behavior:

The terraform provider should be able to perform a `terraform import ...` or `terraform plan -generate-config-out=somefile.tf` to successfully import an existing access list into the terraform state.

#### Teleport Enterprise version
reported with 15.x, reproduced with 17.2.6 (terraform provider and cluster version)

```
% terraform version
Terraform v1.10.5
on darwin_amd64
+ provider terraform.releases.teleport.dev/gravitational/teleport v17.2.7
```

#### Recreation steps

Given the following access list YAML, import it with `tctl create -f access_list.yaml`.
<details>
<summary>`access_list.yaml` contents</summary>

```yaml
version: v1
kind: access_list
metadata:
  name: 06a337d5-a49d-4ddf-857e-3746badd3a5f
spec:
  title: Access List Title
  audit:
    recurrence:
      frequency: 6months
      day_of_month: "1"
    notifications:
      start: 336h
    next_audit_date: "2025-03-01T00:00:00Z"
  description: A description of the Access List and its purpose
  owners:
    - description: test user 1
      name: testuser
      membership_kind: MEMBERSHIP_KIND_USER
  ownership_requires:
    roles:
      - access
  owner_grants:
    roles:
      - access
    traits:
      trait1:
        - value1
  grants:
    roles:
      - access
    traits:
      trait1:
        - value1
  membership_requires:
    roles:
      - access
    traits:
      required_trait1:
        - required_value1
```
</details>

Terraform Provider configuration:

```hcl
terraform {
  required_providers {
    teleport = {
      source  = "terraform.releases.teleport.dev/gravitational/teleport"
      version = "~> 17.0"
    }
  }
}

provider "teleport" {
  addr              = "teleport.example.com:443"
  ...
}
```

There are two methods to import a resource. The `terraform import` command expects you to have a Terraform resource declared in a file already. This can usually be a minimal block:

For example, given a file called `manual.tf`:

```hcl
resource "teleport_access_list" "testlist" {
}
```

Trying to import the resource results in the following error:

```
% terraform import teleport_access_list.testlist 06a337d5-a49d-4ddf-857e-3746badd3a5f
teleport_access_list.testlist: Importing from ID "06a337d5-a49d-4ddf-857e-3746badd3a5f"...
teleport_access_list.testlist: Import prepared!
  Prepared teleport_access_list for import
teleport_access_list.testlist: Refreshing state... [id=06a337d5-a49d-4ddf-857e-3746badd3a5f]
╷
│ Error: Value Conversion Error
│
│ An unexpected error was encountered trying to convert the Terraform value. This is always an error in the provider. Please report the following
│ to the provider developer:
│
│ parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
╵
```

Alternatively, instead of bare resource block (like shown in the `manual.tf` example above), you can specify an `import` and then utilize the `-generate-config-out` option. This results in the same error.

```hcl
import {
  to = teleport_access_list.testlist
  id = "06a337d5-a49d-4ddf-857e-3746badd3a5f"
}
```

```
% terraform plan -generate-config-out=accesslists.tf
teleport_access_list.deletemetest: Preparing import... [id=06a337d5-a49d-4ddf-857e-3746badd3a5f]
teleport_access_list.deletemetest: Refreshing state... [id=06a337d5-a49d-4ddf-857e-3746badd3a5f]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Value Conversion Error
│
│ An unexpected error was encountered trying to convert the Terraform value. This is always an error in the provider. Please report the following
│ to the provider developer:
│
│ parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```

This command is supposed to generate the HCL that represents the resource(s) defined by the `import` blocks, and output it to a file called `accesslists.tf`.

Even with `TF_LOG=debug`, there isn't much information that depicts what field is causing the error.
See attached file for DEBUG output: [terraform-logs.txt](https://github.com/user-attachments/files/18873598/terraform-logs.txt)
