### ISSUE TITLE
Add proxy_servers as a synonym to auth_servers in teleport.yaml

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5247]
### Feature Request

When using a reverse tunnel to register a node, allow this syntax:

```yaml
teleport:
  proxy_servers: ["proxy.example.com:3080"]
  auth_token: ...
```

Which should work just like:

```yaml
teleport:
  auth_servers: ["proxy.example.com:3080"]
  auth_token: ...
```

### Motivation

Putting a proxy server address into `auth_servers` is confusing for users, even if documented.

### Who's it for?
OSS User, Pro, Enterprise
