### ISSUE TITLE
Document how to impersonate a Kubernetes ServiceAccount with Teleport

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5248]
### Feature Request
Teleport's Kubernetes support currently allows you to impersonate either a `User` (via `kubernetes_users`) or `Group` (via `kubernetes_groups`). We should extend this to add support for impersonating a `ServiceAccount` (presumably via `kubernetes_serviceaccounts`).

### Motivation
`ServiceAccount` is the Kubernetes-recommended way to delegate permissions in automation use-cases and is often used in RBAC examples.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by awly** [comment]
Dup of https://github.com/gravitational/teleport/issues/4392

FYI, impersonation headers only support users and groups, so we'd need a completely different mechanism to impersonate service accounts (mutually exclusive with users/groups)

**Comment by webvictim** [comment]
After speaking with @tigrato, this does in fact work out of the box with Teleport today.

### Teleport resources

`access` role:

```yaml
kind: role
metadata:
  description: Access cluster resources
  name: access
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    - system:serviceaccount:default:default
    - system:serviceaccount:test:permissioned-sa
  options:
    ...
version: v6
```

### Kubernetes resources

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: permissioned-sa
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permissioned-sa-clusterrole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permissioned-sa-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: permissioned-sa
  namespace: test
roleRef:
  kind: ClusterRole
  name: permissioned-sa-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Teleport pod ClusterRole/ClusterRoleBinding
# note that the 'impersonate' verb is only needed on 'groups' and 'serviceaccounts' here for this use case
# I'm also enforcing some rudimentary permission boundaries
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teleport-test
rules:
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated # added to enforce permission boundary
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - ""
  # ServiceAccount names here aren't namespaced, but this is still good practice as a permission boundary
  resourceNames:
  - default
  - permissioned-sa
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teleport-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teleport-test
subjects:
- kind: ServiceAccount
  name: teleport-test
  namespace: teleport-test
```

Now test it out:
```
# log into cluster and run `tsh kube login`
gus@apollo:~/se/helm/test/sa-rbac (master%<) % tsh status
> Profile URL:        https://test.teleportdemo.com:443
  Logged in as:       gus
  Cluster:           test.teleportdemo.com
  Roles:              access, auditor, aws, editor
  Logins:             user, root
  Kubernetes:         enabled
  Kubernetes cluster: "test.teleportdemo.com"
  Kubernetes users:   system:serviceaccount:default:default, system:serviceaccount:test:permissioned-sa
  Valid until:        2023-06-22 23:58:16 -0300 ADT [valid for 7h59m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy

# attempt to use non-permissioned default SA is denied
gus@apollo:~/se/helm/test/sa-rbac (master%<) % tsh kubectl get nodes --as system:serviceaccount:default:default
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:default:default" cannot list resource "nodes" in API group "" at the cluster scope

# using permissioned SA works
gus@apollo:~/se/helm/test/sa-rbac (master%<) % tsh kubectl get nodes --as system:serviceaccount:test:permissioned-sa
NAME                                           STATUS   ROLES    AGE   VERSION
ip-192-168-14-140.us-east-2.compute.internal   Ready    <none>   90d   v1.25.6-eks-48e63af
ip-192-168-70-139.us-east-2.compute.internal   Ready    <none>   90d   v1.25.6-eks-48e63af
```

I'm going to leave the issue open so we can more formally test this and write up some docs/best practices.
