### ISSUE TITLE
Teleport agent nodename configuration behavior changed in 17.2.7

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#52480]
Expected behavior:
Previous to 17.2.7 the nodename configuration parameter supported an underscore character. 

```
version: v3
teleport:
  nodename: ubuntu_rds-discovery-db-aws-node
  data_dir: /var/lib/teleport
  join_params:
```

A `tsh ls` output would show the node name as `ubuntu_rds-discovery-db-aws-node`. 

Current behavior:
If the nodename contains an underscore character, Teleport UI will no longer display the nodename in tsh client nor Teleport UI. Instead, it will display the nodes UUID as the host. 

And users cannot `tsh ssh <user>@<nodename>`  to connect to the resource. 

Bug details:
- Teleport version: Teleport Cloud Version 17.2.7
- Recreation steps: Rename an existing node using an underscore character
- Debug logs
