### ISSUE TITLE
Workload ID: JWT SVID custom claim injection

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#52500]
Today, we support injecting custom RDNs into the Subject of an issued X509 SVID e.g

```yaml
kind: workload_identity
version: v1
metadata:
  name: my-workload
spec:
  spiffe:
    id: /foo/bar/{{ join.kubernetes.pod.name }}/{{ join.kubernetes.service_account.name }}
    x509:
      subject_template:
        common_name: my-common-name
        organization: my-organization
        organizational_unit: {{ join.kubernetes.service_account.name }}
```

This allows encoding information that is not suitable for the SPIFFE ID into the resulting workload identity credential. This may be used by consumers for authorization or auditing.

We should support a similar ability for JWT-SVIDs, and allow custom claims to be injected into the resulting JWT. JWT-SVIDs offer even more flexible customisation compared to X509 SVIDs.

Consider compatibility with https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_adding-assume-role-idp (Nested or Flattened) for passing information from attestation into AWS.

It'll be worth exploring a few different implementation options in this ticket and asking customers for feedback before proceeding to implementation.

As an example, it may look something like:

```yaml
kind: workload_identity
version: v1
metadata:
  name: my-workload
spec:
  spiffe:
    id: /foo/bar/{{ join.kubernetes.pod.name }}/{{ join.kubernetes.service_account.name }}
    jwt:
      extra_claims:
        "my-claim": {{ join.kubernetes.pod.name }}
        "my-fixed-claim": some-fixed-value
```

We'll probably want to decide on:

- Whether or not to support non-string claims. It seems like this would introduce a lot of additional complexity.
- Whether or not to support "nested" claims. It seems like this would introduce a lot of additional complexity, but, could offer additional flexibility.

**Comment by boxofrad** [comment]
### Option 1

I prototyped a potential implementation in #52861 to better understand the problem. It allows you to add arbitrarily nested claims as an object, and use template directives in any of the string fields. Under the hood, `extra_claims` is a protobuf [Struct](https://protobuf.dev/reference/protobuf/google.protobuf/#struct) message.

Example configuration:

```yaml
kind: workload_identity
version: v1
metadata:
  name: my-workload
spec:
  spiffe:
    id: /foo/bar
    jwt:
      extra_claims:
        "simple-string-claim": "{{ workload.kubernetes.pod.name }}"
        "something-more-complex":
          foo: "bar"
          baz:
            - true
            - 1234
            - "{{ user.name }}"
            - blah
```

Resulting JWT claims:

```json
{
  "simple-string-claim": "billing-service",
  "something-more-complex": {
    "foo": "bar"
    "baz": [true, 1234, "robot", "blah"]
  }
}
```

### Option 2

Alternatively, we could be more restrictive and make `extra_claims` a `map<string, string>` as this would likely cover the majority of use cases and avoids some complexity.

Example configuration:

```yaml
kind: workload_identity
version: v1
metadata:
  name: my-workload
spec:
  spiffe:
    id: /foo/bar
    jwt:
      extra_claims:
        "claim-1": "{{ join.kubernetes.pod.name }}"
        "claim-2": static value
```

### Option 3

An altogether different approach would be to make `extra_claims` a `string` containing JSON in which you can use template directives.

```yaml
kind: workload_identity
version: v1
metadata:
  name: my-workload
spec:
  spiffe:
    id: /foo/bar
    jwt:
      extra_claims: |
        {
          "simple-string-claim": "{{ workload.kubernetes.pod.name }}",
          "something-more-complex": {
            "foo": "bar"
            "baz": [true, 1234, "{{ user.name }}", "blah"]
          }
        }
```

---

Personally, I prefer option 1 because it's the most flexible and intuitive - and isn't dramatically more complex than the other options.
