### ISSUE TITLE
Auto Update events show as Unknown in Audit Log

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#52727]
Expected behavior:

The Auto Update `auto_update_version` and `auto_update_config` who show their name and a description.

Current behavior:

A audit log entry such as below shows as Unknown in the Audit Log list.

```json
{
  "addr.remote": "127.0.0.1:38726",
  "cluster_name": "teleport.example.com",
  "code": "AUV002I",
  "ei": 0,
  "event": "auto_update_version.update",
  "expires": "0001-01-01T00:00:00Z",
  "name": "autoupdate-version",
  "success": true,
  "time": "2025-03-04T00:24:49.261Z",
  "uid": "86ff5ba4-3ac5-49f5-8256-810f22f32f1f",
  "updated_by": "6d2bdfd3-b3fb-4dd3-a90a-3512a83d9671.teleport.example.com",
  "user": "6d2bdfd3-b3fb-4dd3-a90a-3512a83d9671.teleport.example.com",
  "user_kind": 1
}
```

<img width="390" alt="Image" src="https://github.com/user-attachments/assets/e4b8bc80-44fb-40df-8aaa-6c628c00a419" />

FYI: @hugoShaka 

Bug details:
- Teleport version: 17.3.1
- Recreation steps: 

1. Add Auto Update settings

Add this file autoupdate.yaml

```yaml
kind: autoupdate_version
metadata:
  name: autoupdate-version
spec:
  agents:
    start_version: 17.3.0
    target_version: 17.3.1
    schedule: regular
    mode: enabled
```

`tctl create -f autoupdate.yaml`

2. Review audit log
