### ISSUE TITLE
Database missing engine-version on Elasticache

### ISSUE THREAD

**Issue by DanielCastronovo** [gravitational/teleport#52839]
Expected behavior:
No error logs

Current behavior:
Error log (a lot of logs) with a db Elasticache.
Access to the DB is ok with Teleport.

Bug details:
- Teleport version
- Recreation steps
Create a manual DB (elasticache) on teleport agent.
```
roles: "db"
proxyAddr: xxxxxxxxx:443
enterprise: false
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${service_account_name}
  name: teleport-agent
authToken: "xxxxxxxxxxxxxxxxxxxxxxxx"
log:
  level: DEBUG
  format: json
databases:
  - name: testteleport
    uri: "xxxxxxxx:xxxx"
    protocol: "redis"
    static_labels:
      name: testteleport
    aws:
      region: "eu-west-1"
      assume_role_arn: xxxxxx
      elasticache:
        replication_group_id: testteleport
```
- Debug logs
`{"caller":"cloud/iam.go:200","component":"iam","error":"database missing engine-version label","level":"debug","message":"Assuming database testteleport supports IAM auth.`
