### ISSUE TITLE
Token updates allowed with create without force option

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#52884]
Expected behavior:

Using the `tctl create` without force would not allow overriding an existing token name.

Current behavior:

If a token name already exists no error is given when `tctl create` is used.  Other configurations such as roles does not allow create when the force parameter for an existing entry.

Bug details:
- Teleport version: 17.3.3
- Recreation steps

1. Create a token file token.yaml as below

```yaml
kind: token
metadata:
  name: example-bot-testmar7
spec:
  allow:
  - aws_account: "111111111111"
    aws_arn: arn:aws:sts::111111111111:assumed-role/teleport-bot-role/i-*
  bot_name: example
  join_method: iam
  roles:
  - Bot
 ```

2. Create

`tctl create token.yaml`

3. Modify the token.yaml such as changing the aws account

Run `tctl create token.yaml`

The create is allowed through wo error.
