### ISSUE TITLE
rbac postgresql and auto provisioning, add sequences, views etc ...

### ISSUE THREAD

**Issue by albundy83** [gravitational/teleport#53052]
Hello,

will it be possible to add new types of kind in auto provisioning users.
For moment, only table is supported, will it be possible to have:
- sequences
- views
at least :)

Thanks a lot

**Comment by praveenprem** [comment]
+1 Customer is interested in having the ability to  restrict user access to Postgres View objects in Teleport roles.
```yaml
spec:
  allow:
    db_names:
    - my_company_db
    db_permissions:
    - match:
        object_kind: view
      permissions:
      - SELECT
```
