### ISSUE TITLE
MWI UI: Bot Instances list

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#53584]
List of cluster-wide bot instances.

Requirements:

- Allow locking of specific bot instance
- Show tbot version, operating system, hostname, linked bot, join method.
- Perhaps pop up/window that can show join information.

**Comment by strideynet** [comment]
> Allow locking of specific bot instance

We can omit this for now, since we don't actually have this ability yet.

**Comment by strideynet** [comment]
Dump of the information we have available today:

![Image](https://github.com/user-attachments/assets/0cc9c3f7-9e49-43a1-9fba-89bdc9bac789)

![Image](https://github.com/user-attachments/assets/f75c4647-c5e8-4d08-9db8-d33da829cd9b)

```yaml
kind: bot_instance
metadata:
  expires:
    nanos: 412315000
    seconds: 1744970575
  name: 9b581a9f-057f-416f-bbc6-77db0a20461f
  revision: 275b05a1-5492-4278-b962-0064fd22bd2e
spec:
  bot_name: local-workload-id
  instance_id: 9b581a9f-057f-416f-bbc6-77db0a20461f
status:
  initial_authentication:
    authenticated_at:
      nanos: 47181000
      seconds: 1744187279
    generation: 1
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    metadata:
      raw:
        aud: leaf.tele.ottr.sh
        exp: 1744187572
        iat: 1744187272
        kubernetes.io:
          namespace: not-default
          pod:
            name: my-lovely-pod
            uid: 00000000-0000-0000-1111-000000000000
          serviceaccount:
            name: bar
            uid: 00000000-0000-0000-0000-000000000000
        nbf: 1744187272
        sub: system:serviceaccount:not-default:bar
      type: static_jwks
      username: system:serviceaccount:not-default:bar
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeVM4RHhUb3R1Y0xBQzI5eDQ2S1AKTkRyd1FrWkVsMHhScEl3ZDBSR0RFQWNMVk9NdU5uMXh1MTd1MzNCV2VnQUJtbEF2YkZuRC8yMG5jRGE3U3d1TQo4d3lmVnBmdnFiZVg1OHB2ODhWamRtQ1orL2ZEdS9RaFBraTdhS2ZVazNFY1RNR1JFcXg2clA0N0hSUnhNeGxYCmhWSWU4REtTdEFTcy8rZVI5bWVwTnhDelQxaHZMK29hMzhHbXNvY0NDLy9iYXUwSWtHVzc1ZjJRUGs1V042UjcKTU9HQUdqZ1p5Sklodk9kMDdjRXNVTWhBcXFvNzRIalJXUHllYndSNDQ4UjJiN2RKaHpPWE1NQmlRdEhyL0l1RApEVk9EZWJ6VUxXT2dLQ1g2VkRzVEI0c0VZNGJZdmpQd1VmeHpXTmQ4Rm9MU0QvNG9hbVMwQUo2R3dqSnQyQy85CjJ3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  initial_heartbeat:
    architecture: arm64
    hostname: grus.net.stellar.haus
    is_startup: true
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 83147000
      seconds: 1744187279
    uptime:
      nanos: 208794750
    version: 16.4.18
  latest_authentications:
  - authenticated_at:
      nanos: 771441000
      seconds: 1744881175
    generation: 2248
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQTBZdWtGOVVYWldEL2g2Z2dTQ1g2aEMzSTYyNkxkU3FXM3RHWm1OWUFkVmZ1NmhoVExDRjgKMnFQSHA1ckdOWUZGTTJRODVxdHZHcXFNNVlOcG5mZkUwYm90alNkSzMrYWJXdWRzVnZDbWs2Y3JSeEIrVnF6MQpZN2NFM3d5aGdIUzdsdUd4Zi9acnZmM29LQVVkYW9uNXFPSUhlV1g0d2d0clFKNUNkbGgrWnZ5S3ZSbzBCeTZ5CkZ2QnpzSko3Nkt2elQya3Q0WDNEYXFWWng2S3dJaVJVTlpGZ1BPVGNXRnEvSXZLRThsVzE4LytjZ3V1enVmZ0cKVS82UXo5cFNoeS81Mms3eFlpSjF0aTcydUdteUZtQkpTQmlLMEl1TkRxNlRGR2FXNmNJODZMd1VrSFdicmtFQQpFS1JoaTNtZ1J2R2NwUHNuMlFWK3Q0clcwc3lNemdEYjVRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 455871000
      seconds: 1744881475
    generation: 2249
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXcrMzFBemlPeVBCV2pkZERUNm9xZGhHQlFyUjJ0SEh0eTMzV3ovVGlPU2RqZ3pVa0R6Zy8KVTQydmxJd0N0byt3ckNCWldxTFNJMlNkYi8zWEoxRHNNQS84aWdyZEpSeHJmSlZHQTVtSUNSTFlOTWxMQ1dKegpINFVpdW5UQnNqcTVmdnFHSlVmWVU5d3JlZml1U3EwaVBTbFgwV2xUeVpJUnhpeUVXSnVKRHpxU01JYzFkdVA4CjBjOTZWTFY2bVhUME9KMXg5WHYweVZUVVhVeisrbmhGUnpKaERmbDZhVFhLMm9NYnJoMTFEL1BOaUxtTkJzUGkKUzl3bXAzaHFvYmg5MEFWZ2NjakR4OXBGeFZNOU9TVkxyV3RjdzdxMlpRam81eDkzTzhjc0pxYTF2ZWJaVU9KdQptTjJtYVBCNHZsWndSUXhEM3BXUDZzNTFWVDdzYUlOOHlRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 436263000
      seconds: 1744881775
    generation: 2250
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQTN5VkE4SUhmaUVqYVlWdXFINzAyY1Q1ZHpBaVhteHdrMU9vcytHZ0lUcWJ4bS9DVkt4VjIKZnNyV2szQWtoZ3hvZjhpRjliclhlaFV0TUtXS1FLQ01KSU95TEU5SWFUbU9wWVRqenhGS0NlZXhYejNpaVBENQppVWFkaFQ1bW9mdk9SUkJ4eTB5cXAremEybzFhSlV3SlY2a1VtU2oyWHFmclJ0ZWYrQ0NXOGVLc0toSGZycStOCnloMlhzWlNJZFVFaVJZVHNERHNCTWpOc2l0NUF5MnJWY2RKSjFqYjIxVUpnRTJDcnI2ZndrMU1Tc2hsb2JxSGcKaFlOUHpOa3cxeTVzcmhycnRaM21TbXU4L3RDRzVTbmFSZ3F3WUdDYUlJd1NkVVBPNWhYQ3M4TVdqejROMWNjSgpBQk1semVVbHh0aWVtQXRZUURIRzFmTTFEYldIM3JYYW5RSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 501767000
      seconds: 1744882075
    generation: 2251
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXNBQzl1MHZJVjk2MktJVEZOQ3RNT1orZC9QR1NZQzlDNTVMY3dQZ0RMZzZ0RHNHVlJMRDEKd1ZVQTIwNHZGWTRJOWh2UlNCUTF2d0NuYlRnU1BRTHNva1ZzelJZdXUwUngwYWlnaldIbXVabjhaV05PSzhnUApKUTF0Y0VmWC91NHVRdC9aK09KTERBUVV3Tk9wZ0tvRmZoeUlYZDNzeXFtNGM0c3hXd0lnUDVpZlFRYjhsK0wvCk13REJweFE4SVhuZjA5cSt0N2x1Vm9lNnpZdWJUZDV6VWE3WlRxTkl0MkNPY0NXZVgvZlhad0FNeVpVSGlYeXEKT3ZoZlNrWHhPQ0xJSjdLMDA2bEZYUzdDMktodGtKejBHb205dXdVQk5JRDRGanVxMDJKYkF6N2JuYmRzdjVxUApaazNCSkFlRFJGNitSekVQUE5qeC93WTRHclJUdkJEdVdRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 445464000
      seconds: 1744882375
    generation: 2252
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXBhZG1qdStlN2lPMVdhYmZZRGVZMGVxYzBUeUJtRC92RnhkYWN0WE92TW55bDF4bXFiRTAKYkVpS0JWM2hpZ1JkSzM5R1NzZ1FSQ1NWMU1UR1ZNbnRHb2QvOGJVamdoeFpVcG1CMnR0RzFhU2pDdDZYUmZ5VQpaYXY5TEROMTJJcTYwSjRoRWZYOTBPR3o1WHIyZkdXSG8wZ295ZG9DenV2VEVvbjErSHNTOW5BSEpHTGdCUEdhClkrWVllRHRET2pjaEZJNlpNTXNqT0pWbHF6QWMzRkdGaU5oWG5Edk1lcysvdTJ5dnNrblFyYmZ6UnFSUkREQWcKSllnSkNmRW9LVEZDR0RlMXExN1VtNW5PRnlvK21kRkFjU0lZVVY2UUFCa3JacHAxSW56OWp0ZHBmazRXVXUwTgpCN0MrLzd2dWFET0xQNHpqNzdvL3BPY2w5Q1F3bWMxWEZ3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 481576000
      seconds: 1744882675
    generation: 2253
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXFZa3RMbEVDQzRUcW5DZkZXTFA2U2JHNmwyNWJBSnVFRkV1cnErRHBobmlBTEp0QVRXZ1cKOXBReWVWVlZqdk00ekk3a1d2WUlRcG1pZlJwUm9tNGpWYUpCQWNKZHZKeUVLTFJBcGpiODVyS0VDekkvcGxTagpoc1JCbE1sNjR6dzFJN1pqZHh2Y0xnZWVKY2U0ZEpvR1djQ0h5MEhSYU5TYVozTHVieWZSK1h6YU1NS0hwb25DCnhJakZ0QjVPOXJ0bk0rdlkwckRWUjRUY1NVdytlSFBMd0dnNnRvcHp0cThwVFRTMVM4cXdrOGxkNzRsaG1obmMKSTIvaCtJTUZjK1pYVTNIM1RVbnJIbWErNHJUN3M4UTA0Y1ZKMkd3aFY0cDB6R3hhdG5kaFVrL1BneXZzN2VTbwp0TWRYc1Zwb2pxUjVvVDNsZ2ZMS1kwTytOelM2RmVoek13SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 525967000
      seconds: 1744882975
    generation: 2254
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXFOQ2xLdXdhd0M3blNLdzJwc1RrNlVhWFc5SmRTTnVBMDM1L3pkSWxwaUhldnJLNzB4OFAKWUU5ek5RckRaSHJJWmhyM3B6N1ZQbWJVeWU2dUFPdExPV0wyVWlKWkJQTm9RR0RJZFZtMmlGbm5zK05McXZibwpUcFp3ZWMvLzRpV3lvZXFaUzFSWTBrV0hWcVRhZllsR2hVTEl5YmxyT2lMNXh3QS9pZFVFbWZRMGNlRGlvZDFXCnJXL1BkbjhLZW9FZGFpTm51WDFTdGt1NFlNWS9RTFpIWWZxS05GVWJpdml2UzdCamRDVkZ4b096NjFpVm5JakoKTUc3NHJpVzNLMERVbzBSNjA1bHB3R1FMRmd1blhtVGt3dHY2akFqVC9ZRk5wa05sV1Z3cm5lNTVycGtGamQvaQpJRjlxYW5xMmNzNElOUUJxYnd0aGVRQzhiYTBHZkFyRXhRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 603883000
      seconds: 1744883275
    generation: 2255
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXQzdUdkZXdiSFpLRDM2WVkvZHFWTktoWEh2NXhOOE9WUm8rWVA3SFg5eDY1MzVScTVyeTQKT1hxRFA5YnBDVTdEdmlOZEZPMDV5UURha0NUYnNHY0ZOd2NlQTZsNVlWemQ2MnFuRFE4bFN6OHVzSkI3b0FqRApUaHJndTU1ZnRLSHZidlQ2ZjJ3TXFqL2FJN2tXSlE0eloreUwyaU5TY2prdjRCOVk0Tkl0YnhMTm9FVUtXY0hjClY2UnNaMkZONWtDQmNDZ3QzTk5MQUFlbmpEYSt6K0tEdnUxMXdwYXdrcjFpTE8yS2xBMXFrUjdkVXJVSGVzbkYKTWRjaU1HbXFTL25QWlJEYVpEeVpya3p6YlRiTEhBTzRYZGFSTEZlcnRpQ0ZWcmtBUE50UWpiMDZZbHBhRWVWbQpQaVFDY3BqU2pyeElaRGI1S0d4TXdETmpwcG4wNjd4Nld3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 655722000
      seconds: 1744883575
    generation: 2256
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXFEVDN6VGo0QUVrLzJlKzNwTTRUbXIxYzcrNlBYU05YcDc4ZSs0WGx4aklDSlp1aE5VZ3EKQ0VUd3JsUHRtK0VmQVhDK1ZMbjJUQ1p1eGk3RmlHOVdQVmFpT2FLL293Y0JQVW5aVjNmeDFtWVRzRVVIakRsQgoxKzUwUGIydU5JWGttWlVObEw1SzBlVFEvUkZxam4wb2NoZ2ZoZ0xaaDRsd0hBbWhzUzBOTXd5cHl6SitQN3c3CkxTWnp1OTlYdGo5VENTU05aL2RPUnRUaWdnMTQ1T2ErbVBhQ3FmQnhPZk1jeEtoRjdqamZaWm8zaExTcy9VWnkKZFpTZXllR0FPKzVnUUhneXg0ZmlQZ3N5REs4T2VnNE43QWZVS1crTlJCdTRIN0JhRy9oeG15TUw5ZlR0N2tGNQpwTHhsb2hGcGJ2ZEw3d2I3cW1CWm5LQit2SGFVclVWeTlRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  - authenticated_at:
      nanos: 532488000
      seconds: 1744883875
    generation: 2257
    join_attrs:
      kubernetes:
        pod:
          name: my-lovely-pod
        service_account:
          name: bar
          namespace: not-default
        subject: system:serviceaccount:not-default:bar
      meta:
        join_method: kubernetes
        join_token_name: local-workload-id
    join_method: kubernetes
    join_token: local-workload-id
    public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQTRna21RYlB6N1A3Y2d0V2t3cXd1cnBwS0dwL1hJN01JSjMrNVpIRllyTGhGM25oZlFkcUoKcU5IWk5BdHlRSE10dTd1cmJ6OEVRRmpma1FZTlNjblBqYkV0a3dZamt0VVR6SldkTk5OVFpkWFRJNnJWZ3YxSgpTcW5UR1oyQUNCR05USGp2U1haeXFnRWxQalQyOEY0bm93eVdDMkdDdnJYeVgvU2xWRWxwWXc2MnRackVHM0QwCkRleFJWek43MytvOGtaMHVzcWplQUpXSjNjTzNldmg5NlJnMXd0eEtaV24zS3NKb3ltYm9lekpIclp3SUEzRWsKQTVLbmJSdzNjb2Q3TzA2cXpHY2s2cHp2dWsrNEliV2V0Qk1RK2JEMmM2N1c4ZlEvbjdpSm44MXFROGVYaUZySQoxTzZaZDQyWXd1STFNdjcrWlJQWlBUcW9aOXZXR1QxMTF3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
  latest_heartbeats:
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 226583000
      seconds: 1744866175
    uptime:
      nanos: 160332583
      seconds: 628200
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 243070000
      seconds: 1744867975
    uptime:
      nanos: 160272333
      seconds: 630000
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 259824000
      seconds: 1744869775
    uptime:
      nanos: 160484375
      seconds: 631800
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 276123000
      seconds: 1744871575
    uptime:
      nanos: 160238958
      seconds: 633600
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 292763000
      seconds: 1744873375
    uptime:
      nanos: 160335291
      seconds: 635400
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 309515000
      seconds: 1744875175
    uptime:
      nanos: 160544458
      seconds: 637200
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 325815000
      seconds: 1744876975
    uptime:
      nanos: 160301291
      seconds: 639000
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 342245000
      seconds: 1744878775
    uptime:
      nanos: 160188041
      seconds: 640800
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 358894000
      seconds: 1744880575
    uptime:
      nanos: 160296416
      seconds: 642600
    version: 18.0.0-dev
  - architecture: arm64
    hostname: grus.net.stellar.haus
    join_method: kubernetes
    os: darwin
    recorded_at:
      nanos: 375344000
      seconds: 1744882375
    uptime:
      nanos: 160201041
      seconds: 644400
    version: 18.0.0-dev
version: v1
```
