### ISSUE TITLE
Can't register/login using a U2F key via Safari

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5397]
### Description

**What happened**: I reset the password of a user using `tctl users reset`:

```
$ e/build/tctl -d users reset gus
DEBU             Debug logging has been enabled. common/tctl.go:304
INFO             not using a config file config/configuration.go:140
DEBU             No config file or identity file, loading auth config via extension. common/tctl.go:325
DEBU [KEYSTORE]  Returning SSH certificate "/Users/gus/.tsh/keys/teleport.example.com/webvictim-cert.pub" valid until "2021-01-25 22:06:08 -0400 AST", TLS certificate "/Users/gus/.tsh/keys/teleport.example.com/webvictim-x509.pem" valid until "2021-01-26 02:06:08 +0000 UTC". client/keystore.go:355
DEBU             Found active profile: {https   teleport.example.com:443   false   } webvictim. tctl/profile.go:45
DEBU [KEYSTORE]  Returning SSH certificate "/Users/gus/.tsh/keys/teleport.example.com/webvictim-cert.pub" valid until "2021-01-25 22:06:08 -0400 AST", TLS certificate "/Users/gus/.tsh/keys/teleport.example.com/webvictim-x509.pem" valid until "2021-01-26 02:06:08 +0000 UTC". client/keystore.go:355
DEBU             Setting auth server to web proxy teleport.example.com:443. tctl/profile.go:77
DEBU             Connecting to auth servers: [{teleport.example.com:443 tcp }]. common/tctl.go:182
DEBU [CLIENT]    HTTPS client init(proxyAddr=teleport.example.com:443, insecure=false) client/weblogin.go:303
DEBU             Attempting to connect using reverse tunnel address teleport.example.com:3024. common/tctl.go:215
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:221
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:136
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:221
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:136
DEBU [CLIENT]    Validated host teleport.example.com:3024. client/keyagent.go:98
DEBU [CLIENT]    Validated host teleport.example.com:3024. client/keyagent.go:98
User "gus" has been reset. Share this URL with the user to complete password reset, link is valid for 8h:
https://teleport.example.com:443/web/reset/8a21795a9a84304ffcc3f99a6c8f1b4d

NOTE: Make sure teleport.example.com:443 points at a Teleport proxy which users can access.
```

I clicked this URL and it opened in my default system browser (Safari). I entered the password twice, then clicked the "Change Password" button. I got an error:

<img width="743" alt="Screenshot 2021-01-25 at 10 07 23" src="https://user-images.githubusercontent.com/897821/105722588-34784980-5efc-11eb-8fd7-5402ba520c6f.png">

The same thing also happens when trying to log in using Safari:

<img width="497" alt="Screenshot 2021-01-25 at 11 04 43" src="https://user-images.githubusercontent.com/897821/105723515-41496d00-5efd-11eb-991d-c2c57a2de94c.png">

**What you expected to happen**: Clicking the "Change Password" button should prompt me to tap my U2F key, and the U2F key should flash and wait for input.

I'm pretty sure Safari has supported U2F keys since Safari 13. Yubikey lists it as a supported browser: https://www.yubico.com/works-with-yubikey/catalog/safari/

If a browser doesn't support U2F keys, we should print a warning to use a supported browser.

**How to reproduce it (as minimally and precisely as possible)**: See above.

Auth server config:

```yaml
auth_service:
  enabled: yes
  license_file: /var/lib/license/license.pem
  authentication:
    type: github
    second_factor: u2f
    u2f:
      app_id: https://teleport.example.com
      facets:
        - teleport.example.com:443
        - https://teleport.example.com:443
        - https://teleport.example.com
  public_addr: teleport-auth:3025
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
  tokens:
    - "proxy:<redacted>"  
```

Proxy server config:

```yaml
proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.example.com:443
  listen_addr: 0.0.0.0:3023
  kube_listen_addr: 0.0.0.0:3026
  ssh_public_addr: teleport.example.com:3023
  tunnel_listen_addr: 0.0.0.0:3024
  tunnel_public_addr: teleport.example.com:3024
  https_keypairs:
  - key_file: /var/lib/certificates/tls.key
    cert_file: /var/lib/certificates/tls.crt
```

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v5.1.0 git:v5.1.0-0-g46679fb34 go1.15.5`
- Tsh version (use `tsh version`): `Teleport v5.1.0 git:v5.1.0-0-g46679fb34 go1.16beta1`
- OS (e.g. from `/etc/os-release`):
```
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Cloud

**Browser environment**

- Browser Version (for UI-related issues): 
<img width="272" alt="Screenshot 2021-01-25 at 10 56 55" src="https://user-images.githubusercontent.com/897821/105722452-101c6d00-5efc-11eb-85e4-2ca61e00a843.png">
