### ISSUE TITLE
Allow adding attributes like BYPASSRLS to postgres auto user provisioning feature

### ISSUE THREAD

**Issue by akshaynshah** [gravitational/teleport#54194]
What would you like Teleport to do?
https://goteleport.com/docs/enroll-resources/database-access/auto-user-provisioning/postgres/ the automatic JiT user that this creates, there is no way to assign the BYPASSRLS attribute to it.

There should be a way to define attributes of the automatically created user especially for attributes like BYPASSRLS which cannot be inherited downstream by using let's say the teleport-auto-user group (postgres role) even if we attach the BYPASSRLS attribute manually to teleport-auto-user the automatically created user does not inherit this since this attribute cannot be inherited

Best would be to define the attributes in the teleport config yaml that needs to be added to the automatically created postgres user by teleport-admin

What problem does this solve?
Unable to use the postgresql auto user provisioning when the user needs to bypass RLS for RLS enabled tables

If a workaround exists, please include it.
If anyone has any workarounds to get this done with existing teleport release please let me know.

**Comment by milos-teleport** [comment]
Hi,

The best solution is to have your RLS policies set so the RLS can be bypassed by the trusted role(s) - for example the ones you associate to a user through Teleport RBAC.

If `BYPASSRLS` is a must, then you can have your DBA create roles with `BYPASSRLS` and assign those roles to your Teleport users using the Teleport role RBAC. For example:

```yaml
kind: role
version: v7
metadata:
  name: auto-db-users-superadmin
spec:
  options:
    create_db_user_mode: keep
  allow:
    db_labels:
      "*": "*"
    db_names:
    - "*"
    db_roles:
    - super_admin_role # PG role which has the `BYPASSRLS` permission
```
