### ISSUE TITLE
teleport-slack-plugin chart should expose `annotations.serviceAccount`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#54384]
## What would you like Teleport to do?

The `teleport-slack-plugin` chart supports a built-in `tbot` for getting an identity. It isn't possible to use this with EKS IRSA, though, as it doesn't expose a way to set the IRSA annotation on the `ServiceAccount` used by `tbot` (or a way to provide your own `ServiceAccount` with the annotations already set)

This would be useful for situations where people cannot use the `kubernetes` join method due to https://github.com/gravitational/teleport/issues/37183

This could probably be applied to all plugin charts with built-in `tbot`s.

## What problem does this solve?

Easier deployment of plugins in EKS clusters.

## If a workaround exists, please include it.

Deploy your own `tbot` creating a `kubernetes_secret` output with a custom `ServiceAccount`, and plumb it through to the Slack bot:

```yaml
teleport:
  address: teleport.example.com
  identitySecretName: slack-plugin-identity-output # replace with Kubernetes secret name
  identitySecretPath: identity # needed to pick up identity file
```
