### ISSUE TITLE
Using wildcard for a role causes reason requirement to be ignored.

### ISSUE THREAD

**Issue by phall-teleport** [gravitational/teleport#54397]
Expected behavior:
```
    request:
      reason:
        mode: required
      roles:
      - critical-*
```
should cause a request for any roles matching critical-* to require a reason

Current behavior:
The request will submit without a reason being required. Workaround is to list off any matching roles (instead of critical-*, critical-access) etc.

Bug details:
- Teleport version
   17.4.6
- Recreation steps
  Create a role with the above yaml and then try doing a access request that would be affected by it. 
- Debug logs
