### ISSUE TITLE
Slack Plugin -  Access List not implemented on this auth server

### ISSUE THREAD

**Issue by RonanQuigley** [gravitational/teleport#54987]
# Teleport bug report

## Expected Behaviour

If I am on the community or APGL licensed edition of teleport, the slack access plugin should not crash in the event that the access list feature is unsupported.

## Current Behaviour

The slack plugin crashes after 15 seconds or so due to this task that errors out:

https://github.com/gravitational/teleport/blob/5bca9f408ced1fc45de1080f61d6a7f24feffd45/integrations/access/accesslist/app.go#L159

The timing of the error is variable due to a jitter library being used under the hood.

My current workaround is to just comment out the access list feature and rebuild the slack plugin from source. That's this line:

https://github.com/gravitational/teleport/blob/5bca9f408ced1fc45de1080f61d6a7f24feffd45/integrations/access/slack/bot.go#L102

## Bug Details

Teleport version: 17.4.8

Judging by this [code comment](https://github.com/gravitational/teleport/blob/5bca9f408ced1fc45de1080f61d6a7f24feffd45/tool/tsh/common/tsh.go#L5774) and your [feature list](https://goteleport.com/docs/feature-matrix/) matrix, I think the reason this issue happens is because it's assumed that the access list feature is supported no matter what variant of teleport (enterprise, community etc.) is being used. If I am wrong and this is not a bug then feel free to correct me and explain why.

If this is indeed a bug, I am happy to submit a PR to fix this.

## Recreation steps

I have the following repro:

### Files required

generate-cert.sh

```sh
# Step 1: Generate a CA key and certificate (for signing)
mkdir ./certs
openssl genrsa -out ./certs/ca.key 2048
openssl req -x509 -new -nodes -key ./certs/ca.key \
    -sha256 -days 1825 -out ./certs/ca.crt \
    -subj "/CN=Teleport Local CA/O=Teleport/OU=Slack Plugin"

# Step 2: Generate a server private key
openssl genrsa -out ./certs/localhost.key 2048

# Step 3: Create a certificate signing request (CSR) for the server
openssl req -new -key ./certs/localhost.key \
    -out ./certs/localhost.csr \
    -subj "/CN=localhost/O=Teleport/OU=Slack Plugin"

# Step 4: Create a config file for the certificate with subject alternative names
cat > /tmp/localhost_cert.conf << EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[v3_req]
keyUsage = keyEncipherment, dataEncipherment, digitalSignature
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
EOF

# Step 5: Sign the CSR with the CA key to generate the server certificate
openssl x509 -req -in ./certs/localhost.csr \
    -CA ./certs/ca.crt \
    -CAkey ./certs/ca.key \
    -CAcreateserial \
    -out ./certs/localhost.crt \
    -days 825 \
    -sha256 \
    -extfile /tmp/localhost_cert.conf -extensions v3_req

# Set appropriate permissions
chmod 600 ./certs/*.key
chmod 644 ./certs/*.crt ./certs/*.csr

# Clean up the temp file
rm /tmp/localhost_cert.conf
```

teleport-slack.toml:

```toml
[teleport]
addr = "localhost:3025"
 
client_key = "/var/lib/teleport/plugins/slack/slack.key" # Teleport TLS secret key
client_crt = "/var/lib/teleport/plugins/slack/slack.crt" # Teleport TLS certificate
root_cas = "/var/lib/teleport/plugins/slack/slack.cas"   # Teleport CA certs

[slack]
token = "{ENTER VALID TOKEN HERE}"

[role_to_recipients]
# this is the slack channel we'll route all messages to
"*" = ""

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/slack.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```

teleport-slack.yaml

```yaml
kind: role
metadata:
  name: access-slack
spec:
  allow:
    rules:
        # even if access_list is removed the access list error still happens
      - resources: ['access_request', 'access_list']
        verbs: ['list', 'read', 'update']
version: v7
---
kind: user
metadata:
  name: access-slack
spec:
  roles: ['access-slack']
version: v2
```

teleport.yaml

```yaml
version: v3
teleport:
  nodename: localhost
  data_dir: /var/lib/teleport
  join_params:
    token_name: ""
    method: token
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: localhost
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: localhost:443
  https_keypairs: 
  - key_file: /var/lib/teleport/localhost.key
    cert_file: /var/lib/teleport/localhost.crt
  https_keypairs_reload_interval: 0s
  acme: {}
```

### generate the config

Run the below script to generate the certs in the `certs` directory:

```sh
./generate-cert.sh
```

then do...

```sh
docker run --hostname localhost --rm --entrypoint=/usr/local/bin/teleport \
 -v `pwd`/certs/localhost.crt:/var/lib/teleport/fullchain.pem \
 -v `pwd`/certs/localhost.key:/var/lib/teleport/privkey.pem \
 public.ecr.aws/gravitational/teleport-distroless:17.4.8 configure \
 --cluster-name=localhost \
 --public-addr=localhost:443 \
 --cert-file=/var/lib/teleport/fullchain.pem \
 --key-file=/var/lib/teleport/privkey.pem
```

### run teleport server

```sh
docker rm -f local-teleport
docker run --name=local-teleport --net=host --hostname localhost -e SSL_CERT_FILE=/var/lib/teleport/ca.crt \
 -v `pwd`/teleport.yaml:/etc/teleport/teleport.yaml \
 -v `pwd`/certs:/var/lib/teleport \
 -v `pwd`/teleport-slack.yaml:/etc/teleport/teleport-slack.yaml \
 public.ecr.aws/gravitational/teleport-distroless:17.4.8
```

### create the slack bot user

```sh
docker exec local-teleport tctl create -f /etc/teleport/teleport-slack.yaml --auth-server=localhost:3025
```

### sign the cert

```sh
docker exec local-teleport tctl auth sign --user=access-slack --format=tls --ttl=48h --out /tmp/slack
```

### grab the certs

```sh
docker cp local-teleport:/tmp ./slack-certs
```

### Get teleport token

Add a valid teleport token to your `/etc/teleport-slack.toml` below:

```toml
[slack]
token = "{TOKEN}"
```

### Run the slack plugin (note, I moved the certs for the plugin to /var/lib/teleport/plugins/slack/)

```sh
teleport-slack start  --config <path_to_slack_toml>
```

## Debug logs

A few moments after startup  you will be presented with the below stack trace error.

```
INFO   Starting Teleport Access Slack Plugin 17.4.8: teleport-slack/main.go:93
INFO   Access list monitor is running accesslist/app.go:121
INFO   Plugin is ready common/app.go:159
INFO   Looking for Access List Review reminders accesslist/app.go:149
ERRO   access list endpoint is not implemented on this auth server, so the access list app is ceasing to run. accesslist/app.go:159
ERRO   Terminating with fatal error [1]... error:[
ERROR REPORT:
Original Error: *interceptors.RemoteError unknown service teleport.accesslist.v1.AccessListService
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/accesslist/accesslist.go:70 github.com/gravitational/teleport/api/client/accesslist.(*Client).ListAccessLists
	github.com/gravitational/teleport/integrations/access/common/config.go:64 github.com/gravitational/teleport/integrations/access/common.(*wrappedClient).ListAccessLists
	github.com/gravitational/teleport/integrations/access/accesslist/app.go:156 github.com/gravitational/teleport/integrations/access/accesslist.(*App).remindIfNecessary
	github.com/gravitational/teleport/integrations/access/accesslist/app.go:132 github.com/gravitational/teleport/integrations/access/accesslist.(*App).run
	github.com/gravitational/teleport/integrations/lib/process.go:234 github.com/gravitational/teleport/integrations/access/slack.Bot.SupportedApps.NewApp.NewServiceJob.func2
	github.com/gravitational/teleport/integrations/lib/process.go:255 github.com/gravitational/teleport/integrations/lib.(*serviceJob).DoJob
	github.com/gravitational/teleport/integrations/lib/process.go:101 github.com/gravitational/teleport/integrations/lib.NewProcess.func2.1
	runtime/asm_amd64.s:1700 runtime.goexit
User Message: unknown service teleport.accesslist.v1.AccessListService] lib/bail.go:34
```

## Related Code Changes

Potentially this? 

https://github.com/gravitational/teleport/pull/36228
