### ISSUE TITLE
Roles should not inadvertently grant access

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5513]
### Description

**What happened**:

When creating a role that only specifies node labels, application and kubernetes access are fully granted.

Take this short example role:

```yaml
version: v3
kind: role
metadata:
  name: qa
spec:
  allow:
    node_labels:
      'account_type': 'QA'
```

When this is created via `tctl create -f qa.yaml`, it results in the following `tctl get roles/qa`:

```yaml
kind: role
metadata:
  id: 1612814108898420391
  name: qa
spec:
  allow:
    app_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    node_labels:
      account_type: QA
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```

Since there was no initial mention of the app nor kube services, this could lead to a situation where a user with this QA role will be allowed to access apps/kube clusters when it was only intended for her to get access to nodes with the `account_type: QA` label.

**What you expected to happen**:

Teleport should follow the concept of least privileged access. no access should be granted to kubernetes clusters nor applications.

**How to reproduce it (as minimally and precisely as possible)**:

Copy/paste the example yaml given above and run the commands above.

### Environment

Environment 1

- Teleport version (use `teleport version`): `Teleport Enterprise v5.0.0 git:v5.0.0-0-gac4971801 go1.15.5`
- Tsh version (use `tsh version`): `Teleport v5.0.0 git:v5.0.0-0-gac4971801 go1.15.5`
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

Environment 2

- Teleport version (use `teleport version`): `Teleport Enterprise v5.1.2 git:v5.1.2-0-g822d10b44 go1.15.5`
- Tsh version (use `tsh version`): `Teleport v5.1.2 git:v5.1.2-0-g822d10b44 go1.15.5`
- OS (e.g. from `/etc/os-release`): quay.io/gravitational/teleport-ent:5.1.2 container image on EKS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

AWS

**Browser environment**

N/A

**Relevant Debug Logs If Applicable**

N/A
