### ISSUE TITLE
Intermittent availability of Recordings and Audit data - Kubernetes HA deployment

### ISSUE THREAD

**Issue by pankajpandey9** [gravitational/teleport#5518]
### Description

**What happened**: Session Recordings does not show after refreshing the Teleport UI. However, may come up after refreshing multiple times

**What you expected to happen**: Recording and Audit data should be available everytime the page is refreshed

**How to reproduce it (as minimally and precisely as possible)**: Increase the number of Pods from 1 to 2 for Auth and Proxy

### Environment
- Teleport version (use `teleport version`): quay.io/gravitational/teleport-ent:5.0
- Tsh version (use `tsh version`): 5.0.2
- OS (e.g. from `/etc/os-release`): Kubernetes 1.18.2

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): 
    Kubernetes on-premise Rancher Cluster 
    3 Worker Nodes
    2 Pods for Auth & 2 for Proxy
    etcd cluster for Auth data
    IBM Cloud Object Store buckets for Recordings
    default values for storage - NFS PVC for both the Proxy pods 
    Using NodePorts with Extenal HAProxy TCP loadbalancer

**Browser environment**: Firefox on RHEL

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by awly** [comment]
@pankajpandey9 could you also provide a (redacted) `teleport.yaml` for the auth server?

**Comment by pankajpandey9** [comment]
Here is the output from one of the Auth pods.
```
teleport:
  pid_file: /var/run/teleport.pid
  data_dir: /var/lib/teleport
  # storage settings included
  log:
    output: stderr
    severity: INFO
  storage:
    audit_sessions_uri: s3://<IBM COS bucket>
    credentials_path: /root/.aws/credentials
    etcd_max_client_msg_size_bytes: 15728640
    insecure: false
    password_file: /mnt/secrets/etcd-cred.txt
    peers:
    - https://etcd-0.etcd-headless.etcd.svc.cluster.local:2379
    - https://etcd-1.etcd-headless.etcd.svc.cluster.local:2379
    - https://etcd-2.etcd-headless.etcd.svc.cluster.local:2379
    prefix: /teleport-rke/
    tls_ca_file: /var/lib/ca-certs/ca.crt
    tls_cert_file: /var/lib/ca-certs/tls.crt
    tls_key_file: /var/lib/ca-certs/tls.key
    type: etcd
    username: teleport-rke

  connection_limits:
    max_connections: 1000
    max_users: 250
auth_service:
  enabled: true
  license_file: /var/lib/license/license-enterprise.pem
  authentication:
    second_factor: "off"
    type: oidc
  tokens:
    - proxy,node:<some key>
    - trusted_cluster:<some key1>

  public_addr: dev-ocplb.<domain_name>>:3025
  cluster_name: dev-ocplb.<doamin_name>
  listen_addr: 0.0.0.0:3025
  client_idle_timeout: never
  disconnect_expired_cert: false
  keep_alive_interval: 5m
  keep_alive_count_max: 3

ssh_service:
  enabled: false

proxy_service:
  enabled: false
```
