### ISSUE TITLE
Provide inline method for google workspace (formerly gsuite) service account JSON contents

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5523]
### Feature Request
Provide the ability to specify the `google_service_account_uri` contents inline.  Currently a file must be available to the auth service. 

Ex:
```yaml
kind: oidc
metadata:
  name: googleworkspace
spec:
  google_service_account_uri: |
     {
      ....
  claims_to_roles:
  - claim: groups
    roles:
    - admin
    value: <gsuite-group-email>
  client_id: <GSUITE_CLIENT_ID>.apps.googleusercontent.com
  client_secret: <OAUTH_CLIENT_SECRET>
  display: Google
  google_admin_email: <GSUITE_EMAIL>

  issuer_url: https://accounts.google.com
  redirect_url: https://<cluster-url>:3080/v1/webapi/oidc/callback
```

### Motivation
Within cloud users cannot load and map  to a JSON file.  This will allow them to specify it inline.

### Who's it for?
Cloud
