### ISSUE TITLE
Operator can't create resources

### ISSUE THREAD

**Issue by creack** [gravitational/teleport#55309]
Trying to get resources created by the operator fails in 18.0.1-alpha.1. Works as expected in 17.

Deployed using helm with:

```yaml
clusterName: tp18-1
proxyListenerMode: multiplex
operator:
  enabled: true
  image: public.ecr.aws/gravitational-staging/teleport-operator
```

using resources from the docs:

```yaml
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: manager
spec:
  allow:
    rules:
      - resources: ['user', 'role']
        verbs: ['list','read']
      - resources: ['session', 'event']
        verbs: ['list', 'read']
---
apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: engineer
spec:
  allow:
    logins: ['root', 'ubuntu', '{{internal.logins}}']
    node_labels:
      'env': ['test', 'staging']
```

Logs from the operator deployment:

```
E0531 01:15:36.986763       1 reflector.go:200] "Failed to watch" err="failed to list resources.teleport.dev/v1, Kind=TeleportAutoupdateVersionV1: teleportautoupdateversionsv1.resources.teleport.dev is forbidden: User \"system:serviceaccount:default:teleport-cluster-operator\" cannot list resource \"teleportautoupdateversionsv1\" in API group \"resources.teleport.dev\" in the namespace \"default\"" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285" type="resources.teleport.dev/v1, Kind=TeleportAutoupdateVersionV1"
E0531 01:15:37.209268       1 reflector.go:200] "Failed to watch" err="failed to list resources.teleport.dev/v1, Kind=TeleportAutoupdateConfigV1: teleportautoupdateconfigsv1.resources.teleport.dev is forbidden: User \"system:serviceaccount:default:teleport-cluster-operator\" cannot list resource \"teleportautoupdateconfigsv1\" in API group \"resources.teleport.dev\" in the namespace \"default\"" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285" type="resources.teleport.dev/v1, Kind=TeleportAutoupdateConfigV1"
...
{"timestamp":"2025-05-31T01:17:20Z","level":"error","message":"Could not wait for Cache to sync","controller":"teleportuser","controllerGroup":"resources.teleport.dev","controllerKind":"TeleportUser","err":"failed to wait for teleportuser caches to sync kind source: *unstructured.Unstructured: timed out waiting for cache to be synced for Kind *unstructured.Unstructured"}
...
{"timestamp":"2025-05-31T01:17:20Z","level":"error","message":"error received after stop sequence was engaged","err":"failed to wait for teleportrolev6 caches to sync kind source: *unstructured.Unstructured: timed out waiting for cache to be synced for Kind *unstructured.Unstructured"}
{"timestamp":"2025-05-31T01:17:20Z","level":"error","message":"error received after stop sequence was engaged","err":"failed to wait for teleportuser caches to sync kind source: *unstructured.Unstructured: timed out waiting for cache to be synced for Kind *unstructured.Unstructured"}
{"timestamp":"2025-05-31T01:17:20Z","level":"error","message":"error received after stop sequence was engaged","err":"failed to wait for teleportopensshserverv2 caches to sync kind source: *unstructured.Unstructured: timed out waiting for cache to be synced for Kind *unstructured.Unstructured"}
...
{"timestamp":"2025-05-31T01:17:20Z","level":"error","message":"problem running manager","logger":"setup","err":"failed to wait for teleportrole caches to sync kind source: *unstructured.Unstructured: timed out waiting for cache to be synced for Kind *unstructured.Unstructured"}
```
