### ISSUE TITLE
Unable to join Node using jwks kubernetes token

### ISSUE THREAD

**Issue by creack** [gravitational/teleport#55312]
I was not able to get a node to join Teleport using the kubernetes jwks method on 18.0.0-alpha.1.

Tried from EKS with auth running within the cluster, from EKS with auth running outside, from Kind with auth running outside.

Error on the joiner side:

```
ERROR REPORT:
Original Error: trace.aggregate rpc error: code = Unknown desc = reviewing kubernetes token with static_jwks
        validating jwt signature
                go-jose/go-jose: unsupported key type/format
Stack Trace:
        github.com/gravitational/teleport/lib/auth/join/join.go:335 github.com/gravitational/teleport/lib/auth/join.Register
        github.com/gravitational/teleport/lib/service/connect.go:445 github.com/gravitational/teleport/lib/service.(*TeleportProcess).firstTimeConnect
        github.com/gravitational/teleport/lib/service/connect.go:220 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect
        github.com/gravitational/teleport/lib/service/connect.go:193 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService
        github.com/gravitational/teleport/lib/service/connect.go:86 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService
        github.com/gravitational/teleport/lib/service/service.go:3295 github.com/gravitational/teleport/lib/service.(*TeleportProcess).RegisterWithAuthServer.func1
        github.com/gravitational/teleport/lib/service/supervisor.go:581 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
        github.com/gravitational/teleport/lib/service/supervisor.go:307 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
        runtime/asm_amd64.s:1700 runtime.goexit
User Message: rpc error: code = Unknown desc = reviewing kubernetes token with static_jwks
        validating jwt signature
                go-jose/go-jose: unsupported key type/format] service/connect.go:102
```

Error on the auth/proxy side:

```
2025-05-30T21:40:42.143-06:00 WARN [AUTH]      Failure to join cluster occurred error:[
ERROR REPORT:
Original Error: *errors.errorString go-jose/go-jose: unsupported key type/format
Stack Trace:
        github.com/gravitational/teleport/lib/kube/token/validator.go:300 github.com/gravitational/teleport/lib/kube/token.ValidateTokenWithJWKS
        github.com/gravitational/teleport/lib/auth/join_kubernetes.go:64 github.com/gravitational/teleport/lib/auth.(*Server).checkKubernetesJoinRequest
        github.com/gravitational/teleport/lib/auth/join.go:271 github.com/gravitational/teleport/lib/auth.(*Server).RegisterUsingToken
        github.com/gravitational/teleport/lib/joinserver/joinserver.go:386 github.com/gravitational/teleport/lib/joinserver.(*JoinServiceGRPCServer).RegisterUsingToken
        github.com/gravitational/teleport/api@v0.0.0/client/proto/joinservice.pb.go:1439 github.com/gravitational/teleport/api/client/proto._JoinService_RegisterUsingToken_Handler.func1
        github.com/gravitational/teleport/lib/auth/middleware.go:558 github.com/gravitational/teleport/lib/auth.(*Middleware).withAuthenticatedUserUnaryInterceptor
        google.golang.org/grpc@v1.71.0/server.go:1217 google.golang.org/grpc.getChainUnaryHandler.func1
        github.com/gravitational/teleport/lib/limiter/limiter.go:152 github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptors.(*Limiter).UnaryServerInterceptorWithCustomRate.func1
        google.golang.org/grpc@v1.71.0/server.go:1217 google.golang.org/grpc.getChainUnaryHandler.func1
        github.com/gravitational/teleport/api@v0.0.0/metadata/metadata.go:76 github.com/gravitational/teleport/api/metadata.UnaryServerInterceptor
        google.golang.org/grpc@v1.71.0/server.go:1217 google.golang.org/grpc.getChainUnaryHandler.func1
        github.com/gravitational/teleport/api@v0.0.0/utils/grpc/interceptors/errors.go:76 github.com/gravitational/teleport/api/utils/grpc/interceptors.GRPCServerUnaryErrorInterceptor
        google.golang.org/grpc@v1.71.0/server.go:1217 google.golang.org/grpc.getChainUnaryHandler.func1
        github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.1.0/interceptors/server.go:22 github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptors.(*ServerMetrics).UnaryServerInterceptor.U
naryServerInterceptor.func2
        google.golang.org/grpc@v1.71.0/server.go:1217 google.golang.org/grpc.getChainUnaryHandler.func1
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.59.0/interceptor.go:316 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterce
ptor.func1
        google.golang.org/grpc@v1.71.0/server.go:1208 google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1
        github.com/gravitational/teleport/api@v0.0.0/client/proto/joinservice.pb.go:1441 github.com/gravitational/teleport/api/client/proto._JoinService_RegisterUsingToken_Handler
        google.golang.org/grpc@v1.71.0/server.go:1405 google.golang.org/grpc.(*Server).processUnaryRPC
        google.golang.org/grpc@v1.71.0/server.go:1815 google.golang.org/grpc.(*Server).handleStream
        google.golang.org/grpc@v1.71.0/server.go:1035 google.golang.org/grpc.(*Server).serveStreams.func2.1
        runtime/asm_arm64.s:1223 runtime.goexit
User Message: reviewing kubernetes token with static_jwks
        validating jwt signature
                go-jose/go-jose: unsupported key type/format] host_id:7d5bf08f-b09b-4c9b-a689-c8f4d7fcfc9c node_name:node4 remote_addr:100.110.41.56 role:Instance auth/join.go:150
2025-05-30T21:40:42.143-06:00 INFO  emitting audit event event_type:instance.join fields:"map[addr.remote:100.110.41.56 cluster_name:odrade.gc.devteleport.com code:TJ002E ei:0 error:reviewing kubernetes to
ken with static_jwks\n\tvalidating jwt signature\n\t\tgo-jose/go-jose: unsupported key type/format event:instance.join host_id:7d5bf08f-b09b-4c9b-a689-c8f4d7fcfc9c node_name:node4 role:Instance success:fal
se time:2025-05-31T03:40:42.144Z token_expires:0001-01-01T00:00:00Z trace.component:audit uid:73cba5cd-c03f-4a95-ad25-0a71c6bc5c4f]" events/emitter.go:287
```

Trying on v17 also fails with a different error, complaining about invalid `aud`.

Getting the jwks using: `kubectl get --raw /openid/v1/jwks | pbcopy`

Token:

```
kind: token
version: v2
metadata:
  name: jwks
spec:
  roles: [Node]
  join_method: kubernetes
  kubernetes:
    type: static_jwks
    static_jwks:
      jwks: |
        {"keys":[{"use":"sig","kty":"RSA","kid":"jpQSXpc3C8ik8uKqUhYIr3QJbzn-0cSMjjCXeVBSVcw","alg":"RS256","n":"upYaR_OBS9MhWUOkIkTfN65QRMWl9bYIy2FjdH2CVV0puJFP3r9zi2lWT41ghWHf6_kEa-BPI3-XO98zahIMDJF_1f1DWKvakrNs7L0vvmldsw99UMrFxCOpa3nNiiCcuIiuzxWVWxODwpT3oE9VNiMt-BXcs6m25__4BDP7izAP5r-ieU9opg0fhbrkQaRdh4TvfmRfWiFr2UO5VFpPBtj9d6v8SlSDCtVNcvEl9e3PqeWqPGyaPPXVCitykA_5cenrweUkhvdf_Gtns5g3v9JewgVMgPu6c1AfMNzVdWNdeV_pnoTj4vzXqMnmG-2FQhptOM1DXmVQ5NztCPSBew","e":"AQAB"}]}
    # allow specifies the rules by which the Auth Service determines if the node
    # should be allowed to join.
    allow:
      - service_account: "default:teleport-node"
```

Kubernetes resources to setup the service account and start a node

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teleport-node
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teleport-node-joiner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teleport-node-joiner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teleport-node-joiner
subjects:
- kind: ServiceAccount
  name: teleport-node
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport-node
  namespace: default
  labels:
    app: teleport-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleport-node
  template:
    metadata:
      labels:
        app: teleport-node
    spec:
      serviceAccountName: teleport-node
      containers:
      - name: teleport
        image: ubuntu
        tty: true

```

Teleport config within the pod:

```
version: v3

teleport:
  nodename: node14
  data_dir: /root/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  proxy_server: tp18-1.gc.devteleport.com:443
  join_params:
    method: kubernetes
    token_name: jwks

ssh_service:
  enabled: "yes"

auth_service:
  enabled: "no"

proxy_service:
  enabled: "no"
```

Note that a similar setup with a `in_cluster` token works as expected.
