### ISSUE TITLE
Interesting behavior observed with reviewer role preview_as_role configuration functionality

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#55421]
Expected behavior:
The preview_as_roles setting should permit the reviewer to preview human friendly details about resources accessible by roles listed when reviewing resource access request. Human friendly meaning the resource name and not the UUID of the resource. 

```
review_requests:
      # the reviewer can view and approve or deny access requests for any roles
      # listed here
      roles: ['dbadmin']
      # the reviewer can preview details about resources accessible by any roles
      # listed in preview_as_roles when reviewing Resource Access Requests
      preview_as_roles: ['dbadmin']
```
Current behavior:

In some scenarios the functionality of this setting behaves in a questionable manner. Customer requesting review  of this functionality. 

Scenario 1: 
With `preview_as_roles` set to "*",  only UUIDs are visible. Teleport does not appear to support globing with this setting. Note that if `preview_as_roles` is not set in the reviewer role, the human friendly names are visible. 

```
    review_requests:
      preview_as_roles: 
      - "*"
```

Scenario 2: 
With `preview_as_roles` set to two roles, the reviewer will see the user friendly names for nodes that these roles do not grant access to. For example, with roles `editor` and `auditor` applied, offering no resource permissions by default, the human friendly names are visible. 

```
    review_requests:
      preview_as_roles:
      - editor
      - auditor
```

Scenario 3: 
With preview_as_roles set to a real role and a non existent role, UUIDs are visible even when requesting access to a resource with the real role. For example, roles `access` and `fake-role` are applied. Role fake-role is not defined in the Teleport Cluster. 

```
    review_requests:
      preview_as_roles:
      - access
      - fake-role
```

Requester Role 

```
kind: role
metadata:
  name: requester
spec:
  allow:
    request:
      search_as_roles:
      - access
  deny: {}  
version: v5
```

Bug details:
- Teleport 17.4.10
- Recreation steps 
    - With test user account make access request for individual resources using the requester role. 
    - Shared reviewer role `review_request` settings for each scenario
    - Apply these settings to reviewer role and examine access request
