### ISSUE TITLE
[Question] New cluster won't function

### ISSUE THREAD

**Issue by dudeisbrendan03** [gravitational/teleport#5575]
So I have 5 leafs connecter to 1 root.

Each leaf is it's own independent infrastructure, with the root there to make maintaining each one easier.
Deploying a later one for some reason I keep getting hit by this same error, I haven't configured it differently as far as I'm aware.
For some reason it works fine in the web app, but not with tsh.

![netdiag1](https://user-images.githubusercontent.com/6009600/108005356-69a22400-6ff0-11eb-8e20-900ee52f17af.png)

![image](https://user-images.githubusercontent.com/6009600/108004805-c997cb00-6fee-11eb-9ddc-4a3cd52a9759.png)

- TELEPORT_CLUSTER_A (https://teleport.somewhere)
- TELEPORT_CLUSTER_B (https://teleport.elsewhere) - the one I am having issues with
- TELEPORT_CLUSTER_C (https://teleport.awesome) - a random other client configured the same, functional

All clusters have valid SSL certificates from Let's Encrypt

I connect to TELEPORT_CLUSTER_A (the root)
```
tsh login TELEPORT_CLUSTER_A

...
> Profile URL:        https://teleport.somewhere:3080
  Logged in as:       brendantdj
  Cluster:            TELEPORT_CLUSTER_A
  Roles:              admin*
  Logins:             someperson
  Kubernetes:         disabled
  Valid until:        2021-02-16 00:42:14 +0000 GMT [valid for 18m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```
All is going well, now I check what clusters are available

```
tsh clusters

Cluster Name       Status
------------------ -------
TELEPORT_CLUSTER_A online
TELEPORT_CLUSTER_B online
TELEPORT_CLUSTER_C online
```
The cluster appears to be online, so I swap over to it 

```
tsh login TELEPORT_CLUSTER_B

> Profile URL:        https://teleport.somewhere:3080
  Logged in as:       brendantdj
  Cluster:            TELEPORT_CLUSTER_B
  Roles:              admin*
  Logins:             someperson
  Kubernetes:         disabled
  Valid until:        2021-02-16 00:42:14 +0000 GMT [valid for 18m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

Now list what nodes are available
```
tsh ls

error: Get "https://teleport.cluster.local/v2/namespaces/default/nodes?skip_validation=true": x509: certificate signed by unknown authority
```

I can't figure out why it's https://teleport.cluster.local instead of https://teleport.elsewhere

```yaml
teleport:
  nodename: TELEPORT_NODE_1
  data_dir: /var/lib/teleport
  auth_token: abc
  auth_servers:
  - 127.0.0.1:3025
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: "yes"
  cluster_name: "TELEPORT_CLUSTER_B"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:abc
  enabled: "yes"
  labels:
    env: production
    type: soc
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  - name: arch
    command: [uname, -p]
    period: 1h0m0s
  pam:
    enabled: true
    service_name: "teleport"
    use_pam_auth: false
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: teleport.elsewhere
  https_key_file: /etc/letsencrypt/live/teleport.elsewhere/privkey.pem
  https_cert_file: /etc/letsencrypt/live/teleport.elsewhere/fullchain.pem
```

All the other leafs work fine

```
tsh login TELEPORT_CLUSTER_C
...
tsh ls
(list of nodes)
```

_Originally posted by @dudeisbrendan03 in https://github.com/gravitational/teleport/discussions/5574_
