### ISSUE TITLE
Role editor does not enforce required labels

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#56260]
Expected behavior:

If I try to edit a role and save it without specifying required fields, I should get an error and the role should not be updated.
For example, here I am edting a role to grant db resource access to it, but I haven't added any `db_labels` to the role:

![Image](https://github.com/user-attachments/assets/cacdcbac-3d38-4cab-8a3d-20e9ce4ea91e)

Current behavior:

Required fields are allowed to be left blank. The role is saved with the fields omitted.
I end up with this role spec, which still grants no db access because `db_labels` is not set:

```yaml
kind: role
metadata:
  description: A role which grants nothing
  name: noallow
  revision: e4f42615-289f-4cb2-a6a4-9c06916d7a3c
spec:
  allow:
    db_names:
    - '{{internal.db_names}}'
    db_roles:
    - '{{internal.db_roles}}'
    db_users:
    - '{{internal.db_users}}'
  deny: {}
  options:
    cert_format: standard
    create_db_user: true
    create_db_user_mode: 3
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      desktop: true
    ssh_file_copy: true
version: v5
```

Bug details:
- Teleport version: 18.0.0-alpha.4
- Recreation steps: create or edit a role, give it resource access to databases, don't fill in field marked with red asterisks, click "save".

This confused a customer today because they thought they had granted db access, but in fact had only filled in the `db_service_labels` field using the editor.
The distinction between `db_labels` and `db_service_labels` is subtle and easy to miss especially for new users of Teleport, so it is very important that we don't allow the user to skip filling in required fields. Had they been stopped, they might have wondered "what's the difference, I thought I filled in the labels" and then read the tooltips to figure it out before proceeding.

On that note: I strongly recommend we remove the `Database Service Labels` section and just auto-populate it as `db_service_labels: {"*":"*"}`. I have no idea what else you would want to put there. From user perspective there is only one use case where they need this: resource enrollment flows that check for a database service - in that case, the only meaningful value is to use wildcards anyway.
cc @greedy52 WDYT? I can file an enhancement ticket for this part.
