### ISSUE TITLE
chart/teleport/templates/ingress.yaml: There is no way to set ingress wildcard host

### ISSUE THREAD

**Issue by sergeysedoy97** [gravitational/teleport#5824]
### Description

**What happened**:
```
ingress:
    hosts:
        teleport.example.com:
            - /
        "*.teleport.example.com":  <-- PROBLEM
            - /
```

**What you expected to happen**:
```
ingress:
    hosts:
        - teleport.example.com
            - /
        - "*.teleport.example.com"  <-- NO PROBLEM
            - /
```
