### ISSUE TITLE
Add postgres_public_addr and mysql_public_addr to proxy config

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#5911]
### Description

Currently, database clients (`psql`, `mysql`) connect to the web proxy public address.

For example, given the following proxy configuration the database clients will be configured to connect to `teleport.example.com` after `tsh db login`:

```yaml
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  mysql_listen_addr: 0.0.0.0:3036
  public_addr: teleport.example.com:3080
```

This presents an issue when ALB is used in front of web proxy (for example, when also using ACM in AWS). Since it's a L7 load balancer that supports HTTP(s)/websockets, database client connections that work over their own wire protocols fail, for example:

```sh
➜  ~ psql "service=example user=alice dbname=test"
psql: error: received invalid response to SSL negotiation: H
```

The workaround is to either connect directly to the proxy endpoint, or point a NLB to port 3080 as well and connect to NLB when connecting to a database:

```sh
➜  ~ psql "service=example user=alice dbname=test host=nlb.teleport.example.com"
```

The issue is that in Teleport proxy config there is no way to specify this database client host override, so the proposal is to add `postgres_public_addr` and `mysql_public_addr` support this use-case, similar to `tunnel_public_addr` and `ssh_public_addr` we already have, so users would be able to do:

```yaml
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  mysql_listen_addr: 0.0.0.0:3036
  public_addr: teleport.example.com:3080
  postgres_public_addr: nlb.teleport.example.com:3080
  mysql_public_addr: nlb.teleport.example.com:3036
```
