### ISSUE TITLE
Can't access SSH node after setting up with`teleport configure` 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5917]
### Description

**What happened**:
While recording a video for Teleport 6.0.1, and after running `teleport configure` I'm able to get a running instance but my ssh_service isn't connecting? 

```yaml
# cat /etc/teleport.yaml 
teleport:
  nodename: ubuntu-s-1vcpu-1gb-intel-sfo3-01
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: calcium.asteroid.earth
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: :443
  public_addr: calcium.asteroid.earth:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: ben@goteleport.com
```

![image](https://user-images.githubusercontent.com/559288/110539267-e00ae100-80d9-11eb-9a35-fa14dd2060f6.png)

**What you expected to happen**:
The SSH service is aviaible 

### Reproduction Steps

1. Download Teleport
2. `sudo teleport configure --acme --acme-email=ben@goteleport.com --cluster-name=calcium.asteroid.earth -o /etc/teleport.yaml`
3. Start Teleport

### Server Details
- Teleport version (run `teleport version`): 6.0.1
- Server OS (e.g. from `/etc/os-release`): Ubuntu
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): DO

**Comment by robcoward** [comment]
Check the definition of the automatically created admin role. I have just come across this and found that the 'admin' role was not actually an 'all-powerful' admin, and didnt even have permissions to see the ssh server.

**Comment by benarent** [comment]
Thanks @robcoward , I was just about to put the same thing myself. 

The default role for `admin.yaml` as below. 

```yaml
kind: role
metadata:
  id: 1615324366209297575
  labels:
    migrate-v6.0: "true"
  name: admin
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
