### ISSUE TITLE
Teleport starts all services even if no config is specified

### ISSUE THREAD

**Issue by jchauncey** [gravitational/teleport#594]
So I tried to start a node with just ssh_service but for some reason it is also starting auth and proxy too. It feels like that should not happen.

**Comment by klizhentas** [comment]
@jchauncey can you show your config file?

**Comment by jchauncey** [comment]
```
ip-10-0-0-115 teleport # cat /etc/teleport/teleport.yaml
# By default, this file should be stored in /etc/teleport.yaml

# This section of the configuration file applies to all teleport
# services.
teleport:
    # nodename allows to assign an alternative name this node can be reached by.
    # by default it's equal to hostname

    # Data directory where Teleport keeps its data, like keys/users for
    # authentication (if using the default BoltDB back-end)
    data_dir: /var/lib/teleport

    # one-time invitation token used to join a cluster. it is not used on
    # subsequent starts
    auth_token: token

    # when running in multi-homed or NATed environments Teleport nodes need
    # to know which IP it will be reachable at by other nodes
    advertise_ip: publicip

    # list of auth servers in a cluster. you will have more than one auth server
    # if you configure teleport auth to run in HA configuration
    auth_servers:
        - publicip:3025

    # Teleport throttles all connections to avoid abuse. These settings allow
    # you to adjust the default limits
    connection_limits:
        max_connections: 1000
        max_users: 250

    # Logging configuration. Possible output values are 'stdout', 'stderr' and
    # 'syslog'. Possible severity values are INFO, WARN and ERROR (default).
    log:
        output: stderr
        severity: ERROR

    # Type of storage used for keys. You need to configure this to use etcd
    # backend if you want to run Teleport in HA configuration.
    storage:
        type: bolt

# This section configures the 'node service':
ssh_service:
    enabled: yes
    # IP and the port for SSH service to bind to.
    listen_addr: 0.0.0.0:3022
    # See explanation of labels in "Labeling Nodes" section below
    labels:
      location: us-east-1
      vpc: staging
      k8s: worker
      role: node
    # List (YAML array) of commands to periodically execute and use
    # their output as labels.
    # See explanation of how this works in "Labeling Nodes" section below
    commands:
    - name: hostname
      command: [/usr/bin/hostname]
      period: 1m0s
```

**Comment by klizhentas** [comment]
@jchauncey I think it's just a UX issue, try adding this:

```yaml
proxy_service:
  enabled: "no"
auth_service:
  enabled: "no"
```
