### ISSUE TITLE
Add the possibility to use variable in role *_labels

### ISSUE THREAD

**Issue by gpr** [gravitational/teleport#5973]
I want to restrict some devices to only one people, the owner, without having to create a role per user (it would be painful with a lot of users) it would be very convenient to use the variables "{{external.trait_name}}" and "{{internal.logins}}" in node_labels in order to create that generic role:

```
kind: role
version: v3
metadata:
  name: owner
spec:
  allow:
    logins: [root, '{{external.trait_name}}']
    node_labels:
      'owner': '{{external.trait_name}}'

  deny: {}
```
