### ISSUE TITLE
Custom Approvals/Dual Authorization - kubectl exec

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5986]
### What
Teams require a second person on their same team to allow kubectl exec into a pod. For example: There is a developer on Team A who needs to kubectl exec into a pod. They submit a request for access. A second developer on Team A approves their access request. The first developer kubectl execs into the pod.
If a workaround exists, please include it.

**Comment by awly** [comment]
This can be achieved with a combination of Teleport and k8s RBAC.

## k8s

First, create a k8s role to allow exec access into appropriate pods, something like:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-execer
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
```

Next, bind this role to a k8s group:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-execer
  namespace: default
subjects:
- kind: Group
  name: pod-execer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-execer
  apiGroup: rbac.authorization.k8s.io
```

## teleport

On Teleport side, create a role to represent the k8s group:

```yaml
kind: role
version: v3
metadata:
  name: pod-execer
spec:
  allow:
    kubernetes_groups: ["pod-execer"]
  deny: {}
```

And finally, use the regular dual authorization to request role `pod-execer` https://goteleport.com/teleport/docs/enterprise/workflow/
