### ISSUE TITLE
teleport unable to bind to 3025

### ISSUE THREAD

**Issue by jchauncey** [gravitational/teleport#599]
It seems that when you start teleport it expects the auth_service to be running - 

```
ip-10-0-0-115 teleport # ./teleport start --roles=node --token=e66bdb3a03946a8f66347941f7196b6f --auth-server=publicip:3025
dial tcp 10.0.0.115:3025: getsockopt: connection refused
```

**Comment by jchauncey** [comment]
Nothing is listening on that port and teleport isnt running either - 

```
ip-10-0-0-115 teleport # ps aux | grep teleport
root      8595  0.0  0.0   6756   944 pts/0    S+   00:10   0:00 grep --colour=auto teleport
ip-10-0-0-115 teleport # netstat -alnp | grep LISTEN
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      2122/kubelet
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      15466/hyperkube
tcp6      12      0 :::31887                :::*                    LISTEN      15466/hyperkube
tcp6       0      0 :::30031                :::*                    LISTEN      15466/hyperkube
tcp6       0      0 :::10255                :::*                    LISTEN      2122/kubelet
tcp6       0      0 :::30582                :::*                    LISTEN      15466/hyperkube
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd
tcp6       0      0 :::32537                :::*                    LISTEN      15466/hyperkube
tcp6       0      0 :::4194                 :::*                    LISTEN      2122/kubelet
tcp6       0      0 :::30185                :::*                    LISTEN      15466/hyperkube
tcp6       0      0 :::10250                :::*                    LISTEN      2122/kubelet
tcp6       0      0 :::30892                :::*                    LISTEN      15466/hyperkube
unix  2      [ ACC ]     SEQPACKET  LISTENING     10750    1/systemd            /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     26988    2435/docker          /var/lib/docker/network/files/f4d764b96aec9233424f4ed780d34f3f4aebc794389b6aaf6ef261b9ed1f8cbf.sock
unix  2      [ ACC ]     STREAM     LISTENING     25508    2233/python          /run/felix-driver.sck
unix  2      [ ACC ]     STREAM     LISTENING     2871     1/systemd            /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     16441    1/systemd            /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     16449    1/systemd            /run/rkt/metadata-svc.sock
unix  2      [ ACC ]     STREAM     LISTENING     16456    1/systemd            /var/run/docker.sock
unix  2      [ ACC ]     SEQPACKET  LISTENING     10743    1/systemd            /run/systemd/coredump
unix  2      [ ACC ]     STREAM     LISTENING     12280    1/systemd            /run/systemd/private
```

**Comment by kontsevoy** [comment]
@jchauncey the documentation covers this well. A Teleport system is composed of 3 roles: auth, proxy and node. You cannot run a node by itself. Do you have the auth server on `publicip`?

**Comment by jchauncey** [comment]
Yes this started when I set auth_service enabled to false. The auth server
is bound to all interfaces and is listening. And this node has joined the
cluster before.

**Comment by kontsevoy** [comment]
so what is your question, sorry I'm a bit lost. you're basically describing how it's supposed to work and not asking any questions or stating any problems ;)

**Comment by jchauncey** [comment]
It appears that teleport is expecting there to be a locally running auth-server. Notice how the bind address is for the local node and not the one i specified in the command. It never even attempts to connect to my remote host.

**Comment by kontsevoy** [comment]
What do you mean "never even attempts". It does, and it gives you an error which you pasted here:

```
dial tcp 10.0.0.115:3025: getsockopt: connection refused
```
That's the node trying to connect and failing. Does `publicip` resolve to `10.0.0.115`?

**Comment by jchauncey** [comment]
No they are 2 separate hosts

**Comment by kontsevoy** [comment]
can you do specify the auth server by its IP? Looks like `publicip` doesn't resolve correctly somewhere.

**Comment by jchauncey** [comment]
That's why I said remote host.

**Comment by jchauncey** [comment]
I don't want to give out the public IP of my auth server on github so I redacted it

**Comment by jchauncey** [comment]
I supply the actual up with the command

**Comment by kontsevoy** [comment]
so, no matter what IP you're using with `--auth-server` it always tries to connect to `10.0.0.115`, is that the problem here? 

if so, do you have `/etc/teleport.yaml` as well? Can you post it here plz? Thanks.

**Comment by jchauncey** [comment]
Yes that's the problem. 

```
ip-10-0-0-115 teleport # cat /etc/teleport/teleport.yaml
# By default, this file should be stored in /etc/teleport.yaml

# This section of the configuration file applies to all teleport
# services.
teleport:
    # nodename allows to assign an alternative name this node can be reached by.
    # by default it's equal to hostname

    # Data directory where Teleport keeps its data, like keys/users for
    # authentication (if using the default BoltDB back-end)
    data_dir: /var/lib/teleport

    # one-time invitation token used to join a cluster. it is not used on
    # subsequent starts
    auth_token: token

    # when running in multi-homed or NATed environments Teleport nodes need
    # to know which IP it will be reachable at by other nodes
    advertise_ip: publicip

    # list of auth servers in a cluster. you will have more than one auth server
    # if you configure teleport auth to run in HA configuration
    auth_servers:
        - publicip:3025

    # Teleport throttles all connections to avoid abuse. These settings allow
    # you to adjust the default limits
    connection_limits:
        max_connections: 1000
        max_users: 250

    # Logging configuration. Possible output values are 'stdout', 'stderr' and
    # 'syslog'. Possible severity values are INFO, WARN and ERROR (default).
    log:
        output: stderr
        severity: ERROR

    # Type of storage used for keys. You need to configure this to use etcd
    # backend if you want to run Teleport in HA configuration.
    storage:
        type: bolt

# This section configures the 'node service':
ssh_service:
    enabled: yes
    # IP and the port for SSH service to bind to.
    listen_addr: 0.0.0.0:3022
    # See explanation of labels in "Labeling Nodes" section below
    labels:
      location: us-east-1
      vpc: staging
      k8s: worker
      role: node
    # List (YAML array) of commands to periodically execute and use
    # their output as labels.
    # See explanation of how this works in "Labeling Nodes" section below
    commands:
    - name: hostname
      command: [/usr/bin/hostname]
      period: 1m0s
```
