### ISSUE TITLE
Two deny configurations in initial role YAML in web admin

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6026]
### Description

**What happened**:

If you start a role in the web two `deny` entries are in.  The second one is used.

![image](https://user-images.githubusercontent.com/60704961/111370750-fcc18e80-866e-11eb-8e1f-c5c04c5e1239.png)

```yaml
  # The 'deny' section can have similar settings that override their 'allow' counterparts
  deny:
    logins: ['guest']

  deny: {}
```

**What you expected to happen**:

Only 1 `deny` in example.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Log as user that can see the roles
2. Press create new role

### Server Details
- Teleport version (run `teleport version`): 6.0.1
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
