### ISSUE TITLE
tsh says self-signed cert despite it being a CA signed cert

### ISSUE THREAD

**Issue by prashanthellina** [gravitational/teleport#603]
I set up teleport (v1.2 on Ubuntu 16.04) as per the documentation. I also purchased a CA certified SSL certificate from Thawte and configured the same.

When I visit port 3080 in Google Chrome, the browser accepts the certificate (indicates by showing a green lock icon in the URL bar).

However, when I try to use tsh, I get the following
```
WARNING:
 The proxy you are connecting to uses the self-signed HTTPS certificate.
 Try --insecure flag if you know what you're doing.
```

What do I do to overcome this?

**Comment by klizhentas** [comment]
@prashanthellina are you connecting to proxy via IP? if this IP is not in the cert (which is likely so), you wil still get the warning. If you set `--proxy` to connect to DNS name instead that is valid, the warning will most likely disappear.

**Comment by prashanthellina** [comment]
@klizhentas I am already contacting the proxy using a domain name. When I tested using `tsh` and browser access to port 3080, in both cases, I used the same domain name.

**Comment by klizhentas** [comment]
can you post the tsh command featuring proxy flag?

**Comment by prashanthellina** [comment]
```bash
tsh --proxy=teleport.deepcompute.com --auth=google ssh --login=root <node_name>
```

**Comment by klizhentas** [comment]
can you add `--debug`?

**Comment by prashanthellina** [comment]
```bash
INFO[0000] no teleport login given. defaulting to prashanth  file=client/api.go:216
DEBU[0000] using FSLocalKeyStore                         file=client/keystore.go:73
INFO[0000] [CLIENT] connecting to proxy teleport.deepcompute.com:3023 with host login 'root'  file=client/api.go:740
DEBU[0000] checking host key of teleport.deepcompute.com:3023
  file=client/keyagent.go:105
DEBU[0001] checking host key of teleport.deepcompute.com:3023
  file=client/keyagent.go:105
INFO[0002] oidcLogin start                               file=client/api.go:902
DEBU[0002] not using loopback pool for remote proxy addr: teleport.deepcompute.com:3080  file=client/api.go:914
WARNING:
 The proxy you are connecting to uses the self-signed HTTPS certificate.
 Try --insecure flag if you know what you're doing.
```

**Comment by klizhentas** [comment]
so looks like it's generally not happy with the certificate for some reason, what happens if you

```
openssl s_client -connect teleport.deepcompute.com:3023
```

**Comment by prashanthellina** [comment]
```bash
$ openssl s_client -connect teleport.deepcompute.com:3023

CONNECTED(00000003)
139754085996184:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1478130100
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

**Comment by klizhentas** [comment]
does not look like a right response to me, can you verify your configuration?

**Comment by prashanthellina** [comment]
I thought I screwed up somewhere in the proxy config and that is why I tested in the browser which seems happy. I am sure I made some mistake in the config but it isn't obvious to me. I'm pasting it below (removing all sensitive stuff).

```
teleport:
  nodename: teleport.deepcompute.com
  pid_file: /var/run/teleport.pid
  auth_token: xxxx-token-xxxx
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  storage:
    type: bolt
  data_dir: /var/lib/teleport
auth_service:
  enabled: "yes"
  cluster_name: "testingcluster"
  listen_addr: 0.0.0.0:3025
  tokens:
    - "node:ksdlsdsdslkdsldslkd"
  oidc_connectors:
    - id: google
      redirect_url: https://teleport.deepcompute.com:3080/v1/webapi/oidc/callback
      client_id: xxxxx.apps.googleusercontent.com
      client_secret: jjsdjsdhsjhdjsdhsj
      issuer_url: https://accounts.google.com
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  labels:
    db_role: master
    db_type: postgres
  commands:
  - name: hostname
    command: [/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/bin/uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /root/cert/deepcompute.key
  https_cert_file: /root/cert/deepcompute.pem
```
