### ISSUE TITLE
Empty error message when trying to add a trusted cluster

### ISSUE THREAD

**Issue by kumashiro** [gravitational/teleport#6079]
### Description

I'm trying to add a trusted cluster by following instructions from https://goteleport.com/docs/trustedclusters/ and I'm getting an empty error message. On the leaf cluster, with log severity set to `INFO`, the result of the command looks like this:

```
tctl create cluster.yaml
ERROR:

```

Server logs only one line:

```
ERRO [AUTH]      auth/trustedcluster.go:266
```

Nothing is logged on the root cluster.

With severity set to `DEBUG` on the leaf cluster (sensitive data obscured):

```
tctl -d create cluster.yaml
DEBU             Debug logging has been enabled. common/tctl.go:322
DEBU             reading config file: /etc/teleport.yaml config/configuration.go:143
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:172
DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
DEBU             Connecting to auth servers: [{leaf.cluster.server:3025 tcp } {0.0.0.0:3025 tcp }]. common/tctl.go:193

ERROR REPORT:
Original Error: *trace.BadParameterError
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:131 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:253 github.com/gravitational/teleport/lib/auth.(*Client).PostJSON
	/go/src/github.com/gravitational/teleport/lib/auth/clt.go:2052 github.com/gravitational/teleport/lib/auth.(*Client).UpsertTrustedCluster
	/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:286 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).createTrustedCluster
	/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:258 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create
	/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:134 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
	/go/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:165 github.com/gravitational/teleport/tool/tctl/common.Run
	/go/src/github.com/gravitational/teleport/tool/tctl/main.go:36 main.main
	/opt/go/src/runtime/proc.go:204 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message:
```

Server log on the leaf node:

```
DEBU [AUTH]      ClientCertPool -> cert(leaf-cluster issued by leaf-cluster:numbers_a) auth/middleware.go:593
DEBU [AUTH]      ClientCertPool -> cert(leaf-cluster issued by leaf-cluster:numbers_a) auth/middleware.go:593
DEBU [AUTH]      ClientCertPool -> cert(leaf-cluster issued by leaf-cluster:numbers_b) auth/middleware.go:593
DEBU [AUTH]      ClientCertPool -> cert(leaf-cluster issued by leaf-cluster:numbers-b) auth/middleware.go:593
DEBU [AUTH:1]    Server certificate cert(obscured-uuid.leaf-cluster issued by leaf-cluster:numbers_a). auth/middleware.go:298
DEBU [AUTH:1]    Server certificate cert(obscured-uuid.leaf-cluster issued by leaf-cluster:numbers_a). auth/middleware.go:298
DEBU [AUTH]      Creating enabled Trusted Cluster relationship. auth/trustedcluster.go:92
DEBU [AUTH]      Sending validate request; token=root-trusted-clusters-token, CAs=[CA(name=leaf-cluster, type=host)] auth/trustedcluster.go:261
ERRO [AUTH]      auth/trustedcluster.go:266
```

Nothing is logged on the root cluster server, even with `DEBUG` severity set there.

I still haven't found the cause and cannot tell what the error message should say. If it helps, I confirmed that leaf cluster server successfully connects to port 3080 of the root cluster server (verified with `tcpdump`) and that leaf cluster server can verify root proxy certificate:

```
openssl s_client -connect root.cluster.server:3080 </dev/null 2>&1 | grep 'Verify return'
Verify return code: 0 (ok)
    Verify return code: 0 (ok)
```

Proxy certificates on root and leaf are not self-signed. Contents of the `cluster.yaml` file:

```yaml
kind: "trusted_cluster"
version: "v2"
metadata:
  name: "root-cluster"
spec:
  enabled: true
  token: "root-trusted-clusters-token"
  tunnel_addr: "root.cluster.server:3024"
  web_proxy_addr: "root.cluster.server:3080"
  role_map:
    - remote: "admin"
      local: ["auditor"]
```

Root cluster server configuration:

```yaml
teleport:
  storage:
    type: etcd
    peers: ["https://root.cluster.server:2379"]
    tls_cert_file: /etc/ssl/certs/root.cluster.server.pem
    tls_key_file: /etc/ssl/private/root.cluster.server.key
    tls_ca_file: /etc/ssl/certs/ca.pem
    username: etcd-username
    password_file: /var/lib/teleport/etcd-pass
    prefix: /teleport/
    insecure: false
    etcd_max_client_msg_size_bytes: 15728640
  nodename: root.cluster.server
  data_dir: /var/lib/teleport
  auth_token: root-nodes-token
  #ca_pin: "sha256:ca-pin-hash-goes-here"
  auth_servers:
      - root.cluster.server:3025
  log:
    output: stderr
    severity: INFO

auth_service:
  enabled: "yes"
  cluster_name: "root-cluster"
  listen_addr: 0.0.0.0:3025
  tokens:
  - node:root-nodes-token
  - proxy:root-proxies-token
  - trusted_cluster:root-trusted-clusters-token
  authentication:
    type: local
    second_factor: otp

ssh_service:
  enabled: "yes"
  labels:
    role: bastion
  commands:
  - name: hostname
    command: [/bin/hostname]
    period: 1m0s
  - name: system
    command: [/bin/uname, -o]
    period: 12h0m0s
  - name: arch
    command: [/bin/uname, -m]
    period: 12h0m0s

proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: root.public.address.different.from.root.cluster.server:3080
  https_keypairs:
    - key_file: /etc/ssl/private/root.cluster.server.key
      cert_file: /etc/ssl/certs/root.cluster.server.pem
```

Leaf cluster server configuration:

```yaml
teleport:
  nodename: leaf.cluster.server
  data_dir: /var/lib/teleport
  auth_token: leaf-nodes-token
  #ca_pin: sha256:ca-pin-hash-goes-here
  auth_servers:
    - leaf.cluster.server:3025
  log:
    output: stderr
    severity: INFO

auth_service:
  enabled: yes
  cluster_name: leaf-cluster
  listen_addr: 0.0.0.0:3025
  tokens:
  - node:leaf-nodes-token
  - proxy:leaf-proxies-token
  authentication:
    type: local
    second_factor: otp

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: leaf.cluster.server:3080
  https_keypairs:
    - key_file: /etc/ssl/private/leaf.cluster.server.key
      cert_file: /etc/ssl/certs/leaf.cluster.server.pem

ssh_service:
  enabled: yes
  labels:
    role: bastion
  commands:
  - name: hostname
    command: [/bin/hostname]
    period: 1m0s
  - name: system
    command: [/bin/uname, -o]
    period: 12h0m0s
  - name: arch
    command: [/bin/uname, -m]
    period: 12h0m0s
```

### Server Details
- Teleport version (run `teleport version`): Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5
- Server OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): self-hosted
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): apt
- Additional details:
