### ISSUE TITLE
Can't change password in UI with mfa on

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#6156]
### Description
Auth type mfa wasn't taken into account for password change forms

**What happened**:
Unable to change password

![image](https://user-images.githubusercontent.com/43280172/112527743-9b7d7780-8d60-11eb-91b2-b5acdb5dda88.png)

**What you expected to happen**:
Be able to change password with 2fa. (for auth type `on` and `optional` default to using `otp` similar to invites)

### Reproduction Steps
With teleport.yaml auth setting:
```
authentication:
    type: local
    second_factor: optional
    u2f:
      app_id: https://kimlisa.dev:3080
      facets:
      - https://kimlisa.dev:3080
```
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Initially created password from invite with otp
2. From CLI, mfa add u2f (prolly not needed, but this is the exact steps i took)
3. Go to UI > account > try changing password

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v7.0.0-dev git:v6.0.0-alpha.2-291-g940c83c16-dirty go1.15.7
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws
