### ISSUE TITLE
RBAC Design Doc

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#620]
Multiple users expressed interest in adding more fine-grained authorization to the Teleport.
This document is a proposal for RBAC - role based access control.

## Current State

The Teleport user identity is stored in a certificate as KeyID field and `AllowedLogins`. And the SSH login (AKA "OS login") this user is allowed to assume is translated to `Valid Principals` in the SSH certificate for SSH compatibility purposes.

It is worth noting that we can't use custom user cert extensions to store metadata to keep its certificates compatible with OpenSSH due to [this bug](https://bugzilla.mindrot.org/show_bug.cgi?id=2387)

### Role

A Role is a collection of permissions. 

#### Role Object

Here's a structure of a role object:

```yaml
# Teleport Objec type/kind: "role" in this case.
kind: role
version: v1

#
# Metadata applies to a specific role instance
#
metadata:
  # Mandatory field. First character cannot be NOT alphanumeric. The reason for this
  # is: we can create special "internal" and hidden roles with names starting with,
  # say, '#' or '@' or '_'
  name: admin
  description: "this Role is an example"

#
# Spec is a "frozen" part of a role definition (API contract) and it is not instance-specific.
#
spec:
  # Maximum allowed SSH session duration (would be nice to also enforce it on web logins)
  max_session_ttl: 3h

  # List of local OS logins allowed for this role. Similar to (obsolete) --local-logins flag for `tctl users add`
  logins: [vagrant, root]

  # Nodes this user can login into. The "label spec" is the same format as "tsh ssh" (Teleport has code which
  # parses and validates "label spec"). By default "*" which means "any node"
  node_labels: {*: login, os: *}

  # Namespaces this user is allowed to see.
  namespaces: [default,	staging]

  # Permissions is a list of non-SSH permissions that apply to Teleport-specific objects
  permissions:
    sessions: [read, write]

```

### Cluster namespaces

In addition to clusters we are going to introduce namespaces to limit access and visibility for various teams within the same cluster.

Teleport nodes will belong to namespaces, by default teleport node will be provisioned in `default` namespace, however we can provision nodes in different namespace within the same cluster.

Sessions and all activity executed on the node within the namespace will be automatically assigned to the same namespace.

### Teleport users and roles

Teleport user is assigned to multiple roles.

User object will get new property `roles` with a list of roles assigned to it.

```yaml
roles: 
    - @bob
    - db-admin
    - readonly
```

Every user will have a default role created and associated with this user only, e.g. `alice` will get role `@alice`.

If user is assigned multiple roles, resulting permissions set is a union of all roles assigned to the user.

### Migration for existing users

Existing users will be migrated to get to auto-generated role:

```yaml
# unique role ID
id: @bob
kind: role
version: v1

spec:
   permissions:
       - {ssh: {logins: {bob: true}}}
```

This means that after the upgrade to new version of teleport with RBAC, there won't be any situation where users will be not assigned to any of the roles, simplifying management.

### External users and roles

Let's assume we have an external org "Ops" that wants to get access to database nodes of the org "Bank" for db administration, but nowhere else.

1. Add trusted external cert authority `ops` 
2. Add role for this new organization if necessary, or reuse existing role

```yaml
id: ops
permissions:
   - {ssh: {logins: {bob: true}}}
```

3. Trusted certificate authority for organization "Ops" will have a `roles` property set to `ops`:

```yaml
kind: CertificateAuthority
spec:
   roles: {ops: true}
````

Note that users for external org do not have to sync user entries on the cluster "Bank", however locally, in cluster "Org" they will have to be assigned to the role "ops" to get a certificate signed by certificate authority "ops" and get access.

#### Adding users

Admins will be able to specify the role when creating new local users.

```bash
tctl user add bob --role=admin
```

Also note, that `--logins` flag will be still supported, to maintain backwards compatibility, we can allow using this flag, that will simply update a role associated with this user `@bob`

### Adding roles dynamically

I suggest we allow users to add/update roles via CLI:

```sh
tctl upsert -f role.yaml
```

we will reuse `upsert` command extending support for other types of objects, e.g. users and certificate authorities.

### Changes to the configuration

Some roles may be supplied statically for static teleport backend use-case:

```yaml
auth:
   roles: 
      admin:
          permissions: 
              ... spec goes here
```

### Mapping OIDC/OAuth2.0 claims to Roles

We are going to update `OIDC` connectors with special dynamic mappings to map [claims](http://openid.net/specs/openid-connect-core-1_0.html#Claims)  to roles defined in the system.

Consider the following OIDC connector:

```yaml
 - id: google
   redirect_url: https://localhost:3080/v1/webapi/oidc/callback
   client_id: id-from-google.apps.googleusercontent.com
   client_secret: secret-key-from-google
   issuer_url: https://accounts.google.com
   # will add additional claims to request in auth request
   scope:
      - group
   # map group claim values to teleport roles
   # returned claim value could be list object ["a", "b"] or a simple string
   claims_to_roles:
      - {claim: 'group', 'value': "admin", role: "teleport-admin"}
```
