### ISSUE TITLE
OpenID authentication in auth server with AzureAD failing

### ISSUE THREAD

**Issue by dali-bcg** [gravitational/teleport#621]
Hi,

I attempted to use the AzureAD OpenID endpoints for authentication (I still called it google in the auth server settings) but it fails with the following message : 
`{"message":"OAuth2 error code=unsupported_response_type, message=unable to verify auth code with issuer"}`

I think I am hitting a bug that is already resolved in the coreos/go-oidc package with this PR (https://github.com/coreos/go-oidc/pull/87).

I created an oauth application in AzureAD and configured the auth server as follows : 
```
auth_service:
  enabled: true
  cluster_name: magadan
  oidc_connectors:
    - id: google
      redirect_url: https://localhost:10000/v1/webapi/oidc/callback
      client_id: c6e2cffe-987a-46ff-bd12-xxxxxxyyyyyy
      client_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      issuer_url: https://sts.windows.net/{TENANT_ID}/
```

I wanted to validate the hunch but I struggled to build my own copy of teleport with the updated dependency to verify this. I am happy to provide any assistance on this front.
