### ISSUE TITLE
Some processes in some setup not killed after disconnect

### ISSUE THREAD

**Issue by aiwaniuk** [gravitational/teleport#6245]
### Description

**What happened**:
after running some commands while connected via tsh and closing terminal tab or browser tab some processes persist forever

**What you expected to happen**:
These processes should be killed like in using regular ssh

### Reproduction Steps

starting using ssh: ssh -> "sudo su -" -> vi qwe 

ps auxf
```
root        1353  0.0  0.8  13664  8780 ?        Ss   14:32   0:00  \_ sshd: ubuntu [priv]
ubuntu      1463  0.0  0.5  13672  5100 ?        S    14:32   0:00      \_ sshd: ubuntu@pts/2
ubuntu      1464  0.0  0.5  10540  5496 pts/2    Ss   14:32   0:00          \_ -bash
root        1962  0.0  0.4  11168  4816 pts/2    S+   14:44   0:00              \_ sudo su -
root        1963  0.0  0.0  11168   748 pts/0    Ss   14:44   0:00                  \_ sudo su -
root        1964  0.0  0.4  10128  4264 pts/0    S    14:44   0:00                      \_ su -
root        1965  0.1  0.5  10028  5060 pts/0    S    14:44   0:00                          \_ -bash
root        1976  0.2  0.9  23836  9908 pts/0    S+   14:44   0:00                              \_ vi qwe
```

after closing termianl tab with ssh, all processes from this tree are killed

now using tsh: tsh ssh ubuntu@ip-172-30-48-21 -> "sudo su -" -> vi asd 
```
root        1992  0.2  4.9 1070696 49380 ?       Sl   14:45   0:00  \_ /usr/local/bin/teleport exec
ubuntu      2077  0.2  0.5  10036  5076 pts/0    Ss   14:45   0:00      \_ -bash
root        2086  0.0  0.4  11160  4684 pts/0    S+   14:45   0:00          \_ sudo su -
root        2087  0.0  0.0  11160   744 pts/2    Ss   14:45   0:00              \_ sudo su -
root        2089  0.0  0.4  10128  4240 pts/2    S    14:45   0:00                  \_ su -
root        2090  0.1  0.4  10028  4980 pts/2    S    14:45   0:00                      \_ -bash
root        2101  0.0  0.9  23836  9888 pts/2    S+   14:45   0:00                          \_ vi asd
```
after closing terminal tab with tsh

after a minute ps auxf:
```
root        2086  0.0  0.4  11160  4684 ?        S    14:45   0:00 sudo su -
root        2087  0.0  0.0  11160   744 pts/2    Ss   14:45   0:00  \_ sudo su -
root        2089  0.0  0.4  10128  4240 pts/2    S    14:45   0:00      \_ su -
root        2090  0.0  0.4  10028  4980 pts/2    S    14:45   0:00          \_ -bash
root        2101  0.0  0.9  23836  9888 pts/2    S+   14:45   0:00              \_ vi asd
```
and this processes are never killed

### Server Details
teleport.yaml

```
teleport:
  log:
    output: stdout
    severity: INFO

  auth_token: REDACTED

  auth_servers:
    - REDACTED:3025

  storage:
    type: dir

auth_service:
  enabled: no


ssh_service:
  enabled: yes
  pam:
    enabled: yes

  listen_addr: 0.0.0.0:3022

  labels:
    cluster: box
    owner: aiwaniuk

  permit_user_env: false

proxy_service:
  enabled: no
```

fresh ubuntu 20.04 from AWS
```
ubuntu@ip-172-30-48-21:~$ uname -a
Linux ip-172-30-48-21 5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-30-48-21:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:  Ubuntu 20.04.2 LTS
Release:  20.04
Codename: focal
```
one modification:
```
/etc/sudoers
"Defaults        env_reset" -> "Defaults        env_reset, use_pty"
```

both proxy and auth and node are running 6.0.02
```
ubuntu@ip-172-30-48-21:~$ teleport version
Teleport Enterprise v6.0.2 git: go1.15.5b5
```
