### ISSUE TITLE
login with oidc okta error

### ISSUE THREAD

**Issue by jeremyd** [gravitational/teleport#625]
I'm trying to hotwire the SSO to use okta instead of google. I created a user following the guide about google.  I used the id:google to try to trick it into working.  I used this configuration:

```
teleport:
  nodename: lettuce
ssh_service:
  enabled: yes
proxy_service:
  enabled: yes
auth_service:
  enabled: yes
  cluster_name: testing
  oidc_connectors:    
    - id: google
      redirect_url: https://localhost:3080/v1/webapi/oidc/callback
      client_id: xxx
      client_secret: xxx
      issuer_url: https://<MYCOMPANY>.okta.com
```

I'm getting this error when attempting to login via oidc.  Any idea if this might be easily fixable?  Tried a few different settings on the okta side but to no avail.

```
http: Provider config sync still failing, retrying in 8s: token_endpoint_auth_signing_alg_values_supported cannot include 'none'
```
