### ISSUE TITLE
UI does not allow to approve requests

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6305]
User `alice` has a permission to review access requests and I can approve from the CLI, but UI does not show the button:

<img width="1009" alt="Screen Shot 2021-04-02 at 9 10 49 PM" src="https://user-images.githubusercontent.com/13717/113467455-eef26400-93f7-11eb-9fae-52bf319b3694.png">

```yaml
kind: role
version: v3
metadata:
  name: reviewer
spec:
  allow:
    review_requests:
      roles: ['dbadmin']
---
kind: role
version: v3
metadata:
  name: devops
spec:
  allow:
    request:
      roles: ['dbadmin']
      thresholds:
        - approve: 1
          deny: 1
---
kind: role
version: v3
metadata:
  name: dbadmin
spec:
  allow:
    logins: ['root']
    node_labels:
      'env': 'prod'
      'type': 'db'
```

This works:

```
tsh request review --approve --reason="hello" 9c721e54-b049-4ef8-a7f6-c777aa066764
```
