### ISSUE TITLE
Weird state when adding a user to Teleport OSS with `--roles` specified

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6342]
### Description

**What happened**:

Adding a user to a Teleport OSS cluster with the new Enterprise-like `tctl users add gus --roles=admin` syntax puts the user in a weird state where they don't have any logins associated with them. 

Using the old `tctl users add gus root` syntax prints a deprecation warning, but works as expected.

**What you expected to happen**:

Both formats should work the same.

### Reproduction Steps

Create a user with the Enterprise syntax:
```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2) » kubectl exec deploy/teleport -- tctl users add gus --roles=admin
User "gus" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://gke.teleportdemo.net:443/web/invite/4a8ab46003978921f435488c44ae1091

NOTE: Make sure gke.teleportdemo.net:443 points at a Teleport proxy which users can access.
```

Set up in the browser, then try to log in with `tsh login` - see the weird `-teleport-nologin` entry:

```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2) » tsh login --proxy=gke.teleportdemo.net:443
Enter password for Teleport user gus:
Enter your OTP token:
> Profile URL:        https://gke.teleportdemo.net:443
  Logged in as:       gus
  Cluster:            gke.teleportdemo.net
  Roles:              admin*
  Logins:             -teleport-nologin-9ff4e9fe-28b1-464c-919f-2f1aa4f5fbaf
  Kubernetes:         enabled
  Kubernetes cluster: "gke.teleportdemo.net"
  Valid until:        2021-04-08 05:29:34 -0300 ADT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2) » tctl get user/gus
kind: user
metadata:
  id: 1617827102752982792
  name: gus
spec:
  created_by:
    time: "2021-04-07T20:25:02.709214033Z"
    user:
      name: c5425483-15d9-4038-9f2b-61a4a0bc4aa8.gke.teleportdemo.net
  expires: "0001-01-01T00:00:00Z"
  roles:
  - admin
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
  traits:
    logins: null
version: v2
```

Remove user and re-add using old syntax:

```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2*) » kubectl exec deploy/teleport -- tctl users rm gus
User "gus" has been deleted

~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2*) » kubectl exec deploy/teleport -- tctl users add gus root
NOTE: Teleport 6.0 added RBAC in Open Source edition.

In the future, please create a role and use a new format with --roles flag:

$ tctl users add "gus" --roles=[add your role here]

We will deprecate the old format in the next release of Teleport.
Meanwhile we are going to assign user "gus" to role "admin" created during migration.

User "gus" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://gke.teleportdemo.net:443/web/invite/780d4409ecd22385b55668c1bbba9761

NOTE: Make sure gke.teleportdemo.net:443 points at a Teleport proxy which users can access.
```

Create the user via web UI and log in via `tsh` again - see that the `gus` user now has the `admin` role and `root` login as is expected:
```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2*) » tsh login --proxy=gke.teleportdemo.net:443
Enter password for Teleport user gus:
Enter your OTP token:
> Profile URL:        https://gke.teleportdemo.net:443
  Logged in as:       gus
  Cluster:            gke.teleportdemo.net
  Roles:              admin*
  Logins:             root
  Kubernetes:         enabled
  Kubernetes cluster: "gke.teleportdemo.net"
  Kubernetes users:   gus
  Kubernetes groups:  
  Valid until:        2021-04-08 05:35:19 -0300 ADT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

### Server Details
- Teleport version (run `teleport version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`
- Server OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.2 LTS (Focal Fossa)`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`

**Comment by awly** [comment]
+1, you also can no longer set `--k8s-users` or `--k8s-groups` when creating a local user.
I had to manually edit the user object via `tctl`.

**Comment by webvictim** [comment]
The admin role created is also very unprivileged:

```yaml
kind: role
metadata:
  id: 1617825013604683680
  labels:
    migrate-v6.0: "true"
  name: admin
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```

This means that the initial user created can't see users, roles or auth connectors in the web UI, which seems different to the default Enterprise `admin` role.
