### ISSUE TITLE
cluster_name duplicates in  kubeconfig with tsh

### ISSUE THREAD

**Issue by nitinpatil1992** [gravitational/teleport#6355]
### Description
I have teleport 6 in kubernetes environment and configured with `auth_service` as follows

```
auth_service:
  enabled: yes
  authentication:
    type: local
  tokens:
    - trusted_cluster:sandboxuk-spot
  public_addr: <public_endpoinnt>:3025
  cluster_name: sandboxuk-spot
```
I can successfully login with github integration.
But when I checkout my `~/.kube/config`, it has duplicated context name and user 

```
contexts:
- context:
    cluster: <cluster_endpoint>
    user: sandboxuk-spot-sandboxuk-spot
  name: sandboxuk-spot-sandboxuk
current-context: sandboxuk-spot-sandboxuk-spot
kind: Config
preferences: {}
users:
- name: sandboxuk-spot-sandboxuk-spot
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
```

**What happened**:

**What you expected to happen**:
It shouldn't duplicate the cluster_name

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Deployed the [teleport chart](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport)
2. login with tsh login --proxy=<public_endpoint>:443 -auth=github
3. Check ~/.kube.config
 
### Server Details
- Teleport version (run `teleport version`): v6.0.1 
- Server OS (e.g. from `/etc/os-release`):  eks-optimised linux 5.4.74-36.135.amzn2.x86_64
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): EKS 1.15
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v6.0.1 git:v6.0.1-0-g6166fd56e go1.15.
- Computer OS (e.g. Linux, macOS, Windows): Catalina 10.15.7
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`) N/A
- Run tsh with --debug flag (`tsh --debug`) 
```
> Profile URL:        <public_endpoint>:443
  Logged in as:       nitinpatil1992
  Cluster:            sandboxuk-spot
  Roles:              devops*
  Traits:             kubernetes_groups: []
                      kubernetes_users: []
                      logins: [nitinpatil1992]
  Logins:             admin
  Kubernetes:         enabled
  Kubernetes cluster: "sandboxuk-spot"
  Kubernetes groups:  system:masters
  Valid until:        2021-04-09 03:00:20 +0100 BST [valid for 12h0m0s]
  Extensions:         permit-port-forwarding, permit-pty
```
