### ISSUE TITLE
Yubikey login doesn't work with Firefox (Linux and Mac)

### ISSUE THREAD

**Issue by ilpianista** [gravitational/teleport#6357]
### Description

I did more tests since I opened this issue and the result is that:

I cannot login to the Web portal anymore by either using Firefox or Chromium with the Yubikey (either USB A or C). The login with Chrome 89.0.4389.114 is fine. Firefox doesn't work on Mac either.

Chromium:
![chromium](https://user-images.githubusercontent.com/529436/114046731-61949100-9889-11eb-9c73-2d61db21f98b.png)

Firefox:
![firefox](https://user-images.githubusercontent.com/529436/114046735-62c5be00-9889-11eb-900f-b37519566281.png)

**What happened**:

We upgraded from 5.0.2 to 6.0.2.

**What you expected to happen**:

The login works as usual.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a new account on Teleport 6.0.2
2. Login with the new account and setup U2F via the Yubikey USB A
3. Logout and try to login again
4. The login doesn't work

### Server Details
- Teleport version (run `teleport version`):
```
Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5
```
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
```
AWS
```
- Additional details:
```
teleport:
  nodename: baz2.foo.bar
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: WARN
  storage:
    type: dynamodb
    region: eu-west-1
    table_name: teleport.foo.cluster_state
    audit_events_uri:
      - file:///var/lib/teleport/log
      - dynamodb://teleport.foo.audit_events
    audit_sessions_uri: s3://teleport-logs/
auth_service:
  enabled: "yes"
  cluster_name: foo
  authentication:
    type: local
    second_factor: u2f
    u2f:
      app_id: https://baz-web.foo.bar
      facets:
        - https://baz.foo.bar:3080
  listen_addr: 0.0.0.0:3025
  public_addr: baz.foo.bar
  tokens:
    - "node:ABC"
  session_recording: "node"
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  public_addr: localhost:3022
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  public_addr: https://baz.foo.bar:3080
  https_keypairs:
  - key_file: /etc/letsencrypt/live/baz.foo.bar/privkey.pem
    cert_file: /etc/letsencrypt/live/baz.foo.bar/fullchain.pem
```

The app_id https://baz-web.foo.bar is a web server that returns this JSON:
```
{"trustedFacets":[{"version":{"major":1,"minor":0},"ids":["https://baz.foo.bar:3080"]}]}
```

### Client Details
- Tsh version (`tsh version`):
```
Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5
```
- Computer OS (e.g. Linux, macOS, Windows):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Browser version (for UI-related issues):
```
firefox:amd64 87.0+build3-0ubuntu0.20.04.2
chromium-browser:amd64 1:85.0.4183.83-0ubuntu0.20.04.2
```
- Installed via (e.g. apt, yum, brew, website download):
```
apt
```
- Additional details:

**Comment by awly** [comment]
@ilpianista this is likely because of the `app_id` value in your `teleport.yaml`.
Can you try changing the `u2f` section of the config to:
```yaml
    u2f:
      app_id: https://baz.foo.bar:3080
      facets:
        - https://baz.foo.bar:3080
        - https://baz-web.foo.bar:3080
```

I have some docs updates in flight to make this finicky configuration easier: https://github.com/gravitational/teleport/blob/db60bedc12f74a81ef12b82549efd8988b88521b/docs/pages/access-controls/guides/u2f.mdx#enable-u2f-support
