### ISSUE TITLE
"With google" login hanging and seeing "go-oidc: provider config sync failed" in our logs

### ISSUE THREAD

**Issue by bshelton229** [gravitational/teleport#639]
I've been unable to get google oid authentication working. The web server hangs indefinitely when hitting `https://our-public-host.com:3080/v1/webapi/oidc/login/web?connector_id=google&redirect_url=....`.

The only error we see in the logs is `go-oidc: provider config sync failed, retrying in 8s: Get /.well-known/openid-configuration: unsupported protocol scheme ""`

I believe we have everything set up correctly. The first thing we're seeing is when using `tctl users add` to create the user with `--identity google:my@email.com` we get the standard invitation link on the console, I'm not sure if that's the normal behavior, I would have assumed it just created the user ready to be used with oid.

When clicking the "With google" button, which did appear after configuring the oid provider, we hang indefinitely. No headers are returned, the server just hangs until the browser times out. I'm sure I'm configuring something wrong, but I haven't been able to find it. We have several google oauth2 apps working correctly, so I'm confident the oauth2 credentials are working as they're supposed to.

Thank you in advance! So far this product is fantastic. We just need to get this piece working.

**Comment by klizhentas** [comment]
it looks like something is not set up in your OIDC config in teleport. Can you post your config? Don't forget to omit all the secrets from it!

**Comment by bshelton229** [comment]
Thanks for getting back to me

```yaml
auth_service:
  enabled: yes
  cluster_name: "staging"
  oidc_connectors:
    - id: google
      redirect_url: https://teleport.staging.domain.com:3080/v1/webapi/oidc/callback
      client_id: 12345.apps.googleusercontent.com
      client_secret: 12345
      issuer_url: https://accounts.google.com
```

I solved my first issue, I had a typo in `issuer_url`. A better error message, or some kind of config validation would be a nice to have in the future, if that doesn't exist already.

I'm still a bit confused about how users works. It seems that you have to invite a user and have them sign up, setting a password, and setting 2-factor MFA, just to then later only use google oauth. Is there a way for an admin to add users to the system identified by a certain google oauth2 email address without having the user need to sign up using credentials they never use again?
