### ISSUE TITLE
Maintenance Mode/Announcement Banner

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#6442]
### What
Provide a free form text  field  to display text to all users logged into web UI

### How
Provide an option in teleport.yaml under the proxy section
```
display_banner:
      from_time:
      to_time:
      banner_text:
```
Alternatively also,provide an option in the web UI to update banner text
### Why

This is needed to inform users in advance about  maintenance  windows and/or to make  announcements regarding  service health/status.

### Workaround

None
