### ISSUE TITLE
Dynamodb storage with oidc and static tokens

### ISSUE THREAD

**Issue by bshelton229** [gravitational/teleport#645]
I tried out the dynamodb auth storage and when I enabled it I was no longer able to join nodes using static tokens and my oidc connectors seemed to be ignored. When I use the dynamodb store, I can only add nodes using tokens generated with `tctl nodes add` and the oidc is no longer active at all, meaning I can't create users with `--identity google:some@email.com`.

My configuration

```yaml
teleport:
  nodename: teleport-auth
  storage:
    type: dynamodb
    region: us-west-2
    # Using IAM for auth
    table_name: staging.teleport.auth


auth_service:
  enabled: yes
  cluster_name: "staging"
  tokens:
    - "node,proxy:static_key"
    - "node:another_static_key"
  oidc_connectors:
    - id: google
      redirect_url: https://teleport.staging.domain.com:3080/v1/webapi/oidc/callback
      client_id: 123.apps.googleusercontent.com
      client_secret: 456
      issuer_url: https://accounts.google.com
```

I'm probably configuring something incorrectly, but I wanted to check. This backend seems fairly new, and it possibly doesn't support everything.

What is the best way to have more ephemeral hosts that come up and down via autoscaling groups join clusters automatically. That's what I was planning on using the static tokens for.

Thanks in advance!

**Comment by klizhentas** [comment]
I think this is because by default static configuration is treated as a separate thing and is ignored when using dynamic backends. You can use 

```yaml
seed_config: true
```

defined here:

https://github.com/gravitational/teleport/blob/master/lib/config/fileconf.go#L354

So then teleport will treat this static configuration as a seed config and will populate your Dynamo backend with OIDC settings.

**Comment by bshelton229** [comment]
Great, thanks. I'll give that a try tomorrow. Does that go for the oidc config as well? Is there a way to use the cli to manage static tokens within the store without seeding, is that preferred?

**Comment by klizhentas** [comment]
static config is static, as in only defined via config, so cli can't change it

**Comment by bshelton229** [comment]
I gave `seed_config: true` a shot and didn't have any luck. I boot the auth server up and neither the static tokens nor the oid config seem to make it into dynamo. I can do `tctl nodes add --roles proxy` and add the proxy that way, but the "with google" button doesn't appear and I'm unable to create google oid backed users.

When I attempt to add a user using `--identity google:....` it fails with: `OpenID connector 'google' is not configured`.

The Dynamodb table is getting created. I should mention I'm using the `v1.2.6` tag from the repo, should I try master?

Thanks.

**Comment by klizhentas** [comment]
@bshelton229 can you wipe out local state of `/var/lib/teleport/*` auth server and restart the server with new config? I think that `seed_config` is not getting used as Teleport think it's already initialized the backend.

**Comment by bshelton229** [comment]
I believe I have been wiping that entire dir before each try. I just built a deb off master and am trying that now.

**Comment by klizhentas** [comment]
can you show me the config file part, seed_config should be placed in teleport section:


```yaml
teleport:
   seed_config: true
```

**Comment by bshelton229** [comment]
No problem, and I really appreciate your help. Here is the whole thing, with secure redacted of course.

I start with this config in `/etc/teleport.yaml`

```yaml
teleport:
  nodename: teleport-auth
  storage:
    type: dynamodb
    region: us-west-2
    table_name: staging-test2.teleport.auth
    access_key: access
    secret_key: key
  seed_config: true

auth_service:
  enabled: yes
  cluster_name: "staging"
  tokens:
    - "node,proxy:some_token"
  oidc_connectors:
    - id: google
      redirect_url: https://teleport.staging.domain.com:3080/v1/webapi/oidc/callback
      client_id: key.apps.googleusercontent.com
      client_secret: key_secret
      issuer_url: https://accounts.google.com
```

I then remove the state dir to be safe

`sudo rm -rf /var/lib/teleport`

I then start up the service with

`sudo teleport start --roles auth -c /etc/teleport.yaml`

I cannot add a user using google, and I cannot join a node to the cluster using the static token.

```bash
$ sudo tctl users add bryan devuser --identity google:bryan@test.com
OpenID connector 'google' is not configured
```

The dynamo table is created, with these three keys.

  - teleport/authorities/host/staging
  - teleport/authorities/user/staging
  - teleport/authservers/{somehash}

Thanks!

**Comment by klizhentas** [comment]
can you drop these tables, wipe out the state and try again?

**Comment by bshelton229** [comment]
I've done that a few times. I'm also incrementing the table_name to be safe.

I've been following these steps:

  1. Stop the auth server
  1. `rm -rf /var/lib/teleport`
  1. Delete the dynamodb for good measure.
  1. Increment the number in the dynamodb table_name just to make sure
  1. Start the auth server again

I should mention that config works as expected when I comment out the storage engine and use disk. Of course I need to wipe `/var/lib/teleport` on the nodes and re-join.

I'm now using `Teleport v1.2.7-beta git:v1.2.6-108-ga4ff111`

**Comment by bshelton229** [comment]
I booted up with `--debug` here are some snippets that may be helpful.

Looks like `seed_config` is coming in as true.

```
hostuuid: ""
console: 0
reversetunnels: []
oidcconnectors: []
pidfile: ""
trust: null
lock: null
presence: null
provisioner: null
identity: null
seedconfig: true
```

Backend configuration from the debug output.

```
auth:
  enabled: true
  sshaddr:
    addr: 0.0.0.0:3025
    addrnetwork: tcp
    path: ""
  authorities: []
  domainname: staging
  statictokens: []
  keysbackend:
    type: dynamodb
    params: '{"tablename":"staging-test3.teleport.auth","region":"us-west-2","access_key":"...","secret_key":"..."}'
  eventsbackend:
    type: bolt
    params: '{"path": "/var/lib/teleport/events.db"}'
  recordsbackend:
    type: bolt
    params: '{"path": "/var/lib/teleport/records.db"}'
  limiter:
    rates: []
    maxconnections: 1000
    maxnumberofusers: 250
    clock: null
  noaudit: false
  u2f:
    enabled: false
    appid: https://ip-10-1-16-151:3080
    facets:
    - https://ip-10-1-16-151:3080
```
