### ISSUE TITLE
can't startup auth/proxy with etcd backend

### ISSUE THREAD

**Issue by jeremyd** [gravitational/teleport#647]
Error message is:

```
Key: supply a valid root key for Teleport data
```

I've setup the configuration according to the admin guide but I'm unsure what setting it's complaining about.  I can't seem to find a setting that matches "root key" anywhere.  What am I missing?  (my config is below)

```
teleport:
  storage:
    type: etcd
    peers:
      - "https://127.0.0.1:2379"
    tls_cert_file: /ssl/etcd2.pem
    tls_key_file: /ssl/etcd2-key.pem
    tls_ca_file: /ssl/ca.pem
    data_dir: /var/lib/teleport
proxy_service:
  enabled: yes
  https_key_file: /etc/teleport/certs/key.pem
  https_cert_file: /etc/teleport/certs/cert.pem
auth_service:
  enabled: yes
  cluster_name: development
ssh_service:
  enabled: no
```
