### ISSUE TITLE
Document proxy_protocol for Auth and Proxy

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6508]
Currently not documented:

```yaml
auth_service:
   proxy_protocol: on|off
proxy_service:
   proxy_protocol: on|off
```
