### ISSUE TITLE
Document access requests annotations

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6557]
```yaml
kind: role
metadata:
  name: employee
spec:
  allow:
    request:
      # the `roles` list can now be a mixture of literals and matchers
      roles: ['common', 'dev-*']
      # the `claims_to_roles` mapping works the same as it does in
      # the oidc connector, with the added benefit that the mapped to roles
      # can also be matchers.  the below mapping says that users with
      # the claims `groups: admins` can request any role in the system.
      claims_to_roles:
        - claim: groups
          value: admins
          roles: ['*']
      # teleport can attach annotations to pending access requests. these
      # annotations may be literals, or be variable interpolation expressions,
      # effectively creating a means for propagating selected claims from an
      # external identity provider to the plugin system.
      annotations:
        foo: ['bar']
        groups: ['{{external.groups}}']
  options:
    # the `request_access` field can be set to 'always' or 'reason' to tell
    # tsh of the web UI to always create an access request on login.  If it is
    # set to 'reason', the user will be required to indicate *why* they are
    # generating the access request.
    request_access: reason
    # the `request_prompt` field can be used to tell the user what should
    # be supplied in the request reason field.
    request_prompt: Please provide your ticket ID
version: v3
```

The annotations field can pass the values of a claim/trait via variable interpolation, as shown above. 
That will appear under the `system_annotations` field on the actual request.

The `system_annotations` can then be used by the predicates in review system like so:

```yaml
kind: role
# ...
spec:
  allow:
    review_requests:
      roles: ['*-staging']
      claims_to_roles:
        - claim: teams
          value: admin
          roles: ['*-prod']
      where: 'contains(request.system_annotations["teams"],"red")'
```
