### ISSUE TITLE
Better CLI login

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#665]
As Teleport gains more authentication options, `tsh` needs to provide a better experience for users who opt for non-default options (and work out of the box without additional flags), i.e. `tsh login` or `tsh ssh` should work equally well for:

* Auth0 users
* U2F users

**Comment by klizhentas** [comment]
I need this feature to unblock telekube logins that need second factor to be turned off. Here's my proposal:

## New resource type

Introduce new type of resource `ClusterAuthPreference`

* Local authentication without second factor:

```yaml
kind: ClusterAuthPreference
spec:
   auth_type: "local"
   params:
       second_factor:
            enabled: false
```


* Local authentication with U2F factor

```yaml
kind: ClusterAuthPreference
spec:
   auth_type: "local"
   params:
       second_factor:
            enabled: true
            type: u2f
```

* External authentication with OIDC google

```yaml
kind: ClusterAuthPreference
spec:
   auth_type: "oidc"
   params:
       connector_id: "google"
```

## New auth server API method

`GET /v2/cluster-auth-preferences`

is method that does not need authentication and returns the resource value.

tsh client and web proxy can simply read this method to get the values and render the UI form and set command line flags.
