### ISSUE TITLE
oidc error with token_endpoint_auth_signing_alg_values_supported 'none' with Okta

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6705]
### Description

**What happened**:

Attempting to use Okta with OIDC results in errors  about the `token_endpoint_auth_signing_alg_values_supported` value having known.  A prospect needs to use OIDC instead of SAML. 

I see a related issue but not sure if this in the current Teleport codebase.
[https://github.com/coreos/go-oidc/issues/137](https://github.com/coreos/go-oidc/issues/137)

```bash
        token_endpoint_auth_signing_alg_values_supported cannot include 'none'
[AUDIT]     INFO user.login cluster_name:tele1c code:T1001W ei:0 error:[failed to reach out to oidc connector OktaDev, most likely URL "https://<redacted>.okta.com" is not valid or not accessible, check configuration and try to re-create the connector] event:user.login message:failed to reach out to oidc connector OktaDev, most likely URL "https://<redacted>.okta.com" is not valid or not accessible, check configuration and try to re-create the connector method:oidc success:false time:2021-05-03T14:48:16.888Z uid:bc49a3bb-467d-48c1-8729-470d587 events/emitter.go:323
[WEB]       ERRO Error creating auth request. auth:oidc error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError failed to reach out to oidc connector OktaDev, most likely URL &#34;https://<redacted>.okta.com&#34; is not valid or not accessible, check configuration and try to re-create the connector
```

**What you expected to happen**:
OIDC connector would work.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a OIDC Web application in Okta
2. Add a group Developers to map.  Make sure to set regular expression `.*` as part of the groups claim filter.
2. Create a connector in Teleport:
```yaml
kind: oidc
metadata:
  name: OktaDev
spec:
  claims_to_roles:
  - claim: groups
    roles:
    - admin
    value: Developers
  client_id: <redacted>
  client_secret: <reda
  display: OktaDev
  issuer_url: https://<redacted>.okta.com
  redirect_url: https://teleport.exampel.com:3080/v1/webapi/oidc/callback
  scope:
  - groups
version: v2
```

3. Attempt to login

### Server Details
- Teleport version (run `teleport version`): 6.1.3
- Server OS (e.g. from `/etc/os-release`): ubuntu
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws ec2
