### ISSUE TITLE
RFD: enrich claims for OIDC and SAML

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6707]
## Details

Many times admins don't have access to OIDC/SAML identity providers. Teleport should provide a tool similar to Auth0 rules that allows to modify and code claims on the fly.

The approach below is fully declarative, users can define new traits as a code and they can reduce reliance on identity provider. Users can define all claims through teleport, reducing using the identity provider to a simple email database.

## Login rules

We will decouple user's identity from claims we inject. A new resource `login_rule` will define a rule that will be processed right after the OIDC or SAML callback. This rule will be applied to ephemeral user resource that is generated after SAML/OIDC callback.

```yaml
type: login_rule
spec: 
   match:
       user: 'alice@example.com'
   rewrite:
      # sets attribute 'groups': ['admins'] for user alice
      'groups': ['admins']
```

## Removing attributes

Admins can define dynamic rules to add or remove some traits conditionally or unconditionally.

```yaml
type: login_rule
spec:
    match:
        where: contains(user.metadata.traits, 'admin')
   # no admins allowed
    rewrite:
    - remove(user.groups, 'admin')
```

## Rewriting username

Admins can rewrite usernames based on external claims and rules.

```yaml
type: login_rule
spec:
    match:
        where: '*'
    # rewrite user resource from custom trait 'custom-group' instead of email
    rewrite:
    - set(user.metadata.name, user.metadata.traits['custom-group'])
```

### RBAC 

Teams can have limited scope to add/remove attributes for their sub-teams.

```yaml
type: role
spec:
   allow:
      resources: [login_rules]
      - login_rules
      where: # match label
```

## Export claims from third party services

A customer 'acme' has a third-party storage of information about users stored in a third-party database. Build a plugin that syncs claims from postgres database and adds login rules for each user.

Unlike "access request" approach with waiting room, it does not stand in the way of the login flow and will work even if plugins are down.

## Terraform plugin

Add login to terraform plugin to allow users to define the rules declaratively, as a code.
