### ISSUE TITLE
Add acme to full YAML Reference

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#6716]
## Details

Noticed that acme field isn't in the full YAML Reference and should be:

```
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: :443
  public_addr: db.go-teleport.com:443
  https_keypairs: []
  mysql_listen_addr: 0.0.0.0:3036
  acme:
    enabled: "yes"
    email: example@example.com
```
That's helpful in case you forget to pass in the ACME parameter during config or when following the DB Guides (which skip the config step).

Also the `mysql_listen_addr` field. Think some of these may be getting handled programmatically? Will verify some other fields too.

### Category
- Improve Existing
