### ISSUE TITLE
Active Sessions can be seen by a user lacking, even denied those permissions

### ISSUE THREAD

**Issue by tooboredtocode** [gravitational/teleport#6765]
### Description

**What happened**:

A user without the list permission for Active Sessions is able to see all active sessions. Even denying said permission doesn’t change anything.

**What you expected to happen**:

Either of these settings should have prevented the user from viewing the active sessions.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a new role with the following spec:
```yml
spec:
  allow:
    app_labels:
      access-level: "null"
    db_labels:
      access-level: "null"
    kubernetes_labels:
      access-level: "null"
    node_labels:
      access-level: "null"
  deny:
    rules:
    - resources:
      - role
      - auth_connector
      - session
      - trusted_cluster
      - event
      - user
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
version: v3
```
2. Add the role to a user
3. Said user is able to view active sessions

### Server Details
- Teleport version (run `teleport version`): Teleport v6.1.5 git:v6.1.5-0-gdad2a7b5b go1.15.5
- Server OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated Hardware
