### ISSUE TITLE
Roles aren't assigned to a user specified in bootstrap file

### ISSUE THREAD

**Issue by leshik** [gravitational/teleport#6793]
### Description

**What happened**:

I want to pre-create a local admin user with the password and OTP on bootstrap, with editor and access roles assigned, however, it doesn't work. The user is created but assigned the admin role only.

**What you expected to happen**:

I expect the roles specified in `bootstrap.yaml` assigned to the user.

### Reproduction Steps

```yaml
kind: user
metadata:
  name: admin
spec:
  local_auth:
    mfa:
    - addedAt: "2021-05-10T00:00:00Z"
      id: <some uuid>
      kind: mfa_device
      lastUsed: "2021-05-10T00:00:00Z"
      metadata:
        Name: otp
        Namespace: default
      totp:
        key: <some key>
      version: v1
    password_hash: <some hash>
  roles:
  - editor
  - access
  traits:
    logins:
    - root
    - ubuntu
    - ec2-user
version: v2
```

### Server Details
- Teleport v6.1.5 git:v6.1.5-0-gdad2a7b5b go1.15.5
- Official Docker image from quay.io
- Docker
