### ISSUE TITLE
Session permission not honored in Cloud GUI

### ISSUE THREAD

**Issue by blodan** [gravitational/teleport#6814]
### Description
Adding a role to give a user permission to list and read recorded sessions does not work without event permission

**What happened**:
Session recordings menu is not available in cloud web GUI even though user has permissions for it.

**What you expected to happen**:
Session recordings menu should be available when having the session permission

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create new role with below spec in cloud
2. Assign role to a new user
3. The new user should be able to list and play recorded sessions, but the menu is not there

For the `Session recordings` menu to appear you also have to give access to resource `event` with `[ list, read ]` permissions, but that also gives the user access to audit logs which isn't desireable.

```
kind: role
metadata:
  name: test-role
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    node_labels:
       '*': '*'
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
version: v3
```
