### ISSUE TITLE
URL rewrite in application access always adds port 3080 even when apps runs on 443

### ISSUE THREAD

**Issue by rohithmeethal** [gravitational/teleport#6928]
### Description

**What happened**:

I am using https://goteleport.com/docs/application-access/guides/connecting-apps/#rewrite to rewrite internal applications redirects from https://10.0.0.3 to https://app1.teleport.test.com,
but it always add 3080 as port, even when app is running in 443, ie
it gets redirected https://app1.teleport.test.com:3080

**What you expected to happen**:
Expected redirect is https://app1.teleport.test.com:443

### Reproduction Steps
1. Set proxy service to listen on 443
```ini
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: :443
```
2. Add an application
```
app_service:
  enabled: yes
  apps:
    - name: "pmm"
      uri: "https://10.0.0.3"
      insecure_skip_verify: true
      rewrite:
        redirect:
          - "10.0.0.3"
```
3. Access app from web ui

### Server Details
- Teleport version (run `teleport version`): Teleport v6.1.5 git:v6.1.5-0-gdad2a7b5b go1.15.5
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): VPS
