### ISSUE TITLE
Validation failing when adding a connector 

### ISSUE THREAD

**Issue by quinqu** [gravitational/teleport#7017]
### Description

**What happened**:
When adding a connector, validation fails. Teleport doesn't read in the input under `attributes_to_roles`. 

Error: 
`failed to validate: spec.attributes_to_roles: Invalid type. Expected: array, given: null`

Resource file: 

```yaml
kind: saml
version: v2
metadata:
  name: saml-test
spec:
  display: "Microsoft"
  acs: https://<redacted>:3080/v1/webapi/saml/acs
  attributes_to_roles: 
    - {name: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups", value: <redacted>, roles: ["admin"]}
  entity_descriptor: |
```
Also tried

```yaml
kind: saml
version: v2
metadata:
  name: saml-test
spec:
  display: "Microsoft"
  acs: https://<redacted>:3080/v1/webapi/saml/acs
  attributes_to_roles: [{name: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups", value: <redacted>, roles: ["admin"]}]
  entity_descriptor: |
```

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a saml resource file 
2. `tctl create <filename>`

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v6.2.0-alpha.1
- Server OS (e.g. from `/etc/os-release`): Amazon Linux 2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Debug Logs
 No logs
