### ISSUE TITLE
Crazy load on DynamoDB with just 3 users

### ISSUE THREAD

**Issue by leshik** [gravitational/teleport#7088]
### Description

**What happened**:

I'm having a crazy read load on DynamoDB with just 3 users doing almost nothing. Is this normal? Examples suggest max read DynamoDB capacity of 20 rps, but I'm getting more than 100! And there are only 70 items in `teleport.state` table, weird.

<img width="1446" alt="Screen Shot 2021-05-28 at 11 02 58" src="https://user-images.githubusercontent.com/443678/119928115-1f442200-bfa5-11eb-911a-10d97fe1c63a.png">

### Server Details
- Teleport version (run `teleport version`): `6.1.5`
- Server OS (e.g. from `/etc/os-release`): Official Docker image
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by klizhentas** [comment]
@leshik can you try `tctl top` on the auth server, can you post top requests to the backend that bypass cache?

**Comment by leshik** [comment]
@klizhentas not sure where to look at. Now:

![image](https://user-images.githubusercontent.com/443678/120251382-92061380-c2ab-11eb-952c-8748d595c160.png)

This is with just 1 user.

![image](https://user-images.githubusercontent.com/443678/120251414-a3e7b680-c2ab-11eb-8678-dda55e754b48.png)

**Comment by russjones** [comment]
Hi @leshik I tried to reproduce this on 6.1.5 and 6.2.7 and could not. Can you provide more details to help reproduce?

* What were the users doing when you saw high read load on DynamoDB?
* How many active sessions existed?
* Are you running proxies and auth behind a LB?
* Are you using dynamic labels?

**Comment by russjones** [comment]
@leshik Also, how many roles do you have?

**Comment by leshik** [comment]
@russjones

```yaml
teleport:
  nodename: xx-teleport
  advertise_ip: 10.0.85.42
  log:
    output: stderr
    severity: WARN
  storage:
    type: dynamodb
    region: ap-southeast-2
    table_name: teleport.state
    audit_events_uri:  ['dynamodb://teleport.events']
    audit_sessions_uri: s3://xx-teleport/records
auth_service:
  listen_addr: 0.0.0.0:3025
  public_addr: auth.tele.xxx.xxx.com:3025
  cluster_name: xxx
  authentication:
      type: github
  tokens:
  - node:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  keep_alive_interval: 30s
proxy_service:
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:3080
  public_addr: tele.xxx.xxx.com:443
  ssh_public_addr: ssh.tele.xxx.xxx.com:22
  tunnel_public_addr: proxy.tele.xxx.xxx.com:3024
ssh_service:
  listen_addr: 0.0.0.0:3022
```

Users are usually doing nothing extraordinary, sometimes they join each other sessions, typing something in the console, sometimes with a huge output from some commands.

We've just started using Teleport, and there are no more than 3-4 active sessions.

I use AWS NLB to proxy SSH traffic to port 3023, and AWS ELBv2 ALB to proxy HTTP traffic to port 3080.

I don't have dynamic labels.

There's a total of 9 roles that users can request.
