### ISSUE TITLE
How Do I Increase Web UI Terminal Session Time Limit

### ISSUE THREAD

**Issue by ishu-harsh** [gravitational/teleport#7089]
### Description

**What happened**:

How Do I Increase Web UI Terminal Session Time Limit -- It disconnect in a minute if no action happens then I have to Reopen the session every time and its sucks a lot .....at least it should have 5m

**What you expected to happen**:

At least add some proper documentation for  this
we are facing problem jn debugging pur servers. in teleport .. session not expected to expire early

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by webvictim** [comment]
- How is your Teleport cluster deployed and on what platform?
- What version of Teleport are you running?
- Do you see the same timeouts when using `tsh ssh` via the CLI?

**Comment by ishu-harsh** [comment]
1. How is your Teleport cluster deployed and on what platform? 
    
    We deployed Teleport using docker by creating a `docker-compose.yaml`
```
version: '2'
services:
  # The configure container starts, generates a config, writes it to
  # /etc/teleport/teleport.yaml and then immediately exits.
  configure:
    image: quay.io/gravitational/teleport:6.1
    container_name: teleport-configure
    entrypoint: /bin/sh
    hostname: <FQDN>
    command: -c "if [ ! -f /etc/teleport/teleport.yaml ]; then teleport configure > /etc/teleport/teleport.yaml; fi"
    volumes:
      - ./teleport/config:/etc/teleport

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  # This container depends on the config written by the configure container above, so it
  # sleeps for a second on startup to allow the configure container to run first.
  teleport:
    image: quay.io/gravitational/teleport:6.1
    container_name: teleport
    entrypoint: /bin/sh
    hostname: <FQDN>
    command: -c "sleep 1 && /usr/bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
    environment:
      VIRTUAL_HOST: <FQDN>
      VIRTUAL_PORT: 3080
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: <FQDN>
      LETSENCRYPT_EMAIL: <EMAIL>
    depends_on:
      - configure
      - letsencrypt-nginx-proxy-companion
    
````

2. What version of Teleport are you running?

  We are using 6.1 Teleport Version

3. Do you see the same timeouts when using tsh ssh via the CLI?
4. 
  I didn't use tsh
