### ISSUE TITLE
`Error: Object not found` 

### ISSUE THREAD

**Issue by christian-heusel** [gravitational/teleport#7117]
I have the same problem with the following detailed info:
```
chris@pioneer ~ » tsh -d login --proxy=<host>
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/chris/.tsh/keys/<host>/chris-x509.pem" valid until "2021-02-01 10:33:49 +0000 UTC". client/keystore.go:318
DEBU [CLIENT]    SSH cert not available client/api.go:710
INFO [CLIENT]    no host login given. defaulting to chris client/api.go:1035
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/tmp/ssh-XXXXXXr7FKwr/agent.2159" client/api.go:2745
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/chris/.tsh/keys/<host>/chris-x509.pem" valid until "2021-02-01 10:33:49 +0000 UTC". client/keystore.go:318
INFO [KEYAGENT]  Loading SSH key for user "chris" and cluster "<host>". client/keyagent.go:167
DEBU [TSH]       SSH cert not available tsh/tsh.go:1776
DEBU [CLIENT]    not using loopback pool for remote proxy addr: <host>:3080 client/api.go:2706
Enter password for Teleport user chris:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: <host>:3080 client/api.go:2706
DEBU [CLIENT]    HTTPS client init(proxyAddr=<host>:3080, insecure=false) client/weblogin.go:211
Tap any security key
DEBU [CLIENT]    prompting U2F devices with facet "https://<host>:3080" client/mfa.go:129

ERROR REPORT:
Original Error: *trace.NotFoundError object not found
Stack Trace:
        github.com/gravitational/teleport/lib/httplib/httplib.go:131 github.com/gravitational/teleport/lib/httplib.ConvertResponse
        github.com/gravitational/teleport/lib/client/https_client.go:76 github.com/gravitational/teleport/lib/client.(*WebClient).PostJSON
        github.com/gravitational/teleport/lib/client/weblogin.go:415 github.com/gravitational/teleport/lib/client.SSHAgentMFALogin
        github.com/gravitational/teleport/lib/client/api.go:2666 github.com/gravitational/teleport/lib/client.(*TeleportClient).mfaLocalLogin
        github.com/gravitational/teleport/lib/client/api.go:2550 github.com/gravitational/teleport/lib/client.(*TeleportClient).localLogin
        github.com/gravitational/teleport/lib/client/api.go:2214 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
        github.com/gravitational/teleport/tool/tsh/tsh.go:760 main.onLogin
        github.com/gravitational/teleport/tool/tsh/tsh.go:557 main.Run
        github.com/gravitational/teleport/tool/tsh/tsh.go:257 main.main
        runtime/proc.go:225 runtime.main
        runtime/asm_amd64.s:1371 runtime.goexit
User Message: object not found
```
Local teleport version:
```command
chris@pioneer ~ » teleport version
Teleport v6.2.0 git: go1.16.4
chris@pioneer ~ » pacman -Q teleport
teleport 6.2.1-2
```

Teleport on proxy:
```command
root@apple ~ # teleport version
Teleport v6.2.1 git:v6.2.1-0-gbada2617a go1.15.5
```

Teleport on auth:
```command
root@spinach: ~ # teleport version                                                                                                                                                                                     
Teleport v6.2.1 git:v6.2.1-0-gbada2617a go1.15.5
```

_Originally posted by @christian-heusel in https://github.com/gravitational/teleport/discussions/6967#discussioncomment-801376_

**Comment by awly** [comment]
Some more relevant info is in https://github.com/gravitational/teleport/discussions/6967#discussioncomment-812193
Per the discussion there, it does not appear to be directly MFA-related, as logging in with `second_factor: off` still fails.

**Comment by christian-heusel** [comment]
Continuing to debug here:

> Sorry for the delay.
> Can you try creating a brand new user (tctl users add ...) and logging in with that?
> I wonder if something about your user state got corrupted in the storage backend.

I tried and the error is the exact same one. (with and without `second_factor: off`)

**Comment by christian-heusel** [comment]
I guess there are no news on this?
Maybe I could add that the issue persists even with all systems updated to the new teleport verison and that the issue only occurs on the commandlinetool ... Web is all fine 🌐

**Comment by awly** [comment]
Sorry, this fell through the cracks.
@christian-heusel can you also check the CLI version using `tsh version` instead of `teleport version`?
If that looks fine, what is the output of `tctl get users/chris` on the auth server?

**Comment by christian-heusel** [comment]
`$ tsh version`

```cmd
Teleport v6.2.7 git:v6.2.7-0-g4f8a0007f go1.15.5
```
`$ tctl get users/chris`

```yaml
root@spinach: ~
# tctl get users/chris                                                  [21:20:40]
kind: user
metadata:
  id: 1621002034587554935
  name: chris
spec:
  created_by:
    time: "2021-05-14T14:20:34.587190934Z"
    user:
      name: 020b0b38-a246-4685-b39d-ddab74ef53b7.MathPhysInfo
  expires: "0001-01-01T00:00:00Z"
  roles:
  - admin
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
  traits:
    logins:
    - root
    - chris
version: v2
```
