### ISSUE TITLE
Bootstrapping GitHub connector and roles in OSS does not skip migration

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#7134]
### Description

**What happened**:
I'm trying to bootstrap Teleport OSS with a GitHub connector and two Teleport roles using the `--bootstrap` flag. However, Teleport creates two new roles based off of the two roles that I have in my bootstrap file. The GitHub connector then references these roles created by Teleport rather than the ones from the bootstrap file. The roles created by Teleport are also not respecting the allow label rules contained in the roles that are in the boostrap file. For example, here is a role in the bootstrap file:
```
    kind: role
    version: v3
    metadata:
      name: engineering
    spec:
      allow:
        logins: []
        app_labels:
          tenant: engineering
```
And then this is what Teleport creates based off of that:
```
kind: role
metadata:
  id: 1622567757392505730
  name: github-f8f42be0-8321-4ec0-948f-46721a7bf650
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_labels:
      '*': '*'
    logins:
    - engineering
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
The role created by Teleport is not respecting the `allow` labels in the bootstrap file's role and is also adding a `login`. This seems to be the code doing that: https://github.com/gravitational/teleport/blob/b2494bea8eea95f891be929f6ca9ca8ab7e49ea8/lib/auth/init.go#L734

`tctl create -f <file>` also produces the same result.

**What you expected to happen**:
I expect Teleport to start with my GitHub connector and use the two roles that are in my bootstrap file. Role migration should be skipped: https://github.com/gravitational/teleport/blob/b2494bea8eea95f891be929f6ca9ca8ab7e49ea8/lib/auth/init.go#L610-L612

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Start Teleport with the `--bootstrap` flag. Have a GitHub connector and roles in the file referenced by the `--bootstrap` flag.
2. Use `tctl get all` to view the resources that Teleport has created.
3. The GitHub connector will not be using the roles that are included in the file referenced by the `--bootstrap` flag.
4. `tctl create -f <file>` also produces the same result.

### Server Details
- Teleport version (run `teleport version`): 6.2.0
- Where are you running Teleport? Tried on both Kubernetes and on a server.
