### ISSUE TITLE
Support for access requests, reviews specifications in roles for variable substitution

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7135]
### What
Support  usage of `regexp` functions and external traits in requests and reviews in roles.

```yaml
    request:
      roles:
      - '{{regexp.replace(user.spec.traits[groups-request], ^product(.*)$, "$1-admin")}}'
      - '{{external.additionalroles}}'

    review_requests:
      roles:
     - '{{regexp.replace(user.spec.traits[groups-request], ^product(.*)$, "$1-admin")}}'
```
### How
Extend current role mapping to include these parts of the role to allow usage of functions and external traits.

### Why
Allows for doing dynamic mapping in roles with the traits coming from the SSO>

### Workaround
Manually specifying in roles
