### ISSUE TITLE
Empty roles default to allowing access to all applications

### ISSUE THREAD

**Issue by alexmv** [gravitational/teleport#7227]
### Description

**What happened**:

If I make a role in the web UI with config:
```yaml
kind: role
metadata:
  name: testing-access
spec:
  allow: {}
  deny: {}
version: v3
```
Fetching the config with `tctl get role/testing-access` shows it has actually made:
```yaml
kind: role
metadata:
  id: 1623191134089989653
  name: testing-access
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
...which _grants access to all applications_.

Also, editing it to be:
```yaml
kind: role
metadata:
  id: 1623191134089989653
  name: testing-access
spec:
  allow:
    app_labels: {}
    db_labels: {}
    kubernetes_labels: {}
  deny: {}
version: v3
```
...will _render as in the UI_, if you click "Edit" on the role:
```yaml
kind: role
metadata:
  id: 1623191134089989600
  name: testing-access
spec:
  allow: {}
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
...but _actually be_, via `tctl get role/testing-access`:
```yaml
kind: role
metadata:
  id: 1623192152214230958
  name: testing-access
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
...which means that a role can _masquerade as granting no rights_, but actually _grant access to every application_.

**What you expected to happen**:

A seemingly-empty role should not default to allowing access to everything.

### Reproduction Steps
See above.

### Server Details
- Teleport version (run `teleport version`): `Teleport v6.2.3 git:v6.2.3-0-g3f2dd006c go1.15.5`
- Server OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.2 LTS`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
