### ISSUE TITLE
Improve instructions for configuring self-hosted and cloud databases

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#7265]
### Self-hosted

For self-hosted databases, after generating database secrets with `tctl auth sign`, show the user an example of how to add these secrets to their database configuration right in the CLI.

```
# Postgres
ssl = on
ssl_cert_file = '/etc/certs/server.crt'
ssl_key_file = '/etc/certs/server.key'
ssl_ca_file = '/etc/certs/server.cas'
```

```
# MySQL
[mysqld]
ssl-cert=/etc/certs/server.crt
ssl-key=/etc/certs/server.key
ssl-ca=/etc/certs/server.cas
require_secure_transport=ON
```

```
# Mongo
net:
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/certs/server.pem
    CAFile: /etc/certs/server.cas
```

### RDS/Aurora

When configuring RDS/Aurora, setting up IAM policy causes the most confusion, esp. caused by typos in the ARN string.

Add a command that would ask the user for their RDS cluster name and other information and print the proper policy document for them to add.

Command/UX TBD.

### UI

The current manual instructions in the UI are missing the above steps.

We need to add the configuration/policy to the add database manual dialog.
