### ISSUE TITLE
App access UI tweaks to support AWS console access

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#7349]
## Description

We're working on https://github.com/gravitational/teleport/issues/7027 to add ability to Teleport to automatically sign-in users to AWS management console.

For now, it will be integrated into app access. Users register AWS console as an application. Also, a user may want to register multiple applications for the console to be able to distinct between different accounts, for example:

```yaml
apps:
- name: "aws-stage"
  description: "AWS Management Console Staging"
  uri: "https://console.aws.amazon.com/ec2/v2/home"
  # Users can specify aws_account_id label so we're able to show role ARNs specific to this account, see below.
  labels:
    aws_account_id: 1234
- name: "aws-prod"
  description: "AWS Management Console Production"
  uri: "https://console.aws.amazon.com/ec2/v2/home"
  labels:
    aws_account_id: 4321
```

The role resource also gets an additional property to specify which IAM roles user is allowed to assume:

```yaml
kind: role
metadata:
  name: developer
spec:
  allow:
    aws_role_arns:
    - arn:aws:iam::<acc-id>:role/role-name-1
    - arn:aws:iam::<acc-id>:role/role-name-2
```

## Success criteria

Here are the updates we're looking to make to the Applications UI to support this scenario:

- [x] Currently all application tiles have the same generic icon. For applications representing AWS console we should display AWS icon instead to make them visually distinctive.

- [x] AWS console tiles should provide users with ability to pick the IAM role they want to assume. This is similar to how picking SSH login works on Servers tab. We don't need fancy design for this atm so maybe a simple dropdown would work? Or add the choices to the `...` button in top right corner and disable clicking on the tile.

- [x] After selecting the role, it goes through our normal app access auth flow - but the selected role should be passed to the backend. Not sure what's the best way to do it yet - can it be sent in the "create app session" request?

## New app access screen

It looks like Alex's designs for new application access screen are pretty much ready.

So as an option we could implement ^^ above ^^ things together with the new app access screen - that would probably solve the issue with "where to display role ARNs" since it will be basically table view like servers.

If you think new app access screen is going to take long though, tweaking current tile-based screen for now would work as well.
