### ISSUE TITLE
Github auth connector failed to validate spec.teams_to_logins

### ISSUE THREAD

**Issue by dboslee** [gravitational/teleport#7496]
### Description

**What happened**:
I am able to create a github auth connector without specifying `spec.teams_to_logins`. This causes the value to default to null and breaks get requests to the authconnectors endpoint.

```failed to validate: spec.teams_to_logins: Invalid type. Expected: array, given: null```

![image](https://user-images.githubusercontent.com/8069401/124834371-e0f33880-df3c-11eb-9457-d77745017ac4.png)

**What you expected to happen**:
If `spec.teams_to_logins` is null the value should default to an empty array or not be accepted to begin with.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Navigate to `Teams` -> `Auth Connectors`
2. Click `NEW AUTH CONNECTOR` and then `GITHUB AUTH CONNECTOR`
3. Delete everything nested under `teams_to_logins` from the spec and click `SAVE CHANGES`

Here is an example that causes the error
```
kind: github
version: v3
metadata:
  name: new_github_connector
spec:
  client_id: <client-id>
  client_secret: <client-secret>
  redirect_url: "https://<cluster-url>/v1/webapi/github/callback"
  display: Github
```

### Server Details
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): This instance is running in the teleport cloud staging environment.
