### ISSUE TITLE
Github login failed with "unable to process callback"

### ISSUE THREAD

**Issue by ri0day** [gravitational/teleport#7498]
### Description

**What happened**:
i followed docs from https://goteleport.com/docs/kubernetes-access/getting-started/
configured connector to github
this is my connector config:

```yaml
kind: github
metadata:
  name: github
spec:
  client_id: dfcdb7aac85de7c7232c
  client_secret: ""
  display: Github
  redirect_url: https://tele-demo.shijicloud.com:443/v1/webapi/github/callback
  teams_to_logins:
  - logins:
    - member
    - access
    organization: devops-zoo
    team: teleport-team1
version: v3
```
however , when i login , i got an error page say "**unable to process callback**"
after that ,i fond following logs from teleport server
```json
{"ei":0,"event":"user.login","uid":"38602f2e-8caa-44cc-8af9-4a3757ccd067","code":"T1001W","time":"2021-07-08T08:22:40.22Z","cluster_name":"tele-demo.shijicloud.com","success":false,"error":"list of user teams is empty, did you grant access?","message":"list of user teams is empty, did you grant access?","method":"github"}
```
actually ,the team i configured in connector has 2 members .the logs indicate that teleport seems can not get member infomation from github
 
![image](https://user-images.githubusercontent.com/475184/124891043-31d16280-e00b-11eb-80c6-f32eaa4b7339.png)

**What you expected to happen**:

I expected successfully login

### Server Details
- Teleport version: Teleport v6.2.7 git:v6.2.7-0-g4f8a0007f go1.15.5
- Where are you running Teleport? : AWS EKS

### Client Details
- Tsh version : Teleport v6.2.7 git:v6.2.7-0-g4f8a0007f go1.16.2
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues):chrome
- Installed via (e.g. apt, yum, brew, website download): download

**Comment by travelton** [comment]
@ri0day Generally this means that the Github user you're logging in with is not associated with the configured team. Please double-check that the member has been added to the team. I see your screenshot, but it's not clear if the user is a member of this team. If you're still having trouble, log out and log in to Github again. Perhaps try an Incognito or Private browsing session to ensure no cookies/sessions are interfering. If you're still having trouble, please email support@goteleport.com or join us in [Slack](https://goteleport.com/slack) so we can capture more information.

**Comment by ri0day** [comment]
hi travelton ,thanks 
i tired re-login ,and using Incognito mode .but problem still ,
 btw ,iam the owner of organization and team . i also tried  login with my colleage github account ,he is an member of team but still failed we same error

**Comment by travelton** [comment]
@ri0day Ok, you can enable debug logging mode, on the host running the Teleport Proxy and Auth services, to determine if a more detailed error is output to the Teleport service logs. 

Within the `/etc/teleport.yaml` configuration file, update the logging severity to DEBUG. Please see the config [reference](https://goteleport.com/docs/config-reference/) for specifics on logging configuration. 

```
teleport:
    log:
        output: <output location>
        severity: DEBUG
```

Next, restart your Teleport services. Generally `systemctl restart teleport` on both Auth and Proxy services. Reproduce the problem. Then review the logs for any additional details. Feel free to send them over to support@goteleport.com, and we will analyze them for you.
