### ISSUE TITLE
Teleport errors on Azure AKS

### ISSUE THREAD

**Issue by kseniyashaydurova** [gravitational/teleport#7561]
### Description

**What happened**:

Can't make Teleport work inside Azure AKS and have following errors:

1. Errors inside `teleport` pod:

> ERRO             read tcp 10.240.1.235:3024->10.240.0.226:54269: read: connection reset by peer sshutils/server.go:667
> ERRO             read tcp 10.240.1.235:3023->10.240.0.226:51633: read: connection reset by peer sshutils/server.go:667
> ERRO             read tcp 10.240.1.235:3023->10.240.0.4:27373: read: connection reset by peer sshutils/server.go:667
> ERRO             read tcp 10.240.1.235:3024->10.240.0.4:1980: read: connection reset by peer sshutils/server.go:667
> WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 10.240.1.235:3080-&gt;10.240.0.226:20995: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 10.240.1.235:3080-&gt;10.240.0.226:20995: i/o timeout" multiplexer/multiplexer.go:209
> WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 10.240.1.235:3026-&gt;10.240.0.226:39541: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 10.240.1.235:3026-&gt;10.240.0.226:39541: i/o timeout" multiplexer/multiplexer.go:209
> WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 10.240.1.235:3080-&gt;10.240.0.4:22337: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 10.240.1.235:3080-&gt;10.240.0.4:22337: i/o timeout" multiplexer/multiplexer.go:209
> WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 10.240.1.235:3026-&gt;10.240.0.4:34276: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 10.240.1.235:3026-&gt;10.240.0.4:34276: i/o timeout" multiplexer/multiplexer.go:209

2. Errors in `ingress-nginx` when try to call ping from console 
command - `curl https://teleport.cinemacalculator.christiedigital.com/webapi/ping`

> 2021/07/15 02:24:02 [error] 4032#4032: *12320855 SSL_do_handshake() failed (SSL: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:SSL alert number 80) while SSL handshaking to upstream, client: 10.240.1.192, server: teleport.cinemacalculator.christiedigital.com, request: "GET /webapi/ping HTTP/2.0", upstream: "https://10.240.1.235:3080/webapi/ping", host: "teleport.cinemacalculator.christiedigital.com"
> 2021/07/15 02:24:02 [error] 4032#4032: *12320855 SSL_do_handshake() failed (SSL: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:SSL alert number 80) while SSL handshaking to upstream, client: 10.240.1.192, server: teleport.cinemacalculator.christiedigital.com, request: "GET /webapi/ping HTTP/2.0", upstream: "https://10.240.1.235:3080/webapi/ping", host: "teleport.cinemacalculator.christiedigital.com"
> 2021/07/15 02:24:02 [error] 4032#4032: *12320855 SSL_do_handshake() failed (SSL: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:SSL alert number 80) while SSL handshaking to upstream, client: 10.240.1.192, server: teleport.cinemacalculator.christiedigital.com, request: "GET /webapi/ping HTTP/2.0", upstream: "https://10.240.1.235:3080/webapi/ping", host: "teleport.cinemacalculator.christiedigital.com"
> 10.240.1.192 - - [15/Jul/2021:02:24:02 +0000] "GET /webapi/ping HTTP/2.0" 502 150 "-" "curl/7.77.0" 61 0.009 [teleport-cluster-teleport-3080] [] 10.240.1.235:3080, 10.240.1.235:3080, 10.240.1.235:3080 0, 0, 0 0.004, 0.004, 0.004 502, 502, 502 c635a5f61002885754a88b230d9dfcf9

**What you expected to happen**:

I expect that there would be no issues inside teleport pod and I would be able to connect to teleport with `curl` or web.

### Details

1. Teleport is installed from the Helm Chart as ArgoCD app: 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "80"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-cluster
  project: default
  source:
    chart: teleport-cluster
    helm:
      values: |
        clusterName: teleport.cinemacalculator.christiedigital.com
        acme: true
        acmeEmail: devops+cpca@saritasa.com
        teleportVersionOverride: 6.2.1
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            teleport.cinemacalculator.christiedigital.com:
              - /
          tls:
           - secretName: teleport.cinemacalculator.christiedigital.com-crt
             hosts:
              - teleport.cinemacalculator.christiedigital.com
          proxy:
            tls:
              enabled: true
              usetlssecret: true
              secretName: teleport.cinemacalculator.christiedigital.com-crt

    repoURL: https://charts.releases.teleport.dev
    targetRevision: 6.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

2. ConfigMap teleport.yaml
```
apiVersion: v1
items:
- apiVersion: v1
  data:
    teleport.yaml: |
      teleport:
        log:
          severity: INFO
          output: stderr
      auth_service:
        enabled: true
        cluster_name: teleport.cinemacalculator.christiedigital.com
      kubernetes_service:
        enabled: true
        listen_addr: 0.0.0.0:3027
        labels:
      proxy_service:
        public_addr: 'teleport.cinemacalculator.christiedigital.com:443'
        kube_listen_addr: 0.0.0.0:3026
        enabled: true
        acme:
          enabled: true
          email: devops+cpca@saritasa.com
      ssh_service:
        enabled: false
  kind: ConfigMap
  metadata:
    creationTimestamp: "2021-07-15T02:34:23Z"
    labels:
      argocd.argoproj.io/instance: teleport
    name: teleport
    namespace: teleport-cluster
    resourceVersion: "19079639"
    selfLink: /api/v1/namespaces/teleport-cluster/configmaps/teleport
    uid: be78762f-a544-49f2-9456-7e92d68fab60
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
