### ISSUE TITLE
Add MFA session caching when using K8s commands/api calls.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7568]
### What
Currently with how session MFA is built if a user is using K8s they will be prompted multiple times to authenticate due to how each K8s request is an API call and considered a 'session'. 

This can become burdensome and an undesirable user experience.

More discussion here -  
- https://goteleport.slack.com/archives/CEZH6UL64/p1626269159436900
- https://goteleport.slack.com/archives/CEZH6UL64/p1626269832437300

### How

Implement a session caching or something so that with K8s requests the user will not be asked for re-authenticating all the time. Have a configurable option in the MFA settings to set a cache time limit.

### Why
Improve user experience.

### Workaround

None.

**Comment by GavinFrazar** [comment]
I just want to add for future reference that the workaround here is to disable per-session MFA for k8s resources. For example, make a templated role for k8s access that does not require per-session-MFA:

```yaml
kind: role
metadata:
  name: kube-role
version: v5
spec:
  allow:
    kubernetes_labels:
      "*": "*"
    kubernetes_groups:
      - "{{internal.kubernetes_groups}}"
    kubernetes_users:
      - "{{internal.kubernetes_users}}"
  deny: {}
  options:
    require_session_mfa: false
```

And disable per-session MFA in cluster auth preference:
```yaml
kind: cluster_auth_preference
metadata:
  name: cluster-auth-preference
spec:
  allow_local_auth: true
  disconnect_expired_cert: true
  locking_mode: best_effort
  second_factor: "on"
  require_session_mfa: false
```

Then you can enable per-session MFA for other resources by creating roles allowing non-kube resource labels with the option enabled.
