### ISSUE TITLE
Authentication configuration 2.0

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#757]
## Overview

Teleport 2.0 and the future versions will be gaining more and more ways to authenticate users. The current configuration format in `teleport.yaml` is not scalable to future additions. This ticket is about refactoring auth configuration and making it compatible with dynamic configuration as employed by `telekube`.

There are two components to this ticket:

* YAML configuration format changes
* Dynamic configuration interface via "resources" for cases when Teleport is used as a library, as it is by `telekube`.

## YAML changes

We need to support the new/refreshed YAML configuration without breaking backwards compatibility with existing config files out there.

#### Old Format

The current (soon to be old) config looks roughly like this:

```yaml
auth_service:
  oidc_connectors: []
  u2f:
    enabled: "yes"
    app_id: https://graviton:3080
    facets:
    - https://graviton:3080
```

There are several problems with this:
* How do you disable 2nd factor completely?
* How do you switch between u2f and OTP?
* How do you add support for SAML2 or LDAP?
* What happens if there are multiple OIDC connectors? Which one to use?

The new format proposes a dedicated `authentication` subsection to `auth_service` section.

#### New Format

Below is the new format. Note that:
* New subsection is called `authentication`
* 2nd factor can be turned on/off or switched to u2f 

```yaml
# local auth with OTP
auth_service:
    authentication:
        type: local
        second_factor: otp  # also valid are "utf" or "off" or "false"

# local auth without OTP
auth_service:
    authentication:
        type: local
        second_factor: off 

# local auth with U2F
auth_service:
    authentication:
        type: local
        second_factor: u2f 
        u2f:
            app_id: https://graviton:3080
            facets:
            - https://graviton:3080

# OIDC without 2nd factor
auth_service:
    authentication:
        type: oidc
        oidc:
            name: google
            redirect_url: https://localhost:3080/v1/webapi/oidc/callback
            client_id: id-from-google.apps.googleusercontent.com
            client_secret: secret-key-from-google
            issuer_url: https://accounts.google.com
            display: "whaterver"
            scope: ["ssh_permissions", "roles"]
            permissions: 
                - claim: role
                  value: admin
                  roles: ["dba", "backup", "root"]

# LDAP with OTP 2nd factor
auth_service:
    authentication:
        type: ldap
        second_factor: otp
        ldap:
            name: <ldap-name>
            ldap_setting: value # TBD
            scope: ["ssh_permissions", "roles"]
            permissions: 
                - claim: role
                  value: admin
                  roles: ["dba", "backup", "root"]
```

## Dynamic Configuration

The `authentication` section when parsed on the backend get translated into two resources:

1. ClusterAuthPreference

In case of OIDC:

```yaml
# ldap-settings-resource.yaml
kind: ClusterAuthPreference
metadata:
   # for this resource name can not be other than this name
   # to avoid confusion
    name: cluster-auth-prerference
spec:
    type: oidc
    oidc: google
```

and OIDC connector (that is already defined resource with its own API). Also this resource can not be deleted, only updated via `tctl update -f`

and connector resource:

```yaml
kind: OIDCConnector
metadata:
   name: 
spec:
  name: google
  redirect_url: https://localhost:3080/v1/webapi/oidc/callback
  client_id: id-from-google.apps.googleusercontent.com
  client_secret: secret-key-from-google
  issuer_url: https://accounts.google.com
  display: "whaterver"
  scope: ["ssh_permissions", "roles"]
  permissions: 
    - claim: role
      value: admin
      roles: ["dba", "backup", "root"] 
```

Notice the `kind`, `metadata` and `spec` fields: they are standard for all "resources", i.e. arbitrary YAML-defined objects that Teleport understands. Other types of resources include users, roles, tunnels, etc. `metadata` can hold arbitrary values.

Resources is how Teleport can be configured dynamically (AKA programmatically), by calling something like `tctl create -f ldap-settings-connector.yaml`
