### ISSUE TITLE
CLI login should ask for server's version and auth info

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#758]
## Description

Teleport can be configured with various authentication back-ends (LDAP, local DB, OAuth2, etc). In addition to that, the 2nd factor can be on, off or via u2f. 

Currently the CLI client has no idea how to authenticate a user and it requires a CLI flag to select a method of authentication. This makes it cumbersome to use (why ask user for the auth method if the server already knows?).

## Proposal

The CLI client, before even asking anything, should first request the authentication type from the server. Then, based on the returned information, it should ask the user appropriate questions.

## Implementation

The client already makes an `HTTP GET /ping` call to the proxy server before asking a user for a password. The "ping" call was originally added to determine if HTTPs connection is secure and functional. `/ping` currently returns an empty page. 

Instead `/ping` should return a JSON structure of the following format:

```yaml
kind: ServerInfo
metadata:
    whatever: value
version: 2.0.1-beta-a # should be the same as $(teleport version)
authentication:
     type: local
     second_factor: u2f 
     ...
```

**NOTE** the contents of `authentication` section should contain the _safe subset_ of the `authentication` section in the configuration as shown in #757 - enough for the client to do its job but nothing else (@klizhentas need your input here).
