### ISSUE TITLE
Document claims to roles

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7586]
### What

https://github.com/gravitational/teleport/pull/7538#pullrequestreview-706840107

**Comment by klizhentas** [comment]
Followup about reducing requestor roles:

The claims_to_roles mapping lets you use a combination of regex capture groups and variable substitution to map claims from your identity provider to requestable roles.  Ex:
```
kind: role
metadata:
  name: requestor
spec:
  allow:
    request:
      claims_to_roles:
        - claim: 'teams'
          value: '^team-(.*)$'
          roles: ['role-$1']
version: v3

```

In the above example, if a user had claims of the form `"teams": ["team-foo", "team-bar"]`, they would therefore be able to request the roles role-foo and role-bar.
The syntax works the same for reviewing requests:
```
kind: role
metadata:
  name: reviewer
spec:
  allow:
    review_requests:
      claims_to_roles:
        - claim: 'teams'
          value: '^team-(.*)$'
          roles: ['role-$1']
version: v3
```
Docs are in the process of being updated for `request.claims_to_roles` and `review_requests.claims_to_roles`
