### ISSUE TITLE
NO TLS Keys provided

### ISSUE THREAD

**Issue by noriuky** [gravitational/teleport#759]
Hi, this is my /etc/teleport folder contain:
```
-rw-r--r--   1 root root  teleport.crt
-rw-r--r--   1 root root  teleport.key
-rw-r--r--   1 root root  teleport.yaml
```

this is teleport.yaml:

```
auth_service:
 enabled: true
 tokens:
 - "proxy,node:(((some long key blah blah numbers)))"
teleport:
  advertise_ip: 128.199.243.4
  https_key_file: /etc/teleport/teleport.key
  https_cert_file: /etc/teleport/teleport.crt
```

this is my /etc/systemd/system/teleportd.service:

```
[Unit]
Description=Teleport SSH Service
After=network.target
[Service]
Type=simple
Restart=always
ExecStart=/usr/local/bin/teleport start --config=/etc/teleport/teleport.yaml
[Install]
WantedBy=multi-user.target
```

this is the result of system teleportd status:
```
Redirecting to /bin/systemctl status  teleportd.service
  teleportd.service - Teleport SSH Service
   Loaded: loaded (/etc/systemd/system/teleportd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-02-08 11:08:45 UTC; 1h 1min ago
 /usr/local/bin/teleport[5692]: time="2017-02-08T11:08:45Z" level=
warning msg="[CONFIG] NO TLS Keys provided, using self signed ### certificate"
```
WHY dont load my SSL key and crt files?
tnx
