### ISSUE TITLE
Error connecting App service - GetClusterNetworkingConfig not implemented

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#7623]
Error when connecting an app service using teleport `v7.0.0-beta.2`. The app starts successfully with `v6.0.1`.

 The auth server is running in eks with server version is 6.2.7, which is why `GetClusterNetworkingConfig` is unimplemented. However `teleport start` should be backwards compatible with `v6` versions of teleport.
```
ERROR REPORT:
Original Error: *trace.NotImplementedError unknown method GetClusterNetworkingConfig for service proto.AuthService
Stack Trace:
	/home/bjoerger/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:1475 github.com/gravitational/teleport/api/client.(*Client).GetClusterNetworkingConfig
	/home/bjoerger/gravitational/teleport/lib/auth/clt.go:1628 github.com/gravitational/teleport/lib/auth.(*Client).GetClusterNetworkingConfig
	/home/bjoerger/gravitational/teleport/lib/cache/cache.go:1080 github.com/gravitational/teleport/lib/cache.(*Cache).GetClusterNetworkingConfig
	/home/bjoerger/gravitational/teleport/lib/srv/app/server.go:219 github.com/gravitational/teleport/lib/srv/app.New
	/home/bjoerger/gravitational/teleport/lib/service/service.go:3162 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initApps.func1
	/home/bjoerger/gravitational/teleport/lib/service/supervisor.go:457 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	/home/bjoerger/gravitational/teleport/lib/service/supervisor.go:246 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: unknown method GetClusterNetworkingConfig for service proto.AuthService
```

teleport.yaml:
```
teleport:
  data_dir: /specific/local/dir/
  auth_token: random_app_token
  auth_servers:
  - proxy.example.com:443
app_service:
    enabled: yes
    debug_app: true
    apps:
    - name: "kubernetes-dashboard"
      uri: "http://localhost:8001"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
```
