### ISSUE TITLE
Remove Double Quotes from Acme Email

### ISSUE THREAD

**Issue by blake-teleport** [gravitational/teleport#7630]
### Description

If double quotes are used for the acme email, the acme cert will not be issued.
```bash
TLS handshake error from 18.224.38.78:51626: 400 urn:ietf:params:acme:error:invalidEmail: Error creating new account :: contact email [\"mailto:“blake.brown@goteleport.com\\\"\"] contains non-ASCII characters\n" utils/cli.go:
```

**What you expected to happen**:
Quotes would be ignored like the other fields in teleport.yaml, such as  public_addr.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup a proxy service and have the below formatting

```yaml
proxy_service:
  enabled: "yes"
  web_listen_addr: ":443"
  public_addr: "teleport.example.com:443"
  acme:
    enabled: "yes"
    email: "alice@example.com"
```

### Server Details
- Teleport version (run `teleport version`): 6.2.7
- Server OS (e.g. from `/etc/os-release`): Amazon Linux
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
