### ISSUE TITLE
Optional setting for second factor only allows OTP for new user

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7670]
### Description

**What happened**:
If you set the `second_factor` to `optional` and create a new invite you only see the Google auth option.

![image](https://user-images.githubusercontent.com/60704961/126822270-8ccd3721-b6ac-4d56-8c1b-f9494dcf1074.png)

**What you expected to happen**:

Users can use U2F on creating their user, not just OTP.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set the `second_factor` as optional
```yaml
  authentication:
    type: local
    second_factor: optional
        # this section is used if second_factor is set to 'u2f'
    u2f:

      app_id: https://samdemo2.teleportdemo.com:443
      facets:
      - https://samdemo2.teleportdemo.com:443
      - https://samdemo2.teleportdemo.com
      - samdemo2.teleportdemo.com:443
      - samdemo2.teleportdemo.com    
```
2. Create a new user `tctl users add --roles=admin jeff`
3. Navigate to link.  Only the OTP option will show

### Server Details
- Teleport version (run `teleport version`): 6.2.8
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
