### ISSUE TITLE
Allow regex matching and interpolation together

### ISSUE THREAD

**Issue by colinedwardwood** [gravitational/teleport#7729]
### What
Teleport should allow complex combinations of regex and interpolation for node labels, users, etc. 

### How
For example:

```
kind: role
version: v3
metadata:
  name: interpolation_and_regex
spec:
  allow:
    logins: ['{{external.logins}}', 'admin']
    node_labels:
      'name': '^dev.{{external.access}}.*$'
    database_users: ['^{{email.local(external.email)}}/.*$']
    database_labels:
      'id': '{{external.db_grants}}'
```
In this example, the trait is interpolated into the regexp and then matched. For node_labels, we might want to allow external.access to be a prefix of which nodes could be accessed. Similarly for database_users, where the trait is a prefix that matches the username, which might be randomly generated: james.y/abc123.
The trait may need to be escaped, either by Teleport or externally. Or, Teleport can allow the trait to be a regexp.

**Comment by jamesye-canva** [comment]
A use-case for this is to grant access to a set of related but distinctly labelled nodes through traits, but without needing to individually specify each label. For example, the trait `server.*` will grant access to `server1`, `server2`, etc. Or, the trait `.*-search` will grant access to `app1-search`, `app2-search`, etc. This would be the main use-case for us.

A second use-case could be to allow a user to connect to a database with a username that has a known prefix, but a randomly generated suffix. For example, the random suffix in the username `dbadmin-52a73f1` could be used to identify different "sessions" of a user on different databases externally to Teleport. (Though since Teleport has its own session IDs, this could be redundant.)

If the entire trait can be treated as a regex, that would be more flexible as we would be able to manage permissions almost entirely through SSO and traits, using a few preset Teleport roles that won't need to be modified to change user permissions.

**Comment by jamesye-canva** [comment]
Our installation of Teleport can be considered a retrofit into an environment with over 1000 machines running at any time. Our RBAC policies will be primarily derived from the EC2 instances' `Name` tag. At present count there are almost 100 unique names, although about 50 of those are closely related and are likely to be accessed by a particular set of engineers.

Our application of RBAC thus far has mostly considered resource "names" of some kind, and changing this with the implementation of Teleport wasn't a goal for us. But you're right, using a kind of `group` label would be a better way to fulfill our requirements, and that is something we may be able to explore down the line.

In terms of implementation and this request itself, regex capabilities are not required, and glob-style matching (`?` and `*`) would work for us.

**Comment by jamesye-canva** [comment]
> In terms of matching labels with wildcards or regexes, this should be doable without any changes to Teleport:

Yeah, I think we can make it work with interpolation + wildcards. We might use a role like this:

```yaml
kind: role
version: v4
metadata:
  name: example
spec:
  allow:
    logins:
    - '{{external.logins}}'
    node_labels:
      name:
      - '{{external.access}}'         # exact values only
      - '{{external.access_prefix}}*' # match prefixes
      - '*{{external.access_suffix}}' # match suffixes
```

If any entry of `external.access` contains the `*` character, would this be treated literally?
