### ISSUE TITLE
Support github cert extensions

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7830]
### What

https://docs.github.com/en/organizations/managing-git-access-to-your-organizations-repositories/about-ssh-certificate-authorities

Teleport needs to issue a cert with a custom extension to support the flow

### How
How would you implement this?

### Why
Why do you need this?

### Workaround
If a workaround exists, please include it.

**Comment by jdconti** [comment]
Any targeted release for these extensions? Is the plan to support github and/or other arbitrary certificate extensions via external SAML assertions / OIDC claims?  Thanks!

**Comment by klizhentas** [comment]
I suggest we go the tsh extensions route, similarly to how kubectl does it. If there is an extension, we can call it before the login to add extra fields to certificate signing request.

**Comment by russjones** [comment]
@klizhentas Are you thinking about a UX like `kubectl` where you place a program with `tsh-` prefix somewhere in your PATH?

I think that would require the plugin be configured on each developer workstation to inject the users GitHub login into the CSR.

What if we extended the `options` field on roles allow injection key value pairs that can be filled in with claims? This would allow to fill out extensions with information coming from your IdP.

```yaml
kind: role
metadata:
  name: developer
spec:
  options:
     extensions:
         key_name: "{{ external.github_login }}"
```

**Comment by somethingnew2-0** [comment]
Similar to https://github.com/gravitational/teleport/issues/5275

**Comment by klizhentas** [comment]
Github extensions:

https://docs.github.com/en/organizations/managing-git-access-to-your-organizations-repositories/about-ssh-certificate-authorities

**Comment by klizhentas** [comment]
There are two possible ways to define extensions for client cert:

* Client may request a new certificate with additional fields
* Server (auth) may be configured to add certificates

On top of that, RBAC should enforce what certificate extensions are allowed.

(I will keep on adding thoughts later)

**Comment by russjones** [comment]
@klizhentas Should a client be allowed to request additional fields for their certificate?

If we think about the GitHub example, wouldn't that allow any user to spoof any other user?

**Comment by klizhentas** [comment]
@russjones good point. I'm leaning towards the simple solution that you have proposed, but with a couple of format tweaks:

```yaml
kind: role
metadata:
  name: developer
spec:
  options:
     cert_extensions:
     - type: ssh | x509 # only support ssh for now
        mode: extension | critical_option # only support extension for now
        name: login@github.com
        value: "{{ external.github_login }}" # support variable interpolation
    - type: x509
```
