### ISSUE TITLE
Regexp with external traits

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7870]
Consider a pattern:

```yaml
allow:
   node_labels:
       env: "^(dev|prod).{{external.team}}.env$"
```

This pattern allows any team member of team `acme` to have access to nodes labeled with `dev.acme.env` or `prod.acme.dev`
