### ISSUE TITLE
A `awsconsole-prod` that's not in my teleport.yaml

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#7901]
### Description

**What happened**:

I only have 'awsconsole-test` and not prod, but I've two entries in my Application page. 

![image](https://user-images.githubusercontent.com/559288/129286311-e6b40d5c-252c-4063-a870-b98fbfe555a9.png)

```
        app_service:
            enabled: yes
            debug_app: true
            apps:
              # Name of the application. Used for identification purposes.
            - name: "grafana"
              uri: "http://${grafana_uri}:3000"
              labels:
                env: "prod"
            - name: "metabase"
              uri: "http://${metabase_uri}:3000"
              labels:
                env: "prod"
            - name: "jenkins"
              uri: "http://${jenkins_uri}:8080"
              labels:
                env: "prod"
            - name: "awsconsole-test"
              uri: "https://console.aws.amazon.com/cloudwatch/home"
              labels:
                aws_account_id: "${aws_account_id}"
                env: test         
```

**What you expected to happen**:
