### ISSUE TITLE
Locked time status value not set in user after locked

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7968]
### Description

**What happened**:

After a user is locked for too many bad password attempts the `locked_time` field is not set when it was locked.

`tctl get users/steven`                                                                                                                                              `

```yaml
kind: user
metadata:
  id: 1629298269948676973
  name: steven
spec:
  created_by:
    time: "2021-08-18T14:33:34.141874865Z"
    user:
      name: steven@example.com
  expires: "0001-01-01T00:00:00Z"
  roles:
  - admin
  - access
  - editor
  status:
    is_locked: true
    lock_expires: "2021-08-18T15:11:09.948617733Z"
    locked_message: user has exceeded maximum failed login attempts
    locked_time: "0001-01-01T00:00:00Z"
  traits:
    logins: null
```

**What you expected to happen**:

The `locked_time` value should be set.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.  Create a local user  `tctl users add --roles=access jeff`
2. Attempt to login until the user record `tctl get users/jeff` shows `is_locked`
3.the `locked_time` will not be set

### Server Details
- Teleport version (run `teleport version`): 7.0.3
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:
