### ISSUE TITLE
Set user status to unlocked after lock expiration and successful login

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7972]
### Description

**What happened**:

The user status remains locked after a user has logged in and their original lock has expired.  This causes confusion since they're no longer in a locked status.

```yaml
kind: user
metadata:
  id: 1629298269948676973
  name: steven
spec:
  created_by:
    time: "2021-08-18T14:33:34.141874865Z"
    user:
      name: steven@example.com
  expires: "0001-01-01T00:00:00Z"
  roles:
  - admin
  - access
  - editor
  status:
    is_locked: true
    lock_expires: "2021-08-18T15:11:09.948617733Z"
    locked_message: user has exceeded maximum failed login attempts
    locked_time: "0001-01-01T00:00:00Z"
  traits:
    logins: null
```
**What you expected to happen**:

A user's status would change to locked is `false` after a successful login.  

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a local user
2. Attempt logins with the incorrect password
3. After expiration lock log in
4. The user status will remain locked.

### Server Details
- Teleport version (run `teleport version`): 7.0.3
- Server OS (e.g. from `/etc/os-release`): ubuntu
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws
