### ISSUE TITLE
One Key with Two Values on a Node

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#8046]
### What
One key should be able to have two values.

### How
```
ssh_service:
  enabled: true
  labels:
    environment: env_a
    environment: env_b
```

### Why
Values are not always mutually exclusive.
