### ISSUE TITLE
Trusted Cluster Resource

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#807]
## Description

It is currently very hard to connect clusters together because users have to do manual confusing key exchange and manipulate 3 different objects - ReverseTunnel, User and Host CA. 

To solve this issue we are introducing new high level resources `TrustedCluster`

### TrustedCluster Resource

```yaml
kind: TrustedCluster
version: v1
metadata:
    name: a.example.com
spec:
    # enabled or disabled, if disabled, as a side effect 
    # teleport deletes user CA and host CA
    enabled: true
    # roles roles to assume for users of cluster a.example.com
    roles: ["admin"]
    # security authorization token to join cluster a.example.com
    token: <token>
    # optional ssh_addr, if not set derived from <metadata.name>:<default ssh proxy addr>
    ssh_proxy_addr: a.example.com:3023
    # optional reverse_tunnel_addr, if not set derived from <metadata.name>:<default reverse tunnel addr>
    ssh_reverse_tunnel_addr: a.example.com
```

Two flows exist for adding new clusters: static tokens and short-lived tokens.

1. Static Tokens: Add new type of token to static config in addition to node tokens type:

       Token                        Role               Expiry Time (UTC)
       -----                        ----               -----------------
       node-token                   Node               never
       cluster-token                TrustedCluster     never

1. Short-lived Tokens: Tokens are added using `tctl`:

       $ tctl clusters add --ttl=5m
       The invite token: c8b8ebd3b644fdc36620fc6775fd3757
       
       Run this on the new node to join the cluster:
       
       ... [instructions] ...

User can take token `cluster-token` from cluster `a` and create the following resource:

```yaml
kind: TrustedCluster
version: v1
metadata:
    name: a.example.com
spec:
    enabled: true
    roles: ["admin"]
    token: cluster-a
```

go to cluster `b.example.com` and `tctl create -f cluster-a.yaml`. As a side effect this will create:

* Dial to a.example.com ssh proxy, authorize with bearer token auth, and call API method `AddCluster` of cluster a.example.com, passing it's own host certificate authority SSH cert in the request
* a.example.com will accept the request, add host certificate authority of `b.example.com` to trusted host keys and respond back with it's local user certificate authority and host certificat authority certificates
* b.example.com will add user cert authority and host cert authority of cluster b
* b.example.com will create a reverse tunnel dialing back to cluster a.example.com 

if user wishes to disable, simply update `enabled` property and set to false, as a side effect:

* reverse tunnel should be deleted
* cert authorities should be deleted

to make sure the trust is removed until the next time user wishes to enable trust and key exchange will happen again.

**Comment by klizhentas** [comment]
@kontsevoy please review

**Comment by kontsevoy** [comment]
```yaml
kind: TrustedCluster
version: v1
metadata:
    # name is optional, defaults to "tunnel_addr" value
    name: master
spec:
    # enabled or disabled, if disabled, as a side effect 
    # teleport deletes user CA and host CA (can we h ave this optional with "true" by default?")
    enabled: true
    # roles roles to assume for users of cluster a.example.com (can we have this optional?)
    roles: ["admin"]
    # security authorization token to join cluster a.example.com
    token: <token>
    # Port can be optional, i.e. "master" is a valid value. Defaults to 3024.
    tunnel_addr: master:3024
    # Optional value, used in case the SSH proxy listens on a different external IP/port.
    # If not specified, defaults to tunnel_addr but with port 3023 
    ssh_proxy_addr: master:3023
```
