### ISSUE TITLE
Unable to enforce Network Restrictions  on Ubuntu 20.10

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#8089]
### Description

**What happened**:

Configured network restrictions and set `restricted_session` on a ubuntu groovy vm.  Network restrictions do not appear to be enforced.

```yaml
kind: network_restrictions
version: v4
metadata:
  name: network-restrictions
spec:
  # When Restricted Session is enabled, the network policy becomes
  # "deny-all". Must add back the ranges to allow
  allow:

  # Override "allow" list with exceptions
  deny:
    - cidr: 0.0.0.0/0
 ```

teleport logs showed network restrictions being applied:

```
Aug 29 16:43:37 ip-172-31-93-34 teleport[1095]: 2021-08-29T16:43:37Z [RESTRICTE] INFO New network restrictions applied: allow=[], deny=[0.0.0.0/0] restrictedsession/network.go:315
```

**What you expected to happen**:

Users opening sessions on the node would not be able to make network connections. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install a ubuntu groovy.  set restriction sessions on
```yaml
  enhanced_recording:
    # Must be enabled for Restricted Sessions to work.
    enabled: true
    # Optional: Controls where cgroupv2 hierarchy is mounted. Default value:
    # /cgroup2.
    cgroup_path: /cgroup2

  restricted_session:
    enabled: true  
```
2. attempt to access any network access (`curl -v google.com`)

### Server Details
- Teleport version (run `teleport version`): 7.1.0
- Server OS (e.g. from `/etc/os-release`): 20.10 (Groovy Gorilla)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
