### ISSUE TITLE
Kubernetes Access does not respect public_addr

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8144]
Kubernetes Access does not respect `public_addr`. Suppose you configure a Kubernetes agent like the following:

```yaml
teleport:
  auth_servers:
    - "proxy.teleport-system.svc.cluster.local:3025"
  auth_token: "foo"
  data_dir: "/tmp/test_new_service_pod/data"
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: no
kubernetes_service:
  enabled: "yes"
  kube_cluster_name: "kube1"
  public_addr: ["kube.teleport-system.svc.cluster.local:3027"]
  listen_addr: 0.0.0.0:3027
```

After a `tsh kube login` if you attempt to use `kubectl` you will see the following:

```
$ kubectl get pods
Error from server: Teleport proxy failed to connect to "kube" agent "kube.teleport-system.svc.cluster.local" over reverse tunnel:

  no tunnel connection found: no kube reverse tunnel for 8b1aecff-e64e-4edb-b936-088f4164d9e6.auth-proxy-5685cfccf4-chsnz found

This usually means that the agent is offline or has disconnected. Check the
agent logs and, if the issue persists, try restarting it or re-registering it
with the cluster.
```

This is because the `public_addr` field is not being set as can be seen in [lib/kube/proxy/server.go#L258-L281](https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/server.go#L258-L281).

The following patch appears to fix the issue by simply propagating `public_addr` along. However, it needs to be cleaned up (don't index without checking length), test coverage needs to be added, and verified this is the expected behavior as described in [RFD 5 - Kubernetes (k8s) service enhancements](https://github.com/gravitational/teleport/blob/master/rfd/0005-kubernetes-service.md).

```diff
diff --git a/lib/kube/proxy/forwarder.go b/lib/kube/proxy/forwarder.go
index 585237eed..dd6140707 100644
--- a/lib/kube/proxy/forwarder.go
+++ b/lib/kube/proxy/forwarder.go
@@ -134,6 +134,8 @@ type ForwarderConfig struct {
    DynamicLabels *labels.Dynamic
    // LockWatcher is a lock watcher.
    LockWatcher *services.LockWatcher
+   // PublicAddr
+   PublicAddr string
 }

 // CheckAndSetDefaults checks and sets default values
diff --git a/lib/kube/proxy/server.go b/lib/kube/proxy/server.go
index 19a700e8c..86b6a1a97 100644
--- a/lib/kube/proxy/server.go
+++ b/lib/kube/proxy/server.go
@@ -256,7 +256,9 @@ func (t *TLSServer) GetServerInfo() (types.Resource, error) {
    defer t.mu.Unlock()

    var addr string
-   if t.listener != nil {
+   if t.TLSServerConfig.ForwarderConfig.PublicAddr != "" {
+       addr = t.TLSServerConfig.ForwarderConfig.PublicAddr
+   } else if t.listener != nil {
        addr = t.listener.Addr().String()
    }

diff --git a/lib/service/kubernetes.go b/lib/service/kubernetes.go
index 977a760dc..f6a40f531 100644
--- a/lib/service/kubernetes.go
+++ b/lib/service/kubernetes.go
@@ -237,6 +237,7 @@ func (process *TeleportProcess) initKubernetesService(log *logrus.Entry, conn *C
            StaticLabels:      cfg.Kube.StaticLabels,
            DynamicLabels:     dynLabels,
            LockWatcher:       lockWatcher,
+           PublicAddr:        cfg.Kube.PublicAddrs[0].String(),
        },
        TLS:           tlsConfig,
        AccessPoint:   accessPoint,
```
