### ISSUE TITLE
[v.7.0] /docs/pages/setup/guides/fluentd.mdx

### ISSUE THREAD

**Issue by michaelmcallister** [gravitational/teleport#8398]
## Details
The example `teleport-event-handler-impersonator` role (copied below) includes a 'deny' directive that prevents access to all nodes. When applied to the current user it prevents access to all nodes via `tsh`.

```
kind: role
version: v4
metadata:
  name: teleport-event-handler-impersonator
spec:
  # SSH options used for user sessions 
  options:
    # max_session_ttl defines the TTL (time to live) of SSH certificates 
    # issued to the users with this role.
    max_session_ttl: 10h

  # allow section declares a list of resource/verb combinations that are
  # allowed for the users of this role. by default nothing is allowed.
  allow:
    impersonate:
      users: ['teleport-event-handler']
      roles: ['teleport-event-handler']

  # the deny section uses the identical format as the 'allow' section.
  # the deny rules always override allow rules.
  deny:
    node_labels:
      '*': '*'
```

### Category
- Improve Existing

**Comment by michaelmcallister** [comment]
```
❯ tctl users ls
User                              Roles
--------------------------------- -----------------------------------------
michael.mcallister@goteleport.com admin,teleport-event-handler-impersonator
teleport-event-handler            teleport-event-handler
```

```
❯ tctl get roles/teleport-event-handler-impersonator
kind: role
metadata:
  id: 1632791823726079832
  name: teleport-event-handler-impersonator
spec:
  allow:
    impersonate:
      roles:
      - teleport-event-handler
      users:
      - teleport-event-handler
  deny:
    node_labels:
      '*': '*'
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v4
```
This will break my node access:

```
❯ tsh ls
Node Name Address Labels
--------- ------- ------
```

Removing the 'deny' directive and re-applying the role seems to fix the issue:
```
❯ tctl get roles/teleport-event-handler-impersonator
kind: role
metadata:
  id: 1632791961941006614
  name: teleport-event-handler-impersonator
spec:
  allow:
    impersonate:
      roles:
      - teleport-event-handler
      users:
      - teleport-event-handler
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v4
```

```
❯ tsh ls
Node Name Address    Labels
--------- ---------- ------
fluentd   ⟵ Tunnel
```
