### ISSUE TITLE
Turning off 2nd factor is not possible

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#848]
Teleport 2.0 supports "off" setting in YAML for the 2nd factor right now:

```yaml
auth_service:
  authentication:
      second_factor: off
```

However, it's not really implemented. The UI seems to be reacting to "off" value, but the login still requires a token.

### Proposed Fix

This needs to start working :-)
