### ISSUE TITLE
Auto-configure group policy for Desktop Access Setup. 

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/teleport#8805]
### What
There are currently four different policy updates (allow RDP connection, disable NLA for RDP, enabling smart card, opening RDP port in firewall) required to prepare the primary windows server for Desktop Access. A way to automate these policy updates will help ease the initial trial. 

### How
Using Powershell scripts or registry files. 

### Why
Improves user experience.

**Comment by benarent** [comment]
+1 . I used https://github.com/aws-quickstart/quickstart-microsoft-activedirectory to setup my AD on AWS. It's open source, and could be good starting point. https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/tree/main/scripts/Modules/Module-AD

**Comment by klizhentas** [comment]
When trying to get LDAPS and PKI infrastructure (for issuing certificates inside the domain) working with AWS Managed AD. 

Most of it seems to be manual steps, such as the huge blog post you have to follow to get it enabled.

Azure managed AD comes with LDAPS enabled out of the box.

The big issue is that Microsoft doesn't provide good ways to automate group policy objects. Many customers will already have most of this infrastructure set up - but I'm unsure if this is the case with AWS managed AD. LDAPS (a Teleport requirement) isn't something that you'd have enabled just for regular domain usage unless you have a specific need for it.

- It took engineer two hours to follow the blog post and that's clearly a non-starter for customers. It did actually work, but you have to follow things to the letter and there's a lot of potential issues that may crop up.

- There is a CloudFormation template (https://github.com/aws-quickstart/quickstart-microsoft-pki/blob/main/templates/two-tier.template) and associated PowerShell script (https://github.com/aws-quickstart/quickstart-microsoft-pki/blob/main/scripts/Modules/Module-Pki/Module-Pki.psm1) that looks to automate most of those same steps we followed in the blog post. 

@webvictim will try to get AWS managed AD setup deployed via automation this week and run the automation against it to see if I can fix any potential issues. If we at least have some recommended commands for customers which work in our demo environments, that will put us in a good place for deploying this with prospects.

From @klizhentas:

Can we use `tctl autoconfigure` approach to automate that configuration [similar to DB access](https://github.com/gravitational/teleport/blob/master/rfd/0046-database-access-config.md)?

**Comment by zmb3** [comment]
Potentially of value: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/gpmc/group-policy-management-console-scripting-samples

**Comment by benarent** [comment]
After spending two days recording a 30min 'Getting Started with Desktop Access' there are few other pain points I've found.

- Desktop Access can be ran in reverse tunnel mode, but requires more exotic port config. ( will follow up with ticket ) 
- Importing 'user-ca.cer' and exporting Domain Controllers CA is still a bit of a pain.
- Part 1/6 https://goteleport.com/docs/ver/8.0/desktop-access/getting-started/#step-16-create-a-user-group-and-group-policy-object is LOTS of ClickOps. It would be great to automate this. 
- Teleport needs specific ports open in the Domain Controller, port `636`, I rage opened all ports to debug my issues but it would be good to have a concise set of ports needed.

**Comment by ibeckermayer** [comment]
[It looks like it may be possible to configure GPO via Powershell](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/set-gpregistryvalue?view=windowsserver2022-ps)

**Comment by ibeckermayer** [comment]
# Notes

Notes on this project, organized by the manually-configured section of the current documentation that needs to be replaced. Miscellaneous notes catalogued here in this section.

Had some success finding which registry keys were set using this function ([source](https://sdmsoftware.com/group-policy-videos/find-all-registry-settings-managed-in-a-gpo/))

```powershell
# This function retrieves settings it does not make changes to GPOs.

function Recurse-PolicyKeys{
 [CmdletBinding()]
 param(
   [Parameter(Mandatory=$true)]
   [string]$GPOName,

   [Parameter(Mandatory=$true)]
   [string]$Key
 )
 $current = Get-GPRegistryValue -Name $gpoName -Key $key
 foreach ($item in $current){
   if ($item.ValueName -ne $null){
   [array]$returnVal += $item 
 }
   else{
     Recurse-PolicyKeys -Key $item.fullkeypath -gpoName $gpoName
   }
 }
 return $returnVal
}
```
For example:
```powershell

```

## [Step 3/6: Configure a GPO to allow Teleport connections](https://goteleport.com/docs/desktop-access/getting-started/#step-36-configure-a-gpo-to-allow-teleport-connections)

### [Create another GPO and import the Teleport CA](https://goteleport.com/docs/desktop-access/getting-started/#create-another-gpo-and-import-the-teleport-ca)

I haven't tried this yet, but it appears to be accessible via
```powershell
Get-GPRegistryValue -Name "Teleport Access Policy" -Key "HKLM\Software\Policies\Microsoft\SystemCertificates\Root\Certificates"
```

### [Enable the Smart Card service](https://goteleport.com/docs/desktop-access/getting-started/#enable-the-smart-card-service)

Unlike some of the other settings, it didn't seem as though this registry was configured in the GPO via the manual process. That is to say, when I tried a
```powershell
Get-GPRegistryValue -Name "Teleport Access Policy" -Key "HKLM\System\CurrentControlSet\Services\SCardSvr\Start"
```
I would get back the `Get-GPRegistryValue : The following Group Policy registry setting was not found: ...` error.

However [this support thread](https://social.technet.microsoft.com/Forums/en-US/9a411810-5ced-4513-a3e3-96b07ae0a0f6/smartcard-service-never-stays-in-quotautomaticquot-mode?forum=win10itprogeneral) implies that setting this value to "2" should do the trick:

```powershell
Set-GPRegistryValue -Name "Teleport Access Policy" -Key "HKLM\System\CurrentControlSet\Services\SCardSvr\Start" -ValueName Start -Type DWord -Value 2
```

This will require more experimentation to confirm -- for example, when I change this setting via powershell (to say "1"), it doesn't show up as changed in the editor. So it's not clear that it's actually doing what I want it to do.

### [Open firewall to inbound RDP connections](https://goteleport.com/docs/desktop-access/getting-started/#open-firewall-to-inbound-rdp-connections)

These two settings I found when tinkering around (`Get-GPRegistryValue -Name "Teleport Access Policy" -Key "HKLM\Software\Policies\Microsoft\WindowsFirewall`):

```powershell
Set-GPRegistryValue -Name "Teleport Access Policy" -Key "HKLM\Software\Policies\Microsoft\WindowsFirewall" -ValueName PolicyVersion -Type DWord -Value 534
```

```powershell
Set-GPRegistryValue -Name "Teleport Access Policy" -Key "HKLM\Software\Policies\Microsoft\WindowsFirewall\FirewallRules" -ValueName RemoteDesktop-UserMode-In-TCP -Type String -Value "v2.20|Action=Allow|Active=TRUE|Dir=In|Protocol=6|LPort=3389|App=%SystemRoot%\system32\svchost.exe|Svc=termservice|Name=@FirewallAPI.dll,-28775|Desc=@FirewallAPI.dll,-28756|EmbedCtxt=@FirewallAPI.dll,-28752|"
```

[ref1](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpfas/15ab2dd9-cbb3-4450-a459-1759aa20e9f7), [ref2](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpfas/2efe0b76-7b4a-41ff-9050-1023f8196d16)

**Comment by robpomeroy** [comment]
I'm building (and plan to open source) an Ansible playbook to automate the configuration of AD.  To solve the GP configuration problem, I create a GPO manually, export it (backup), and then insert variables into the export to make it generic. For want of a GPO Ansible module, I simulate idempotency by running test scripts before taking actions. The following is for step *Step 2/6. Prevent the service account from performing interactive logins*, which demonstrates this approach:

```YAML
- name: Test GPO - Block interactive login for Teleport Service
  ansible.windows.win_powershell:
    script: |
      Get-GPO -Name "Block interactive login for Teleport Service"
  register: gpo_test
  changed_when: false

- name: Create GPO - Block interactive login for Teleport Service
  ansible.windows.win_powershell:
    script: |
      (New-GPO -Name "Block interactive login for Teleport Service" | New-GPLink -Target "{{ domain_dn }}").GpoId.Guid
  register: gpo_create
  when: gpo_test.error

- name: Get SID of Teleport Service
  ansible.windows.win_powershell:
    script: |
      (Get-ADUser -Identity "Teleport Service").SID.Value
  register: teleport_sid
  changed_when: false
  when: gpo_test.error

- name: Create GPO backup directories
  ansible.windows.win_file:
    path: C:\Windows\Temp\block_interactive\{{ item.path }}
    state: directory
  with_filetree: ../templates/block_interactive
  when: item.state == 'directory' and gpo_test.error

- name: Copy GPO backup files
  ansible.windows.win_template:
    src: "{{ item.src }}"
    # Remove the ".j2" extension when copying
    dest: C:\Windows\Temp\block_interactive\{{ item.path.rstrip(".j2") }}
    trim_blocks: no
  with_filetree: ../templates/block_interactive
  when: item.state == "file" and gpo_test.error

- name: Import GPO - Block interactive login for Teleport Service
  ansible.windows.win_powershell:
    script: |
      Import-GPO -BackupGpoName "Block interactive login for Teleport Service" -Path "C:\Windows\Temp\block_interactive" -TargetGuid "{{ gpo_create.output[0] }}"
  when: gpo_test.error
```

Then in the GPO export files, we place variables as required. For example, in `DomainSysvol\GPO\Machine\microsoft\windows nt\SecEdit\GptTmpl.inf.j2`:

```ini
[Unicode]
Unicode=yes
[Version]
signature="$CHICAGO$"
Revision=1
[Privilege Rights]
SeDenyInteractiveLogonRight = *{{ teleport_sid.output[0] }}
SeDenyRemoteInteractiveLogonRight = *{{ teleport_sid.output[0] }}
```

You have to be super mindful of file encoding. The `GptTmpl.inf` file for example exports as UTF-16. You need to convert it to UTF-8, otherwise the Ansible `win_template` module mangles it during upload/interpolation. I also discovered that without the `trim_blocks` parameter, PowerShell segfaults during the  import!

Haven't yet worked out how to automate the problem @benarent calls out, of importing the user CA certificate.
