### ISSUE TITLE
helm teleport-cluster wrongfuly mounts `gcp-credentials` volume when not using static credentials

### ISSUE THREAD

**Issue by HagaiBarel** [gravitational/teleport#8842]
### Description

**What happened**:

The teleport-cluster helm chart adds a volume mount to the deployment pod template with `gcp-credentials` even when passing `gcp.credentialSecretName: ""`. But since the volume isn't created, this results in a failed mount and the pod never starts

**What you expected to happen**:
The volume mount should not be added as the corresponding volume isn't created either

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
From the terminal run:

```shell
helm install -n teleport teleport teleport/teleport-cluster \
--set chartMode=gcp \
--set gcp.credentialSecretName="" \
--set gcp.projectId=dummy \
--set gcp.backendTable=dummy \
--set gcp.auditLogTable=dummy \
--set gcp.sessionRecordingBucket=dummy \
--set clusterName=teleport.example.com \
--dry-run \
--debug
```

And view the resulting deployment spec, the relevant section is:

```yaml
        volumeMounts:
        - mountPath: /etc/teleport-secrets
          name: "gcp-credentials"
          readOnly: true
        - mountPath: /etc/teleport
          name: "config"
          readOnly: true
        - mountPath: /var/lib/teleport
          name: "data"
      volumes:
      - name: "config"
        configMap:
          name: teleport
      - name: "data"
        emptyDir: {}
```

### Server Details
- Teleport version (run `teleport version`): 7.3.3
- Server OS (e.g. from `/etc/os-release`):  N/A
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP
- Additional details:
- helm chart version: 7.3.3

As far as I can gather, this comes from a wrong conditional in the deployment template here: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/deployment.yaml#L155-L159

But it conditional should match the one below it here 
https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/deployment.yaml#L179-L183
