### ISSUE TITLE
Redshift auto-discovery

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#8877]
### What

In https://github.com/gravitational/teleport/pull/8481 we added auto-discovery for RDS instances and Aurora clusters. We should extend this for Redshift clusters as well.

Users should be able to include `redshift` type in their auto-discovery configuration and have Teleport proxy all matching Redshift databases similar to RDS:

```yaml
db_service:
  aws:
  - types: ["redshift"]
    regions: ["us-west-1"]
    tags:
      "*": "*"
```

### How

All the building blocks are there implemented in https://github.com/gravitational/teleport/pull/8481, just need to extend the database cloud watcher (`lib/srv/db/cloud/watchers`) to support Redshift in the same fashion as RDS.
