### ISSUE TITLE
Tsh connects to 3080 instead of 443

### ISSUE THREAD

**Issue by Born2Bake** [gravitational/teleport#8898]
### Description

**What happened**:
Default installation, trying to login using tsh client and getting port 3080 error even though in the config I have set port 443.

**What you expected to happen**:
Successfully login.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install teleport
2. Add config
```
teleport:
  nodename: teleport-lxc
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.domain.com
ssh_service:
  enabled: "yes"
  labels:
    env: teleport-lxc
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
  - name: arch
    command: ['/bin/uname', '-p']
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
#  kube_listen_addr: 0.0.0.0:3026
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.domain.com:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: xxx@xxxx.com
kubernetes_service:
  enabled: yes
  listen_addr: 0.0.0.0:3026
  # replace this path with the actual path for your generated kubeconfig
  kubeconfig_file: "/etc/kubeconfig"

```

3. tsh login --proxy=teleport.domain.com:443 --auth=local --user=teleport-admin
ERROR: Get "https://teleport.domain.com:3080/webapi/ping/local": dial tcp xx.xxx.xxx:3080: connect: connection refused

For some reason it tries to connect to port 3080.

### Server Details
- Teleport version (run `teleport version`): Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): D Hardware
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2
- Computer OS (e.g. Linux, macOS, Windows): Ubuntu 20.04.3 LTS
- Browser version (for UI-related issues): UI is totally fine
- Installed via (e.g. apt, yum, brew, website download): apt
