### ISSUE TITLE
Connect error via SSH: `no matching host key type found`

### ISSUE THREAD

**Issue by christian-heusel** [gravitational/teleport#8973]
### Description

**What happened**:
Once I try to connect to any server in our cluster via the SSH Client (to use teleport + ansible) I get the following error message:
```
chris@pioneer ~ » ssh host.example.com
Unable to negotiate with 123.456.78.9 port 3023: no matching host key type found. Their offer: ssh-rsa-cert-v01@openssh.com
ERROR: exit status 255

kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**What you expected to happen**:
The connection via SSH Works as expected and does not abort due to the specified error.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup teleport ssh access via `tsh config`
2. run `ssh user@host.example.com`

So far I could only reproduce the issue with all of my ArchLinux Machines!

### Server Details
- Teleport version (run `teleport version`): `Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2`
- Server OS (e.g. from `/etc/os-release`): `Debian GNU/Linux 11 (bullseye)`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated Hardware
- Additional details: 

`cat /etc/teleport.yaml`
```
teleport:
  nodename: host
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_servers:
   - ...:3025
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
proxy_service:
  enabled: "no"
```

### Client Details
- Tsh version (`tsh version`): `Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2`
- Computer OS (e.g. Linux, macOS, Windows): ArchLinux
- Browser version (for UI-related issues): -
- Installed via (e.g. apt, yum, brew, website download): [package in the aur](https://aur.archlinux.org/packages/teleport-bin)
- Additional details:
  - ssh version: `OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021`

```
#
# Begin generated Teleport configuration for host.example.com:3080 from `tsh config`
#

# Common flags for all MathPhysInfo hosts
Host *.example.com proxy.example.com
    UserKnownHostsFile "/home/chris/.tsh/known_hosts"
    IdentityFile "/home/chris/.tsh/keys/proxy.example.com/chris"
    CertificateFile "/home/chris/.tsh/keys/proxy.example.com/chris-ssh/ClusterName.pub"

# Flags for all MathPhysInfo hosts except the proxy
Host *.example.com !proxy.example.com
    Port 3022
    ProxyCommand "/usr/bin/tsh" config-proxy --login="%r" --proxy=proxy.example.com:3023 %h:%p "ClusterName"

# End generated Teleport configuration
```

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`): ➡️ no log change upon error
- Run tsh with --debug flag (`tsh --debug`): ➡️ tsh is not invoked directly
