### ISSUE TITLE
Browser caches the app url and it doesn't get cleared for too long.

### ISSUE THREAD

**Issue by t3chboy** [gravitational/teleport#9002]
### Description
We have done basic setup for application access, and we tried  for default debug app, but after the app open its get cached in browser for all the teleport urls, so from there on-wards whichever teleport portal url we try to make it it open the same app. 
We also tried to cleared cookies,localstorage & browser cache but same issue still exists.
We also tried with incognito, but there also for 1st time we got access to portal later on it also used to open only app page.

**What happened**:
App page gets cached with teleport-portal url, and everytime we try to access teleport portal app gets opened.

**What you expected to happen**:
Default app page should not have been cached with teleport portal url.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.Installed teleport on ec2 instance as per : https://goteleport.com/docs/getting-started/linux-server/
2. edited teleport.yaml and added : `debug_app: true`
3. Now open teleport portal & login, and select default app to access
4. Url redirects and on the teleport domain/ip itself default app gets open and it gets cached over there.
5. Even on this page : https://10.0.80.34/web/login?redirect_uri=https://10.0.80.34/web  default app page opens.

### Server Details
- Teleport version (run `teleport version`): latest
- Server OS (e.g. from `/etc/os-release`): ubuntu latest
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Teleport.yaml 
```
teleport:
  nodename: ip-10-0-xx-xx
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  auth_token: d947f7b9d3dc809547483fe95c1a0735
  ca_pin: "sha256:f59945bf5b5281b0451620fc4f9958262534d6377f8b3ae24013fde0f0b981c7"
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: telep.example.com
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
app_service:
  enabled: yes
  debug_app: true
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:443
  public_addr: 10.0.XX.XX:443
  https_keypairs:
    - key_file: /home/ubuntu/localhost.key
      cert_file: /home/ubuntu/localhost.crt
  acme:
    enabled: "no"
    email: myemailid@example.com


```

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
Following log generated everytime i try to reload the page : https://10.0.X.X/ 
```
021-11-15T18:35:44Z INFO             Round trip: GET /, code: 200, duration: 326.438µs tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706a2e66796e642e636f6d.teleport.cluster.local forward/fwd.go:185
2021-11-15T18:35:44Z INFO [APP:WEB]   Round trip: GET /, code: 200, duration: 4.942611ms tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server: forward/fwd.go:185

```
