### ISSUE TITLE
Teleport nodes should start with stale data

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#9085]
Teleport nodes should start even if they can not connect to auth as long as they have cached access to the the backend. By default the cache should be for 24 hours, but we should support making this configurable. We also need to add this information to our documentation (what customers can expect for Teleport, what signals to send so the cache can be closed without currupting it, and how to change cache validity).

**Comment by russjones** [comment]
Something like this.

```yaml
cache:
  type: "in-memory"

  # Default cache validity is 24 hours. This value can be increased
  # or decreased based off tolerance of serving stale data.
  ttl: "24h"
```
