### ISSUE TITLE
Get a join token got access denied to perform action "create" on "token"

### ISSUE THREAD

**Issue by dove-young** [gravitational/teleport#9333]
### Description

**What happened**:

When I create a join token following the instruction on https://goteleport.com/docs/kubernetes-access/getting-started/agent/ , I got Xv509 error

```
[root@st2-dev21 teleport]# ./tctl nodes add --roles=kube --ttl=10000h --format=json
[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://teleport.cluster.local/v2/configuration/name": x509: certificate is valid for st2-dev21.myfyre.com, localhost, localhost.local, not 6d61696e.teleport.cluster.local
        Get "https://teleport.cluster.local/v2/configuration/name": x509: certificate is valid for st2-dev21.myfyre.com, localhost, localhost.local, not 6d61696e.teleport.cluster.local, failed lookup of proxy reverse tunnel address: Get "https://st2-dev21.myfyre.com:3080/webapi/find": x509: certificate signed by unknown authority
        Get "https://st2-dev21.myfyre.com:3080/webapi/find": x509: certificate signed by unknown authority.
Is the auth server running on "st2-dev21.myfyre.com:3080"?
```

Then I tried insecure, and got access denied error

```
[root@st2-dev21 teleport]# ./tctl nodes add --roles=kube --ttl=10000h --format=json --insecure
ERROR: access denied to perform action "create" on "token"
```

Here is my `teleport.yaml`

```
teleport:
  data_dir: /root/teleport/data/auth
  pid_file: /root/teleport/data/auth.pid
  auth_token: cluster-join-token
  auth_servers:
  - 127.0.0.1:3025
  - st2-dev21.myfyre.com:3025
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  cluster_name: "main"
  listen_addr: 0.0.0.0:3025
  public_addr: "st2-dev21.myfyre.com:3025"
  authentication:
    second_factor: off
  tokens:
  - proxy,node:cluster-join-token
  session_recording: "proxy"
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0
  proxy_checks_host_keys: no
ssh_service:
  enabled: "yes"
  labels:
    db_role: master
    db_type: postgres
  commands:
  - name: hostname
    command: [/usr/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/usr/bin/uname, -p]
    period: 1h0m0s

#  https_cert_file: /root/teleport/PEM/stackOverflow/teleport.crt
#  https_key_file: /root/teleport/PEM/stackOverflow/teleport.key
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  kube_listen_addr: 0.0.0.0:3026
  public_addr: 'st2-dev21.myfyre.com:3080'

#  https_cert_file: /root/teleport/PEM/stackOverflow/teleport.crt
#  https_key_file: /root/teleport/PEM/stackOverflow/teleport.key

#  https_key_file: /root/teleport/key.pem
#  https_cert_file: /root/teleport/cert.pem
```

Here is the CLI I start Teleport 

```
teleport/./teleport start --config /root/teleport/teleport.yaml
```

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`): Teleport v7.3.3 git:v7.3.3-0-g47ccf9e go1.16.2
- Server OS (e.g. from `/etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): VM
- Additional details:

### Client Details
- Tsh version (`tsh version`):  Teleport v7.3.3 git:v7.3.3-0-g47ccf9e go1.16.2
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): Firefox 
- Installed via (e.g. apt, yum, brew, website download): download
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)
