### ISSUE TITLE
Unable to add a k8s cluster to teleport-cluster

### ISSUE THREAD

**Issue by shubhindia** [gravitational/teleport#9336]
### Description

**What happened**:
I have configured teleport-cluster in kubernetes with helm chart, I have set `acme=false` and using ClusterIssuer to issue the tls certificate to teleport instance. I am able to login and create users in this instance but when I try to install teleport-agent in kubernetes cluster to add the cluster in this teleport instance, I get `Failed to ping web proxy "<teleport-instance>:3024" addr: Get "https://<teleport-instance>:3024/webapi/find": tls: first record does not look like a TLS handshake leaseID:1 <teleport-instance>:3024 reversetunnel/agent.go:269`. Attaching screenshot of whole log below

![teleport-agent-error](https://user-images.githubusercontent.com/7694806/145527747-4b1bdff0-244f-4d09-acbd-2a7fbc04a4e4.jpg)

**What you expected to happen**:
Teleport agent should connect to teleport-cluster.

### Reproduction Steps
This is how my rendered helm template looks like
```
# Source: teleport-cluster/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: MustRunAs
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  readOnlyRootFilesystem: true
  volumes:
  - '*'
  hostNetwork: false
  hostIPC: false
  hostPID: false
---
# Source: teleport-cluster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
---
# Source: teleport-cluster/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
data:
  teleport.yaml: |
    teleport:
      log:
        severity: INFO
        output: stderr
    auth_service:
      enabled: true
      cluster_name: <teleport-instance>
      authentication:
        type: local
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: <teleport-instance>
    proxy_service:
      public_addr: '<teleport-instance>:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      enabled: true
      https_keypairs:
      - key_file: /etc/teleport-tls/tls.key
        cert_file: /etc/teleport-tls/tls.crt
    ssh_service:
      enabled: false
---
# Source: teleport-cluster/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  labels:
    app: teleport-cluster
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Source: teleport-cluster/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teleport-cluster
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
---
# Source: teleport-cluster/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teleport-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teleport-cluster
subjects:
- kind: ServiceAccount
  name: teleport-cluster
  namespace: teleport-cluster
---
# Source: teleport-cluster/templates/psp.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: teleport-cluster-psp
  namespace: teleport-cluster
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - teleport-cluster
---
# Source: teleport-cluster/templates/psp.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teleport-cluster-psp
  namespace: teleport-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teleport-cluster-psp
subjects:
- kind: ServiceAccount
  name: teleport-cluster
---
# Source: teleport-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  labels:
    app: teleport-cluster
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 3080
    protocol: TCP
  - name: sshproxy
    port: 3023
    targetPort: 3023
    protocol: TCP
  - name: k8s
    port: 3026
    targetPort: 3026
    protocol: TCP
  - name: sshtun
    port: 3024
    targetPort: 3024
    protocol: TCP
  - name: mysql
    port: 3036
    targetPort: 3036
    protocol: TCP
  selector:
    app: teleport-cluster
---
# Source: teleport-cluster/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  labels:
    app: teleport-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleport-cluster
  template:
    metadata:
      annotations:
        # ConfigMap checksum, to recreate the pod on config changes.
        checksum/config: f12fa48264dbc8b90827d466ae0a1ce4101d75cc8a5c9093b62f02a2d93b8cb0
      labels:
        app: teleport-cluster
    spec:
      containers:
      - name: "teleport"
        image: "quay.io/gravitational/teleport:8.0.3"
        imagePullPolicy: IfNotPresent
        args:
        - "--diag-addr=0.0.0.0:3000"
        ports:
        - name: diag
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: diag
          initialDelaySeconds: 5 # wait 5s for agent to start
          periodSeconds: 5 # poll health every 5s
          failureThreshold: 6 # consider agent unhealthy after 30s (6 * 5s)
        readinessProbe:
          httpGet:
            path: /readyz
            port: diag
          initialDelaySeconds: 5 # wait 5s for agent to register
          periodSeconds: 5 # poll health every 5s
          failureThreshold: 12 # consider agent unhealthy after 60s (12 * 5s)
        volumeMounts:
        - mountPath: /etc/teleport-tls
          name: "teleport-tls"
          readOnly: true
        - mountPath: /etc/teleport
          name: "config"
          readOnly: true
        - mountPath: /var/lib/teleport
          name: "data"
      volumes:
      - name: gcp-credentials
        secret:
          secretName: teleport-gcp-credentials
      - name: teleport-tls
        secret:
          secretName: teleport-tls
      - name: "config"
        configMap:
          name: teleport-cluster
      - name: "data"
        persistentVolumeClaim:
          claimName: teleport-cluster
      serviceAccountName: teleport-cluster
---
# Source: teleport-cluster/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
spec:
  secretName: teleport-tls
  dnsNames:
  - "<teleport-instance>"
  - "*.<teleport-instance>"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
```

### Server Details
- Teleport version (run `teleport version`): 8.0.3
- Where are you running Teleport? : kops in aws
