### ISSUE TITLE
Kubernetes - forbidden error after logging into kube cluster

### ISSUE THREAD

**Issue by stefangrosaru** [gravitational/teleport#9434]
### Description
Unable to run any kubectl commands after logging into kubernetes cluster via tsh

**What happened**:
The following error is displayed:

`Error from server (Forbidden): pods is forbidden: User "username" cannot list resource "pods" in API group "" in the namespace "default"`

**What you expected to happen**:
kubectl commands work without any errors

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Add teleport agent to k8s cluster following these steps: https://goteleport.com/docs/kubernetes-access/getting-started/agent/
2. Log into cluster using `tsh kube login k3d-mini`
3. Try to issue any kubectl command: `kubectl get pods`

### Server Details
- Teleport version (run `teleport version`): 8.0.1
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): k3d single node cluster running on docker
- Additional details:

### Client Details
- Tsh version (`tsh version`):8.0.6
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Installed via (e.g. apt, yum, brew, website download): brew

### Debug Logs
This is the audit log generated by the request
```
{
  "addr.local": "10.43.0.1:443",
  "addr.remote": "10.10.10.10:443",
  "cluster_name": "tele.example.com",
  "code": "T3009I",
  "ei": 0,
  "event": "kube.request",
  "kubernetes_cluster": "k3d-mini",
  "kubernetes_groups": [
    "admins",
    "system:authenticated"
  ],
  "kubernetes_users": [
    "stefan"
  ],
  "login": "stefan",
  "namespace": "default",
  "proto": "kube",
  "request_path": "/api/v1/namespaces/default/pods",
  "resource_api_group": "core/v1",
  "resource_kind": "pods",
  "resource_namespace": "default",
  "response_code": 403,
  "server_id": "bbc7e90f-462a-4df4-92c2-f632a1b5c8f3",
  "time": "2021-12-16T00:51:37.713Z",
  "uid": "d93c1378-aa74-4bdb-831c-4b591aff0b88",
  "user": "stefan",
  "verb": "GET"
}
```

**Comment by stevenGravy** [comment]
@stefangrosaru did you define roles and rolesbinding for the group `admins` or the user `stefan`?

**Comment by stefangrosaru** [comment]
@stevenGravy thanks for looking into this, I have defined the role bindings below in k8s:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teleport-impersonation
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teleport
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teleport-impersonation
subjects:
- kind: ServiceAccount
  # this should be changed to the name of the Kubernetes ServiceAccount being used
  name: stefan
  namespace: default
```

**Comment by stefangrosaru** [comment]
**Update**

After binding the cluster-admin role to my user, I was able to perform kubectl commands without forbidden errors, but I'm not entirely sure this is the right way to do it when using teleport.

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stefan-rolebinding
subjects:
- kind: User
  name: stefan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
