### ISSUE TITLE
debug flag does not show failed label command

### ISSUE THREAD

**Issue by ghost** [gravitational/teleport#9440]
### Description
It's very hard to troubleshoot incorrect commands for labels since teleport does not show what went wrong or what the actual command looked like when it was executed. 
**What happened**:
Log state
`2021-12-16T08:42:01Z ERRO             Failed to run command and update label: exit status 1. labels/labels.go:152
`
**What you expected to happen**:
I'm running with --debug for troubleshooting and I would like more verbose output with information of  what went wrong and the actual command

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
Using this

```
ssh_service:
  enabled: yes
  commands:
  - name: hostname
    command: ["hostname"]
    period: 1h0m0s
  - name: failed
    command: ["cat", "/this/does/not/exist"]
    period: 1h0m0s
```
### Server Details
- Teleport version: Teleport v8.0.6 git:v8.0.6-0-g807c6d662 go1.17.3
- Server OS: Ubuntu 20.04.3 LTS
- Where are you running Teleport: Dedicated hardware
- Additional details:
