### ISSUE TITLE
Connect 3 or more clusters

### ISSUE THREAD

**Issue by jmgomezcrespo** [gravitational/teleport#957]
Hi !!
I have 3 Teleport cluster  with version 2.0.4, I been try to define one of them as master with only 1 instance  and the others two as slaves that contain one node (auth-proxy) and some nodes.

I put slaves' keys in master teleport configuration like that
    cluster_name: master
    trusted_clusters:
      - key_file: /var/lib/teleport/client.ca
      - key_file: /var/lib/teleport/client2.ca

The slave teleport have the same tunnel address, which is master IP

- key_file: /var/lib/teleport/cm.ca
  allow_logins: User
  tunnel_addr: Public_IP_Master

Teleport started in the three nodes but only connected one slave, the other slave don't show any information in debug mode about tunnel connection. Is possible create this architecture?

Thanks, and sorry for my english

**Comment by russjones** [comment]
@jmgomezcrespo Yes, you can have a single master and multiple Trusted Clusters attached to it. Suppose you have three clusters `one`, `two`, and `three`. Suppose `one` is the master and `two` and `three` are the Trusted Clusters. Your config files should look something like this:

`one`
```
trusted_clusters:
   - key_file: /path/to/two.ca
   - key_file: /path/to/three.ca
```

`two`
```
trusted_clusters:
   - key_file: /path/to/one.ca
   allow_logins: root
   tunnel_addr: one:3024
```

`three`
```
trusted_clusters:
   - key_file: /path/to/one.ca
   allow_logins: root
   tunnel_addr: one:3024
```

Keep in mind after you export your certificates you will have to restart all three Auth Servers before these changes are read in.
