### ISSUE TITLE
How to ssh into local machine

### ISSUE THREAD

**Issue by aqiank** [gravitational/teleport#964]
I can ssh to the node at the server itself but when I try to ssh using `tsh ssh --insecure --user jacky --proxy iim.ltd jacky@jacky-pc`, I get `failed connecting to node jacky-pc. dial tcp 121.7.103.158:3022: getsockopt: connection refused`.

I was thinking I could get it to work like normal ssh tunnel but I guess there some things that I don't get quite right. Is there somebody who can point me at the right direction?

I started server's Teleport using `teleport start` and local machine's Teleport using `teleport start --roles=node,proxy`.

Server's `/etc/teleport.yaml`
```
teleport:
  nodename: example.com
  advertise_ip: 51.129.76.200
  log:
    output: stderr
    severity: INFO

auth_service:
  enabled: yes
  cluster_name: example.com
  tokens:
    - "node:abc123"
  trusted_clusters:
    - key_file: /root/jacky-pc.ca

ssh_service:
  enabled: yes
  labels:
    role: ca
  commands:
    - name: kernel
      command: [/bin/uname, -r]
      period: 5m

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
```

Local machine's `/etc/teleport.yaml`
```
teleport:
  nodename: jacky-pc
  auth_token: abc123
  auth_servers:
    - 51.129.76.200:3025
  log:
    output: stderr
    severity: INFO

auth_service:
  enabled: yes
  cluster_name: jacky-pc
  trusted_clusters:
    - key_file: /home/jacky/Downloads/teleport/example.com.ca
      allow_logins: jacky
      tunnel_addr: 51.129.76.200:3024

ssh_service:
  enabled: yes
  labels:
    role: node,proxy

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
```
