### ISSUE TITLE
Fail to render teleport-cluster helm chart at master branch

### ISSUE THREAD

**Issue by shibataka000** [gravitational/teleport#9648]
This issue is related but difference from #9644 .

### Description

**What happened**:

Fail to render [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) helm chart at master branch.

**What you expected to happen**:

Success to render [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) helm chart at master branch.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.

1. Create `values.yaml` as follow.

```yaml
clusterName: MY_CLUSTER_NAME
chartMode: aws
aws:
  region: ap-northeast-1
  backendTable: teleport-backend
  auditLogTable: teleport-events
  sessionRecordingBucket: teleport-sessions
highAvailability:
  replicaCount: 2
  certManager:
    enabled: true
    issuerName: letsencrypt
```

2. Run `helm template` command as follow. Then it returns error.

```bash
$ helm template teleport ./examples/chart/teleport-cluster --namespace teleport --values values.yaml
Error: YAML parse error on teleport-cluster/templates/service.yaml: error converting YAML to JSON: yaml: line 14: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```

### Server Details
None

### Client Details
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Helm: v3.7.2
- [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) helm chart: v8.0.7

### Debug Logs
I uploaded output by following command to [teleport-cluster-helm-chart-error-log.txt](https://gist.github.com/shibataka000/2f97dd3be4554cbbd5d457eec735a567).

```bash
$ helm template teleport ./examples/chart/teleport-cluster --namespace teleport --values values.yaml --debug
```
