### ISSUE TITLE
helm chartMode:custom and Config and PVC mount [improvement suggestion]

### ISSUE THREAD

**Issue by dmitry-mightydevops** [gravitational/teleport#9713]
### Description

**issue 1: pvc**

I'm using teleport-cluster helm chart. I need to provide a custom config to teleport so I can proxy let's say grafana. 

To do that I'm forced to supply `chartMode:custom` which basically has no PVC solution for teleport data
https://github.com/gravitational/teleport/blob/c7c94111cd0a844f0f31c422748b89896caad943/examples/chart/teleport-cluster/templates/deployment.yaml#L192

Which is expected to be mounted in /var/lib/teleport [here](https://github.com/gravitational/teleport/blob/c7c94111cd0a844f0f31c422748b89896caad943/examples/chart/teleport-cluster/templates/deployment.yaml#L99)

So with "custom" mode of helm chart without PVC - I have to apply via tctl commands to setup roles, github-connector
```
kubectl -n teleport-cluster exec -i ${POD?} -- tctl create -f  < ../../teleport/roles.yaml
kubectl -n teleport-cluster exec -i ${POD?} -- tctl create -f  < ../../teleport/github-connector.yaml
```

each time the POD is restarted. This makes `chartMode: custom` absolutely hard to use.  So I suggest to have PVC (data) is not to be "standalone" option only. It should be available for any chartMode.

**issue 2: custom teleport config**

I need to provide a custom config to teleport so I can proxy let's say grafana. In order to do that I need to supply a custom config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport
  namespace: teleport-cluster
data:
  teleport.yaml: |
    teleport:
      log:
        severity: INFO
        output: stderr
        format:
          output: text
          extra_fields: ["timestamp","level","component","caller"]
    auth_service:
      enabled: true
      cluster_name: teleport.thesite.com
      authentication:
        type: local
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: teleport.thesite.com
    proxy_service:
      public_addr: 'teleport.thesite.com:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      enabled: true
      acme:
        enabled: true
        email: devops+site@thesite.com
    ssh_service:
      enabled: false
    app_service:
      enabled: yes
      # Teleport provides a small debug app that can be used to make sure application
      # access is working correctly. It'll output JWTs so it can be useful
      # when extending your application.
      debug_app: true
      # This section contains definitions of all applications proxied by this
      # service. It can contain multiple items.
      apps:
        - name: "grafana"
          # URI and port the application is available at.
          uri: "http://grafana.grafana:80"
          # Optional application public address to override.
          public_addr: "grafana.teleport.thesite.com"
          # Optional static labels to assign to the app. Used in RBAC.
          labels:
            env: "prod"
```

It would be nice to define configmap as part of the helm chart yaml manifest, which will be used instead of dynamically rendering it [here](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/config.yaml)

so something like this:

```yaml
{{- if not (eq .Values.config ) -}}
apiVersion: v1
kind: ConfigMap
data: 
  teleport.yaml: |
    {{ .Values.config | nindent 6 }}
{{ else }}
....generate config from dynamic values (what we have now)....
{{ end }} 
```

That way if such config value is missed - things are working. If it present - the value is used. 

**What you expected to happen**:

- PVC object (for teleport data) to be created regardless of chartMode value
- teleport config to be defined as part of the HELM chart values.yaml 

### Server Details
- Teleport version (run `teleport version`): 8.0.7
- Where are you running Teleport? aws eks
- teleport-cluster helm chart:  teleport/teleport-cluster   	8.0.7

### Client Details
- Tsh version (`tsh version`): Teleport v8.0.7 git:v8.0.7-0-geb8076446 go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): Chrome
- Installed via (e.g. apt, yum, brew, website download): yum
