### ISSUE TITLE
Teleport web UI and Application Access running behind reverse proxy

### ISSUE THREAD

**Issue by stefangrosaru** [gravitational/teleport#9799]
### What
What would you like Teleport to do differently?
Allow the teleport web UI and its features to work behind a reverse proxy such as traefik, nginx, etc.

### How
How would you implement this?
As an example we have teleport.example.com which is the url for the web ui and *.teleport.example.com which is used for application access. We would then have these two names configured in the reverse proxy, for example nginx, so that they pass the traffic to teleport.

### Why
Why do you need this?
The application access service of teleport is very useful, especially when using unsecure apps, but it would be nice to have the option to decide which apps should be put behind that layer of security and which ones should not.

### Workaround
There is no current workaround as far as I am aware.

**Comment by alexbarcelo** [comment]
I will leave this here, in case is correct (which I'm not 100% sure) and becomes useful for somebody:

## Workaround

Configure your reverse proxy to perform SSL termination. Configure your certificates (I personally use a wildcard domain `*.tele.my.domain` plus the UI `tele.my.domain`).

Remove ACME configuration from the Teleport yaml. Add both certificates in the `https_keypairs` (in `proxy_service`).

I may be mistaken because I was testing things and DNS may be propagating and being naughty in general. But I believe that it is working with this configuration.

It seems a bit silly, as it is unwrapping and rewrapping the SSL with the same certificate; but with this configuration the LAN connections can be performed directly (without going through the reverse proxy) and everything seems to work. The ALPN is not performed because ALPN doesn't seem to behave nicely with reverse proxies, AFAICT. That's why a wildcard seems to be needed.

Hopefully someone will correct me if I'm wrong.

**Comment by stefangrosaru** [comment]
@alexbarcelo Thanks for taking the time to help with this.
 I have had a few attempts to achieve something similar, however I have encountered issues with some of the teleport functionality, namely application access and the ability for server nodes to connect to the cluster in "reverse tunnel" mode.

**Comment by alexbarcelo** [comment]
DISCLAIMER: I believe that my solution works for web-based access, but it seems to fail for the `tsh login` flow.

Maybe there is some client certificate shenanigans? I don't really know the answer, but keep that in mind if you try my workaround.

Application access seems to work _if you connect directly to the node_ (instead of going through the reverse proxy). I suppose that the same mechanism is failing, whatever it is.

**Comment by stefangrosaru** [comment]
Yes, I wonder if you can get around this by creating another teleport service that deals with application access, but still not sure how to get the auth service to work. 

Maybe doing L4 load balancing instead of L7 could also help, the only issue with that is that you lose the ability to do hostname based routing.

It seems that some teleport services are incompatible with each other, but I was not able to find any info on this in the documentation.

**Comment by toby1991** [comment]
After 3 years, this problem still exist......

**Comment by KasperSkytte** [comment]
I have trouble with adding applications too. I use nginx as reverse-proxy for the main domain (like most self-hosters nowadays?), and then teleport on a subdomain `teleport.domain.com`. When I set my email in the ACME setting in the server `teleport.yml` I get:
```
2022-03-16T21:43:17Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *errors.errorString acme/autocert: missing server name
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:344 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
	/go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:282 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: acme/autocert: missing server name] alpnproxy/proxy.go:290
```

When I set `http_keypairs` to link to both the `domain.com` and `teleport.domain.com` certificates and private keys, I'm not allowed to connect through the browser because of HSTS, invalid certificate. The ladder case also happens when I leave either of `acme` or `http_keypairs` settings blank. I have the required ports forwared on the router. 

The app I'm starting also shows the following line in the output:
```
2022-03-17T09:28:01+01:00 INFO [APP:SERVI] Failed to ping web proxy "teleport.domain.com:3024" addr: Get "https://teleport.domain.com:3024/webapi/find": tls: first record does not look like a TLS handshake leaseID:1 target:teleport.domain.com:3024 reversetunnel/agent.go:269
```

but a simple `nmap teleport.domain.com -p 3024` shows the port is open. I have set `*.teleport.domain.com` and `teleport.domain.com` DNS CNAME records.

What am I doing wrong? The browser doesn't get the correct certificate presented, but why?

**Comment by webvictim** [comment]
@KasperSkytte That error (`Failed to ping web proxy "teleport.domain.com:3024"`) isn't really an error, it's just some debugging output that should be silenced. I'm going to raise an issue to get this fixed.

With regard to your other issue, did you get it resolved? If not, can you please share your full `/etc/teleport.yaml` config file (with any secrets/tokens redacted)? 

In general you don't _need_ to run Teleport behind nginx or anything else, it expects to be able to terminate its own TLS (which is why it has the ACME support to get certificates automatically from LetsEncrypt)

**Comment by KasperSkytte** [comment]
@webvictim Sorry I totally forgot about this. The trouble was caused by both contradicting certificates between teleport and the reverse proxy, and that I forgot to add `*.teleport.domain.com` in addition to `teleport.domain.com` to the reverse-proxy config. So pretty basic mistakes :)

**Comment by KasperSkytte** [comment]
So both the `https_keypairs` and `acme` settings under `proxy_service` in `teleport.yaml` are blank. I let the reverse proxy handle things and it works like a charm.

**Comment by abjoseph** [comment]
> So both the `https_keypairs` and `acme` settings under `proxy_service` in `teleport.yaml` are blank. I let the reverse proxy handle things and it works like a charm.

@KasperSkytte Could you share your `/etc/teleport.yaml`? If your https_keypairs field is empty, how are you configuring teleport to use your proxied domain instead of its default domains --> `teleport.cluster.local` and `*.teleport.cluster.local`

**Comment by abjoseph** [comment]
@webvictim Is there a way to configure teleport to use your proxied domain instead of its default domains --> teleport.cluster.local and *.teleport.cluster.local when behind a reverse proxy like nginx? Does one always have to configure the certificates within the `https_keypairs` field?

**Comment by webvictim** [comment]
@abjoseph `teleport.cluster.local` is irrelevant here - that's just an internal SNI name that Teleport uses to refer to its own internal connections to the Teleport auth service.

Here's a working config that I use for putting Teleport behind [Caddy](https://caddyserver.com/):

`/etc/teleport.yaml`:
```yaml
version: v1
teleport:
  log:
    output: stderr
    severity: DEBUG
auth_service:
  enabled: yes
  cluster_name: teleport.example.com
  authentication:
    type: github
    second_factor: webauthn
    webauthn:
      rp_id: teleport.example.com
ssh_service:
  enabled: yes
  labels:
    type: node
proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:3080
  # public address which caddy hosts in front of Teleport
  public_addr: teleport.example.com:443
  ssh_public_addr: teleport.example.com:3023
  tunnel_public_addr: teleport.example.com:3024
  kube_public_addr: teleport.example.com:3026
```

`/etc/caddy/Caddyfile.d/teleport.conf`:
```
teleport.example.com, *.teleport.example.com {
    tls {
        dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN}
    }
    reverse_proxy https://localhost:3080 {
                transport http {
                        tls
                        tls_insecure_skip_verify
                }
        }
}
```

How it works:
- The DNS for `teleport.example.com` and `*.teleport.example.com` points to the public IP of the server
- Caddy listens externally for HTTPS traffic on port 443, and automatically fetches ACME certs for `teleport.example.com` and `*.teleport.example.com` using a DNS-01 challenge (Cloudflare is my DNS provider)
-  Caddy forwards any requests for either of these hosts to `https://localhost:3080`, which is the port for the web UI on Teleport's proxy service.
- As there are no `https_keypairs` configured, Teleport generates a self-signed certificate and serves the web UI using this certificate.
  -  Caddy ignores the self-signed cert, due to the `tls_insecure_skip_verify` in its config.
- Any requests for Teleport's SSH proxy (port 3023), SSH tunnel (port 3024) and Kubernetes proxy (port 3026) are sent to those ports, which are opened to the outside world to allow direct connections to each of those Teleport services outside of Caddy.

**Comment by abjoseph** [comment]
@webvictim Thank you for the thorough reply. Please see below my complete setup which is still not working when trying to register a node.

### teleport config --> `/etc/teleport.yaml`

```yaml
version: v1
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  #listen_addr: 0.0.0.0:3025
  cluster_name: teleport.example.com
  #authentication:
    #type: github
    #second_factor: webauthn
    #webauthn:
      #rp_id: teleport.example.com
  #public_addr: teleport.example.com:3025
  #proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: lan-net
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  #listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.example.com:443
  ssh_public_addr: teleport.example.com:3023
  tunnel_public_addr: teleport.example.com:3024
  #tunnel_listen_addr: 0.0.0.0:3024
```

### nginx config --> `teleport.example.conf`

```Nginx
server {
    listen                   443 ssl http2;

    server_name              teleport.example.com *.teleport.example.com;

    ssl_certificate          /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key      /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate  /etc/letsencrypt/live/example.com/fullchain.pem;

    include                  /etc/nginx/snippets/ssl.conf;

    location / {

        proxy_buffering      off;
        proxy_set_header     Host $host;
        proxy_set_header     X-Real-IP $remote_addr;
        proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header     X-Forwarded-Proto "https";

        # WebSocket support
        proxy_http_version   1.1;
        proxy_set_header     Upgrade $http_upgrade;
        proxy_set_header     Connection "upgrade";
        proxy_read_timeout   86400;

        proxy_pass           https://teleport.localdomain.net:3080;
    }
}
```

### Additional context:
After adding a new user with `tctl users add teleport-admin --roles=editor,access --logins=root,ubuntu` I'm able to login to the webui at https://teleport.example.com.

![image](https://user-images.githubusercontent.com/26844547/164946140-30224555-2314-4abf-a116-e88ed7a91419.png)

In the webui, I click the "Add Server" button in the top right corner and copy the command from the "Manually" tab.
e.g `teleport start --roles=node --token=9bed84d4c9ad70210f528962b14881cf --auth-server=teleport.example.com:443 `

![image](https://user-images.githubusercontent.com/26844547/164946080-d0ef4235-7ef6-432d-b7cb-b23a3cd83788.png)

When I go to the linux host (protected-resource) that I want to add as a node in teleport and run the above command, I get the below error:

```shell
root@rport:~# sudo teleport start \
> --roles=node \
> --auth-server=teleport.example.com:443  \
> --token=b289190e4c8c68f54ba5610a65578242 \
> --labels=env=lab-net

INFO             Generating new host UUID: e7091a70-29fd-421b-9259-7475351f4d9b. service/service.go:689
INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:395
INFO [PROC:1]    Node has obtained credentials to connect to the cluster. service/connect.go:429
ERRO [PROC:1]    "Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tGet \"https://teleport.cluster.local/v2/domain\": x509: certificate is valid for *.example.com, not 74656c65706f72742e6d616368696e656a61722e636f6d.teleport.cluster.local, Get \"https://teleport.cluster.local/v2/domain\": ssh: handshake failed: EOF." service/connect.go:86
```
