### ISSUE TITLE
Teleport cluster cannot renew letsencrypt cert with reverse tunneling enabled

### ISSUE THREAD

**Issue by ahelwer** [gravitational/teleport#9936]
### Description

**What happened**:

My teleport cluster has the proxy service enabled on port 3080, which as I understand it is necessary to support reverse tunneling. Here is the relevant config section:
```yaml
proxy_service:
  enabled: "yes"
  proxy_protocol: on
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport-proxy.hostname.com:3080
  https_keypairs: []
  acme:
    enabled: "yes"
    email: myemail@gmail.com
```
However, my cluster failed to renew its letsencrypt cert with the following error:
```
Original Error: *errors.errorString acme/autocert: unable to satisfy &#34;https://acme-v02.api.letsencrypt.org/acme/authz-v3/71841660120&#34; for domain &#34;teleport-proxy.hostname.com&#34;: no viable challenge type found
```
As found in https://github.com/gravitational/teleport/issues/5771 the proxy service needs to be on port 443 to support letsencrypt auto-renewal.

**What you expected to happen**:
I expected to be able to run my cluster in a configuration supporting reverse tunneling while also supporting automatic letsencrypt renewal.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a new Teleport cluster, originally hosting the web proxy on port 443; receive valid letsencrypt cert
2. Update the Teleport cluster to host the web proxy on port 3080
3. Wait until your letsencrypt cert expires

### Server Details
- Teleport version (run `teleport version`): Teleport v8.1.0 git:v8.1.0-0-g3dc269bef go1.17.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS (Focal Fossa)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Azure
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)
[log.txt](https://github.com/gravitational/teleport/files/7936502/log.txt)
